### ISSUE TITLE
[CI] Add Build for Ray Master

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#103]
In recent PR (#78) we removed dependency on ray master. Let's add it back for a separate build on ray master to test our code to see if it's future proof. 

Ray's master wheels are named to latest pypi version and on S3. (https://ray.readthedocs.io/en/latest/installation.html) 

Here's how it can be installed without hardcoded it:
- In a script, `pip install -U ray; python -c "import ray; print(ray.__version__)"`
- Pipe the output to format the wheel name, for example: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-{RAY_VERSION_NAME}-cp36-cp36m-manylinux1_x86_64.whl

We just need to run the test on ray master for py3.6 and linux.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
