### ISSUE TITLE
PythonFrameManager:: _partitions_cache never created

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#1030]
part of on-going work for #74 

Type checker errored at:
```
modin/modin/engines/python/pandas_on_python/frame/partition_manager.py
  41:29 - error: Cannot access member '_partitions_cache' for type 'PythonFrameManager'
  Member '_partitions_cache' is unknown
  40:47 - error: Cannot access member '_partitions_cache' for type 'PythonFrameManager'
  Member '_partitions_cache' is unknown
  59:29 - error: Cannot access member '_partitions_cache' for type 'PythonFrameManager'
  Member '_partitions_cache' is unknown
  58:46 - error: Cannot access member '_partitions_cache' for type 'PythonFrameManager'
  Member '_partitions_cache' is unknown
```

Additionally, after doing a grep of `_partitions_cache` over the codebase, it was never assigned.

https://github.com/modin-project/modin/blob/6aac82bc06d8fd57d603d11ca62a966973839610/modin/engines/python/pandas_on_python/frame/partition_manager.py#L40

Should it be removed?

**Comment by devin-petersohn** [comment]
Thanks @simon-mo, you are correct that it is a deprecated field. It hasn't been caught because our unit tests don't test the metadata (maybe they should) and the Python backend is strictly for debugging. It should be removed.

**Comment by simon-mo** [comment]
Can you advise on what in particular is ok to be removed?, PythonFrameManager or just the caching mechanism?

**Comment by devin-petersohn** [comment]
The `block_widths` and `block_lengths` are calculated elsewhere. They should be removed as was done in #721:

https://github.com/modin-project/modin/pull/721/files#diff-f030cc083716a25f1211475c41633d4bL24-L103
