### ISSUE TITLE
Unable to run code working properly with traditional pandas when importing dask modin

### ISSUE THREAD

**Issue by chris-ibrahim** [modin-project/modin#1031]
Hello, I'm currently trying to use modin to speed up file loadings in someone else's project I am resuming. 

I have been trying for a few days to get it work on my system and different environments. So, I don't know where to start but I am going to try to be as comprehensive as I can regarding the different approach I've tried to solve my issue.

### System information
- **OS Platform and Distribution**: Linux Ubuntu 18.04 / Windows 10
- **Modin installed from**: pip
- **Modin version**: 0.6.3
- **Python version**: 3.6.8

### Problem description

I first tried to install dask modin directly on windows and then I figured out it was not going to work that way after reading carefully the documentation on modin install on windows telling that the wsl is recommended. 

Then I tried to install it on a virtual machine Ubuntu 18.0.4. I followed the modin installation guide on Linux but it seems like there are still errors showing up whenever I tried to run my code.

Since my program worked fine on the last pandas release (0.25.3). I first thought maybe it is a python version issue which is not compatible with a modin version able to work on my environment. 

So I tried to test my code on every version of python compatible to the pandas currently used by modin (python 3.5.3, 3.6, 3.7, 3.8) and I am still getting the same type of errors that I've copied below.

Since I did not manage to get anything to work on Linux, I went back to windows and tried to update modin package, as I saw a new version had been released. When using this new version, I am now get the following errors.

### Source code / logs

* On Windows 10 Ubuntu WSL 18.04 with Python 3.7 VENV
* On Windows 10 with Python 3.5 VENV
* On Windows 10 with Python 3.6 VENV
* On Windows 10 with Python 3.7 VENV
* On Windows 10 with Python 3.8 VENV
* On Ubuntu 18.04 with Python 3.6 VENV
* On Ubuntu 18.04 with Python 3.7 VENV
[Error python 3-5 windows.txt](https://github.com/modin-project/modin/files/4099025/Error.python.3-5.windows.txt)
[Error python 3-6 windows.txt](https://github.com/modin-project/modin/files/4099026/Error.python.3-6.windows.txt)
[Error python 3-7 windows WSL 18.04.txt](https://github.com/modin-project/modin/files/4099027/Error.python.3-7.windows.WSL.18.04.txt)
[Error python 3-7 windows.txt](https://github.com/modin-project/modin/files/4099028/Error.python.3-7.windows.txt)
[Error on python 3-6 VM ubuntu 18-04.txt](https://github.com/modin-project/modin/files/4099029/Error.on.python.3-6.VM.ubuntu.18-04.txt)
[Error on python 3-7 VM ubuntu 18-04.txt](https://github.com/modin-project/modin/files/4099030/Error.on.python.3-7.VM.ubuntu.18-04.txt)
[Error on python 3-8 windows.txt](https://github.com/modin-project/modin/files/4099031/Error.on.python.3-8.windows.txt)

**Comment by devin-petersohn** [comment]
Thanks @chris-ibrahim for the comprehensive issue!

Some of these pytest outputs have `KeyBoardInterrupt` in them. The warnings and errors at the end of the workflow don't affect the correctness of the run, they are just outputs from Ray/Dask related to shutting down the engine.

I will dig into the other errors. I may have to ask for more information as I investigate, and I'd like to get these issues resolved as quickly as I can. Thanks again for posting the detailed thread! I will keep you updated via this thread.

**Comment by chris-ibrahim** [comment]
Yes there are few KeyBoardInterrupts. Some of the tests freeze at the execution, so I simply ended them.

Thanks for your help @devin-petersohn, and don't hesitate to ask for more information.

**Comment by devin-petersohn** [comment]
Since it's the beginning of the university semester (I'm a PhD student), it will take some time as I am teaching this semester and it's always a little hectic at the start. I should be able to work on this tomorrow or the weekend. Thanks so much for your patience and willingness to provide more information as needed!

**Comment by devin-petersohn** [comment]
Update: I'm fairly confident I have found the source of the issue and I will get the fix in as soon as I can. It involves cases where Dask is serializing the entire package to run a single function. I will have to work around this and it will be a fairly large change.

**Comment by chris-ibrahim** [comment]
Alright, I understand. As for me, I paused this part of the project, just take the time you need.
Thank you so much and I hope you will manage to fix the issue.

**Comment by devin-petersohn** [comment]
I made some good progress on this today, I'm hoping to put the PR in later today. I want to get this documented in Dask as well so that others can benefit from the work I put in 😄.
