### ISSUE TITLE
[bug] to_datetime in modin pandas converts to datetime index

### ISSUE THREAD

**Issue by iamdbestjoy** [modin-project/modin#1034]
modin pandas dataframe creates datetime index from to_datetime command where as the original pandas to_datetime command returns actually a datetime.
![modin bug](https://user-images.githubusercontent.com/10412507/73218751-6e5b1800-410f-11ea-9554-d325bd8cd0a4.JPG)

**Comment by devin-petersohn** [comment]
Hi @iamdbestjoy thanks for posting this report!

We are defaulting to pandas in this case, but the conversion back to a Modin object is not correct. I also noticed that there's no warning for defaulting to pandas. It will be a straightforward fix, thanks again for reporting!

As a side note, over the next couple of releases I will be spending time implementing more comprehensive datetime support (including `pd.to_datetime`). There are over 50 methods to be implemented for `dt`, but they are all relatively straightforward.
