### ISSUE TITLE
Capitalization of "S" in "S3://" results in inconsistent behaviors when reading from S3 path

### ISSUE THREAD

**Issue by youngstone** [modin-project/modin#1037]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.7.0
- **Python version**: 3.6.8
- **Exact command to reproduce**: 

### Describe the problem

Reading data from a S3 path, e.g. `read_csv`, `read_json`, behaves differently based on the capitalization of "S" in the path. See below code example.

### Source code / logs

```
import pandas as pd
import ray
import modin.pandas as mpd

filepath = "s3://my-bucket/data/traffic.json"
filepath_2 = "s3://my-bucket/data/BikeSharingDaily.csv"
filepath_3 = "S3://my-bucket/data/BikeSharingDaily.csv"

# working
df_native = pd.read_json(filepath, lines=True)
df_native_2 = pd.read_csv(filepath_2)

# not working (FileNotFoundError: [Errno 2] No such file or directory: 's3://my-bucket/data/traffic.json')
df_modin = mpd.read_json(filepath, lines=True)

# working (but it prints, defaulting to pandas implementation)
df_modin_2 = mpd.read_csv(filepath_2)

# working (no additional print)
df_modin_3 = mpd.read_csv(filepath_3)
```

**Comment by devin-petersohn** [comment]
Hi @youngstone, thanks for the report!

This is a bit of a silly bug, and we weren't testing for `S3://`, only `s3://`, so the tests did not catch it.

The offending line is here: https://github.com/modin-project/modin/blob/6aac82bc06d8fd57d603d11ca62a966973839610/modin/engines/base/io/file_reader.py#L4

Thanks again for reporting!
