### ISSUE TITLE
Unable to load modin.pandas with Dask 2.10.0

### ISSUE THREAD

**Issue by rewreu** [modin-project/modin#1043]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS, 10.14.6
- **Modin installed from (source or binary)**:
binary, 2.10.0
- **Modin version**:
0.7.0
- **Python version**:
3.6
- **Exact command to reproduce**:
import modin.pandas as pd

### Describe the problem

>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/modin/__init__.py", line 69, in <module>
    __execution_engine__ = get_execution_engine()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/modin/__init__.py", line 58, in get_execution_engine
    "Please `pip install modin[dask]` to install compatible Dask version."
ImportError: Please `pip install modin[dask]` to install compatible Dask version.

I opened up the `__init__.py` file, in line 55: 
`or str(distributed.__version__) < "2.3.2"`, this returns **True**  even when `distributed.__version__ ==2.10.0`

**Comment by devin-petersohn** [comment]
Hi @rewreu thanks for posting!

This is a bug. I will get this fixed, but in the meantime, the workaround is as follows:

```python
import os
os.environ["MODIN_ENGINE"] = "dask"
import modin.pandas as pd
```

This will ignore the checks for version.
