### ISSUE TITLE
Modin incompatible with joblib memory

### ISSUE THREAD

**Issue by jontis** [modin-project/modin#1047]
Modin version 0.7.0

Trying to cache functions with decorator
@memory.cache

crashes with:
...
...
  return object.__getattribute__(self, item)
  File "/home/jonathan/miniconda3/envs/tsfresh/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 151, in _get_columns
    return self._query_compiler.columns
RecursionError: maximum recursion depth exceeded

This is a serious issue to us. 
We do data science with pandas and a lot of the functions takes a long time to run so we cache results with joblib memory. 
It would be fantastic to use modin to speed up pandas to get functions to run faster the first time and then use the cached result.

However, modin does not work with joblib and that forces recalculating the function every time.
This might be a duplicate of issue 672, as I believe that joblib pickles parameters and results:
https://github.com/modin-project/modin/issues/672

**Comment by devin-petersohn** [comment]
Hi @jontis, thanks for posting!

This is related to #672. The `RecursionError` comes from the attempt to pickle the Modin object. I will escalate this, but please understand we're a very small team.

Alternatively, I'm in the process of implementing a system-wide cache with some query planning under the hood. This would benefit the same use-case where the same call would just return the cached object. This is a part of my PhD thesis research into optimizing these types of use-cases. It's early, so I don't have a good time-frame for when this work will get merged into the master.

**Comment by jontis** [comment]
No worries. I don't expect people to do work just because I want them too :-)

I am merely stating that getting this particular issue sorted would make Modin a lot more useful to my team, and probably a lot of others with similar usecases. Continuing discussion in the main issue.

**Comment by devin-petersohn** [comment]
In that case, I'll close this as duplicate so we can continue discussion at #672.
