### ISSUE TITLE
read_parquet reading only subset of multi-file Parquet directory

### ISSUE THREAD

**Issue by guidoman** [modin-project/modin#1051]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15.3
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.7.0
- **Python version**: 3.7.6
- **Exact command to reproduce**:

### Describe the problem

I have a set of Parquet files inside a directory "myparquet" on my local filesystem (copied from HDFS). Files have the following naming pattern:
```
part-00000-d50dbe9c-3b97-4f05-8355-6a01a98c8fef-c000.snappy.parquet
...
part-00071-d50dbe9c-3b97-4f05-8355-6a01a98c8fef-c000.snappy.parquet
```
Pandas by default reads all Parquet files correctly into a DataFrame, while it seems that the Modin implementation reads only a subset (maybe only a single file).

**Note**: I'm using Ray, not sure if this matters.

**Example code**:

```
import modin.pandas as pd
import pandas
import ray

ray.init()

if __name__ == '__main__':
    modin_df = pd.read_parquet('myparquet')
    pandas_df = pandas.read_parquet('myparquet')
    print(f'Modin DF len = {len(modin_df)}')
    print(f'Pandas DF len = {len(pandas_df)}')
```

The **output** will be something like the following:
```
Modin DF len = 2743
Pandas DF len = 132493
```

**Comment by devin-petersohn** [comment]
Hi @guidoman thanks for posting!

This may be a regression introduced by #955. We test this use-case, but it looks like it's still not reading all of the part files in your case. Do you have an example file you can share? I'll try to reproduce this, but it would definitely help if you had a file that reproduced this. Thanks again for reporting!

**Comment by guidoman** [comment]
[myparquet.zip](https://github.com/modin-project/modin/files/4172110/myparquet.zip)
