### ISSUE TITLE
pd.rename() is failing to rename columns

### ISSUE THREAD

**Issue by KevOBrien** [modin-project/modin#1056]
The following code snippet fails to rename the columns 'a' and 'b' to 'x' and 'y'. Changing to regular pandas works fine, and also not doing the operation inplace results in the same

```
import modin.pandas as pd

print(pd.__version__)

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6]
})

df.rename({'a': 'x', 'b': 'y'}, axis=1, inplace=True)

print(df)
```

Output:

```
0.6.3
UserWarning: Distributing <class 'dict'> object. This may take some time.
   a  b
0  1  4
1  2  5
2  3  6

```
Also, I am using modin==0.7.0, but it is printing version 0.6.3.

**Comment by KevOBrien** [comment]
It does work if I pass the dict to the `columns` parameter, instead of specifying `mapper` and `axis`.

**Comment by jpadillo** [comment]
Try specifying the axis as either index or column like so

df.rename({'a': 'x', 'b': 'y'}, axis='column', inplace=True)
