### ISSUE TITLE
Binary operator throwing a ValueError for cases that Pandas accepts

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1059]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.15.3
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.7.0
- **Python version**: 3.7.6
- **Exact command to reproduce**: See below

### Describe the problem

Adding a series to a dataframe throws a ValueError. The exact same case works fine in Pandas. All binary operators have this issue.

### Source code / logs

Here is the script to reproduce the issue:

```
import pandas as pd
import modin.pandas as mpd

df = pd.DataFrame({"col1": [1, 2, 3], "col2" : [4,5,6] })
s = pd.Series([1], index=['col1'])

mdf = mpd.DataFrame(df)
ms = mpd.Series(s)

print("df + s: ")
print(df + s)
print("mdf + ms: ")
print(mdf + ms)
```

Running it will hit the following assertion:

```
Traceback (most recent call last):
  File "bug.py", line 13, in <module>
    print(mdf + ms)
  File "/Users/wonchanl/Workspace/modinv/modin/pandas/dataframe.py", line 2084, in __add__
    return self.add(other, axis=axis, level=level, fill_value=fill_value)
  File "/Users/wonchanl/Workspace/modinv/modin/pandas/dataframe.py", line 480, in add
    other, axis=axis, level=level, fill_value=fill_value
  File "/Users/wonchanl/Workspace/modinv/modin/pandas/base.py", line 335, in add
    "add", other, axis=axis, level=level, fill_value=fill_value
  File "/Users/wonchanl/Workspace/modinv/modin/pandas/base.py", line 206, in _binary_op
    other = self._validate_other(other, axis, numeric_or_object_only=True)
  File "/Users/wonchanl/Workspace/modinv/modin/pandas/base.py", line 136, in _validate_other
    len(self._query_compiler.columns), len(other)
ValueError: Unable to coerce to Series, length must be 2: given 1
```

The Pandas implementation produces the following result:

```
df + s: 
   col1  col2
0   2.0   NaN
1   3.0   NaN
2   4.0   NaN
```

The problem disappears when the length of `ms` is exactly 2.

**Comment by devin-petersohn** [comment]
Thanks @magnatelee! I believe what is happening here is that the join part of the binary operation isn't handling the `Series` case properly when it needs to be applied along the columns.

Using a `DataFrame`, it works (though it doesn't apply to the whole column), so it's a matter of correctly joining the columns.

**Comment by devin-petersohn** [comment]
I put a temporary fix in for this for the next release since it's a bug.
