### ISSUE TITLE
Binary operators should stop converting Series operands back to Pandas

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1060]
### Describe the problem

The frontend code for binary operators should stop converting a series to Pandas before passing it to the query compiler. It should rather let the query compiler choose how to handle such cases. Here are some of the functions that need to be fixed (I only listed four as there are quite a few):

https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L477-L478
https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L598-L599
https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L684-L685
https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L731-L732

**Comment by devin-petersohn** [comment]
Thanks @magnatelee, this is residual from when the front end was integrated closely into the backend.

**Comment by magnatelee** [comment]
One thing to note is that once we remove those `to_pandas` calls, it's going to be ugly to tell whether a query compiler represents a series or a dataframe with a single column. This difference actually matters as binary operators basically ignore the `axis` value when operands are all dataframes, whereas `axis` determines how a RHS is treated when it's a series, as demonstrated in this example:

```
df = pd.DataFrame({"c1" : [1,2,3], "c2" : [4,5,6]})
df2 = pd.DataFrame({"c1" : [7,8,9]})
print(df.add(df2, axis=1))
#    c1  c2
# 0   8 NaN
# 1  10 NaN
# 2  12 NaN
print(df.add(df2, axis=0))
#    c1  c2
# 0   8 NaN
# 1  10 NaN
# 2  12 NaN
print(df.add(df["c1"], axis=1))
#    c1  c2   0   1   2
# 0 NaN NaN NaN NaN NaN
# 1 NaN NaN NaN NaN NaN
# 2 NaN NaN NaN NaN NaN
print(df.add(df["c1"], axis=0))
#    c1  c2
# 0   2   5
# 1   4   7
# 2   6   9
```

I'm currently relying on the internal convention that a series has only one column named `__reduced__`, but this "interface" seems to be a bit brittle.

**Comment by devin-petersohn** [comment]
> it's going to be ugly to tell whether a query compiler represents a series or a dataframe with a single column

Yes, I was anticipating this. From the API, we can potentially pass a `broadcast` parameter to the `query_compiler`. This still leaks information, but it's better than what we have. Do you have an idea here?

Side note: `__reduced__` is for Series objects where `Series.name is None`. Having `None` query compiler's columns creates some issues with some of the operators, so I created that internal representation to distinguish between `None` and everything else. It's not ideal, but having a string there is better than `None`.

**Comment by magnatelee** [comment]
Adding a `broadcast` parameter sounds good, though I'll need to look at other functions to see if `broadcast` also makes sense for them. 

> Side note: __reduced__ is for Series objects where Series.name is None. Having None query compiler's columns creates some issues with some of the operators, so I created that internal representation to distinguish between None and everything else. It's not ideal, but having a string there is better than None.

Thanks for clarification. I'll remove any access to this internal representation from my code once a `broadcast` parameter, or something to that effect, is added.
