### ISSUE TITLE
`_getitem` materializing boolean indexers

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1061]
### Describe the problem
This issue is similar to #1060. The frontend code is materializing boolean indexers, which is not only bad for performance but also limits the size of problems that the system can handle.

Note that removing this materialization step will make the code unable to rely on `is_bool_indexer` for checking if the `key` is a boolean indexer, and Modin should provide an equivalent check whose implementation should be provided by the backend.

### Source code / logs
https://github.com/modin-project/modin/blob/master/modin/pandas/series.py#L169
https://github.com/modin-project/modin/blob/master/modin/pandas/series.py#L170

**Comment by devin-petersohn** [comment]
Thanks @magnatelee, this is a good suggestion.

**Comment by mvashishtha** [comment]
This sounds like #4753. There are some other kinds of bool `__getitem__` not covered by that PR, but we can open separate issues for those.
