### ISSUE TITLE
`__setitem__` always falling back to Pandas when the key is not a string

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1063]
### Describe the problem

The `__setitem__` always falls back to Pandas when the key is not a string even when the query compiler is perfectly capable of handling cases where the key is a list of strings.

### Source code / logs
https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L1986-L1997

**Comment by devin-petersohn** [comment]
Thanks @magnatelee, we should fix this as it affects performance as well.

**Comment by itamarst** [comment]
Will try to figure this out.

**Comment by itamarst** [comment]
Can't find any reference documentation for `DataFrame.__setitem__`  in Pandas docs. Though I'm starting to learn the documentation never actually covers the full API...

The code is more useful: https://github.com/pandas-dev/pandas/blob/385a2ca42ae17ac5457901e8718b3f23263d86ad/pandas/core/frame.py#L3026 (master as of today).

It seems the following cases need to be handled (suggesting this is really multiple issues):

* [ ] Key is a boolean DataFrame or 2-dimensionial array (`df[df > df2] = 0` is example in Pandas code).
* [ ] The key is a slice.
* [ ] The key is a function which generates a new key given the DataFrame as input.
* [ ] The key is a boolean indexer.
* [ ] The key is a list-like.

**Comment by itamarst** [comment]
Note that as I just discovered while working on #1898, some usage patterns don't fallback to Pandas, they just break outright.

**Comment by mvashishtha** [comment]
All the cases @itamarst mentions seem to work at version c9fc326e3a02f2090c58f6e233aac29ddd651bea.
