### ISSUE TITLE
Query compiler's interface for unary operators and scalar reductions is inconsistent with that for binary operators

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1064]
### Describe the problem

Currently, there are no query compiler calls for unary operators and scalar reductions that are equivalent to `binary_op` for binary operators. I think the API should be made consistent so that either binary operators have their own calls in the query compiler or unary operators and scalar reductions have a unified interface. 

(Just to clarify terms, a unary operator is an operator that is applied individually to values in a series, and it produces another series of the same shape: `abs`, `astype`, `isna`, etc.. A scalar reduction is an operation on a series that produces a single value at the end: `mean`, `min`, `max`, etc..)

### Source code / logs

https://github.com/modin-project/modin/blob/master/modin/backends/base/query_compiler.py#L101
https://github.com/modin-project/modin/blob/master/modin/backends/base/query_compiler.py#L255-L256
https://github.com/modin-project/modin/blob/master/modin/backends/base/query_compiler.py#L219-L225

**Comment by devin-petersohn** [comment]
Thanks @magnatelee, I believe the `binary_op` should probably be enumerated in the `query_compiler`. I prefer this to passing around strings that identify what function should be run.
