### ISSUE TITLE
New API: `unique` for Series

### ISSUE THREAD

**Issue by em-watkins** [modin-project/modin#1065]
currently defaults to pandas implementation

**Comment by devin-petersohn** [comment]
Hi @em-watkins, thanks for posting!

`unique` returns an `ndarray`, so in the current implementation it'll probably be just as fast when it's implemented because we don't currently have a distributed `ndarray`. Is this something that takes an extremely long time in your workflows?

**Comment by aregm** [comment]
Implemented via #1331
