### ISSUE TITLE
Column indexing is buggy when the dataframe has multiple columns having the same name

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1069]
### Describe the problem

When a dataframe `df` looks like this:
```
   c1  c2  c1
0   1   4   7
1   2   5   8
2   3   6   9
```

`df.c1` should return a dataframe where the column `c1` appears twice. However, with Modin I got the following series as the output:

```
c1    1
c1    7
Name: 0, dtype: int64
```

The root cause is that `DataFrame._getitem_column` is blindly converting the query compiler output to a series even though the output may have more than one column.

### Source code / logs

https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L1911

**Comment by devin-petersohn** [comment]
Thanks @magnatelee for the report, this is a bug as you say.

The difficulty with this is that we somehow need to communicate from the layers below the API what the return type is. Either we need to check the `len(_query_compiler.columns)` or we need to check the number of times the `key` is in the columns from the API layer.

Alternatively, and possibly most correctly, we could `squeeze` before returning. What do you think about this?

**Comment by magnatelee** [comment]
Calling `squeeze` sounds like the right thing to me as well, but I start to feel that forgetting whether a query compiler represents a series or a dataframe makes certain things somewhat difficult to handle (see my comment here: https://github.com/modin-project/modin/issues/1060#issuecomment-584269263). Would it be a bad idea to just remember this fact somewhere in the query compiler?

**Comment by devin-petersohn** [comment]
> Would it be a bad idea to just remember this fact somewhere in the query compiler?

I would have to think about this. I'm not entirely sure it's the best approach because it overfits to the pandas API, and we will want to integrate with other dataframe APIs in the future. I do see the issues related to this, though, because somehow we need to signal to the query compiler whether to broadcast a column to all columns or just do a join.
