### ISSUE TITLE
Update Ray version to 0.8.3

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1102]
Blocked on the release of ray 0.8.3

We cannot upgrade to 0.8.2 because of issue https://github.com/ray-project/ray/issues/7296.

**Comment by foxel** [comment]
What except of changing the dependency might be needed here?

**Comment by devin-petersohn** [comment]
@foxel Ray has not yet released 0.8.3: https://github.com/ray-project/ray/releases

**Comment by simon-mo** [comment]
Yes, it is planned for next week the week of March 22.

**Comment by devin-petersohn** [comment]
Thanks @simon-mo looking forward to it!

**Comment by gshimansky** [comment]
Ray 0.8.3 is out now.
