### ISSUE TITLE
unable to read json files using modin getting an error  "cannot use a string pattern on a bytes-like object"

### ISSUE THREAD

**Issue by shivatharun** [modin-project/modin#1105]
import modin.pandas as mpd

print([pd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in  data_objects])

ERROR: cannot use a string pattern on a bytes-like object

Note: data_objects are aws s3 json file keys

its working fine when using with pandas.

**Comment by devin-petersohn** [comment]
Hi @shivatharun, thanks for posting!

I need a bit more information before I can reproduce and diagnose this.

- What is your OS and version?
- What is your Python version?
- What modin version are you running on?
- Please post the full traceback of the error.
- Please provide a minimal example if possible (without the list comprehension and show what the variables represent more explicitly).
- Ideally show something I can use to reproduce the error.

Thanks again for posting, I will start diagnosing this once we have enough information.

**Comment by shivatharun** [comment]
**What is your OS and version?**
       CentOS and version 7
**What is your Python version?**
       Python 3.6.8
**What modin version are you running on?** 
      modin version =0.7.0

-   I'm trying to read all the files which are stored in AWS S3 and append it to single dataframe.

- I am passing explicit date as parameter(lets say "20200226")  to run, my regex expression will return all the file keys which are 20200226 and will store in data_objects

- data_objects is list of aws s3 json file keys as below syntax

data_objects = [bucketname/folder1=20200226/folder2/folder3/folder4/folder5/jsonfile1,
bucketname/folder1=20200226/folder2/folder3/folder4/folder5/jsonfile2,
bucketname/folder1=20200226/folder2/folder3/folder4/folder5/jsonfile3]

**My code is below:**

import modin.pandas as mpd
data = mpd.concat(
                [mpd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in
                 data_objects], ignore_index=True, sort=False)

**ERROR**

Traceback (most recent call last):
  File "py.py", line 47, in <module>
    data = mpd.concat([mpd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in data_objects], ignore_index=True, sort=False)
  File "py.py", line 47, in <listcomp>
    data = mpd.concat([mpd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in data_objects], ignore_index=True, sort=False)
  File "/usr/local/lib/python3.6/site-packages/modin/pandas/io.py", line 142, in read_json
    return DataFrame(query_compiler=BaseFactory.read_json(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/modin/data_management/factories.py", line 60, in read_json
    return cls._determine_engine()._read_json(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/modin/data_management/factories.py", line 64, in _read_json
    return cls.io_cls.read_json(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/modin/engines/base/io/text/json_reader.py", line 11, in read
    path_or_buf = cls.get_path(path_or_buf)
  File "/usr/local/lib/python3.6/site-packages/modin/engines/base/io/file_reader.py", line 15, in get_path
    if S3_ADDRESS_REGEX.search(file_path):
TypeError: cannot use a string pattern on a bytes-like object

**The same code is running fine when i'm using pandas**

**Comment by mvashishtha** [comment]
@shivatharun it seems you are trying to read a `bytes` object with `read_json`. I say this because [`s3.Object.get`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Object.get) returns a response whose `'Body'` contains is a `botocore.response.StreamingBody`, whose `read` method [returns bytes](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/response.html).

pandas can't read json bytes. e.g. in pandas `pd.read_json(b'{"a": [4]}')` throws `TypeError: Expected file path name or file-like object, got <class 'bytes'> type` whereas  `pd.read_json('{"a": [4]}')` works. Modin version b09dd424e95830e6a19a631741eb8381b9020ee5 throws the same error, so I don't think there's anything to fix here.
