### ISSUE TITLE
Sleeping inside an applymap function

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#1112]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.14.6
- **Modin version** (`modin.__version__`): 0.7.0+27.gd1b3f70
- **Python version**: 3.6
- **Code we can use to reproduce**:

```
def sleepy(df):
    print("AAA")
    time.sleep(0.001)
    return df+2
modin_df = modin_df.applymap(sleepy)
parts = modin_df._query_compiler._modin_frame._partitions
oids = []
for row in parts:
    for block in row:
        oids.append(block.oid)
ray.get(oids)
```

### Describe the problem
The above code runs indefinitely. However, redefining `sleepy` to below fixes the issue.
```
def sleepy(df):
    start = time.time()
    while False:
        if time.time() > start + sleep_time:
            break
    return df
```

I think this issue is caused by how pandas, time.sleep(), modin, and ray handle things when we do an applymap.

**Comment by devin-petersohn** [comment]
Thanks @williamma12 for reporting! We should investigate this. There may be some weird things going on here with how we actually deploy functions and their interaction with `time.sleep`. It may reveal some interesting performance enhancements we can do.

**Comment by jeffreykennethli** [comment]
@williamma12 I tried rerunning this script on the latest Modin and was not able to reproduce it i.e. it ran in normal time. Could you try to reproduce it? As a minor note, in the redefined `sleepy(df)`, I believe it should say `while True:`

**Comment by mvashishtha** [comment]
Closing this as stale, given @jeffreykennethli 's comment.
