### ISSUE TITLE
Assigning numpy.ndarray to a column produces an empty DataFrame

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1118]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.1+3.ga8ff01a

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import numpy as np
#import pandas as pd
import ray
ray.init(huge_pages=False, plasma_directory="/localdisk/gashiman/plasma", memory=1024*1024*1024*200, object_store_memory=1024*1024*1024*200)
import modin.pandas as pd

df = pd.DataFrame(columns=['id', 'max_speed', 'health'])
print(df)

a = np.array(['one', 'two'])
print(type(a))
df['id'] = a
print(df)
```

### Describe the problem

There is a difference between Pandas and Modin behavior. After assignment in Pandas DataFrame has N row where N is the length of assigned array. In Modin assignment produces a DataFrame that is still empty.

### Source code / logs

So in Pandas I am getting this output

```
Empty DataFrame
Columns: [id, max_speed, health]
Index: []
<class 'numpy.ndarray'>
    id max_speed health
0  one       NaN    NaN
1  two       NaN    NaN
```
while on Modin I get this
```
2020-02-28 14:22:55,644 INFO resource_spec.py:216 -- Starting Ray with 200.0 GiB memory available for workers and up to 200.0 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-28 14:22:55,937 WARNING services.py:1365 -- WARNING: object_store_memory is not verified when plasma_directory is set.
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
Empty DataFrame
Columns: [id, max_speed, health]
Index: []
<class 'numpy.ndarray'>
UserWarning: Distributing <class 'dict'> object. This may take some time.
Empty DataFrame
Columns: [id, max_speed, health]
Index: []
```

**Comment by devin-petersohn** [comment]
Thanks @gshimansky, this is a problem. I think it comes from how we handle empty dataframes, but I'll need to dig further to get a clear picture.

**Comment by gshimansky** [comment]
This only happens if I use numpy.ndarray in assignment. If I use a list it works exactly like Pandas does.
