### ISSUE TITLE
DataFrame.prod after transpose on Windows results in incorrect result

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1119]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows only
- **Modin version** (`modin.__version__`): 0.7.1+4.ga39d66a
- **Python version**: All
- **Code we can use to reproduce**: <Testing>

### Describe the problem

Recently with #1081, a new behavior has emerged caused by updating pandas. For `DataFrame.prod` in Windows, pytest will generate incorrect numbers for `df.T.prod`. This can be reproduced by running the tests after removing the `@pytest.markskipif` command on these lines: 

https://github.com/modin-project/modin/blob/a39d66aa105547cbdb67c8c462f2b587fe8b5402/modin/pandas/test/test_dataframe.py#L3214-L3217

https://github.com/modin-project/modin/blob/a39d66aa105547cbdb67c8c462f2b587fe8b5402/modin/pandas/test/test_dataframe.py#L3269-L3272

Note that this is only happening on `prod` and on Windows.

**Comment by vnlitvinov** [comment]
@devin-petersohn are you sure this is fixed? I see the same issue hitting CI, for example here: https://github.com/modin-project/modin/pull/1801/checks?check_run_id=908354983

**Comment by devin-petersohn** [comment]
I am not sure. There were some CI issues yesterday so #1801 may have been merged by mistake.

**Comment by devin-petersohn** [comment]
Reverted commit.

**Comment by mvashishtha** [comment]
Looks like we're no longer skipping the `prod` test even in the transposed cases: https://github.com/modin-project/modin/blob/35782883efd7e22f8e29a7c9887a4453adabf783/modin/pandas/test/dataframe/test_reduce.py#L294

So I'll close this issue.
