### ISSUE TITLE
Connect CI (GitHub Actions) to internal infra 

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1120]
### Describe the problem

Explore connecting TeamCity to GitHub Actions

**Comment by gshimansky** [comment]
TeamCity CI was added to modin-project and it is executed on new pull requests. There is one problem that build logs are located on a server not accessible from the public Internet.

**Comment by gshimansky** [comment]
TeamCity command scripts were updated with the following construct `(... commands ...) |& tee 
enginename_tests.log`
