### ISSUE TITLE
Parallelized pd.read_html()

### ISSUE THREAD

**Issue by klamike** [modin-project/modin#1127]
In the modin docs, read_html is marked as Default to Pandas. 

Is parallelizing read_html on the table? If not, what about the format means it cannot be processed in parallel?

**Comment by devin-petersohn** [comment]
Hi @klamike thanks for the request!

`read_html` can be difficult to parallelize, are you reading an extraordinarily large file? Everything is on the table 😄, but it is a matter of priority based on what the expected speedup would be. At a certain point the network could end up being slower than the parsing of the file, so parallelism would not particularly help in that case. Do you have an example file that we can use to evaluate expected speedup?

**Comment by devin-petersohn** [comment]
Closing to track #1296.
