### ISSUE TITLE
Initial integration of Omniscidb engine for Modin

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1129]
### Describe the feature

Omniscidb (https://github.com/omnisci/omniscidb) is "an open source SQL-based, relational, columnar database engine that leverages the full performance and parallelism of modern hardware (both CPUs and GPUs) to enable querying of multi-billion row datasets in milliseconds, without the need for indexing, pre-aggregation, or downsampling."

This can be implemented as a query compiler layer. Since it is a relational system, some things will not work out of the box.

cc @alexbaden, @aregm

**Comment by anmyachev** [comment]
Done in #2079
