### ISSUE TITLE
Program shutdown when change from pandas to MODIN.

### ISSUE THREAD

**Issue by wsf1990** [modin-project/modin#1141]
I change the lib from pandas to modin by change the import to :
```
import modin.pandas as pd
```
But my code can't startup,and send me this error:
```
E0316 23:22:19.686399431    2993 completion_queue.cc:1043]   Completion queue next failed: {"created":"@1584372139.686388489","description":"pollset_work","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/ev_epollex_linux.cc","file_line":317,"referenced_errors":[{"created":"@1584372139.686388063","description":"Bad file descriptor","errno":9,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/ev_epollex_linux.cc","file_line":945,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}Killed
```
I even not know does this was occurred by MODIN.I'm using latest modin which version is 0.7.2.

**Comment by devin-petersohn** [comment]
@wsf1990 thanks for posting!

Can you try the following to narrow down the issue:

```python
import ray
ray.init()
```

If this works, can I know your Python version and OS?

**Comment by wsf1990** [comment]
Yes, This works and print a log:
```
resource_spec.py:216 -- Starting Ray with * GiB memory available for workers and up to * GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
``` 
I'm using python 3.7 and ubuntu 18.04.
For more,If I use modin in a django project works well, this just occurred on a multiprocessing project.

**Comment by devin-petersohn** [comment]
Thanks for the additional information @wsf1990. This is a multiprocessing issue, at the moment Modin object cannot be pickled: #672. We have plans to support this in the future. In the issue linked there should be a temporary workaround until we can get this resolved. There are things in the API layer that are not able to be pickled at the moment.

Closing as duplicate, please direct any further questions related to multiprocessing and pickling to the issue #672. If you have another question or issue feel free to open a new issue. Thanks again for reporting and please let me know if the workaround works for you!
