### ISSUE TITLE
cannot import name 'UInt8Dtype'

### ISSUE THREAD

**Issue by alexanu** [modin-project/modin#1145]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.7.2
- **Python version**: 3.6.5 64-bit via Anaconda
- **Code we can use to reproduce**: 

### Describe the problem
I've managed to install modin using Conda Prompt: pip install modin[dask]
However, the next step "import modin.pandas as pd" delivers this Error Message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\modin\pandas\__init__.py in ()
     11     )
     12 
---> 13 from pandas import (
     14     eval,
     15     unique,

ImportError: cannot import name 'UInt8Dtype'

**Comment by devin-petersohn** [comment]
Hi @alexanu thanks for the report!

What does `pandas.__version__` show for you? We recently updated to pandas 1.0 and that `UInt8Dtype` was added in that version.

**Comment by devin-petersohn** [comment]
Closing this. Please reopen the issue if this has not been solved.
