### ISSUE TITLE
pandas groupby apply inconsistent when by is list of columns

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1148]
This requires further investigation before an issue should be opened in pandas. Documented in tests here:

https://github.com/modin-project/modin/blob/master/modin/pandas/test/test_groupby.py#L149-L155

This behavior is different inside and outside of pytest. We need to check to see if any of the previous groupby calls are changing the `apply` output.

**Comment by mvashishtha** [comment]
Link is stale, so I can't tell what this issue is referring to now. I can't find a comment about this in the groupby test, so I'm closing this issue for now.
