### ISSUE TITLE
Modin (0.7.2) allows `astype('categorical')` but produces `object` as a result?

### ISSUE THREAD

**Issue by ianozsvald** [modin-project/modin#1153]
### System information
- **Linux Mint 19.3**
- **Modin version 0.7.2** (`modin.__version__`)
- **pandas 1.0.1**
- **Python version 3.7**

### Describe the problem
I'm not clear if the Categorical dtype is supported, Modin seems to use `object` rather than `category` `dtype` in some reports.

### Source code / logs

Below I make a DataFrame (Pandas and Modin) with 1 million 'a' and 1 million 'b' in a list, then make a new Series `astype('categorical')`.

In the Modin example we get two `object` columns for `info()`, in the Pandas example I get 1 `object` and 1 `categorical`. Should `categorical` be supported for Modin?

Asking for the `dtype` for the categorical column does report a categorical result.

Example using Pandas:

```
df_cat = pd.DataFrame({'items': ['a'] * 1_000_000 + ['b'] * 1_000_000})
df_cat['items_cat'] = df_cat['items'].astype('category')
df_cat.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 2 columns):
 #   Column     Dtype   
---  ------     -----   
 0   items      object  
 1   items_cat  category
dtypes: category(1), object(1)
memory usage: 17.2+ MB
```

Same example using Modin:
```
import modin.pandas as mdpd
df_md_cat = mdpd.DataFrame({'items': ['a'] * 1_000_000 + ['b'] * 1_000_000})
df_md_cat['items_cat'] = df_md_cat['items'].astype('category')

df_md_cat['items_cat'].dtype
CategoricalDtype(categories=['a', 'b'], ordered=False)

df_md_cat.info()
<class 'modin.pandas.dataframe.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 2 columns):
 #   Column     Dtype 
---  ------     ----- 
 0   items      object
 1   items_cat  object
dtypes: object(2)
memory usage: 30.5+ MB
```

**Comment by ianozsvald** [comment]
Ah - so trying to make a `category` on a string in the above example doesn't work but making a categorical from a list of integers does work. However - it gets mis-reported by `info()`:

```
df_md_cat2 = mdpd.DataFrame({'items': [1] * 1_000_000 + [2] * 1_000_000})
df_md_cat2['items_cat'] = df_md_cat2['items'].astype('category')
df_md_cat2['items_cat'].dtype 
# the result is the same CategoricalDtype as Pandas shows
CategoricalDtype(categories=[1, 2], ordered=False)

# info() however shows two int64 columns in the list 
# and in the summary, with no categoricals
df_md_cat2.info()
<class 'modin.pandas.dataframe.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 2 columns):
 #   Column     Dtype
---  ------     -----
 0   items      int64
 1   items_cat  int64
dtypes: int64(2)
```

**Comment by devin-petersohn** [comment]
Hi @ianozsvald thanks for the report!

Categorical should be supported. I can reproduce the issue myself, thank you for the reproducer. We fall back to pandas for the `info` string, so it's interesting that the pandas implementation is failing like this. I will investigate, we may just need to override the resulting string with the correct dtypes.

**Comment by devin-petersohn** [comment]
This is the same as #1165, we have some progress on the bug in that thread so I will close this for duplication purposes. I will add a comment on that thread about the `info` case to ensure we don't lose this specific use case.
