### ISSUE TITLE
melt function implementation

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1205]

**Comment by dchigarev** [comment]
**Current state:**
For now there is two `melt` implementation that are ready, they both could be found in #1689. First applying `melt` to the row partitions, but requires slow reordering (performance of reordering could be improved after `sort_values` will be implemented in a scalable way). And the second applies `melt` to only subset of partitions (depends on columns that we needed in computation), but requires materialization of columns that specified in `id_vars` to broadcast them to every partition. 

Discussion about these two approaches and the time measurements of both implementation could be found [here](https://github.com/modin-project/modin/pull/1689).

**Comment by devin-petersohn** [comment]
@dchigarev I have left a comment in #1689 to use row partitioning for performance and scalability. Does that make sense?
