### ISSUE TITLE
set_value function implementation

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1286]

**Comment by YarShev** [comment]
It is deprecated functionality in pandas since version 0.21.0 ([ref](https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.Series.set_value.html)).

**Comment by YarShev** [comment]
It was removed from pandas ([ref](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html)).
