### ISSUE TITLE
strides function implementation

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1289]

**Comment by YarShev** [comment]
It is deprecated functionality in pandas since version 0.23.0 ([ref](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.Series.strides.html)).

**Comment by YarShev** [comment]
It was removed from pandas ([ref](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html)).
