### ISSUE TITLE
valid function implementation

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1293]

**Comment by YarShev** [comment]
It is deprecated functionality in pandas since version 0.23.0 ([ref](https://pandas.pydata.org/pandas-docs/version/0.25.3/reference/api/pandas.Series.valid.html)).

**Comment by YarShev** [comment]
It was removed from pandas ([ref](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html)).
