### ISSUE TITLE
[ExecAPI] Ray Python API wrapping is complete

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1344]

**Comment by mvashishtha** [comment]
I don't know what this means. @anmyachev please open if you know and it's still relevant.

**Comment by anmyachev** [comment]
It seems to me that it is similar to https://github.com/modin-project/modin/pull/3854. 
We need to define a separate level for interacting with Ray, just like we did for Dask.

**Comment by anmyachev** [comment]
Now we have `RayWrapper` class for interacting with Ray. Looks like the task is completed.
