### ISSUE TITLE
KeyError(f"None of [{key}] are in the [{axis_name}]")

### ISSUE THREAD

**Issue by jadhosn** [modin-project/modin#1366]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`): 0.7.2
- **Python version**: 3.7
- **Code we can use to reproduce**:
```
import pandas as pd
import modin.pandas as mpd

df = pd.DataFrame({'idx': [1,4,5], 'A': [4,5,6], 'B':['a','b','c']})
df = df.set_index("idx")
# write out parquet with index using pandas
df.to_parquet("./data/tmp.parquet")
# read the same parquet using modin.pandas
mdf = mpd.read_parquet("./data/tmp.parquet")
```
returns 
>"None of [Index(['idx'], dtype='object')] are in the [columns]"

### Describe the problem

Parquet files that are written using Pandas, throws this error when read using modin's `read_parquet()`

### Source code / logs

> KeyError: "None of [Index(['idx'], dtype='object')] are in the [columns]"

**Comment by devin-petersohn** [comment]
Hi @jadhosn thanks for the report!

This looks like a bug specific to setting the index, I will dig into this, thanks again for the report!

**Comment by jadhosn** [comment]
@devin-petersohn thank you! 
In the meantime, which of the following workarounds would you recommend to use to still gain an efficiency boost using modin:
* Write out the original parquet file with `idx` as a column, read the parquet file using modin, then `set_index` using modin
```
import pandas as pd
import modin.pandas as mpd

df = pd.DataFrame({'idx': [1,4,5], 'A': [4,5,6], 'B':['a','b','c']})
# write out pandas df with idx as column
df.to_parquet("./data/tmp.parquet")

# read the parquet file using modin
mdf = mpd.read_parquet("./data/tmp.parquet")

# set index
mdf = mdf.set_index("idx")
```
* Read the indexed parquet file using pandas, transform the pandas dataframe into a modin dataframe, then proceed with workflow
```
import pandas as pd
import modin.pandas as mpd

df = pd.DataFrame({'idx': [1,4,5], 'A': [4,5,6], 'B':['a','b','c']})
df = df.set_index("idx")

# write out pandas df with idx as column
df.to_parquet("./data/tmp.parquet")

# read the parquet file using pandas
df = pd.read_parquet("./data/tmp.parquet") 

# transform into modin dataframe
mdf = mpd.DataFrame(df)
```

Since I'm merging large data frames based on the index, would you recommend modin's `set_index` or `DataFrame` in terms of efficiency gains?

**Comment by devin-petersohn** [comment]
`set_index` is probably the way to go, `DataFrame` will take 2-3 seconds per GB of data because it has to partition and communicate the data. `set_index` should take significantly less time. Let me know if you run into issues with this workaround!

**Comment by lu003** [comment]
Hi all,

I'm a student trying to replicate the results of a paper for my class. I'm having trouble rerunning the source code and it returns this error. I'm very new to all these modules and not quite sure how to fix this even after reading this thread. More specifically I'm trying to run the spatial_SeqFISH_analysis.py (in Analysis/SeqFish/) and it returns this error:

![image](https://user-images.githubusercontent.com/66535693/118321195-e5fab500-b4c2-11eb-9af8-e48e8d360119.png)

 If anybody could be of help that would be great!

The article link: [](https://www.nature.com/articles/nmeth.4636)
Github source code: [](https://github.com/Teichlab/SpatialDE)
