### ISSUE TITLE
Running df.query('X == Y'), and got ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task. 

### ISSUE THREAD

**Issue by hansioux** [modin-project/modin#1389]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Modin version** (`modin.__version__`): 0.7.2
- **Python version**:  3.7.7
- **Code we can use to reproduce**: df2 = df1.query('X == Y')

### Describe the problem
I have a rather large csv file (about 9.8G).  Running with regular pandas DataFrame took too long, so I tried to speed up the process with modin and ray.  I don't know how to upload my 9.8G csv file.

I installed modin by running 
pip install modin[all]

After adjusting imports to import modin.pandas as pd 
It would take even longer than regular pandas DataFrame, before crashing with this error

ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task. 

### Source code / logs
Log
$ python run.py
FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
UserWarning: Parameters provided defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
(pid=28382) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28366) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28379) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28392) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28359) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28377) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28368) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28378) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28363) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28361) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28372) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28389) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28375) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28357) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28367) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28360) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
(pid=28370) DtypeWarning: Columns (1011) have mixed types.Specify dtype option on import or set low_memory=False.
UserWarning: `Series.unique` defaulting to pandas implementation.
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
UserWarning: `DataFrame.insert` for empty DataFrame defaulting to pandas implementation.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.
(pid=28370) *** Aborted at 1587619386 (unix time) try "date -d @1587619386" if you are using GNU date ***
(pid=28370) PC: @                0x0 (unknown)
(pid=28370) *** SIGBUS (@0x7fb8f1a15000) received by PID 28370 (TID 0x7fbeb4309700) from PID 18446744073468465152; stack trace: ***
(pid=28370)     @     0x7fbeb3eff390 (unknown)
(pid=28370)     @     0x7fbeb3c72156 (unknown)
(pid=28370)     @     0x7fbeb24c59ab __pyx_f_3ray_7_raylet_13Pickle5Writer_write_to()
(pid=28370)     @     0x7fbeb24e8150 __pyx_f_3ray_7_raylet_write_serialized_object()
(pid=28370)     @     0x7fbeb25139c3 __pyx_f_3ray_7_raylet_10CoreWorker_store_task_outputs()
(pid=28370)     @     0x7fbeb24f309d __pyx_f_3ray_7_raylet_task_execution_handler()
(pid=28370)     @     0x7fbeb24b2dd4 std::_Function_handler<>::_M_invoke()
(pid=28370)     @     0x7fbeb253f3e8 ray::CoreWorker::ExecuteTask()
(pid=28370)     @     0x7fbeb251e8db std::_Function_handler<>::_M_invoke()
(pid=28370)     @     0x7fbeb2553288 _ZZN3ray28CoreWorkerDirectTaskReceiver14HandlePushTaskERKNS_3rpc15PushTaskRequestEPNS1_13PushTaskReplyESt8functionIFvNS_6StatusES7_IFvvEESA_EEENKUlvE_clEv
(pid=28370)     @     0x7fbeb2555d73 ray::SchedulingQueue::Add()
(pid=28370)     @     0x7fbeb2556e70 ray::CoreWorkerDirectTaskReceiver::HandlePushTask()
(pid=28370)     @     0x7fbeb253401b _ZN5boost4asio6detail18completion_handlerIZN3ray10CoreWorker14HandlePushTaskERKNS3_3rpc15PushTaskRequestEPNS5_13PushTaskReplyESt8functionIFvNS3_6StatusESB_IFvvEESE_EEE
UlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=28370)     @     0x7fbeb25223a5 boost::asio::detail::scheduler::run()
(pid=28370)     @     0x7fbeb2526502 ray::CoreWorker::StartExecutingTasks()
(pid=28370)     @     0x7fbeb24b56bc __pyx_pw_3ray_7_raylet_10CoreWorker_5run_task_loop()
(pid=28370)     @     0x56460e3fd6c1 _PyMethodDef_RawFastCallKeywords
(pid=28370)     @     0x56460e4046af _PyMethodDescr_FastCallKeywords
(pid=28370)     @     0x56460e468add _PyEval_EvalFrameDefault
(pid=28370)     @     0x56460e3fcd5b _PyFunction_FastCallKeywords
(pid=28370)     @     0x56460e4644e0 _PyEval_EvalFrameDefault
(pid=28370)     @     0x56460e3ad289 _PyEval_EvalCodeWithName
(pid=28370)     @     0x56460e3ae1c4 PyEval_EvalCodeEx
(pid=28370)     @     0x56460e3ae1ec PyEval_EvalCode
(pid=28370)     @     0x56460e4c4cb4 run_mod
(pid=28370)     @     0x56460e4cf0d1 PyRun_FileExFlags
(pid=28370)     @     0x56460e4cf2c3 PyRun_SimpleFileExFlags
(pid=28370)     @     0x56460e4d03f5 pymain_main
(pid=28370)     @     0x56460e4d051c _Py_UnixMain
(pid=28370)     @     0x7fbeb3b44830 __libc_start_main
(pid=28370)     @     0x56460e473ac0 (unknown)
E0423 13:23:07.950350 28399 task_manager.cc:98] 3 retries left for task 75bbf3f914ba6d3cffffffff0100, attempting to resubmit.
E0423 13:23:07.992408 28399 core_worker.cc:185] Will resubmit task after a 5 second delay: Type=NORMAL_TASK, Language=PYTHON, function_descriptor=modin.engines.ray.pandas_on_ray.frame.axis_partition,,depl
oy_ray_func, task_id=75bbf3f914ba6d3cffffffff0100, job_id=0100, num_args=82, num_returns=105
Traceback (most recent call last):
  File "/home/user/src/run.py", line 55, in __init__
    self.open_file()
  File "/home/user/src/run.py", line 452, in open_file
    self.update_table()
  File "/home/user/src/run.py", line 466, in update_table
    self.dfScore = get_scores(df, self.thresholds, self.source)
  File "/home/user/src/get_scores.py", line 35, in get_scores
    dfT = get_score(df, threshold, source)
  File "/home/user/src/modules.py", line 437, in get_score
    df2 = df1.query('X == Y')
  File "/home/user/anaconda3/envs/tf/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1285, in query
    new_query_compiler = self._query_compiler.query(expr, **kwargs)
  File "/home/user/anaconda3/envs/tf/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 725, in query
    self._modin_frame.filter_full_axis(1, query_builder)
  File "/home/user/anaconda3/envs/tf/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 813, in filter_full_axis
    0, new_partitions, lambda df: df.index
  File "/home/user/anaconda3/envs/tf/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py", line 56, in get_indices
    new_idx = ray.get(new_idx)
  File "/home/user/anaconda3/envs/tf/lib/python3.7/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray_worker (pid=28355, ip=10.0.201.21)
  File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 630, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 519, in ray._raylet.deserialize_args
ray.exceptions.RayTaskError: ray_worker (pid=28389, ip=10.0.201.21)
  File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 630, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 519, in ray._raylet.deserialize_args
ray.exceptions.RayTaskError: ray_worker (pid=28366, ip=10.0.201.21)
  File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 630, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 519, in ray._raylet.deserialize_args
ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task.

**Comment by devin-petersohn** [comment]
Hi @hansioux, thanks for reporting! This looks like a memory issue, we are also tracking this with the Ray team as well.

While we work on this issue, if I may offer some suggested rewrites that may help:

- It looks like you create an empty `DataFrame` then `insert` many times, I recommend trying to read all files not in a loop and then use `pd.concat` to create one large dataframe from them. That will be more optimized in the context of both pandas and Modin. Modin doesn't have query planning yet to be able to predict this behavior so we cannot yet optimize for it
- `df.query` in this case can be rewritten to `df[df.X == df.Y]` and that should be faster and more memory efficient in Modin.

With some query planning in the future these problems will not exist, but this rewrite will also make the pandas code more efficient too.

**Comment by mvashishtha** [comment]
We don't have a reproducer for this issue. It's so old that I'm going to close it as stale. @hansioux please comment here if you think this issue needs more attention.
