### ISSUE TITLE
Everything after DataFrame.sample() running out of memory

### ISSUE THREAD

**Issue by jadhosn** [modin-project/modin#1395]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux (remote machine) 
- **Modin version** (`modin.__version__`): 0.7.0
- **Python version**: 3.7
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

# read data files
df1 = pd.read_parquet("data1.parquet")
df2 = pd.read_parquet("data2.parquet") 

# do some operations
df = pd.merge(df1, df2, right_index=True, left_index=True, sort=False)

# write out the result
df.to_parquet("new_data.parquet")

# but if you sample down
df = df.sample(n=10000, random_state=42)

# then do anything after it, nothing works
df.to_parquet("new_data2.parquet") #<-- doesn't complete
```

### Describe the problem

Everything after `DataFrame.sample()` is not working/killing the process/workers running out of memory (similar to this [issue](https://github.com/dask/dask/issues/4256) on Dask)

The same code runs beautifully without `.sample()` on the same machine. Whenever `.sample()` is summoned, the workers start running out of memory and the run gets killed after a couple of retries. 

What's worth noting here that modin is doing a beautiful job on the complete data file (~ 1M records), but then whenever I sub-sample to say 100,000 records, it starts running out of memory!

PS: I'm running modin + dask

**Comment by devin-petersohn** [comment]
Hi @jadhosn thanks for the report!

>What's worth noting here that modin is doing a beautiful job on the complete data file (~ 1M records), but then whenever I sub-sample to say 100,000 records, it starts running out of memory!

This is interesting, looking through the `sample` [code](https://github.com/modin-project/modin/blob/6961c50ead66f6b6def9631459880f212908f727/modin/pandas/base.py#L2345), it should not be creating copies. I spent some time triaging this here is what I can note (with Dask):

- `sample` is taking way too much time and using only one core the whole time. 2 minutes on 1m lines of code is not reasonable, we should fix this
- Python worker memory does appear to increase even though it should not be. It is going through the internal `mask`, which has a memory and runtime optimized implementation so I would not expect this. 
- If I dig into the implementation a bit, the rearranged nature of the `sample` is causing `mask` to take longer than expected. Example:

```python
# From internal implementation
sample_indices = random_num_gen.choice( 
    np.arange(0, len(df)), size=n, replace=replace, p=weights 
)
df.iloc[sample_indices] # Takes >2 min on 1m rows, creates >8000 partitions
df.iloc[np.sort(sample_indices)] # Takes 173ms on 1m rows
```

I will optimistically tag for next release (Monday) but cannot make a promise here. If you are okay with sorted indices for this use case, I can provide a temporary workaround.

**Comment by jadhosn** [comment]
@devin-petersohn thank you for the quick response! That seems like exactly what I'm seeing. 

I am okay with sorted indices (assuming this operation is not expensive in modin as I will be executing it right before the `sample()` call). What workaround did you have in mind?

**Comment by devin-petersohn** [comment]
This will be overfit to your example code above, but you should be able to adjust as you need.

Code you provided:
```python
# read data files
df1 = pd.read_parquet("data1.parquet")
df2 = pd.read_parquet("data2.parquet") 

# do some operations
df = pd.merge(df1, df2, right_index=True, left_index=True, sort=False)
```

To replace `sample`:
```python
random_state = 42
n = 10_000 # 10,000 records
replace = False
weights = None
random_num_gen = np.random.RandomState(random_state)
sample_indices = random_num_gen.choice( 
    np.arange(0, len(df)), size=n, replace=replace, p=weights 
)
sampled_df = df.iloc[np.sort(sample_indices)] # Takes 173ms on 1m rows
```

This should be near instant from an interactive perspective.

**Comment by devin-petersohn** [comment]
We weren't able to get to this in time for this release, will prioritize for the next release.
