### ISSUE TITLE
add `modin/env` folder for files with pip and conda packages

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#1401]
At the moment, we have several environment files that are located in the root of the repository. Example: `df_test_requires.txt`, `env_windows.yml`, `requirements.txt`, `windows_test_requires.txt`.

What do you think about adding a folder for these files? 

- This will reduce the semantic load for users who first see the project. 
- Also in the future there will be less chances to forget to add the package to any file.

**Comment by gshimansky** [comment]
PyCharm detects `requirements.txt` automatically and verifies project requirements from its contents. Are you sure it will detect this file if it is located in a subfolder?

**Comment by anmyachev** [comment]
> PyCharm detects `requirements.txt` automatically and verifies project requirements from its contents. Are you sure it will detect this file if it is located in a subfolder?

For PyCharm we need to manually [change](https://www.jetbrains.com/help/pycharm/managing-dependencies.html#create-requirements) the path to `requirements.txt` file.

**Comment by gshimansky** [comment]
So it means that standard location of this file is root of the project. I don't think we should change it.

**Comment by anmyachev** [comment]
Ok, let's leave this file at the root.
