### ISSUE TITLE
Assigning Index object to DataFrame.index which has an "index" column replaces column contents

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1403]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Windows 10, Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.2+72.g6961c50.dirty

- **Python version**:

Python 3.7.7

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

df1 = pd.DataFrame([['ccc', 'xxx', 2], ['bbb', 'yyy', 5], ['aaa', 'zzz', 8]],
                   columns=['index', 'whatever', 'shield'])
print(df1)

df2 = df1.rename({'index': 'name'}, axis='columns')
print(df2)
```

### Describe the problem

If frame contains a column named `index` (which happens often after `reset_index` is used with `drop=False` (by default)), then some weird thing happens. In addition to renaming column label Modin inserts index contents into that column:
```
  index whatever  shield
0   ccc      xxx       2
1   bbb      yyy       5
2   aaa      zzz       8
   name whatever  shield
0     0      xxx       2
1     1      yyy       5
2     2      zzz       8
```
while pandas does only renaming:
```
  index whatever  shield
0   ccc      xxx       2
1   bbb      yyy       5
2   aaa      zzz       8
  name whatever  shield
0  ccc      xxx       2
1  bbb      yyy       5
2  aaa      zzz       8
```

**Comment by gshimansky** [comment]
The problem is in this like in `dataframe.py`:
```python
        obj.index = new_index
```
which assigns an index to a new dataframe object. But when it goes inside of DataFrame.__setitem__ it assigns these values to a **column** named `index` instead of object **index**.

**Comment by gshimansky** [comment]
Here is a reproducer without `rename`
```python
import modin.pandas as pd

df = pd.DataFrame([['ccc', 2], ['bbb', 5], ['aaa', 8]],
                   columns=['index', 'shield'])
print(df)
idx = pd.Index(['111', '222', '333'])
df.index = idx
print(df)
```

**Comment by gshimansky** [comment]
This is patch to tests to test this behavior
```patch
diff --git a/modin/pandas/test/utils.py b/modin/pandas/test/utils.py
index 1c517a6..3986cad 100644
--- a/modin/pandas/test/utils.py
+++ b/modin/pandas/test/utils.py
@@ -62,6 +62,12 @@ test_data = {
         ]
         for i in range(NCOLS)
     },
+    "with_index_column": {
+        "index": [1, 2, 3, 4],
+        "col4": [4, 5, 6, 7],
+        "col1": [8.0, 9.4, 10.1, 11.3],
+        "col2": ["a", "b", "c", "d"],
+    },
     # "int_float_object_data": {
     #     "col3": [1, 2, 3, 4],
     #     "col4": [4, 5, 6, 7],
@@ -154,6 +160,7 @@ numeric_dfs = [
     "float_data",
     "sparse_nan_data",
     "dense_nan_data",
+    "with_index_column",
     "100x100",
 ]
```

**Comment by dchigarev** [comment]
> The problem is in this like in `dataframe.py`:
> 
> ```python
>         obj.index = new_index
> ```
> 
> which assigns an index to a new dataframe object. But when it goes inside of DataFrame.**setitem** it assigns these values to a **column** named `index` instead of object **index**.

Well quick fix for that is
```python
    obj._set_index(new_index)
```
now it's directly call the function that change indexes, without going to `dataframe.py __setattr__` which looks like this
```python
def __setattr__(self, key, value):
        if key in ["_query_compiler"] or key in self.__dict__:
            pass
        elif key in self:
            self.__setitem__(key, value)
        elif isinstance(value, pandas.Series):
            ...
        object.__setattr__(self, key, value) 
```
so, if `key` named like some of `DataFrame` attribute (like `index`, `columns` etc) and the DataFrame itself contains a column with that name, then (going by that if-statement):
```python
    elif key in self:
        self.__setitem__(key, value)
```
we'll try to assign `value` to a column, instead of calling `object.__setattr__(self, key, value)` and changing the attribute itself

It's means, that we probably should add a check that `key` isn't an attribute name (`self.__dict__` returns dict with only one field `'_query_compiler'` so this is not that type of check)

**Comment by gshimansky** [comment]
@dchigarev yes, but will that change make it possible to still write `df["index"]` = some_new_value` or will all such assignments assign to `df.index` instead?

**Comment by dchigarev** [comment]
with changing `self.__dict__` to `dir(self)` related code works as expected:
```python
    import modin.pandas as pd

    df1 = pd.DataFrame([['ccc', 'xxx', 2], ['bbb', 'yyy', 5], ['aaa', 'zzz', 8]],
                       columns=['index', 'whatever', 'shield'])

    df1["index"] = [1,2,3]
    df2 = df1.rename({'index': 'name'}, axis='columns')
    
    print(df2)
```

Output:
```
   name whatever  shield
0     1      xxx       2
1     2      yyy       5
2     3      zzz       8
```

**Comment by gshimansky** [comment]
Ok I tried implementing this approach referenced above. This does fix some of failing tests, but I still get 449 test failures. Without this fix and with test dataframe that contains "index" column I get 526 test failures from test_dataframe.py.

**Comment by gshimansky** [comment]
@dchigarev your suggestion to fix this bug was correct. Problem with my test was that it tested too broadly and resulted in additional failures #1447, #1464 and #1467. I had to narrow down this test and still had to fix additional problems in PR.
