### ISSUE TITLE
Convert docstrings to numpydoc

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#1411]
**Is your feature request related to a problem? Please describe.**
Since in the near future a large number of new people will begin to work on the project, it is necessary to agree on a standard for docstrings. And introduce some kind of automatic checks.

For my part, I would like to suggest `nympydoc` package that we can use in github actions CI.

**Comment by devin-petersohn** [comment]
So far, the approach has been:

```python
def some_method(self, arg1, arg2):
	"""The one-line description of the method.

	Args:
		arg1: Description
		arg2: Description

	Returns:
		What this returns (if anything)
	"""
	# Begin implementation
	return something

```

I am open to new suggestions as long as we are standardized. `numpydoc` seems reasonable, interested to hear other opinions.

**Comment by aregm** [comment]
Looks like numpydoc has a standard extension in sphinx, which will make the cross-reference easier.

**Comment by devin-petersohn** [comment]
numpydoc is a good testable standard. Let's go with that. We can install `pydocstyle` and test from bash with

```
pydocstyle --convention=numpy modin/pandas
```

**Comment by mvashishtha** [comment]
@anmyachev is this still relevant?

**Comment by anmyachev** [comment]
@mvashishtha It is necessary to make an analysis of which files are not yet checked in the CI for compliance with numpydoc  standard. If there are such files, then we need to check them too.

**Comment by anmyachev** [comment]
Most of the code uses this format; when we find files where the format is different, we will create separate tasks and convert the corresponding files to the new format.
