### ISSUE TITLE
internal error when calling `values` on a dataframe column with `datetime64[ns, UTC]` dtype

### ISSUE THREAD

**Issue by mooneral** [modin-project/modin#1420]
### System information
- **OS Platform:and Distribution:
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)")**:
- **Modin version** (`0.7.3`):
- **Python version: `3.6.9`**:
- **`df['time'].values`**:
<img width="233" alt="df" src="https://user-images.githubusercontent.com/6414106/80867225-4815bd00-8ca8-11ea-882b-4cf04464ee5d.png">

### Describe the problem

i have a dataframe with multiple columns which one column is `time` with `datetime64[ns, UTC] dtype` when i try to access values using  `df['time'].values` i get an `internal error`.
but it is okay when i run on other columns that have `object dtype`.

### Source code / logs

```shell


---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-156-51a3b749d3d0> in <module>()
----> 1 btc['time'].values

4 frames
/usr/local/lib/python3.6/dist-packages/modin/pandas/base.py in __getattribute__(self, item)
   3379         ]
   3380         if item not in default_behaviors:
-> 3381             method = object.__getattribute__(self, item)
   3382             is_callable = callable(method)
   3383             # We default to pandas on empty DataFrames. This avoids a large amount of

/usr/local/lib/python3.6/dist-packages/modin/pandas/series.py in values(self)
    347             The numpy representation of this object.
    348         """
--> 349         return super(Series, self).to_numpy().flatten()
    350 
    351     def __xor__(self, other):

/usr/local/lib/python3.6/dist-packages/modin/pandas/base.py in to_numpy(self, dtype, copy)
   2979             A numpy array.
   2980         """
-> 2981         arr = self._query_compiler.to_numpy()
   2982         if dtype is not None:
   2983             return np.asarray(arr, dtype)

/usr/local/lib/python3.6/dist-packages/modin/backends/pandas/query_compiler.py in to_numpy(self)
    180         arr = self._modin_frame.to_numpy()
    181         ErrorMessage.catch_bugs_and_request_email(
--> 182             len(arr) != len(self.index) or len(arr[0]) != len(self.columns)
    183         )
    184         return arr

/usr/local/lib/python3.6/dist-packages/modin/error_message.py in catch_bugs_and_request_email(cls, failure_condition, extra_log)
     51                 "Internal Error. "
     52                 "Please email bug_reports@modin.org with the traceback and command that"
---> 53                 " caused this error.\n{}".format(extra_log)
     54             )
     55 

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
```

**Comment by gshimansky** [comment]
Hello @rezava, thank you for reporting this. I am trying to reproduce this bug but I need more details.
How big is your dataframe? Is this bug reproducible on a dataset of several lines like in your screenshot?

**Comment by rezava** [comment]
Hey @gshimansky,
> How big is your dataframe? Is this bug reproducible on a dataset of several lines like in your screenshot?

in fact, the data I'm using is bitcoin 1min historical data with approx 1 million rows.
and I think you can reproduce with similar data and procedure.

**Comment by devin-petersohn** [comment]
Closing as this should be fixed with the various improvements and updates to datetime in the next release. Please reopen if the issue still exists on master. Thanks!
