### ISSUE TITLE
Reading CSV with mismatched quotes causes infinite loop

### ISSUE THREAD

**Issue by pratheekrebala** [modin-project/modin#1423]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.04
- **Modin version** (`modin.__version__`): HEAD
- **Python version**: 3.8
- **Code we can use to reproduce**:

Try to read this file using the `pd.read_csv("test_quotes_1.txt", sep='\t')` function:

The sample file I am trying to read is: [test_quotes_1.txt](https://github.com/modin-project/modin/files/4584991/test_quotes_1.txt) which contains the following tab separated data:

```
a   b   c   d
e   f"  l   m
n   o   "p   q"
```

Trying to read the above data will cause an infinite loop.

### Describe the problem
When trying to read CSV (or any delimiter separated data) that has mismatched quotes, the `read_csv` method will cause an infinite loop.

I have provided a TSV example above but this same can be re-created using a CSV file like this one
[test_quotes_1_comma.txt](https://github.com/modin-project/modin/files/4584997/test_quotes_1_comma.txt)

### Source code / logs
The root cause of this issue seems to be the `while` loop that checks for quotes:

https://github.com/modin-project/modin/blob/555c89956b48e6b4ad50877ba4b7c7594cd592e5/modin/engines/base/io/text/text_file_reader.py#L26-L30

An odd number of quotes will mean that this while loop will never resolve and the program will just hang without any error messages. Since this is part of the `engines.base.io.text_file_reader` module, this issue exists with both Ray and Dask.

I think one naive solution might be to check for `EOF` and breaking the loop. A long message suggesting this might also be helpful.

Although this is a malformed data file, trying to read this with pandas succeeds.

I'm happy to send a PR addressing this.

**Comment by pratheekrebala** [comment]
On a slightly related note: It would be very useful if the `read_csv` function would also respect the `quoting=csv.QUOTE_NONE` attribute that is accepted by `pandas.read_csv`. Ideally, this flag should jump over the entire loop above.

In my dataset which contains malformed quotes, commenting out the quote checking loop causes the read of a ~200MB dataset to go from >1m to 5s (also ensures that data is read correctly). For now, I am using an invalid unicode character `\U0000FFFF` to achieve the same outcome as `csv.QUOTE_NONE`

```python
pd.read_csv(
        str(file_name),
        sep='\t',
        names=column_names,
        index_col=False,
        na_values='*',
        dtype='object',
        quoting=csv.QUOTE_NONE,
        quotechar=u"\U0000FFFF"
)
```

**Comment by gshimansky** [comment]
Hello @pratheekrebala, thank you for reporting this problem. Indeed there is a bug in `read_csv` implementation and your suggestion of handing `QUOTE_NONE` is correct.

**Comment by devin-petersohn** [comment]
@pratheekrebala We will happily accept your PR addressing this, it's a good find!

The loop exists to ensure that we don't try to partition the data in the middle of a quote. The requirement here is that the partitioned reader consumes up to a complete row of data, but long quotes can cause issues if they contain newlines.

**Comment by pratheekrebala** [comment]
@devin-petersohn: I'll send a PR to address the issue this week.

**Comment by YarShev** [comment]
@pratheekrebala , Can you please answer for a question, are you planning to sent a PR addressing this issue or not? I would like to know this just for that we don't duplicate working.

**Comment by pratheekrebala** [comment]
Hi @YarShev, Apologies about the delay. I will work on this and circle back today.

**Comment by YarShev** [comment]
Hi, @pratheekrebala , it is great! We are waiting for your PR. Thanks a lot!
