### ISSUE TITLE
Assignment of float to int changes data type instead of truncation

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1431]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+15.gc09e61f.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

col = pd.Series([1, 2, 3])
print(type(col[0]))
print(type(col[1]))
col[0] = 1.1
print(type(col[0]))
print(type(col[1]))
```

### Describe the problem

In this reproducer assignment of float to an integer Series changes data type of the whole Series object. Pandas instead truncates floats to integers and retains int64 data type.

**Comment by devin-petersohn** [comment]
This is interesting because pandas is not consistent between `Series.__setitem__` and `Series.iloc.__setitem__`:

```python
import pandas

col = pandas.Series([1, 2, 3])
print(type(col[0]))
print(type(col[1]))
col[0] = 1.1
print(type(col[0]))
print(type(col[1]))

col = pd.Series([1, 2, 3])
print(type(col[0]))
print(type(col[1]))
col.iloc[0] = 1.1
print(type(col[0]))
print(type(col[1]))
```

@gshimansky Is this a problem in a workflow you're testing? Does the workflow assume the data type will not change?

**Comment by gshimansky** [comment]
No this code doesn't appear in any benchmark. I noticed this bug when I was writing reproducer tests and filed it as a side work because I saw difference with pandas behavior.

**Comment by mvashishtha** [comment]
pandas 1.4.4 seems to also change datatype to float when you do assignment with either `Series.__setitem__` or `Series.iloc.__setitem__`. Modin does the same as of version af6f8277cf9caeb7dec8b390ef3652ec0fa04774. Both Modin and pandas seem to behave the same way for the code in https://github.com/modin-project/modin/issues/1431#issuecomment-663650672.
