### ISSUE TITLE
read_csv(sep=None) cannot find the separator automatically

### ISSUE THREAD

**Issue by isilopekel** [modin-project/modin#1452]
### System information
- **OS Platform and Distribution:**  Linux Ubuntu 16.04
- **Modin version** : 0.7.3
- **Python version**: 3.6.7
- **Code we can use to reproduce**:
```
# Create a dummy.csv file with the following content
a,b,c
1,2,3
4,5,6

if __name__ == "__main__":
    import modin.pandas as pd

    df=pd.read_csv("dummy.csv", sep=None)
    print(df.columns)
    print(len(df.columns))

    df2=pd.read_csv("dummy.csv")
    print(df2.columns)
    print(len(df2.columns))
```

### Describe the problem
The code above with sep=None cannot parse the columns. The output is
Index(['a,b,c'], dtype='object')
1
Index(['a', 'b', 'c'], dtype='object')
3

From pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html):
If sep is None, the C engine cannot automatically detect the separator, but the Python parsing engine can, meaning the latter will be used and automatically detect the separator by Python’s builtin sniffer tool, csv.Sniffer.

**Comment by devin-petersohn** [comment]
Hi @isilopekel, thanks for the report. It is a simple change.

From the commit message for the fix:

```
Previously, pandas allowed
`sep=False` for tab delimeted text files. Because we explicitly look for
a `sep` character we converted `sep=False` to `sep="\t"`. We checked
with a line `if not sep` which also evaluated to True when `sep` is
`None`.
```

**Comment by isilopekel** [comment]
Thank you!
