### ISSUE TITLE
TypeError: object of type 'slice' has no len()

### ISSUE THREAD

**Issue by jcrichard** [modin-project/modin#1456]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Modin version** (`modin.__version__`): 0.7.3
- **Python version**: 3.7
- **Code we can use to reproduce**: The code is available on [google collab](https://colab.research.google.com/drive/1n48GuNeeXr1HpbHAQsqIQQgsn1x3VIcM?usp=sharing)

### Describe the problem

Indexing multicolumn index dataframe generates an exception.

### Source code / logs

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-ad6eab4f4683> in <module>()
      4              np.array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'])]
      5 df = pd.DataFrame(np.random.randn(8, 4), index=arrays).T
----> 6 df.loc[df.index>2,:]

/usr/local/lib/python3.6/dist-packages/modin/pandas/indexing.py in __getitem__(self, key)
    249             hasattr(result, "columns")
    250             and isinstance(result.columns, pandas.MultiIndex)
--> 251             and all(col_loc[i] in result.columns.levels[i] for i in range(len(col_loc)))
    252         ):
    253             result.columns = result.columns.droplevel(list(range(len(col_loc))))

TypeError: object of type 'slice' has no len()
```

**Comment by devin-petersohn** [comment]
Hi @jcrichard thanks for the report!

I can reproduce the issue on current master.
