### ISSUE TITLE
Groupby agg needs an extra argument unlike pandas

### ISSUE THREAD

**Issue by isilopekel** [modin-project/modin#1458]
### System information

- OS Platform and Distribution: Linux Ubuntu 16.04
- Modin version : 0.7.3
- Python version: 3.6.7
- Code we can use to reproduce:

```
# Create a dummy.csv file with the following content
a,b,c
1,2,3
4,5,6
1,2,3


if __name__ == "__main__":
    import pandas as pd

    df = pd.read_csv("dummy.csv", sep=",")
    df_agg = df.groupby(["a","b"]).agg(
        Max=('c', np.max),
        Sum=('c', np.sum),
        Uni=("c", pd.Series.nunique)
    ).reset_index()

    print(df_agg)

    import modin.pandas as mpd
    df = mpd.read_csv("dummy.csv", sep=",")
    df_agg2 = df.groupby(["a","b"]).agg(
        Max=('c', np.max),
        Sum=('c', np.sum),
        target_col=('c', mpd.Series.nunique)
    ).reset_index()

```

### Describe the problem

Modin throws an error: TypeError: agg() missing 1 required positional argument: 'arg'

**Comment by devin-petersohn** [comment]
Hi @isilopekel thanks for the report!

I will have to dig into this. Our API is matching pandas, but I need to see how they are handling this case internally because it is the python interpreter throwing the error when `agg` is called.
