### ISSUE TITLE
default_to_pandas at groupby works incorrect when 'by' is str

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1461]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows 10 1809
- **Modin version** (`modin.__version__`):  0.7.3+41.gd617985
- **Python version**:  Python 3.7.5
- **Code we can use to reproduce**:
```python
if __name__ == "__main__":
    import pandas
    import modin.pandas as pd
    from modin.pandas.test.utils import df_equals

    data = {
        "col1": [0, 1, 2, 3],
        "col2": [4, 5, 6, 7],
    }

    md_grp, pd_grp = pd.DataFrame(data).groupby(by="col1"), pandas.DataFrame(data).groupby(by="col1")
    df_equals(md_grp.first(), pd_grp.first())

```

### Describe the problem

When passing `by` parameter as str, modin groupby behaves differ from pandas. It works like if we pass to the `by` column itself, not just its name. The problem occurs only with those operations that falls to `_default_to_pandas`.
### Source code / logs

Well, to start with that pandas itself behaves differently when we pass column to the `by` and its name:
```python
import pandas
data = {
    "col1": [0, 1, 2, 3],
    "col2": [4, 5, 6, 7],
}

df = pandas.DataFrame(data)
col1 = df["col1"].copy()

grp1, grp2 = df.groupby(col1), df.groupby(col1.name)
pandas.testing.assert_frame_equal(grp1.first(), grp2.first())
```
related code will output:
```
AssertionError: DataFrame are different

DataFrame shape mismatch
[left]:  (4, 2)
[right]: (4, 1)
```

So it's important to keep type of what we are grouping, but as we see at [dataframe.py: def groupby()](https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L405-L416):
```python
...
elif isinstance(by, str):
    drop = by in self.columns
    idx_name = by
    if (
        isinstance(self.axes[axis], pandas.MultiIndex)
        and by in self.axes[axis].names
     ):
        pass
     else:
        by = self.__getitem__(by)._query_compiler
...
```
we set `by` to the column value, and then, at [groupby.py: def _default_to_pandas()](https://github.com/modin-project/modin/blob/master/modin/pandas/groupby.py#L571-L593) we have no ability to track the origin type of `by`

**Comment by devin-petersohn** [comment]
The type of the passed `by` object is not necessarily the problem:

```python
import pandas
data = {
    "col1": [0, 1, 2, 3],
    "col2": [4, 5, 6, 7],
}

df = pandas.DataFrame(data)
col1 = df["col1"] # Remove copy

grp1, grp2 = df.groupby(col1), df.groupby(col1.name)
pandas.testing.assert_frame_equal(grp1.first(), grp2.first())
```

The problem with `first` specifically is that it is defaulting to pandas. We track whether or not to drop the original column from the result with `drop`. 

https://github.com/modin-project/modin/blob/94927b8fedd0d992ad51da41d806fb36d6d8d099/modin/pandas/groupby.py#L52

After the `_default_to_pandas` logic runs, we should just drop the extra column if `self._drop is True`.

Default found here: https://github.com/modin-project/modin/blob/94927b8fedd0d992ad51da41d806fb36d6d8d099/modin/pandas/groupby.py#L571
