### ISSUE TITLE
Need to test DataFrame.product with small DataFrames

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1464]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+42.gc78828e.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```patch
diff --git a/modin/pandas/test/utils.py b/modin/pandas/test/utils.py
index 1faaf38..d4d257c 100644
--- a/modin/pandas/test/utils.py
+++ b/modin/pandas/test/utils.py
@@ -63,6 +63,11 @@ test_data = {
         ]
         for i in range(NCOLS)
     },
+    "small": {
+        "col0": [1, 2, 3, 4],
+        "col1": [8.0, 9.4, 10.1, 11.3],
+        "col2": [4, 5, 6, 7],
+    },
     # "int_float_object_data": {
     #     "col3": [1, 2, 3, 4],
     #     "col4": [4, 5, 6, 7],
```

### Describe the problem

When dataframe size is small and is smaller than `min_count` parameter value for `product` it causes a lot of tests to fail. Pandas behaves quite strangely and Modin works differently.

**Comment by dchigarev** [comment]
I've found out that `pandas` have a strange output for `product` and `sum` only if `numeric_only` parameter specified or `skipna=False`, so I've changed `modin` behavior to it mirrors `pandas` in #1827 and also added test cases that were suggested by @gshimansky above
