### ISSUE TITLE
cummax/cummin throw exception on mixed int/float type dataframes

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1467]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+42.gc78828e.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

data={'col1': [1, 2], 'col2': [3.3, 4.4]}
df = pd.DataFrame(data)
df1 = df.cummax(axis=1)
print(df1)
```

### Describe the problem

Pandas allows comparing ints with floats while Modin throws a TypeException.

**Comment by devin-petersohn** [comment]
The same problem exists for `cummin`.
