### ISSUE TITLE
iloc functionality issue

### ISSUE THREAD

**Issue by osalpekar** [modin-project/modin#147]
For certain DataFrames (will have more detail on this shortly), `df.iloc[[<index_number>]]` to pull a row from a DataFrame doesn't work. Seems to be working fine for smaller DataFrames (including mixed-type DataFrames), but the issue is present in larger DataFrames.

Use this to reproduce:
```
import modin.pandas as pd
data = {"col{}".format(i+1): random_state.randint(RAND_LOW, RAND_HIGH, size=(100)) for i in range(100)}
df = pd.DataFrame(data)
print(df.iloc[[12]])
```

**Comment by ndy-cd** [comment]
So, it seems to be a problem with assigning new value through .iloc
code to reproduce:
`
import modin.pandas as pd #dask
test = pd.DataFrame({'first': range(10)})
test['first'].iloc[0] = 500
# or test['first'].iloc[[0, 1, 2]] = 500
print(test) # there is no changes
`
