### ISSUE TITLE
Pandas backend feature

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1471]

**Comment by mvashishtha** [comment]
@modin-project/modin-contributors @modin-project/modin-core does anyone know what this is referring to?

**Comment by anmyachev** [comment]
@mvashishtha this is an epic tracker for all the functions from Modin' api that we can implement without a fallback to pandas, but at the same time using the pandas dataframe type, which are stored in partitions. At least that's my understanding :)

**Comment by YarShev** [comment]
I think we can close this issue as there are no concrete details on this. Feel free to reopen.
