### ISSUE TITLE
Series.rank and DataFrame.rank throw ValueError:  buffer source array is read-only

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1481]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+44.g426b96e.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import modin.pandas as pd
df = pd.DataFrame({"col1": [1, 10], "col2": [20, 5]})
print(df.rank())
```

### Describe the problem

Exception is thrown on Ray, other modin engines work correctly

**Comment by gshimansky** [comment]
The following is a possible workaround for ValueError exception. It makes a copy of source dataframe before calling `rank`, but with this workaround the result of `rank` operation is lost and test fails because of this.
```patch
diff --git a/modin/backends/pandas/query_compiler.py b/modin/backends/pandas/query_compiler.py
index 6dab519..47cb6b6 100644
--- a/modin/backends/pandas/query_compiler.py
+++ b/modin/backends/pandas/query_compiler.py
@@ -751,7 +751,7 @@ class PandasQueryCompiler(BaseQueryCompiler):
         numeric_only = True if axis else kwargs.get("numeric_only", False)
         new_modin_frame = self._modin_frame._apply_full_axis(
             axis,
-            lambda df: df.rank(**kwargs),
+            copy_df_for_func(lambda df: df.rank(**kwargs)),
             new_index=self.index,
             new_columns=self.columns if not numeric_only else None,
             dtypes=np.float64,
```

**Comment by devin-petersohn** [comment]
@gshimansky Is this still an issue? It may have been fixed.
