### ISSUE TITLE
ReadCSV for OmniSci backend.

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1483]
Implement readcsv for omnisci through the canonical query_compiler path.

**Comment by anton-malakhov** [comment]
https://github.com/igalink/omniscidb/pull/3

**Comment by Garra1980** [comment]
For taxi we seem to know how to handle smth like this:
df = pd.read_csv(src_taxi, names=columns_names, parse_dates=["pickup_datetime"])

**Comment by anton-malakhov** [comment]
bridged omnisci side and python, arrow table was successfully consumed by Artems part of FSI

**Comment by anton-malakhov** [comment]
The search of segfault is over, we found a workaround which unblocks the next step.
Next step is to replace ibis and mapd_server via dbe extension

**Comment by anton-malakhov** [comment]
This is log from chat in Russian:

> давай общую картину обрисую - у нас есть сегфолт из-за плохой видимости, но он имеет воркараунд. у нас был сегфолт в createTable, FSI. я его заворкараундил и тест почти прошёл на те же вызовы что модин должен делать, ломаясь в конце. и теперь у нас сегфолт при старте модина с воркараундом LD_PRELOAD
 ну и напоследок - если пускать модин без воркараунда, то падает ещё на
ERROR MapDParser:parseSql:859 - failed to parse SQL 'execute relalg {"rels": 
видимо не та ветка модина

**Comment by Garra1980** [comment]
Added changes for executeRelAlg entry point in omnisci to try - https://github.com/intel-go/omniscidb/commit/e64b85538f70dade424c7615fce3bbcb51ccefb9

**Comment by Garra1980** [comment]
Likely proper changes for executeRelAlg entry point - https://github.com/intel-go/omniscidb/commit/86cedddb1650a5dd612a7911b9a96162de7bead2

**Comment by anton-malakhov** [comment]
Finally it is working for a simple test! changes in brunches modin: intel/anton/dbe-integration  omnisci: consuming_arrow_table

**Comment by anton-malakhov** [comment]
a lot of segfaults are behind, trying to defer conversion of arrow to pandas. and replace it by conversion to omnisci instead

**Comment by anton-malakhov** [comment]
it works! Arrow materializes in omnisci after processing by the compiler

**Comment by anton-malakhov** [comment]
https://github.com/intel-go/modin/pull/61

**Comment by Garra1980** [comment]
Do we support every argument of read_csv fucntion? Anyway we need to create tests for arguments we support

**Comment by Garra1980** [comment]
For census benchmark we need to support 'header' argument of read_csv, seems there is an issue with it now

**Comment by Garra1980** [comment]
Remove from 0.8.2 - #2019 goes first

**Comment by YarShev** [comment]
Partially implemted. See details in https://modin.readthedocs.io/en/stable/supported_apis/io_supported.html.
