### ISSUE TITLE
modin.pandas.utils.from_pandas does not work with pandas.Series

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1494]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+46.g4286305.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import pandas as pd
import modin.pandas as mpd
s = pd.Series([1, 2])
mpd.utils.from_pandas(s)
```

### Describe the problem

The above code throws as exception `AttributeError: 'Series' object has no attribute 'columns'`.

**Comment by devin-petersohn** [comment]
This is not intended for public use, so we can close this. Conversion from pandas Series to modin.Series goes through Series constructor.
