### ISSUE TITLE
concat ignores sort argument

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1497]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **Modin version** (`modin.__version__`): 0.7.3+52.g880545b
- **Python version**: Python 3.7.3
- **Code we can use to reproduce**:

### Describe the problem

sort argument in modin.pandas.concat calls doesn't affect the result. It works like sort is always True.

### Source code / logs

import modin.pandas as pd

a = pd.DataFrame({'c' : [3],
                  'd' : [4]},
                 columns=list('dc'))
b = pd.DataFrame({'a' : [1],
                  'b' : [2]},
                 columns=list('ba'))

print(pd.concat([a, b], sort=True))
print(pd.concat([a, b], sort=False))

**Comment by itamarst** [comment]
I will see if I can fix this.
