### ISSUE TITLE
IndexError in multi-column groupby + sum

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1499]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **Modin version** (`modin.__version__`): '0.7.3+52.g880545b'
- **Python version**: Python 3.7.3
- **Code we can use to reproduce**:

### Describe the problem
Get IndexError when try multi-column groupby with pandas-on-ray engine

IndexError:  positional indexers are out-of-bounds

### Source code / logs

import modin.pandas as mpd

df = mpd.DataFrame(
    [[1, 11, 101], [1, 21, 201], [2, 12, 102], [2, 22, 202], [2, 32, 302]],
    columns=list("abc"),
)
print(df.groupby(["a", "b"]).sum())

**Comment by devin-petersohn** [comment]
Closing this. Just tested this code, it has been fixed. Please re-open if this is still an issue.
