### ISSUE TITLE
GPU DataFrame support

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#150]
Support for GPU Dataframe: 
http://rapids.ai/documentation.html

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.

**Comment by rohan-gt** [comment]
Does modin have GPU support now?

**Comment by devin-petersohn** [comment]
@rohan-gt Modin does not have GPU support yet. I believe I closed this in error when I was closing a bunch of stale issues.

**Comment by mvashishtha** [comment]
Duplicate of #2538
