### ISSUE TITLE
Missing column in groupby result

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1500]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 19.04
- **Modin version**: '0.7.3+52.g880545b'
- **Python version**: Python 3.7.3

### Describe the problem

When groupby key is not used as an index, we can miss it in the resulting frame

### Source code / logs

import modin.pandas as mpd
import pandas as pd

df = mpd.DataFrame(
    [[1, 11, 101], [1, 21, 201], [2, 12, 102], [2, 22, 202], [2, 32, 302]],
    columns=list("abc"),
)
print("Modin")
print(df.groupby(["a"], as_index=False).b.sum())

df = pd.DataFrame(
    [[1, 11, 101], [1, 21, 201], [2, 12, 102], [2, 22, 202], [2, 32, 302]],
    columns=list("abc"),
)
print("Pandas")
print(df.groupby(["a"], as_index=False).b.sum())

**Comment by devin-petersohn** [comment]
Closing this, as the error is no longer reproducible on master as it was fixed. Please re-open if the error was not fixed.
