### ISSUE TITLE
astype({"col": "category"}) should convert Series.values type to pandas.core.arrays.categorical.Categorical

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1503]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+57.g23015c5

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```
if __name__ == "__main__":
    #import pandas as pd
    import modin.pandas as pd

    series_length = 10_000
    df = pd.DataFrame(
        {
            "col1": ["str{0}".format(i) for i in range(0, series_length)],
            "col2": [i for i in range(0, series_length)],
        }
    )

    df1 = df.astype({"col1": "category"})
    print(df1)
    print(df1.dtypes)
    print(type(df1["col1"].values))
    print(df1["col1"].values)
```

### Describe the problem

On Pandas column.values type is `pandas.core.arrays.categorical.Categorical` while in Modin it remains to be `numpy.ndarray`. Test for this bug was written in PR #1382 and is marked as xfail at the moment.

**Comment by pyrito** [comment]
Thanks for the bug report @gshimansky ! I was able to reproduce this on the latest master: [af86009](https://github.com/modin-project/modin/commit/af860093fc59ed1ae68d9ab8716e5c8534fe9a01).
