### ISSUE TITLE
ReadCSV: parameter nrows cause fallback to Pandas

### ISSUE THREAD

**Issue by akharche** [modin-project/modin#1523]
Adding 'dtype' parameter to read_csv() falls back to Pandas implementation.

```
dtype = np.int16
df = pd.read_csv(filename, nrows=100000, dtype=dtype, header=None)
```
`UserWarning: Parameters provided defaulting to pandas implementation.`

**Comment by devin-petersohn** [comment]
Hi @akharche, thanks for the report!

I believe it is the `nrows=100000` argument that is causing the default to pandas. `dtype` parameter is supported.

**Comment by akharche** [comment]
Hi @devin-petersohn, thanks for the clarification!

Should I reopen the issue with 'nrows' parameter?

**Comment by devin-petersohn** [comment]
No we can keep the issue. @aregm has changed the title.
