### ISSUE TITLE
Create new omnisci FSI endpoint to pass arrow directly

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#1526]
We need to create a new endpoint to omnicsi foreign storage interface to allow directly passing in-memory arrow table to it.

**Comment by anton-malakhov** [comment]
polishing is needed but it is no longer a blocker for read_csv

**Comment by fexolm** [comment]
It looks like this endpoint is pretty stable now, at least when we use it from c++. So, I'm closing the ticket.

**Comment by anton-malakhov** [comment]
We also need to address issue of null type which exists in Arrow but not in omnisci

**Comment by anton-malakhov** [comment]
@fexolm I think this task is done. continuation is ```Null type support in Omnisci```
