### ISSUE TITLE
Should we split `test_dataframe.py` (~5500 LOC) into several others?

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#1527]
If we look at `.github/workflows/ci.yml`, we will see that `test_dataframe.py` is tested by classes, when the rest of the files are tested as a whole.

I suggest create `test_dataframe` folder with the following files:
- `test_binary.py`
- `test_map_metadata.py`
- `test_udf.py`
- `test_default.py`
- `test_reduction_a.py`
- `test_reduction_b.py`
- `test_window.py`
- `test_indexing.py`
- `test_iter.py`
- `test_join_sort.py`

**Comment by devin-petersohn** [comment]
The general breakdown of the test classes is based on a general classification of its behaviors, to group similar tests. This change would retain that structure, but reduce the amount of code in a single file.

I'm interested to hear other thoughts.

**Comment by anmyachev** [comment]
@gshimansky what do you think about it? (as far as I know, you worked with test infrastructure for some time)

**Comment by gshimansky** [comment]
For TeamCity it doesn't matter, we run all (except test_io.py which cannot be run with xdist) pytests in a single command
```
python -m pytest -rfE --tb=native -n=48 modin/pandas/test/test_series.py \
modin/pandas/test/test_dataframe.py \
modin/pandas/test/test_concat.py \
modin/pandas/test/test_groupby.py \
modin/pandas/test/test_reshape.py \
modin/pandas/test/test_general.py
```
so the fewer files there, the shorter command line (or we could use wildcards).
