### ISSUE TITLE
Error with Modin Pandas and pyodbc

### ISSUE THREAD

**Issue by jpchavezs** [modin-project/modin#1533]
Hi, I am trying to get information from a Netezza db with modin.pandas. 

When I try this with pandas works well.

This is mi code: 

import modin.pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as pltt
import pyodbc
import os
from io import open

conn= pyodbc.connect("""
DRIVER={NetezzaSQL};
SERVER=XXX;
PORT=5480;
DATABASE=DATABASE; 
UID=USER:
PWD=PASS;
""")

df=pd.read_sql("SELECT * FROM TABLE ",conn)

**That return me this error:** 

ProgrammingError                          Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
   1585         try:
-> 1586             cur.execute(*args, **kwargs)
   1587             return cur

ProgrammingError: ('42000', '[42000] Syntax error or access violation (27) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

DatabaseError                             Traceback (most recent call last)
 in ()
 
----> 3 df=pd.read_sql("SELECT * FROM TABLE",conn)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\modin\pandas\io.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    381         df_gen = pandas.read_sql(**kwargs)
    382         return (DataFrame(query_compiler=BaseFactory.from_pandas(df)) for df in df_gen)
--> 383     return DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
    384 
    385 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\modin\data_management\factories.py in read_sql(cls, **kwargs)
    151     @classmethod
    152     def read_sql(cls, **kwargs):
--> 153         return cls._determine_engine()._read_sql(**kwargs)
    154 
    155     @classmethod

~\AppData\Local\Continuum\anaconda3\lib\site-packages\modin\data_management\factories.py in _read_sql(cls, **kwargs)
    155     @classmethod
    156     def _read_sql(cls, **kwargs):
--> 157         return cls.io_cls.read_sql(**kwargs)
    158 
    159     @classmethod

~\AppData\Local\Continuum\anaconda3\lib\site-packages\modin\engines\base\io\sql\sql_reader.py in read(cls, sql, con, index_col, **kwargs)
     60             return cls.single_worker_read(sql, con=con, index_col=index_col, **kwargs)
     61         row_cnt_query = "SELECT COUNT(*) FROM ({}) as foo".format(sql)
---> 62         row_cnt = pandas.read_sql(row_cnt_query, con).squeeze()
     63         cols_names_df = pandas.read_sql(
     64             "SELECT * FROM ({}) as foo LIMIT 0".format(sql), con, index_col=index_col

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    410             coerce_float=coerce_float,
    411             parse_dates=parse_dates,
--> 412             chunksize=chunksize,
    413         )
    414 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1631 
   1632         args = _convert_params(sql, params)
-> 1633         cursor = self.execute(*args)
   1634         columns = [col_desc[0] for col_desc in cursor.description]
   1635 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
   1596 
   1597             ex = DatabaseError(f"Execution failed on sql '{args[0]}': {exc}")
-> 1598             raise ex from exc
   1599 
   1600     @staticmethod

DatabaseError: Execution failed on sql 'SELECT COUNT(*) FROM (SELECT * from TABLE;

SELECT  * FROM TBALE as nameAlias} ${WHERE condition}) as foo': ('42000', '[42000] Syntax error or access violation (27) (SQLExecDirectW)')

Thanks.

**Comment by knyats** [comment]
Hi,

I am trying to use modin.pandas to  query an IBM DB2 table. DB2 does not use the LIMIT keyword so I am getting an error from the line in your code
"SELECT * FROM ({}) as foo LIMIT 0".format(sql), con, index_col=index_co

Error message
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "LIMIT" was found following "".  Expected tokens may include:  "FETCH FIRST <n> ROWS ONLY".  SQLSTATE=42601 SQLCODE=-104

**Comment by devin-petersohn** [comment]
Hi @knyats will you open a new issue for that syntax error? I do not want to lose track of it. Thanks!
