### ISSUE TITLE
Add SOCKS5 SSH proxy support in Ray

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#1539]
Related to #1538, enables running Modin with Ray autoscaler in a typical enterprise network.

**Comment by vnlitvinov** [comment]
@anmyachev here's the first try to add proxy support: https://github.com/vnlitvinov/ray/tree/add-ssh-proxy

It reads another parameter from `auth` section of the `.yml` file named `ssh_proxy_command` and, if it's non-empty, adds it as `-o ProxyCommand=that_value`.

**Comment by anmyachev** [comment]
@vnlitvinov Nice! We should also apply next patch to your proxy changes:

```patch
diff --git a/python/ray/autoscaler/ray-schema.json b/python/ray/autoscaler/ray-schema.json
index d48f4f231..9a72b329f 100644
--- a/python/ray/autoscaler/ray-schema.json
+++ b/python/ray/autoscaler/ray-schema.json
@@ -156,7 +156,10 @@
                 },
                 "ssh_private_key": {
                     "type": "string"
-                }
+                },
+               "ssh_proxy_command": {
+                   "type": "string"
+               }
             }
         },
         "docker": {
@@ -239,4 +242,4 @@
             "description": "Whether to avoid restarting the cluster during updates. This field is controlled by the ray --no-restart flag and cannot be set by the user."
         }
     }
-}
\ No newline at end of file
+}
```

**Comment by vnlitvinov** [comment]
Per discussion with Ray devs, I'll be changing the PR there back to specify full `ProxyCommand`, then they would hopefully accept it.

**Comment by vnlitvinov** [comment]
Fixed by https://github.com/ray-project/ray/pull/8833 - now there is an optional `ssh_proxy_command` option under `auth` which, if present, is passed as-is to `ssh` as `-o ProxyCommand=<value>`. For now it requires using Ray from `master`.
