### ISSUE TITLE
Support H2O groupby queries in OmnisciOnRay engine

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1541]
We need to cover aggregation API used in H2O groupby queries. Issue doesn't cover other features required for H2O benchmarks (type cast, data transfer etc.)

Current status:
 - [x] Query #1
 - [x] Query #2
 - [x] Query #3
 - [x] Query #4
 - [x] Query #5
 - [ ] Query #6
 - [x] Query #7 - modified to avoid assign
 - [ ] Query #8
 - [ ] Query #9
 - [x] Query #10

**Comment by ienkovich** [comment]
Current issues with remaining queries:

Query #6 - we need to implement std and median aggregators in OmniSci

Query #8 - we need to use window functions to implement groupby.head method. Unfortunately, OmniSci doesn't preserve rows order in partitions when window function is applied without order by. In our case we have sorted order prior groupby call. So, it is possible to translate, but requires sort_values implementation to become backend specific first.

Query #9 - here we have grouby.apply with lambda. Passed lambda uses unsupported corr aggregate. Also it returns new Series built on cell values extracted from corr result. With would be very challenging to support using lazy computations.

**Comment by anmyachev** [comment]
@ienkovich is this still relevant?
