### ISSUE TITLE
Support taxi queries in Modin

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1548]
Taxi queries for Modin could  look like this:
    q1_pandas_output = df.groupby("cab_type").size()
    q2_pandas_output = df.groupby("passenger_count").agg({"total_amount": "mean"})    
    q3_pandas_output = df.groupby(["passenger_count", df["pickup_datetime"].dt.year]).size()
    q4_pandas_output = (df.groupby(["passenger_count", df["pickup_datetime"].dt.year, df["trip_distance"].round(),])
        .size().reset_index().sort_values(by=["pickup_datetime", 0], ascending=[True, False])

**Comment by Garra1980** [comment]
First query already works while sizes calculation is done on Modin side

**Comment by Garra1980** [comment]
Second query works on Modin as well

**Comment by ienkovich** [comment]
> First query already works while sizes calculation is done on Modin side

It's not clear what exactly is computed on Modin side. Currently we cannot perform groupby with no aggregates in OmniSci and return the result for additional processing in Modin. Does it mean we hit a default pandas execution branch somehow?

**Comment by Garra1980** [comment]
Will try support first query as q1_pandas_output = df.groupby("cab_type").agg({"cab_type": "size"}) then

**Comment by Garra1980** [comment]
Actually we had to do smth like res=df.groupby("cab_type").agg({"pasenger_count": "size"}) which is now supported in omnisci-modin. All necessary for  res = df.groupby("cab_type").size() seems to be in #1534 so we can try to pull everything into omnisci engine after that PR is finished. But for now q1 is ok using agg function

**Comment by Garra1980** [comment]
q3/q4 is in progress, support for dt_year is in review stage - https://github.com/intel-go/modin/pull/26, translation of groupby for modified columns is in progress

**Comment by Garra1980** [comment]
Q4 implementation depends on https://github.com/modin-project/modin/issues/1577

**Comment by Garra1980** [comment]
We may need resolving of https://github.com/modin-project/modin/issues/1592 for q3/q4

**Comment by Garra1980** [comment]
Initial support is here - https://github.com/intel-go/modin/pull/28
it is also occurred that when as_index=False in groupby query pandas outputs only groupby columns which are from original frame, i.e. if we have df.[col].dt.year in groupby arguments it will not be output. This needs to be handled as well

**Comment by Garra1980** [comment]
Need to add q4 test in our omnisci-on-ray branch

**Comment by Garra1980** [comment]
Q4 test added
