### ISSUE TITLE
Support median and std aggregates in OmniSci backend

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1574]

**Comment by ienkovich** [comment]
Prototype for stddev was implemented in OmniSci. It covers only a single hash table layout and doesn't support reduction (so, works for tables with a single fragment). Prototype version works for a simple groupby.agg testcase, but it looks we need to spend too much time to make this patch working in all cases.

For now I stop work on direct stddev support in OmniSci and start work on std support on Modin side (to decompose std into simpler aggregates and math ops)

**Comment by ienkovich** [comment]
intel-go/modin#58 added support for std in groupby.agg

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
