### ISSUE TITLE
Dataframe.sparse and Series.sparse property accessors are not implemented

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1584]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+110.g6637572

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

### Describe the problem

`sparse` property accessor should allow access to `.density` property and `.from_spmatrix`, `.to_coo`, `.to_dense` functions. See https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#api-frame-sparse

**Comment by dchigarev** [comment]
All sparse accessors were added in #2318, however all of them are defaulting to pandas

**Comment by pyrito** [comment]
Trying this on latest master and it seems that the property accessors are implemented now, but as @dchigarev they are defaulting to pandas. I think the main issue here has been resolved, so I'm going to close this issue.
