### ISSUE TITLE
Groupby.apply results are transposed when apply function returns a scalar

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1587]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+115.g16c28a4

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "col1": ["a", "a", "a", "b", "b", "c", "c", "c"],
        "col2": [10, 20, 30, 40, 50, 60, 70, 80],
    })

def func(data):
    return 111.11

print(df)
gb = df.groupby("col1")
print(gb.groups)

df1 = gb.apply(func)
print(df1)
print(df1.shape)
```

### Describe the problem

When running on Pandas the resulting DataFrame has shape `(3,)`:
```
col1
a    111.11
b    111.11
c    111.11
dtype: float64
(3,)
```

while on Modin it has shape `(1, 3)`:
```
col1       a       b       c
col1
0     111.11  111.11  111.11
(1, 3)
```

**Comment by pyrito** [comment]
Running this on latest master and I'm seeing this output instead:
```
      __reduced__
col1             
a          111.11
b          111.11
c          111.11
(3, 1)
```

**Comment by pyrito** [comment]
I'm hoping this will get resolved with the rewrite of groupby.

**Comment by YarShev** [comment]
Works on latest master for me so closing.
