### ISSUE TITLE
CI Comments on Github that tests are passed when they are failed

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1604]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+118.gf2cc740

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

### Describe the problem

Sometimes when word `FAILURES` is truncated comment script show that tests passed. For example in this comment https://github.com/modin-project/modin/pull/1603#issuecomment-644367411

**Comment by vnlitvinov** [comment]
@gshimansky I think this can now be closed?

**Comment by gshimansky** [comment]
Yes
