### ISSUE TITLE
Add checks on executed frame to validate result's scheme

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1607]
We need to add some checks for OmniSci engine on execution result to check its scheme matches desired frame. This would allow to detect incorrect Calcite plans more early.

**Comment by ienkovich** [comment]
Right now in many cases we get different dtypes for columns after uploading execution result back to Pandas. E.g. bool becomes int, category becomes object, int8 becomes int64, NULL column become object etc. Hope we will have more control over it when start using Arrow tables for data exchange. Until then only limited checks can be added

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
