### ISSUE TITLE
Load data to modin from pandas

### ISSUE THREAD

**Issue by Nishant23** [modin-project/modin#1609]
Hi,

How to convert pandas dataframe to modin dataframe? Dask has method from_pandas to load data from pandas data frame, does it have similar function for this?

**Comment by devin-petersohn** [comment]
Hi @Nishant23, thanks for the question!

You can just pass it to the `DataFrame` constructor like this:

```
import pandas
import modin.pandas as pd

pandas_df = pandas.DataFrame(...)  # pandas
modin_df = pd.DataFrame(pandas_df)  # modin
```

We felt this was the most intuitive way, and it also works in pandas to pass a `DataFrame` to the `DataFrame` constructor.

**Comment by Nishant23** [comment]
Thanks @devin-petersohn .
