### ISSUE TITLE
Passing MultiIndex to loc leads to keyError

### ISSUE THREAD

**Issue by 513090336** [modin-project/modin#1610]
DataFrame result has colums, ['code_jq', 'time', 'factor', 'close'].

> result = result.set_index(['code_jq', 'time']).sort_index(ascending=False);
cut = result.groupby(['code_jq'])['factor'].apply(lambda x: len(x) >= total_days - 10);
result = result.loc[cut[cut].index]

When the program runs to this line of code, `result = result.loc[cut[cut].index]` ,it shows keyerror that means dataframe can't find keys. 

Is anyone know why and how to solve it?

**Comment by devin-petersohn** [comment]
Hi @513090336, thanks for the report. I was able to reproduce what you're seeing, it is an issue with `loc` and MultiIndex. We will get this fixed.

As a temporary workaround, you can use this code:

```python
result = result.set_index(['code_jq', 'time']).sort_index(ascending=False);
cut = result.groupby(['code_jq'])['factor'].apply(lambda x: len(x) >= total_days - 10)
indexer = cut.index.get_indexer_for(cut[cut].index)
result = result.iloc[indexer]
```

**Comment by 513090336** [comment]
Thank you！you helps me a lot.
