### ISSUE TITLE
Creating Series with category dtype leads to inconsistent object

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1628]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 1809
- **Modin version** (`modin.__version__`): 0.7.3+129.g793eafd.dirty
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
if __name__ == "__main__":
    import numpy as np
    import modin.pandas as pd

    kwargs = {
        "data": np.arange(256),
        "dtype": "category",
    }

    md_series = pd.Series(**kwargs)
    print(md_series.max())

```

### Describe the problem
After that way of creating modin Series (with category dtype), its behavior is unpredictable. Some operations may give incorrect answers (for ex. `max`), others would throw an exception (for ex. `to_pandas`), another would raise an internal error (for ex. `to_numpy`).

The output of related code will be:
```
223
```
But it's obvious that it must be a `255`.
### Source code / logs
If we would print content of Series partitions, we will see that index and values lengths of `__reduced__` column is different:
```
>>> md_series._query_compiler._modin_frame._partitions[0][0].to_pandas()
   __reduced__
0            0
1            1
2            2
3            3
4            4
..         ...
59          27
60          28
61          29
62          30
63          31

[64 rows x 1 columns]
>>> len(md_series._query_compiler._modin_frame._partitions[0][0].to_pandas()["__reduced__"].values)
32
>>> len(md_series._query_compiler._modin_frame._partitions[0][0].to_pandas()["__reduced__"].index)
64
```
So, the partition contains invalid pandas DataFrame. It seems that the problem is in a way how we splitting pandas DataFrame into partitions:
https://github.com/modin-project/modin/blob/e6e24496becb6bb9ddf4dfb9d10448d1a799d459/modin/engines/base/frame/partition_manager.py#L291-L301
The thing is, that when pandas DataFrame contains only one column and its `dtype=category` (this is the case, when we're creating modin Series with category dtype) then `iloc` slicing behaves strange.
Example:
```
>>> import pandas
>>> pandas.__version__
'1.0.3'
>>> df = pandas.DataFrame([1,2,3,4,5], dtype="category")
>>> df.iloc[0:5, 0:2]
   0
0  1
1  2
2
3
4
>>> len(df.iloc[0:5, 0:2].index)
5
>>> len(df.iloc[0:5, 0:2].values)
2
```
Not sure if this a documented behavior or there is a bug in Pandas, but that seems to be causing the problem in modin also

**Comment by mvashishtha** [comment]
> I think all we have to do to close this issue is to add a test for categorical Series creation and make sure that it passes.

@dchigarev What exactly do you want to test about a categorical Series in Modin?

**Comment by dchigarev** [comment]
At least the original reproducer from the head of this issue. Previously this one was giving an incorrect result for `max`, I'd like to ensure that it's not the case now.
<details><summary>Reproducer</summary>

```python
if __name__ == "__main__":
    import numpy as np
    import modin.pandas as pd

    kwargs = {
        "data": np.arange(256),
        "dtype": "category",
    }

    md_series = pd.Series(**kwargs)
    print(md_series.max())  # Previously it was printing '223', when the correct answer is '255'
```

</details>

**Comment by mvashishtha** [comment]
When I run that code now with Modin version `0.11.1+32.gef2159be`, I just get 

`nan`

With pandas, I get 

```
TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one
```

Modin does not match pandas there, but it seems that neither one should give a numerical.

**Comment by dchigarev** [comment]
Hmm, it's interesting that previously it worked somehow.

Anyway, judging by `dir(pandas.Categorical([1, 2]))` categories still have some aggregations functions, for example, `count`, its implementation in Modin (as well as the sum) follows the MapReduce approach, so doing `count` should be equivalent to `sum` in terms of code/logic coverage.

**Comment by devin-petersohn** [comment]
@dchigarev I don't fully follow what you're saying. Do you think we should be testing pandas Categoricals?

**Comment by dchigarev** [comment]
No, I meant that we should test Modin DataFrames holding categorical data based on what `pandas.Categorical` actually supports. Above there was a [message](https://github.com/modin-project/modin/issues/1628#issuecomment-955114445), mentioning `pandas.Categorical` does not support `sum` for unordered categories, so I proposed to test something that categoricals natively support, for example, `count` and `.to_numpy()`.

```python
def test_categorical():
    pd_df = pandas.DataFrame(**categorical_data)
    md_df = pd.DataFrame(**categorical_data)

    df_equals(md_df.count(), pd_df.count())
    df_equals(md_df.to_numpy(), pd_df.to_numpy())
```
