### ISSUE TITLE
Support constructions like df.groupby(["a"]).agg({"a":"sum"}) or 

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1639]
We also fail on df.groupby("a").size() where a is first column in df.
Currently we can't handle such cases since eg we don't support columns (no matter what columns, index or regular) with same names

**Comment by anmyachev** [comment]
@Garra1980 the following code works. Can we close this issue?

```python
df = pd.DataFrame({"col1": [1,2,3,5], "col2": [5,6,4,2]})
print(df.groupby(["col1"]).agg({"col1": "sum"}))  # works
print(df.groupby("col1").size())  # works
```
