### ISSUE TITLE
Setup build process for Omnisci with DB engine enabled

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1652]
When we build omnisci with -DENABLE_DBE=on we need to have some python env to create all necessary components for dbe import. 
We need to setup correct procedure for this

**Comment by Garra1980** [comment]
Also currently there is a problem with linkage for dbe.so - under some conditions libDBEngine.so is not visible

**Comment by Garra1980** [comment]
Looks like cmakefile for Embedded and setup.py for cythonizing should be revised

**Comment by Garra1980** [comment]
Several PRs were made intended to improve build process:
https://github.com/intel-go/omniscidb/pull/46
https://github.com/intel-go/omniscidb/pull/47

**Comment by Garra1980** [comment]
Currently consume_arrow_branch can be build by following steps:
- open new shell
- from omnisci root folder launch conda env create -f scripts/mapd-deps-conda-dev-env.yml --force
- conda activate omnisci-dev
- configure with cmake .. -DCMAKE_BUILD_TYPE=debug|release -DENABLE_CUDA=off -DENABLE_TESTS=off -DENABLE_FSI=ON -DENABLE_DBE=ON -DENABLE_AWS_S3=OFF
- make -jN
- cd build_dir/Embedded && python setup.py install -f

**Comment by Garra1980** [comment]
https://github.com/intel-go/omniscidb/pull/49 - PR that should improve build/install process so last step would be 
- make -jN && make install

**Comment by aregm** [comment]
Please, create public PR against OmniSci master

**Comment by Garra1980** [comment]
> Please, create public PR against OmniSci master

Will add it to existing PR

**Comment by Garra1980** [comment]
At the moment checked in intel-go/omniscidb/modin branch

**Comment by Garra1980** [comment]
**Current flow to use omnisci engine in modin is as follows (requires conda)**: 
checkout https://github.com/intel-go/omniscidb/tree/modin branch 
сd omnisci_root_folder

conda env create -f scripts/mapd-deps-conda-dev-env.yml --force

conda activate omnisci-dev

bash scripts/conda/build-install-all.sh

As a result omnisci-dev env will contain dbe

 

**To run omnisci engine specific tests**:
conda activate omnisci-dev

Checkout modin's branch https://github.com/intel-go/modin/tree/omnisci-on-ray

pip install ray==0.8.6

conda install pytest -c conda-forge

conda install pytest-cov -c conda-forge

conda install pytest-custom-exit-code -c conda-forge

PYTHONPATH=path_to_modin_root pytest modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py

To run you own test - see beginning of test_dataframe.py as a template

**Comment by anton-malakhov** [comment]
Modin tests also need ` conda install -c conda-forge matplotlib sqlalchemy`
