### ISSUE TITLE
[omnisci][FSI] data is null in setNullValues

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1663]
### Describe the problem
Find out proper solution for data == nullptr here: https://github.com/intel-go/omniscidb/blob/consuming_arrow_table/DataMgr/ForeignStorage/ArrowForeignStorage.cpp#L156-L177

**Comment by fexolm** [comment]
Should be fixed in https://github.com/intel-go/omniscidb/pull/48
