### ISSUE TITLE
`Series.apply("array")` doesn't work if Series contains one element 

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#1674]
### Describe the problem

The problem is occurred if we call method of `Series` that contains one element. It happens because of we use direct method call of inner df ([see example](https://github.com/modin-project/modin/pull/1657/files#diff-db8dc531e116caee2b9cc5ccbcc5c642R1437)). In this case `array` method will be called from `pandas.DataFrame`, but `pandas.DataFrame` doesn't support it. In order to call method from `Series` we should use `squeeze(axis=1)` for df. An example of exception is below:

### Source code / logs

```python
import modin.pandas as pd
s = pd.Series([1])
s.apply("array")
AttributeError: 'DataFrame' object has no attribute 'array'
```

**Comment by amyskov** [comment]
PR with fix currently unblocked and can be reviewed.

**Comment by amyskov** [comment]
PR is still under review/corrections.
