### ISSUE TITLE
df.loc[row][column] = value has no effect

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1675]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+165.g9721d46

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df = pd.DataFrame(index=["a", "b", "c"], columns=["col1"])
df.loc["a"]["col1"] = 123
df.loc["b"]["col1"] = 321
df.loc["c"]["col1"] = 444
print(df)
```

### Describe the problem

Assigning to `df.loc[row][column]` as no effect and dataframe contents remains all `NaN`.

**Comment by devin-petersohn** [comment]
Related to https://github.com/modin-project/modin/issues/1556

**Comment by gshimansky** [comment]
Yes the same problem must have happened in #1556 because `loc` and `iloc` don't initialize resulting `Series._parent` field.
