### ISSUE TITLE
DataFrame.astype(int) has no effect

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1678]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+166.g00f57f1.dirty

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df = pd.DataFrame(index=["row1", "row2", "row3"], columns=["col1"])
df.loc["row1"]["col1"] = 11
df.loc["row2"]["col1"] = 21
df.loc["row3"]["col1"] = 31
print(df)
print(df.dtypes)
df1 = df.astype(int)
print(df1)
print(df1.dtypes)
```

### Describe the problem

When DataFrame is first created without any contents, all of its columns are marked as `object` type. Even when it is filled with integers it doesn't change anything. But when `astype(int)` is called, column types should change to `int`. This happens on Pandas but doesn't happen on Modin.

**Comment by me9hanics** [comment]
I'm having a possibly more general. I have a Pandas series with floats, that all represent years, such as 1937.0 or 1989.0, and I want to convert them to integers.

```
0       1937.0
1       1968.0
2       1974.0
3       1909.0
4       1931.0
         ...  
2452       NaN
2453    1900.0
2454    2001.0
2455       NaN
2456       NaN
Name: FirstYear, Length: 2457, dtype: float64
```

I tried `artists['FirstYear'] = artists['FirstYear'].astype(int, errors='ignore')`, but it did not change anything, the output of `artists['FirstYear'].astype(int, errors='ignore')` is still containing floats.<br>
When I tried _apply_, that did not help either: `artists['FirstYear'] = artists['FirstYear'].apply(lambda x: int(x) if pd.notnull(x) else x)
` still leads to the same result.
But most interestingly, if I go value by value manually, even then it does not work: 
```
t = artists['FirstYear'].copy()
for x in t:
    if not np.isnan(x):
        x = int(x) #Tried t = t.replace(x, int(x)) and t[t==x] = int(x) too
```

In fact, I found that whilst int(t[0]) returns the correct value,` t[0]=int(t[0])` also does not change the value to int inside the cell. If I run something like` t[0] = 1,` then the first element will be float: 1.0.

I see that this is probably a problem with the series having _dtype: float64_ therefore it does not let element-wisely convert to an int, but this should be worked around in .astype(int) in my opinion. 

**Details**: Windows 11, Python 3.10.11, Pandas 2.1.3

**Comment by YarShev** [comment]
Hi @me9hanics, what you are trying to do is the expected behavior in pandas. I guess you would need to create an issue in pandas repo and clarify there the behavior you want to see (if it is appropriate).

An example of code you used from my point of view.

```python
import pandas
import numpy as np

s = pandas.Series(list(range(64)))
s[0] = np.nan
s.astype(int, errors='ignore')
0      NaN
1      1.0
2      2.0
3      3.0
4      4.0
      ...
59    59.0
60    60.0
61    61.0
62    62.0
63    63.0
Length: 64, dtype: float64
```
