### ISSUE TITLE
DataFrame.apply produces transposed result

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1686]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+167.gc685f41.dirty

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "col1": ["a", "a", "a", "b", "b", "c", "c", "c"],
        "col2": [10, 20, 30, 40, 50, 60, 70, 80],
    })

print(df)
df1 = df.apply(lambda s: pd.Series([111.11, 222.22], index=['aa', 'bb']))
print(df1)
print(df1.shape)
```

### Describe the problem

Result here is quite different in Modin compared to Pandas. Bug looks similar to DataFrameGroupBy.apply() bugs #1682 and #1587.

**Comment by pyrito** [comment]
As of latest master the results seem to be matching pandas, so I will close this issue.
