### ISSUE TITLE
AttributeError: module 'numpy.random' has no attribute 'randomState'

### ISSUE THREAD

**Issue by luoyunan** [modin-project/modin#1692]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin version** (`modin.__version__`):  0.7.4
- **Python version**: 3.7.6
- **Code we can use to reproduce**: 
```python
import modin.pandas as mpd
import numpy as np

rng = np.random.RandomState(42)
df = mpd.DataFrame(np.random.rand(100, 3))
df = df.sample(n=50, random_state=rng)
```

### Describe the problem

The `DataFrame.sample()` function, when passed the `random_state` argument, raised an AttributeError when calling Numpy (I'm using Numpy 1.18.5). See tracebacks below. 

### Source code / logs

It looks like in `base.py` Line 2483, `np.random.randomState` should be `np.random.RandomState`.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-667e79aa734e> in <module>
      1 rng = np.random.RandomState(42)
      2 df = mpd.DataFrame(np.random.rand(100, 3))
----> 3 df = df.sample(n=50, random_state=rng)

/export/home/software/anaconda3/lib/python3.7/site-packages/modin/pandas/base.py in sample(self, n, frac, replace, weights, random_state, axis)
   2481             if isinstance(random_state, int):
   2482                 random_num_gen = np.random.RandomState(random_state)
-> 2483             elif isinstance(random_state, np.random.randomState):
   2484                 random_num_gen = random_state
   2485             else:

AttributeError: module 'numpy.random' has no attribute 'randomState'
```

**Comment by devin-petersohn** [comment]
Hi @luoyunan thanks for posting this! I can reproduce the issue you are seeing on the current master.

As a temporary workaround until the next release, you can pass the integer value `42` instead of creating your own `RandomState` object.

Since it is a very minor fix and you went to the source to find it, would you like to open a PR that fixes this and adds a test case?
