### ISSUE TITLE
Automatical data folder creation/usage when db engine is enabled

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1693]
Currently when working through Omnisci db engine we need to write smth like
```
from dbe import PyDbEngine as PDE
pdb = PDE("data", 8874)
```

where data is the folder that should be created manually. 
We need to get rid of such actions. I think we should leave possibility of specifying concrete values but always be able to deal with default ones

And by the way the same is true for calcite port number

**Comment by igalink** [comment]
Fixed in Pr: https://github.com/intel-go/omniscidb/pull/56
