### ISSUE TITLE
Support read_csv features for mortgage benchmark

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1699]
In mortgage different parameters are used during data import:

**names, dtype, skiprows, delimiter, parse_dates( there is separate #1696 for it)**

We need to add support for all of them to be able to run mortgage with omnisci engine

**Comment by anton-malakhov** [comment]
one by one, connecting options between pandas and Arrow.

**Comment by Garra1980** [comment]
parse_dates is the top since it is needed both in taxi and mortgage

**Comment by Garra1980** [comment]
Short reproducer from mortgage:
```
import os
os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd
cols = ["seller_name", "new_name"]
dtypes = {'seller_name':'category', 'new_name':'category'}
df = pd.read_csv("names_small.csv", names=cols, dtype=dtypes, delimiter=",")
```

names_small.csv:
```
"seller_name"|"New"
"WITMER FUNDING|LLC","Witmer"
"WELLS FARGO CREDIT RISK TRANSFER SECURITIES TRUST 2015","Wells Fargo"
"WELLS FARGO BANK| NA","Wells Fargo"
```

Currently we have exception during read_csv:
 File "/localdisk/izamyati/modin/modin/experimental/engines/omnisci_on_ray/io.py", line 94, in read_csv
    raise "abrakadabra"

**Comment by anton-malakhov** [comment]
дебажный ассет - значит в эрроу не сработало и можно идти по пандовому пути

**Comment by anton-malakhov** [comment]
done from this side, next one is #1698

**Comment by anton-malakhov** [comment]
testing revealed some issues, fixing, investigating

**Comment by anton-malakhov** [comment]
Using "_to_pandas" it works now:
```
                rp = pd.read_csv(self.csv_file, **kwargs)
                rm = mpd.read_csv(self.csv_file, **kwargs)._to_pandas()
                assert_almost_equal(rm, rp,
                    check_dtype=False,
                    check_less_precise=2,
                    )
``` @ienkovich

**Comment by devin-petersohn** [comment]
@anton-malakhov We can add a new internal `df_almost_equals` or some utility like that.
