### ISSUE TITLE
Modin Pandas concat with axis=1 does not work

### ISSUE THREAD

**Issue by pashkov-v** [modin-project/modin#1700]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.4 LTS
- **Modin version** (`modin.__version__`): 0.7.4
- **Python version**: 3.8.0

### Describe the problem
When I try to concatenate several Modin Pandas DataFrames of equal number of rows column-wise, I get either `KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'` (when `ignore_index=False`), or `ValueError: Length mismatch:` (with `ignore_index=True`).

### Source code / logs
```
import numpy as np
import modin.pandas as modin_pd
modin_pd.concat([modin_pd.Series(np.ones(10)), modin_pd.Series(np.ones(10))], axis=1, ignore_index=True)
```

**Comment by devin-petersohn** [comment]
Hi @pashkov-v thanks for the report!

I can reproduce this with the code you provided on current master branch. It looks like a metadata issue at the API layer because `_to_pandas` on the result produces a correct result.

```python
import numpy as np
import modin.pandas as modin_pd
modin_pd.concat([modin_pd.Series(np.ones(10)), modin_pd.Series(np.ones(10))], axis=1, ignore_index=True)._to_pandas()
```
