### ISSUE TITLE
 self._query_compiler.columns RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by deepalib-cuelogic** [modin-project/modin#1706]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

**Comment by devin-petersohn** [comment]
Hi @deepalib-cuelogic thanks for posting!

We need more information to reproduce and fix this issue. Can you share the code that produced this error? Thanks!

**Comment by pyrito** [comment]
Closing due to lack of information/reproducer.
