### ISSUE TITLE
Wrong output for DataFrame aggregations with level parameter

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#1709]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.7.3+197.g8602fc0
- **Python version**: 3.8.3
- **Code we can use to reproduce**:
```
import modin.pandas as pd
import pandas

data = {"col1": [1, 2, 3], "col2": [11, 12, 13]}
index = [[4, 4, 5], [6, 7, 7]]
df_pandas = pandas.DataFrame(data, index=index)
df_modin = pd.DataFrame(data, index=index)

print("df_pandas.sum(level=0)\n", df_pandas.sum(level=0))
print("df_modin.sum(level=0)\n", df_modin.sum(level=0))
```
Output:
```
df_pandas.sum(level=0)
    col1  col2
4     3    23
5     3    13
df_modin.sum(level=0)
 col1     3
col2    23
dtype: int64
```

### Describe the problem
Level parameter doesn't handled by `DataFrame.sum` function, probably we should use `base.py::_handle_level_agg` function like it is done in the `count` function.

**Comment by devin-petersohn** [comment]
This is a P0 issue, moving back to 0.8.0 release. I will take this one.

**Comment by devin-petersohn** [comment]
Combining with #1710, #1711, #1712, #1713, #1714, #1715, #1716

**Comment by devin-petersohn** [comment]
Also needed is a fix for `min`.

**Comment by Garra1980** [comment]
Do we still need something here?

**Comment by amyskov** [comment]
Basing on 2ca3f34b2c3c22bf285c0349d35a5099de3a2e78 commit, problem is solved for `sum`, `median`, `prod`, `std`, `var` functions and still exists for `mean`, `max` functions.

**Comment by Garra1980** [comment]
@devin-petersohn - do you plan to look at it for release?

**Comment by devin-petersohn** [comment]
Yes, many things have jumped in priority and I haven't had the chance yet but I still plan to.

**Comment by amyskov** [comment]
Now using of `level` parameter triggers pandas implementation, so issue can be closed.

**Comment by devin-petersohn** [comment]
I have an implementation started here: https://github.com/modin-project/modin/pull/2758. The order is the only difference.

**Comment by amyskov** [comment]
@devin-petersohn https://github.com/modin-project/modin/pull/2758 was merged, can this issue be closed?

**Comment by devin-petersohn** [comment]
Yes, I believe it can be closed.
