### ISSUE TITLE
Wrong output for DataFrame.std with level parameter

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#1714]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.7.3+197.g8602fc0
- **Python version**: 3.8.3
- **Code we can use to reproduce**:
```
import modin.pandas as pd
import pandas

data = {"col1": [1, 2, 3], "col2": [11, 12, 13]}
index = [[4, 4, 5], [6, 7, 7]]
df_pandas = pandas.DataFrame(data, index=index)
df_modin = pd.DataFrame(data, index=index)

print("df_pandas.std(level=0)\n", df_pandas.std(level=0))
print("df_modin.std(level=0)\n", df_modin.std(level=0))
```
Output:
```
df_pandas.std(level=0)
        col1      col2
4  0.707107  0.707107
5       NaN       NaN
df_modin.std(level=0)
 col1    0.707107
col2    0.707107
dtype: float64
```

### Describe the problem
Level parameter doesn't handled by `DataFrame.std` function, probably we should use `base.py::_handle_level_agg` function like it is done in the `count` function.

**Comment by devin-petersohn** [comment]
Close to track #1709
