### ISSUE TITLE
Implement arrow pipeline for record batch returned as result of omnisci's execution

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1721]
Please take a look here, result is converted to pandas DataFrame, but can be better integrated with arrow pipeline: 
https://github.com/intel-go/modin/blob/9863079318765c424a90dc034780a9f1868aee7a/modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py#L85-L88

**Comment by ienkovich** [comment]
Related patches are in intel-go/modin#57
