### ISSUE TITLE
Enable lazy read arrow table in omnisci backend

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#1725]
In some cases we can skip parsing some columns by enabling lazy evaluation in reading arrow table.
Example:
```python
df = read_csv("name")
df = df[['a', 'b']]
```

**Comment by anton-malakhov** [comment]
I think it is more on compiler side, isn't it, Ilya?

**Comment by ienkovich** [comment]
I'm not sure we should try to perform such optimization, because multiple projections from the original dataframe could cause multiple csv reads. Do we really need this optimization to match some framework's performance?

**Comment by anton-malakhov** [comment]
lazy arrow table conversion is implemented by Ilya already.

**Comment by Garra1980** [comment]
Do we still need this?

**Comment by fexolm** [comment]
I agree with Ilya, that it could cause multiple csv reads, which we don't really want. If noone else has thoughts about why we could need such optimization then we could close this, I think.

**Comment by fexolm** [comment]
I agree with Ilya, that it could cause multiple csv reads, which we don't really want.
The other point is that in some cases we could skip read_csv at all. When I created a ticket, there was no lazy csv reading at all, arrow read_csv was executed immediately on read_csv call (the only lazynes was in defered consumeArrowTable call), I'm not sure if something changed, but if it didn't change, I think it shouldn't be tricky to defer table reading to the first materialization.

**Comment by ienkovich** [comment]
The original request is not very specific and doesn't come from the real need. Also lazy read_csv would most probably make more harm, then give gain. So, I'm closing this issue. We can get back to this feature later if real need appears.
