### ISSUE TITLE
Wrong result for SQL request in embedded OmniSci

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1735]
import pyarrow
import sys;
sys.setdlopenflags(1 | 256)
import dbe
import pandas

engine = dbe.PyDbEngine('data', 6001, False)

data = {"a": [1, 1, None]}
df = pandas.DataFrame(data, columns=['a'])
at = pyarrow.Table.from_pandas(df)

engine.consumeArrowTable('t1', at)

cursor = engine.executeDML("SELECT (CASE WHEN a IS NULL THEN 1 ELSE a END) as a FROM t1")
rb = cursor.getArrowRecordBatch()
df1 = rb.to_pandas()
print(df1)

The result contains NaN but only '1' values expected. This test reproduces a problem for many fillna tests which fail with embedded OmniSci. With regular table in OmniSci server the result is correct, so I assume the issue might be caused by using FSI (probably has_nulls metainfo is incorrect and CASE expr is 'optimized'?).

**Comment by fexolm** [comment]
Fixed by https://github.com/intel-go/omniscidb/pull/54
With follow up #1755
