### ISSUE TITLE
FLOOR function doesn't work in embedded OmniSci

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1742]
Here is a set of queries I successfully run on OmniSci server:

```
CREATE TABLE t1 (a integer);
INSERT INTO t1 VALUES (1);
SELECT FLOOR(a / CAST(0.5 AS DOUBLE)) FROM t1;
```

It also works if I create table using CREATE DATAFRAME. Then I try to execute similar query using embedded engine:

```
import pyarrow
import sys;
sys.setdlopenflags(1 | 256)
import dbe
import pandas

data = {"a": [1]}
df = pandas.DataFrame(data)
table = pyarrow.Table.from_pandas(df)

engine = dbe.PyDbEngine('data', 6001)
engine.consumeArrowTable('t1', table)

cursor = engine.executeDML("SELECT FLOOR(a / CAST(0.5 AS DOUBLE)) FROM t1;")
rb = cursor.getArrowRecordBatch()
df1 = rb.to_pandas()
print(df1)
```

And get an error:
```
DBE:executeDML: Function FLOOR(DOUBLE) not supported.
Segmentation fault (core dumped)
```

**Comment by ienkovich** [comment]
Many functions (including math functions like FLOOR, LOG10 etc) are initialized from Calcite extension functions. There are two places with initialization:
DBHandler::DBHandler - https://github.com/intel-go/omniscidb/blob/develop/ThriftHandler/DBHandler.cpp#L286
QueryRunner::QueryRunner - https://github.com/intel-go/omniscidb/blob/develop/QueryRunner/QueryRunner.cpp#L145
We execute none of them and build QueryRunner using another constructor, which doesn't initialize extension functions.

**Comment by igalink** [comment]
Fixed in the PR : https://github.com/intel-go/omniscidb/pull/56
