### ISSUE TITLE
Fix memory leaks in omnisci embedded engine

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#1746]
It looks like we don't correctly free memory in some places in an embedded engine.
E.g cursors in cursors_ array never released.
Please check memory safety with some memcheck tools and fix the problems before upstreaming changes.

**Comment by Garra1980** [comment]
@fexolm could uou please elaborate a bit about cursors_array non-releasing?

**Comment by fexolm** [comment]
each cursor in cursors_ array allocates with `new` but delete is never called for that elements. Only cursors_.clear() which does not deallocate cursors.

**Comment by igalink** [comment]
Got rid of the list of cursors.
Replaced pointer to shared_ptr in cursor-returning functions.
Added a virtual destructor.
Updated tests.

PR: https://github.com/intel-go/omniscidb/pull/66

**Comment by igalink** [comment]
PR updated according the code review comments.
Pending re-review.
