### ISSUE TITLE
Modin CI fails with newer versions of Dask and Distributed

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#1749]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.7.3+230.g6ca8016
- **Python version**: 3.8.3
- **Code we can use to reproduce**:

### Describe the problem

Initially problem was introduced in #1722 and in order to enable CI, hot fix with Dask and Distributed packages downgrade (from 2.20.0 to 2.19.0 versions) was done in #1737. It's necessary to investigate the reason of the bug and enable Modin CI with newer versions of these packages.

**Comment by stonebig** [comment]
Dask-0.21.0 is out. does it fix the issue ?

**Comment by devin-petersohn** [comment]
@stonebig Thank you for commenting on this. We are finalizing testing for the next release, so we will test this right after that.

**Comment by devin-petersohn** [comment]
This was fixed by Dask. Thanks @stonebig
