### ISSUE TITLE
[modin] Support more than one partition in HDK

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1762]
https://github.com/intel-go/modin/blob/23a0fcc520ffad7e377ce4fc466a9a2488995272/modin/engines/base/frame/partition_manager.py#L323-L324

There is only one partition created (the link above).
We need multiple parts support in order to process them in parallel

**Comment by anmyachev** [comment]
HDK was removed in https://github.com/modin-project/modin/pull/7275
