### ISSUE TITLE
[Reminder]Make daal4py version in omniscripts requirements default again

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1769]
Currently we are making custom daal4py version in omniscripts requirements. This is temporary to see ML improvements right now for presentations. Later we need to set it to default once new daal4py is in conda permanently

**Comment by anmyachev** [comment]
@Garra1980 is it relevant?

**Comment by mvashishtha** [comment]
bump @Garra1980

**Comment by anmyachev** [comment]
Looks outdated. @Garra1980 feel free to reopen it if needed
