### ISSUE TITLE
Add ability to insert distributed columns at Pandas query compiler

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1772]
For now, there is no way to insert one or multiple columns in a dataframe at a specific location if you are working at the query compiler level, without materializing column and passing it into `insert`.

**Comment by devin-petersohn** [comment]
I agree, this can use something better than what we have. Right now, I would say use `concat`:

```python
return query_compiler.get_column_array(self.columns[:loc]).concat(1, new_value).concat(1, query_compiler.get_column_array(self.columns[loc:]))
```

No guarantee on it working as I wrote it 😄.
