### ISSUE TITLE
Make set_index implementation back-end specific

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1780]
Currently, set_index computes the resulting index in front-end. For lazy frames, we would like to delay index computation until the frame is finally materialized. To do that we need to move set_index logic into query compilers.

**Comment by dchigarev** [comment]
`set_index` implementation was partially moved to a backend by @devin-petersohn in #2666, so now if all keys is a frame column names (`set_index` also can obtain an index values as a key) then the call of `set_index` will be [redirected](https://github.com/modin-project/modin/blob/77d40ce26a0052a9739a677521efd0b5b9d8048c/modin/pandas/dataframe.py#L1591) to a query compiler method `.set_index_from_columns`. 

Currently, this should be enough for OmniSci backend to implement `set_index` in a lazy mode. However, cases when keys contain actual values of the index are still defaulting to pandas at the API level. @devin-petersohn what was the idea of keeping this at the front-end, is there are some logic you planed that should be exactly at the API layer, or this can be safely moved to the backend?

**Comment by devin-petersohn** [comment]
@dchigarev Which line are you referring to about defaulting to pandas?

**Comment by dchigarev** [comment]
@devin-petersohn 
https://github.com/modin-project/modin/blob/77d40ce26a0052a9739a677521efd0b5b9d8048c/modin/pandas/dataframe.py#L1568

**Comment by devin-petersohn** [comment]
I see, this is happening when the user passes in a list of index objects (or lists) to build a multiIndex. I think this is not a very common case, so it should be okay to let pandas handle the computation for now.

Previously we were handling this very similarly, since the objects being passed in are not distributed it may not make sense to worry too much about it right now.

**Comment by Garra1980** [comment]
Should we close this one and create another, more specific task?

**Comment by dchigarev** [comment]
@Garra1980 We can keep it, but point out that this task is not blocking #1766 anymore

**Comment by Garra1980** [comment]
That's okay, I was mostly wondering about release target - do we keep this task for 0.8.4 or not?

**Comment by dchigarev** [comment]
@Garra1980 Yes, I think we can remove P1 priority and remove this from 0.8.4 (or even close this task) because `set_index` logic that gotta be at the backend was already moved there in #2666.

**Comment by Garra1980** [comment]
:) Let's close it then?
