### ISSUE TITLE
ClusterError class should implement its own version of __str__ method

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#1781]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

`ClusterError` includes the `cause` field that is not printed. This makes it difficult to understand the problems that cause exceptions.

**Comment by devin-petersohn** [comment]
@anmyachev Is this a part of the next release 0.8.0?

**Comment by anmyachev** [comment]
> @anmyachev Is this a part of the next release 0.8.0?

Yes. I added the issue to 0.8.0 release.
