### ISSUE TITLE
Building and packaging for omnisci and modin

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1826]
## The goal is user-friendly installation of Modin with all the dependencies:

- [ ]   conda install -c intel modin
- [ ]   pip install modin[all] 

It implies:

- [ ]  Adding conda-forge/ray-feedstock
- [ ]  Adding omniscidb wheels to pypi (optional)
- [x]  Adding -c intel omniscidb packages
- [x]  Adding -c intel modin
- [ ]  Up-streaming omnisci recipes

**Comment by anton-malakhov** [comment]
Updated plan description. Status:
* implemented omnisci multi-packaging: https://github.com/intel-go/omniscidb/pull/73
* Omni-upstream sync: https://github.com/omnisci/omniscidb/pull/562

**Comment by anton-malakhov** [comment]
- Modin: https://github.com/intel-go/modin/pull/92

**Comment by anton-malakhov** [comment]
Upstream for cmake changes https://github.com/omnisci/omniscidb/pull/585

**Comment by Garra1980** [comment]
conda create -n test11 -c intel/label/test -c conda-forge modin=0.8.intel - this is how currently modin with omnisci could be installed

**Comment by anton-malakhov** [comment]
To build conda packages with conda-build:

1. conda install conda-build -n base
2. conda activate base
3. conda-build -c conda-forge scripts/conda
