### ISSUE TITLE
Upgrade to Pyarrow 1.0

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1844]
In #1377 we require `pyarrow<0.17`, but since Pyarrow 1.0 released, we should update to new stable API.

**Comment by itamarst** [comment]
Gandiva appears to be no longer part of the default pyarrow wheel.

There is an open issue to package it separately: https://issues.apache.org/jira/browse/ARROW-8518

**Comment by devin-petersohn** [comment]
Thanks @itamarst, this will be an issue in updating. Unfortunately that issue is slated for resolution in version 2. We probably will have to make the gandiva import conditional.
