### ISSUE TITLE
TypeError: reset_index() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by xuehui1991** [modin-project/modin#186]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by williamma12** [comment]
Hi, we have the an identical API to pandas 0.23.4 and [`reset_index`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.reset_index.html) does not take in the keyword argument `name`, which is likely the issue. However, if that is not the issue please provide a code sample and I'll look more into the issue.

**Comment by jaysnm** [comment]
Hi. I encountered this same error. Close look into the error revealed that reset_index() renamed index column from 'name' to index. See attached screenshot.
![reset_index](https://user-images.githubusercontent.com/20385376/56125218-1c327700-5f81-11e9-98ad-c4e89c32559f.png)

**Comment by devin-petersohn** [comment]
Hi @jaysnm, thank you so much for the clarification! This helps a lot.

This is the line: https://github.com/modin-project/modin/blob/master/modin/backends/pandas/query_compiler.py#L810. We should be checking that the index has a name first.

**Comment by vivekruhela** [comment]
I am using pandas version 0.24.2 and I am getting the same error randomly. Randomly means sometimes reset_index works but sometimes it doesn't works. I tried to reinstall this library also but failed. What could be the possible cause..
