### ISSUE TITLE
Relax hard pin on pandas version, use >= version instead

### ISSUE THREAD

**Issue by discdiver** [modin-project/modin#1860]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave
- **Modin version** (`modin.__version__`): modin-0.7.4
- **Python version**: 3.7
- **Code we can use to reproduce**:

In a conda environment

`pip install modin`

leads to pandas 1.1.0 being uninstalled in favor of 1.0.5 without warning.

### Source code / logs
```
Collecting modin
  Downloading modin-0.7.4-py3-none-macosx_10_9_x86_64.whl (334 kB)
     |████████████████████████████████| 334 kB 1.2 MB/s 
Collecting pandas==1.0.5
  Downloading pandas-1.0.5-cp37-cp37m-macosx_10_9_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 2.9 MB/s 
Requirement already satisfied: packaging in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from modin) (20.4)
Requirement already satisfied: numpy>=1.13.3 in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from pandas==1.0.5->modin) (1.18.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from pandas==1.0.5->modin) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from pandas==1.0.5->modin) (2020.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from packaging->modin) (2.4.7)
Requirement already satisfied: six in /Users/jeffhale/miniconda3/lib/python3.7/site-packages (from packaging->modin) (1.15.0)
Installing collected packages: pandas, modin
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.0
    Uninstalling pandas-1.1.0:
      Successfully uninstalled pandas-1.1.0
Successfully installed modin-0.7.4 pandas-1.0.5
```

**Comment by devin-petersohn** [comment]
Hi @discdiver thanks for posting.

We are planning to relax the requirements for the pandas version a bit, but still throw a warning. pandas released a couple of days before our planned release, and there wasn't time to adequately test everything in the new pandas version.

You can reinstall pandas 1.1 after install modin, or install with `pip install --no-deps modin` if you want to keep pandas 1.1. 

I am going to rename the issue to something we can track to fix this issue. Thanks again for posting!

**Comment by devin-petersohn** [comment]
We are going to keep the hard pin on pandas due to behavior changes even between micro releases.

**Comment by devin-petersohn** [comment]
Resolving the original issue, Pandas version was updated 1.1
