### ISSUE TITLE
'pip install -r requirements' often fail in CI checks on master branch

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#1867]
Error message looks like:
`ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE...`

We **need to establish** CI checks as much as possible.
First of all, we probably should use `pip install` with `--no-cache-dir` option.

Example commits from master of last day with same problem:
- 4d80bd8e163f6e628e2d9b4ce6d933b7aad65b48
- 9a65e777fce940a2de3e9ace6f5119023d44a011

**Comment by anmyachev** [comment]
It's seems that pytest-testmon doesn't properly working.
```
testmon: collection automatically deactivated because it's not compatible with coverage.py, changed files: 8, skipping collection of 30 files, environment: default
```

**Comment by anmyachev** [comment]
The problem is not caching, because errors were reproduced even in the case of a disabled cache.

**Comment by devin-petersohn** [comment]
@anmyachev I have noticed this issue over the past week or so. Restarting CI can sometimes fix it. I cannot find the source of the issue.

Maybe we should just miniconda? https://github.com/marketplace/actions/setup-miniconda

**Comment by anmyachev** [comment]
> @anmyachev I have noticed this issue over the past week or so. Restarting CI can sometimes fix it. I cannot find the source of the issue.
> 
> Maybe we should just miniconda? https://github.com/marketplace/actions/setup-miniconda

Thanks @devin-petersohn! Usage conda action with cache action seems to me a good solution for establish CI. Need more testing.
