### ISSUE TITLE
Documentation for installation on Windows

### ISSUE THREAD

**Issue by waltonereed** [modin-project/modin#187]
Can you please include documentation on how to install Modin for Windows machines, since Ray is not supported on Windows?

**Comment by devin-petersohn** [comment]
Hi @waltonereed, thanks for your question! I will add this to the documentation, but for now here are the instructions:

I personally use Modin on Windows through the Windows Subsystem for Linux (WSL): https://docs.microsoft.com/en-us/windows/wsl/install-win10

After you install WSL, open the Linux distribution's shell you installed (Ubuntu in my case). 

From here you can follow the installation instructions for Linux:

```
pip install modin
```

From here, you need to run `jupyter` or `ipython` or `python` from this terminal.

If you have any further questions, please let me know!

**Comment by hnyang1107** [comment]
Hi, I can install modin in My WSL but I got a void dataframe when I run `df = pd.read_csv` without any error.

**Comment by devin-petersohn** [comment]
Hi @hnyang1107, is this installed via `pip`? It might be worth creating a new issue to track the problem you're running into.

**Comment by devin-petersohn** [comment]
Closing as complete in #188

**Comment by shivam-kotwalia** [comment]
Just to update - It can now be installed on Windows using dask backned 
`pip install modin[dask]`
