### ISSUE TITLE
Data is copied during manipulations with partitions with python engine

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#1897]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.04
- **Modin version** (`modin.__version__`): 0.7.3+290.gaa78a18
- **Python version**: 3.8.3
- **Code we can use to reproduce**:

### Describe the problem

As it was noticed in https://github.com/modin-project/modin/issues/1284#issuecomment-669887558 data copy during manipulations with partitions can significantly decrease performance of Modin functions.

**Comment by devin-petersohn** [comment]
The python engine is for debugging only, so optimizing performance is not necessary.

**Comment by amyskov** [comment]
Ok, i see. In that case we can close this isue, i think.
