### ISSUE TITLE
[BUG] groupby + aggregate return pandas series as a result

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1906]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **Modin installed from (source or binary)**: source
- **Modin version**: master
- **Python version**: 3.8.3
- **Exact command to reproduce**: python test.py

### Describe the problem
Pandas Series is returned by operation instead of Modin Series.

### Source code / logs
```
import modin.pandas as pd

data = {
        "a": [1, 1, 2, 2, 2],
        "b": [11, 21, 12, 22, 32],
        "c": [101, 201, 102, 202, 302],
    }
df = pd.DataFrame(data)
df = df.groupby(["a"]).c.sum()
print(type(df))
```
```
# python test.py
<class 'pandas.core.series.Series'>
```

**Comment by dchigarev** [comment]
There is a bug in how we're accessing attributes via `__getattr__`, look at the related code:
```python
if __name__ == "__main__":
    import modin.pandas as pd

    data = {
            "a": [1, 1, 2, 2, 2],
            "b": [11, 21, 12, 22, 32],
            "c": [101, 201, 102, 202, 302],
        }
    df = pd.DataFrame(data)

    attr_res = df.groupby(["a"]).c
    item_res = df.groupby(["a"])["c"]

    print(type(attr_res)) # pandas.SeriesGroupBy
    print(type(item_res)) # modin.SeriesGroupBy

```

The thing is, that for some reasons we're doing `__getitem__` default to pandas in `__getattr__`, despite we already have implementation for `DataFrameGroupBy.__getitem__` https://github.com/modin-project/modin/blob/896f5b6e456fc7565fc2dea59af479b4b1739e1c/modin/pandas/groupby.py#L109-L114
What is happening here is:
1. `df.__getitem__(key)` returns `pandas.SeriesGroupBy`
2. `_default_to_pandas` expects only DataFrames and Series as the result of the default function
3. `_default_to_pandas` can't create any distributed object from an unexpected object and just returns it
4. we're getting pandas object as the result of modin function

so the fix will be is just replacing default to pandas call to `self.__getitem__(key)`

@devin-petersohn if you don't mind, I can prepare the PR with this quick fix

**Comment by devin-petersohn** [comment]
@dchigarev I have assigned to you, thanks for looking at it!
