### ISSUE TITLE
CI fails on Windows checks

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#1908]
CI fails on Windows tests on the step `Run goanpeca/setup-miniconda@v1.6.0` with the next message:
```
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

##[error]The process 'C:\Miniconda\condabin\conda.bat' failed with exit code 1
```
_Note:_ Reopened #1904, since it was closed by mistake

**Comment by devin-petersohn** [comment]
Is this still an issue @amyskov?

**Comment by amyskov** [comment]
I think, that it is not an issue since the problem is not reproduced no more.
