### ISSUE TITLE
read_csv using pyarrow uses single core

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#1916]
Reading csv files for NYC Taxi benchmarks by Modin with OmniSci engine enabled, we observe a single loaded core on the system. We expect arrow based read_csv to be multi-threaded.

**Comment by devin-petersohn** [comment]
It may be due to the fact that we are overriding `OMP_NUM_THREADS` because pyarrow/Ray will spawn too many threads on multi-socket machines.

**Comment by devin-petersohn** [comment]
https://github.com/modin-project/modin/blob/master/modin/pandas/__init__.py#L93

**Comment by ienkovich** [comment]
I tried to remove this string, but it had no effect on read_csv performance.

**Comment by anton-malakhov** [comment]
There are two places where OMP_NUM_THREADS is set, 1) in Modin as Devin pointed out and 2) in Ray: https://github.com/ray-project/ray/pull/6998.

**Comment by anton-malakhov** [comment]
fixed unconditional assignment of OMP_NUM_THREADS var. Ideally, it is better to refer users to https://github.com/joblib/threadpoolctl instead. Will give it a thought
