### ISSUE TITLE
Performance Issue with Conversion to numpy

### ISSUE THREAD

**Issue by owerbat** [modin-project/modin#1926]
- Linux
- Python 3.7
- Modin 0.8.0

Conversion of `modin.pandas.DataFrame` to `numpy.array` (e.g. with `numpy.asarray()`) is slower than conversion of `pandas.DataFrame` to `numpy.array`.

**Comment by devin-petersohn** [comment]
@owerbat Thanks for the report, I am going to reclassify as performance.

**Comment by Garra1980** [comment]
@devin-petersohn any thoughts/estimations about this

**Comment by devin-petersohn** [comment]
The multiprocessing and multi node cases will cause large objects to be communicated. This is why it takes longer than pandas.

The only way to handle this is to convert to a numpy compatible object that stays distributed.

**Comment by anmyachev** [comment]
> The only way to handle this is to convert to a numpy compatible object that stays distributed.

This has already been implemented in experimental mode for working with numpy arrays (can be enabled with `MODIN_EXPERIMENTAL_NUMPY_API=True` env var).
