### ISSUE TITLE
Different from pandas index at `read_csv` in case of specified `names`

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1930]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 0.8.0
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
if __name__ == "__main__":
    import pandas
    import modin.pandas as pd
    from modin.pandas.test.test_io import (
        create_test_pandas_dataframe,
        TEST_CSV_FILENAME,
        df_equals,
    )

    create_test_pandas_dataframe().to_csv(TEST_CSV_FILENAME)

    md_df = pd.read_csv(TEST_CSV_FILENAME, names=["c1", "c2", "c3", "c4", "c5"])
    pd_df = pandas.read_csv(TEST_CSV_FILENAME, names=["c1", "c2", "c3", "c4", "c5"])

    try:
        df_equals(md_df, pd_df)
    except Exception as e:
        print(e)  # DataFrame.index are different

    md_df = pd.read_csv(
        TEST_CSV_FILENAME, names=["c1", "c2", "c3", "c4", "c5"], usecols=[0, 1, 2, 3, 4]
    )
    pd_df = pandas.read_csv(
        TEST_CSV_FILENAME, names=["c1", "c2", "c3", "c4", "c5"], usecols=[0, 1, 2, 3, 4]
    )

    df_equals(md_df, pd_df)  # everything is okay

```

### Describe the problem
Here is the output of the code above:
```
DataFrame.index values are different (100.0 %)
[left]:  RangeIndex(start=0, stop=5, step=1)
[right]: Float64Index([nan, 0.0, 1.0, 2.0, 3.0], dtype='float64')
```
As we can see the indices are different. In case `names` parameter is specified `read_csv` will start read data right from the first line of the file and that line pandas indicates with `nan` value at index, when Modin just creates `RangeIndex`. But when `usecols` is specified at the same time as `names` Pandas creates `RangeIndex` the same as Modin.

**Comment by devin-petersohn** [comment]
This might be a similar issue to #2239.

**Comment by mvashishtha** [comment]
This is quite an old issue, so we need to figure out whether it still applies.

**Comment by pyrito** [comment]
I was able to create the dataset used: [test.csv](https://github.com/modin-project/modin/files/9570090/test.csv)

Unfortunately, it looks like both `df_equals` statements are now failing. For the first check we get this:
```
DataFrame.iloc[:, 0] (column name="c1") values are different (80.0 %)
[index]: [nan, 0.0, 1.0, 2.0, 3.0]
[left]:  [col1, 0, 1, 2, 3]
[right]: [col1, 0, 1, 2, 3]
```
And for the second check after using `usecols` we are getting the following error:
```
DataFrame.iloc[:, 1] (column name="c2") values are different (80.0 %)
[index]: [0, 1, 2, 3, 4]
[left]:  [col1, 0, 1, 2, 3]
[right]: [col1, 0, 1, 2, 3]
```
It looks like Modin reads in the numbers as `numpy.int64` by default where was pandas is reading them in as strings.
