### ISSUE TITLE
Integrating a new distributed framework

### ISSUE THREAD

**Issue by deHasara** [modin-project/modin#1933]
Let's say I have the operators- Selection, Projection, Union, Difference etc.(Dataframe Algebra explained in [paper](https://arxiv.org/pdf/2001.00888.pdf)) as the end points of the framework. How can I integrate Modin to the API?  From which layer of the Modin architecture can this integration be initiated?

**Comment by devin-petersohn** [comment]
The Algebra in the paper and the API deviate somewhat partially for programmer sanity and partially for simplicity. The Modin Dataframe Layer implements this algebra: https://github.com/modin-project/modin/blob/master/modin/engines/base/frame/data.py. The method names are somewhat different from the algebra operators, and some functionalities like groupby are expanded for optimization purposes.

A good example of this is the integration with Omnisci currently in progress: https://github.com/modin-project/modin/pull/1893

**Comment by pyrito** [comment]
Closing this issue since the answer seems to have resolved the initial question. Please re-open if needed.
