### ISSUE TITLE
Package all tests during setup to foster testability of installed Modin

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#1948]
If we're going to ship _some_ tests we better ship all of them, so users would be able to run the full suite after installation without requiring to use source distribution.

cc @anton-malakhov  @devin-petersohn

**Comment by anton-malakhov** [comment]
https://github.com/intel-go/modin/pull/92

**Comment by vnlitvinov** [comment]
@anton-malakhov how come it's fixed if the fix is not in this repo? 😝
