### ISSUE TITLE
Replace abstract query compiler methods at BaseQueryCompiler to default to pandas

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1957]
Currently, it's a backend task to fall back to pandas in case when some method is not supported at the current backend. We need to move all fallback to pandas to the BaseQueryCompiler, so all of the backends has consistent behavior when some method is not supported.

**Comment by dchigarev** [comment]
- [x] Common DataFrame methods
- [x] Common Series methods
- [x] `pandas.Series.dt` methods
- [x] `pandas.Series.str` methods
- [x] Binary operations
- [ ] Groupby methods
- [ ] Rolling methods
- [ ] Resample methods
- [ ] Window methods

**Comment by Garra1980** [comment]
Great job, thanks guys!!
