### ISSUE TITLE
Upgrade to Ray 0.8.7

### ISSUE THREAD

**Issue by crypdick** [modin-project/modin#1958]
I am experiencing an issue with Ray which is fixed in `0.8.7`; however, Modin has pinned the Ray version to `0.8.6` [here](https://github.com/modin-project/modin/blob/master/modin/__init__.py#L56). Can we please update the dependency?

**Comment by devin-petersohn** [comment]
Thanks @crypdick for the report, yes we should update it. I took last week off and am still catching up. You can install Ray 0.8.7 and bypass this in the short term with the following:

```python
import os
os.environ["MODIN_ENGINE"] = "ray"  # set this first
import modin.pandas as pd  # then import
```

You can also set the environment variable outside of python as well. 

On a more general note, it is probably time to relax the pin. I think the ray API has stabilized to the point where we can use a `>=` instead of a hard pin.

**Comment by crypdick** [comment]
@devin-petersohn here's what I get when I try that:

```
    import modin.pandas as mpd
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/modin/pandas/__init__.py", line 170, in <module>
    execution_engine.subscribe(_update_engine)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/modin/__init__.py", line 93, in subscribe
    callback(self)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/modin/pandas/__init__.py", line 113, in _update_engine
    initialize_ray()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/modin/engines/ray/utils.py", line 147, in initialize_ray
    lru_evict=True,
TypeError: init() got an unexpected keyword argument 'include_webui'
```

**Comment by binarycrayon** [comment]
I have the same need so added a pr, thanks!

**Comment by yxue-kabam** [comment]
@crypdick Ray community recently decided to rename `webui` to `dashboard`, so `include_webui` became `include_dashboard`. detail see this pr https://github.com/ray-project/ray/pull/8999

I've mitigated that change in my pr (basically omitted include_webui kwarg since it's set to `False` anyway)

**Comment by binarycrayon** [comment]
@crypdick Ray community recently decided to rename webui to dashboard, so include_webui became include_dashboard. detail see this pr ray-project/ray#8999

I've mitigated that kwarg in my pr (basically changed to include_dashboard=False)

**Comment by crypdick** [comment]
Just figured out how to pin Modin to the latest master SHA, in case it's helpful to anyone:

```
pip install git+https://github.com/modin-project/modin.git@0c0b6f64bc9c6afc1267fe9fc703a0e30d783f96
pip install  "modin[ray] @ git+https://github.com/modin-project/modin.git@0c0b6f64bc9c6afc1267fe9fc703a0e30d783f96"
``` 
(haven't gotten this to work with `requirements.txt`)
