### ISSUE TITLE
Add support for dictionary type to arrow::read_csv

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#1963]
For now, arrow only supports auto_dictionary_enciding options, which implicitly encodes columns with cardinality < threshold. But we need to have the opportunity to set explicit type `dict` to columns which we would like to encode with `column_types` field in `ConverterOptions`.

**Comment by dchigarev** [comment]
Support for explicit dictionary type at `read_csv` was already added by [this](https://github.com/apache/arrow/pull/8160) PR at arrow. Since then we can write a code like this and it'll execute correctly.

```python
pyarrow.csv.read_csv(
    "test.csv",
    convert_options=ConvertOptions(
        column_types={"col1": pa.dictionary(pa.int32(), pa.int32())}
    ),
)
```
