### ISSUE TITLE
iloc issue when iterating through all the columns

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#197]
### Describe the problem
`iloc` throws a `TypeError` the first time I iterate through all the columns but works every time after

### Source code / logs
```
import modin.pandas as pd

data = {
    "col3": [0, 1, 2, 3],
    "col4": [4, 5, 6, 7],
    "col5": [8, 9, 10, 11],
    "col1": [12, 13, 14, 15],
    "col2": [0, 0, 0, 0],
}

modin_df = pd.DataFrame(data)
```
Then the first time I run the following code block, I get a `TypeError: 'int' object is not iterable`, but if I rerun the code block, everything works
```
for i in range(len(modin_df.columns)):
    modin_df.iloc[:, i]
```

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
