### ISSUE TITLE
Creating Series from nested lists leads to an exception

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1972]
### System information
- **OmniSci branch**: [intel-go/omniscidb/gal/fix_pytests](https://github.com/intel-go/omniscidb/tree/gal/fix_pytests)
- **Modin branch**: [intel-go/modin/omnisci-on-ray](https://github.com/intel-go/modin/tree/omnisci-on-ray)
- **Code we can use to reproduce**:
```python
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

if __name__ == "__main__":
    import modin.pandas as pd
    import pandas

    data = [[1, 2, 3, 4], [1, 2, 3, 4]]
    
    pd_ser = pandas.Series(data)
    md_ser = pd.Series(data)

    print("pd_series:\n", pd_ser, sep="")
    print("md_series:\n", md_ser, sep="")  # Core dumped

```

<details><summary>Output</summary>

```
pd_series:
0    [1, 2, 3, 4]
1    [1, 2, 3, 4]
dtype: object

md_series:
terminate called after throwing an instance of 'std::runtime_error'
  what():  list<item: int64> is not yet supported.
*** Aborted at 1598532184 (unix time) try "date -d @1598532184" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0xb6674d00019b92) received by PID 105362 (TID 0x7f08ee476740) from PID 105362; stack trace: ***
    @     0x7f08ee066890 (unknown)
    @     0x7f08edca1e97 gsignal
    @     0x7f08edca3801 abort
    @     0x7f08dc6fe84a __gnu_cxx::__verbose_terminate_handler()
    @     0x7f08dc6fcf47 __cxxabiv1::__terminate()
    @     0x7f08dc6fcf7d std::terminate()
    @     0x7f08dc6fd1a4 __cxa_rethrow
    @     0x7e976eaa9d89 EmbeddedDatabase::DBEngineImpl::createArrowTable()
    @     0x7f08d001e659 __pyx_pw_3dbe_10PyDbEngine_13consumeArrowTable()
    @     0x55c1ab6e7e77 method_vectorcall_VARARGS_KEYWORDS
    @     0x55c1ab643820 _PyEval_EvalFrameDefault.cold.2792
    @     0x55c1ab6cd802 _PyEval_EvalCodeWithName
    @     0x55c1ab6ceb80 method_vectorcall
    @     0x55c1ab643841 _PyEval_EvalFrameDefault.cold.2792
    @     0x55c1ab6cd802 _PyEval_EvalCodeWithName
    @     0x55c1ab6ceb80 method_vectorcall
    @     0x55c1ab643841 _PyEval_EvalFrameDefault.cold.2792
    @     0x55c1ab6cea6b method_vectorcall
    @     0x55c1ab643841 _PyEval_EvalFrameDefault.cold.2792
    @     0x55c1ab6ce6cb _PyFunction_Vectorcall.localalias.355
    @     0x55c1ab643820 _PyEval_EvalFrameDefault.cold.2792
    @     0x55c1ab6cef7a property_descr_get
    @     0x55c1ab681c55 _PyObject_GenericGetAttrWithDict
    @     0x55c1ab703ebe _PyEval_EvalFrameDefault
    @     0x55c1ab6cef7a property_descr_get
    @     0x55c1ab681c55 _PyObject_GenericGetAttrWithDict
    @     0x55c1ab703ebe _PyEval_EvalFrameDefault
    @     0x55c1ab6cef7a property_descr_get
    @     0x55c1ab681c55 _PyObject_GenericGetAttrWithDict
    @     0x55c1ab6b2806 wrapperdescr_call
    @     0x55c1ab6805cf _PyObject_MakeTpCall
    @     0x55c1ab707ae9 _PyEval_EvalFrameDefault
Aborted (core dumped)

```

</details>

**Comment by Garra1980** [comment]
Currently in this case list[int64] passed into omnisci as column type which is unsupported. Seems, we should handle this separately

Core dumping will be fixed later - all omnisci's exceptions will be caught and handled in modin

**Comment by Garra1980** [comment]
This needs to be defaulted to pandas

**Comment by dchigarev** [comment]
> This needs to be defaulted to pandas

What `modin.DataFrame` constructor do, when we construct it from anything that is not query compiler:
1. Constructs `pandas.DataFrame` with passed data and parameters
2. **Constructs `modin.DataFrame` from `pandas.DataFrame`** (unsupported in case of lists)

And what default to pandas do is:

1. Translates `modin.DataFrame` -> `pandas.DataFrame`
2. Perform some function on `pandas.DataFrame`
3. **Constructs `modin.DataFrame` from `pandas.DataFrame`** (still unsupported in case of lists)

So, we can't construct `modin.DataFrame` as default to pandas, because if our unsupported operation is constructing, we need to perform it anyway in default to pandas. I think the only way is throwing an exception that `list[int64]` is not supported as a dtype for Series.

**Comment by dchigarev** [comment]
#2208 brings changes that if we're constructing from frame with data types that unsupported by OmniSci, then we're doing all operations with frame default to pandas and not loading it into OmniSci. So case described in an issue is fixed.
