### ISSUE TITLE
Make mask and where distributed

### ISSUE THREAD

**Issue by goodwanghan** [modin-project/modin#1977]
When using Ray backend, I can see the warning that `mask` and `where` default to pandas. Does that mean the operation will cause modin to collect all data onto one machine and then use pandas to do the job? If so, does it collect only the specific columns or it collects the whole dataframe onto one machine?

`mask` and `where` are relatively common operations, can we make them distributed?

Thank you!

**Comment by mvashishtha** [comment]
@goodwanghan thank you for your request. `where` is already implemented in a distributed way. We'll track `mask` implementation in #1206.
