### ISSUE TITLE
Multiindex in modin give "slice unhashable error"

### ISSUE THREAD

**Issue by 0luhancheng0** [modin-project/modin#1988]
### System information
- MacOS
- 0.8.0
-3.7.6

```

import modin.pandas as pd
import numpy as np
index = pd.MultiIndex.from_product([np.arange(10), np.arange(10)], names=['f','s'])
data = np.arange(100)
df = pd.Series(data, index=index).sort_index()
df.loc[(slice(None), 1), ]

```

### Describe the problem
The code above gives `TypeError: unhashable type: 'slice'` error while the plain pandas runs without error

**Comment by devin-petersohn** [comment]
Hi @0luhancheng0, thanks for posting! I can reproduce this with what you've provided, it should be a straightforward fix. Thanks for the concise example!

Until we get this fixed, here is a workaround that will solve this issue:

```python
import modin.pandas as pd
import numpy as np
index = pd.MultiIndex.from_product([np.arange(10), np.arange(10)], names=['f','s'])
data = np.arange(100)
df = pd.Series(data, index=index).sort_index()
# df.loc[(slice(None), 1), ]
df.index = df.index.swaplevel()
df.loc[1,]
```

It's a silly workaround but it solves the case where we were trying to hash the slice until we get it fixed. Thanks again for posting this!
