### ISSUE TITLE
Performance lower than vanilla pandas

### ISSUE THREAD

**Issue by hsezhiyan** [modin-project/modin#1990]
### System information
- Macbook Pro, Mid 2014, OS: MacOS Mojave
- 2.8 GHz Intel core i7, 16GB Memory, Intel Iris Pro graphics card
- `modin v.0.8.0`
- `python3 v.3.7.4`

Hello, 

I am quite new to this project, so this problem may be an easy fix. Essentially, I am trying to load the following [file](https://drive.google.com/file/d/1heF7MmEXvo6wlEgl7ARWFahCJgIOeRS-/view?usp=sharing) using `modin`. However, using `modin` is much slower than using vanilla `pandas`.

To use modin, I do:
```
import modin
modin.read_csv("labels.csv")
``` 
And for pandas:
```
import pandas as pd
pd.read_csv("labels.csv")
```
I use `time.time()` to measure elapsed time. For `modin`, it takes about `1.03` seconds, but for vanilla pandas, it takes only `0.02` seconds, which is a speedup of 50x. Can someone explain if I'm using this library incorrectly?

**Comment by devin-petersohn** [comment]
Hi @hsezhiyan, thanks for posting!

I wasn't able to reproduce that performance of 1s for Modin, here is what I see on a 2013 iMac:

```python
In [1]: import time                                                                                                                                                            

In [2]: import modin.pandas as pd                                                                                                                                              

In [3]: s = time.time() 
   ...: df = pd.read_csv("labels.csv") 
   ...: print(time.time() - s)                                                                                                                                                 
0.07983684539794922
```

If you can share more of the code or a notebook you're working it, that would help. I am going to reclassify this as a performance issue.
