### ISSUE TITLE
Enable modin-on-omnisci for modin cloud

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1991]
We need to try Modin Cloud with new experimental engine which is based on OmnisciDB 
At the moment https://github.com/intel-go/modin/tree/omnisci-on-ray branch should be used
In general instructions for using omnisci engine are here - https://github.com/modin-project/modin/issues/1652#issuecomment-679925921
(current PR in master branch - https://github.com/modin-project/modin/pull/1893)

**Comment by vnlitvinov** [comment]
REF: draft enabling the feature: https://github.com/intel-ai/modin/pull/109/ (not complete, needs cluster yml fixed)
