### ISSUE TITLE
Get rid of passing Pandas backend-specific arguments to a query compiler level

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2002]
Currently, some functions at API level passes an arguments to a query compiler methods, that make sense only for pandas backend.
For example, all DataFrame binary operation passes `broadcast` parameter to a backend, that indicates that `other` value is `Series` and we will be able to broadcast it at ModinFrame layer:
https://github.com/modin-project/modin/blob/826699e1c28059e1109d1c62b433b9a45f358f56/modin/pandas/dataframe.py#L523-L531

We should find all the places at API layer where we pass backend-specific arguments to a query compiler and move it to a query compiler level

**Comment by devin-petersohn** [comment]
`broadcast` here is about the behavior, not about pandas. `broadcast` means that the values in other must be added to every other column/row (`axis` dependent). Other backends need to know this information as well.

Is there another place in the code where you've noticed the leakage of pandas-specific implementation details? There may be, but I do not think this is one of them.

**Comment by dchigarev** [comment]
I had an opportunity to check every method when I was working on #1957, and I didn't find any places where we're passing backend-specific arguments from API layer to backend.

So closing these issue since there is no issue
