### ISSUE TITLE
Distributed K-means algorithm 

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#2004]
Generic distributed implementation of K-means on Modin/Ray using the Scaleout API.

**Comment by pyrito** [comment]
Is this a feature we want to support as part of Modin directly? Isn't k-means something that is more specific to a user's implementation as opposed to something we need to do within Modin?

**Comment by mvashishtha** [comment]
@pyrito pandas doesn't support this and I don't know of anyone ever asking for this feature, so I'll mark it as P3.

**Comment by anmyachev** [comment]
Not actual. @aregm feel free to reopen if needed
