### ISSUE TITLE
UserWarning: Parameters provided defaulting to pandas implementation.

### ISSUE THREAD

**Issue by AhmedSalam22** [modin-project/modin#2007]
Hi I want this feature, please

UserWarning: Parameters provided defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.

![Screenshot (315)](https://user-images.githubusercontent.com/35177448/92150332-8f12eb00-ee1f-11ea-9902-f0292b58c5a4.png)

**Comment by devin-petersohn** [comment]
@AhmedSalam22 I think this is possible a duplicate of #2005. Is there a different issue here?

**Comment by AhmedSalam22** [comment]
thank you so much, sir, it is duplicate you can close this thread. sorry for bother
