### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2008]
Current goals:
- < 45 min on PR
- < 20 concurrent jobs on PR (enterprise tier of github actions has a limit of 180 concurrent jobs)

**Comment by anmyachev** [comment]
Current state (for dd27013 in master):
- ~ 50 min
- 24 parallel jobs

**Comment by anmyachev** [comment]
Further improvements should be for:
- `test_series.py`
- `test_groupby.py`
- `test+default.py`

**Comment by jbrockmendel** [comment]
`pytest modin/pandas/test/` takes me 2.5 hours locally (the pandas test suite with `--skip-slow --skip-db` takes 23 minutes).

Of this, test_join_sort takes 55 minutes, test_groupby takes 37, test_series takes 18, test_indexing takes 17

**Comment by mvashishtha** [comment]
@jbrockmendel that local command only runs tests with the ray. It doesn't test the dask engine at all and skips many tests in the CI. [Here](https://github.com/modin-project/modin/runs/7320816368?check_suite_focus=true) is an example recent successful CI run. The whole thing took 1h 17 minutes. Note that the CI benefits from parallelism across tests.

`test_join_sort` has [way too many test cases](https://github.com/modin-project/modin/issues/4202#issuecomment-1040433535).

**Comment by pyrito** [comment]
In this vein, test-compat-win (engine dask, python 3.6) has been notoriously slow in CI for some time now.

**Comment by pyrito** [comment]
One thing that we could do to make CI faster for test-compat-win is to launch parallel jobs of pytests similar to what we do for test-windows right now.

**Comment by vnlitvinov** [comment]
Another note: this PR https://github.com/modin-project/modin/pull/6267 seems to be a good example were testing only `PandasOnPython` is not enough - we should try to keep at least some tests which are bumping into Ray peculiarities. Seems that `test_map_metadata.py` is a good candidate.

**Comment by anmyachev** [comment]
> Think more what we run regarding ASV - whether we really care about that in PRs, or maybe we can drop this from PRs and instead run this on merges to master comparing current and previous commit or something similar? cc @anmyachev

ASV tests are only run when there are changes in `asv_bench` folder, which is quite rare.

**Comment by anmyachev** [comment]
> Add running the whole test suite on PandasOnPython backend on Windows

@vnlitvinov do you mean `BaseOnPython` execution? Or are we just not testing `PandasOnPython` at all right now, so I don’t see it?

**Comment by vnlitvinov** [comment]
> @vnlitvinov do you mean `BaseOnPython` execution? Or are we just not testing `PandasOnPython` at all right now, so I don’t see it?

We aren't testing `PandasOnPython` on Windows at all, and `BaseOnPython` is a different thing, it cannot substitute testing for Ray or Dask because it uses different query compiler (and it's using a partitioning mechanism).
