### ISSUE TITLE
Implement distributed merge_asof

### ISSUE THREAD

**Issue by itamarst** [modin-project/modin#2013]
Currently `modin.pandas.merge_asof` falls back to Pandas. It would be good to implement a distributed, Modin-native implementation.

First step will be figuring out if this should be implemented in one go, or if it's big enough to merit multiple sub-tasks.

**Comment by itamarst** [comment]
Here's my initial idea:

1. Extract just the columns that will be used to calculate the merge.
2. Use Pandas' implementation on that to match up indexes: you'd use the two columns above as indexes, and the actual indexes as value columns.
3. Now that you know how to match up indexes, match up the rest of the data with Modin logic (might be possible to use normal merge logic at this point).

This is of course very handwavy, but seems plausible. The improvement is that instead of converting _everything_ into a Pandas DataFrame, only the relevant two columns/indexes are (with even less work/allocation when the indexes are being used).

How's that sound @devin-petersohn? Do you think there's a better approach?

**Comment by devin-petersohn** [comment]
Thanks @itamarst it makes sense.

>This is of course very handwavy, but seems plausible. The improvement is that instead of converting everything into a Pandas DataFrame, only the relevant two columns/indexes are (with even less work/allocation when the indexes are being used).

This is how we do some other implementations currently, so it makes sense until we have better internal support for conditional joins.

**Comment by itamarst** [comment]
OK, opened draft PR with sketch (#2178), would appreciate some feedback about whether this seems like a good direction.
