### ISSUE TITLE
Some parameters of read_csv are not covered by tests

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2019]
Tests in `modin/pandas/test/test_io.py` doesn't cover all the parameters of `pd.read_csv` function.

**Comment by devin-petersohn** [comment]
The entire `io` test suite needs improvement.

**Comment by amyskov** [comment]
Most of the parameters are covered by tests, but work is still in progress.

**Comment by amyskov** [comment]
Current status of `read_csv` parameters coverage by tests (y - already covered by tests, partly - parameter tests coverage not compete, PR - parameter tests coverage implemented in PR, WIP - work under parameter test coverage is in progress):
read_csv   parameter | Current status
-- | --
"filepath_or_buffer", | y
"sep", | partly, PR
"delimiter", | partly, PR
"header", | y
"names", | y
"index_col", | y
"usecols", | y
"squeeze", | PR
"prefix", | PR
"mangle_dupe_cols", | PR
"dtype", | y
"engine", | PR
"converters", | PR
"true_values", | PR
"false_values", | PR
"skipinitialspace", | PR
"skiprows", | y
"nrows", | y
"na_values", | PR
"keep_default_na", | PR
"na_filter", | PR
"verbose", |  
"skip_blank_lines", | PR
"parse_dates", | partly, PR
"infer_datetime_format", | PR
"keep_date_col", | PR
"date_parser", | PR
"dayfirst", | PR
"cache_dates", | PR
"iterator", | PR
"chunksize", | y
"compression", | y
"thousands", | WIP
"decimal", | WIP
"lineterminator", | WIP
"quotechar", | WIP
"quoting", | partly, PR
"escapechar", | WIP
"comment", | WIP
"encoding", | y
"dialect", |  
"error_bad_lines", |  
"warn_bad_lines", |  
"skipfooter", | y
"doublequote", |  
"delim_whitespace", |  
"low_memory", |  
"memory_map", |  
"float_precision", |

**Comment by amyskov** [comment]
All subtasks were done, so closing this epic too.
