### ISSUE TITLE
Improve speed of read_parquet

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#205]
### Describe the problem

Currently `modin.pandas.io.read_parquet` uses Ray to read each column individually in-parallel. It would be more efficient to choose the number of partitions based on the number of cores and read multiple columns at once. It may not immediately improve read times, but it would improve the speed of operations after.

Currently io.py needs a minor refactor (#203).

This issue would be good for a first time contributor familiar with Parquet. Feel free to reply to this issue with any questions.

### Source code / logs

[Link to source](https://github.com/modin-project/modin/blob/master/modin/pandas/io.py#L30)
[Link to Ray Remote Task](https://github.com/modin-project/modin/blob/master/modin/pandas/io.py#L613)

**Comment by eavidan** [comment]
Hi @devin-petersohn 
Just opened a [PR](#246) for this
It was a fairly small code change
If I missed anything, would be glad to refactor

**Comment by devin-petersohn** [comment]
Your fix looks great! I think we can close this issue. Thanks again!
