### ISSUE TITLE
Group all controlling environment variables in single file

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2059]
**Is your feature request related to a problem? Please describe.**
Currently it's hard both for Modin developer and for end user to see which variables exist and what they do.
I propose to move all variables to a single unified file and replace their usage with getter functions which will have docstrings explaining what variables do.

**Comment by devin-petersohn** [comment]
This will also be important for documentation purposes as well.

**Comment by devin-petersohn** [comment]
I see a couple of options available, not sure which one is better (or maybe we can have both):

1.) Have some kind of global `modin.options` module where all environment variables set options, and then can be updated with `set` or retrieved with `get`.  This should make it easy to change to config files as well.
2.) Context-specific configurations via `with` statement arguments.

A couple of questions that should influence design come to mind:
* How to ensure local configuration updates are propagated to the whole cluster? It should be easy but we have to make sure it gets done.
* Can we make certain configurations conditional on the data or workload parameters?

**Comment by vnlitvinov** [comment]
After some discussion with **Devin** my current implementation idea is the following:
1) Move `Publisher` from `modin/__init__.py` and generalize it enough so it can retrieve values from `os.environ` by itself
2) Make all env variables used now utilize this `Publisher`
3) Create a follow-up thread/ticket to discuss and design the (eventual) Modin configuration system, as for now it's almost non-existant (being managed by randomly placed environment variables), and gathering them in one place is just the first step - we'd like to be able to update the variable and have it propagated to all workers, have some dependencies (like make Modin pick `Ray` as engine if `OmniSci` is picked as backend), etc.
