### ISSUE TITLE
Metadata mismatch with `apply(np.unit8)` 

### ISSUE THREAD

**Issue by jayantsingh123** [modin-project/modin#2063]
### System information
- **macOs with Catalina version 10.15.6**
- **Modin version** (`modin.__version__`): 0.8.0
- **Python version**: 3.8

### Describe the problem

While using `modin` with `apply()` and `swifter` feature for fast application of functions to a dataframe, following error is encountered;

`AttributeError: 'ParallelDataFrameAccessor' object has no attribute 'progress_bar'`

### Source code / logs
  

``` python

import os
os.environ["MODIN_ENGINE"] = "dask"
import modin.pandas as pd
import swifter


temp_df = pd.DataFrame({"A": [0, 1, 2, 3, 1], "B": [3, 4, 5, 6, 7]})
temp_df[["A", "B"]] = temp_df[["A", "B"]].swifter.progress_bar(False).apply(np.uint8)
temp_df
```

Here is the error we got; 

`AttributeError: 'ParallelDataFrameAccessor' object has no attribute 'progress_bar'`. But it should be noted that using regular pandas we can easily apply the function;

``` python

import pandas as pd

temp_df = pd.DataFrame({"A": [0, 1, 2, 3, 1], "B": [3, 4, 5, 6, 7]})
temp_df[["A", "B"]] = temp_df[["A", "B"]].apply(np.uint8)
temp_df


A	B
0	3
1	4
2	5
3	6
1	7
```

It will be nice to have similar functionality with `Modin` too. More details about this issue can be found at following link to the Modin discourse; https://discuss.modin.org/t/paralleldataframeaccessor-object-has-no-attribute-progress-bar-while-using-modin/121

Regards

**Comment by devin-petersohn** [comment]
Thanks @jayantsingh123 for the report! 

I have made an issue for the swifter related problem at jmcarpenter2/swifter#127. There's a different bug here related to the apply function that we should fix. 

```python
import os
os.environ["MODIN_ENGINE"] = "dask"
import modin.pandas as pd
import swifter


temp_df = pd.DataFrame({"A": [0, 1, 2, 3, 1], "B": [3, 4, 5, 6, 7]})
temp_df[["A", "B"]] = temp_df[["A", "B"]].apply(np.uint8)
temp_df
```

**Comment by devin-petersohn** [comment]
To reflect the issue we can track, I will change the title

**Comment by pyrito** [comment]
The issue still seems to be present on the latest master. It looks like the dtypes after the apply haven't changed. See:
```python
In [5]: import os
   ...: os.environ["MODIN_ENGINE"] = "dask"
   ...: import modin.pandas as pd
   ...: import swifter
   ...: 
   ...: 
   ...: temp_df = pd.DataFrame({"A": [0, 1, 2, 3, 1], "B": [3, 4, 5, 6, 7]})
   ...: temp_df[["A", "B"]] = temp_df[["A", "B"]].swifter.progress_bar(False).apply(np.uint8)
   ...: temp_df
UserWarning: Distributing <class 'dict'> object. This may take some time.
UserWarning: Parallel Accessor does not use have a progress bar.
Out[5]: 
   A  B
0  0  3
1  1  4
2  2  5
3  3  6
4  1  7

In [6]: temp_df.dtypes
Out[6]: 
A    int64
B    int64
dtype: object

In [7]: import os
   ...: os.environ["MODIN_ENGINE"] = "dask"
   ...: import pandas as pd
   ...: import swifter
   ...: 
   ...: 
   ...: temp_df = pd.DataFrame({"A": [0, 1, 2, 3, 1], "B": [3, 4, 5, 6, 7]})
   ...: temp_df[["A", "B"]] = temp_df[["A", "B"]].swifter.progress_bar(False).apply(np.uint8)
   ...: temp_df
Out[7]: 
   A  B
0  0  3
1  1  4
2  2  5
3  3  6
4  1  7

In [8]: temp_df.dtypes
Out[8]: 
A    uint8
B    uint8
dtype: object
```
