### ISSUE TITLE
Reduce amount of "delivering" during remote call for basic containers

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2072]
**Original problem**
There are certain cases when just giving a proxy (remote) object to a call does not work due to various reasons.
Right now it is handled by "delivering" the objects to remote end (passing them "by value") by pickling them locally and unpickling remotely. Objects that are already remote should be excluded from this delivery.

**Improvement requested**
While this works for simple cases like `foo(obj1, obj2)` it pickles too much in cases like `bar([obj1, obj2])` - it will pickle both `obj1` and `obj2` even if those two were really remote objects.
We should improve the wrapping function to try and process at least basic types like `tuple`, `list` and `dict` on a per-element basis.

**Comment by pyrito** [comment]
@vnlitvinov Do you have an example of the case you mention?

**Comment by mvashishtha** [comment]
@pyrito I think @vnlitvinov might be referring to cases like this, where remote functions get a list of object IDs:

https://github.com/modin-project/modin/blob/6e1849f4deb7e5060d046ab532943bbe44e33ccb/modin/core/execution/ray/common/utils.py#L221-L224

But I think we should get rid of that kind of behavior entirely, and instead pass all object IDs directly as arguments to remote functions. That will fix deadlocks like #4507.

**Comment by anmyachev** [comment]
@vnlitvinov is it related to "Modin in the cloud" feature so we can close it?
