### ISSUE TITLE
Internal Naming change for Modin DataFrame in documentation and interally

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2078]
The architecture diagram is difficult to understand because there is a mismatch between current naming and the figure. 

@vnlitvinov suggested changing to `Dataframe Algebra`.

**Comment by vnlitvinov** [comment]
More verbose option is `Dataframe Algebra Unit` - we're talking about the frame which lies below Query Compiler on [the diagram](https://modin.readthedocs.io/en/latest/architecture.html#system-architecture)

**Comment by ashutoshtiwari13** [comment]
Can I attempt to change this and get a PR raised ?

**Comment by devin-petersohn** [comment]
@ashutoshtiwari13 Sure, there may be more discussion on the PR on how exactly we want the naming.

**Comment by YarShev** [comment]
I think we stabilized naming both in code and docs so closing.
