### ISSUE TITLE
`compare` function implementation

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#2091]
So far, we are just defaulting to pandas.

**Comment by anmyachev** [comment]
Default implementation of the function was be added by #1840.

Distributed implementation should be added in another PR.

**Comment by kvu35** [comment]
@anmyachev @devin-petersohn I think this API can be implemented using a process similar to binary op in the query compiler level. Hope it's all right if I work on this and open a PR.

**Comment by anmyachev** [comment]
Thanks @kvu35!
This will be very helpful for us.
