### ISSUE TITLE
Make conda package for ray 0.8.7

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2098]
To make a conda release of recent Modin we need `ray==0.8.7` available in conda.

Note that to package new `ray` we also need to package `colorful` from https://github.com/timofurrer/colorful as `ray-0.8.7` depends on it.

**Comment by vnlitvinov** [comment]
Status update: recipes tested manually and update provided for our infra guys for publication. Awaiting confirmation from them.

**Comment by aregm** [comment]
Uploaded to intel/label/validation.
