### ISSUE TITLE
FSI: Implement zero-copy read where possible

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#2118]

**Comment by fexolm** [comment]
https://github.com/intel-ai/omniscidb/pull/94

**Comment by fexolm** [comment]
I'm waiting for a response from omnisci team, to discuss some architectural problems.

**Comment by fexolm** [comment]
we've discussed the patch with Alex, and I've reworked my pr.

**Comment by aregm** [comment]
@fexolm What is the status?

**Comment by Garra1980** [comment]
PR is under review - https://github.com/omnisci/omniscidb/pull/604

**Comment by fexolm** [comment]
PR was merged
