### ISSUE TITLE
Add testing for `read_parquet` from HDFS

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#2121]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin version**: 0.8.0
- **Python version**: 3.7.7

### Describe the problem
Currently `read_parquet` function hasn't any CI testing for HDFS.

Notes:
For including testing need to:
1. Install java 
2. Install hadoop
3. Set environment vars:
3.1. HADOOP_HOME=whereis hadoop
3.2. ARROW_LIBHDFS_DIR=$HADOOP_HOME/lib/native
3.3. JAVA_HOME=whereis java
4. Possible test case:
```python

def test_from_parquet_remote_hdfs():
    path = "hdfs://" + os.getcwd() + "/modin/pandas/test/data/hdfs.parquet"
    pandas_df = pandas.read_parquet(path)
    modin_df = pd.read_parquet(path)
    df_equals(modin_df, pandas_df)
```

**Comment by pyrito** [comment]
Looks like this has been added as of https://github.com/modin-project/modin/pull/2523
