### ISSUE TITLE
[OmniSci] Mortgage benchmark doesn't work with Calcite enabled

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#2128]
It successfully runs with disabled Calcite and hung with 100% CPU load with enabled Calcite.

**Comment by fexolm** [comment]
It looks, the issue is somewhere in our optimizations for joins. Disabling them allows us to execute queries with calcite enabled, however, performance is 2 times slower then ibis. I hope, that folks from omnisci will help to find the problem.

**Comment by ienkovich** [comment]
A possible reason for bad performance is `--enable-multifrag-rs` which gave us a nice boost for Ibis.

**Comment by fexolm** [comment]
Enabling joins optimization inlines projection into the join, that leads type mismatch of join keys for some reason. And that leads omnisci to fallback nested-loop join instead of a hash join. 
So, we need to find out the cause of type mismatch.

**Comment by fexolm** [comment]
It was fixed, by disable JoinProjectTranspose optimizations. Omnisci does not enable them by default, they use it only to optimize queries with views. Also, it looks there is a bug in that optimization on calcite side and also, omnisci does not support joins with casts on hashtable build phase. So, it's better to disable the optimization, as it should not significantly impact performance.
