### ISSUE TITLE
df.value_counts missed in dataframe_supported.rst

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2131]
See [pandas.DataFrame.value_counts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html?highlight=value_counts#pandas.DataFrame.value_counts)

**Comment by anmyachev** [comment]
cc @YarShev because you worked on Series.value_counts.

**Comment by YarShev** [comment]
@anmyachev , thanks for notice! I'll fix this.
