### ISSUE TITLE
[OmniSci] Dump debug timers into logs only

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#2187]
Currently `enable_debug_timer` causes timers to be dumped into the console. It should go into log files only.

**Comment by Garra1980** [comment]
@igalink please take a look

**Comment by igalink** [comment]
PR created: https://github.com/intel-ai/omniscidb/pull/100

**Comment by igalink** [comment]
Fixed in the PR: https://github.com/intel-ai/omniscidb/pull/100
