### ISSUE TITLE
convert docstrings in high level APIs to numpydoc style

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2197]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

**Comment by devin-petersohn** [comment]
Is this a duplicate of #1411

**Comment by anmyachev** [comment]
> Is this a duplicate of #1411?

#1411 is about the entire modin project(pydocstyle checks for all subfolders, for example, `modin/experimental`), but #2197 is about pandas public api(mainly for `modin/pandas` folder).
