### ISSUE TITLE
Regression on NYC Taxi Readcsv when using OmniSciDB

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#2198]
Read time went up to ~21s from pure 7sec on OmniSci without Modin or Ibis. 1 file, 20 mln records, 8276 CLX.

**Comment by fexolm** [comment]
On pure omnisci with flushed file caches I have 7 sec, with caches - 5sec. So, it seems there is no regression in omnisci. So, I think the issue is somewhere in modin, or in FSI endpoint for python. Will investigate that soon.

**Comment by fexolm** [comment]
That is a known issue. As we currently map category and string types from modin to string type in arrow, we can not decide on FSI side whether we want to dictionary encode that values or not. So, we always encode those strings to allow group by queries by them.
This could be solved, by mapping category types to arrow's dictionary type, which could be done with the current arrow's master, but this feature is not yet released. Also, support for converting arrow dictionaries to omnisci dictionaries on FSI side is in pr too. see https://github.com/intel-ai/omniscidb/pull/81

**Comment by fexolm** [comment]
We are waiting for arrow 2.0, as it supports explicit dictionary encoding in read_csv.

**Comment by pyrito** [comment]
What's the status on this?

**Comment by Garra1980** [comment]
let's close
