### ISSUE TITLE
Refactor Modin Dataframe Algebra to support general algebra, create ABC

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2204]
* mask (project and select)
* filters on metadata (dtype may require computation)
* fold (window) m-n
* fold n-n
* map 1-1
* group by (reduce)
* infer types as an operator: [columns]
* filter
* map 1-n
* join
* outer join - special case
* difference
* concat (union)
* group by
* type mapper TODO
* transpose
* to labels
* from labels

**Comment by YarShev** [comment]
Outdated
