### ISSUE TITLE
FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2206]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.8.1.1+1.gf1fe8fe

- **Python version**:

Python 3.7.7 :: Intel(R) Corporation

- **Code we can use to reproduce**:

### Describe the problem

When running some applications, e.g. Modin benchmark test `ci/benchmarks/test_benchmarks.py::test_groupby_sum[sum-no_indexing-10000x10000-int-modin]` I am getting thousands of warnings like this:
```
(pid=1814399) FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version.
(pid=1812862) FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version.
(pid=1811781) FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version.
(pid=1812876) FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version.
(pid=1814389) FutureWarning: The `squeeze` parameter is deprecated and will be removed in a future version.
```

**Comment by gshimansky** [comment]
`squeeze` parameter apparently has been deprecated in `DataFrame.groupby` and `Series.groupby`:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6503
https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L1733

**Comment by devin-petersohn** [comment]
This will simply be a matter of removing it and suppressing the warnings from internal invocations.

**Comment by devin-petersohn** [comment]
@gshimansky Can you try to reproduce this today? We want to clean up some of these older issues if possible.

**Comment by gshimansky** [comment]
This has been fixed a long time ago. I couldn't find the exact PR because as far as I remember it was fixed as a side effect of some groupby changes.
