### ISSUE TITLE
Use lgtm service to improve code quality

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2210]
Main page of the service: https://lgtm.com/

Modin page with problem found by `lgtm`: https://lgtm.com/projects/g/modin-project/modin?mode=list

It's also possible to add it to CI checks.

**Comment by anmyachev** [comment]
сс @devin-petersohn @Garra1980

**Comment by anmyachev** [comment]
For example:
* https://github.com/modin-project/modin/pull/2211

**Comment by devin-petersohn** [comment]
Sounds great, let's use it. There are a number of places where the code can be improved from this.

**Comment by devin-petersohn** [comment]
I just took another look at this, and our quality is pretty good. Let's fix some of the remaining issues.
