### ISSUE TITLE
Support returning multiple values from `_apply_full_axis`

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#2214]

**Comment by devin-petersohn** [comment]
What is the need for this?

**Comment by YarShev** [comment]
This is request from oneDAL team. They are currently implementing some prototype for their distributed algorithms with using Modin, namely, `_apply_full_axis`. In order to be compatible with scikit-learn they asked us to implement returning of multiple values from `_apply_full_axis`. I think this feature is useful for us as well because there are some functions (like `pandas.DataFrame.align`) which return multiple values. I have already provided the feature related to returning of multiple values from `_apply_full_axis` to oneDAL team  and currently I am doing `pd.DataFrame.align` implementation.

**Comment by YarShev** [comment]
I am closing the issue because we implemented another approach for distributed ML algorithms.
Having tested the performance for `aling` method with the feature of returning multiple values from `_apply_full_axis` it turned out the execution time of Modin implementation is significantly more than pandas. We will need to think of another implementation for `align`.
