### ISSUE TITLE
write dataframe to csv

### ISSUE THREAD

**Issue by tkmamidi** [modin-project/modin#2215]
I'm using Modin and it looks cool. However, when I try to write my dataframe to csv, it is defaulting to pandas. How far is the next update for this implementation?

**Comment by tkmamidi** [comment]
I'm using Modin and it looks cool. However, when I try to write my dataframe to csv, it is defaulting to pandas.

**Comment by devin-petersohn** [comment]
Thanks for the request @tkmamidi. I will assign it for the next release. `to_csv` will be difficult because it's not a parallel/distributed format.

**Comment by deschman** [comment]
It looks like this has been implemented and the docs describe that it should be. However modin 0.10.1 is still defaulting to pandas when calling df.to_csv while using the dask engine. I notice the PR from Feb 22 references ray in the notes. Has this not been implemented with the dask engine yet? If not, I can create another issue to investigate.

**Comment by anmyachev** [comment]
Hi @deschman!

You are right, `to_csv` function is not implemented for `dask` engine.
It would be great if you could create issue about this.
