### ISSUE TITLE
modin read and .apply()  giving RayTaskError(AttributeError)  : pandas.core.window.rolling.Rolling.aggregate AttributeError: 'function' object has no attribute 'Rolling'

### ISSUE THREAD

**Issue by sriramya1409** [modin-project/modin#2227]
### System information
- **OS Platform - Linux x86_64
- **Modin version** (`modin.__version__`): 0.8.1.1
- **Python version**:  3.7.4
- **Code we can use to reproduce**:
df_modin = mpd.read_csv('file.csv',sep=',',header=[0])
df_modin['date'] = mpd.to_datetime(df_modin['date'], format='%Y-%m-%d')
df_modin['Prev_Trans_Date'] = mpd.to_datetime(df_modin['Prev_Trans_Date'],format='%Y-%m-%d')
df_modin['TDays_bw_Trans'] = df_modin.apply(lambda df : tradeDiff_Pd(df.Prev_Trans_Date,df.date), axis=1)

### Describe the problem
I'm trying read a csv file using modin and applying a custom function on two columns. I'm facing a RayTaskError():pandas.core.window.rolling.Rolling.aggregate AttributeError: 'function' object has no attribute 'Rolling'.

I ran the same code( without setting modin engine) on windows OS. It worked fine. I'm facing issue on linux. To avoid this error, I tried to set the modin engine as "dask"(before importing modin) but it was running very slow. Please help! Thanks!
Pandas Version on Linux and Windows: 1.1.2
Ray Version (Both OS): 1.0.0

### Source code / logs
---------------------------------------------------------------------------
RayTaskError(AttributeError)              Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.7/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    110         if kwargs.get("sep", sep) is False:
    111             kwargs["sep"] = "\t"
--> 112         return _read(**kwargs)
    113 
    114     return parser_func

~/.local/lib/python3.7/site-packages/modin/pandas/io.py in _read(**kwargs)
    125     from modin.data_management.factories.dispatcher import EngineDispatcher
    126 
--> 127     pd_obj = EngineDispatcher.read_csv(**kwargs)
    128     # This happens when `read_csv` returns a TextFileReader object for iterating through
    129     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/.local/lib/python3.7/site-packages/modin/data_management/factories/dispatcher.py in read_csv(cls, **kwargs)
    111     @classmethod
    112     def read_csv(cls, **kwargs):
--> 113         return cls.__engine._read_csv(**kwargs)
    114 
    115     @classmethod

~/.local/lib/python3.7/site-packages/modin/data_management/factories/factories.py in _read_csv(cls, **kwargs)
     85     @classmethod
     86     def _read_csv(cls, **kwargs):
---> 87         return cls.io_cls.read_csv(**kwargs)
     88 
     89     @classmethod

~/.local/lib/python3.7/site-packages/modin/engines/base/io/file_reader.py in read(cls, *args, **kwargs)
     27     @classmethod
     28     def read(cls, *args, **kwargs):
---> 29         query_compiler = cls._read(*args, **kwargs)
     30         # TODO (devin-petersohn): Make this section more general for non-pandas kernel
     31         # implementations.

~/.local/lib/python3.7/site-packages/modin/engines/base/io/text/csv_reader.py in _read(cls, filepath_or_buffer, **kwargs)
    169         # or based on the column(s) that were requested.
    170         if index_col is None:
--> 171             row_lengths = cls.materialize(index_ids)
    172             new_index = pandas.RangeIndex(sum(row_lengths))
    173             # pandas has a really weird edge case here.

~/.local/lib/python3.7/site-packages/modin/engines/ray/task_wrapper.py in materialize(cls, obj_id)
     27     @classmethod
     28     def materialize(cls, obj_id):
---> 29         return ray.get(obj_id)

~/.local/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1426                     worker.core_worker.dump_object_store_memory_usage()
   1427                 if isinstance(value, RayTaskError):
-> 1428                     raise value.as_instanceof_cause()
   1429                 else:
   1430                     raise value

RayTaskError(AttributeError): ray::deploy_ray_func() (pid=11437, ip=162.128.131.13)
  File "python/ray/_raylet.pyx", line 448, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 465, in ray._raylet.execute_task
  File "/home/ss4496/.local/lib/python3.7/site-packages/ray/serialization.py", line 308, in deserialize_objects
    self._deserialize_object(data, metadata, object_ref))
  File "/home/ss4496/.local/lib/python3.7/site-packages/ray/serialization.py", line 247, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/ss4496/.local/lib/python3.7/site-packages/ray/serialization.py", line 226, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/ss4496/.local/lib/python3.7/site-packages/ray/serialization.py", line 216, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/ss4496/.local/lib/python3.7/site-packages/modin/backends/__init__.py", line 14, in <module>
    from .base import BaseQueryCompiler
  File "/home/ss4496/.local/lib/python3.7/site-packages/modin/backends/base/__init__.py", line 14, in <module>
    from .query_compiler import BaseQueryCompiler
  File "/home/ss4496/.local/lib/python3.7/site-packages/modin/backends/base/query_compiler.py", line 50, in <module>
    class BaseQueryCompiler(abc.ABC):
  File "/home/ss4496/.local/lib/python3.7/site-packages/modin/backends/base/query_compiler.py", line 1725, in BaseQueryCompiler
    pandas.core.window.rolling.Rolling.aggregate
AttributeError: 'function' object has no attribute 'Rolling'

**Comment by devin-petersohn** [comment]
Hi @sriramya1409 thanks for posting!

This is a strange one, it looks like the version of pandas that Ray is using is not the same as the version on the head node. Can you try the following on the Linux machine with the issue?

```python
import ray
ray.init()

@ray.remote
def f()
    import pandas
    print(pandas.core.window.rolling.Rolling.aggregate)

ray.get(f.remote())
ray.get([f.remote() for _ in range(96)])
```

It looks like Ray is failing to import the correct pandas version so let's test that with this piece of code.

**Comment by pyrito** [comment]
Hi @sriramya1409 are you still facing this issue? I'm going to close this issue since the thread has gone stale. Please reopen if needed!
