### ISSUE TITLE
df_equals do not assert frame missmatches in some cases

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2249]
Sometimes `df_equals` just returns `False` when frame aren't equals and not asserting it
https://github.com/modin-project/modin/blob/dd691cd0d4bb5403b38242563ed8b6ddb316734a/modin/pandas/test/utils.py#L506-L510

**Comment by YarShev** [comment]
Also, I think we need to use the functions in the public pandas API to compare dataframes via `df_equals`.
```python
from modin.pandas.test.utils import df_equals
FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
```

**Comment by dchigarev** [comment]
@YarShev good point! I've filled it in an issue #2260
