### ISSUE TITLE
Pull request message about commit message format is incorrect

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2258]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.1

- **Modin version** (`modin.__version__`):

0.8.1.1+4.gbd8f73a

When PR is created, developer is asked a question whether message format confirms to format described in `https://modin.readthedocs.io/en/latest/contributing.html`. The problem is that this page doesn't exist. There is a page `https://modin.readthedocs.io/en/latest/developer/contributing.html` but it doesn't mention anything about special message format.

**Comment by anmyachev** [comment]
#2193 solves this problem.
