### ISSUE TITLE
cumsum not checking dtypes wrong

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#228]
### Describe the problem
`cumsum` is not allowing summing over columns of objects and TimeStamps or summing over rows of TimeStamps or numeric types

### Source code / logs
```
import modin.pandas as pd

data = {
    "col3": [1, 2, 3, 4],
    "col4": [4, 5, 6, 7],
    "col1": [8.0, 9.4, 10.1, 11.3],
    "col2": [
    np.timedelta64(1, "M"),
    np.timedelta64(2, "D"),
    np.timedelta64(3, "Y"),
    np.timedelta64(20, "D"),
]}

pd.DataFrame(data).cumsum()
```

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
