### ISSUE TITLE
Default Ray password length is insufficient

### ISSUE THREAD

**Issue by asomsiko** [modin-project/modin#2280]
### Describe the problem
Modin generates a 16-byte Ray password which is too short. The recommendation is to have at least 32-byte secret

### Source code / logs
https://github.com/modin-project/modin/blob/cc57954466804bd7363ac4f5fe4d9967f7a1a169/modin/engines/ray/utils.py#L102

**Comment by anmyachev** [comment]
Hi @asomsiko thanks for posting!

This fix will be available from 0.8.2 release or you can install modin from master branch.
