### ISSUE TITLE
[OmniSci] Slow import in H2O Join benchmark

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#2315]
Data import for join benchmarks takes ~10sec while CSV parsing takes only 0.6 sec. Most probably time is spent in a dictionaries build. We should check if there is an opportunity for improvement.

**Comment by fexolm** [comment]
Dictionary encoding is slow for columns with high cardinality and it doesn't seem reasonable to dictionary encode such columns.  However, currently in omnisci-on-ray backend, we encode all columns, as we don't have an option not to encode them.
With arrow 2.0 we would have such option and also we would use arrow's dictionary encoding, so let's wait until we have arrow 2.0 and measure performance with it.

**Comment by ienkovich** [comment]
In H2O benchmarks we join by string columns and therefore dictionary encoding is what we need. Do we build all required dictionaries in parallel?

**Comment by fexolm** [comment]
Yes, we do. But OmniSci's bulk insert in the dictionary is almost serial. Maybe we could gain some performance using arrow's dictionary encoding. Let's wait arrow 2.0 and test it.

**Comment by anmyachev** [comment]
@AndreyPavlenko is this still relevant? Maybe you know.
