### ISSUE TITLE
Row Partition API

### ISSUE THREAD

**Issue by richardliaw** [modin-project/modin#2342]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

I'd like to be able to obtain a list of row partitions from a distributed Modin dataframe.

This would allow me to easily do distributed data-parallel training by feeding in these dataframe shards. This would be useful for both XGBoost and Horovod.

cc @tgaddair

**Comment by devin-petersohn** [comment]
Thanks @richardliaw for the request!

We should consider a developer API for cases like this that enable access to Modin internal partitions without needing to dig into them. I have been thinking about this some.

Design can look something like this:

```python
from modin.developer.partitioning import extract_row_partitions, extract_col_partitions
import ray

row_oid_list = extract_row_partitions(df, assert_type=ray.ObjectRef)
col_oid_list =  extract_col_partitions(df, assert_type=ray.ObjectRef)
```

Thoughts @richardliaw?

cc @aregm

**Comment by fschlimb** [comment]
I ran into a similar issue.
In addition to being able to extract the partitions it would be good to know the locality of each partition. Knowing where a partition (currently) resides can be used to minimize data movement when passing partitions to ray actors. Minimal data movement requires pairing actors and partitions which are 'pinned' to the same node.

**Comment by richardliaw** [comment]
@devin-petersohn sounds good!

**Comment by devin-petersohn** [comment]
I have a prototype ready to try. Install via `pip install git+https://github.com/devin-petersohn/modin@feat/2342`

Usage is simple:
```python
from modin.developer import unwrap_row_partitions

unwrap_row_partitions(df)
```

You will get a list of `ray.ObjectRef` each contain a row partition.

**Comment by fschlimb** [comment]
Thanks, works great for me!
What about getting sufficient information to be able to map data to local actors?

**Comment by fschlimb** [comment]
How would this work with modin on dask?

**Comment by YarShev** [comment]
> Thanks, works great for me!
> What about getting sufficient information to be able to map data to local actors?

I think, we

**Comment by YarShev** [comment]
> Thanks, works great for me!
> What about getting sufficient information to be able to map data to local actors?

Maybe it would be good to have some kind of `RowPartitionsActor` and `ColPartitionsActor` that will keep row partitions and column partitions, respectively, assigned to them. Also, these actors should keep some info on node ip address (it is supposed an actor per node).

**Comment by YarShev** [comment]
> How would this work with modin on dask?

It will work the same way as for ray. If I am not correct, @devin-petersohn , please, correct me.

**Comment by devin-petersohn** [comment]
It will work the same, if you are expecting a certain engine, there is a keyword argument in the API for the engine. It will make sure that the objects are compatible with that engine or throw an error if they are not.

**Comment by fschlimb** [comment]
> Maybe it would be good to have some kind of RowPartitionsActor and ColPartitionsActor that will keep row partitions and column partitions, respectively, assigned to them. Also, these actors should keep some info on node ip address (it is supposed an actor per node).
Do mean as a modin-internal entity or something the user should use? How would a user benefit from this, can you provide a short made-up example?

**Comment by YarShev** [comment]
That can be both Modin entity (if that is really necessary) and something the user should define. For instance, there are some frameworks, which use threads power under the hood, to execute an algorithm. Thus, it might be better to use one actor per node that uses all resources for threading.

**Comment by YarShev** [comment]
> Thanks, works great for me!
> What about getting sufficient information to be able to map data to local actors?

I supplemented @devin-petersohn's prototype a little bit. `unwrap_row_partitions` returns a `list` containing tuples (`ray.ObjectRef` to node IP address for row partition, `ray.ObjectRef` to row partition) in this fork: `pip install git+https://github.com/YarShev/modin@dev/yigoshev-issue2342`. Does it make sense?
