### ISSUE TITLE
pip install modin[dask] fails

### ISSUE THREAD

**Issue by andreamoro** [modin-project/modin#2350]
### System information
- OS Mac X 10.5.17
- Python 3.8, no modin installed at first (but tried also by installing modin later)

### Describe the problem
the `pip install modin[dask]` command fails with the following error `zsh: no matches found: modin[dask]`.

Had to install distributed, dask and modin individually.

**Comment by anmyachev** [comment]
@andreamoro thanks for posting!

Can you try `pip install 'modin[dask]'`?

It looks like a [feature](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity) of `zsh`.

**Comment by andreamoro** [comment]
Yes, thanks this did solve the problem already yesterday.
