### ISSUE TITLE
TypeError when importing modin

### ISSUE THREAD

**Issue by ek-nath** [modin-project/modin#236]
### System information
- **Amazon linux (Centos)**:
- **Modin installed from binary**:
- **Modin version**: 0.2.2:
- **Python version**: 3.7.0:
- **Ray version**: 0.5.3
- **import modin.pandas**:

### Describe the problem
I am getting an import error because of an unexpected argument `use_raylet`

### Source code / logs
```
In [1]: import modin.pandas
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-d42df328a6c7> in <module>()
----> 1 import modin.pandas

~/anaconda3/lib/python3.7/site-packages/modin/pandas/__init__.py in <module>()
     78             include_webui=False,
     79             redirect_worker_output=True,
---> 80             use_raylet=True,
     81         )
     82 except AssertionError:

TypeError: init() got an unexpected keyword argument 'use_raylet'
```

**Comment by devin-petersohn** [comment]
What is your Ray version?

```python
import ray
ray.__version__
```

**Comment by devin-petersohn** [comment]
Hi @ek-nath, I did a bit more digging. It looks like you may have recently built Ray from source. We depend on the pypi release of Ray, and the `ray.init` API changed slightly since the last Ray release. If you want to resolve this issue, you will have to install Ray using pip (`pip install ray`).  

cc @robertnishihara

**Comment by ek-nath** [comment]
I have updated the original issue report with the version. It is 0.5.3

**Comment by ek-nath** [comment]
installing `ray` via pip doesn't seem to resolve the issue either. I will try to check with an older version of ray and report back

**Comment by devin-petersohn** [comment]
You may need to `pip uninstall ray; pip install ray`.

**Comment by ek-nath** [comment]
This is weird. I am unable to install `ray` at all using `pip`. 

```bash
dev-machine % pip install ray       
Collecting ray
  Could not find a version that satisfies the requirement ray (from versions: )
No matching distribution found for ray

(18-10-31 20:11:08) <1> [~]  
dev-machine % pip install ray==0.5.3
Collecting ray==0.5.3
  Could not find a version that satisfies the requirement ray==0.5.3 (from versions: )
No matching distribution found for ray==0.5.3

(18-10-31 20:11:10) <1> [~]  
```

**Comment by ek-nath** [comment]
Was able to install using `pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp37-cp37m-manylinux1_x86_64.whl` based on instructions [here](https://ray.readthedocs.io/en/latest/installation.html)

But the problem of the `use_raylet` persists and like it says in the URL, it installs version 0.5.3

**Comment by devin-petersohn** [comment]
Oh, it is a Python 3.7 issue. Ray 0.5.3 on pypi did not ship with Python 3.7 support.

There is a PR that will resolve this `use_raylet` issue: https://github.com/ray-project/ray/pull/3176, and once it gets merged the nightly wheels (where you installed from) will reflect that change.

In the meantime, it is possible to install this way:
```
pip install git+https://github.com/devin-petersohn/modin/@no_raylet
```

I pushed a branch that removes the `use_raylet` option to my fork of Modin. Everything else is identical to current master.

**Comment by ek-nath** [comment]
Success @devin-petersohn 
```bash
python -c "import modin.pandas"
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2018-10-31_20-41-01_29838/logs.
Waiting for redis server at 127.0.0.1:12739 to respond...
Waiting for redis server at 127.0.0.1:17503 to respond...
Starting the Plasma object store with 6.4900694009999995 GB memory using /dev/shm.
```
