### ISSUE TITLE
Error when using unhashable key in '__setitem__'

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#2362]
### Describe the problem

I get `TypeError: unhashable type: 'slice'` when trying to set value(s) to `Series` using slice.

### Source code / logs

```python
import modin.pandas as pd
import pandas

ps = pandas.Series([1,2,3])
ms = pd.Series([1,2,3])

ps[1:3] = 0
ps
0    1
1    0
2    0
dtype: int64

ms[1:3] = 0
TypeError: unhashable type: 'slice'
```

**Comment by dchigarev** [comment]
It doesn't work for all cases where `key` is not a label-like value.
<details><summary>Example</summary>

```python
import modin.pandas as pd

ms = pd.Series([1,2,3])
ms[1] = 0 # Works fine
ms[1:3] = 0 # TypeError
ms[[True, False, True]] = 0 # TypeError
ms[[0, 1]] = 0 # TypeError
```

</details>

Current `Series.__setitem__` implementation:
https://github.com/modin-project/modin/blob/f14a3c187fd2349348e74c9e5095884371ef8645/modin/pandas/series.py#L287-L292
Problems:
1. We check that `key` is in `self.keys` dict assuming that `key` is always hashable, however it doesn't work for lists and slices.
2. Right after this check it calls query compilers `setitem` method, which also works only for label-like values, so adding a check that `key is hashable` to the first if-statement will not resolve the problem

**Comment by YarShev** [comment]
We probably can fix similar case for DF with the same way because the case for DF is currently defaulting to pandas. @dchigarev , will you look at this, please?

```python
import modin.pandas as pd
df = pd.DataFrame([1,2,3])
ms[1:3] = 0
UserWarning: `DataFrame.setitem_without_string_columns` defaulting to pandas implementation.
```

**Comment by dchigarev** [comment]
sure
