### ISSUE TITLE
Update pyarrow to 1.0 in tutorial

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#2372]
https://github.com/modin-project/modin/blob/master/examples/tutorial/tutorial_notebooks/cluster/modin-cluster.yaml#L138

**Comment by YarShev** [comment]
@anmyachev

**Comment by anmyachev** [comment]
@devin-petersohn I don't see that the examples are actually using `pyarrow`. Can we just remove the line `- pip install pyarrow==0.16` from `modin-cluster.yaml`?

**Comment by devin-petersohn** [comment]
@anmyachev Yes it should be fine to remove
