### ISSUE TITLE
Replace QueryRunner by DBHandler in the DBEngine

### ISSUE THREAD

**Issue by igalink** [modin-project/modin#2382]
DBHandler provides more options for database management then QuryRunner.
So it should be used in the DBEngine.

**Comment by Garra1980** [comment]
THis should go prior #1612 followed by preparing patch(es) for upstreaming

**Comment by igalink** [comment]
The new PR created and approved: https://github.com/intel-ai/omniscidb/pull/119
Testing in final stage: 
1. C++ unit tests - done
2. initdb - done
3. omisci_server - done
4. DBE tests in progress

**Comment by igalink** [comment]
All tests are done
PR updated: https://github.com/intel-ai/omniscidb/pull/119/
