### ISSUE TITLE
read_csv with header passed from outside doesn't seem to work

### ISSUE THREAD

**Issue by aakashganga** [modin-project/modin#239]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Modin installed from (source or binary)**: pypi
- **Modin version**:0.2.2
- **Python version**:3.6
- **Exact command to reproduce**: pd.read_csv('file,sep='\t',index_col=False,names=headerlist)

### Describe the problem

It appears that read_csv with header passed from outside and index unspecified doesn't work. Get the following error.

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The above command works with Pandas.

**Comment by devin-petersohn** [comment]
@aakashganga Thanks for posting this issue! I will look into the issue to reproduce it and get it fixed. Thanks again!

**Comment by devin-petersohn** [comment]
So it looks like this will work as long as you pass a `list` object, but if you try to pass a `modin.pandas.Series` or `modin.pandas.Index` object it will not. 

I will fix this, in the meantime if it is blocking you, you can convert the names to a python `list` and it should work normally. Thanks again for posting the issue!

**Comment by aakashganga** [comment]
Got it.
