### ISSUE TITLE
Publish ray to conda-forge

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2396]

**Comment by vnlitvinov** [comment]
Spent about 26 hours already, prepared a Linux version that builds Ray 1.0.1.
Now need Windows version.

**Comment by devin-petersohn** [comment]
Does Ray still vendor other packages? It is not allowed in conda-forge

**Comment by vnlitvinov** [comment]
I'm not sure about that... it might be, but if they do, they "hide" the packages under themselves, so vendored packages should not be impacting the environment otherwise. Would that still be a problem? 'cause if it would, I'd have to spend more time on this before trying to publish.

Do you know if they have a tool to check for those problems, or should I just file a PR and deal with it?

**Comment by devin-petersohn** [comment]
It is a problem whether the packages are hidden or not because it "hides" dependencies from conda itself. 

I don't think there's a tool that checks for this, I believe it is on the honor system.

**Comment by vnlitvinov** [comment]
_time tracking:_ spent a day trying to make Ray again build but this time on a clean installation with no system-wide compilers... not yet successful; also `import ray` fails in testing phase. Need to investigate closer.

**Comment by vnlitvinov** [comment]
_time tracking_: after another day and a half Ray finally builds on Linux and _mostly_ builds on Windows (might be my laptop's Visual Studio install being funky).

**Comment by vnlitvinov** [comment]
_time tracking_: another day (about 9 hours to this mark) spent trying to make Ray pass conda-forge CI. I decided to disable MacOS for now lacking HW for developing (and lack of our interest), and Ray on Linux finally builds fine in all variants, but not all packages' tests pass yet. Ray on Windows is not yet compiling despite working fine on my laptop, apparently their CI has older version of platform SDK installed.

**Comment by vnlitvinov** [comment]
> It is a problem whether the packages are hidden or not because it "hides" dependencies from conda itself.

Oh, and a follow-up - I think my version of the recipe no longer bundles any shared library besides what Ray needs, but they bundle a few executables (e.g. `redis`). I don't think we can easily remove those and replace with outside ones, though.
Small hope of salvation is those executables should not be exposed via `$PATH`.

**Comment by vnlitvinov** [comment]
_time tracking_: after another day Ray on Linux finally passes CI completely, and Ray on Windows builds but not yet pass tests due to some missing dependencies.

**Comment by vnlitvinov** [comment]
_time tracking_: 2 more hours spent investigating, and now Ray passes Linux and Windows CI in conda-forge PR

**Comment by vnlitvinov** [comment]
_time tracking_: about 8 man-hours later Ray passes again, but this time with `ray-rllib` (which uncovered some bugs in packaging; Windows and symlinks is a very... "funny" couple).

**Comment by vnlitvinov** [comment]
_time tracking_: hard to cound, but should be around 4 more hours spent fixing `ray-rllib` on Windows and pestering conda-forge guys for approval.

Result: https://anaconda.org/conda-forge/ray-core
