### ISSUE TITLE
[DOCS] Add documentation main page for links examples

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2412]
We have many examples in the repo, but the documentation doesn't contain any. It would be good to add the walk-throughs from the github repo.

This page should link to the notebooks in the repo. Separate issues will be created for each example.

**Comment by vfdev-5** [comment]
I'd like to work on this issue. Could you please assign it to me ?

**Comment by mvashishtha** [comment]
@devin-petersohn We have a "getting started" section in the github README with links to notebooks and examples. I'm going to close this issue.
