### ISSUE TITLE
[DOCS] CONTRIBUTING.rst does not render the commit message formatting example

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2424]
The code block is missing a newline after

**Comment by reshamas** [comment]
@devin-petersohn 
at which should there be a blank line?
https://github.com/modin-project/modin/blob/master/docs/CONTRIBUTING.rst

**Comment by reshamas** [comment]
Looks like line 52 which has only `.` should be deleted.

**Comment by reshamas** [comment]
prior to line 92, add a blank line.
