### ISSUE TITLE
[DOCS] Bad links in index.rst

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2426]
```
modin/docs/index.rst:140: WARNING: toctree contains reference to nonexisting document 'contributing'
modin/docs/index.rst:154: WARNING: toctree contains reference to nonexisting document 'contributing'
modin/docs/index.rst:154: WARNING: toctree contains reference to nonexisting document 'architecture'
```

These files were moved, but the links were not updated.

**Comment by vfdev-5** [comment]
@devin-petersohn can we also rename CONTRIBUTING.rst to contributing.rst here ?

**Comment by devin-petersohn** [comment]
Yes, according to the github documentation, it is not case sensitive: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file

That can be fixed as a part of this issue, since the links are pointing to the old file.
