### ISSUE TITLE
AttributeError: module 'modin.pandas' has no attribute 'read_gbq'

### ISSUE THREAD

**Issue by zeevikal** [modin-project/modin#243]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Modin installed from (source or binary)**: pip
- **Modin version**: 0.2.2
- **Python version**: 3.6
- **Exact command to reproduce**: pd.read_gbq(query, project_id, private_key, dialect)

### Describe the problem
I'm getting this error when I'm trying to read data (via query) from Google BigQuery, as worked in Pandas library. 

### Source code / logs
AttributeError: module 'modin.pandas' has no attribute 'read_gbq'

**Comment by devin-petersohn** [comment]
Hi @zeevikal, thanks for posting this! 

I have implemented this in #244.

**Comment by zeevikal** [comment]
you're awesome! thanks 👍

**Comment by zeevikal** [comment]
hi @devin-petersohn , when do you think you'll upload a new version with this PR?

**Comment by devin-petersohn** [comment]
We are planning a new release this Thursday. We are trying to release every 2-3 weeks. If you want to try this now, you can use pip to install directly from GitHub: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

That would also be a good way to let me know if you run into any problems!

**Comment by zeevikal** [comment]
hi @devin-petersohn ,
I installed it from the master branch and got few errors with `ray` lib.
first I got `Task is a driver task and so the object created by ray.put could not be reconstructed` error message.
then I added `object_store_memory` and started it with the `--shm-size` flag.
I got another error message - `Could not connect to socket /tmp/plasma_storeXXX`.
FYI - I'm running my job with Kubernetes cluster.

**Comment by devin-petersohn** [comment]
How did you add `object_store_memory`? Would you mind posting a small code snippet? (Just the imports and `ray.init` lines will be fine)

cc @pcmoritz

Side note: it might be worth creating a new issue to track this specific issue for the sake of others who might run into this problem.

**Comment by zeevikal** [comment]
sure, I'll open one.
@devin-petersohn please let me know if there is a problem to run `modin` or `ray` libraries on a docker image.
thanks

**Comment by devin-petersohn** [comment]
There shouldn't be any problem with running either of these in Docker, I'll add some comments to the new issue #245.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
