### ISSUE TITLE
Error while creating big sized Modin DataFrame 

### ISSUE THREAD

**Issue by KalyanovD** [modin-project/modin#2455]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **AWS instance**: c5.18xlarge
- **Modin version** (`modin.__version__`): 0.8.2
- **Python version**: 3.7
- **Code we can use to reproduce**:
```
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-r', metavar='n', help='ray init', type=int, default=0)
args = parser.parse_args()`

if args.r==1:
    import ray
    ray.init(num_cpus=36)
    print(ray.nodes())

import modin.pandas as pd
import daal4py as d4p
from daal4py.sklearn import patch_sklearn
patch_sklearn()

import numpy as np
from sklearn.decomposition import PCA
from sklearn.datasets import make_classification

X = pd.DataFrame(make_classification(n_samples=10000000, n_features=280)) # error

algo = d4p.normalization_zscore(doScale=True)
X = algo.compute(X).normalizedData

pca = PCA(n_components=2, svd_solver='daal')
Xt = pca.fit_transform(X)

if args.r==1:
    ray.shutdown()
```

To reproduce use conda envs, install modin from pip and run python file.py

### Describe the problem

At this instance we have error while creating DataFrame. It was noticed first with using read_csv() for reading dataset with similar shape. This error wasn't reproduced on other machines. If we manage ray processes manually(python file.py -r 1) this error wasn't reproduced too.
### Source code / logs

```
Intel(R) Data Analytics Acceleration Library (Intel(R) DAAL) solvers for sklearn enabled: https://in                                                                                                                                         telpython.github.io/daal4py/sklearn.html

UserWarning: Distributing <class 'tuple'> object. This may take some time.
*** Aborted at 1605601119 (unix time) try "date -d @1605601119" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGBUS (@0x7f94fbf76fe0) received by PID 4659 (TID 0x7f91f5e69700) from PID 18446744073641881568                                                                                                                                         ; stack trace: ***
    @     0x7fa70a2b33c0 (unknown)
    @     0x7fa70a23a877 (unknown)
    @     0x7fa6eed3f421 execute_native_thread_routine_compat
    @     0x7fa70a2a7609 start_thread
    @     0x7fa70a1ce103 clone
Bus error (core dumped)
```

**Comment by YarShev** [comment]
Hi @KalyanovD, thanks for posting! I think `DataFrame`, which you want to create, is not able to fit in memory of your machine. If it is, you should consider out of core feature in Modin (please, look at [here](https://modin.readthedocs.io/en/latest/out_of_core.html)). If it is not, please let us know. Also, when creating `DataFrame` with the way you use, I get the following the message (`VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray`). Thus, you need to consider a recommendation from that message.

**Comment by pyrito** [comment]
Hi @KalyanovD , piggy backing off what @YarShev , could you give some details on what machines this wasn't reproduced on? Did those machines have more memory? I'm going to go ahead and close this issue since the thread has gone stale, but please re-open if the issue still persists.
