### ISSUE TITLE
Why is not  modin  imported? 

### ISSUE THREAD

**Issue by Barolina** [modin-project/modin#2464]
i use modin[dask]==0.8.2

When  do i run  my script , happen only  this 

```
  UserWarning: The Dask Engine for Modin is experimental.
```

the script stops at the line 
```
 import modin.pandas as pd 
```

**Comment by devin-petersohn** [comment]
Hi @Barolina, thanks for posting!

Do you see any error messages? The warning is normal and only informational.

**Comment by Barolina** [comment]
i found, thanks
