### ISSUE TITLE
hi. in my notebook modin couse ,ploty incorrect plot dataframe.

### ISSUE THREAD

**Issue by zeintiz** [modin-project/modin#2466]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

**Comment by devin-petersohn** [comment]
Hi @zeintiz, thanks for posting. We need some more information to be able to resolve or help with the issue. Can you tell us about the dataframe you are using with plotly and how it is incorrect? Thanks in advance!

**Comment by devin-petersohn** [comment]
Closing as more information needed. Please feel free to reopen with more information. Thanks!
