### ISSUE TITLE
Publish Windows-installable gpustat

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2474]
Currently `gpustat` (declared `noarch`) is not installable on Windows due to one of its dependencies missing for Windows.
`gpustat` is a soft dependency of Ray.

**Comment by vnlitvinov** [comment]
Ref: https://github.com/conda-forge/gpustat-feedstock/pull/2

**Comment by vnlitvinov** [comment]
Might be bloked by waiting for upstream release, ref: https://github.com/wookayin/gpustat/issues/92

**Comment by anmyachev** [comment]
@vnlitvinov is it relevant?

**Comment by vnlitvinov** [comment]
I guess we can close that and, if that ever arises, ask Ray guys to do the required work since they've now taken on maintaining Ray in conda-forge.
