### ISSUE TITLE
read_csv with Ray engine with 'lineterminator' parameter outputs incorrect result

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2493]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin version** : ce2bea8867739ea792cdda0dce8ad50e366ebae1
- **Python version**: 3.8.6
- **Code we can use to reproduce**: 
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals

test_filename = "test.csv"
kwargs = {
    "filepath_or_buffer": test_filename,
    "lineterminator": "x",
}
str_two_cols = "col1,col2x1,2x3,4x"

try:
    with open(test_filename, "w") as f:
        f.write(str_two_cols)

    df_pandas = pandas.read_csv(**kwargs)
    print("pandas.read_csv output:\n", df_pandas)
    df_pd = pd.read_csv(**kwargs)
    print("pd.read_csv output:\n", df_pd)
    df_equals(df_pandas, df_pd)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
pandas.read_csv output:
    col1  col2
0     1     2
1     3     4
pd.read_csv output:
 Empty DataFrame
Columns: [col1, col2]
Index: []
Traceback (most recent call last):
  File "test.py", line 125, in <module>
    df_equals(df_pandas, df_pd)
  File "/modin/pandas/test/utils.py", line 511, in df_equals
    assert False, "One of the passed frames is empty, when other isn't"
AssertionError: One of the passed frames is empty, when other isn't
```

**Comment by pyrito** [comment]
I am still able to reproduce this bug on the latest master.

**Comment by brunovh** [comment]
Do I see it right that it was fixed by removing support for `lineterminator` and defaulting to pandas?

**Comment by anmyachev** [comment]
> Do I see it right that it was fixed by removing support for `lineterminator` and defaulting to pandas?

Hi @brunovh , unfortunately yes. Do you need an optimized version for `lineterminator`?

**Comment by brunovh** [comment]
Hi @anmyachev I had been using this in 0.18.0 and was hoping to benefit from bug fixes with update to newest version. Would be great to see this coming back in future updates

**Comment by anmyachev** [comment]
> lineterminator

Thanks for the feedback

**Comment by anmyachev** [comment]
@brunovh I suppose it's easy to add support for standard cases like: `"\n"`, `"\r"`, `"\r\n"`, but difficult for more specific ones. Will partial support for standard parameters help you?

**Comment by brunovh** [comment]
@anmyachev Partial support for standard parameters would be very helpful!
