### ISSUE TITLE
What's Modin required Pandas version?

### ISSUE THREAD

**Issue by amberz** [modin-project/modin#2499]
The pandas version output is '1.1.4' from below script. 
import pandas as pd
pd.__version__

but when I run modin, got error pandas version is 0.25.3 and Modin doesn't match with Pandas. 
import modin.pandas as pd

UserWarning: The pandas version installed 0.25.3 does not match the supported pandas version in Modin 1.1.4. This may cause undesired side effects!

**Comment by YarShev** [comment]
Hi @amberz ! Apparently, you have pandas installed 0.25.3. To make sure what pandas version you have, can you run the following command in your bash:
```bash
# if you use conda, then
$ conda list | grep pandas
# if you use pip, then
$ pip list | grep pandas
```

**Comment by Babakjfard** [comment]
I get this error message :

UserWarning: The pandas version installed 1.1.4 does not match the supported pandas version in Modin 1.1.5. This may cause undesired side effects!

**Comment by Garra1980** [comment]
should be 1.2.3 currently

**Comment by devin-petersohn** [comment]
@Babakjfard If you are using Python 3.6 or below, that is no longer supported by pandas/Modin. The version you are using is probably ~1 year old.

Modin and pandas have moved to supporting minimum Python version 3.7.1

**Comment by srivallid** [comment]
I get the following error when I import Modin
`UserWarning: The pandas version installed 1.2.3 does not match the supported pandas version in Modin 1.2.4. This may cause undesired side effects!`

I am using anaconda and jupyter, Anaconda is not allowing me to upgrade pandas to 1.2.4, when attempted, it shows a list of conflicts.

Is there any way to downgrade modin so that the pandas versions are compatible?

**Comment by YarShev** [comment]
@srivallid , why can't you remove pandas 1.2.3 at all and install pandas 1.2.4 using `conda install pandas=1.2.4`?

**Comment by srivallid** [comment]
> @srivallid , why can't you remove pandas 1.2.3 at all and install pandas 1.2.4 using `conda install pandas=1.2.4`?

I tried `conda remove pandas`, it removed a bunch of other packages including modin, I tried installing modin with `conda install -c conda-forge modin`, it says `Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`

**Comment by YarShev** [comment]
What is your conda version?

**Comment by srivallid** [comment]
> What is your conda version?

4.10.3

**Comment by YarShev** [comment]
Ok, let's start from clean environment. You can install the latest release into that new environment via `pip install modin` (``pip install modin[ray]` - with ray support, `pip install modin[dask]` with dask support).

**Comment by abubelinha** [comment]
Hi. I am on a different environment but I guess the problem is similar so I don't think this deserves opening a new issue.
I have an account in a shared computing cluster where we can load different preconfigured software modules.
In my case, I have the following modules combination:
```
$ module load pandas/1.3.4-python-3.9.9 
$ module load dask/2022.2.0 # not sure if this is necessary or not for Modin

```
After loading those modules, I did this:
```
$ pip install modin
$ python
Python 3.9.9 (main, Dec  1 2021, 15:05:04)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import modin.pandas as pd
UserWarning: The pandas version installed 1.3.4 does not match the supported pandas version in Modin 1.4.1. This may cause undesired side effects!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abubelinha/.local/lib/python3.9/site-packages/modin/pandas/__init__.py", line 183, in <module>
    from .dataframe import DataFrame
  File "/home/abubelinha/.local/lib/python3.9/site-packages/modin/pandas/dataframe.py", line 49, in <module>
    from .groupby import DataFrameGroupBy
  File "/home/abubelinha/.local/lib/python3.9/site-packages/modin/pandas/groupby.py", line 20, in <module>
    from pandas.core.apply import reconstruct_func
ImportError: cannot import name 'reconstruct_func' from 'pandas.core.apply' (/opt/cluster/2020/software/Core/pandas/1.3.4-python-3.9.9/lib/python3.9/site-packages/pandas/core/apply.py)
```

Is this due to unsupported Pandas version, or it is the Python version, or anything else?
Perhaps I could pip install a particular Modin version which is compatible with pandas.1.3.4 & python-3.9.9 ?

Thanks a lot in advance

**Comment by pyrito** [comment]
@abubelinha , are you still having this issue?

**Comment by kart2k15** [comment]
> @abubelinha , are you still having this issue?

yess

**Comment by mvashishtha** [comment]
@kart2k15 what is the issue you are having? What pandas and python versions are you using? Are you able to use Modin at all? Are you able to upgrade python or pandas?
