### ISSUE TITLE
Dataframe Algebra - how Pandas operations were written using algebra defined by Modin?

### ISSUE THREAD

**Issue by deHasara** [modin-project/modin#2506]
In Modin documentation, it says that Modin internal dataframe algebra has narrowed down 200+ Pandas operations to 15 operations. Few examples('pivot', 'agg' and reindex_like) were explained in the paper. Where can I find, how other Pandas operations were written using Modin dataframe algebra?

**Comment by devin-petersohn** [comment]
Hi @deHasara, thanks for posting!

I'm currently working on a paper that explains this for every operator. It is a lot of work as you can imagine! We don't have any current resources published on it yet. We started with the implementation as a concrete reference implementation, and are now going back and writing about it.

**Comment by pyrito** [comment]
Closing this since the paper has been published now. @deHasara please check out: https://people.eecs.berkeley.edu/~totemtang/paper/Modin.pdf
