### ISSUE TITLE
Using import modin.pandas doesn't work

### ISSUE THREAD

**Issue by amoghsr** [modin-project/modin#2507]
### System information
- **OS Platform and Distribution**: Windows 10 18363.1198
- **Modin version** (`modin.__version__`):  0.8.2.1+35.g299ba18
- **Python version**: 3.8
- **Code we can use to reproduce**: 
```
import modin.pandas as pd
df = pd.read_json("data.json", lines=True)
print(df)
```

### Describe the problem
I'm trying to reduce the time it takes to process a dataset with pandas. Following the documentation it is still unclear on how to do so. The program doesn't return any output and just gets stuck. Please help as I am a beginner.
### Source code / logs
No output produced.

**Comment by anmyachev** [comment]
Hello @amoghsr! 

It's a pity that it happened.

Please provide more context so that we can resolve your issue:
* how did you install the modin
* do you use all the defaults, or set up any environment variables (starting with `Modin_`)?

**Comment by amoghsr** [comment]
Can I reply here?

I installed the module with pip install modin[all]
I haven’t set up any paths or envs 


Sent from Yahoo Mail for iPhone


On Thursday, December 3, 2020, 12:16 PM, Anatoly Myachev <notifications@github.com> wrote:




Hello @amoghsr!

It's a pity that it happened.

Please provide more context so that we can resolve your issue:
   
   - how did you install the modin
   - do you use all the defaults, or set up any environment variables (starting with Modin_)?

**Comment by anmyachev** [comment]
@amoghsr 
* please show your environment via `pip list` or `conda list` (if you used pip inside a conda environment)
* try to run next script and show output (to make sure that the import is not working, and not the function)
  ```python
  import modin.pandas as pd
  print("modin import successful")
  df = pd.read_json("data.json", lines=True)
  print("read_json successful")
  print(df)
  ```

**Comment by amoghsr** [comment]
Heres 1.Package                  Version------------------------ -------------------aiohttp                  3.7.3aiohttp-cors             0.7.0aioredis                 1.3.1async-timeout            3.0.1attrs                    20.3.0backcall                 0.2.0beautifulsoup4           4.9.3blessings                1.7bokeh                    2.2.3boto3                    1.4.8botocore                 1.8.50cachetools               4.1.1certifi                  2020.11.8chardet                  3.0.4click                    7.1.2cloudpickle              1.4.1colorama                 0.4.4colorful                 0.5.4cycler                   0.10.0dask                     2.19.0decorator                4.4.2distributed              2.19.0docutils                 0.16filelock                 3.0.12fsspec                   0.8.4google                   3.0.0google-api-core          1.23.0google-auth              1.23.0googleapis-common-protos 1.52.0gpustat                  0.6.0grpcio                   1.34.0HeapDict                 1.0.1hiredis                  1.1.0httpagentparser          1.9.0idna                     2.10ijson                    3.1.3ipykernel                5.3.4ipython                  7.19.0ipython-genutils         0.2.0jedi                     0.17.2Jinja2                   2.11.2jmespath                 0.10.0jsonschema               3.2.0jupyter-client           6.1.7jupyter-core             4.7.0kiwisolver               1.3.1locket                   0.2.0MarkupSafe               1.1.1matplotlib               3.3.3modin                    0.8.2.1+35.g299ba18msgpack                  1.0.0multidict                5.0.2numpy                    1.19.4nvidia-ml-py3            7.352.0opencensus               0.7.11opencensus-context       0.1.2packaging                20.7pandas                   1.1.4parso                    0.7.1partd                    1.1.0pickleshare              0.7.5Pillow                   8.0.1pip                      20.3plumbum                  1.6.9prometheus-client        0.9.0prompt-toolkit           3.0.8protobuf                 3.14.0psutil                   5.7.3py-spy                   0.3.3pyarrow                  1.0.0pyasn1                   0.4.8pyasn1-modules           0.2.8Pygments                 2.7.2pyparsing                2.4.7pyrsistent               0.17.3python-dateutil          2.8.1pytz                     2020.4pywin32                  300PyYAML                   5.3.1pyzmq                    20.0.0ray                      1.0.1.post1redis                    3.4.1requests                 2.25.0rpyc                     4.1.5rsa                      4.6s3transfer               0.1.13setuptools               50.3.2six                      1.15.0sortedcontainers         2.3.0soupsieve                2.0.1tblib                    1.7.0toolz                    0.11.1tornado                  6.1traitlets                5.0.5typing-extensions        3.7.4.3ua-parser                0.10.0ujson                    4.0.1urllib3                  1.26.2user-agents              2.2.0wcwidth                  0.2.5yarl                     1.6.3zict                     2.0.0


As for the script you gave, it doesn't run. It gives no output and keeps running. If I remove the import statement and the code it was used for, it works.

    On Thursday, 3 December 2020, 16:15:37 GMT+4, Anatoly Myachev <notifications@github.com> wrote:  
 
 


@amoghsr
   
   - please show your environment via pip list or conda list (if you used pip inside a conda environment)
   - try to run next script and show output (to make sure that the import is not working, and not the function)   import modin.pandas as pd
print("modin import successful")
df = pd.read_json("data.json", lines=True)
print("read_json successful")
print(df)

**Comment by anmyachev** [comment]
@amoghsr you are using the modin from the master, therefore you should also install modin dependencies from the master. Try next command: `pip install -U git+https://github.com/modin-project/modin@master#egg=modin[all]`, then show output of `pip list` and also try rerun script.

**Comment by mvashishtha** [comment]
Closing this because it's been almost 2 years. @amoghsr please reply here if you need more help.
