### ISSUE TITLE
Use codecov' delayed notifications in our CI

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2544]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

It would be great if we did not see premature numbers from codecov.

For details see:
https://docs.codecov.io/docs/merging-reports#delayed-notifications

**Comment by pyrito** [comment]
Yes, we should do something about the codecov notifications.
