### ISSUE TITLE
dataframe.applymap support? 

### ISSUE THREAD

**Issue by asencis** [modin-project/modin#2546]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Modin version** (`modin.__version__`): 0.8.2
- **Python version**:  Python 3.7.4
```
import re
import time

def lexigraphql_regex_analyzer(*args, **kwargs):
    """
    regex="^[_a-zA-Z][_a-zA-Z0-9]*$"
    string=""
    """
    regex = kwargs.get('regex', None)
    string = kwargs.get('string', None)
    return ''.join([str(char) for char in list(string) if re.match(regex, str(char))])

def sanitize_data(value):
    return value.strip()

if __name__ == "__main__":

    ### Read in the data with Pandas
    import pandas as pd

    s = time.time()

    df = pd.read_csv(
        '{}'.format('./data/CHANDRA.2.0.source.tsv'),
        sep=";|,",
        skipinitialspace=True,
        engine='python',
        comment='#'
    )

    df = df.applymap(lambda x: sanitize_data(x) if isinstance(x, str) else x)

    df.columns = [lexigraphql_regex_analyzer(regex="^[_a-zA-Z][_a-zA-Z0-9]*$", string=column) for column in df.columns]

    print(df.dtypes)

    e = time.time()
    print("Pandas Loading Time = {}".format(e-s))

    ### Read in the data with Modin
    import modin.pandas as pd

    s = time.time()

    df = pd.read_csv(
        '{}'.format('./data/CHANDRA.2.0.source.tsv'),
        sep=";|,",
        skipinitialspace=True,
        engine='python',
        comment='#'
    )

    df = df.applymap(lambda x: sanitize_data(x) if isinstance(x, str) else x)

    df.columns = [lexigraphql_regex_analyzer(regex="^[_a-zA-Z][_a-zA-Z0-9]*$", string=column) for column in df.columns]

    print(df.dtypes)

    e = time.time()
    print("Modin Loading Time = {}".format(e-s))
```

When attempting to use `applymap()` I receive a "function provided is not verified" error. Running the same code in pandas does not give this error.

The tsv for the code snippet can be downloaded from here: [https://nyc3.digitaloceanspaces.com/asencis/datasets/records/files/CHANDRA.2.0.source.tsv](https://nyc3.digitaloceanspaces.com/asencis/datasets/records/files/CHANDRA.2.0.source.tsv)

```
_RAJ    float64
_DEJ    float64
CXO      object
RAJ     float64
DEJ     float64
ePos    float64
SN      float64
Fb       object
b_Fb     object
B_Fb     object
Fw       object
hr       object
hr       object
fc        int64
fe        int64
fs        int64
Vab      object
Vib      object
Vaw      object
Viw     float64
dtype: object
Pandas Loading Time = 2.54580020904541
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
_RAJ    object
_DEJ    object
CXO     object
RAJ     object
DEJ     object
ePos    object
SN      object
Fb      object
b_Fb    object
B_Fb    object
Fw      object
hr      object
hr      object
fc      object
fe      object
fs      object
Vab     object
Vib     object
Vaw     object
Viw     object
dtype: object
Modin Loading Time = 1.1737842559814453
```

**Comment by devin-petersohn** [comment]
Hi @asencis thanks for posting.

The warning message is not indented to be interpreted as an error. It is informing you that we don't have the same checks on the function.

**Comment by asencis** [comment]
@devin-petersohn Hi Devin - I'm not sure what you mean by the same checks. Is the function supported or unsupported? It doesn't seem to perform the same output as pandas - so to me, this seems like it's an unsupported feature?

**Comment by devin-petersohn** [comment]
It is supported.

I see from your example that the dtypes are different. I was not able to reproduce the difference locally with your code + data. I could not get pandas to do any implicit type casting after `applymap` in any case I tried locally, but of course this does not mean it does not happen. Pandas has many undocumented cases of different behaviors, especially with types.

It might be a platform/OS issue as well. I will have this attempted on a mac as well to be sure.

**Comment by williamma12** [comment]
Hi @asencis,

I was both able and unable to replicate your issue. The result from modin was indeed all objects but I got the same result from pandas. I believe that this is the intended behavior because the first two rows is always a string type, which would force each of the columns to be an object type. After commenting out the first two rows (lines 71 and 72 in the file you linked), I was able to get the intended dtypes that you got as your pandas.

Can you double check the data file or paste the first few rows of the csv (excluding comments) here? I'd be happy to look into the issue more!
