### ISSUE TITLE
Unable to import Modin

### ISSUE THREAD

**Issue by sahil0094** [modin-project/modin#2583]
ImportError: cannot import name 'IndexKeyFunc'

**Comment by devin-petersohn** [comment]
Hi @sahil0094 what version of pandas are you running? Is it possible to share more of the error?

**Comment by sahil0094** [comment]
i just imported modin.pandas as pd and got this error. pandas version is 1.0.1

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-222-6849e756e216> in <module>
      1 os.environ["MODIN_ENGINE"] = "dask"  # Modin will use Dask
      2 
----> 3 import modin.pandas as pd

~/anaconda3/envs/python3/lib/python3.6/site-packages/modin/pandas/__init__.py in <module>
    179 
    180 from .. import __version__
--> 181 from .dataframe import DataFrame
    182 from .io import (
    183     read_csv,

~/anaconda3/envs/python3/lib/python3.6/site-packages/modin/pandas/dataframe.py in <module>
     52 )
     53 from .iterator import PartitionIterator
---> 54 from .series import Series
     55 from .base import BasePandasDataset, _ATTRS_NO_LOOKUP
     56 from .groupby import DataFrameGroupBy

~/anaconda3/envs/python3/lib/python3.6/site-packages/modin/pandas/series.py in <module>
     32 )
     33 from pandas._libs.lib import no_default
---> 34 from pandas._typing import IndexKeyFunc
     35 import sys
     36 from typing import Union, Optional

ImportError: cannot import name 'IndexKeyFunc'

**Comment by devin-petersohn** [comment]
Your pandas version is likely not compatible with Modin, are you able to run `pip install -U modin`? It will update your local pandas version to what is compatible with Modin (pandas 1.1).

**Comment by sahil0094** [comment]
I am able to run pip install -U modin but after that also i face same error. By the way, I am using aws sagemaker

**Comment by devin-petersohn** [comment]
I see, let's try to update the panda version individually:

```
pip install -U pandas==1.1.5
```

There is normally a warning that pops up when the pandas version is not the same as the one that Modin expects. Did you see that warning as well?

**Comment by sahil0094** [comment]
@devin-petersohn  same error after pip install -U pandas==1.1.5

**Comment by devin-petersohn** [comment]
This must be a python environment issue. I would restart the notebook and make sure you python path is the same for pip python ipython jupyter and conda.

**Comment by sahil0094** [comment]
Thanks! I am able to resolve the issue by restarting the notebook

**Comment by devin-petersohn** [comment]
Great! Closing as resolved.
