### ISSUE TITLE
Change prefect to use Ray exectuor, it will be awesome.

### ISSUE THREAD

**Issue by ggservice007** [modin-project/modin#2590]
Modin is awesome. It supports both Dask and Ray.

I want to change another project Prefect to supports both Dask and Ray. 

Any ideas?

## Prefect
The easiest way to automate your data.

Prefect is the new standard in dataflow automation, trusted to build, run, and monitor millions of data workflows and pipelines. 

Prefect workflows are designed to be run at any time, for any reason, with any concurrency. Running a workflow on a schedule is a special case.

![Snip20210111_9](https://user-images.githubusercontent.com/9192908/104143968-7e413a00-53fc-11eb-99cc-e82d3fee4ed2.png)

https://www.prefect.io/

https://github.com/PrefectHQ/prefect

## But Prefect is based on Dask executors

Change Dask to Ray executor, any idea?

https://github.com/PrefectHQ/prefect/issues/3929

https://github.com/ray-project/ray/issues/13327

**Comment by devin-petersohn** [comment]
@ggservice007 thanks for the question. Modin can use either Dask or Ray, so I don't think there's any engineering we can do in Modin to enable prefect, it should just work.

Did you have something specific in mind?

**Comment by ggservice007** [comment]
I do not want to modify the Modin to enable Prefect.  I want to change Prefect to support Ray. 

You have make the Modin to support both the Dask and Ray at the same time. 

@devin-petersohn Can you give me some experience or lesson about using Dask or Ray to do same thing? Or provide some documents about the difference between Dask and Ray deeply?

**Comment by devin-petersohn** [comment]
At a high level, Ray and Dask basically do the same thing, with different sets of features within the broad set of task-parallel schedulers. For some tasks, Ray is faster than Dask, and vice-versa.

In Modin, we created an execution abstraction that allows us to deploy the same Python code to different execution engines. It is possible to extend the internal abstractions for external use and this is something we plan to do eventually. 

Prefect is maintained by Dask developers, so even if someone writes the Ray engine I do not know if they would accept it. They would need to maintain it themselves and as Dask users, they aren't familiar with Ray.

**Comment by ggservice007** [comment]
Base exectuor:

src/prefect/executors/base.py

```python
from contextlib import contextmanager
from typing import Any, Callable, Iterator

from prefect.utilities.logging import get_logger


class Executor:
    """
    Base Executor class that all other executors inherit from.
    """

    def __init__(self) -> None:
        self.logger = get_logger(type(self).__name__)

    def __repr__(self) -> str:
        return "<Executor: {}>".format(type(self).__name__)

    @contextmanager
    def start(self) -> Iterator[None]:
        """
        Context manager for initializing execution.

        Any initialization this executor needs to perform should be done in this
        context manager, and torn down after yielding.
        """
        yield

    def submit(
        self, fn: Callable, *args: Any, extra_context: dict = None, **kwargs: Any
    ) -> Any:
        """
        Submit a function to the executor for execution. Returns a future-like object.

        Args:
            - fn (Callable): function that is being submitted for execution
            - *args (Any): arguments to be passed to `fn`
            - extra_context (dict, optional): an optional dictionary with extra information
                about the submitted task
            - **kwargs (Any): keyword arguments to be passed to `fn`

        Returns:
            - Any: a future-like object
        """
        raise NotImplementedError()

    def wait(self, futures: Any) -> Any:
        """
        Resolves futures to their values. Blocks until the future is complete.

        Args:
            - futures (Any): iterable of futures to compute

        Returns:
            - Any: an iterable of resolved futures
        """
        raise NotImplementedError()

```

**Comment by ggservice007** [comment]
## src/prefect/executors/ray.py

```python
import asyncio
import logging
import uuid
import sys
import weakref
from contextlib import contextmanager
from typing import Any, Callable, Iterator, TYPE_CHECKING, Union, Optional

from prefect import context
from prefect.executors.base import Executor
from prefect.utilities.importtools import import_object


class RayExecutor(Executor):
    def __init__(
        self):
      pass

    @contextmanager
    def start(self) -> Iterator[None]:
        pass


    def wait(self, futures: Any) -> Any:
        pass

```

**Comment by devin-petersohn** [comment]
Closing because no action items on our end.
