### ISSUE TITLE
Get omniscidb compilation phase out of critical path

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#2621]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin installed from (source or binary)**: all
- **Modin version**: future
- **Python version**: all supported
- **Exact command to reproduce**:

### Describe the problem

This is NYCTaxi Q4 repeated 10 times:
![image.png](https://images.zenhubusercontent.com/5ec63e2c3585b7e8ae82fc4f/0be5ebad-7cd3-485a-88b8-3b06a4516d96)
i.e. query compilation is serial and is on critical path. There should be one or another way to hide or eliminate it:
* introduce explicit query compilation API (with parametrization) so Modin could control when and what to compile, executing only previously compiled queries
* implement pipeline using TBB FlowGraph
* or/and implement better caching on the omnisci side only

**Comment by pyrito** [comment]
What is the status of this now?
