### ISSUE TITLE
Implement skiprows parameter for read_csv with OmniSci backend

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2628]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?
According to pyarrow documentation `pyarrow.read_csv` supports skip_rows parameter for `int` values (https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions), it can be used for implementation of skiprows parameter of `modin.read_csv` with OmniSci backend.

**Comment by anmyachev** [comment]
This feature has already been implemented.

There is a condition for defaulting to pandas: https://github.com/modin-project/modin/blob/e00b5169f9127b7823982d6b06c57829c9e7e40d/modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py#L541
