### ISSUE TITLE
Compare conda vs mamba

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#2636]
Explore time and error message quality for mamba vs conda install on the usual suspects:
- AI Kit
- Modin
- torch stack
- pandas, scikit-learn, xgboost, catboost, etc.

**Comment by pyrito** [comment]
Is this referring to using conda vs mamba in CI?

**Comment by Garra1980** [comment]
not only

**Comment by Garra1980** [comment]
I think we can close this
