### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2637]
Since we already have people using Python 3.9, we should change this.
```
modin\pandas\iterator.py:16
```

**Comment by tirkarthi** [comment]
I have created https://github.com/modin-project/modin/pull/2641 to fix this. I have also fixed some deprecation warnings.

**Comment by tirkarthi** [comment]
The change was delayed to Python 3.10 which will raise `ImportError` for importing ABC directly from collections.
