### ISSUE TITLE
Redesign Modin to align with DataFrame Algebra

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#2656]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

Redesign Modin's architecture to implement the DataFrame Algebra proposed in the vision paper found [here](https://people.eecs.berkeley.edu/~totemtang/paper/Modin.pdf). Predecessor to #2204

**Comment by RehanSD** [comment]
@devin-petersohn

**Comment by YarShev** [comment]
@RehanSD, please update the link to a newer paper in the issue description. I suppose this one should be https://people.eecs.berkeley.edu/~totemtang/paper/Modin.pdf.

**Comment by RehanSD** [comment]
We have resolved the code portion of this refactor - we also need to update the documentation to reflect the new language.
