### ISSUE TITLE
Arrow data extent memory exeeded when using modin

### ISSUE THREAD

**Issue by ivalmian** [modin-project/modin#266]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7.5
- **Modin installed from (source or binary)**: Binary with pip
- **Modin version**: 0.2.4
- **Python version**: 3.6
- **Exact command to reproduce**: df=pd.concat([df_spe,df_enc]).sort_values('PAT_ID').reset_index(drop=True)

### Describe the problem

Hi, 

I'm pretty new to modin, trying to transition from pandas. My usecases are large in-memory dataframes (100-200GB). I am able to load and do certain manipulations, however, when I tried to do a sort follow by drop index I received a memory exceeded error. System memory is not the limiting factor (503 GB available).

Ilya

### Source code / logs

---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-9-fcc075b248bd> in <module>()
----> 1 df=pd.concat([df_spe,df_enc]).sort_values('PAT_ID').reset_index(drop=True)

/apps/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py in sort_values(self, by, axis, ascending, inplace, kind, na_position)
   3760                 na_position=na_position,
   3761             ).index
-> 3762             return self.reindex(index=new_index, copy=not inplace)
   3763         else:
   3764             broadcast_value_list = [

/apps/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py in reindex(self, labels, index, columns, axis, method, copy, level, fill_value, limit, tolerance)
   2990                 fill_value=fill_value,
   2991                 limit=limit,
-> 2992                 tolerance=tolerance,
   2993             )
   2994         else:

/apps/anaconda3/lib/python3.6/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py in reindex(self, axis, labels, **kwargs)
    825         # assumes identical partitioning. Internally, we *may* change the
    826         # partitioning during a map across a full axis.
--> 827         new_data = self.map_across_full_axis(axis, func)
    828         return self.__constructor__(new_data, new_index, new_columns)
    829 

/apps/anaconda3/lib/python3.6/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py in map_across_full_axis(self, axis, func)
   1575     # data in the same place.
   1576     def map_across_full_axis(self, axis, func):
-> 1577         return self.data.map_across_full_axis(axis, func)
   1578 
   1579     def _cumulative_builder(self, func, **kwargs):

/apps/anaconda3/lib/python3.6/site-packages/modin/data_management/partitioning/partition_collections/base_block_partitions.py in map_across_full_axis(self, axis, map_func)
    268         # partitions as best we can right now.
    269         num_splits = cls._compute_num_partitions()
--> 270         preprocessed_map_func = self.preprocess_func(map_func)
    271         partitions = self.column_partitions if not axis else self.row_partitions
    272         result_blocks = np.array(

/apps/anaconda3/lib/python3.6/site-packages/modin/data_management/partitioning/partition_collections/base_block_partitions.py in preprocess_func(self, map_func)
     89             being used).
     90         """
---> 91         return self._partition_class.preprocess_func(map_func)
     92 
     93     # END Abstract Methods

/apps/anaconda3/lib/python3.6/site-packages/modin/data_management/partitioning/remote_partition/pandas_on_ray.py in preprocess_func(cls, func)
    103             A ray.ObjectID.
    104         """
--> 105         return ray.put(func)
    106 
    107     @classmethod

/apps/anaconda3/lib/python3.6/site-packages/ray/worker.py in put(value, worker)
   2540         object_id = worker.local_scheduler_client.compute_put_id(
   2541             worker.current_task_id, worker.put_index, worker.use_raylet)
-> 2542         worker.put_object(object_id, value)
   2543         worker.put_index += 1
   2544         return object_id

/apps/anaconda3/lib/python3.6/site-packages/ray/worker.py in put_object(self, object_id, value)
    404         # Serialize and put the object in the object store.
    405         try:
--> 406             self.store_and_register(object_id, value)
    407         except pyarrow.PlasmaObjectExists:
    408             # The object already exists in the object store, so there is no

/apps/anaconda3/lib/python3.6/site-packages/ray/worker.py in store_and_register(self, object_id, value, depth)
    339                     memcopy_threads=self.memcopy_threads,
    340                     serialization_context=self.get_serialization_context(
--> 341                         self.task_driver_id))
    342                 break
    343             except pyarrow.SerializationCallbackError as e:

/apps/anaconda3/lib/python3.6/site-packages/ray/utils.py in _wrapper(*args, **kwargs)
    385                 def _wrapper(*args, **kwargs):
    386                     with self.lock:
--> 387                         return orig_attr(*args, **kwargs)
    388 
    389                 self._wrapper_cache[attr] = _wrapper

/apps/anaconda3/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient.put()

/apps/anaconda3/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.serialize()

/apps/anaconda3/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: Maximum size exceeded (2GB)

**Comment by devin-petersohn** [comment]
I just remembered that we can also use Plasma hugepages. This should probably be on by default. Here is how you can do it on the most recent release:

```python
import ray
ray.init(huge_pages=True)
import modin.pandas as pd
```

I will create a PR to enable this by default. Thanks again for pointing this out!

**Comment by pcmoritz** [comment]
I just looked into it, it looks like the problem here is that there are some 32 bit integers are used here:

https://github.com/apache/arrow/blob/7ee27ac98cfb1aa8031729d823732968b2289f5a/cpp/src/arrow/python/serialize.cc#L525

Are there any bytes in your data structure @ivalmian?

I can submit a patch for that later today (huge pages won't help here unfortunately).

**Comment by pcmoritz** [comment]
Thanks! Is it possible to send me a pickled version of the data that causes the problem (potentially by anonymizing it and only keeping the datatypes the same).

**Comment by pcmoritz** [comment]
I created a JIRA issue here: https://issues.apache.org/jira/browse/ARROW-3919

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
