### ISSUE TITLE
Conversion from Modin dataframe to spark dataframe

### ISSUE THREAD

**Issue by Bhavsik** [modin-project/modin#2669]
Is there any way by which we can convert Modin Data frame into spark data frame? 
And one more question.
finaldf["Alarm"] = pd.Series(AlarmList)
ValueError: Length of values (62) does not match length of index (74)
Is there any work around of this in Modin.
Because in pandas this empty rows will be filled with Nan.

**Comment by devin-petersohn** [comment]
Hi @Bhavsik, thanks for the question!

Currently, the only way from Modin to Spark would be through files, parquet should be fine. Does your workflow require Spark for some follow on steps?

Your second question looks like a bug. Would you open a new issue so we can track that separately from this question? That would help a lot!

**Comment by Bhavsik** [comment]
Hi @devin-petersohn, our work flow require Spark for further calculations. 
So, we need to change from Modin to Spark. Does we can go with Modin to Pandas ?
I have tried with Datafarame.topandas() but it's not working.
And I will create new issue for second question.

**Comment by devin-petersohn** [comment]
There is an API for going to pandas, `df._to_pandas()`. It's an internal API, but you can use it for your purposes.. Let me know if that helps!

**Comment by pyrito** [comment]
@Bhavsik did Devin's suggestion help? I'm going to go ahead and close this issue.
