### ISSUE TITLE
.apply() do not apply the function it receives as an argument properly.  

### ISSUE THREAD

**Issue by galrapo** [modin-project/modin#267]
Python v3.6 on Jupyter notebook

When using df.apply() a warning appears and informs that validation isn't available in this version yet.
Also, when checking the dataframe after .apply() nothing has changed.
When comparing with Pandas .apply(), it makes the job done, means there's no problem with the function given as an argument to apply().

**Comment by devin-petersohn** [comment]
Hi @galrapo, thanks for posting this!

Do you mind showing the function your using in the `apply`? There may be something that Modin is not properly handling with respect to your particular function (and others like it perhaps).

The warning you are seeing is there to let you know that we don't check the function given to `apply` for validation purposes. It should match the pandas output, however. If you can provide the function, it will be much easier to resolve this issue.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
