### ISSUE TITLE
Modin Series not working properly

### ISSUE THREAD

**Issue by Bhavsik** [modin-project/modin#2678]
finaldf["Alarm"] = pd.Series(AlarmList)
ValueError: Length of values (62) does not match length of index (74)
Is there any work around of this in Modin because in pandas this empty rows will be filled with Nan.

**Comment by devin-petersohn** [comment]
Hi @Bhavsik, thanks for the report!

Is it possible to share a way to reproduce this error? For example, when I try:

```python
df = pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))).add_prefix("col")
df["a"] = df["col0"][-100:]
```

This has missing values for over 1 million rows and still works for me. Is it possible to share more of the code?

**Comment by Bhavsik** [comment]
upperalarm = [17028.625876324455, 19167.291371843567, 21432.522763867324, 23797.79165904118, 26218.150061244414, 28615.490124066953, 30844.295869561138, 31168.349374190628, 32809.988285626074, 34838.1561670214, 40865.63408258141, 39853.51674524953, 36310.856434239024, 34908.38223892729, 35475.18853322556, 32961.14469391921, 34166.306890944805, 34336.421926745614, 35380.681628812774, 36598.5414446568, 37722.22169616411, 38939.84535802893, 41008.64459523856, 42455.429082310875, 42623.949642674925, 45645.97121012906, 48177.01457803082, 48444.157384851984, 51083.66541257374, 50117.71313178161, 52725.10220780819, 55012.646834616986, 61218.726498148615, 64095.96542871834, 60740.73394022115, 62950.53597619867, 62278.18163057967, 67474.54735349846, 70519.07327641455, 73742.34832592362, 81279.85706694631, 97305.2993209677, 109201.3034774798, 168585.11929178395, 238268.67911533982, 676839.3592418204, 689259.7573286432, 702764.5543435472, 716437.187300981, 730147.1925771942, 742517.7133124131, 752116.3821007923, 760732.5386691744, 756429.213984703, 737376.2843653494, 623101.4282361465, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
modeldf["upperalarm"]  = pd.Series(upperalarm)

As you can see over here i have data frame modeldf in which i am adding upperalarm as column. While adding this i am getting below error.
ValueError: Length of values (66) does not match length of index (77).

modeldf have 77 rows and 9 columns of different type. List have 66 rows of float type.

**Comment by devin-petersohn** [comment]
@Bhavsik Is this a new column in the dataframe? Does `"upperalarm"` already exist in the dataframe before the statement? Creating test data has not reproduced the error for me.

**Comment by Bhavsik** [comment]
@devin-petersohn Yes it's a new column in the dataframe. We are creating this using list "upperalarm".

**Comment by devin-petersohn** [comment]
@Bhavsik if possible can you send your script and data to bug_reports@modin.org? My attempts at reproducing this issue have been unsuccessful.

**Comment by pyrito** [comment]
@Bhavsik do you have a reproducer you could give us here? I'm not able to replicate the issue. Please go ahead and reopen this if you're still having this issue.
