### ISSUE TITLE
Construct modin DataFrame from list of remote Ray objects?

### ISSUE THREAD

**Issue by Hoeze** [modin-project/modin#2704]
Hi, is it possible to create a list of remote Ray Pandas Dataframes and concatenate those to a single modin dataframe without copying them?

**Comment by YarShev** [comment]
Hi @Hoeze , thanks for posting! Yes, you can create a list of remote Ray pandas DataFrames and construct Modin DataFrame from them, for example, as follows:
```python
import ray
ray.init()

import pandas

df1 = pandas.DataFrame([1,2,3])
df2 = pandas.DataFrame([1,2,3])
df3 = pandas.DataFrame([1,2,3])
df4 = pandas.DataFrame([1,2,3])

oid1 = ray.put(df1)
oid2 = ray.put(df2)
oid3 = ray.put(df3)
oid4 = ray.put(df4)

dfs_list = [[oid1, oid2, oid3, oid4]] # You can place `df1`, `df2`, `df3`, `df4` with any way in the list `dfs_list`
dfs_list
[[ObjectRef(ffffffffffffffffffffffff0100000001000000),
  ObjectRef(ffffffffffffffffffffffff0100000002000000),
  ObjectRef(ffffffffffffffffffffffff0100000003000000),
  ObjectRef(ffffffffffffffffffffffff0100000004000000)]]

from modin.distributed.dataframe.pandas import from_partitions, unwrap_partitions
df = from_partitions(dfs_list, axis=None)
df
   0  0  0  0
0  1  1  1  1
1  2  2  2  2
2  3  3  3  3
# Also, you can get the partitions back
parts = unwrap_partitions(df, axis=None)
parts
[[ObjectRef(ffffffffffffffffffffffff0100000001000000),
  ObjectRef(ffffffffffffffffffffffff0100000002000000),
  ObjectRef(ffffffffffffffffffffffff0100000003000000),
  ObjectRef(ffffffffffffffffffffffff0100000004000000)]]
```
As you can see `dfs_list` and `parts` are identical. Please, refer to the docstrings of `from_partitions` ([1](https://github.com/modin-project/modin/blob/master/modin/distributed/dataframe/pandas/partitions.py#L88)) and `unwrap_partitions` ([2](https://github.com/modin-project/modin/blob/master/modin/distributed/dataframe/pandas/partitions.py#L22)) for more info. We are currently adding a documentation page for these features.

**Comment by Hoeze** [comment]
Thanks a lot @YarShev :+1:
