### ISSUE TITLE
Support for ray.util.iter.ParallelIterator

### ISSUE THREAD

**Issue by fschlimb** [modin-project/modin#2714]
To use RaySGD with modin DFs it would be nice to have simple and efficient path to creating MLDataSet from a modin DF.
The MLDataSet can be constructed from a ray.util.iter.ParallelIterator. Such a ParallelIterator can be constructed from actors.
An implementation could assign one actor per modin shard, which would allow MLDataSet to operate locally not and copy data (if distributed). In theory, it should even be possible to use the same ObjRefs.

Since this is Ray-specific, such a feature should probably live in a lower level of the API that clearly exposes that it's specific to Ray.

@YarShev

**Comment by devin-petersohn** [comment]
I don't think functionality like this would belong in Modin. Modin is runtime agnostic, so it doesn't make sense to have these narrowly focused utilities here.

How were you imagining this working? I imagine that we could add something to Ray that creates an MLDataSet from Modin. To me that makes more sense.

**Comment by fschlimb** [comment]
Yes, there is benefits to either way, in modin or ray. I already heard similar arguments from the ray side just inversed.

I don't see any problem with having something like modin.modin_on_ray.get_parallelIterator(df). I think it's important to think about how modin wants to collaborate/compose with the rest of the world. Just converting to pandas and take it from there is not a scalable approach.

Yes, such functionality is runtime specific, but is is good style and useful to provide the opportunity to benefit from sharing runtime features. A parallel iterator is not a narrow feature to me.

**Comment by devin-petersohn** [comment]
We are building high level APIs for getting runtime agnostic partitions to handle externally. I am not suggesting that everything should go through pandas, I think you misunderstand.

I can see how `modin.modin_on_ray.get_parallelIterator(df)` might lead to severe API bloat as the number of integrations grows. I imagine the solution as being more along the lines of how libraries typically handle integrations, where if we want to collaborate/integrate and convert to something else, it goes on the consumer side. There might be exceptions, but for something general like this, it is more natural in Ray.

**Comment by devin-petersohn** [comment]
@fschlimb I opened an issue on the Ray side and they are enthusiastic to have it added there: https://github.com/ray-project/ray/issues/14039.

Please feel free to add it there! We have some examples for how to create actors from Modin partitions in the XGBoost implementation, it might be good to take a look there as well.

**Comment by fschlimb** [comment]
Great, thanks @devin-petersohn !
