### ISSUE TITLE
Modin core utilisation: Calls to DataFrame.loc uses single core only

### ISSUE THREAD

**Issue by JCurtisRMIT** [modin-project/modin#2746]
Just started using modin today - seems great

however whenever I'm making calls to `DataFrame.loc` i revert back to a single core. It actually seems even slower than pandas if that's actually possible.

How can I use all of my cores here? I'm using Ray for the engine on Ubuntu

**Comment by JCurtisRMIT** [comment]
Okay seemed to figure out the issue here! the version of `pandas` that pip is using with `Modin[all]` returns an error on any call to `loc` using this syntax:

```python
df.loc[df['col_name'].str.contains('thestringyouarelookingfor')]
```

traceback links this url: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike


Filling that column's `NaN`s with an empty string allows the same call to work with `modin` on all cores again and barely breaking a sweat on any of them.

![Screenshot from 2021-02-17 17-06-42](https://user-images.githubusercontent.com/25715542/108163269-d1688400-7142-11eb-8feb-24ba5f732a08.png)

```python
df['col_name'] = df['col_name'].fillna('')
df.loc[df['col_name'].str.contains('thestringyouarelookingfor')]
```

modin (or ray) was just spinning one core at full throttle for about 20 mins and not reporting any of this - so may be worth investigating

**Comment by devin-petersohn** [comment]
Thanks for the detailed issue @JCurtisRMIT. I'm going to reopen this so we can look into it.

Sometimes errors cannot be determined statically before execution (e.g., we may not know if a column contains `NaN`s without looking at the data first).

**Comment by mvashishtha** [comment]
@pyrito I don't know how to reproduce the bug. `Series.str.contains` does seem to work with null values, e.g.

```python
import modin.pandas as pd

s = pd.Series(['a', 'b', None, ''])
print(s.str.contains('a'))
print(s.loc[s.str.contains('a')])
```

I get the correct `contains` result and the error is the same as in pandas.

@JCurtisRMIT if you can provide a reproducer at the latest modin version, please comment here. For now I'll close this as resolved.
