### ISSUE TITLE
CSV IO part refactoring

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2748]
Currently CSV IO part [`_read`](https://github.com/modin-project/modin/blob/master/modin/engines/base/io/text/csv_dispatcher.py#L26) function is quite big function, that making it difficult to understand it logic, so this function can be spitted into functions to fix it.

**Comment by williamma12** [comment]
I was thinking about this issue as well as I was adding the glob file
reading for csvs, I temporarily copied the csv _read function and only made
minor changes.

There is also a lot of overlap between json and fwf _read and csv read.

**Comment by amyskov** [comment]
PR with refactoring of CSV IO part is under review now.
