### ISSUE TITLE
pd.set_option Jupyter Notebook settings when using Modin

### ISSUE THREAD

**Issue by JCurtisRMIT** [modin-project/modin#2752]
Hi folks,

Are these methods supported in `modin`?

```python
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)
```

**Comment by devin-petersohn** [comment]
Hi @JCurtisRMIT, they should be supported. If it is a large dataframe, printing all of the columns and rows will be very expensive if you do it often. We are working on a more convenient way to view the entire dataframe without having to print everything to the notebook or console through a spreadsheet-like interface to solve this problem.

**Comment by pyrito** [comment]
Closing this issue since the `pd.set_option` still seems to be a problem and we have a duplicate here: https://github.com/modin-project/modin/issues/4640
