### ISSUE TITLE
Implement Progress Bar for more complex queries (i.e. groupby)

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#2775]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

We have currently implemented a progress bar for queries in PR #2677; however, this does not add progress bars for queries like groupbys. We need to add the ability to view progress bars for queries with groupby's etc.s

Example query:
```python
df.groupby(by=lambda x: x < np.random.randint(0,4)).mean()
```

Continuation of the work in #629.

**Comment by devin-petersohn** [comment]
@RehanSD I think your query is defaulting to pandas. Is it supposed to?

**Comment by RehanSD** [comment]
I initially didn't think that that was happening, so I did some digging around and checked out the codepath. It looks like you may be right about calling .mean() on the DataFrameGroupBy object defaults to pandas' implementation. I wonder if the bigger issue is writing our own implementations for things like mean, or at least wrapping the area that calls the default implementation in progress bar wrappers?

**Comment by RehanSD** [comment]
I was able to get a progress bar to show up for the query by copying the progress bar wrapper Noah wrote, wrapping groupby_agg in the query compiler, and changing one part in the code where it loops through the results to loop through the results._modin_frame._partitions (otherwise it errors since Noah wrote it to loop through results which would have been a numpy array originally).

**Comment by devin-petersohn** [comment]
>It looks like you may be right about calling .mean() on the DataFrameGroupBy object defaults to pandas' implementation.

It is the `by=some_function` that defaults to pandas right now.

There's a `groupby_agg` in the modin frame and frame manager which should already be showing the progress bar. Try:

```python
df.groupby(by="col1").sum()  # mean(), count(), apply(lambda x: x.head(1))
```

They seem to be working for me.

**Comment by RehanSD** [comment]
I see - I think that we should still show a progress bar even if we default to pandas - which we can make happen by adding the progress bar wrappers to the query compiler as well.

**Comment by RehanSD** [comment]
When I try your example, the ipython kernel crashes - both on Jupyter notebook and from iPython:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/17012605/110052746-ed585200-7d0c-11eb-988c-96772e037bed.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/17012605/110052781-fa754100-7d0c-11eb-9628-a66f64c01ce0.png">
I did a fresh reinstall of Modin from pip to make sure it wasn't an issue with my install, and it still crashes.

**Comment by devin-petersohn** [comment]
@RehanSD do you still have this issue?

**Comment by RehanSD** [comment]
No - it turned out to be an issue with my ray version.

**Comment by pyrito** [comment]
@RehanSD I'm going to go ahead and close this if you're no longer dealing with this issue.
