### ISSUE TITLE
Reading parquet files which are not created with pandas fails.

### ISSUE THREAD

**Issue by rolveb** [modin-project/modin#2789]
### System information
Modin 0.8.1
Linux

### Describe the problem
Cannot dispatch parquet files with meta information described with b'ARROW:schema' since modin solution is hardcoded to key 
meta.metadata[b"pandas"]. Point of origin in code listed below. Regular pandas works for the expression.

### Source code / logs
Parquet file was created with $ xeus convert (4.0 alpha) and not saved from pandas initially

[In 1]: import modin.pandas as pandas
[In 2]: pandas.read_parquet('somefile.parquet').set_index('times').between_time(start_time='23:50',
    ...: end_time='00:00', include_start=False, include_end=True).groupby(['station', 'lev'])['count'].describe(perce
    ...: ntiles=[0.001, 0.01, 0.05,0.1])

In [3]: %debug
> /home/xxx/micromamba/lib/python3.8/site-packages/modin/engines/base/io/column_stores/parquet_dispatcher.py(119)_read()
    117                 # computation.
    118                 index_columns = eval(
--> 119                     meta.metadata[b"pandas"].replace(b"null", b"None")
    120                 ).get("index_columns", [])
    121                 column_names = [c for c in column_names if c not in index_columns]

ipdb> meta.metadata.keys()
dict_keys([b'ARROW:schema'])
ipdb>

**Comment by devin-petersohn** [comment]
@rolveb Thanks for the report, we have a fix in progress here: #2774. It will be included in the next release.

**Comment by devin-petersohn** [comment]
Closed by #2774
