### ISSUE TITLE
Add Spreadsheet API

### ISSUE THREAD

**Issue by richardlin047** [modin-project/modin#2796]
Add the `modin.spreadsheet` API by integrating `modin-spreadsheet`.

Plan to expose 2 API:
`from_dataframe`: Creates spreadsheet from dataframe
`to_dataframe`:  Exports dataframe from spreadsheet

Conventional usage could look like:
`import modin.spreadsheet as mss`

**Comment by rootsmusic** [comment]
@richardlin047 See #6416 about modin.spreadsheet.
