### ISSUE TITLE
a little much WARNING with ray0.6.0 

### ISSUE THREAD

**Issue by appvin** [modin-project/modin#282]
for example, the WARNING after import:

> WARNING: The use_raylet argument has been deprecated. Please remove it.

and after the read_csv function:

> WARNING: _submit() is being deprecated. Please use _remote().
WARNING: _submit() is being deprecated. Please use _remote().
......

But the ray only support python 3.7 in the version 0.6.0, so, is there an upgrade plan here?

**Comment by devin-petersohn** [comment]
Hi @appvin, yes we are planning a release for later today. Ray made some API changes, and we need to make modifications for those (they released 0.6 yesterday).

I will get this fixed today.

**Comment by devin-petersohn** [comment]
Modin 0.2.5 has been released. https://pypi.org/project/modin/0.2.5/

`pip install -U modin`
