### ISSUE TITLE
Querying empty dataframes throws exceptions

### ISSUE THREAD

**Issue by btseytlin** [modin-project/modin#2839]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): 0.9.0
- **Python version**: 3.8.5
- **Code we can use to reproduce**:

```
import modin.pandas as pd
df = pd.DataFrame(columns=['a', 'b'])
df[(df.a == 1) & (df.b == 2)]
```
Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...python3.8/site-packages/modin/pandas/series.py", line 147, in __and__
    new_self, new_other = self._prepare_inter_op(other)
  File "...python3.8/site-packages/modin/pandas/base.py", line 2830, in default_handler
    return self._default_to_pandas(item, *args, **kwargs)
  File "...python3.8/site-packages/modin/pandas/base.py", line 377, in _default_to_pandas
    result = getattr(getattr(pandas, type(self).__name__), op)(
AttributeError: type object 'Series' has no attribute '_prepare_inter_op'
```
### Describe the problem

This just returns an empty dataframe in vanilla pandas, but breaks down loudly in Modin.

**Comment by devin-petersohn** [comment]
Hi @btseytlin thanks for posting!

We need better handling of empty dataframes in Modin, agree. Usually it's supposed to fall back to the pandas behavior, thanks for reporting!
