### ISSUE TITLE
When will Out-of-Core and cluster support?

### ISSUE THREAD

**Issue by DonYum** [modin-project/modin#2852]
Out-of-Core and cluster is very important to big data processing. I really want to know when will modin support this features well(not toy)? 
Is there some plan?

Thanks a lot!

**Comment by devin-petersohn** [comment]
Hi @DonYum, you can track this PR: #2848. It will be available when Ray releases 1.3.0.

**Comment by pyrito** [comment]
Hi @DonYum , out-of-core and cluster support should be supported now. Please see the following links:
- https://modin.readthedocs.io/en/stable/getting_started/using_modin/using_modin_cluster.html
- https://modin.readthedocs.io/en/latest/getting_started/why_modin/out_of_core.html
