### ISSUE TITLE
Map Omnisci exceptions to Python exceptions in DBE

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#2861]
We should properly transit exceptions from C++ code to Python code

**Comment by igalink** [comment]
After examining the OmnisciDB and Modin exceptions, I came to the conclusion that there is no need to use custom exceptions. It is enough to use the basic ones, which automatically converted into an appropriate Python exceptions.
As part of this task, bugs related to exceptions were fixed and a test was added.
Created PR: https://github.com/intel-ai/omniscidb/pull/149

**Comment by igalink** [comment]
PR #149 merged it into modin branch.
Created PR to the Omnisci master: https://github.com/omnisci/omniscidb/pull/645.
