### ISSUE TITLE
BaseFrameManager.broadcast_apply has argument "other_name" but it is impossible to pass from query_compiler level

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2863]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.2 LTS

- **Modin version** (`modin.__version__`):

0.9.0+15.g371b1abe.dirty

- **Python version**:

Python 3.8.6

- **Code we can use to reproduce**:

### Describe the problem

There is a function `BaseFrameManager.broadcast_apply` https://github.com/modin-project/modin/blob/master/modin/engines/base/frame/partition_manager.py#L251 which has argument `other_name` which means name of second frame argument in the applied function. But when calling this function via `BasePandasFrame.broadcast_apply` it is impossible to specify this name because `BasePandasFrame.broadcast_apply` has no such argument and always calls `BaseFrameManager.broadcast_apply` implicitly without specifying `other_name` parameter https://github.com/modin-project/modin/blob/master/modin/engines/base/frame/data.py#L1509.
Because of this developer is forced to write apply function with implicit 2nd parameter name `r` which isn't very meaningful and isn't documented anywhere.

**Comment by pyrito** [comment]
@gshimansky can you update this issue with the latest code lines? I think things have changed.

**Comment by gshimansky** [comment]
I think the bug still applies although class names have changed.
Function `broadcast_apply` still exists and its `other_name` parameter implicit value is still `"r"` https://github.com/modin-project/modin/blob/master/modin/core/dataframe/pandas/partitioning/partition_manager.py#L338
It is still called without `other_name` parameter from `PandasDataframe.broadcast_apply` https://github.com/modin-project/modin/blob/master/modin/core/dataframe/pandas/dataframe/dataframe.py#L2148
