### ISSUE TITLE
GroupBy 'as_index=False' inserts by-column if aggregating on the by-column, when pandas does not

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2876]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Modin version** (`modin.__version__`): f123445d064cf685af98da640f8e75efcc05234f
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import os
os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd
import pandas

data = {"col1": [1, 1, 2, 2, 2], "col2": [1, 2, 3, 4, 5]}

pd_df = pandas.DataFrame(data)
md_df = pd.DataFrame(data)

print(f"pd_grp:\n{pd_df.groupby('col1', as_index=False).agg({'col1': 'sum'})}")
print(f"md_grp:\n{md_df.groupby('col1', as_index=False).agg({'col1': 'sum'})}")

```

Output:
```
pd_grp:
   col1
0     2
1     6

md_grp:
   by_col1  col1
0        1     2
1        2     6

```

### Describe the problem
When aggregating the same column that we're grouping on, pandas does not insert by-cols at the resulting frame (if `as_index=False`), when Modin with OmniSci backend do.

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
