### ISSUE TITLE
HDK backend preserves NaNs at the result of GroupBy aggregation when it shouldn't

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2878]
### System information
- **Modin version** (`modin.__version__`): 21707d2dd8c51404db692e27fb1a69203440d2eb
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd
import pandas

from modin.pandas.test.utils import df_equals

data = {
    "col1": [1, 2, 2, 2],
    "col2": [None, 1, 2, None],
}

pd_res = pandas.DataFrame(data).groupby("col1").sum()
md_res = pd.DataFrame(data).groupby("col1").sum()

df_equals(md_res, pd_res)  # AssertionError
```

Output:
```
AssertionError: DataFrame.iloc[:, 0] (column name="col2") are different

DataFrame.iloc[:, 0] (column name="col2") values are different (50.0 %)
[index]: [1, 2]
[left]:  [nan, 3.0]
[right]: [0.0, 3.0]
```

### Describe the problem
If group has the only one item to aggregate and it's `None`, then pandas replaces `None` to 0, OmniSci backend don't do that.

**Comment by anmyachev** [comment]
The error is reproduced on the [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
