### ISSUE TITLE
MultiIndex groupby with `level=` kwarg returns empty result

### ISSUE THREAD

**Issue by alex04103** [modin-project/modin#2891]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.1 LTS
- **Modin version** (`modin.__version__`): 0.9.1
- **Python version**: 3.8.8
- **Code we can use to reproduce**:

```bash
# Envrionment setup

docker run -e JUPYTER_ENABLE_LAB=yes -p 8888:8888 jupyter/minimal-notebook
docker exec -it $(docker ps --latest --quiet) bash
pip install modin[ray] s3fs
```

```python
# Code to be pasted into notebook

import pandas as pd
#import modin.pandas as pd

index = pd.MultiIndex.from_tuples([['one', 'two'], ['one', 'three'], ['two', 'one']], names=['X', 'Y'])
data = pd.DataFrame([[1, 2, 3], [3, 4, 5], [6, 7, 8]], index=index)
display(data)
pairs = data.groupby(level=['X', 'Y'])
display(list(pairs))
```

### Describe the problem
The code found above works as expected with pandas, but fails to work with modin.pandas.

The DataFrame `data` looks as follows:
```
                0     1     2
X       Y             
one     two     1     2     3
        three   3     4     5
two     one     6     7     8
```

Using pandas, the groupby result is intact and as expected:
```
[(('one', 'three'),
             0  1  2
  X   Y             
  one three  3  4  5),
 (('one', 'two'),
           0  1  2
  X   Y           
  one two  1  2  3),
 (('two', 'one'),
           0  1  2
  X   Y           
  two one  6  7  8)]
```

When using modin.pandas, no result is produced:
```
[]
```

I guess the issue is specific to the `level=`-based groupby. It also occurs when the groupby is done only by a single level.

Maybe related: https://github.com/modin-project/modin/issues/234

**Comment by devin-petersohn** [comment]
Hi @alex04103 thanks for the report!

I think it may also be related to #2531, which we have work in progress on fixing.
