### ISSUE TITLE
Investigate performance regression that brought by 'dropna=True' at GroupBy

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2896]
6287b30430a6649b7b5111efa93967a0419a7388 commit added `dropna` implementation for OmniSci backend, and also enabled `dropna` parameter in groupby. However, it's reported that it brought performance regression in groupby queries at taxi benchmark and broken `plasticc`. This needs to be checked and fixed. For now `dropna` logic at `groupby` is disabled by 7005388204c07e40aeb5765529e4c601faf3fdd0

**Comment by YarShev** [comment]
We should consider this for near releases.
cc @Garra1980

**Comment by gshimansky** [comment]
Are there any plans for this issue?

**Comment by Garra1980** [comment]
which one exactly, I see at least two :)

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
