### ISSUE TITLE
[ASV] performance regression in append operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2899]
Pandas_on_ray engine - 44 cpus
<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
265±8ms     |     338±9ms  |   1.28 | benchmarks.TimeAppend.time_append(((500000, 20), (1000000, 10)), True)
899±20ms    |   1.01±0.02s  |   1.12 | benchmarks.TimeAppend.time_append(((5000, 5000), (5000, 5000)), True)

Found regression commits:
* 7cfc85c311fbe91c653285c46639352dd9ae4321
* 6f1e0c04b22a82f7a24271a5e9d4139cc5ee5537

Used command:
`asv continuous -f 1.05 5b6f73a98cc0ee5a78503704b98b7268709dc797 21707d2dd8c51404db692e27fb1a69203440d2eb  --launch-method=spawn -b time_append  -a repeat=8 -a number=2`

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by pyrito** [comment]
@anmyachev is this just flaky/sporadic or is this consistently slower?

**Comment by anmyachev** [comment]
> @anmyachev is this just flaky/sporadic or is this consistently slower?

@pyrito consistently slower (but the reason for the degradation of performance may already be different)
![image](https://user-images.githubusercontent.com/45976948/186457778-c19a6f2a-a4b2-4599-8ae0-822cac3cc11e.png)

**Comment by anmyachev** [comment]
Not relevant since `append` has been removed in pandas 2.X and modin 0.23.0.
