### ISSUE TITLE
[ASV] performance regression in mean operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2900]
Pandas_on_ray engine - 44 cpus
<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
   109±3ms     |     153±3ms  |   1.40 | benchmarks.TimeArithmetic.time_mean((1000000, 10), 0)

Found regression commits:
* caa10993a589b2cb642ce5bd8bc5a8221d00879e

Used command:
`asv continuous -f 1.05 5b6f73a98cc0ee5a78503704b98b7268709dc797 21707d2dd8c51404db692e27fb1a69203440d2eb  --launch-method=spawn -b time_mean  -a repeat=8 -a number=2`

**Comment by anmyachev** [comment]
caa10993a589b2cb642ce5bd8bc5a8221d00879e also affects `median`, `nunique`, `sum` operations

<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
209_5ms  |       388_20ms |    1.86 | benchmarks.TimeArithmetic.time_median((5000, 5000), 0) 
190_9ms  |       381_20ms |    2.00 | benchmarks.TimeArithmetic.time_nunique((5000, 5000), 0)
 99.9_3ms |         148_3ms |    1.48 | benchmarks.TimeArithmetic.time_sum((1000000, 10), 0)

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Hi @anmyachev! Are these performance regressions still present? Should we assign this to someone?

**Comment by anmyachev** [comment]
@RehanSD there is a regression. The best result we had for `mean` op was 90ms

**Comment by anmyachev** [comment]
Results are not actual.
