### ISSUE TITLE
[ASV] performance regression in nunique operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2901]
Pandas_on_ray engine - 44 cpus
<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
2.32±0.08s |       5.00±0.1s  |   2.15 | benchmarks.TimeArithmetic.time_nunique((1000000, 10), 1)

Found regression commits:
* 5cb3283531322f5ad709f1c9a3f618953b2aab32

Used command:
`asv continuous -f 1.05 5b6f73a98cc0ee5a78503704b98b7268709dc797 21707d2dd8c51404db692e27fb1a69203440d2eb  --launch-method=spawn -b time_nunique  -a repeat=8 -a number=2`

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Hi @anmyachev! Are these performance regressions still present? Should we assign the to someone?

**Comment by anmyachev** [comment]
Not relevant, current result: 2.39 sec
