### ISSUE TITLE
[ASV] performance regression in mean operation applied to groupby object

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2902]
Pandas_on_ray engine - 44 cpus
<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
2.19±0.02s  |        4.12±0s |    1.88 | benchmarks.TimeGroupByMultiColumn.time_groupby_agg_mean((1000000, 10), 'huge_amount_groups', 6)

Found regression commits:
* 5cb3283531322f5ad709f1c9a3f618953b2aab32

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Hi @anmyachev! Are these performance regressions still present? Should we assign the to someone?

**Comment by anmyachev** [comment]
Hi @RehanSD! The regression is still present, but the current result is slightly better: 3.552 s.

I think @dchigarev knows this code very well but I don’t know if he has the time for it.

**Comment by anmyachev** [comment]
Results are not actual.
