### ISSUE TITLE
[ASV] performance regressions

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2903]
Need more investigations:

Pandas_on_ray engine - 44 cpus

<0.8.0>   |     <0.9.1>|       ratio | benchmark
-|-|-|-
209±5ms      |    255±2ms     |1.22 | benchmarks.TimeValueCountsSeries.time_value_counts((5000, 5000), 100, 3)
250±4ms       |   306±7ms     |1.22  |benchmarks.TimeValueCountsSeries.time_value_counts((1000000, 10), 100, 3)
674±10ms        | 799±20ms     |1.19  |benchmarks.TimeResetIndex.time_reset_index((5000, 5000), True, None)
1.99±0.01s   |    2.19±0.01s     |1.10  |benchmarks.TimeMerge.time_merge(((5000, 5000), (5000, 5000)), 'inner', False)
1.52±0s       |1.67±0.01s     |1.10  |benchmarks.TimeIndexing.time_iloc((5000, 5000), 'bool')
1.86±0.01s    |   2.01±0.02s  |   1.09  |benchmarks.TimeIndexing.time_iloc((5000, 5000), 'function')
2.02±0.02s     |  2.18±0.02s   |  1.08  |benchmarks.TimeJoin.time_join(((5000, 5000), (5000, 5000)), 'inner', False)
1.54±0.01s      | 1.65±0.01s    | 1.07  |benchmarks.TimeIndexing.time_iloc((5000, 5000), 'slice')
2.04±0.01s       |2.17±0.01s     |1.07  |benchmarks.TimeJoin.time_join(((5000, 5000), (5000, 5000)), 'left', False)

**Comment by RehanSD** [comment]
Hi @anmyachev! Are these performance regressions still present? Should we assign the to someone?
