### ISSUE TITLE
Running slow than normal pandas 

### ISSUE THREAD

**Issue by pavanpraneeth** [modin-project/modin#2911]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by pavanpraneeth** [comment]
First it ran fast then it became dead slow. Anything required to do from my side

**Comment by YarShev** [comment]
Hi @pavanpraneeth , can you give the code snippet that you are using, please?

**Comment by pavanpraneeth** [comment]
import os


from distributed import Client

Client(n_workers=10)
import modin.pandas as pd



global df1
s=time.time()
df1=pd.read_parquet('class1_sec_out.parquet.gzip')
e=time.time()
print(e-s)
df2=pd.read_parquet('hcc_class1.parquet.gzip')

df2.loc[:,'flag'] = ''
df2.loc[:,'sec'] = ''
df2.loc[:,'sec_std'] = ''
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')
e=time.time()



def hcc(df2):
    for i in tqdm(range(len(df2))):
        temp=df1[df1['document_id']==df2['document_id'][i]]
        temp.reset_index(drop=True,inplace=True)
        sub_temp=temp[temp['Section_start']<=df2['start_char'][i]]
        sub_temp.reset_index(drop=True,inplace=True)
        
        if len(sub_temp) > 0 :
            if (sub_temp['Section_end'].iloc[-1] >= df2['end_char'][i]):

                s1=sub_temp['Section'].iloc[-1]
                s2=sub_temp['Section_Standardized'].iloc[-1]
                df2['flag'][i]=1
                df2['sec'][i]=s1
                df2['sec_std'][i]=s2
            else:
                df2['flag'][i]=0
                df2['sec'][i]=''
                df2['sec_std'][i]=''
                
        else:
                df2['flag'][i]=0
                df2['sec'][i]=''
                df2['sec_std'][i]=''
    return df2

**Comment by pavanpraneeth** [comment]
> Hi @pavanpraneeth , can you give the code snippet that you are using, please?

hi please check

**Comment by YarShev** [comment]
@pavanpraneeth , I would like to clarify what issue you are experiencing. I see you measured this line `df1=pd.read_parquet('class1_sec_out.parquet.gzip')` and print the time via `print(e-s)`. When does this become slower?

**Comment by pavanpraneeth** [comment]
> @pavanpraneeth , I would like to clarify what issue you are experiencing. I see you measured this line `df1=pd.read_parquet('class1_sec_out.parquet.gzip')` and print the time via `print(e-s)`. When does this become slower?

it just ran well in the morning, normally by pandas it take 2 secs to read this ,with modin it is taking 4 sec and rest function is aslo exec slowly

**Comment by pavanpraneeth** [comment]
> > @pavanpraneeth , I would like to clarify what issue you are experiencing. I see you measured this line `df1=pd.read_parquet('class1_sec_out.parquet.gzip')` and print the time via `print(e-s)`. When does this become slower?
> 
> it just ran well in the morning, normally by pandas it take 2 secs to read this ,with modin it is taking 4 sec and rest function is aslo exec slowly

when i run this line 2 times, it is fast for second time

**Comment by pavanpraneeth** [comment]
> > @pavanpraneeth , I would like to clarify what issue you are experiencing. I see you measured this line `df1=pd.read_parquet('class1_sec_out.parquet.gzip')` and print the time via `print(e-s)`. When does this become slower?
> 
> it just ran well in the morning, normally by pandas it take 2 secs to read this ,with modin it is taking 4 sec and rest function is aslo exec slowly

Hi @YarShev please reply fast

**Comment by pavanpraneeth** [comment]
can u please suggest some solution to engine initialization?
also size is(505421,22)
please it will be great

**Comment by pavanpraneeth** [comment]
also should i use loc instead of indexing

**Comment by YarShev** [comment]
> can u please suggest some solution to engine initialization?
> also size is(505421,22)
> please it will be great

You can initialize an engine yourself, i.e. do as follows:
```python
# in case of Dask engine
from distributed.client import Client
client = Client(n_workers="your_number")
# in case of Ray engine
import ray
ray.init(num_cpus="your_number")
```
In that case two identical Modin operations that follow to each other should have +/- the same performance.

> also should i use loc instead of indexing

`loc` is one of the indexing's way. Please, refer to [this comment](https://github.com/modin-project/modin/issues/2893#issuecomment-801180022) about `loc`.

**Comment by mivikasgarud** [comment]
@YarShev @devin-petersohn 
I have a dataframe having >100k records, it has 10-15 columns which needs to be coalesced, I used following code:
    for COL in [cols_to_be_coalesced]:
        df['COL'] = np.where(df['COL']!='', df['COL'], df['COL_X'])   

Here if df is pandas dataframe, it executes it in ~2 minutes but of df is modin dataframe, it takes ~30 minutes. 
Can you please suggest equivalent faster alternative of np.where for modin dataframe ?

**Comment by devin-petersohn** [comment]
@mivikasgarud I answered on the mailing list, copying here:

Thanks for the question. It's a good point, we don't currently support the numpy functionalities, but there might be a way we can with NEP18. If you are comfortable, it would be nice to add an issue to the GitHub repo to support NEP18 in Modin.

A small rewrite to enable the parallelism of the low level Modin implementation:
```python
def apply_func(df):
    for COL in [cols_to_be_coalesced]:
        df['COL'] = np.where(df['COL']!='', df['COL'], df['COL_X'])

df.apply(lambda s: apply_func(s.to_frame(), axis=1)
```
Let me know how it goes!

**Comment by RehanSD** [comment]
Hi folks! It seems like the performance issues in question have hopefully been resolved by Devin's code snippet above, so I'm marking this as closed! If folks have further questions, please feel free to reopen this issue, or to open a new issue!
