### ISSUE TITLE
[ASV] performance regression in value_counts operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2925]
Pandas_on_ray engine - 44 cpus

Benchmark | Commit | Factor | Before | After
-- | -- | -- | -- | --
benchmarks.TimeValueCountsSeries.time_value_counts((1000000, 10), 100, None) | 09d7c180 | 2.18x | 138.171ms | 300.928ms
benchmarks.TimeValueCountsSeries.time_value_counts((5000, 5000), 100, None) | 09d7c180 | 1.99x | 138.166ms | 275.188ms

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Hi @anmyachev - do these performance regressions still appear on master?

**Comment by anmyachev** [comment]
Results are not actual.
