### ISSUE TITLE
[ASV] performance regression in sort_values operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2927]
Pandas_on_ray engine - 44 cpus

Benchmark | Commit | Factor | Before | After
-- | -- | -- | -- | --
benchmarks.TimeSortValues.time_sort_values((5000, 5000), 1, True) | 7c46bddc | 1.23x | 2.389s | 2.930s
benchmarks.TimeSortValues.time_sort_values((5000, 5000), 1, False) | 7c46bddc | 1.23x | 2.384s | 2.932s

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Duplicate of #3535
