### ISSUE TITLE
[ASV] performance regression in head operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2928]
Pandas_on_ray engine - 44 cpus

Benchmark | Commit | Factor | Before | After
-- | -- | -- | -- | --
benchmarks.TimeHead.time_head((5000, 5000), 0.8) | b49cc682 | 1.09x | 148.893ms | 162.408ms
benchmarks.TimeHead.time_head((5000, 5000), 5) | b49cc682 | 1.08x | 47.301ms | 51.182ms

**Comment by anmyachev** [comment]
Feel free to reassign.

**Comment by RehanSD** [comment]
Hi @anmyachev! Are these performance regressions still present? Should we assign the to someone?

**Comment by anmyachev** [comment]
Not relevant, current results:

Benchmark | Current results
-- | -- 
benchmarks.TimeHead.time_head((5000, 5000), 0.8) | 86.527ms
benchmarks.TimeHead.time_head((5000, 5000), 5) | 27.393ms
