### ISSUE TITLE
Support more "create dataframe" options in FSI

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#2931]
We need to support more options in CREATE DATAFRAME
- [ ] skip row import if it is longer than MAX_LENGTH
- [ ] support array type
- [ ] support shared dictionary

**Comment by RehanSD** [comment]
Hi @fexolm! I'm wondering if any progress has been made on this issue? I'm marking it as stale here, but feel free to reopen it or open a new issue if you'd like to resolve this!
