### ISSUE TITLE
Document `modin.pandas.[groupby, indexing, accessor, iterator, plotting, series_utils, io, general]`

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2959]
Initial status of doc-strings in related modules:
|Filename|Doc-strings status|
|-|-|
|indexing.py	| no docs at all|
|groupby.py	| all docs are already inherited from pandas, except: `__init__`, `__getitem__`, `_index`, `_sort`, `_as_index`, `_iter`, `_index_grouped`, `_wrap_aggregation`, `_apply_agg_function`, `_default_to_pandas`
accessor.py	| all docs are already inherited from pandas, except: `BaseSparseAccessor` (only has 3 methods)
|utils.py            | all docs are already written, except: `from_non_pandas`. Check relevance of existed docs|
|iterator.py	| all docs are already written, check its relevance|
|plotting.py	| all docs are already written, check its relevance|
|series_utils.py | all docs are already inherited, only `__init__` doc is required|
|io.py		| all docs are already written or inherited, check its relevance|
|general.py	| all docs are already inherited|

In addition to methods and classes docstrings, we should also write a brief description of each module at the beginning of it.

**Comment by gshimansky** [comment]
I'll take care about `indexing`.

**Comment by gshimansky** [comment]
I'll take care of `accessor.py`

**Comment by gshimansky** [comment]
It'll take care of `utils.py`.

**Comment by gshimansky** [comment]
I'll take care of `iterator.py`.

**Comment by gshimansky** [comment]
I'll take care of `plotting.py`.

**Comment by gshimansky** [comment]
I'll take care of `series_utils.py`.

**Comment by gshimansky** [comment]
I'll take care of `io.py`.

**Comment by gshimansky** [comment]
I'll take care of `general.py`.

**Comment by gshimansky** [comment]
I'll take care of `groupby.py`.
