### ISSUE TITLE
'modin.pandas' has no attribute 'select_dtypes'

### ISSUE THREAD

**Issue by chetan-velivela** [modin-project/modin#2960]
Modin seems to have no quick way to select specific columns from a dataframe, such as getting a second dataframe that only contains the numeric columns of the first. When attempting to use a = pd.select_dtypes(np.number) I get the error 'modin.pandas' has no attribute 'select_dtypes'.

**Comment by devin-petersohn** [comment]
Hi @chetan-velivela thanks for posting!

I believe the correct usage is to use `df.select_dtypes(np.number)` instead of `pd.select_dtypes`. Pandas gives me the same error if I try to use pandas.select_dtypes:

```
In [1]: import pandas

In [2]: pandas.select_dtypes
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5809631886ce> in <module>
----> 1 pandas.select_dtypes

~\anaconda3\lib\site-packages\pandas\__init__.py in __getattr__(name)
    242         return _SparseArray
    243
--> 244     raise AttributeError(f"module 'pandas' has no attribute '{name}'")
    245
    246

AttributeError: module 'pandas' has no attribute 'select_dtypes'
```

**Comment by chetan-velivela** [comment]
You are correct, thanks for the quick solution
