### ISSUE TITLE
Request for support on cx_Oracle, pyodbc, and pymysql modules

### ISSUE THREAD

**Issue by megurikun08** [modin-project/modin#2973]
Hi MODIN team, good day. This is to request for a patch/support on cx_Oracle, pyodbc, and pymysql modules. As I have been using modin recently, I always receive a warning prompt in my python console

`UserWarning: To use parallel implementation of 'read_sql', pass the sqlalchemyconnection string instead of <class 'cx_Oracle.Connection'>`

many thanks!

**Comment by ra928** [comment]
Hi Modin team! Just wanted to emphasis that, it would be really good add. 
Thank you so much!

**Comment by devin-petersohn** [comment]
@mvashishtha Do we support these through the `ModinConnection` interfaces?

**Comment by mvashishtha** [comment]
@ra928 @megurikun08 Modin should now support the following without that warning:

- pymysql with a sqlalchemy connection string like [this](https://stackoverflow.com/a/31295255/17554722)
- pyodbc with a sqlalchemy connection string like [these](https://stackoverflow.com/a/15750953/17554722)
- cx_oracle with a sqlalchemy connection string built as [here](https://stackoverflow.com/a/57693172/17554722)

You should be able to use Modin by passing the connection string directly to `read_sql` as you would in pandas, e.g.:

```python
import modin.pandas as pd
pd.read_sql("SELECT * FROM my_table;", con="mssql+pyodbc://user:password@server/database")
```

If you prefer to create a sqlalchemy connection with the sqlalchemy [`create_engine`](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine) method, you can use [`ModinDatabaseConnection`](https://modin.readthedocs.io/en/stable/getting_started/faq.html?highlight=ModinDatabaseConnection#how-do-i-connect-modin-to-a-database-via-read-sql) to forward any arguments you want to `create_engine`.
