### ISSUE TITLE
Define public API for internal frame classes

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#2978]
Since we are currently working on Modin documentation (docstrings, rst documentation in `docs` folder), we need to define public API for the classes that are in `modin/engines/base/frame` folder in order to expose the right API in rst documentation. I would like to suggest the following changes:

`BaseFrameAxisPartition` - without changes for now

* ``apply``
* ``shuffle``
* ``force_materialization``
* ``unwrap``

`PandasFrameAxisPartition` - without changes for now

* ``apply``
* ``shuffle``
* ``deploy_axis_func``
* ``deploy_func_between_two_axis_partitions``

`BasePandasFrame`

* ``dtype``
* ``axes``
* ``_apply_index_objs`` - convert to public
* ``mask``
* ``from_labels``
* ``to_labels``
* ``reorder_labels``
* ``copy``
* ``combine_dtypes``
* ``astype``
* ``add_prefix``
* ``add_suffix``
* ``_numeric_columns`` - convert to public
* ``_fold_reduce`` - convert to public
* ``_map_reduce`` - convert to public
* ``_map`` - convert to public
* ``_fold`` - convert to public
* ``filter_full_axis``
* ``_apply_full_axis`` - convert to public
* ``_apply_full_axis_select_indices`` - convert to public
* ``_apply_select_indices`` - convert to public
* ``broadcast_apply``
* ``broadcast_apply_select_indices``
* ``broadcast_apply_full_axis``
* ``_binary_op`` - convert to public
* ``_concat`` - convert to public
* ``groupby_reduce``
* ``from_pandas``
* ``from_arrow``
* ``to_pandas``
* ``to_numpy``
* ``transpose``
* ``finalize`` - convert to private or rework so that the partition manager manipulate with the partitions, but not the frame itself does.

`BaseFrameManager` - convert to `BasePandasFrameManager`

* ``preprocess_func``
* ``groupby_reduce``
* ``broadcast_apply_select_indices``
* ``broadcast_apply``
* ``broadcast_axis_partitions``
* ``map_partitions``
* ``lazy_map_partitions``
* ``map_axis_partitions``
* ``simple_shuffle``
* ``concat``
* ``concatenate``
* ``to_pandas``
* ``to_numpy``
* ``from_pandas``
* ``from_arrow``
* ``get_indices``
* ``apply_func_to_select_indices``
* ``apply_func_to_select_indices_along_full_axis``
* ``apply_func_to_indices_both_axis``
* ``binary_operation``

`BaseFramePartition` - convert to `BasePandasFramePartition`

* ``get``
* ``apply``
* ``add_to_apply_calls``
* ``drain_call_queue``
* ``wait``
* ``to_pandas``
* ``to_numpy``
* ``mask``
* ``put``
* ``preprocess_func``
* ``length``
* ``width``
* ``empty``
* ``width_extraction_fn`` - convert to private
* ``length_extraction_fn`` - convert to private

cc @devin-petersohn

**Comment by vnlitvinov** [comment]
Assigning @devin-petersohn to take a look and give feedback on proposed conversions.

**Comment by devin-petersohn** [comment]
> * `BasePandasFrame._apply_index_objs` - convert to public
> * `BasePandasFrame.reorder_labels`

These should be private, everything else looks correct to me. Thanks @YarShev!

**Comment by YarShev** [comment]
@devin-petersohn , as for `BasePandasFrame._apply_index_objs`, I agree it should be private. However, I am not sure of `BasePandasFrame.reorder_labels`. Why do you think it should be private?

**Comment by YarShev** [comment]
@devin-petersohn, by the way, as for `BaseFrameManager - convert to BasePandasFrameManager`, maybe, we should rename the former to `BasePandasFramePartitionManager` (and all related stuff). What do you think?

**Comment by devin-petersohn** [comment]
@YarShev `reorder_labels` is used when the order output of `mask` does not match the order of occurrence in the dataframe. It is separated because it is expensive to reorder, and cheap to do the `mask` in order. It is not called from any other class.

**Comment by devin-petersohn** [comment]
@YarShev I suppose that would make sense, there's no way in those cases to avoid calling it because the metadata needs to be coordinated and rebroadcasted. In that case, I would prefer to change the name to `synchronize_labels` to be more descriptive (and discourage misuse).

**Comment by YarShev** [comment]
@devin-petersohn , what about this ([link](https://github.com/modin-project/modin/issues/2978#issuecomment-828415003))?

**Comment by YarShev** [comment]
@devin-petersohn , I saw fit to make the following changes:

* FrameManager -> PartitionManager
* _frame_mgr_cls-> _partition_mgr_cls
* BasePandasFrame -> PandasFrame
* BasePandasFrameManager -> PandasFramePartitionManager
* BasePandasFramePartition -> PandasFramePartition
* DaskFrameManager -> PandasOnDaskFramePartitionManager
* PythonFrameManager -> PandasOnPythonFramePartitionManager
* cuDFOnRayFrameManager -> cuDFOnRayFramePartitionManager
* RayFrameManager -> GenericRayFramePartitionManager
* PandasOnRayFrameManager -> PandasOnRayFramePartitionManager
* PyarrowOnRayFrameManager -> PyarrowOnRayFramePartitionManager
* OmnisciOnRayFrameManager -> OmnisciOnRayFramePartitionManager

Please, look at the changes in the PR.
