### ISSUE TITLE
Modin df.groupby() and groupby().sum() significantly slower than stock Pandas

### ISSUE THREAD

**Issue by raoberman** [modin-project/modin#2992]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.08
- **Modin version** (`modin.__version__`): 0.9
- **Python version**: 3.8
- **Code we can use to reproduce**: https://github.com/oneapi-src/oneAPI-samples/tree/master/AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted and code on screenshot (add at end):
- 
![image](https://user-images.githubusercontent.com/26121125/115252113-2bf96e80-a0f9-11eb-9786-2b6006ddd836.png)

### Describe the problem
Tested on 2 separate datasets, and machines, on AI Kit Modin and pip Modin installations - the dataset used in the screenshot code is 1.67 GB, so should be large enough to show performance. 
df.groupby().sum() and df.groupby() are significantly slower than stock Pandas (Modin performs at approximately 0.44x of stock Pandas speed).

Slow-down performance seen on multiple runs.

### Source code / logs
See GitHub and screenshot above^

**Comment by raoberman** [comment]
@aregm please prioritize

**Comment by devin-petersohn** [comment]
There have been significant regressions in `groupby` due to some recent changes in how metadata is handled and some special casing of code that probably should not have been merged. I am planning to start working on this soon. It has been reported elsewhere too.

**Comment by raoberman** [comment]
@devin-petersohn  is this fixed? should this be closed?

**Comment by anmyachev** [comment]
I benchmarked this functionality using the following reproducer with `Modin==0.10.1`:
```python
import numpy as np
import time
import os

os.environ["MODIN_CPUS"] = "4"

import pandas
import modin.pandas as pd

array=np.random.randint(low=100,high=10000,size=(2**18,2**8))
#array
np.savetxt("foo.csv", array, delimiter=",") #how to generate array

pandas_df = pandas.read_csv("foo.csv", names=["col{}".format(i) for i in range(256)])
pandas_df.head()

modin_df=pd.read_csv("foo.csv", names=["col{}".format(i) for i in range(256)])
modin_df.head()

print(f"MODIN_CPUS: {os.environ['MODIN_CPUS']}")

start = time.time()
pandas_df.groupby(by="col5").sum()
print(f"pandas groupby: {time.time()-start}")

start = time.time()
modin_df.groupby(by="col5").sum()
print(f"modin_df groupby: {time.time()-start}")
```

Got the following results:
```bash
MODIN_CPUS: 4
pandas groupby: 1.0989692211151123
modin_df groupby: 0.4405097961425781
MODIN_CPUS: 16
pandas groupby: 1.1088049411773682
modin_df groupby: 0.29872918128967285
MODIN_CPUS: 32
pandas groupby: 1.1032674312591553
modin_df groupby: 0.3968362808227539
```

According to my results, it turns out that the **Modin is faster**.
Can you re-measure and confirm that this problem disappeared from you?(by using `Modin==0.10.1`)

**Comment by raoberman** [comment]
confirmed. closing this issue

**Comment by junsongzhao** [comment]
Run same code on modin in /usr/local/lib/python3.9/dist-packages (0.18.0)
modin's groupby is still slower than pandas: 
pandas read_csv: 8.66018795967102
modin read_csv: 2.5489859580993652
shape = (14, 8)
MODIN_CPUS: 8
pandas groupby: 0.33652782440185547
modin_df groupby: 1.085317850112915

**Comment by anmyachev** [comment]
@junsongzhao thanks!

Indeed, I see slowdown again in Modin:
```bash
MODIN_CPUS: 8
pandas groupby: 0.5045671463012695
modin_df groupby: 1.0263855457305908
pandas groupby: 0.6923069953918457
modin_df groupby: 0.8415443897247314
pandas groupby: 0.4542958736419678
modin_df groupby: 0.8163461685180664
```

@dchigarev could take a look?

**Comment by YarShev** [comment]
@anmyachev, @dchigarev, should we reopen this issue?

**Comment by dchigarev** [comment]
Let's reopen since we had confirmed evidence of regression, I'll post with more details when I get look into it
