### ISSUE TITLE
Doc checker quirks

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2995]
### Describe the problem
There are certain quirks which doc checker from #2968 does not handle.

To reproduce place the code below as `modin/demo.py` and run `python scripts/doc_checker modin/demo.py`.

The issues are:
1. The script does not handle poor monkey-patching (replacing with `lambda` without copying a docstring)
2. `numpydoc.Validate()` reports weird results if identation in `Parameters` section is too big
3. The script does not point to exact line of failure, but rather to object definition start (makes fixing misspelled `moDin` in the example below harder)

We should check identation and report it to the user.

### Source code / logs
<details><summary>modin/demo.py</summary>

```python
def foo(a, b, c):
    """
    Foo mumble mumble.

    moDin is misspelled on purpose.

    Parameters
    ----------
        a : object
            This is description.
        b : object
            More text goes here.
        c : object
            Outta fantasy what to say.

    Returns
    -------
    int
        Random number, generated by fair dice roll.
    """
    return 4


foo = lambda a, b, c: 5
```
</details>

<details><summary>Output when `foo` monkey-patching is active</summary>

```
INFO:PYDOCSTYLE OUTPUT FOR modin\demo.py
ERROR:modin\demo.py:1 at module level:
        D100: Missing docstring in public module
modin\demo.py:1 in public function `foo`:
        D103: Missing docstring in public function

Traceback (most recent call last):
  File "scripts/doc_checker.py", line 557, in <module>
    if not validate(args.paths, args.add_ignore, not args.disable_numpydoc):
  File "scripts/doc_checker.py", line 489, in validate
    if not numpydoc_validate(path):
  File "scripts/doc_checker.py", line 402, in numpydoc_validate
    results = list(map(validate_object, to_validate))
  File "scripts/doc_checker.py", line 328, in validate_object
    noqa_checks = get_noqa_checks(doc)
  File "scripts/doc_checker.py", line 298, in get_noqa_checks
    if "# noqa:" in noqa_str:
TypeError: argument of type 'NoneType' is not iterable
```
</details>

<details><summary>Output when `foo = lambda` is commented out</summary>

```
INFO:PYDOCSTYLE OUTPUT FOR modin\demo.py
ERROR:modin\demo.py:1 at module level:
        D100: Missing docstring in public module

INFO:NUMPYDOC OUTPUT FOR modin\demo.py
ERROR:modin.demo:0:GL08:The object does not have a docstring
ERROR:modin.demo.foo:1:PR01:Parameters {'c', 'b'} not documented
ERROR:modin.demo.foo:1:MD02:Spelling error in line: 3, found: 'moDin', reference: 'Modin'
ERROR:INVALID DOCUMENTATION FOUND
```
</details>

**Comment by gshimansky** [comment]
I get an error about word `ray` in an URL on [this line](https://github.com/modin-project/modin/blob/master/modin/pandas/indexing.py#L28). Can you advise how to disable it?

**Comment by anmyachev** [comment]
> I get an error about word `ray` in an URL on [this line](https://github.com/modin-project/modin/blob/master/modin/pandas/indexing.py#L28). Can you advise how to disable it?

Now there is only one way - use `# noqa: MD02`, but since such a solution disables checking of all words in the dockstring, then in #3001 I will need change regexp pattern.

**Comment by gshimansky** [comment]
> Now there is only one way - use `# noqa: MD02`, but since such a solution disables checking of all words in the dockstring, then in #3001 I will need change regexp pattern.

I have troubles placing `# noqa: MD02` correctly. Whenever I put it, it has no effect on the docstring at the beginning of this file. How do you suggest to do it?

**Comment by anmyachev** [comment]
> > Now there is only one way - use `# noqa: MD02`, but since such a solution disables checking of all words in the dockstring, then in #3001 I will need change regexp pattern.
> 
> I have troubles placing `# noqa: MD02` correctly. Whenever I put it, it has no effect on the docstring at the beginning of this file. How do you suggest to do it?

To apply to the module documentation, `# noqa: MD02` should be placed in the first line of the file.

**Comment by gshimansky** [comment]
I have problem with files `modin/pandas/groupby.py` and `modin/pandas/plotting.py` because `doc_checker` breaks on them like this:
```
Traceback (most recent call last):
  File "scripts/doc_checker.py", line 581, in <module>
    if not validate(args.paths, args.add_ignore, not args.disable_numpydoc):
  File "scripts/doc_checker.py", line 513, in validate
    if not numpydoc_validate(path):
  File "scripts/doc_checker.py", line 428, in numpydoc_validate
    results = list(map(validate_object, to_validate))
  File "scripts/doc_checker.py", line 353, in validate_object
    results = validate_modin_error(doc, results)
  File "scripts/doc_checker.py", line 243, in validate_modin_error
    errors += check_spelling_words(doc)
  File "scripts/doc_checker.py", line 174, in check_spelling_words
    for idx, line in enumerate(inspect.getsourcelines(doc.code_obj)[0]):
  File "/home/gregory/work/miniconda3/envs/modin/lib/python3.8/inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/gregory/work/miniconda3/envs/modin/lib/python3.8/inspect.py", line 780, in findsource
    file = getsourcefile(object)
  File "/home/gregory/work/miniconda3/envs/modin/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/home/gregory/work/miniconda3/envs/modin/lib/python3.8/inspect.py", line 676, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got property
```
I tried the latest commit from PR #3001 branch and the problem is still reproducible.

**Comment by gshimansky** [comment]
Another problem with `doc_checker` is that for file `modin/pandas/accessor.py` from PR #3022 I get errors about functions `from_spmatrix` and `from_coo` although docstrings for these functions should be inherited.

**Comment by gshimansky** [comment]
Another problem with `doc_checker` is that when I have to write `# noqa: MD02` on the first line of a file, our `test_headers` fails for it https://github.com/modin-project/modin/pull/3022/checks?check_run_id=2452514001
Writing `# noqa: MD02` on the first line of a file is the only way to suppress an error about `ray` on this line: https://github.com/modin-project/modin/blob/master/modin/pandas/indexing.py#L28 .

**Comment by anmyachev** [comment]
> Another problem with `doc_checker` is that when I have to write `# noqa: MD02` on the first line of a file, our `test_headers` fails for it https://github.com/modin-project/modin/pull/3022/checks?check_run_id=2452514001
> Writing `# noqa: MD02` on the first line of a file is the only way to suppress an error about `ray` on this line: https://github.com/modin-project/modin/blob/master/modin/pandas/indexing.py#L28 .

fixed

**Comment by anmyachev** [comment]
> Another problem with `doc_checker` is that for file `modin/pandas/accessor.py` from PR #3022 I get errors about functions `from_spmatrix` and `from_coo` although docstrings for these functions should be inherited.

The problem has to do with how `_inherit_docstrings` handle functions with `classmethod` decorator.

**Comment by vnlitvinov** [comment]
> The problem has to do with how `_inherit_docstrings` handle functions with `classmethod` decorator. cc @vnlitvinov

Tracked by #3033
