### ISSUE TITLE
[OmniSci] Apply calcite self-join fix to modin optimization pipeline

### ISSUE THREAD

**Issue by fexolm** [modin-project/modin#3006]
Omnisci team found and fixed the problem with self-join queries in their calcite server. 
As we have a separate optimization path for our modin-on-omnisci endpoint we should apply the same patch to it.

The patch is not open-sourced yet, but it should be open-sourced in the next release.

**Comment by igalink** [comment]
PR created: https://github.com/intel-ai/omniscidb/pull/158
