### ISSUE TITLE
[Omnisci] Document Calcite input format that we use in Modin-on-Omnisci mode

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#3007]
For Omnisci backend we communicate with Calcite using json-based protocol. Let's try to document it first and then put somewhere in Omnisci's internals

**Comment by Garra1980** [comment]
I believe it is here - https://github.com/intel-ai/omniscidb/blob/ienkovich/doc-rel-alg-json/docs/source/calcite/rel_alg_json.rst

**Comment by RehanSD** [comment]
Hi @Garra1980 and @fexolm - is this issue still open?
