### ISSUE TITLE
Bump Ray Version to 1.3

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#3010]

**Comment by vnlitvinov** [comment]
I think this might be blocked by https://github.com/conda-forge/ray-packages-feedstock/pull/11

**Comment by devin-petersohn** [comment]
@vnlitvinov I don't think we should let it be blocked on the conda-forge release. We need to make changes to enable us to not be blocked because we use the conda-forge release in our tests. I can make the necessary changes.

**Comment by devin-petersohn** [comment]
We will upgrade to 1.4. Ray 1.3 does not support the way we handle joins/groupby. Ray 1.4 does.

**Comment by crypdick** [comment]
Related: #3130
