### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'axes'

### ISSUE THREAD

**Issue by KangTomwk** [modin-project/modin#3012]
demo:
from modin.distributed.dataframe.pandas import from_partitions
from_partitions(partition,1) 

Where partition is the objectRef of ray stored in the list

The following error occurred：
RayTaskError(AttributeError): ray::deploy_ray_func() (pid=19880, ip=10.3.69.181)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "/root/miniconda3/envs/dev/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 253, in deploy_ray_func
    result = func(partition, **kwargs)
  File "/root/miniconda3/envs/dev/lib/python3.7/site-packages/modin/distributed/dataframe/pandas/partitions.py", line 162, in <lambda>
    index = partition_mgr_class.get_indices(0, parts, lambda df: df.axes[0])
AttributeError: 'bytes' object has no attribute 'axes'

Has anyone encountered it ？？？？

**Comment by YarShev** [comment]
Hi @KangTomwk , thanks for the posting! Please, provide more details from your scenario. Which object does `partition[0]` refers to? Is it a pandas DataFrame? Here is a working example:

```python
from modin.distributed.dataframe.pandas import from_partitions
import pandas
import ray

ray.init()
pdf = pandas.DataFrame([1, 2, 3])
partition = [ray.put(pdf)]
mdf = from_partitions(partition, axis=1)
```

**Comment by KangTomwk** [comment]
> Hi @KangTomwk , thanks for the posting! Please, provide more details from your scenario. Which object does `partition[0]` refers to? Is it a pandas DataFrame? Here is a working example:
> 
> ```python
> from modin.distributed.dataframe.pandas import from_partitions
> import pandas
> import ray
> 
> ray.init()
> pdf = pandas.DataFrame([1, 2, 3])
> partition = [ray.put(pdf)]
> mdf = from_partitions(partition, axis=1)
> ```

Hi 
This is my example：

```
from modin.distributed.dataframe.pandas import from_partitions

list_objectRef = []
for ref in itear_objectRef:
    list_objectRef.append(ref)
len(list_objectRef)
actual_df = from_partitions(list_objectRef, 1)
```

Here itear_objectRef is the objectStore that we write to ray with flink, which is an iterator, and then traverse the iterator and put it into the list, which is equivalent to [ray.put(pdf)]！！！

**Comment by YarShev** [comment]
@KangTomwk . to understand the issue can you change your example a bit?

```python
import ray
from modin.distributed.dataframe.pandas import from_partitions

list_objectRef = []
for ref in itear_objectRef:
    list_objectRef.append(ref)
print(len(list_objectRef))
materialized_objects = ray.get(list_objectRef)
print([type(obj) for obj in materialized_objects])
print([obj for obj in materialized_objects)
actual_df = from_partitions(list_objectRef, 1)
```
If `materialized_objects` contains at least one object different from pandas DataFrame, there will be an error when calling `from_partitions` because currently Modin supports pandas DataFrame(s) as underlying partitions.

**Comment by KangTomwk** [comment]
> @KangTomwk . to understand the issue can you change your example a bit?
> 
> ```python
> import ray
> from modin.distributed.dataframe.pandas import from_partitions
> 
> list_objectRef = []
> for ref in itear_objectRef:
>     list_objectRef.append(ref)
> print(len(list_objectRef))
> materialized_objects = ray.get(list_objectRef)
> print([type(obj) for obj in materialized_objects])
> print([obj for obj in materialized_objects])
> actual_df = from_partitions(list_objectRef, 1)
> ```
> 
> If `materialized_objects` contains at least one object different from pandas DataFrame, there will be an error when calling `from_partitions` because currently Modin supports pandas DataFrame(s) as underlying partitions.

Hi

How do I convert objectRef into pandas dataframe now? Then convert multiple pandas dataframes into a modin dataframe？

**Comment by YarShev** [comment]
@KangTomwk , please, let me know what the line `print([type(obj) for obj in materialized_objects])` prints. If all the objects are pandas DataFrame(s), your example should work.

**Comment by KangTomwk** [comment]
> @KangTomwk，请让我知道该行`print([type(obj) for obj in materialized_objects])`打印的内容。如果所有对象都是pandas DataFrame，则您的示例应该可以使用。

Hi

The result is as follows：[<class 'bytes'>]

**Comment by YarShev** [comment]
@KangTomwk , okay, probably, you write data as `bytes` (pickled data) to ray object store with flink. Modin doesn't know anything about how an object should look like being unpickled. Are you able to unpickle data (via `cloudpickle.loads()`) before putting it to ray object store?

**Comment by KangTomwk** [comment]
> @KangTomwk，好吧，可能是使用flink将数据写为`bytes`（腌制数据）到ray对象存储中。Modin对某个物体看起来像被解开的样子一无所知。您是否可以通过`cloudpickle.loads()`将数据放到ray对象存储中来对其进行修补？

How does modin convert a pandas dataframe into a modin dataframe?

**Comment by YarShev** [comment]
@KangTomwk , you can use the following function to convert a pandas DataFrame to a Modin DataFrame:
```python
from modin.pandas.utils import from_pandas
modin_df = from_pandas(pandas_df)
```

**Comment by YarShev** [comment]
Reclassifying the issue as question.

**Comment by KangTomwk** [comment]
> @KangTomwk , you can use the following function to convert a pandas DataFrame to a Modin DataFrame:
> 
> ```python
> from modin.pandas.utils import from_pandas
> modin_df = from_pandas(pandas_df)
> ```

How to merge multiple modin dataframes together？？？

**Comment by YarShev** [comment]
I guess you need `concat` function but if you are interested in another type of merge, you can use `merge` or `join` functions.
```python
import modin.pandas as pd
concatenated_modin_df = pd.concat(list_of_modin_dfs, axis=X) # where X is axis along which you want to concatenate modin dfs
```

What about this question?

> Are you able to unpickle data (via cloudpickle.loads()) before putting it to ray object store?

**Comment by KangTomwk** [comment]
What is cloudpickle.loads()? Why do you want to do this? Don't understand？？

**Comment by YarShev** [comment]
@KangTomwk , I guess you serialize data (transform data to bytes via `cloudpickle.dumps()`) before putting it ray object store. When creating a Modin DataFrame using `from_partitions` Modin refers to actual data to compute index and columns via passed list of object refs. Since actual data is bytes you has the error. However, if you deserialize data (transform bytes to data via `cloudpickle.loads()`) before putting it to ray object store, Modin will be able to construct a DataFrame correctly.

**Comment by KangTomwk** [comment]
`bst.predict(dtrain_200w)` 
The following error occurred：
无标题 
2021-05-06 10:45:29,119 INFO xgboost.py:102 -- Prediction started
2021-05-06 10:45:35,366 INFO xgboost_ray.py:378 -- Data preparation time: 6.237504959106445 s
---------------------------------------------------------------------------
RayTaskError(IndexError)                  Traceback (most recent call last)
<ipython-input-29-edb132072a5f> in <module>
----> 1 bst.predict(dtrain_200w)

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost.py in predict(self, data, nthread, **kwargs)
    111         ), f"Type of `data` is {type(data)}, but expected {DMatrix}."
    112 
--> 113         result = _predict(self.copy(), data, nthread, **kwargs)
    114         LOGGER.info("Prediction finished")
    115 

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost_ray.py in _predict(booster, data, nthread, **kwargs)
    400     results = [part_res for part_res, _ in results]
    401 
--> 402     result = from_partitions(results, 0).reset_index(drop=True)
    403     LOGGER.info(f"Prediction time: {time.time() - s} s")
    404 

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/distributed/dataframe/pandas/partitions.py in from_partitions(partitions, axis)
    160         )
    161 
--> 162     index = partition_mgr_class.get_indices(0, parts, lambda df: df.axes[0])
    163     columns = partition_mgr_class.get_indices(1, parts, lambda df: df.axes[1])
    164     return DataFrame(

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py in get_indices(cls, axis, partitions, index_func)
    147                 else []
    148             )
--> 149         new_idx = ray.get(new_idx)
    150         return new_idx[0].append(new_idx[1:]) if len(new_idx) else new_idx
    151 

~/miniconda3/envs/dev/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1377                     worker.core_worker.dump_object_store_memory_usage()
   1378                 if isinstance(value, RayTaskError):
-> 1379                     raise value.as_instanceof_cause()
   1380                 else:
   1381                     raise value

RayTaskError(IndexError): ray::deploy_ray_func() (pid=24407, ip=10.3.69.181)
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 447, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::ModinXGBoostActor.predict() (pid=24492, ip=10.3.69.181)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost_ray.py", line 104, in predict
    return predictions if len(predictions) > 1 else predictions[0]
IndexError: list index out of range 

Have you encountered it ？？？？

**Comment by KangTomwk** [comment]
`bst.predict(dtrain_200w)`

The following error occurred：
2021-05-06 10:45:29,119 INFO xgboost.py:102 -- Prediction started
2021-05-06 10:45:35,366 INFO xgboost_ray.py:378 -- Data preparation time: 6.237504959106445 s
RayTaskError(IndexError)                  Traceback (most recent call last)
 in 
----> 1 bst.predict(dtrain_200w)

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost.py in predict(self, data, nthread, **kwargs)
    111         ), f"Type of data is {type(data)}, but expected {DMatrix}."
    112 
--> 113         result = _predict(self.copy(), data, nthread, **kwargs)
    114         LOGGER.info("Prediction finished")
    115 

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost_ray.py in _predict(booster, data, nthread, **kwargs)
    400     results = [part_res for part_res, _ in results]
    401 
--> 402     result = from_partitions(results, 0).reset_index(drop=True)
    403     LOGGER.info(f"Prediction time: {time.time() - s} s")
    404 

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/distributed/dataframe/pandas/partitions.py in from_partitions(partitions, axis)
    160         )
    161 
--> 162     index = partition_mgr_class.get_indices(0, parts, lambda df: df.axes[0])
    163     columns = partition_mgr_class.get_indices(1, parts, lambda df: df.axes[1])
    164     return DataFrame(

~/miniconda3/envs/dev/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py in get_indices(cls, axis, partitions, index_func)
    147                 else []
    148             )
--> 149         new_idx = ray.get(new_idx)
    150         return new_idx[0].append(new_idx[1:]) if len(new_idx) else new_idx
    151 

~/miniconda3/envs/dev/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1377                     worker.core_worker.dump_object_store_memory_usage()
   1378                 if isinstance(value, RayTaskError):
-> 1379                     raise value.as_instanceof_cause()
   1380                 else:
   1381                     raise value

RayTaskError(IndexError): ray::deploy_ray_func() (pid=24407, ip=10.3.69.181)
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 447, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::ModinXGBoostActor.predict() (pid=24492, ip=10.3.69.181)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/envs/dev/lib/python3.7/site-packages/modin/experimental/xgboost/xgboost_ray.py", line 104, in predict
    return predictions if len(predictions) > 1 else predictions[0]
IndexError: list index out of range

Have you encountered it ？？？？

**Comment by YarShev** [comment]
@KangTomwk , it looks like your prediction result is DataFrame with empty list of columns. To make sure, can you print index/columns here ([link](https://github.com/modin-project/modin/blob/master/modin/engines/ray/pandas_on_ray/frame/partition_manager.py#L149)) after `ray.get(new_idx)` as follows `print(new_idx)`?

**Comment by YarShev** [comment]
@KangTomwk , it looks like your prediction result is empty DataFrame with empty list of index. To make sure, can you print index here ([link](https://github.com/modin-project/modin/blob/master/modin/engines/ray/pandas_on_ray/frame/partition_manager.py#L149)) after `ray.get(new_idx)` as follows `print(new_idx)`?

**Comment by YarShev** [comment]
@KangTomwk , also, print `partitions` in the same place I mentioned above as follows `print(partitions)`.

**Comment by RehanSD** [comment]
Hi @KangTomwk! I'm marking this issue as resolved for now - please feel free to reopen it or open a new one if the issue persists!
