### ISSUE TITLE
PandasQueryCompiler:  Dose it use the modin dataframe algebra to express pandas query?

### ISSUE THREAD

**Issue by panfengfeng** [modin-project/modin#3020]
I am learning the modin' code, and confuesd by the transformation from pandas query to modin dataframe algebra. Does the module-PandasQueryCompiler do this job?

**Comment by devin-petersohn** [comment]
Hi @panfengfeng thanks for the question!

The `PandasQueryCompiler` object serves two main purposes:
1. Map UDFs to the dataframe algebra for a given pandas API
2. Modularly support multiple storage formats

Dataframe algebra relies heavily on UDFs for many operators, and we need a way to map pandas APIs to the algebra + UDF that will result in the correct output. The UDF is tied to the in-memory format, and we want to be able to change that as formats get better.

Take `pandas.DataFrame.count` for example. The query compiler layer maps the UDF for how to actually execute the `count` and the algebraic operator defines that we are executing a `mapreduce` (`mapreduce` is a subset of `reduce` which can be applied in two phases). 

Does this make sense?

**Comment by panfengfeng** [comment]
Thank you very much @devin-petersohn , you give me an good example to understand the "Dataframe algebra relies". I will review the pandas.DataFrame.count

**Comment by panfengfeng** [comment]
another question, I see the code  for example, MapFunction,  and also see MapFunction.register, it registers many pandas.dataframe function, does it mean the modin.dataframe api uses the implementation of pandas.dataframe

**Comment by devin-petersohn** [comment]
@panfengfeng Currently we have some optimization in place, but nothing that is completely holistic. We are working on a project that does this on the University side, stay tuned!

**Comment by RehanSD** [comment]
Hi @panfengfeng - we're currently working on implementing our df algebra #2924, and plan to add optimizations and lazy evaluation after this - please stay tuned for more updates!
