### ISSUE TITLE
Append works slow on omnisci backend

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3038]
Switching to a bunch of pandas on ray significantly speeds up the execution of the script.

```python
from time import time

import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10**6, size=(5000, 5000)))
df2 = DataFrame(np.random.randint(10**6, size=(5000, 5000)))

start = time()
df1.append(df2)._query_compiler._modin_frame._execute()
print(f"append time: {time()-start}")
```

Changed the script to not convert to pandas.

**Comment by anmyachev** [comment]
Same problem with `merge` operation.

**Comment by ienkovich** [comment]
We shouldn't expect OmniSci to be faster in this test. Original `pandas` would execute this operation faster than OmniSci initialization time. With OmniSci we also have data import/export costs and you also convert the result back to `pandas.DataFrame`. That's the reason to have lazy execution for OmniSci engine (to avoid all these overheads per each operation).

**Comment by anmyachev** [comment]
Converting an array to a dataframe is also a lazy operation?
How, in this case, to force the conversion before performing the operation? (to eliminate overhead)

**Comment by ienkovich** [comment]
When you create a dataframe, data is converted to Arrow format. This conversion is not lazy.

**Comment by anmyachev** [comment]
`concat([df1, df2], join="inner", axis=0)._query_compiler._modin_frame._execute()` also works slow.

**Comment by anmyachev** [comment]
@ienkovich this code start OmniSci import?
```python
    df.shape  # to trigger real execution
    df._query_compiler._modin_frame._partitions[0][
        0
    ].frame_id = OmnisciServer().put_arrow_to_omnisci(
        df._query_compiler._modin_frame._partitions[0][0].get()
    )  # to trigger real execution
```

**Comment by ienkovich** [comment]
yes

**Comment by RehanSD** [comment]
Hi @ienkovich and @anmyachev! Is this performance regression still present? Should we assign someone to this?

**Comment by Garra1980** [comment]
@AndreyPavlenko please take a look

**Comment by AndreyPavlenko** [comment]
In my environment, modin is about 2.5 times slower, than pandas and the following warnings are printed:
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
