### ISSUE TITLE
 [OmniSci] concat requiring join is not supported yet

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3042]
Reproducer for `NotImplementedError: concat requiring join is not supported yet` error:
```python

from time import time

import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10, size=(5000, 5000)), columns=[f"col{x}" for x in range(5000)])
df2 = DataFrame(np.random.randint(10, size=(5000, 5000)), columns=[f"col{x}" for x in range(5000)])

start = time()
df1.merge(df2, left_index=True, right_index=True, how="left", sort=False)._query_compiler._modin_frame._execute()
print(f"merge time: {time()-start}")

```

**Comment by anmyachev** [comment]
Same error exist for join operation: `df1.join(df2, how="left", lsuffix="left_", sort=False)._query_compiler._modin_frame._execute()`

**Comment by ienkovich** [comment]
We have two problems here. Firstly, `NotImplementedError` shouldn't be visible to users. In this case, the front-end directly calls `concat` in its `merge`/`join` implementation, and IIRC we wanted to catch `NotImplementedError` in the wrapper used for defaulting to pandas at the back-end level.

Another task is to cover some join cases in our `concat` implementation to support merge by index.
