### ISSUE TITLE
xgboost train appear Task failed: IOError

### ISSUE THREAD

**Issue by KangTomwk** [modin-project/modin#3049]
Hi：

```
train_dtrain = xgb.DMatrix(actual_dfs.drop(["label"], axis = 1),actual_dfs.label)
config = {
    "tree_method": "hist",
    "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()
bst = xgb.train(
    config,
    train_dtrain,
    steps,
    evals=[(train_dtrain, "train")],
    evals_result=evals_result) 
```

I perform xgboost training, the data volume is added to 100W, and the master has been stuck, and the following error appears in the python-core-driver-xxx.log：

task_manager.cc:323: Task failed: IOError: 8: Sent message larger than max (141176840 vs. 104857600): Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=modin.experimental.xgboost.xgboost_ray, class_name=ModinXGBoostActor, function_name=set_train_data, function_hash=}, task_id=b37e32bac24e65b94b070e4001000000, task_name=ModinXGBoostActor.set_train_data(), job_id=01000000, num_args=25602, num_returns=2, actor_task_spec={actor_id=4b070e4001000000, actor_caller_id=ffffffffffffffffffffffff01000000, actor_counter=0}

Has anyone encountered it? ? ? How to solve it? ?

**Comment by KangTomwk** [comment]
Hi:

1、Python versions：3.7.10
2、Training dataset：higgs
3、Additional details for code example.
 ```
 import modin.pandas as pd
 import modin.experimental.xgboost as xgb
 import ray

 ray.init()
 actual_dfs= pd.read_csv("higgs.csv") 
 train_dtrain = xgb.DMatrix(actual_dfs.drop(["label"], axis = 1),actual_dfs.label)
 config = {
    "tree_method": "hist",
    "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()
bst = xgb.train(
    config,
    train_dtrain,
    steps,
    evals=[(train_dtrain, "train")],
    evals_result=evals_result) 
```
4、Ray cluster startup is ray.init(), no parameters are set

**Comment by KangTomwk** [comment]
> Hi @KangTomwk! Thanks for the report!
> 
> For start fixing issue we are needed in more info. Could you please provide more information about:
> 
> 1. python packages versions.
> 2. Your training dataset.
> 3. Additional details for code example.
> 4. Parameters of your Ray cluster.
> 
> Have you any additional traceback of this exception?

Hi:

1、Python versions：3.7.10
2、Training dataset：higgs
3、Additional details for code example.
```
import modin.pandas as pd
import modin.experimental.xgboost as xgb
import ray

ray.init()
actual_dfs= pd.read_csv("higgs.csv") 
train_dtrain = xgb.DMatrix(actual_dfs.drop(["label"], axis = 1),actual_dfs.label)
config = {
   "tree_method": "hist",
   "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()
bst = xgb.train(
   config,
   train_dtrain,
   steps,
   evals=[(train_dtrain, "train")],
   evals_result=evals_result) 
```
4、Ray cluster startup is ray.init(), no parameters are set

**Comment by devin-petersohn** [comment]
@KangTomwk What are your Ray and Modin versions?

**Comment by KangTomwk** [comment]
> @KangTomwk What are your Ray and Modin versions?

Hi

Ray versions：1.1.0
Modin  versions：0.9.1

**Comment by prutskov** [comment]
Thanks @KangTomwk! We'll take a look on this!

**Comment by KangTomwk** [comment]
When the amount of data is 100,000 rows, there is no problem with training. When it reaches 1 million rows, it keeps getting stuck.

**Comment by prutskov** [comment]
Hi @KangTomwk! I run your script using latest Modin cf259f1cd38c70e246fd5e3ea904b675a5d10bd9 and this successfully works for me.
I used Higgs from [UCI archive](https://archive.ics.uci.edu/ml/datasets/HIGGS). Size is 7.5G, shape is 10.999.999 rows x 29 cols.

The script:
```python
import modin.pandas as pd
import modin.experimental.xgboost as xgb
import ray
ray.init()

actual_dfs= pd.read_csv("../HIGGS.csv") 
print(f'Shape: {actual_dfs.shape}')

train_dtrain = xgb.DMatrix(actual_dfs.iloc[:, :-1], actual_dfs.iloc[:,-1])
config = {
   "tree_method": "hist",
   "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()

bst = xgb.train(
   config,
   train_dtrain,
   steps,
   evals=[(train_dtrain, "train")],
   evals_result=evals_result)

print(f'Booster: {bst}')
print(f'evals_result: {evals_result}')
```
Output:
```
Shape: (10999999, 29)
Booster: <modin.experimental.xgboost.xgboost.Booster object at 0x7fb97a3f2d90>
evals_result: {'train': OrderedDict([('logloss', [0.03011]), ('error', [0.040188])])}
```

Could you, please, try again on the latest Modin's master?

**Comment by RehanSD** [comment]
Hi @KangTomwk! Hopefully @prutskov's comment resolves this issue, so I'm marking it as closed. If the issue persists, please feel free to reopen this issue, or to open a new one!
