### ISSUE TITLE
Switch to omnisci from conda-forge

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#3057]
Right now we're relying on OmniSci from [intel/label/modin](https://anaconda.org/intel/omniscidbe4py) Anaconda channel while all other packages required for Modin itself are available in `conda-forge`.

Since https://github.com/conda-forge/omniscidb-feedstock/pull/39 was merged OmniSci is now available in [conda-forge](https://anaconda.org/conda-forge/pyomniscidbe).

We should switch to that channel to use community (and OmniSci themselves) supported version.

**Comment by gshimansky** [comment]
Do we have any other packages in `intel/label/modin` that aren't available in conda-forge? I mean, do we still need to specify `intel/label/modin` at all when building conda environments?

**Comment by vnlitvinov** [comment]
This is probably blocked by https://github.com/intel-ai/omniscidb/issues/167 as agreed with @Garra1980

**Comment by vnlitvinov** [comment]
Closed by #3308.
