### ISSUE TITLE
modin ray.utils not found, attribute error

### ISSUE THREAD

**Issue by prabhant** [modin-project/modin#3059]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Apple M1, BigSur
- **Modin version** (`modin.__version__`):0.9.1
- **Python version**:3.8
- **Code we can use to reproduce**:
```
import modin.pandas as pd
 df = pd.DataFrame()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prabhant/opt/anaconda3/envs/env/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 90, in __init__
    Engine.subscribe(_update_engine)
  File "/Users/prabhant/opt/anaconda3/envs/env/lib/python3.8/site-packages/modin/config/pubsub.py", line 107, in subscribe
    callback(cls)
  File "/Users/prabhant/opt/anaconda3/envs/env/lib/python3.8/site-packages/modin/pandas/__init__.py", line 117, in _update_engine
    initialize_ray()
  File "/Users/prabhant/opt/anaconda3/envs/env/lib/python3.8/site-packages/modin/engines/ray/utils.py", line 143, in initialize_ray
    0.6 * ray.utils.get_system_memory() // 10 ** 9 * 10 ** 9
AttributeError: module 'ray' has no attribute 'utils'
```

### Describe the problem
Seems like the ray.utils does not really exist in ray 1.3.0

```
import ray
ray.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ray' has no attribute 'utils'

```

**Comment by devin-petersohn** [comment]
Hi @prabhant thanks for the report!

What version of ray are you using? And how did you install modin?

**Comment by samueldominguez** [comment]
@devin-petersohn I have the same issue.

Modin version: 0.8.3
Ray version: 1.3.0
Python version: 3.6.9
System: Ubuntu 18.04 WSL2

Installed modin via `pip install modin[ray]`

**Comment by devin-petersohn** [comment]
@samueldominguez You should be able to fix the issue with `pip install ray==1.1`. We haven't released Ray 1.3 support yet, and it looks like they have changed their API.

**Comment by samueldominguez** [comment]
This fixed my issue, thanks Devin.

**Comment by prabhant** [comment]
Hi, I am using ray 1.3 and installed the modin via pip install modin, one more problem was that pip install modin[ray] was not working.

**Comment by samueldominguez** [comment]
@prabhant 

> I am using ray 1.3
as @devin-petersohn mentioned this is not supported yet. I uninstalled modin + ray then installed ray 1.1 separately
via `pip install ray==1.1` then installed modin via `pip install modin`.
>  one more problem was that pip install modin[ray] was not working
what isn't working? can you provide logs?

**Comment by prabhant** [comment]
I get 
zsh: no matches found: modin[ray]

I'm using M1, can it be because of that?

**Comment by devin-petersohn** [comment]
I believe in zsh, you have to wrap the `modin[ray]` in quotes:

```
pip install "modin[ray]"
```

Does that fix the issue?

**Comment by prabhant** [comment]
Seems to be working now, thanks.

**Comment by Garra1980** [comment]
can we close this then?

**Comment by YarShev** [comment]
Yes, we can close this issue.

**Comment by Durgesh-Majeti-Code** [comment]
I am still getting this error. I followed the steps mentioned in the thread. I uninstalled modin and then installed it with ray==1.1 but I still get this error.

**Comment by devin-petersohn** [comment]
@Durgesh-Majeti-Code thanks for commenting, are you able to open a new issue? This is a little bit older of an issue and we don't want to lose track of this!
