### ISSUE TITLE
[HDK] UserWarning: <function DataFrame.join> defaulting to pandas implementation.

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3066]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

```python
import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10**6, size=(50000, 32)), columns=[f"col{x}" for x in range(32)])
df2 = DataFrame(np.random.randint(10**6, size=(50000, 32)), columns=[f"col{x}" for x in range(32)])

print(df1.join(df2, on="col1", how="left", lsuffix="left_", sort=False))
```

**Comment by RehanSD** [comment]
Hi @anmyachev! Does this feature still need to be added to OmniSci?

**Comment by AndreyPavlenko** [comment]
The issue is still reproducible.

**Comment by anmyachev** [comment]
Still defaulting to pandas on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
