### ISSUE TITLE
Freezing when creating a simple DataFrame

### ISSUE THREAD

**Issue by danpetruk** [modin-project/modin#3068]
### System information
- Windows 10
- Modin 0.9.1
- Python 

### Describe the problem

A lot of text appears in the console (see below) and then the process freezes. Wrapping with` if __name__ == '__main__':          freeze_support()` as suggested in the output does indeed help, but shouldn't it work without such wrapping? 

### Source code / logs

```
import modin.pandas as pd
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
print(1)
```

### Console output (too long to be included here):
https://pastebin.com/6xR5rtJR

**Comment by devin-petersohn** [comment]
@danpetruk Thanks for reporting!

The `freeze_support` is a requirement of the Dask executor. I agree that it causes unnecessary pain, but it is something we can't safely work around in Modin.

The Ray executor doesn't require this change, you can install with `pip install modin[ray]`. Let me know if that works for you!

**Comment by devin-petersohn** [comment]
Related to #843

**Comment by danpetruk** [comment]
Thanks, this answers my question
