### ISSUE TITLE
[OmniSci] default index reset with no drop is not supported

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3079]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): e4fa1409d6ee048dcdcafc092a10bdc90d965303
- **Python version**: 3.7.10
- **Code we can use to reproduce**:

```python
import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10**6, size=(10_000, 10)), columns=[f"col{x}" for x in range(10)])
print(df1.reset_index(drop=False))
```

### Source code / logs

```python
Traceback (most recent call last):
  File "benchmarks/test.py", line 8, in <module>
    print(df1.reset_index(drop=False))
  File "modin/pandas/base.py", line 1872, in reset_index
    col_fill=col_fill,
  File "modin/experimental/backends/omnisci/query_compiler.py", line 46, in method_wrapper
    return method(self, *args, **kwargs)
  File "modin/experimental/backends/omnisci/query_compiler.py", line 513, in reset_index
    self._modin_frame.reset_index(drop), shape_hint=shape_hint
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1224, in reset_index
    "default index reset with no drop is not supported"
NotImplementedError: default index reset with no drop is not supported
```

**Comment by AndreyPavlenko** [comment]
Closing as not reproducible. If you could reproduce the issue, please reopen.

**Comment by AndreyPavlenko** [comment]
The code above does not fail, but defaults to Pandas:
UserWarning: default index reset with no drop is not supported is not currently supported by ExperimentalOmnisciOnNative, defaulting to pandas implementation.

**Comment by RehanSD** [comment]
Hi @anmyachev! I'm converting this to a feature request, since it seems this is a new feature that has to be implemented!

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
