### ISSUE TITLE
`read_csv` with OmniSci backend and `parse_dates` parameter works incorrectly

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3081]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): 563f26d
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd
from modin.pandas.test.utils import df_equals

import pandas

test_filename = "test_csv.csv"

data = """col1,col2,col3,col4,col5,col6
0,2000-01-01,0,00:00:00,DJSfUncxsL,3361.303564068564
"""
kwargs = {"parse_dates": ["col4"]}

try:
    with open(test_filename, "w") as f:
        f.write(data)

    df_modin = pd.read_csv(test_filename, **kwargs)
    df_pandas = pandas.read_csv(test_filename, **kwargs)

    df_equals(df_pandas, df_modin)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 494, in <module>
    df_equals(df_pandas, df_modin)
  File "/modin/modin/pandas/test/utils.py", line 534, in df_equals
    check_categorical=False,
  File "/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/_testing.py", line 1716, in assert_frame_equal
    atol=atol,
  File "/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/_testing.py", line 1439, in assert_series_equal
    raise AssertionError(msg)
AssertionError: [datetimelike_compat=True] ['2000-01-01'] is not equal to <DatetimeArray>
['2000-01-01 00:00:00']
Length: 1, dtype: datetime64[ns].
```

**Comment by RehanSD** [comment]
@amyskov is this bug still present on master? Should we assign someone to this?

**Comment by Garra1980** [comment]
@AndreyPavlenko please check this one

**Comment by AndreyPavlenko** [comment]
There are 2 issues:

1. Without parse_dates, modin stores the value as datetime.date, but pandas - as str:
Modin col2: <class 'datetime.date'> 2000-01-01
Pandas col2: <class 'str'> 2000-01-01

2. With parse_dates, the types are the following:
Modin col4: <class 'datetime.time'> 00:00:00
Pandas col4: <class 'pandas._libs.tslibs.timestamps.Timestamp'> 2022-10-12 00:00:00

The first one seems like an issue, but I'm not sure about the second one.

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
