### ISSUE TITLE
Standalone Intel Modin oneContainer for oneContainer Portal

### ISSUE THREAD

**Issue by raoberman** [modin-project/modin#3095]
Add Intel Distribution of Modin container to the oneContainer portal so that Intel oneContainer users can easily find and use Intel Distribution of Modin alongside other Intel AI Kit optimized containers (like TF, AI Kit and SKLearn)

https://software.intel.com/content/www/us/en/develop/tools/containers.html

@aregm

**Comment by mvashishtha** [comment]
@raoberman @Garra1980 @aregm is this still relevant?
