### ISSUE TITLE
Add Intel Distribution of Modin AI Kit Instructions to Modin Installation Documentation 

### ISSUE THREAD

**Issue by raoberman** [modin-project/modin#3096]
Add information on how to install, download Intel Distribution of Modin and its OmniSci backend to the Modin documentation [installation section](https://modin.readthedocs.io/en/latest/installation.html), This way, users have information on all types of Modin installs. Also provide other resources such as the Intel Distribution of Modin page for more information: https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/distribution-of-modin.html#gs.1wcine

@aregm

**Comment by Garra1980** [comment]
Closing as it is covered by #3098
