### ISSUE TITLE
Get rid of propagating `level` parameter to the query compiler for reduction operations

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3102]
`level` parameter for the list of the following operations is handled at the DataFrame API level, however, it's still passed to the QC.
Here is the example for `count` method:
https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L961-L973
If `level` is specified it's processed by grouping on the corresponding level, but even if it isn't specified it's still passed to the `query_compiler.count`.

List of affected methods:
- [`DataFrame.sum`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/dataframe.py#L1679)
- [`DataFrame.prod`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/dataframe.py#L1335)
- [`Series.sum`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/series.py#L1255)
- [`Series.prod`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/series.py#L965)
- [`Base.all`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L664)
- [`Base.any`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L719)
- [`Base.count`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L961)
- [`Base.kurt`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L1423)
- [`Base.mad`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L1475)
- [`Base.max`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L1513)
- [`Base.min`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L1622)
- [`Base._stat_operation`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/pandas/base.py#L1535)

**Comment by anmyachev** [comment]
`level` parameter is no longer used by any of the functions in the list.

@dchigarev pls reopen if I missed something
