### ISSUE TITLE
Documentation broken links

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3114]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version**: 64d6cb064feac23ed5bfa0cba221f35c512c114e
- **Python version**: Any
- **Code we can use to reproduce**:

### Describe the problem

Commit 64d6cb064feac23ed5bfa0cba221f35c512c114e doesn't take into account the most recent changes from https://github.com/modin-project/modin/pull/3030. For example `docs\flow\modin\engines\ray\pandas_on_ray\frame\partition_manager.rst` denotes `PandasOnRayFrameManager` class, while source code class name is `PandasOnRayFramePartitionManager`.

**Comment by amyskov** [comment]
cc @YarShev @prutskov @vnlitvinov

**Comment by YarShev** [comment]
@amyskov , thanks for pointing out! I will take a look. Is that the only issue that you specified?

**Comment by amyskov** [comment]
> @amyskov , thanks for pointing out! I will take a look. Is that the only issue that you specified?

There was another cases, they can be found by examining of warnings that occurs during docs building.

**Comment by YarShev** [comment]
It seems to me all the cases related to this issue are fixed. Please, look at the PR.
