### ISSUE TITLE
Index column named 'Unnamed: 0' on `.to_csv()` after reading DataFrame with `.read_csv()`

### ISSUE THREAD

**Issue by julibeg** [modin-project/modin#3119]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.10
- **Modin version** (`modin.__version__`): 0.9.1
- **Python version**: 3.7.4
- **Code we can use to reproduce**:
```
import numpy as np
import pandas as pd
import os
os.environ["MODIN_ENGINE"] = "ray" 
import modin.pandas as pd2

df1 = pd.DataFrame(np.arange(12).reshape(4, 3), columns=list('abc'),
                   index=[f'i{i}' for i in range(1, 5)])
df2 = pd2.DataFrame(np.arange(12).reshape(4, 3), columns=list('abc'),
                    index=[f'i{i}' for i in range(1, 5)])

df1.to_csv('df1.csv')
df2.to_csv('df2.csv')

df1_re = pd.read_csv('df1.csv', index_col=0)
df2_re = pd2.read_csv('df2.csv', index_col=0)

df1_re.to_csv('df1_re.csv')
df2_re.to_csv('df2_re.csv')
```
This gives 
```
$ head *re*csv
==> df1_re.csv <==
,a,b,c
i1,0,1,2
i2,3,4,5
i3,6,7,8
i4,9,10,11

==> df2_re.csv <==
Unnamed: 0,a,b,c
i1,0,1,2
i2,3,4,5
i3,6,7,8
i4,9,10,11
```

### Describe the problem
After reading a CSV and writing it again the resulting file has `Unnamed: 0` as header of the index column, whereas a file that has been written with pandas does not (compare `df1_re.csv` and `df2_re.csv` after running the example). This only occurs with Ray, while Dask gives ``UserWarning: `to_csv` defaulting to pandas implementation.`` and writes the file as expected.

**Comment by devin-petersohn** [comment]
Thanks @julibeg for the report!

cc @anmyachev

**Comment by anmyachev** [comment]
Some details.

After creating `df2` by the constructor,  `df2` has 1 partition:
```python
    a   b   c
i1  0   1   2
i2  3   4   5
i3  6   7   8
i4  9  10  11
```
After creating `df2_re` by `read_csv`, `df2_re` has 2 partitions:
```python
(Pdb) df2_re._query_compiler._modin_frame._partitions[0][0].to_pandas()
            a  b  c
Unnamed: 0
i1          0  1  2
i2          3  4  5
(Pdb) df2_re._query_compiler._modin_frame._partitions[1][0].to_pandas()
            a   b   c
Unnamed: 0
i3          6   7   8
i4          9  10  11
```

It turns out in some cases that a dataframe created from the same data but in different ways has a different internal representation. Need to understand why.
