### ISSUE TITLE
Dask engine implementation uses private Dask API

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3133]
There are several places where getting the current dask scheduler's client is done by calling the dask's private method [`_get_global_client`](https://github.com/dask/distributed/blob/2c8684701eb3e19a48ef1ef7125ed4f9ccd9d682/distributed/client.py#L101). There is a public version of this method called [`default_client`](https://github.com/dask/distributed/blob/2c8684701eb3e19a48ef1ef7125ed4f9ccd9d682/distributed/client.py#L4487) that should be used instead. Both of these functions return an already active client if there is some, otherwise, they either return None or raise an exception.

We also may use [`get_client`](https://github.com/dask/distributed/blob/2c8684701eb3e19a48ef1ef7125ed4f9ccd9d682/distributed/worker.py#L3383) function instead, which guarantees to return a valid client (in contrast with the two previous ones) because it creates a new one if there is no active client (probably the most appropriate approach).

Files where `_get_global_client` is used:
- `modin/engines/dask/task_wrapper.py`
- `modin/engines/dask/pandas_on_dask/frame/data.py`
- `modin/engines/dask/pandas_on_dask/partition_manager.py`
- `modin/engines/dask/pandas_on_dask/partition.py`

cc @YarShev

**Comment by dchigarev** [comment]
@YarShev should we fix it now if there is upcoming integration with the scaleout-api which will automatically solve this?

**Comment by YarShev** [comment]
@dchigarev , yes, we should fix this now because the integration with the scaleout-api won't solve it in the first stages. Also, we need to use Ray public API (`.options()`) instead of Ray private API (`foo._remote()`) to pass additional arguments like `num_returns` in a remote function. Can you create an issue for this, please?

**Comment by vnlitvinov** [comment]
> We also may use [`get_client`](https://github.com/dask/distributed/blob/2c8684701eb3e19a48ef1ef7125ed4f9ccd9d682/distributed/worker.py#L3383) function instead, which guarantees to return a valid client (in contrast with the two previous ones) because it creates a new one if there is no active client (probably the most appropriate approach).

I don't feel that hiding a case of "hey, we use Dask API and want to talk to a client but nobody's home" is appropriate. We should fail as early as possible when programming something, so errors are not lurking under the rug waiting to bite us when we move around.
