### ISSUE TITLE
Ray engine implementation uses ray's private API

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3135]
Currently, we use private ray's [`._remote()`](https://github.com/ray-project/ray/blob/ca68bf1e931f9091fa1a7f7f42e8740ac3517b3c/python/ray/remote_function.py#L180) function to override the remote function's parameters before its execution:
https://github.com/modin-project/modin/blob/51658b49b54ce89f1277f8b73bdef4cf909e53fd/modin/engines/ray/task_wrapper.py#L65
Ray provides public API to override function's parameters, the same behaviour could be achieved by combination of [`.options()`](https://github.com/ray-project/ray/blob/ca68bf1e931f9091fa1a7f7f42e8740ac3517b3c/python/ray/remote_function.py#L120)  + [`.remote()`](https://github.com/ray-project/ray/blob/ca68bf1e931f9091fa1a7f7f42e8740ac3517b3c/python/ray/remote_function.py#L109-L113) methods.
```python
@ray.remote
def foo(*args, **kwargs):
    return bar(args, kwargs)

# Previous approach:
id1, id2, id3 = foo._remote(args=args, kwargs=kwargs, num_returns=3)

# Proposal:
tuned_foo = foo.options(num_returns=3)
id1, id2, id3 = tuned_foo.remote(*args, **kwargs)
```

Files where `._remote` is used:
- `modin/engines/ray/task_wrapper.py`
- `modin/engines/ray/pandas_on_ray/frame/axis_partition.py`
- `modin/experimental/engines/pandas_on_ray/io_exp.py`
- `modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py`
- `modin/experimental/xgboost/xgboost_ray.py`

**Comment by dchigarev** [comment]
@YarShev do you have more files/cases of using ray's private API on your mind?

**Comment by YarShev** [comment]
@dchigarev , yes, I added some more files to the list at the top of this issue.
