### ISSUE TITLE
Unskip tests with Future version pandas

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3142]
Currently we have problem with tests: test___repr__ - https://github.com/modin-project/modin/blob/master/modin/pandas/test/test_series.py#L501 , test_dtype_empty - https://github.com/modin-project/modin/blob/master/modin/pandas/test/test_series.py#L1539 . 

I found this problem when I was working on #2164.  

These tests creating empty Series. Modin have default type for Series ``object``. But currently Pandas have default type for Series ``float64``. Therefore now tests failed. 

Currently version pandas have next DeprecationWarning:
`` DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.``

More details about this you can see here: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html

Therefore tests will be passed after new version Pandas.

**Comment by YarShev** [comment]
@Rubtsowa , I am not sure that I understand the issue. Example:

```python
import pandas
import modin.pandas as pd
ps = pandas.Series()
Series([], dtype: float64)
ms = pd.Series()
Series([], dtype: float64)
ps.dtypes == ms.dtypes
True
```
Can you elaborate?

Related to #3141 .

**Comment by YarShev** [comment]
@Rubtsowa , what pandas version do you have installed?

**Comment by Rubtsowa** [comment]
@YarShev 1.2.4

**Comment by Rubtsowa** [comment]
This problem occurs when we call dtype. Because the dtype is assigned internally from an empty DataFrame.

**Comment by YarShev** [comment]
[42078](https://github.com/pandas-dev/pandas/issues/42078)

**Comment by Garra1980** [comment]
so what is the plan here then?

**Comment by Garra1980** [comment]
We need to wait Pandas 2.0 for test unskipping

**Comment by RehanSD** [comment]
Hi @Garra1980 @dchigarev @YarShev has this issue been resolved?

**Comment by anmyachev** [comment]
Fixed in https://github.com/modin-project/modin/pull/5995.
