### ISSUE TITLE
Accelerate out of core - maybe using memory mapped file

### ISSUE THREAD

**Issue by nirn1973** [modin-project/modin#3145]
Requesting to accelerate out of core execution, maybe using memory mapped files.

Thanks very much for making Modin happen!

Nir

**Comment by devin-petersohn** [comment]
Hi @nirn1973 thanks for posting!

For my understanding, do you have a problem with the current out of core support in Modin?

**Comment by nirn1973** [comment]
Thx for the prompt response. The issue with the current out of core mode is that the computations become very very slow, making this mode less useful for prototyping, and definitely not fast enough for production.  I am hoping something could be done to accelerate the out of core mode, since it is a common situation.

Thank you,

Nir 


>

**Comment by devin-petersohn** [comment]
Hi Nir, thanks for the extra context. What operations are you running? I agree that it's a common case, did you notice a slowdown recently? We recently (0.10.0 release) updated how out of core is done, so if there's a slowdown for you we should definitely address it.

**Comment by RehanSD** [comment]
Hi @nirn1973! I'm marking this issue as resolved, since it hasn't been updated in a while. If you have any further questions, please feel free to reopen this issue or open a new one!
