### ISSUE TITLE
`ValueError` during initialization of Ray 1.4 in Modin

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3151]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**:  3.8.10
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
df = pd.DataFrame([0])
```

### Describe the problem

During initialization of Ray in Modin `ValueError` is occurred:
```
ValueError: The configured object store size (486.0 GB) exceeds /dev/shm size (405.07611136 GB). This will harm performance. Consider deleting files in /dev/shm or increasing its size with --shm-size in Docker. To ignore this warning, set RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE=1.
```

**Comment by dchigarev** [comment]
Ray verifies object-store size and raises such exception when [`plasma_directory` is not specified](https://github.com/ray-project/ray/blob/90805d302f5950244f346f55d253b926f1b5504f/python/ray/_private/services.py#L1751), in this case, ray assumes `/dev/shm` to be the default plasma directory (on Linux) and compares specified `object_store_size` with the available shared memory.

Modin at the ray initialization uses total available memory to compute default object store size, which appears to be greater than the available shared memory:
https://github.com/modin-project/modin/blob/b8dd3b2f1a1b416d425ecfe49227fefbe1774505/modin/engines/ray/utils.py#L139-L140 
Modin should use `ray._private.utils.get_shared_memory_bytes()` to fill `system_memory` value instead.

### Temporary workaround
Specify a valid `object_store_size` in bytes by `MODIN_MEMORY` environment variable or by explicit ray initialization before using Modin:
```python
import ray
ray.init(object_store_size=STORE_SIZE)

import modn.pandas as pd
...
```
