### ISSUE TITLE
can not support  [pd.Group(key='date',freq='1M') ,pd.Group('ID')]

### ISSUE THREAD

**Issue by KabratKingEstelle** [modin-project/modin#3164]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

**Comment by devin-petersohn** [comment]
Hi @sunshine0123 thanks for the report!

What was the error message that you saw? Did it fail completely or just show a warning?

**Comment by RehanSD** [comment]
Hi @KabratKingEstelle! I'm marking this issue as resolved, since it hasn't been updated in a while. If you have any further questions, please feel free to reopen this issue, or open a new one.
