### ISSUE TITLE
Refactor "check support" IO functions

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3166]
Some IO classes have "check support" functions (for example `modin.engines.base.io.text.csv_dispatcher.CSVDispatcher._read_csv_check_support` and `modin.engines.ray.generic.io.RayIO._to_csv_check_support` functions), which takes IO function arguments and return `bool` indicating whether these arguments are supported or not. Returning of `bool` is not necessary and "not supported" action can be done inside "check supported" function.

**Comment by RehanSD** [comment]
Hi @amyskov! Has this issue been resolved? I know @noloerino put in a PR recently (#4647) that refactors the IO, but I don't know if that resolves this issue!

**Comment by mvashishtha** [comment]
I think #4647 resolved this issue.
