### ISSUE TITLE
Add modin implementation for value_counts()

### ISSUE THREAD

**Issue by bobcolner** [modin-project/modin#3169]
Super useful function for exploring data.

**Comment by YarShev** [comment]
Hi @bobcolner , thanks for the posting! We already have related to this issue #1294 . @dchigarev , any progress there?

**Comment by dchigarev** [comment]
There is a draft PR with `value_counts` implementation (#2730). It's marked as a draft for now because of the failing OmniSci tests there, they're related with the #2856 which is blocking `value_counts` PR and currently in progress.

**Comment by bobcolner** [comment]
anyupdates?
