### ISSUE TITLE
[docs] Willing to accept docs contribution for xgboost_ray?

### ISSUE THREAD

**Issue by richardliaw** [modin-project/modin#3177]
XGBoost Ray supports doing data processing using distributed modin dataframes. 

Would you be willing to take a tutorial/page on your docs to highlight this usage?

https://github.com/ray-project/xgboost_ray#data-sources

cc @krfricke

**Comment by devin-petersohn** [comment]
@richardliaw Yes, we'd be definitely accept a contribution to the docs! I don't see a good place in the existing docs structure, should we add a page for integrations and put it there?

**Comment by RehanSD** [comment]
HI @richardliaw! I'm closing this issue since it hasn't been updated in a while - feel free to reopen it, or open a new one, if you have any further questions!
