### ISSUE TITLE
_modin_frame.fold cannot be called on objects that exist only partially (rest filled with NaNs)

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3178]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.2 LTS

- **Modin version** (`modin.__version__`):

0.10.0+28.g786d64d9

- **Python version**:

Python 3.8.6

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

data = [x for x in range(256)]
s1 = pd.Series(data)
# Make object partly existent
s2 = s1[:2].reindex(s1.index)
s3 = s2.clip(data, data, axis=0)
print(s3)
```

### Describe the problem

Code above raises an exception when `s3` is printed because it gets axis information from only 1 partition because `s2` consists of only 1 partition instead of many like `s1`, the rest don't exist since they are filled with NaNs. Such object `s3` is produced by call `_modin_frame.fold` in `clip`. This bug happens in PR #2803 because `fillna` also uses `fold`.

**Comment by RehanSD** [comment]
Hi @gshimansky! Has this issue been resolved?

**Comment by RehanSD** [comment]
Confirmed that this is resolved on master!
