### ISSUE TITLE
`read_csv` fallbacks to pandas implementation if file path given relative to the home directory

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3180]
Initially was found in the https://github.com/modin-project/modin/issues/3170#issuecomment-866513968.

**Comment by RehanSD** [comment]
@amyskov @mvashishtha has this issue been resolved?

**Comment by mvashishtha** [comment]
No, #4724 is stuck on CI failures.

**Comment by YarShev** [comment]
Closed in #6448.
