### ISSUE TITLE
Make OmniSci engine configurable

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3191]
Currently, there is no way to pass custom launch parameters to the OmniSci backend. All of the Modin engines (Ray and Dask so far) have an option of [explicit initialization](https://modin.readthedocs.io/en/latest/using_modin.html#advanced-usage-experimental), this option is not supported for OmniSci engine though.

Ideally, we want to implement something like this:
```python
import modin.pandas as pd
from dbe import PyDbEngine

# Explicit engine initialization with custom parameters
server = PyDbEngine(enable_watchdog=1)

# Modin is supposed to use the existing instance of the DbEngine
print(pd.DataFrame({"a":[1, 2, 3]}).sum())
```
This approach would work fine for now, because there is always a single one partition, containing a single one OmniSci server, but if we want to scale (for example running on a cluster and so different machines) we *may* need more than one instance of DBEngine, and so the presented approach won't work.

@ienkovich @Garra1980 
so, I have a question, does the future "scaling" suppose to have multiple OmniSci servers, which will cause us to initialize all of them with the custom parameters, or the whole scaling will be handled inside a single OmniSci server and so we can use the above approach?

**Comment by ienkovich** [comment]
We want to have distributed execution with OmniSci eventually. We still don't have any particular plans on how we will do it but we will definitely have multiple OmniSci engine instances.

**Comment by Garra1980** [comment]
@vnlitvinov can we move forward this one as we agreed?

**Comment by vnlitvinov** [comment]
I would say that it needs to at least have a formal `TODO` comment or separate issue created to track adding validation.

**Comment by dchigarev** [comment]
I thought that the next step would be adding some explicit parameters validation at the `pydbe` side, however, I found out that `dbe` already does this, and even prints nice errors:

```python
import sys
sys.setdlopenflags(1 | 256)  # RTLD_LAZY+RTLD_GLOBAL
from dbe import PyDbEngine

server = PyDbEngine(enable_watchdog="invalid_value")
Usage Error: the argument ('invalid-value') for option '--enable-watchdog' is invalid. Valid choices are 'on|off', 'yes|no', '1|0' and 'true|false'
Traceback (most recent call last):
  File "tst.py", line 74, in <module>
    enable_watchdog="invalid_value",
  File "dbe.pyx", line 168, in dbe.PyDbEngine.__cinit__
RuntimeError: DBE paramerameters parsing failed

server = PyDbEngine(invalid_parameter="invalid_value")
Usage Error: unrecognised option '--invalid-parameter'
Traceback (most recent call last):
  File "tst.py", line 75, in <module>
    invalid_parameter=1,
  File "dbe.pyx", line 168, in dbe.PyDbEngine.__cinit__
RuntimeError: DBE paramerameters parsing failed
```
The validation [is done](https://github.com/intel-ai/omniscidb/blob/a48c6a1913a4477250f6ec11af419ebf6204b97e/Embedded/DBEngine.cpp#L128-L131) on the `dbe` side, isn't this is what we wanted to achieve?
