### ISSUE TITLE
Do not pass `None` parameters value to the backend, when it can be replaced by default one

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3195]
For some of the methods (only `DataFrame.sum` was found so far) front-end does not handle default values as appropriate. For example, considering [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html) default value for `skipna` parameter is `True`, however going from the function's signature, if nothing is passed it'll be `None`:
https://github.com/modin-project/modin/blob/b6131c592d2e340269f8647b2a3f021122f49e83/modin/pandas/dataframe.py#L1994-L1997
This `None` is never converted at the API level, so the raw `None` value will be passed to the backend, which causes unnecessary overcomplicating of their work.

**Comment by devin-petersohn** [comment]
Good catch @dchigarev, this will be good to fix.
