### ISSUE TITLE
Ray engine hangs during initialization on WSL1

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3200]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: WSL1 Ubuntu 20.04.2 LTS
- **Modin version** (`modin.__version__`): e633a32c2706f75fbbdf852deace9e3384b31086
- **Python version**: 3.8.10
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
df = pd.DataFrame()
```

### Describe the problem

Problem is in hanging of `ray.init` function on WSL1. Corresponded [issue 16804](https://github.com/ray-project/ray/issues/16804) was created in Ray.

**Comment by RehanSD** [comment]
Hi @prutskov has this issue been resolved?

**Comment by mvashishtha** [comment]
Our CI seem to show ray can start on windows. I'll close this for now.
