### ISSUE TITLE
Pip: no matches found: modin[ray]

### ISSUE THREAD

**Issue by alexlenail** [modin-project/modin#3201]
### System information
- **OSX 11.3 (Big Sur)**:
- **modin-0.10.0**
- **Python 3.7.10**:

### Describe the problem
Can install modin, can't install dependencies using commands from docs. 

### Source code / logs
```
~ » pip install modin[ray] 
zsh: no matches found: modin[ray]
~ » pip install modin[dask]
zsh: no matches found: modin[dask]
~ » pip install modin[all] 
zsh: no matches found: modin[all]
```

**Comment by devin-petersohn** [comment]
Hi @alexlenail thanks for posting!

In zsh, you need to wrap the `modin[ray]` in quotes:

```
pip install "modin[ray]"
```

In the other shells it is not necessary, but maybe we should update the docs to make it copy/paste friendly to zsh users.
