### ISSUE TITLE
Ray Dataset integration

### ISSUE THREAD

**Issue by wuisawesome** [modin-project/modin#3213]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

This is a tracking issue on the Modin side for a Modin <-> Ray Dataset integration. 

The Modin -> Ray Dataset part will probably look like  #2714 and can be done entirely on in the Ray Dataset codebase (by a sufficiently talented Modin engineer 😉).

The Ray Dataset -> Modin portion will require some way to require some way to build a dataframe from a row partitioned dataset.

**Comment by wuisawesome** [comment]
Companion issue: https://github.com/ray-project/ray/issues/16851

cc @devin-petersohn

**Comment by wuisawesome** [comment]
For reference, here is the package reference for datasets: https://docs.ray.io/en/master/data/package-ref.html

**Comment by CansuCandan** [comment]
+++

**Comment by wuisawesome** [comment]
Closed by https://github.com/ray-project/ray/pull/18122
