### ISSUE TITLE
read_csv breaking on 50 GB+ tsv file

### ISSUE THREAD

**Issue by aunell** [modin-project/modin#3224]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version: 0.9.1** (`modin.__version__`):
- **Python version: 3.7.9 Intel Corporation**:
- **Code we can use to reproduce**: Please contact alyssa.unell@intel.com for more information on the code and dataset.

### Describe the problem
When using the read_csv command, modin crashes with a raylet error on a 50 GB+ dataset. When passing in a parameter of nrows=100000 to reduce the amount of data present, the command functions as predicted, but it will break for the whole dataset.

### Source code / logs
Please contact alyssa.unell@intel.com for more information on the code and dataset.

Error output:
(pid=202974) @ 0x55eb6cc7d925 PyEval_EvalCodeEx
(pid=202974) @ 0x55eb6cd2892b PyEval_EvalCode
(pid=202974) @ 0x55eb6cd4c297 run_mod
(pid=202974) @ 0x55eb6cd5714c PyRun_FileExFlags
(pid=202974) @ 0x55eb6cd5732a PyRun_SimpleFileExFlags
(pid=202974) @ 0x55eb6cd578ec pymain_main
(pid=202974) @ 0x55eb6cd57a3c _Py_UnixMain
(pid=202974) @ 0x7f6ed0cc0840 __libc_start_main
(pid=202974) @ 0x55eb6ccbde39 (unknown)
(pid=202600) E0701 12:47:39.776859 202600 204056 core_worker.cc:693] Raylet failed. Shutting down.

**Comment by raoberman** [comment]
@aregm  @gshimansky

**Comment by aunell** [comment]
CURRENTLY PAUSED DUE TO LACK OF MEMORY ON USER'S LOCAL MACHINE

**Comment by devin-petersohn** [comment]
Hi @raoberman @aunell, a 50GB tsv should still be possible with out of core. Can we try again with the latest versions of Modin and Ray?

**Comment by gshimansky** [comment]
Ray often logs cause of failure when a worker dies. Please add `RAY_LOG_LEVEL=DEBUG` and `RAY_BACKEND_LOG_LEVEL=debug` environment variables so that Ray would log even more information. Also, if worker crashes, it is possible to debug it with gdb (adding `RAY_RAYLET_GDB=1 RAY_RAYLET_TMUX=1` to environment) according to Ray debug page https://docs.ray.io/en/master/debugging.html. This way you can get worker stack trace.

**Comment by RehanSD** [comment]
Hi @aunell! I'm marking this issue as resolved since it hasn't been updated in a while! If you have any further questions, please feel free to reopen this issue, or open a new one!
