### ISSUE TITLE
reason: 'utf-8' codec can't decode byte 0xdc in position 339: invalid continuation byte

### ISSUE THREAD

**Issue by paccy-ops** [modin-project/modin#3229]
UnicodeDecodeError: skipped file doc1_UTF-16BE.html in ./venv/lib/python3.9/site-packages/weasyprint/tests/resources (reason: 'utf-8' codec can't decode byte 0xdc in position 339: invalid continuation byte)
xgettext: ./venv/lib/python3.9/site-packages/kombu/asynchronous/aws/connection.py:1: Unknown encoding "utf8". Proceeding with ASCII instead.

**Comment by devin-petersohn** [comment]
Hi @paccy-ops, can you share more about the issue you ran into (and maybe the file?)

**Comment by RehanSD** [comment]
Hi @paccy-ops! I'm marking this issue as resolved since it hasn't been updated in a while! If you have any further questions, please feel free to reopen this issue, or open a new one!
