### ISSUE TITLE
conda install modin issues

### ISSUE THREAD

**Issue by scottschmidl** [modin-project/modin#3241]
Hello All,

I am attempting to install modin with `conda install modin`. When I do it tells me that I have to downgrade my Pandas version to 1.1.4, it's currently 1.3, and I would rather not downgrade. Is there a workaround for this or when will Modin support the up-to-version of Pandas?
Thanks

**Comment by YarShev** [comment]
Hi @scottschmidl , we do not have Modin with pandas 1.3.0 in conda-forge yet. Please, use the latest Modin release 0.10.1 from PyPI.

**Comment by scottschmidl** [comment]
@YarShev there is no issue with inconsistencies use pip? I just want to verify because I know that can be an issue sometimes and I don't want any conflicts with my current running pandas version.
Thanks

**Comment by YarShev** [comment]
@scottschmidl , there shouldn't be any inconsistencies with the latest Modin release 0.10.1 from PyPI because it supports pandas 1.3.0 that you have.

**Comment by scottschmidl** [comment]
Excellent, thank you very much

**Comment by YarShev** [comment]
You're welcome! I'm closing the issue but feel free reopen it again if there are other related questions.
