### ISSUE TITLE
Conflict with pandas

### ISSUE THREAD

**Issue by thistlillo** [modin-project/modin#3253]
I have just installed `modin` (0.10.1) via `pip` (pip-21.1.3) on a machine running `python 3.7`. The command was: `pip install modin[all]`. The installed version of `pandas`  is `1.3.0`.

Installation went fine, but executing `import modin.pandas as pd` I get this error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-8e6f0d266a8b> in <module>
      1 # import bamboolib as bam
      2 import numpy as np
----> 3 import modin.pandas as pd
      4 import pickle
      5 

~/.local/lib/python3.7/site-packages/modin/pandas/__init__.py in <module>
    160 from .. import __version__
    161 from .dataframe import DataFrame
--> 162 from .io import (
    163     read_csv,
    164     read_parquet,

~/.local/lib/python3.7/site-packages/modin/pandas/io.py in <module>
    595 
    596 
--> 597 @_inherit_docstrings(pandas.read_xml)
    598 def read_xml(
    599     path_or_buffer,

/opt/tljh/user/lib/python3.7/site-packages/pandas/__init__.py in __getattr__(name)
    242         return _SparseArray
    243 
--> 244     raise AttributeError(f"module 'pandas' has no attribute '{name}'")
    245 
    246 

AttributeError: module 'pandas' has no attribute 'read_xml'
```
From what I have read, `read_xml` is not available in `pandas` version `1.3`, but it will be available starting with `1.4`. I tried to upgrade `pandas`, but it kept the current version. I could not find any requirement list for `modin`. When installing it, `pip` did not warn about incompatible versions of libraries.

I have searched the set of previous issues and nothing appears concerning this problem. So, my question is: what am I doing wrong? Is there any way I can have `modin` working in my setup?

**Comment by devin-petersohn** [comment]
Hi @thistlillo, `read_xml` was added in pandas `1.3`: https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html.

Can you run the following?
```
import pandas
print(pandas.__version__)
import modin.pandas as pd
print(pd.dataframe.pandas.__version__)
```

This will show your installed pandas version and the version modin is using.

**Comment by thistlillo** [comment]
Then it is trange since the output of the instructions you gave is;

```
1.3.0
1.3.0
```

without any error, by the way.

**Comment by devin-petersohn** [comment]
Yes it is strange, especially since it looks like Modin was imported successfully to run those commands. If you rerun the original issue code does it still error at that line?

**Comment by thistlillo** [comment]
In a fresh notebook, no errors. Sorry for the question, but this is the first time something like this has happened to me.

**Comment by devin-petersohn** [comment]
@thistlillo No problem, glad I could help!
