### ISSUE TITLE
Recommended tips for using modin in production ML systems

### ISSUE THREAD

**Issue by kvsingh1** [modin-project/modin#3260]
Hi,

As I understand, Modin is mostly used as a plug-in library for Data Scientists in their analysis and model building. I am wondering if people have used Modin in production ML systems, and if there are any recommended tips/best practices. I am planning to use Dask as the compute engine to run Modin on.

Thanks.

**Comment by YarShev** [comment]
Hi @kvsingh1 , thanks for posting!

We already have own implementation of distributed XGBoost training and prediction but so far it is only implemented with Ray compute engine. Good start point for you could be reading these pages ([link1](https://modin.readthedocs.io/en/latest/flow/modin/experimental/xgboost.html), [link2](https://modin.readthedocs.io/en/latest/modin_xgboost.html)) in our documentation. Feel free to ask more about it or any other related questions.

**Comment by kvsingh1** [comment]
Hi @YarShev, thanks for your response!

I should have clarified - my question is for the non-modelling aspects of a production ML system. Essentially, just using modin as a replacement for pandas for data preprocessing and feature generation logic. And if people have used Modin as a replacement for pandas in production systems as opposed to interactive jupyter notebooks.

**Comment by YarShev** [comment]
@kvsingh1 , you can do everything (e.g. data validation, data cleaning, data exploration) with Modin in the same way as you interact with pandas only having changed the import statement.

```python
# import pandas as pd
import modin.pandas as pd
```

Does this make sense to you?

**Comment by RehanSD** [comment]
Hi @kvsingh1! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, feel free to reopen this issue, or open a new one!
