### ISSUE TITLE
What's the differences with Mars?

### ISSUE THREAD

**Issue by DonYum** [modin-project/modin#3263]

**Comment by devin-petersohn** [comment]
Hi @DonYum, thanks for the question!

Mars is a project out of Alibaba. They are building a tensor implementation from the ground up to solve some of the needs of their developers. They have a dataframe built on their tensor computing framework.

Modin is a drop-in replacement for pandas. We have developed a core algebra (https://arxiv.org/pdf/2001.00888) that encompasses the entire pandas API. This was a core contribution of my PhD. Modin uses this algebra as a narrow waist. This algebra is able to be used by other systems (even Mars) via the interfaces we have created. This would give other systems the ability to expose the pandas API without having to individually implement everything themselves.

I encourage you to get their point of view as well. Thanks again for the question!

**Comment by DonYum** [comment]
Got it. Thank you for your reply!
BRs!

**Comment by anmyachev** [comment]
@devin-petersohn should we add your comments about Mars to `docs/comparisons` or just close the issue? :)

**Comment by devin-petersohn** [comment]
We can probably close the issue and add later.
