### ISSUE TITLE
Improve "Modin in the Cloud" support ☁️

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#3264]
We have introduced support for "Modin in the Cloud" for automatically spawning a cloud cluster and running a workload in it seamlessly.
The implementation covered only basic codepaths, though, so we need to improve that and handle as much as possible.

Current idea is to first fix as many failing tests as possible in "cloud simulation" approach so we can enable them in the CI.

**Comment by RehanSD** [comment]
@vnlitvinov has this issue been resolved?

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
