### ISSUE TITLE
Aggregate, GroupBy dataframe operations hangs on Modin

### ISSUE THREAD

**Issue by aunell1** [modin-project/modin#3267]
### System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Modin version (modin.__version__): 0.9.1
Python version: 3.7.9 Intel Corporation
Code we can use to reproduce: please contact alyssa.unell@intel.com for more information on the code and the dataset
The code was created as a workaround for bug #3262 

for fold in [7,8,9,10,11,12]:
        px = np.where( tra.dt_day <fold )[0]
        py = np.where( tra.dt_day==fold )[0]
        mn = gf[tar].iloc[px].mean().astype('float32')
        if smooth_method==0:
            te2=gf.iloc[px].groupby(col)[tar].agg('mean')
            te1=gf.iloc[px].groupby(col)[tar].agg('count')
            te=te2
            te=te.to_frame()
            te['smooth'] = (te1*te2)
            te['smooth'] += (mn*1)
            te['smooth'] /= (te1+1)

### Describe the problem
This code runs quickly with stock pandas but hangs on modin with memory consumption.

### Source code / logs
Hangs, never finishes running

**Comment by YarShev** [comment]
Closing the issue because it doesn't persist on master.
