### ISSUE TITLE
is possible to add DataFrame.to_excel function?

### ISSUE THREAD

**Issue by PeterPirog** [modin-project/modin#3269]
Hello
I suggest to add DataFrame.to_excel function in modin.

Peter

**Comment by GeorgeAzaru** [comment]
We definitely need this. Should get prioritized.

**Comment by YarShev** [comment]
cc @devin-petersohn

**Comment by devin-petersohn** [comment]
We will look into this. Excel as a format is not very conducive to distribution access, let alone distributed writes.

I have put an exploration on the roadmap for after this next release.

**Comment by RehanSD** [comment]
Duplicate of #2565
