### ISSUE TITLE
Enable proper debugging in `modin in the cloud`

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3275]
# Problem statement

Some of the tests in the `made in the cloud` mode fall on the remote side. For the debugger to work properly in the console, you need to make additional configuration of the project.

## Instruction manual

1. Clone the repository to the machine: `git clone https://github.com/modin-project/modin`
2. Install the dependencies according to the documentation on the official [website](https://modin.readthedocs.io/en/latest/contributing.html#development-dependencies)
3. Changing the file `modin\\experimental\\cloud\\local_cluster.py`
   1. Find the class `LocalConnection`
   2. Find the method `_run` in this class
   3. Instead of just `return subprocess.Popen(` insert the following construction:

      <details>
         <summary>Lots of code</summary>

         ```py
           if 'distutils' not in str(cmd):
               return subprocess.Popen(
                   cmd,
                   stdin=None,
                   stdout=None,
                   stderr=None,
               )
         ```

      </details>

4. To check that everything is installed as needed and works correctly, you can run a test that exactly works as usual.
   You can check as follows:

    ```shell
        set MODIN_ENGINE=Python
        python -m pytest modin/pandas/test/test_io.py::test_to_dense
    ```

   The test should pass without errors.

5. All further tests will be run in the `model in the cloud` mode. To do this, set the environment variables:

    ```shell
        set MODIN_EXPERIMENTAL=1
        set MODIN_ENGINE=Python
    ```

6. To run the pdb in the `name_test` test (in the place where the exception is thrown) , we can use the command:

    ```shell
        python -m pytest --pdb --simulate-cloud=normal name_test
    ```

7. But point 6 may not always be suitable.
   If we want to stop at a specific line, then we can write the following in it:

   ```py
   import pdb
   pdb.set_trace()
   ```

   To avoid errors from `pdb` , you need to run the test like this:

   ```shell
       python -m pytest --capture=no --simulate-cloud=normal `name_test`
   ```

8. The debugger started at the place where you wrote `pdb. set_trace()`
9. You are great!

# Ideal solution

It should break on remote exceptions just the way it does on local ones when `--pdb` is passed to `pytest`.

**Comment by RehanSD** [comment]
@Lozovskii-Aleksandr has this issue been resolved?

**Comment by YarShev** [comment]
@vnlitvinov, does https://github.com/modin-project/modin/pull/4585 close this issue?

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
