### ISSUE TITLE
Long tests in `test_map_metadata`

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3277]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.8.10 64-bit
- **Code we can use to reproduce**: [notebook](https://github.com/Lozovskii-Aleksandr/modin/blob/cloud_investigated/test_analytics/example_notebook_cmp_duration_test.ipynb)

#### Task

When running the test `modin\\pandas\\test\dataframe\\test_map_metadata.py` in the 'moving in the cloud' mode, it runs for more than 2 hours. This is too much, since in normal mode it runs in less than 10 minutes. It is necessary to find and correct the reasons for such temporary differences. In [this](https://github.com/Lozovskii-Aleksandr/modin/blob/cloud_investigated/test_analytics/example_notebook_cmp_duration_test.ipynb) the notebook shows the logic of how the longest tests were searched for.

#### List of the longest tests

Here I will write out the output of the notebook, which I indicated above.

Top 5 longest tests in `test_map_metadata`:

1. Test: modin/pandas/test/dataframe/test_map_metadata.py::test_applymap[square-float_nan_data]
    Time difference: 58.733764299999976

2. Test: modin/pandas/test/dataframe/test_map_metadata.py::test_applymap_numeric[plus one-float_nan_data]
    Time difference: 56.32550849999994

3. Test: modin/pandas/test/dataframe/test_map_metadata.py::test_applymap[plus one-float_nan_data]
    Time difference: 55.36009379999998

4. Test: modin/pandas/test/dataframe/test_map_metadata.py::test_applymap_numeric[square-float_nan_data]
    Time difference: 54.68688940000002

5. Test: modin/pandas/test/dataframe/test_map_metadata.py::test_at[float_nan_data]
    Time difference: 53.90222800000005

**Comment by RehanSD** [comment]
Hi @Lozovskii-Aleksandr! I tried a few of the tests you list, and they finished pretty fast on my laptop, so I'll mark this issue as resolved! If you notice any further performance regressions,  please feel free to reopen this issue, or open a new one!
