### ISSUE TITLE
Group different errors in "modin in the cloud" and order by frequency

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3279]
### Task

The operability of `modin` is checked using tests. Tests for minimal functionality: `modin\\pandas\\test\\test_io.py`, `modin\\pandas\\test\dataframe\\test_map_metadata.py` and `modin\\pandas\\test\\test_series.py`. In normal mode, the tests work correctly and do not crash. In the `modin in the cloud` mode, these tests give errors. Many of these mistakes are repeated. We will find these errors and find out how often they occur.

### Instructions

To analyze the tests, I wrote the `ParseOutputPytest` module, the full instructions for which are located here: [link](https://github.com/Lozovskii-Aleksandr/modin/tree/cloud_investigated/test_analytics). You can also find links to usage examples there.

The essence of the module is as follows: it runs the specified test and saves information about it in json format. Then it parses the received json, and makes up its 'short error' for each failed test. A 'short error' refers to the last few lines of the full text of the error. In this short error text, the last few lines of the traceback appear, which allow you to understand the essence of the error. Then there is a grouping by a 'short error', where each such error corresponds to a list of tests where this error occurs.

Depending on how many last lines we will consider, we will get a different number of errors. In this notebook, you can see an example of its use [link](https://github.com/Lozovskii-Aleksandr/modin/blob/cloud_investigated/test_analytics/Example/example_notebook_test_minimum.ipynb).

This module can also be used for other tests, it is enough to pass the appropriate parameters to it.

**Comment by Lozovskii-Aleksandr** [comment]
I have received error statistics for tests that are conducted for Windows.

I have collected data in a table that shows the path to the test, how many errors there are in this test, and how many of them are unique. Unique errors are those that match the last 9 lines of the traceback.

<details>
<summary>Table</summary>

| path_to_test                                  | total_error | unique error |
| :-------------------------------------------- | :---------: | :----------: |
| modin/pandas/test/dataframe/test_binary       |     112     |      4       |
| modin/pandas/test/dataframe/test_default      |     381     |      28      |
| modin/pandas/test/dataframe/test_indexing     |    1687     |      25      |
| modin/pandas/test/dataframe/test_iter         |     19      |      8       |
| modin/pandas/test/dataframe/test_join_sort    |    3813     |      5       |
| modin/pandas/test/dataframe/test_map_metadata |     136     |      30      |
| modin/pandas/test/dataframe/test_pickle       |      0      |      0       |
| modin/pandas/test/dataframe/test_reduction    |     478     |      6       |
| modin/pandas/test/dataframe/test_udf          |     149     |      7       |
| modin/pandas/test/dataframe/test_window       |     269     |      7       |
| modin/pandas/test/test_concat                 |     26      |      8       |
| modin/pandas/test/test_general                |     24      |      10      |
| modin/pandas/test/test_groupby                |     148     |      13      |
| modin/pandas/test/test_io                     |     86      |      22      |
| modin/pandas/test/test_reshape                |      5      |      5       |
| modin/pandas/test/test_rolling                |     46      |      8       |
| modin/pandas/test/test_series                 |    1844     |      90      |

</details>

**Comment by Lozovskii-Aleksandr** [comment]
For all the files listed above in the table, I collected errors and wrote them out in order of decreasing frequency of occurrence.

<details>
<summary>List errors</summary>

<details>
<summary>Error: TypeError: __array__() takes 1 positional argument but 2 were given</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3296)

    ======= Remote Traceback =======
    E       self._get_axis(axis).identical(ax)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\indexes\base.py", line 4485, in identical
    E       self.equals(other)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\indexes\multi.py", line 3464, in equals
    E       other_values = algos.take_nd(
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\algorithms.py", line 1708, in take_nd
    E       indexer = ensure_int64(indexer, copy=False)
    E     File "pandas\_libs\algos_common_helper.pxi", line 93, in pandas._libs.algos.ensure_int64
    E   TypeError: __array__() takes 1 positional argument but 2 were given 

Occurs in 2436 tests.

- modin/pandas/test/dataframe/test_indexing.py::test_reset_index_with_multi_index_no_drop[True-0-False-no_col_fill-no_col_level-no_level-True-3-float_nan_data]
- modin/pandas/test/dataframe/test_indexing.py::test_reset_index_with_multi_index_no_drop[True-0-False-no_col_fill-no_col_level-None-True-3-float_nan_data]
- modin/pandas/test/dataframe/test_indexing.py::test_reset_index_with_multi_index_no_drop[True-0-False-no_col_fill-no_col_level-0-True-3-float_nan_data]

And also in 2433 tests.

</details>

<details>
<summary>Error: TypeError: __array__() takes 1 positional argument but 2 were given</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3296)

    ======= Remote Traceback =======
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 355, in _homogenize
    E       val = sanitize_array(
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\construction.py", line 482, in sanitize_array
    E       subarr = maybe_convert_platform(data)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\cast.py", line 112, in maybe_convert_platform
    E       values = construct_1d_object_array_from_listlike(values)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\cast.py", line 1639, in construct_1d_object_array_from_listlike
    E       result[:] = values
    E   TypeError: __array__() takes 1 positional argument but 2 were given 

Occurs in 2305 tests.

- modin/pandas/test/dataframe/test_binary.py::test_math_functions[add-rows-scalar]
- modin/pandas/test/dataframe/test_binary.py::test_math_functions[add-rows-series_or_list]
- modin/pandas/test/dataframe/test_binary.py::test_math_functions[add-columns-scalar]

And also in 2302 tests.

</details>

<details>
<summary>Error: TypeError: __array__() takes 1 positional argument but 2 were given</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3296)

    ======= Remote Traceback =======
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\series.py", line 364, in __init__
    E       data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\construction.py", line 480, in sanitize_array
    E       subarr = _try_cast(data, dtype, copy, raise_cast_failure)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\construction.py", line 598, in _try_cast
    E       subarr = construct_1d_object_array_from_listlike(subarr)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\cast.py", line 1639, in construct_1d_object_array_from_listlike
    E       result[:] = values
    E   TypeError: __array__() takes 1 positional argument but 2 were given

Occurs in 1637 tests.
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_True-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level0,last,first,multiindex_level1-int_data]

And also in 1634 tests.

</details>

<details>
<summary>Error: TypeError: issubclass() arg 1 must be a class</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3280)

    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\_testing.py:744: in _check_types
        assert_attr_equal("dtype", left, right, obj=obj)
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\inference.py:68: in is_number
        return isinstance(obj, (Number, np.number))
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py:98: in __instancecheck__
        return _abc_instancecheck(cls, instance)
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py:102: in __subclasscheck__
        return _abc_subclasscheck(cls, subclass)
    E   TypeError: issubclass() arg 1 must be a class 

Occurs in 1249 tests.

- modin/pandas/test/dataframe/test_binary.py::test_mismatched_row_partitions[idx_not_aligned-ser_ser_same_name-True]
- modin/pandas/test/dataframe/test_binary.py::test_mismatched_row_partitions[idx_not_aligned-ser_ser_same_name-False]
- modin/pandas/test/dataframe/test_binary.py::test_mismatched_row_partitions[idx_not_aligned-ser_ser_different_name-True]

And also in 1246 tests.

</details>

<details>
<summary>Error: AttributeError: 'slice' object has no attribute '__array__'</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3282)

    E   ========= Remote Traceback (1) =========
    E   Traceback (most recent call last):
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
    E       res = self._HANDLERS[handler](self, *args)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
    E       return obj(*args, **dict(kwargs))
    E     File "C:\prog\modin\modin\experimental\cloud\rpyc_proxy.py", line 38, in _pickled_array
    E       return pickle.dumps(obj.__array__())
    E   AttributeError: 'slice' object has no attribute '__array__' 

Occurs in 278 tests.

- modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[add]
- modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[radd]
- modin/pandas/test/dataframe/test_binary.py::test_math_functions_level[sub]

And also in 275 tests.

</details>

<details>
<summary>Error: TypeError: can only be called with ndarray object</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3281)

    E   ========= Remote Traceback (1) =========
    E   Traceback (most recent call last):
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
    E       res = self._HANDLERS[handler](self, *args)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
    E       return obj(*args, **dict(kwargs))
    E   TypeError: can only be called with ndarray object 

Occurs in 265 tests.

- modin/pandas/test/dataframe/test_indexing.py::test_loc[int_data]
- modin/pandas/test/dataframe/test_map_metadata.py::test_at[int_data]
- modin/pandas/test/test_series.py::test___getitem__[int_data]

And also in 262 tests.

</details>

<details>
<summary>Error: TypeError: issubclass() arg 1 must be a class</summary>

    ======= Remote Traceback =======
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\common.py", line 1640, in _is_dtype_type
    E       elif is_list_like(arr_or_dtype):
    E     File "pandas\_libs\lib.pyx", line 1033, in pandas._libs.lib.is_list_like
    E     File "pandas\_libs\lib.pyx", line 1038, in pandas._libs.lib.c_is_list_like
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py", line 98, in __instancecheck__
    E       return _abc_instancecheck(cls, instance)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py", line 102, in __subclasscheck__
    E       return _abc_subclasscheck(cls, subclass)
    E   TypeError: issubclass() arg 1 must be a class

Occurs in 113 tests.

- modin/pandas/test/dataframe/test_default.py::test_shift[0-0-ndarray-int_data]
- modin/pandas/test/dataframe/test_default.py::test_shift[0-0-ndarray-float_nan_data]
- modin/pandas/test/dataframe/test_default.py::test_shift[0-1-ndarray-int_data]

And also in 110 tests.

</details>

<details>
<summary>Error: TypeError: Expected list, got type</summary>

There is already a bug for this problem - [link](https://github.com/modin-project/modin/issues/3284)

    ======= Remote Traceback =======
    E       mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 287, in init_dict
    E       return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 80, in arrays_to_mgr
    E       index = extract_index(arrays)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 382, in extract_index
    E       indexes.append(val.index)
    E     File "pandas\_libs\properties.pyx", line 62, in pandas._libs.properties.AxisProperty.__get__
    E   TypeError: Expected list, got type 

Occurs in 55 tests.

- modin/pandas/test/dataframe/test_window.py::test_frame_fillna_limit[1-int_data]
- modin/pandas/test/dataframe/test_window.py::test_frame_fillna_limit[1-float_nan_data]
- modin/pandas/test/dataframe/test_window.py::test_frame_fillna_limit[2-int_data]

And also in 52 tests.

</details>

<details>
<summary>Error: TypeError: __array__() takes 1 positional argument but 2 were given</summary>

    modin\pandas\test\utils.py:527: in df_equals
        assert_frame_equal(
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\_testing.py:756: in _get_ilevel_values
        filled = take_1d(unique._values, level_codes, fill_value=unique._na_value)
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\algorithms.py:1708: in take_nd
        indexer = ensure_int64(indexer, copy=False)
    pandas\_libs\algos_common_helper.pxi:93: in pandas._libs.algos.ensure_int64
        ???
    E   TypeError: __array__() takes 1 positional argument but 2 were given 

Occurs in 53 tests.

- modin/pandas/test/dataframe/test_default.py::test_pivot[<lambda>1-<lambda>-None-int_data]
- modin/pandas/test/dataframe/test_default.py::test_pivot[None-<lambda>-None-int_data]
- modin/pandas/test/dataframe/test_default.py::test_pivot_table_data[<lambda>1-<lambda>0-<lambda>0-int_data]

And also in 50 tests.

</details>

<details>
<summary>Error: ValueError: object __array__ method not producing an array</summary>

    ======= Remote Traceback =======
    E       new_modin_frame = self._modin_frame.mask(col_indices=key)
    E     File "C:\prog\modin\modin\engines\base\frame\data.py", line 495, in mask
    E       col_partitions_list = self._get_dict_of_block_index(1, col_numeric_idx)
    E     File "C:\prog\modin\modin\engines\base\frame\data.py", line 986, in _get_dict_of_block_index
    E       indices = np.sort(
    E     File "<__array_function__ internals>", line 5, in sort
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\numpy\core\fromnumeric.py", line 997, in sort
    E       a = asanyarray(a).copy(order="K")
    E   ValueError: object __array__ method not producing an array 

Occurs in 53 tests.

- modin/pandas/test/test_groupby.py::test_mixed_dtypes_groupby[True]
- modin/pandas/test/test_groupby.py::test_mixed_dtypes_groupby[False]
- modin/pandas/test/test_groupby.py::test_simple_row_groupby[True-True-col1]

And also in 50 tests.

</details>

**Comment by RehanSD** [comment]
Hi @Lozovskii-Aleksandr @vnlitvinov has this issue been resolved?

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
