### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3280]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.8.10 64-bit
- **Code we can use to reproduce**:

To run the test, clone the repository, install the dependencies, activate the installed virtual environment, and run the command:

```shell
  set MODIN_EXPERIMENTAL=1
  set MODIN_ENGINE=Python
  python -m pytest --simulate-cloud=normal modin/pandas/test/test_series.py::test_callable_key_in_getitem[int_data]
```

### Describe the problem

Occurs in 1055 tests.
     modin/pandas/test/test_series.py::test_callable_key_in_getitem[int_data]
     modin/pandas/test/test_series.py::test_callable_key_in_getitem[float_nan_data]
     modin/pandas/test/test_series.py::test_T[int_data]
And also in 1052 tests.

### Source code / logs

Part's traceback:

```shell
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\_testing.py:744: in _check_types
        assert_attr_equal("dtype", left, right, obj=obj)
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\inference.py:68: in is_number
        return isinstance(obj, (Number, np.number))
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py:98: in __instancecheck__
        return _abc_instancecheck(cls, instance)
    C:\Users\alozovsk\Anaconda3\envs\modin\lib\abc.py:102: in __subclasscheck__
        return _abc_subclasscheck(cls, subclass)
    E   TypeError: issubclass() arg 1 must be a class
```

**Comment by RehanSD** [comment]
Hi @Lozovskii-Aleksandr @vnlitvinov has this issue been resolved?

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
