### ISSUE TITLE
TypeError: can only be called with ndarray object

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3281]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.8.10 64-bit
- **Code we can use to reproduce**:

To run the test, clone the repository, install the dependencies, activate the installed virtual environment, and run the command:

```shell
  set MODIN_EXPERIMENTAL=1
  set MODIN_ENGINE=Python
  python -m pytest --simulate-cloud=normal modin/pandas/test/test_series.py::test___getitem__[int_data]
```

### Describe the problem

Occurs in 264 tests.
     modin/pandas/test/test_series.py::test___getitem__[int_data]
     modin/pandas/test/test_series.py::test_agg[sum-int_data]
     modin/pandas/test/test_series.py::test_aggregate[sum-int_data]
And also in 261 tests.

### Source code / logs

Part's traceback:

```shell
    E   ========= Remote Traceback (1) =========
    E   Traceback (most recent call last):
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
    E       res = self._HANDLERS[handler](self, *args)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
    E       return obj(*args, **dict(kwargs))
    E   TypeError: can only be called with ndarray object
    ```

**Comment by RehanSD** [comment]
Hi @Lozovskii-Aleksandr @vnlitvinov has this issue been resolved?

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
