### ISSUE TITLE
TypeError: Expected list, got type

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3284]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.8.10 64-bit
- **Code we can use to reproduce**:

To run the test, clone the repository, install the dependencies, activate the installed virtual environment, and run the command:

```shell
  set MODIN_EXPERIMENTAL=1
  set MODIN_ENGINE=Python
  python -m pytest --simulate-cloud=normal modin/pandas/test/test_io.py::TestCsv::test_series_to_csv
```

### Describe the problem

Occurs in 43 tests.
     modin/pandas/test/test_io.py::TestCsv::test_series_to_csv
     modin/pandas/test/test_series.py::test_fillna[None-None-int_data]
     modin/pandas/test/test_series.py::test_fillna[None-None-float_nan_data]
And also in 40 tests.

### Source code / logs

Part's traceback:

```shell
    ======= Remote Traceback =======
    ...
    E       mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 287, in init_dict
    E       return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 80, in arrays_to_mgr
    E       index = extract_index(arrays)
    E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\internals\construction.py", line 382, in extract_index
    E       indexes.append(val.index)
    E     File "pandas\_libs\properties.pyx", line 62, in pandas._libs.properties.AxisProperty.__get__
    E   TypeError: Expected list, got type
```

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
