### ISSUE TITLE
Converting Modin dataframe to Pandas in a more time efficient way

### ISSUE THREAD

**Issue by si-maleki** [modin-project/modin#3293]
I regularly read files larger than 30GB, and spend a lot of time waiting for read_csv. I'm looking to use Modin to speed this up, while using Pandas for the remaining tasks (see footnote for reason). I am finding that while modin.read_csv is incredibly quick,  applying ._to_pandas() takes almost as long as pandas.read_csv.

Is there a more efficient way to convert Modin dataframes to Pandas than ._to_pandas()? My understanding is that Modin would perform this conversion 'under the hood' when a Pandas command that is not yet supported/accelerated by Modin is run, so I would assume that a more efficient way exists. 

Footnote: I am looking to use Modin in parallel to Pandas, and only for the most time-consuming tasks, primarily because I ran into some errors when running my scripts using Modin (e.g. more specific functions such as pd.PeriodIndex). Am I missing something?

**Comment by YarShev** [comment]
Hi, @si-maleki , thanks for the question! Yes, you are correct on that if a pandas operation is not yet supported, Modin calls `._to_pandas` that is currently poor on the performance. We have some issues to accelerate it (#2814, #2815, #2818). Let us know if you also have thoughts on how it can be improved. As a workaround you can try the following way: 1) materialize all the partitions with `ray.get` or `dask_client.gather` at once, 2) concatenate them in an appropriate way, 3) call a pandas op.

Currently, `pd.PeriodIndex` is provided by Modin in the same form as it comes from pandas.

**Comment by devin-petersohn** [comment]
Just to add to what @YarShev  said:

>Footnote: I am looking to use Modin in parallel to Pandas, and only for the most time-consuming tasks, primarily because I ran into some errors when running my scripts using Modin (e.g. more specific functions such as pd.PeriodIndex). Am I missing something?

This sounds like a bug. Would you open an issue for anything that errors in Modin but usually works in pandas? That would help us out a lot!

**Comment by RehanSD** [comment]
Hi @si-maleki! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!
