### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by santhosh2410** [modin-project/modin#3294]
how to dynamically get column from dataset into individual dataframe.  Example if my dataset contains id,name,age and address  and  i create a list containing column names. if i pass the list to an for loop and it have check the column in the list and column name in the dataframe if it matches then it have concat that into the empty dataframe created for it.

eg:
 l =[age,address]

age = pd.Dataframe()
address = pd.DataFrame()
for i in l:
filtered = df[[i]]

into the respective dataframes

thanks in advance

**Comment by YarShev** [comment]
Hi @santhosh2410 , If I correctly understand your question, you should probably do as follows:

```python
cols = ["age", "address"]
df_age = pd.DataFrame([], columns=["age"])
df_address = pd.DataFrame([], columns=["address"])
for c in cols:
    if c in df_age.columns:
        df_age[c] = df[c]
    elif c in df_address.columns:
        df_address[c] = df[c]
```
Let me know if this is what you try to achieve.

**Comment by devin-petersohn** [comment]
@santhosh2410 do you mind changing the name of the issue to something that is easily searchable related to the question?

To answer your question, generally you want to concat everything at once, so something like:

```
l =[age,address]

age = pd.Dataframe()
address = pd.DataFrame()

final_age_df = pd.concat([d for d in l if all(d.columns in age.columns)])
final_address_df = pd.concat([d for d in l if all(d.columns in address.columns)])
```

**Comment by santhosh2410** [comment]
@YarShev @devin-petersohn thank you so much

**Comment by anmyachev** [comment]
@santhosh2410 feel free to reopen issue if needed.
