### ISSUE TITLE
Modin resample error

### ISSUE THREAD

**Issue by kocmurat93** [modin-project/modin#3303]
hi ,
i used resample method with ray modin and ı got error that was TypeError: ‘Resampler’ object is not subscriptable .  My code works with pandas .
my code is :
team_md.resample(‘3T’)[[‘Value’]].mean()
how can i solve this ?

thanks ! 

Murat KOÇ
Machine Learning Engineer

**Comment by prutskov** [comment]
Hi, @kocmurat93!
Thank you for the report. Looks like `Resampler` object hasn't `__getitem__` method, that's reason of your issue. This is bug and we will fix that.

**Comment by kocmurat93** [comment]
hi @prutskov ,

We would like to help you to fix the bug in order to speed up the process . Our team can fix this bug.

**Comment by prutskov** [comment]
@kocmurat93 it would be great! Before creating of corresponded PR, please, note about our [contributing guidelines](https://modin.readthedocs.io/en/latest/contributing.html).

**Comment by dikuchan** [comment]
Hi! What's the current status of the issue? I may try to fix the bug if it's not that complex.

**Comment by devin-petersohn** [comment]
@dikuchan Please feel free to make the change, it is fairly straightforward. 

@prutskov Are you able to assist here as well?

**Comment by prutskov** [comment]
@devin-petersohn Yes, sure, I'll help.
@dikuchan If you have any questions feel free to ask! Note about our [contributing guidelines](https://modin.readthedocs.io/en/latest/contributing.html).
