### ISSUE TITLE
Rolling Error

### ISSUE THREAD

**Issue by kocmurat93** [modin-project/modin#3328]
hi , 

rolling calculation works correctly pandas and ı tested it on modin , it doesnt work and i got error:

error : positional indexers are out-of-bounds.

can you fix this problem ? 

thanks ! 

Murat KOÇ 

![dd](https://user-images.githubusercontent.com/16020575/128608334-f9b9c6dd-74aa-48be-a5cf-3d68e67fe1f9.jpg)

**Comment by prutskov** [comment]
Hi, @kocmurat93!

Could you, please, attach a reproducer of the problem? It would be helpful to know about your `team_md` (shape, index, columns)

**Comment by mvashishtha** [comment]
@kocmurat93 since we haven't heard from you in a long time, I'm going to close this issue. Please respond here if you still have concerns.
