### ISSUE TITLE
Modin ray shows error on pd.read_parquet

### ISSUE THREAD

**Issue by reza1615** [modin-project/modin#3333]
modin version 0.10.0
I could open this parquet file with pandas and it only show this erro when i import modin.
os: ubuntu 20.04
error
![image](https://user-images.githubusercontent.com/2202483/128868834-96bbece8-9306-4fd0-8716-a26cb29527e1.png)

**Comment by devin-petersohn** [comment]
Hi @reza1615, thanks for the report!

How many columns are in this dataset? Are you able to share the file?

**Comment by mvashishtha** [comment]
@reza1615 I'm closing this issue because you haven't provided more information. Please comment here if you still have concerns.
