### ISSUE TITLE
how to get specified index and row values if match is not found

### ISSUE THREAD

**Issue by santhosh2410** [modin-project/modin#3347]
In the code below I'm checking the matching column values in another column and assign its to a variable and if the match is found I need to get that particular index position value and save it as text file.

```python
import re
for i in df['parent'].unique():
    with open('out.txt', 'a') as f:
        f.writelines(i+"\n")
    for j in df['child'].reset_index().iterrows():`
        index = j[0]
        al = j[1][1]
        if re.search(al,i):
            record = df[index] #I need to get value of the index variable here
            with open('out.txt', 'a') as f:
                f.writelines(str(index) +" "+ record)
```

**Comment by YarShev** [comment]
Hi @santhosh2410 , thanks for your question! I edited your example a bit for readability. You need to make minor changes in the example:

```python
import re
for idx, i in enumerate(df['parent'].unique()): # here!!!
    with open('out.txt', 'a') as f:
        f.writelines(i+"\n")
    for j in df['child'].reset_index().iterrows():`
        index = j[0]
        al = j[1][1]
        if re.search(al,i):
            record = df.index[idx] # Here!!! I need to get value of the index variable here
            with open('out.txt', 'a') as f:
                f.writelines(str(index) +" "+ record)
```

Does this make sense?

**Comment by santhosh2410** [comment]
hi @YarShev can help in this code to get non matching value

**Comment by YarShev** [comment]
@santhosh2410 , you only need to change the line `if re.search(al,i):` to `if not re.search(al,i):`.

**Comment by mvashishtha** [comment]
@santhosh2410 I'm closing this issue because it's been a long time since the last update. Please comment here if you still have any concerns.
