### ISSUE TITLE
[Ray Cluster] A crash problem occurred when using modin to process large data sets on the ray cluster

### ISSUE THREAD

**Issue by youthmrg** [modin-project/modin#3351]
# Problem description
- ray 1.4.1
- modin 0.10.0

I used Kubernetes to build a Ray cluster with 10 nodes, and tried to use modin to process large-scale data sets on the cluster, but encountered an inexplicable crash problem. I don't understand, is this a modin problem or a ray problem?

<img width="1235" alt="image-20210819092954517" src="https://user-images.githubusercontent.com/42192409/129993493-ffaabcd2-d84d-425c-b742-e651907ccdec.png">

The configuration of the cluster is as follows. I believe that this configuration can theoretically handle this data set.
| Node Type | Number of Nodes | CPU  | Memory | Plasma |
| --------- | --------------- | ---- | ------ | ------ |
| Head      | 1               | 8    | 16 GB  | 9 GB   |
| Worker    | 10              | 8    | 16 GB  | 9 GB   |

If part of the data set is used, it can run successfully. But using all the data sets, the above error occurred. No overflow was observed on the ray dashboard. It seems that the crash happened suddenly for no reason.

**Comment by YarShev** [comment]
@youthmrg , thanks for the report! It seems to me there are no enough resources in your cluster nodes to process the data.

cc @modin-project/modin-ray , any comments?

**Comment by YarShev** [comment]
@youthmrg , how much large your data is? And also, could you try installing Modin 0.10.1 or from sources ([installing instruction](https://modin.readthedocs.io/en/latest/installation.html)) to see if the issue persists?

**Comment by youthmrg** [comment]
@YarShev The size of the dataset has 10 million rows and 41 columns, and the disk occupies about 3GB in the PostgreSQL database. This is a small dataset for testing, but this error has already occurred

**Comment by mvashishtha** [comment]
I assume https://github.com/ray-project/ray/pull/17234 fixed this issue because it's quite old and no one else has commented here. @briancpark please comment here if you need more help.
