### ISSUE TITLE
Doc error on the comparison page - Dask does support a `quantile` method (albeit approximate)

### ISSUE THREAD

**Issue by ianozsvald** [modin-project/modin#3354]
On https://modin.readthedocs.io/en/latest/comparisons/dask.html you note `Dask is currently missing multiple APIs from pandas that Modin has implemented. Of note: Dask does not implement iloc, MultiIndex, apply(axis=0), quantile, median, and more`.

Dask has a `quantile` method for both `Series` and `DataFrame`: https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.quantile.html . I'd suggest either removing "quantile" from that sentence or maybe noting that only an approximate quantile is available.

I agree that an exact `median` is not supported, nor is that likely. 

The approximate `quantile` method has been improved (details for the morbid: https://github.com/dask/dask/pull/3819#issuecomment-410063014 ), the current default has better error characteristics than from several years back and a newer `tdigest` options allows for error guarantees.

**Comment by YarShev** [comment]
Hi @ianozsvald , thanks for the notice! We'll definitely correct this.
