### ISSUE TITLE
Ray Dataset convert to Modin Dataframe

### ISSUE THREAD

**Issue by CansuCandan** [modin-project/modin#3366]
Hi,

We read data from HDFS using Ray Dataframe. Our aim is convert Ray dataframe to Modin dataframe but `ds.to_modin() ` is not exist. Can you help us?

Thank you!

**Comment by devin-petersohn** [comment]
Hi @CansuCandan, thanks for posting!

We have an open issue tracking this #3213. Would you be ok to move the conversation there? It will help keep the conversations targeted.

**Comment by devin-petersohn** [comment]
Closing as duplicate of #3213
