### ISSUE TITLE
Do not pin pandas down to patch level

### ISSUE THREAD

**Issue by h-vetinari** [modin-project/modin#3371]
From https://github.com/conda-forge/modin-feedstock/pull/21:

> > @h-vetinari: Regarding the pandas pin, I understand that it is tempting to pin against the exact version being tested, but it is not scalable (what if another library pins to pandas 1.3.1, then skips to 1.3.3 in the next update?, etc). Pandas follows SemVer pretty strictly (so even minor-releases should stay fully backward compatible), and IMO pinning down to patch-level is an antipattern that should be removed upstream.
> 
> @devin-petersohn: Understandable, would you open an issue to discuss this on the Modin repo?

Xref #3369

**Comment by gshimansky** [comment]
These are PRs that updated pandas 1.3.0->1.3.1: https://github.com/modin-project/modin/pull/3290 and 1.3.1->1.3.2: https://github.com/modin-project/modin/pull/3343. There were some functional changes and changes in tests. Making sure that modin code works with all 1.3.x may require making it more flexible and running CI testing for all of the pandas patch-level releases.

**Comment by h-vetinari** [comment]
Fair enough, where there are actual pandas-bugs that affect the test suite, patch releases make a "difference". I put this in quotes, because most times, the failing tests are just skipped or worked around, so mostly the test suite was just _pretending_ to be compatible.

In any case, I think the `least` that should be done is to leave the pin open, i.e. `pandas>=1.3.2`. And I'm not even speaking about the `environment_dev.yml` here, but about the packaging in conda-forge.

**Comment by RehanSD** [comment]
Hi @gshimansky @h-vetinari @vnlitvinov and @devin-petersohn has this issue been resolved?

**Comment by h-vetinari** [comment]
No this issue has not been resolved. Modin [still](https://github.com/modin-project/modin/blob/0.17.0/setup.py#L5) [pins](https://github.com/modin-project/modin/blob/0.17.0/environment-dev.yml#L5) pins pandas down to patch level.

**Comment by h-vetinari** [comment]
> We will need CI to test all Pandas patchlevel version in a range individually to make sure that they all work, not the latest one, e.g. 1.3.0, 1.3.1, 1.3.2, etc.

This is overkill and not scalable (especially for a library/framework). You are not responsible for pandas-bugs, _pandas_ is (and your users should be free to have the bugs in pandas fixed independently of which version you test in CI; if pandas releases a new patch release tomorrow, you're actively preventing your users from getting those fixes, because you claim you need to vet them for them first, which is paternalistic at best).

A more reasonable approach (more coverage, less CI jobs) would be to test against pandas `1.{x=current}.{z=latest for x}` and `1.{y=current-1}.{z=latest for y}`, and carry a dependency of `pandas >=1.4,<1.6` (since x=5 ATM). And that's _already_ a POV that distrusts pandas (and robs users of their agency), since pandas promises SemVer stability (and so even new minor releases should be fine), but that at least would be a more reasonable trade-off between (actual) stability and intrusiveness, because the API surface can change a fair bit between minor releases.

Still, realistically no-one is going to _want_ to use 1.5.1 if 1.5.3 is available. If they so choose regardless, then they should be free to ~keep the pieces~ live with the minimal fallout, since modin gets tested (and made compatible) reasonably quickly against whatever is the newest pandas (patch) version - "consenting adults" and all that. The upshot is that not pinning so hard is what would allow modin to live peacefully alongside other libraries and their dependencies (which it currently doesn't), without creating a monstrous CI matrix here.

**Comment by mvashishtha** [comment]
@h-vetinari I agree with you and we have consensus from a few modin contributors (including @vnlitvinov and @devin-petersohn offline) that we should stop pinning to patch version. So I think at this point we're ready for a PR.

**Comment by vnlitvinov** [comment]
I wonder if just running with `>=1.5.3` would work for now, it seems to be the minimal change (and would allow users to upgrade), or should we just state `>=1.5,<1.6`? opinions @h-vetinari @devin-petersohn

**Comment by h-vetinari** [comment]
1.5.3 doesn't exist yet, I just used that version to make my point.

I'd still prefer to just specify pandas down to only the minor version, but even so, `>=1.5.1,<1.6` would be an improvement (though somewhat marginal; covering 1.4 and/or 1.6.dev would be much more substantial - though to be sure I'd already be much happier with the mentioned loosening)

**Comment by vnlitvinov** [comment]
Loosening the requirements to `>=1.4,<1.7` (this seems to be what you're asking for) would most likely require us to do some amount of compatibility code, as we're using some internal functions (yes, we shouldn't, but, as we're trying to mimic pandas API 100%, it's usually better to use some internal function than to copy-paste its whole body), and some interfaces diverge a little (an example would be changing the default value of some parameter from `None` to `no_default`).

**Comment by h-vetinari** [comment]
Fair enough if supporting more than one pandas minor version is too much effort for now (considering how closely modin sticks to pandas); again, `>=1.5.1,<1.6` would already be an improvement.

**Comment by devin-petersohn** [comment]
At some point we have made some backwards progress on this. I agree with what has been said here and propose the following concrete steps:

* Loosen the requirements as @h-vetinari mentions `>=1.5.1,<1.6` (is 1.5.0 a problem?)
* Take out the exception for pandas version compatibility and change it back to a warning (this probably shouldn't have been changed)
* Consider loosening the pin even more (`>=1.0`?) and just stick with the warning, letting users choose to upgrade (or not)
