### ISSUE TITLE
TypeError: '>=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3379]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.2
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

```shell
set MODIN_EXPERIMENTAL=1
python -m pytest modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level0-int_data]
```

### Describe the problem

This is the only test file that does not work among all the tests modin for windows.

Occurs in 1296 tests.

- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level0-float_nan_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level1,multiindex_level0-float_nan_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_columns_int-multiindex_level0,last,first,multiindex_level1-int_data]

And also in 1291 tests.

### Source code / logs

<details>
<summary>Traceback</summary>

```shell
modin\pandas\test\utils.py:705: in eval_general
    values = execute_callable(
modin\pandas\test\utils.py:684: in execute_callable
    md_result = fn(modin_df, **md_kwargs)
modin\pandas\test\dataframe\test_join_sort.py:486: in <lambda>
    lambda df: df.sort_values(
modin\pandas\base.py:2409: in sort_values
    result = self._query_compiler.sort_columns_by_row_values(
modin\backends\pandas\query_compiler.py:3145: in sort_columns_by_row_values
    broadcast_value_list = [
modin\backends\pandas\query_compiler.py:3145: in <listcomp>
    broadcast_value_list = [
modin\backends\pandas\query_compiler.py:2166: in getitem_row_array
    return self.__constructor__(self._modin_frame.mask(row_numeric_idx=key))
modin\engines\base\frame\data.py:469: in mask
    row_partitions_list = self._get_dict_of_block_index(0, row_numeric_idx)
modin\engines\base\frame\data.py:987: in _get_dict_of_block_index
    [i if i >= 0 else max(0, len(self.axes[axis]) + i) for i in indices]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x0000014AEADDC2E0>

>       [i if i >= 0 else max(0, len(self.axes[axis]) + i) for i in indices]
    )
E   TypeError: '>=' not supported between instances of 'str' and 'int'
```

</details>

**Comment by RehanSD** [comment]
Hi @Lozovskii-Aleksandr has this issue been resolved?

**Comment by mvashishtha** [comment]
@RehanSD at version 88f7b27d32b099c508e93251cafe503f2908d426, all of test_sort_values passes when we have `MODIN_EXPERIMENTAL=1`. So I think we can close this.
