### ISSUE TITLE
Problems with current modin docker examples

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3392]
1. Executable scripts build*.sh are not executable.
2. If HTTP(S) proxy is used during build, environment variables remain to be set in the container image. If this image is uploaded to a Docker Hub, and is used by someone else, they will get proxy settings that were used during build. These proxy variables have to be cleared at the end of docker build script.
3. There is no need to create separate containers for different benchmarks. One container can encompass all of them.
4. Conda environment may be activated without use of login shell for everything (it is slow).
5. Need to add modin on ray examples in container.

**Comment by devin-petersohn** [comment]
@anmyachev This was closed, but I see @gshimansky is still making progress in his fork. Were all the necessary changes merged?

**Comment by gshimansky** [comment]
I think all changes were merged. I didn't do any pushes after https://github.com/gshimansky/modin/commit/24aa552dd4c84f8bb4859389c28e147beee41d06 and it was merged.
