### ISSUE TITLE
[OmniSci] Make codegen in OmniSci more friendly for Series processing

### ISSUE THREAD

**Issue by ienkovich** [modin-project/modin#3406]
Currently, rows processing loop has (supposedly) unnecessary memory accesses. This causes a significant overhead when row size is quite small (e.g. binary operation for Series). We should investigate why all those memory accesses exist and try to remove them (completely remove or move out of the loop).

**Comment by Garra1980** [comment]
Let's track this here - https://github.com/intel-ai/omniscidb/issues/176
