### ISSUE TITLE
ASV: all shapes should be of list type

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3407]
There are two ways to define shapes, by default through a dictionary or through a `json` file. Due to the fact that the `json` format does not support the use of `tuples`, we have to use the `list` type. But since in both cases the hash from the benchmark source code is considered and it must be the same, then the `list` type must also be used in dictionaries.

Here the shape are of `tuple` type: https://github.com/modin-project/modin/blob/600fa2632973167176333cb03c8a8c3b278be4ca/asv_bench/benchmarks/utils/data_shapes.py#L50
https://github.com/modin-project/modin/blob/600fa2632973167176333cb03c8a8c3b278be4ca/asv_bench/benchmarks/utils/data_shapes.py#L53

**Comment by vnlitvinov** [comment]
I would suggest measuring the hash by converting to a predictable string (e.g. using `hash(json.dumps(obj, sort_keys=True, indent=4)))`).

**Comment by anmyachev** [comment]
> I would suggest measuring the hash by converting to a predictable string (e.g. using `hash(json.dumps(obj, sort_keys=True, indent=4)))`).

At the moment, `ASV` itself calculates the hash, so changes in the calculation must be made to the source code of the library. I suggest leaving it as it is.
