### ISSUE TITLE
Support for `progress_` methods from `tqdm.pandas()`

### ISSUE THREAD

**Issue by muammar** [modin-project/modin#3418]
I have recently started to use Modin to accelerate operations when using Pandas DataFrames with Dask. I like the idea that by just changing a single line of code on my notebook, I can get the most from Modin. I heavily use `tqdm.pandas()` to get progress bars. Modin does not currently support these. That was a little bit annoying because I had to change, for example,  from `.progress_apply` to `.apply` in long notebooks. 

Would it be possible to add support for `.progress_` methods from `tqdm.pandas()`?

Feel free to close this report if this request is not relevant.

**Comment by devin-petersohn** [comment]
Hi @muammar thanks for the request! We have an experimental progress bar in Modin that uses tqdm, but compatibility with tqdm makes a lot of sense as well. You can see how to use the current progress bar here: https://modin.readthedocs.io/en/latest/experimental_features/progress_bar.html

`tqdm.pandas()` adds the `progress_*` methods to a pandas dataframe, so this change might be needed in tqdm to have full compatibility.

**Comment by RehanSD** [comment]
Hi @muammar! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!

**Comment by Garra1980** [comment]
this feature can be valuable for modin adoption

**Comment by RehanSD** [comment]
> this feature can be valuable for modin adoption

Hi @Garra1980 - would you like to reopen the issue?
