### ISSUE TITLE
read_json: FutureWarning: the 'numpy' keyword is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3432]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Ubuntu 20.04`
- **Modin version** (`modin.__version__`): ac8e2d18826ebe7666bfd3c48fd0489b6b0426ea
- **Python version**: `3.8.10`
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

pd.DataFrame([1,2,3,4,5], columns=["col1"]).to_json("test.json", lines=True, orient="records")
pd.read_json("test.json", lines=True)
```

### Describe the problem

The warning appears even when the user does not use this parameter.

### Source code / logs

```shell
(pid=21108) FutureWarning: the 'numpy' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'numpy'
(pid=11332) FutureWarning: the 'numpy' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'numpy'
(pid=29788) FutureWarning: the 'numpy' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'numpy'
```

**Comment by RehanSD** [comment]
Confirmed that this is reproducible on master!

**Comment by anmyachev** [comment]
The parameter is already removed on [current ](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c)master. Not actual.
