### ISSUE TITLE
[omnisci] Segmentation fault on isnull().sum() operation

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3443]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.1 LTS

- **Modin version** (`modin.__version__`):

0.10.2+26.gda2ad792

- **Python version**:

Python 3.9.7

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

MULTIPLIER = 50000000

df = pd.DataFrame({
    "a": [np.float64(1)] * MULTIPLIER,
    "s": ["abc"] * MULTIPLIER,
    "i": [10] * MULTIPLIER,
    "t": [pd.to_datetime("2021")] * MULTIPLIER
})

print(df.dtypes)
df2 = df.isnull()
print(df2)
s = df.isnull().sum()
print(s)
count = df.isnull().sum().sum()
print(count)
```

### Describe the problem

Running code above gives Segmentation fault to me. It seems to depends on the value of `MULTIPLIER`. The smaller this value, the less probability to get a segfault.

**Comment by anmyachev** [comment]
@Garra1980 this error is not reproducible on the master. Can we close it?

**Comment by Garra1980** [comment]
I think yes
