### ISSUE TITLE
AttributeError: module 'modin.pandas' has no attribute 'api'

### ISSUE THREAD

**Issue by soumava-das** [modin-project/modin#3447]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **Modin version** (`modin.__version__`): 0.10.2
- **Python version**: 3.8.10
- **Code we can use to reproduce**: 

import modin.pandas as pd

indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=d)
df['new'] = df['rough'].rolling(window=indexer).apply(np.prod, raw=True) - 1

### Describe the problem
modin should have defaulted to pandas in case this functionality is not implemented instead of throwing an error.

### Source code / logs
    indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=d)
AttributeError: module 'modin.pandas' has no attribute 'api'

**Comment by devin-petersohn** [comment]
Thanks @soumava-das for the report!

@prutskov Are you able to take a look? It might just need to be rolled into the default api.

**Comment by prutskov** [comment]
@devin-petersohn Yes, I'll take a look on this.
