### ISSUE TITLE
Exception has occurred: TypeError Cannot do operation non-numeric dtypes

### ISSUE THREAD

**Issue by russell94paul** [modin-project/modin#3448]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu
- **Modin version**: 0.8.3
- **Python version**: Python 3.6.9 :: Anaconda, Inc.
- **Code we can use to reproduce**:
- Attempt to add (+) a timedelta (e.g. 42 days) on to a datetime columns in a modin.pandas series, you can see an example in my screenshout below.

### Library Information
Library versions:
- pandas 1.1.5
- ray 1.1.0
- modin 0.8.3

(I had been using a more recent version of ray, but it was giving me issues, and found v 1.1.0 to work best for me)

### Describe the problem
Receiving an error when trying to add to datetime types (which are able to be added together by default in pandas).

My initial thoughts are that it is not defaulting to the pandas function for datetime/timedelta 
One object is a datetime object and one is a timedelta so pandas itself might have additional logic for handling the addition of these objects as they are two different data types. Just speculating though

Please let me know if there is any necessary pieces of information to be included. Thanks

### Source code / logs
```
Cannot do operation non-numeric dtypes
  File "load.py", in LoadExternalTables()
    eligibility[params.ods_last_selling_day] = eligibility[params.ods_first_selling_day] + pd.to_timedelta(7*eligibility[params.ods_weeks_at_regular_price],unit='D')
  File "load.py", line 64, in LoadExternalTables()
    LoadExternalTables() #loads eligibility and wp_sales_plan (xxx schema)
  File "main.py", line 59, in _main
    load.LoadExternalTables()   # 1 min
  File "main.py", line 197, in <module>
    main()
```

**Comment by devin-petersohn** [comment]
Hi @russell94paul, thanks for posting!

Are you able to upgrade your python environment to 3.7.1+? The latest version of Modin is 0.10.2, and 0.8.3 is from January. We dropped Python 3.6 when pandas did.

As a side note, we are discussing ways to continue supporting key older versions of pandas. This is good evidence that we need to support more than just the latest.

**Comment by russell94paul** [comment]
Hi Devin,

Thanks. I was under the assumption Modin 0.8.3 was the latest (which wasn't working) I will try upgrading my python environment and modin library version and let you know  what the outcome is.

**Comment by devin-petersohn** [comment]
Thanks @russell94paul, if it's not possible or too challenging to do so please feel free to let us know.

**Comment by russell94paul** [comment]
Hi Devin,

I have updated the libraries as you had suggested, but I am still running into the same issue when trying to perform addition of datetime objects.

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda3/envs/test/lib/python3.7/site-packages/pandas/core/indexes/extension.py", line 174, in method
    result = meth(_maybe_unwrap_index(other))
  File /anaconda3/envs/test/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/anaconda3/envs/test/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 1279, in __add__
    return self._add_datetime_arraylike(other)
  File "anaconda3/envs/test/lib/python3.7/site-packages/pandas/core/arrays/timedeltas.py", line 466, in _add_datetime_arraylike
    return other + self
  File "/anaconda3/envs/test/lib/python3.7/site-packages/modin/pandas/series.py", line 202, in __add__
    return self.add(right)
  File "/anaconda3/envs/test/lib/python3.7/site-packages/modin/pandas/series.py", line 554, in add
    new_other, level=level, fill_value=fill_value, axis=axis
  File "/anaconda3/envs/test/lib/python3.7/site-packages/modin/pandas/base.py", line 579, in add
    "add", other, axis=axis, level=level, fill_value=fill_value
  File "/anaconda3/envs/test/lib/python3.7/site-packages/modin/pandas/base.py", line 412, in _binary_op
    other = self._validate_other(other, axis, numeric_or_object_only=True)
  File "/anaconda3/envs/test/lib/python3.7/site-packages/modin/pandas/base.py", line 308, in _validate_other
    raise TypeError("Cannot do operation non-numeric dtypes")
TypeError: Cannot do operation non-numeric dtypes`

I had forgotten to include all the error details previously.

**Comment by devin-petersohn** [comment]
I see, thanks for the update! I modified the markdown in your comments a bit to help readability.

Yes, this is a bug. The full stack trace in your recent comment really helps identify the issue, thanks so much!

We'll have someone look at this for 0.11.1

**Comment by russell94paul** [comment]
Thanks Devin.  I meant to include it in the first post, but copied the incorrect trace.

Would be great to get it working. 

I am currently tasked with optimizing a large pipeline job for both memory usage and runtime. All our code is currently in pandas, and some is in numpy (crosstab format) in order to handle the computation in memory.

I have been looking and reasearching possible improvements to be made and am considering modin as one of the options.

Vaex is another option that may be more suitable as our issue is a OOM issues, and Vaex might just solve that problem.

Currently just testing and benchmarking various libraries - we may only end up optimizing current Pandas operations.

**Comment by devin-petersohn** [comment]
Thanks for the context @russell94paul. We'll get someone on this.

**Comment by RehanSD** [comment]
Hi @russell94paul! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!
