### ISSUE TITLE
Reading in multiple JSON files using glob (wildcard) syntax

### ISSUE THREAD

**Issue by EvanZ** [modin-project/modin#3450]
There was a similar feature request (https://github.com/modin-project/modin/pull/2662) that solved this problem for CSV files. For my use case I am trying to read hundreds or thousands of jsonlines files spit out by a Spark ETL process. In some cases we could convert to csv, but a lot of our datasets have array or vectorized features, which are typically easier to deal with as json.

Discussed here:

https://discuss.modin.org/t/read-multiple-csv-files/157/4?u=evanz

**Comment by devin-petersohn** [comment]
Thanks @EvanZ for the request!

cc @anmyachev. I don't think it would be too complicated or too much of a deviation from the CSV (or maybe even pickle) versions.

**Comment by RehanSD** [comment]
@anmyachev has this issue been resolved?

**Comment by anmyachev** [comment]
> @anmyachev has this issue been resolved?

@RehanSD  not yet

**Comment by anmyachev** [comment]
Also requested in https://modin-project.slack.com/archives/C02MY2YV5MK/p1703075320557569
