### ISSUE TITLE
Loading parquet from MinIO

### ISSUE THREAD

**Issue by grafail** [modin-project/modin#3464]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 21.04
- **Modin version** (`modin.__version__`): 0.10.2
- **Python version**: 3.8.12
- **Code we can use to reproduce**:
This connects to a local MinIO installation running in Docker.
```
        storage_options = {
                                    "region_name": "us-east-1",
                                    "endpoint_url": "http://localhost:9000",
                                    "use_ssl": False,
                            }
        s3 = s3fs.S3FileSystem(anon=False, key="key",
                               secret="secret", client_kwargs=storage_options)
        s3_path = f"/{bucket}/{some_file}"
        df = pd.read_parquet(s3.open(s3_path))
```

### Describe the problem

https://github.com/modin-project/modin/blob/a0a3ebb0b4ec218a90ef0d08d440fd7f0faabfab/modin/engines/base/io/column_stores/parquet_reader.py#L94

This line does not allow a MinIO instance (or any other custom S3 instance) to be used instead of Amazon S3.
Pandas does work with the exact same config.

A possible fix could be to replace the line above with this:
```python
re.split("(?<=s3://)(.+)(?=/)", path.url())
```

### Source code / logs
```
File ".../modin/engines/base/io/column_stores/parquet_dispatcher.py", line 106, in _read
    path = "s3://" + bucket_path[0].split("://")[1] + bucket_path[1]
IndexError: list index out of range
```

**Comment by prutskov** [comment]
Hi @grafail! Thank you for the report.
Could you check the workflow on the latest modin/master branch? We recently (in da2ad792aa0c74ed11616e20d7581780fdbada31) updated our `read_parquet` function and it will be part of Modin 0.11.

**Comment by grafail** [comment]
Thanks, it indeed worked for me on the version on master.

**Comment by prutskov** [comment]
@grafail Cool! Feel free to ask in case any issues!
