### ISSUE TITLE
[omnisci] Printing a dataframe column ends on index 61 instead of dataframe last index

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3477]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.1 LTS

- **Modin version** (`modin.__version__`):

0.10.2+39.g15f168ca

- **Python version**:

Python 3.9.7

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

MULTIPLIER = 1000_000

df = pd.DataFrame({
    "a": [np.float(1)] * MULTIPLIER,
    "s": ["abc"] * MULTIPLIER,
    "i": [10] * MULTIPLIER,
    "t": [pd.to_datetime("2021")] * MULTIPLIER
})

print(df.shape)
print(df["t"])
```

### Describe the problem

Printing a column out of a large dataframe prints only up to 61 row while dataframe doesn't end on row 61.

**Comment by AndreyPavlenko** [comment]
On the latest master I'm getting the following output:

```
(1000000, 4)
0        2021-01-01
1        2021-01-01
2        2021-01-01
3        2021-01-01
4        2021-01-01
            ...    
999995   2021-01-01
999996   2021-01-01
999997   2021-01-01
999998   2021-01-01
999999   2021-01-01
Name: t, Length: 1000000, dtype: datetime64[ns]
```
Closing as not reproducible. If you could reproduce the issue, please reopen.
