### ISSUE TITLE
`parse_dates` parameter in OmniSci's `read_csv` doesn't work since Arrow 3.0

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3485]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 0.11
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import modin.pandas as pd
import pandas

pandas.DataFrame({"a": ["2020-01-01", "2020-02-02"]}).to_csv("test.csv")

md_df = pd.read_csv("test.csv", parse_dates=False)
pd_df = pandas.read_csv("test.csv", parse_dates=False)

print(f"modin dtypes:\n{md_df.dtypes}\n")  # a: datetime64[ns]
print(f"pandas dtypes:\n{pd_df.dtypes}\n") # a: object
```

Output:
```
modin dtypes:
              int64
a    datetime64[ns]
dtype: object

pandas dtypes:
Unnamed: 0     int64
a             object
dtype: object
```

### Describe the problem
In Arrow 3.0 they introduced an [auto `date32` type inference](https://issues.apache.org/jira/browse/ARROW-11247) in Arrow's `read_csv`, there is no way of not doing automatic inference unless providing an explicit type scheme. Computing a type scheme to properly handle pandas `parse_dates` appears to be very expensive in some cases (in [the case of a wide frame](https://github.com/modin-project/modin/pull/3308#issuecomment-918116462) mostly), so it was decided to do this only in a [strict compatibility mode](https://github.com/modin-project/modin/issues/3411). Until then, `parse_dates` parameter is considered to be unsupported in Omnisci backend.

[Commit that brings `parse_dates` support](https://github.com/dchigarev/modin/commit/b7f605150b7c81d56b7a7d64c8314ff3de61449d) considering that strict mode is implemented.

**Comment by gshimansky** [comment]
What is the suggested way to read a CSV file with datetime columns now? AFAIK converting columns to datetime after reading is impossible too https://docs-new.omnisci.com/sql/data-manipulation-dml/sql-capabilities#type-cast-support

**Comment by dchigarev** [comment]
@gshimansky all of the columns are converted to DateTime automatically since arrow 3.0, this is a deviation from pandas since pandas don't convert any columns to DateTime until they are explicitly specified via `parse_dates` parameter. To achieve pandas behaviour of non-converting certain columns to DateTime you can specify explicit type-scheme via `dtype` parameter of the `read_csv`:
```python
df = pd.read_csv(filepath, dtype={"datetime_column_that_shouldn't_be_converted_to_datetime_type": "string"})
```

**Comment by gshimansky** [comment]
@dchigarev Thank  you for clarification. I missed the part that Arrow now detects datetime automatically.

**Comment by anmyachev** [comment]
The error is reproduced on the [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
