### ISSUE TITLE
`GroupBy.groups/.indices` ignores dropna=False as kwarg

### ISSUE THREAD

**Issue by ahallermed** [modin-project/modin#3498]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 11.5.2
- **Modin version** (`modin.__version__`): 0.10.0 and 0.10.2
- **Python version**: 3.8.10

### Describe the problem

Using groupby, the modin implementation ignores the parameter dropna.
Ad-hoc, the property "_index_grouped" could be the problem, as it calls `groupby(by)` only with the parameter by, but not with any other kwargs. [Here is the line reference to this property.](https://github.com/modin-project/modin/blob/c3b8d7e4863615f99c8a1c6b7316e680daaa4393/modin/pandas/groupby.py#L767)

The code below can reproduce this issue. As additional information: Using `pandas_grouped.groups` fails with this error: `ValueError: Categorical categories cannot be null`, but iterating over the groups still works.

#### Code to reproduce

```python
import modin
import numpy as np
import pandas

def print_name_and_groups(title, grouped):
    print(title)
    for name, group in grouped:
        print("name:\n", name)
        print("group:\n", group)
        print()

data = {"a": [1, 2, 3, 4], "b": [11, np.nan, 13, np.nan]}

df = modin.pandas.DataFrame(data)
modin_grouped = df.groupby("b", dropna=False)
print_name_and_groups("modin groups:", modin_grouped)

df = pandas.DataFrame(data)
pandas_grouped = df.groupby("b", dropna=False)
print_name_and_groups("pandas groups:", pandas_grouped
```

#### Output
```bash
modin groups:
name:
 11.0
group:
    a     b
0  1  11.0

name:
 13.0
group:
    a     b
2  3  13.0

pandas groups:
name:
 11.0
group:
    a     b
0  1  11.0

name:
 13.0
group:
    a     b
2  3  13.0

name:
 nan
group:
    a   b
1  2 NaN
3  4 NaN
```

**Comment by devin-petersohn** [comment]
Hi @ahallermed thanks for the report! I see the problem reproducible with `groups` but not with the builtin groupby functions like `sum`, `count`, `mean`, etc.

>Ad-hoc, the property "_index_grouped" could be the problem, as it calls groupby(by) only with the parameter by, but not with any other kwargs

Looking at the code, I agree and think this is right. Since you've already dove into the code, let me know if you want to contribute the patch to fix this. Thanks again for the detailed report!

**Comment by ahallermed** [comment]
Hello @devin-petersohn,
thanks to you for the fast reply.

I had a closer look at the code and especially the tests and the latter kind of overwhelmed me.

I fear the side-effects, the project setup for testing and setting up a test that serves your compliance. But I am willing to learn from your changes and get more involved one after another. Therefore, I want to give you a proposal that may help you do a fix.

## In groupby.py
My suggestion would be, to replace `groupby(by)` with `groupby(by, **self._kwargs)` in the following lines:
[line 821](https://github.com/modin-project/modin/blob/c3b8d7e4863615f99c8a1c6b7316e680daaa4393/modin/pandas/groupby.py#L821)
[line 838](https://github.com/modin-project/modin/blob/c3b8d7e4863615f99c8a1c6b7316e680daaa4393/modin/pandas/groupby.py#L838)
[line 840](https://github.com/modin-project/modin/blob/c3b8d7e4863615f99c8a1c6b7316e680daaa4393/modin/pandas/groupby.py#L840)

I am not deep enough in the code to say, whether one needs to additionally add `self._squeeze` like in [line 316](https://github.com/modin-project/modin/blob/c3b8d7e4863615f99c8a1c6b7316e680daaa4393/modin/pandas/groupby.py#L316)

## In test_groupby.py
For the test, I would suggest to use the reproduction code (see above) as a minimalistic test case, e.g.:

```python
def test_dropna_parameter_is_used:
    data = {"a": [1, 2, 3, 4], "b": [11, np.nan, 13, np.nan]}

    modin_df = modin.pandas.DataFrame(data)
    modin_groupby = modin_df.groupby("b", dropna=False)

    pandas_df = pandas.DataFrame(data)
    pandas_groupby = pandas_df.groupby("b", dropna=False)

    assert 3 == pandas.groupby.ngroups
    assert modin_groupby.ngroups == pandas.groupby.ngroups
    eval_groups(modin_groupby, pandas_groupby)
```

There is already a test for `def test_groupby_multiindex(groupby_kwargs):` on line 1182, but it is not with nan and not with the parameter dropna and only for multiindex.

I am curious how the fix will actually be implemented and tested. Thank you in advance!

**Comment by devin-petersohn** [comment]
Thanks @ahallermed!

Please feel free to put those changed in as a pull request and we can take the changes from there. It would be great to be able to attribute the changes to the one who did the work! We will make any necessary changes on that PR once it is in to ensure that it works with the other components of `groupby`.

If you put in a PR just make sure you take a quick look at the contributing docs on how to format the commit message and sign the commit with `git commit -s` (outlined here: https://modin.readthedocs.io/en/latest/contributing.html)

**Comment by ahallermed** [comment]
Hello @devin-petersohn, thanks for helping me about how to do a pull request. I'll do one next week.

**Comment by devin-petersohn** [comment]
@ahallermed It's a great PR, I left a comment there about the commit message.

**Comment by ahallermed** [comment]
Sure. Please go ahead.

**Comment by ahallermed** [comment]
@dchigarev Thank you for your commitment!

**Comment by Garra1980** [comment]
@ahallermed corresponding PR was merged

**Comment by ahallermed** [comment]
@Garra1980 Thank you for the update!
