### ISSUE TITLE
Add `s3fs` to deps in setup.py

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3499]

**Comment by prutskov** [comment]
Do we suppose that user should install specific dependencies like `s3fs` by himself? If yes, do we have any mention of this in docs, for example? Because it's not obvious that missing package needed for working of some components is a responsibility of user but not Modin.

**Comment by devin-petersohn** [comment]
That is how pandas handles it, and I think we give a good error message if s3fs is not installed and we need to use it.

**Comment by prutskov** [comment]
What should we do for issue described in #3504? Is `fsspec` an optional too? (But #3504 could be resolved by `pip install modin[all]`)

**Comment by devin-petersohn** [comment]
I left a comment there, we need to catch the `ModuleNotFoundError` and throw a better error and message, I think. Do you agree?

**Comment by prutskov** [comment]
Yes, I agree with that approach. I created new issue #3505. This issue/PR might be closed I think.
