### ISSUE TITLE
Throw custom errors with message for optional packages instead of `ModuleNotFoundError`

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3505]
Currently in the list of optional deps we have:

- fsspec
- s3fs

We should check the package availability before usage and throw message to user in the absence. Possible example is here: https://github.com/modin-project/modin/issues/3504#issuecomment-931540502

**Comment by anmyachev** [comment]
@prutskov `fsspec` is currently a required dependency

**Comment by devin-petersohn** [comment]
Resolved by #3652
