### ISSUE TITLE
`read_fwf` does not play nice with `gzip`

### ISSUE THREAD

**Issue by randolf-scholz** [modin-project/modin#3507]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **Modin version** (`modin.__version__`): 0.11.0
- **Python version**: 3.9.7
- **Code we can use to reproduce**:

Download one of the `state*.gz` files from [https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/](https://cdiac.ess-dive.lbl.gov/ftp/ushcn_daily/).

```python
from modin import pandas as pd
import gzip

with gzip.open("state01_AL.txt.gz") as file:
    df = pd.read_fwf(file)
```

### Describe the problem

Using the file-object returned from `gzip` causes fallback to regular `pandas`

The related issue for `read_csv`: https://github.com/modin-project/modin/issues/630 was fixed in https://github.com/modin-project/modin/pull/682.

**Comment by devin-petersohn** [comment]
Hi @randolf-scholz, thanks for posting!

This should be relatively straightforward to add, we'll look into it for the next release. Thanks again for the report!

**Comment by anmyachev** [comment]
if `read_csv` works well in the case maybe https://github.com/modin-project/modin/pull/3540 can help with the issue.
