### ISSUE TITLE
[omnisci] Usability problem with omnisci if some portion of code unrelated to Modin works for a long time

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3514]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.3 LTS

- **Modin version** (`modin.__version__`):

0.11.0

- **Python version**:

Python 3.7.10

- **Code we can use to reproduce**:

My jupyter notebook has a ETL part and then ML part that calls XGBoost.train. This call executes for 2 hours and no Modin APIs are called while XGBoost works. When execution resumes I get the following exception which prevents Modin from executing any code that call omnisci:

```
RuntimeError: TException - service has thrown: TOmniSciException(error_msg=Idle Session Timeout. User should re-authenticate.)
```

**Comment by gshimansky** [comment]
> There is a idle-session-duration parameter for omnisci_server. Can you please try with increased value of that param?

Is it possible to set its default setting to some really high value?

**Comment by Garra1980** [comment]
It is documented on omnisci side - https://docs.omnisci.com/installation-and-configuration/config-parameters. I agree we should mention this in Modin docs explicitly if not yet. We also can increase default value passing new value to server in modin sources.
But for now we don't know whether this param helps at all :)

**Comment by anmyachev** [comment]
@Garra1980 can we close the issue?

**Comment by anmyachev** [comment]
With the transition to `pyhdk`, this problem is no longer relevant.
