### ISSUE TITLE
Commitlint checks every commit, making it harder to use GitHub UI to merge suggestions

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#3525]
We can change commitlint to check only the first commit. I think since we squash, we don't need the same prefix for every commit, just the first.

cc @modin-project/modin-core

**Comment by devin-petersohn** [comment]
>I agree, but let's also add commitlint to pushes to master to make sure they're merged with correct messages, as composing a commit message is a manual task now.

What do we do if it fails?

**Comment by YarShev** [comment]
I like the idea. It is useful not only for beginners with Modin, but and it also allows not to bloat a discussion in an issue. However, we should think about pushes to master as well in future. I am approving the PR, @vnlitvinov , if you have some thoughts on it for now, feel free to give them :)
