### ISSUE TITLE
in OSX, parquet formatted dataframe errors on tail() - "length should not be negative"

### ISSUE THREAD

**Issue by farhadabar** [modin-project/modin#3527]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- **Modin version** (`modin.__version__`):0.11.1
- **Python version**: 3.8.3
- **Code we can use to reproduce**:
- 

df = pd.read_parquet('/var/tmp/prod.parquet')
df.head() # works!
df.tail() #  fails! "length should not be negative"

### Describe the problem

This happens only on OSX

When a parquet dataset is read by modin, the tail operation errors.

exporting to a csv and reread with pd.read_csv, both head() and tail() work.

**Comment by farhadabar** [comment]
here you go,


>>> df
      MPG  Cylinders  Displacement  ...  Acceleration  Model_Year  Origin
0    18.0          8         307.0  ...          12.0          70     usa
1    15.0          8         350.0  ...          11.5          70     usa
2    18.0          8         318.0  ...          11.0          70     usa
3    16.0          8         304.0  ...          12.0          70     usa
4    17.0          8         302.0  ...          10.5          70     usa
..    ...        ...           ...  ...           ...         ...     ...
393  27.0          4         140.0  ...          15.6          82     usa
394  44.0          4          97.0  ...          24.6          82  europe
395  32.0          4         135.0  ...          11.6          82     usa
396  28.0          4         120.0  ...          18.6          82     usa
397  31.0          4         119.0  ...          19.4          82     usa

[398 rows x 8 columns]

>>> df.head()
    MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  Model_Year Origin
0  18.0          8         307.0       130.0    3504          12.0          70    usa
1  15.0          8         350.0       165.0    3693          11.5          70    usa
2  18.0          8         318.0       150.0    3436          11.0          70    usa
3  16.0          8         304.0       150.0    3433          12.0          70    usa
4  17.0          8         302.0       140.0    3449          10.5          70    usa

>>> df.tail()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/pandas/base.py", line 2469, in tail
    return self.iloc[-n:]
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/pandas/indexing.py", line 754, in __getitem__
    result = super(_iLocIndexer, self).__getitem__(row_lookup, col_lookup, ndim)
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/pandas/indexing.py", line 300, in __getitem__
    qc_view = self.qc.view(row_lookup, col_lookup)
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py", line 3056, in view
    self._modin_frame.mask(row_numeric_idx=index, col_numeric_idx=columns)
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 474, in mask
    new_row_lengths = [
  File "/Applications/Genetica/Cortex10/miniconda3/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 475, in <listcomp>
    len(range(*idx.indices(self._row_lengths[p])))
ValueError: length should not be negative

**Comment by jeffreykennethli** [comment]
I was able to reproduce this issue, but it wasn't an issue with `tail()` rather an issue with indexing into a column by name. I suspect they are related to how we are partitioning parquet files.

I did this on MacOS: 12.0.1, python==3.9.10, modin==0.13.0

Here is a script:
```
import modin.pandas as pd 

df = pd.read_parquet("s3://modin-test/test_parquet_file.parquet")
df["numerical_1"]
```

I can also confirm this breaks when reading the same parquet file locally and not from s3. I can also confirm this is broken on older versions of Modin as far back as 0.12.0.

Here is the stack trace: https://gist.github.com/jeffreykennethli/f0ed5408755b96b8b5133140f7def18a

**Comment by cristianmtr** [comment]
I am also getting this issue, on Ubuntu 22.04

```python
!pip freeze | grep modin
modin==0.12.1
...
!pip freeze | grep modin
modin==0.12.1
...
```

using the above sample code

```python
import modin.pandas as pd 

df = pd.read_parquet("s3://modin-test/test_parquet_file.parquet", storage_options={"anon":True})
df["numerical_1"]
```
