### ISSUE TITLE
Create Head and Tail for ProgressBar estimation and optimized Repr operations

### ISSUE THREAD

**Issue by todd-yu** [modin-project/modin#3531]
**Is your feature request related to a problem? Please describe.**

Create Head and Tail for ProgressBar estimation and optimized Repr operations

**Comment by todd-yu** [comment]
Assigned to @todd-yu

**Comment by RehanSD** [comment]
Hi @todd-yu has this issue been resolved?

**Comment by mvashishtha** [comment]
@RehanSD I think that as of modin version 88f7b27d32b099c508e93251cafe503f2908d426, we still don't have progress bars for `head`, `tail`, or `repr`.

**Comment by todd-yu** [comment]
Hey all, nope this was largely a research implementation and isn't fit to be merged into the Modin codebase.

**Comment by RehanSD** [comment]
@todd-yu do we plan to implement this, or should we close this as won't do?

**Comment by todd-yu** [comment]
Let's close this for now, thanks!
