### ISSUE TITLE
BUG: Modin currently support s3 paths that start with "S3" and "s3" prefixes

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3559]
The main problem is that this behavior is different from `pandas` and `fsspec`.

I suggest removing the logic to maintain this behavior in `Modin`. If necessary, we can add this logic to `fsspec` library, but take into account the need for compatibility with `pandas`.

**Comment by RehanSD** [comment]
Hi @anmyachev - has this issue been resolved?

**Comment by mvashishtha** [comment]
@RehanSD at modin version 88f7b27d32b099c508e93251cafe503f2908d426, none of `read_csv` , `read_json`, `read_fwf`, or `read_parquet` accept S3. I think we can mark this issue as resolved.
