### ISSUE TITLE
`DataFrame.apply` is halting during interaction with scipy

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3563]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 01a5de21c8fb3f6da0f9f887f6a659b7037136a0
- **Python version**: 3.8.12
- **Code we can use to reproduce**:
```
import modin.pandas as pd
import numpy as np
from scipy.io.wavfile import write, read

test_filename = "test.wav"
samplerate = 44100
fs = 100

# generate 100Hz sine wave
t = np.linspace(0., 1., samplerate)
amplitude = np.iinfo(np.int16).max
data = amplitude * np.sin(2. * np.pi * fs * t)
write(test_filename, samplerate, data.astype(np.int16))

data = pd.DataFrame({"filepath": [test_filename]})
data['audio'] = data['filepath'].apply(read)
```

### Describe the problem

Modin `DataFrame.apply` is halting during applying `scipy` custom function, while pandas works fine.
`scipy` 1.7.1 from conda-forge

**Comment by vnlitvinov** [comment]
@devin-petersohn what was the reason to create the dummy `Series` in the first place? the most obvious fix here would be to create a 1-element `Series` like this: `pandas.Series(self.values[:1], index=self.index[:1])`, and the only drawback I see here compared to current solution is that it potentially would run slower (if the user-defined `func` takes more time on a real data piece than on simulated).

I don't really see the way around that... and the way to overcome the drawback would be to store the results of applying to a single element and then concatenate, but I believe it won't give any real speedup here.
