### ISSUE TITLE
Replace `s3fs` usage with `fsspec`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3572]
We have some place where it's using. They can be replaced with using of `fsspec`. Thus, we unify the read operations.

https://github.com/modin-project/modin/blob/01a5de21c8fb3f6da0f9f887f6a659b7037136a0/modin/core/io/file_dispatcher.py#L198

https://github.com/modin-project/modin/blob/01a5de21c8fb3f6da0f9f887f6a659b7037136a0/modin/core/io/text/csv_glob_dispatcher.py#L286

https://github.com/modin-project/modin/blob/01a5de21c8fb3f6da0f9f887f6a659b7037136a0/modin/core/io/text/csv_glob_dispatcher.py#L318

**Comment by vnlitvinov** [comment]
@anmyachev @pyrito does https://github.com/modin-project/modin/pull/4898 also close this one?

**Comment by pyrito** [comment]
@vnlitvinov yes thanks for bringing it up. This should be resolved now.
