### ISSUE TITLE
[CI] Jenkins Improvement Proposal

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#358]
Our current CI system deserves some improvement. Here's a proposal:
- [ ] Travis will run lint only. 
- [ ] Jenkins will take care of the heavy load in one single PRB job
  - [ ] It will run {Py2, Py3} x {Ray, Python} build matrix in parallel. 
  - [ ] It will run {Dask, Ray, Python} performance regression testing in parallel. It will compare current commit with master commits and generate report. 
- [ ] @modin-bot will take care of aggregating the result and post a comment the the PR. It should look like the following (all links should direct to some htmls in s3):
------------------
🤖Jenkins Summary 🤖

### [PyTest Result](link_to_some_html)
- All passed 🎉

### [Performance Result](link)
- No performance degradation 🎉
------------------
🤖Jenkins Summary 🤖

### [PyTest Result](link_to_some_html)
- **5 Failed**
  - [py2_python_test_dataframe](link)
  - [py2_ray_test_dataframe](link)
  - [test_3_report](link)
  - [test_4_report](link)
  - [test_5_report](link)

### [Performance Result](link)
- Performance degradation in *2* targets
![reg_test_png](https://s3.amazonaws.com/simon-mo-dev-public/public/example_reg_test.png)
----------------

Please give feedback! 

cc @devin-petersohn

**Comment by devin-petersohn** [comment]
This sounds great @simon-mo! I think that the direction is great, and will much better inform the merge process.

There are some things in the tests themselves that need to be updated, now that our test suite is in a good position.

I would like to add a couple of axes to the test suite:
* Ray should run with multiple partitions (e.g. 4, 8, 12)
    * This can be done in-parallel as well
* The size/scale of dataframes should be varied as well, but that can be done within the tests.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
