### ISSUE TITLE
Modin scalability issues

### ISSUE THREAD

**Issue by nirandaperera** [modin-project/modin#3588]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **Modin version** (`modin.__version__`): 0.11.1
- **Python version**: 3.8.5
- **Code we can use to reproduce**: yes

### Describe the problem
hi all,
I am evaluating modin and I am trying to test the scalability (strong scaling). Following is a snippet of the code.
I have been running this while varying the number of CPUs in the ray cluster. I have a 10 node cluster with 16 CPUs each. So, I am testing for 1, 2, 4, …, 128, 160 CPUs (each time the entire cluster has been stopped and restarted with new configuration).

For 100M rows, following are the average timings I got (discarding the 0th iteration).
| world | AVERAGE of time (ms) |
|-------|----------------------|
| 1     | 48879.18562          |
| 2     | 42504.13573          |
| 4     | 38960.01136          |
| 8     | 43442.16764          |
| 16    | 45417.99891          |
| 32    | 47339.0817           |
| 64    | 45241.66238          |
| 128   | 48524.96344          |
| 160   | 52743.6024           |

It looks like I might be doing something wrong here, because I couldn’t get any speed up, while adding more resources for the operation.

I tried assigning `NPartitions` the same as number of CPUs in the cluster. But that didn’t help as well.
```python
import modin.config
modin.config.NPartitions.put(w)
```

I am wondering what I am missing here?

Thanks in advance

### Source code / logs
```python
r = 100* 10**6
it = 5

import ray
ray.init(address='v-001:6379', _redis_password=RAY_PW, _node_ip_address='v-001')    

frame_data = np.random.randint(0, r, size=(r, 2)) 
frame_data1 = np.random.randint(0, r, size=(r, 2)) 

os.environ["MODIN_ENGINE"] = "ray"  
import modin.pandas as pd

for i in range(it):

    df_l = pd.DataFrame(frame_data).add_prefix("col")
    df_r = pd.DataFrame(frame_data1).add_prefix("col")
    print(f"data loaded", flush=True)

    t1 = time.time()
    out = df_l.merge(df_r, on='col0', how='inner')
    t2 = time.time()

    print(f"timings {r} {i} {(t2 - t1) * 1000:.0f} ms, {out.shape[0]}", flush=True)

    del df_l 
    del df_r
    del out 
    gc.collect()
```

**Comment by RehanSD** [comment]
Hi @nirandaperera! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!
