### ISSUE TITLE
can't read sheet in xlsx file 

### ISSUE THREAD

**Issue by amir-shehzad** [modin-project/modin#359]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04 shell on Windows 10
- **Modin installed from (source or binary)**:
pip
- **Modin version**:
0.2.5
- **Python version**:
Python 3.6.4
- **Exact command to reproduce**:
import modin.pandas as pd
pd.read_excel("test.xlsx", sheet_name="Items")

### Error 
/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/modin/pandas/io.py:512: UserWarning: Defaulting to Pandas implementation
  warnings.warn("Defaulting to Pandas implementation", UserWarning)

---------------------------------------------------------------------------

TypeError  Traceback (most recent call last) <ipython-input-8-687c3198b05e> in <module>()

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/modin/pandas/io.py in read_excel(io, sheet_name, header, skiprows, index_col, names, usecols, parse_dates, date_parser, na_values, thousands, convert_float, converters, dtype, true_values, false_values, engine, squeeze)
    529         false_values,
    530         engine,
--> 531         squeeze,
    532     )
    533     ray_frame = from_pandas(port_frame)

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    176                 else:
    177                     kwargs[new_arg_name] = new_arg_value
--> 178             return func(*args, **kwargs)
    179         return wrapper
    180     return _deprecate_kwarg

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    176                 else:
    177                     kwargs[new_arg_name] = new_arg_value
--> 178             return func(*args, **kwargs)
    179         return wrapper
    180     return _deprecate_kwarg

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, **kwds)
    327         skipfooter=skipfooter,
    328         convert_float=convert_float,
--> 329         **kwds)
    330 
    331 

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py in parse(self, sheet_name, header, names, index_col, usecols, squeeze, converters, true_values, false_values, skiprows, nrows, na_values, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, **kwds)
    454                                  skipfooter=skipfooter,
    455                                  convert_float=convert_float,
--> 456                                  **kwds)
    457 
    458     def _should_parse(self, i, usecols):

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py in _parse_excel(self, sheet_name, header, names, index_col, usecols, squeeze, dtype, true_values, false_values, skiprows, nrows, na_values, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, **kwds)
    685                                     **kwds)
    686 
--> 687                 output[asheetname] = parser.read(nrows=nrows)
    688                 if names is not None:
    689                     output[asheetname].columns = names

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1034                 raise ValueError('skipfooter not supported for iteration')
   1035 
-> 1036         ret = self._engine.read(nrows)
   1037 
   1038         # May alter columns / col_dict

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, rows)
   2237     def read(self, rows=None):
   2238         try:
-> 2239             content = self._get_lines(rows)
   2240         except StopIteration:
   2241             if self._first_chunk:

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in _get_lines(self, rows)
   2994         if self.skip_blank_lines:
   2995             lines = self._remove_empty_lines(lines)
-> 2996         lines = self._check_thousands(lines)
   2997         return self._check_decimal(lines)
   2998 

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in _check_thousands(self, lines)
   2767         return self._search_replace_num_columns(lines=lines,
   2768                                                 search=self.thousands,
-> 2769                                                 replace='')
   2770 
   2771     def _search_replace_num_columns(self, lines, search, replace):

/ubuntu-on-windows/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in _search_replace_num_columns(self, lines, search, replace)
   2775             for i, x in enumerate(l):
   2776                 if (not isinstance(x, compat.string_types) or
-> 2777                     search not in x or
   2778                     (self._no_thousands_columns and
   2779                      i in self._no_thousands_columns) or

TypeError: 'in <string>' requires string as left operand, not bool

**Comment by devin-petersohn** [comment]
Hi @amir-shehzad, thanks for posting this!

Does the same error occur when you run it in pandas? I am not able to reproduce this locally. Because this command directly calls the pandas version and then converts to a Modin DataFrame, the error is happening on the pandas side. What version of pandas are you using?

**Comment by amir-shehzad** [comment]
Sorry for late reply. I just checked and it is working.
