### ISSUE TITLE
read_excel function error. but i can read the .xlsm with pandas

### ISSUE THREAD

**Issue by wangkailun** [modin-project/modin#3596]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10企业版
- **Modin version** (`modin.__version__`):0.11.2
- **Python version**: 3.7
- **Code we can use to reproduce**:
`
from dask.distributed import Client
from distributed import client
import os , sys
PATH = os.path.dirname(os.path.realpath(sys.argv[0]))
if __name__ == "__main__":
    client = Client(n_workers = 4)
    import modin.pandas as pd

    data = pd.read_excel(r"D:\Users\klwangd\Desktop\WAT_Data_Summary\data\TM7232 Monthly SPC WAT data collect format-202109.xlsm",sheet_name="Data collect formate" , header=6 , engine="openpyxl")
    print(data)
    `

### Describe the problem

![image](https://user-images.githubusercontent.com/19208269/138657219-72added8-3434-4eb1-968a-6a56bb698ff6.png)

### Source code / logs

UserWarning: Parallel `read_excel` is a new feature! Please email bug_reports@modin.org if you run into any problems.
distributed.worker - WARNING - Compute Failed
Function:  parse
args:      ()
kwargs:    {'sheet_name': 'sheet1', 'header': 6, 'names': None, 'index_col': None, 'usecols': None, 'squeeze': False, 'dtype': None, 'engine': 'openpyxl', 'converters': None, 'true_values': None, 'false_values': None, 'skiprows': 204, 'nrows': None, 'na_values': None, 'keep_default_na': True, 'na_filter': True, 'verbose': False, 'parse_dates': False, 'date_parser': None, 'thousands': None, 'comment': None, 'skipfooter': 0, 'convert_float': None, 'mangle_dupe_cols': True, 'storage_options': None, '_header': b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x14ac" xmlns:x14ac="http://schemas.microsoft
Exception: "ValueError('Passed header=6 but only 4 lines in file')"

**Comment by RehanSD** [comment]
Hi @wangkailun! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!
