### ISSUE TITLE
Get rid of redundant function calls on Ray workers

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#3599]
We have had a hacky solution to prevent #3014, #647, #746. We should try to get rid of it since we use Ray functionality that is not directly supposed to be used.

**Comment by RehanSD** [comment]
Hi @YarShev @vnlitvinov @devin-petersohn has this issue been resolved?

**Comment by mvashishtha** [comment]
@RehanSD I think #4603 fixed this.
