### ISSUE TITLE
Centralize tests in Modin

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#3622]
Right now, Modin tests are split between the top-level `modin/test` and in the directories (e.g. `modin/pandas/test`). I would like to centralize the test location to make it easier to run the test suite with `pytest`.

**Comment by teaVeloper** [comment]
Hi,
I will look at this issue in participating at the Sprint.

**Comment by vnlitvinov** [comment]
Should we also move `stress_tests` and `asv_bench` (cc @anmyachev) under this location to clean up the root?

**Comment by anmyachev** [comment]
`asv_bench` has a separate benchmark infrastructure, I think it should not be mixed with other tests.
