### ISSUE TITLE
`test-internals` GH action does not report coverage data to Codecov.

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3628]
[`test-internals`](https://github.com/modin-project/modin/blob/ef2159be59194891304f89fe5be15a03214d0e7b/.github/workflows/push.yml#L4-L31) CI job from GH actions does not report code coverage data to Codecov when [others jobs do](https://github.com/modin-project/modin/blob/ef2159be59194891304f89fe5be15a03214d0e7b/.github/workflows/push.yml#L79-L88). We need to add reporting to Codecov for this job as well.

**Comment by devin-petersohn** [comment]
@dchigarev Is this fixed?

**Comment by dchigarev** [comment]
> Is this fixed?

@devin-petersohn No, it's not
