### ISSUE TITLE
Fix an example related to ProgressBar usage

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#3634]
Remove tqdm import and add an operation on Modin Dataframe in https://modin.readthedocs.io/en/latest/experimental_features/progress_bar.html#quickstart.

**Comment by devin-petersohn** [comment]
@YarShev Should this be in 0.13.0? I think it can be pretty straightforward to fix.

**Comment by YarShev** [comment]
@devin-petersohn , yes, we should put this in 0.13.0. I will issue a PR soon.

**Comment by RehanSD** [comment]
@YarShev has this issue been resolved?

**Comment by YarShev** [comment]
Issued #5119.
