### ISSUE TITLE
Move OmniSci engine usage from experimental feature to main ones

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#3641]
We should move OmniSci engine usage from experimental feature to main ones.

**Comment by Garra1980** [comment]
what does it mean - move usage from experimental to main?

**Comment by YarShev** [comment]
Move content related to OmniSci engine from `modin/experimental/core` to `modin/core` and avoid setting `MODIN_EXPERIMENTAL=1`.

**Comment by Garra1980** [comment]
@aregm was against this iirc. Probably smth has been changed

**Comment by YarShev** [comment]
Yes, let's try to put it in 0.13.

**Comment by devin-petersohn** [comment]
Added to 0.13.0 release

**Comment by Rubtsowa** [comment]
This is an epic issue. List of individual issues is below:

- [ ] RelAlgExecutor.cpp:1177 Check failed in work at MODIN_STORAGE_FORMAT=omnisci
#3788

**Comment by anmyachev** [comment]
@Garra1980 almost all issues in the tracker have been fixed. It might be worth updating the tracker and considering moving it from experimental in the nearest release.

**Comment by Garra1980** [comment]
Thanks a lot for checking all subsidiary issues! I support the idea to give this issue a go - let's plan to move it forward for the upcoming releases

**Comment by anmyachev** [comment]
https://github.com/modin-project/modin/issues/7234
