### ISSUE TITLE
test_io.py flakily times out in Github CI

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#3653]
### Describe the problem

test_io.py sometimes times out on CI for PRs that shouldn't be making it much slower, e.g. [here](https://github.com/modin-project/modin/runs/4107837313?check_suite_focus=true) for #3651 and [here](https://github.com/modin-project/modin/runs/4012089345?check_suite_focus=true) for #3573. 

Alternatives are:

1) Make the test faster, e.g. by deleting tests, speeding up tests, or increasing parallelism
2) Increase the timeout from 30 minutes [here](https://github.com/modin-project/modin/blob/master/.github/workflows/ci.yml#L612).

I'll make a PR for option 2) without looking into 1).

**Comment by mvashishtha** [comment]
#3551 is the better fix.

**Comment by jeffreykennethli** [comment]
@anmyachev is there any update to this issue? I'd like to help resolve this task (can take it on if appropriate).

**Comment by mvashishtha** [comment]
@anmyachev mentioned [here](https://github.com/modin-project/modin/pull/3575#issuecomment-962652220) in the fix PR that the fix is blocked by #3659. He is working on #3659 as well.

**Comment by mvashishtha** [comment]
It's too late to officially link https://github.com/modin-project/modin/pull/3575 to this issue, but it's supposed to have fixed this issue.
