### ISSUE TITLE
Ray tasks are restarted when workers died, this behavior is not always desirable

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3659]
### System information
- **Modin version** (`modin.__version__`): 8acad95ed2dea2c7671d6dc3518d4b0b12c8b682
- **Link to Ray docs**: https://docs.ray.io/en/latest/fault-tolerance.html#tasks

### Describe the problem

An example of undesirable behavior is when tasks write to disk. In this case, duplication of data may occur. This behavior can be observed for `to_csv` function on Ray engine.

For such cases, we should use `max_retries=0` parameter of `ray.remote` function.

**Comment by gshimansky** [comment]
What is the reason why a worker dies?

**Comment by anmyachev** [comment]
I think overload, we tell Modin to use 4 cores, although there are only 2 cores on the github machines.
