### ISSUE TITLE
DataFrame has too many partitions after performing `concat` operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3675]
### System information
- **Modin version** (`modin.__version__`): d81b118104b39be3a14eff4658e96fcc64036e26
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

def test3():
    dfs = [None]*1000
    for i in range(1000):
        dfs[i] = pd.DataFrame({"A": [1,2,3,4,5]*3, "B": [6,7,8,9,10]*3})
    result = pd.concat(dfs)
    result.to_csv("result.csv")

test3()
```

### Describe the problem

This leads to the creation of many more workers than the available cores and can be a reason for a freeze or significant slowdown in code execution (the problem was found on `Ray`, but most likely it is present for `Dask` too).
We need to develop a process for repartitioning if necessary or maybe it already exists but how it works?

### Source code / logs

```bash
An example of one of the many warnings:
...
2021-11-12 12:23:07,131 WARNING worker.py:1215 -- WARNING: 136 PYTHON worker processes have been started on node: 4008fd6949b9629e54217435b571113a31e1fbd35e93cfbf575fb461 with address: 10.125.130.30. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
...
```

**Comment by dchigarev** [comment]
Also related #3657

**Comment by devin-petersohn** [comment]
#3886 will need more time to address all of the comments, it will likely be in the release after this

**Comment by anmyachev** [comment]
@devin-petersohn what about [temp](https://modin-project.slack.com/archives/CKBB4EVBK/p1639666022040500?thread_ts=1639576404.031600&cid=CKBB4EVBK) solution?

**Comment by anmyachev** [comment]
The important function is `to_csv`. I can call the rebalance right before it (not after `concat` function). This should be acceptable for a major release.

**Comment by anmyachev** [comment]
I don't even have to create a public API. Just do rebalancing directly in `to_csv` function. This will be enough for the customer to start. @devin-petersohn what do you think? This approach can be quickly implemented from what I have already written.

**Comment by devin-petersohn** [comment]
@anmyachev Current version works quite well for `to_csv`. Is it possible for this user to use an experimental branch?

**Comment by anmyachev** [comment]
@devin-petersohn I'm not sure, but https://github.com/modin-project/modin/pull/4028 looks easily replaceable with your implementation. I just need to change the test and clear the commit history.

**Comment by anmyachev** [comment]
> @anmyachev Current version (in #3886) works quite well for `to_csv`. Is it possible for this user to use an experimental branch?

@devin-petersohn unfortunately, the user only uses conda packages, without modifying the source codes. So this option is not suitable. What about #4028? This approach shouldn't slow down the execution of `to_csv` function in any case.
