### ISSUE TITLE
CI flake: conda failed with exit code 1

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#3729]
### Describe the problem
Sample failure [here](https://github.com/mvashishtha/modin/runs/4289466317?check_suite_focus=true) for Ubuntu. During the "Updating 'modin' env from conda env update..." step of "Run conda-incubator/setup-miniconda@v2", a failure produces the error `The process '/usr/share/miniconda/condabin/conda' failed with exit code 1`.

### Source code / logs
```
  Warning: 
  CondaHTTPError: HTTP 530 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/blessings-1.7-py37h89c1867_1005.tar.bz2>
  Elapsed: 00:00.051798
  CF-RAY: 6b23ad997dd96420-SJC
  
  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
  
  
  CondaHTTPError: HTTP 530 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/blessings-1.7-py37h89c1867_1005.tar.bz2>
  Elapsed: 00:00.051798
  CF-RAY: 6b23ad997dd96420-SJC
  
  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
  
 

Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```

For the issue linked above, [this](https://github.com/conda-incubator/setup-miniconda/issues/129) is the root cause, and no fix is in sight.

**Comment by devin-petersohn** [comment]
Maybe we can add a retry in the case this fails.

**Comment by mvashishtha** [comment]
This isn't fixed. I think the setu-miniconda command just ignores the `max_attempts` and `retry_on` arguments. e.g. [here](https://github.com/modin-project/modin/runs/4885939506?check_suite_focus=true) the setup failed and I see:

```
Warning: Unexpected input(s) 'max_attempts', 'retry_on', valid inputs are ['installer-url', 'miniconda-version', 'miniforge-variant', 'miniforge-version', 'conda-version', 'conda-build-version', 'environment-file', 'activate-environment', 'python-version', 'add-anaconda-token', 'add-pip-as-python-dependency', 'allow-softlinks', 'auto-activate-base', 'auto-update-conda', 'condarc-file', 'channel-alias', 'channel-priority', 'channels', 'show-channel-urls', 'use-only-tar-bz2', 'remove-profiles', 'mamba-version', 'use-mamba', 'architecture', 'clean-patched-environment-file']
```

I think I got those arguments from [this action](https://github.com/marketplace/actions/retry-step), which requires node.js to be installed.

**Comment by mvashishtha** [comment]
It looks like the issue to watch is https://github.com/conda-incubator/setup-miniconda/issues/129.

Note that per [this comment](https://github.com/conda-incubator/setup-miniconda/issues/129#issuecomment-1139163588) on that thread,  the issue is significantly less painful now that on GitHub you can re-run only the failed jobs, rather than having to restart every job.

**Comment by mvashishtha** [comment]
This has hit me twice recently. One recent instance: https://github.com/modin-project/modin/actions/runs/3275094044/jobs/5389493243

**Comment by mvashishtha** [comment]
I wanted to use something like [Retry Step](https://github.com/marketplace/actions/retry-step) to retry the action, but retry step is for shell commands, whereas we want to retry another action.

I saw this clever solution that may work: https://github.com/apache/tvm/pull/12058

**Comment by mvashishtha** [comment]
> I saw this clever solution that may work: https://github.com/apache/tvm/pull/12058

I tried this with no wait between retries, but it wasn't very effective.

**Comment by anmyachev** [comment]
@mvashishtha I haven't seen this error in a long time. Relevant or not?

**Comment by mvashishtha** [comment]
@anmyachev I don't remember seeing it recently either. However, I don't know whether we should close issues for flakes like this that haven't come up recently.
