### ISSUE TITLE
GroupBy comparator in `test_groupby.py` does not fully verify groups equality

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3756]
The method that's used to check equality of the groups in `GroupBy` does not check the lengths of the group iterators, it just iterates on the shortest one:
https://github.com/modin-project/modin/blob/0947ee853e621f85f86653526b7303f8c24ed5f6/modin/pandas/test/test_groupby.py#L35-L38
This may potentially hide errors of non-equal groups:
```python
>>> obj1.groups
{1: ["a"], 2: ["b"], np.nan: ["c"]}
>>> obj2.groups
{1: ["a"], 2: ["b"]}
>>> modin_groupby_equals_pandas(obj1, obj2) # No assertion error
>>>
```
We should replace `zip` to the `itertools.zip_longest` to iterate on the longest sequence, not on the shortest one.

**Comment by devin-petersohn** [comment]
Removing from backport since it is a test update.

**Comment by devin-petersohn** [comment]
Adding back to backports because newer patches depend on this small update
