### ISSUE TITLE
DataFrame min/max functions drop datetime and string columns in default mode while Pandas keeps them

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3759]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.3 LTS

- **Modin version** (`modin.__version__`):

0.12.0

- **Python version**:

Python 3.9.7

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

df = pd.DataFrame([[1, 2.2, np.datetime64('2013-08-01 08:14:37'), "aaa"],
                   [4, 5.5, np.datetime64('2014-08-01 09:13:00'), "bbb"],
                   [7, 8.8, np.datetime64('2015-08-01 09:48:00'), "ccc"]],
                  index=[1, 2, 3],
                  columns=['int', 'float', 'timestamp', 'string'])
print(df)
print(df.dtypes)

print(df.min())
print(df.max())
```

### Describe the problem

Calling `min` or `max` functions on DataFrame with datetime or string object columns makes Modin drop these columns while Pandas in default mode processes them correctly.

**Comment by devin-petersohn** [comment]
This check is the problem:

https://github.com/modin-project/modin/blob/02a23d401f391944bbcf5f540a68113303cf8131/modin/pandas/dataframe.py#L2733-L2773

**Comment by anmyachev** [comment]
It works like in pandas on the [current](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c) master.
