### ISSUE TITLE
Reformat the modin readthedocs main index page to be more easily navigated

### ISSUE THREAD

**Issue by jeffreykennethli** [modin-project/modin#3763]
The current main index page only has top level navbar titles: Getting Started, Supported APIs, etc. but on the main index page we can/should add links since the navbar is not intuitive for everyone, see https://modin.readthedocs.io/en/latest/index.html.

For reference, in pandas' main index page there are four cards that link to the four navbar titles, see [pandas documentation](https://pandas.pydata.org/docs/).

Original comment:
>I feel it a little confusing when I open the main index page, and there's nothing on the left to navigate - I only have a "this page contains" navbar on the right, and I have to notice the upper navbar which is something I'm not used to.

>Can we duplicate the upper menu here on the left then?

>_Originally posted by @vnlitvinov in https://github.com/modin-project/modin/pull/3726#discussion_r759196114_

**Comment by dorisjlee** [comment]
We can also have a "Table of Contents" with links via `.. toctree::` at the bottom of the index page, similar to [this](https://lux-api.readthedocs.io/en/latest/) and [this](https://lux-api.readthedocs.io/). This is good for mobile view when the left bar is minimized.

**Comment by YarShev** [comment]
@dorisjlee, @jeffreykennethli, @mvashishtha, is this issue resolved?

**Comment by dorisjlee** [comment]
This should be resolved now.
