### ISSUE TITLE
REFACTOR: remove redefinition of `_row_lengths` and `_column_widths` functions in `PandasOnDaskDataframe`.

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3780]
Basic implementation should work for `Dask` engine. It already works for `Ray` engine.

Links to basic implementations: https://github.com/modin-project/modin/blob/d590de080dddb7ed715a58d57c602d96322c4dcf/modin/core/dataframe/pandas/dataframe/dataframe.py#L105
https://github.com/modin-project/modin/blob/d590de080dddb7ed715a58d57c602d96322c4dcf/modin/core/dataframe/pandas/dataframe/dataframe.py#L124

Links to `Dask` redefinitions:
https://github.com/modin-project/modin/blob/d590de080dddb7ed715a58d57c602d96322c4dcf/modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py#L47
https://github.com/modin-project/modin/blob/d590de080dddb7ed715a58d57c602d96322c4dcf/modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py#L64

**Comment by vnlitvinov** [comment]
TBH, I would rather we _add_ a specific Ray implementation that also gathers all objects widths in one go instead of doing a loop, this could potentially be a little bit faster.

**Comment by devin-petersohn** [comment]
It should be significantly faster @vnlitvinov.

**Comment by vnlitvinov** [comment]
I wonder if https://github.com/modin-project/modin/pull/4683 and https://github.com/modin-project/modin/pull/4718 actually address this. @anmyachev thoughts?

**Comment by anmyachev** [comment]
> I wonder if #4683 and #4718 actually address this. @anmyachev thoughts?

Really! Now the default implementation is enough, which for both Dask and Ray gather all remote objects at once.
