### ISSUE TITLE
Improve structure for "Getting Started" section

### ISSUE THREAD

**Issue by dorisjlee** [modin-project/modin#3792]
Related to #3687. Suggesting new structure for "Getting Started" section, which is intended as a starting point for Modin users.
 
```
Getting Started/
├─ *Quickstart Guide (minimal install & setup script, 1-line replacement, mini-benchmark to demo speedup, same as updated README)
├─ Installation (pip, conda, source)/
├─ *Example (link to 1-2 notebook ex of how Modin is used for XYZ)
├─ *Tutorial (link to tutorial notebooks)
├─ Using Modin/
│  ├─ Using Modin locally
│  ├─ Using Modin in a cluster
├─ FAQs
├─ Troubleshooting
├─ Why use Modin?/
│  ├─ Modin vs. pandas
│  ├─ Out of Core in Modin
│  ├─ Modin vs. other distributed dataframes (disclaimer/overview)
│  ├─│  ├─ Modin vs. Dask DataFrame (#3779)
│  ├─│  ├─ Modin vs. Koalas
```
`*` indicates that the documentation page would have an associated notebook.
(edited based on thread below)

Currently, the tutorial notebooks are [here](https://github.com/modin-project/modin/blob/master/examples/tutorial/tutorial_notebooks), which is not linked in the current docs (see #2412).

Note that this PR will not include new files for:
```
│  ├─ FAQs
│  ├─ Troubleshooting
```
given that it will be part of #2635.

Beyond the Getting Started Section, the overall top-level guide should be: 

```
Getting Started
Usage Guide
Supported APIs
Developer
Contact
```

**Comment by dorisjlee** [comment]
In progress: 

- [ ]  Quickstart Guide
- [ ]  Quickstart Guide (ipynb)
- [ ]  Installation
- [ ] Using Modin
- [ ] Notebook Example (ipynb)
- [ ] Link to Tutorials

**Comment by jeffreykennethli** [comment]
Regarding the "Getting Started" Structure, I think "Using Modin locally" belongs above "Using Modin in a cluster", given that cluster usage is under active development (not as mature). Even Examples and Tutorial could belong above "Using Modin locally", so something like:

1. Example
2. Tutorial
3. Using Modin locally
4. Using Modin in a cluster

Under "Why Use Modin", I suggest:

1. Modin vs. pandas
2. Out of Core in Modin
3. Modin vs. other

**Comment by jeffreykennethli** [comment]
PR #3816 updates the getting started FAQ and is related to this change.

**Comment by dorisjlee** [comment]
Thanks @jeffreykennethli, agreed that this ordering makes a lot more sense!

**Comment by YarShev** [comment]
I think it would be great to have a similar documentation structure to pandas (see [here](https://pandas.pydata.org/docs/index.html)).

```
.getting_started/ as @dorisjlee proposes
    .quick_start (minimal install & setup script, 1-line replacement, mini-benchmark to demo speedup, same as updated README)
    .installation (pip, conda, source)
    .why_use_modin (comparison with other distributed dataframe implementations)
.usage_guide/
    .examples (what we have now) # this should include not only Modin operation pipeline, but and how much faster are the operations relative to pandas ones.
    .tutorials (what we have now)
    .optimization_guide/notes (recommendations to users on how to better organize their pipeline, perform an operation, etc.)
.developer_guide # as it is now
.supported_apis # as it is now
.advanced_usage # should probably go in usage guide
.contact # as it is now
```

@modin-project/modin-core, @modin-project/modin-omnisci, @modin-project/modin-contributors, thoughts?

**Comment by devin-petersohn** [comment]
Many users only visit one or two pages in our current docs on https://modin.readthedocs.io/en/stable/. I don't like the idea of having to navigate two pages to see quick start, or examples/tutorials. Ideally the most critical doc pages would be at the top of the home page for easy accessibility: 
![image](https://user-images.githubusercontent.com/10732128/146035847-c1a95637-e6c0-4385-9053-fdd33a182e2e.png)

I think we should choose what links are at the top of the page first.

**Comment by YarShev** [comment]
@devin-petersohn, our documentation is growing and put everything onto one page probably doesn't look good. In the near months we likely want to add comprehensive examples, which show Modin usage, performance against to pandas, etc., as well as some optimization notes regarding improving/accelerating a generic query pipeline (like put less NPartitions number in case an operations is performed via `map` operator for a wide dataframe since there is excessive amount of remote partitions, which is much greater than the number of CPUs) and specific operations (like for inner join recommend using a larger dataframe as a left operand and a smaller dataframe as a right operand). I think usage_guide page looks as a good candidate where we would put all examples, tutorials, optimization notes/guide, etc. Does that make sense?

**Comment by dorisjlee** [comment]
I agree with @YarShev that it might not be a great idea to have too many things on the header, but as @devin-petersohn  mentioned, for something very important like the quickstart, it would be worth putting at the top. Everything else like example and tutorials, it would be worth linking to both in the index.rst (home page) and README, while living nested within the user guide. The navigation to these pages would also be helped if we added a TOC tree on the left panel, as described in #3763.

**Comment by YarShev** [comment]
I issued a draft of the usage guide in #3864. Comments/thoughts on improving/expanding it are welcome.

**Comment by dorisjlee** [comment]
> I issued a draft of the usage guide in #3864. Comments/thoughts on improving/expanding it are welcome.

Thanks @YarShev. Is the usage guide intended to be ready by advanced users of Modin? i.e., after reading Getting Started. If so it would probably to rename this advance usage?

**Comment by jeffreykennethli** [comment]
Re: #3864

I like the addition of a section that explains how to use modin better that doesn't dive right into the advanced or experimental features, and I think `Usage Guide` is a good name for it. It makes me think a lot of the `Advanced Features` section could be folded into `Usage Guide` under a `usage_guide/advanced` section.

Any features in `Advanced Usage` we deem to be too experimental can go under a `usage_guide/experimental`.

> order it to be before the "Developer" section?

Agree with this - I think the ordering should be:

```
Getting Started
Usage Guide
Supported APIs
Developer
Contact
```

**Comment by YarShev** [comment]
> I like the addition of a section that explains how to use modin better that doesn't dive right into the advanced or experimental features, and I think `Usage Guide` is a good name for it. It makes me think a lot of the `Advanced Features` section could be folded into `Usage Guide` under a `usage_guide/advanced` section.

@dorisjlee, @jeffreykennethli' comment makes sense to me.

> Agree with this - I think the ordering should be:
> 
> Getting Started
> Usage Guide
> Supported APIs
> Developer
> Contact

I would rename `Developer` section to `Developer Guide` to resemble pandas docs.

**Comment by dorisjlee** [comment]
This new organization sounds good!

**Comment by Garra1980** [comment]
Several thoughts of mine (maybe less for structure but more about content):
https://modin.readthedocs.io/en/latest/getting_started/using_modin.html#apis-supported - not quite clear what APIs are mentioned here
https://modin.readthedocs.io/en/latest/getting_started/using_modin.html#advanced-usage-experimental - this probably should go to our new Advanced usage section

**Comment by Garra1980** [comment]
Probably it's worth to structure Getting Started section somewhat similar to Pandas' one
i.e. reduce installation section leaving only main installation channels, add user-level description of Modin as we agreed (some content could be taken from https://github.com/modin-project/modin/blob/master/examples/tutorial/tutorial_notebooks/introduction notebooks) and put links to other noteboosk with more advanced Modin usage (eg along with xgboost or scikit-learn)
