### ISSUE TITLE
``value_counts`` doesn't work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3813]
When I run at MODIN_STORAGE_FORMAT=omnisci:
```
import numpy as np
import modin.pandas as pd
values = np.array([3, 1, 2, 3, 4, np.nan])
pd.value_counts(values, normalize=True)
```
I have result:
```
3.0    0.333333
1.0    0.166667
2.0    0.166667
4.0    0.166667
NaN    0.166667
dtype: float64
```
But if run:
```
import pandas
pandas.value_counts(values, normalize=True)
```
I have result:
```
3.0    0.4
1.0    0.2
2.0    0.2
4.0    0.2
dtype: float64
```

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment]
This issue is caused by #2896

**Comment by anmyachev** [comment]
The error is reproduced on the [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
