### ISSUE TITLE
``to_numeric`` doesn`t work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3815]
When I run at MODIN_STORAGE_FORMAT=omnisci:
```
import modin.pandas as pd
s = pd.Series([])
pd.to_numeric(s)
```
I have error:
```
KeyError: 'Column F___reduced__ does not exist in schema'
```

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
