### ISSUE TITLE
Series types don`t match at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3825]
When I run at MODIN_STORAGE_FORMAT=omnisci:
```
import numpy as np
import pandas
import modin.pandas as pd
arr = np.random.rand(2 ** 6)
arr[::10] = np.nan
pandas.testing.assert_series_equal(pd.Series(arr), pandas.Series(arr))
```
I have error:
```
AssertionError: Series Expected type <class 'pandas.core.series.Series'>, found <class 'modin.pandas.series.Series'> instead
```

**Comment by vnlitvinov** [comment]
I think the reproducer itself is invalid, `pandas.testing` rightily expects `pandas.Series`, not `modin.panads.Series` as input.

**Comment by anmyachev** [comment]
`pandas.testing.assert_series_equal` doesn't accept Modin object. This is expected behavior.

`df_equals(pd.Series(arr), pandas.Series(arr))` works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
