### ISSUE TITLE
significant reduction in speed after "modin[ray]" upgrade to the latest version

### ISSUE THREAD

**Issue by Peji-moghimi** [modin-project/modin#3846]
System information

- OS Distribution: Centos linux 7
- Memory: 376 GB  DDR4
- Modin version: 0.12.0
- Ray version: 1.4.0
- Python version: 3.5.1

I have been using the following setup for a while now, however, after using `pip install -U "modin[ray]"` yesterday, everything has become significantly slower, e.g. 2h for `read_csv` instead of the usual ~36m and ~3m for `df.sample(frac=0.1).groupby(['col_1', 'col_2'])['col_2'].transform(np.size)` instead of the usual ~1m 36s:

```
import ray
def ray_init():    
    ray.init(_temp_dir="/some/specific/path/ray/tmp/", 
             _plasma_directory="/some/specific/path/ray/",
             _memory=3000000000000,
             object_store_memory=3000000000000)
    os.environ["MODIN_ENGINE"] = "ray"
    os.environ['MODIN_MEMORY']='365000000000'
    return None

ray_init()

import modin.pandas as pd
from modin.config import ProgressBar
ProgressBar.enable()

df_128gb = pd.read_csv('df_128gb.csv', low_memory=True, memory_map=True)
```

Any ideas what could be causing this?

Thanks!
Pej

_Originally posted by @Peji-moghimi in https://github.com/modin-project/modin/issues/3705#issuecomment-991139161_

**Comment by Peji-moghimi** [comment]
I now definitively know that ray==1.1.0 and modin==0.9.1 work significantly faster for `read_csv` at approximately 25 minutes, as oppose to ~2hours with `pip install -U "modin[ray]"`.

**Comment by devin-petersohn** [comment]
Hi @Peji-moghimi thanks for the issue!

Would you be able to try the following to see if there's still a slowdown:

```
pip install modin==0.9.1
pip install ray==1.4
```

It may not work due to API changes in Ray, in which case I will help with next steps. Looking forward to figuring this out!

If it helps, I can also email you.

**Comment by mvashishtha** [comment]
@Peji-moghimi because we haven't received a reply in over 10 months, I'm going to close this issue. I'm happy to help if ray performance is not what you expect. Please just reach out here.
