### ISSUE TITLE
`test_xgboost.py` test fails with big amount of cores

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3877]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 72ca672f3e79cb4cdd589692db2d0e19d696da5c
- **Python version**: 3.8.12
- **Code we can use to reproduce**:
```
conda env create --name modin -f environment-dev.yml && conda activate modin
MODIN_ENGINE=ray MODIN_MEMORY=1000000000 pytest modin/experimental/xgboost/test/test_xgboost.py::test_xgb_with_regression_datasets[load_diabetes-112-DataFrame]
```

### Describe the problem

test works fine on small machines (my laptop or Github Action machine with two cores), but fails on machine with big amount of cores (tested on Intel(R) Xeon(R) Platinum 8276L).

### Source code / logs

```
E               AssertionError:
E               Not equal to tolerance rtol=0.0007, atol=0
E
E               Mismatched elements: 1 / 1 (100%)
E               Max absolute difference: 0.13829
E               Max relative difference: 0.00085634
E                x: array(161.62738)
E                y: array(161.48909)

modin/experimental/xgboost/test/test_xgboost.py:255: AssertionError
```

**Comment by Garra1980** [comment]
cc @prutskov

**Comment by vnlitvinov** [comment]
Could someone (probably @anmyachev or @YarShev) with access to multi-core machine check if this is still relevant please?

**Comment by YarShev** [comment]
Checked on 112 cores, the test passed so closing the issue.
