### ISSUE TITLE
read_excel drops blank rows

### ISSUE THREAD

**Issue by ElLorans** [modin-project/modin#3884]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.12.1
- **Python version**: 3.10.1
- **Code we can use to reproduce**:
```
import pandas as pd
import modin.pandas as md

pd_df = pd.read_excel("testing.xlsx)
md_df = md.read_excel("testing.xlsx")
print(pd_df.shape[0]-md_df.shape[0])
```

### Describe the problem

When reading an excel file, modin drops blank rows, while pandas does not. I don't know how to prevent modin from skipping blank rows.
### Source code / logs

File to reproduce the issue:
[testing.xlsx](https://github.com/modin-project/modin/files/7776925/testing.xlsx)

**Comment by naren-ponder** [comment]
@ElLorans Thanks for filing the Github issue, I was able to reproduce and will be fixing it as part of this release
