### ISSUE TITLE
Modin[all] installation in Python 3.10

### ISSUE THREAD

**Issue by kirui93** [modin-project/modin#3889]
Modin doesn't install on Python 3.10. 
`pip3 install modin[all]` results in an error for building dependencies.

**Comment by devin-petersohn** [comment]
Hi @kirui93 thanks for raising the issue!

I suspect that the problem with `modin[all]` is that Ray does not yet support Python 3.10 (https://github.com/ray-project/ray/issues/19116).

If you want to use Modin with Ray, you will need to downgrade your Python version until Ray can support Python 3.10. If you prefer to stay on Python 3.10, you can `pip install modin[dask,remote,spreadsheet,sql]`. That will install everything but Ray.

Let me know if that works for you! Thanks again for the issue!

**Comment by mvashishtha** [comment]
Ray now supports python 3.10!  ray 2.0.0, 1.13.0 are both available on Python 3.10.4.
