### ISSUE TITLE
Integrate pyright type checking

### ISSUE THREAD

**Issue by jeffreykennethli** [modin-project/modin#3899]
For https://github.com/modin-project/modin/issues/74 adding type hints to the modin repo, it's helpful to integrate a type checker so that we can incrementally and consistently update the codebase. [pyright](https://github.com/microsoft/pyright) is a good option for this, as [simon-mo mentioned here](https://github.com/modin-project/modin/issues/74#issuecomment-577320843).

To integrate pyright, we need to add a [pyrightconfig.json](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) to the repo, recommend that modin contributors install pyright, either:
- as a [VSCode extension](https://github.com/microsoft/pyright#vs-code-extension)
  - both [pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and [python in vscode](https://marketplace.visualstudio.com/items?itemName=ms-python.python) run pyright in the backend
- via [pip/conda](https://github.com/microsoft/pyright#command-line)
- vim/emacs/sublime text also have support

Then we should add pyright to our CI via presumbit check, see [pyright docs](https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md) and our [contributing section](https://github.com/modin-project/modin/tree/master/contributing).

**Comment by mvashishtha** [comment]
@jeffreykennethli I'm going to close this because we're starting to cover the codebase with MyPy as in #4619. Please re-open and comment here if we need to do something else for this issue.
