### ISSUE TITLE
Broken links in "Supported APIs" table

### ISSUE THREAD

**Issue by dorisjlee** [modin-project/modin#3922]
Some links to the pandas documentation are broken in the [Supported APIs page](https://modin.readthedocs.io/en/latest/supported_apis/dataframe_supported.html) and need to be updated (e.g., `as_blocks`, `as_matrix`, etc.)

**Comment by susmitpy** [comment]
@mvashishtha I am scraping all broken links, will comment in 5 minutes

**Comment by mvashishtha** [comment]
@susmitpy Thanks very much. Would you like to make a pull request to fix the links as well?

**Comment by susmitpy** [comment]
@mvashishtha There are a lot of broken links, some of them are deprecated

**Comment by susmitpy** [comment]
@mvashishtha  Please find the broken links on API docs of DataFrame:
[('as_blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_blocks.html#pandas.DataFrame.as_blocks'), ('as_matrix', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_matrix.html#pandas.DataFrame.as_matrix'), ('blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.blocks.html#pandas.DataFrame.blocks'), ('clip_lower', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_lower.html#pandas.DataFrame.clip_lower'), ('clip_upper', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_upper.html#pandas.DataFrame.clip_upper'), ('from_items', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_items.html#pandas.DataFrame.from_items'), ('ftypes', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ftypes.html#pandas.DataFrame.ftypes'), ('to_dense', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dense.html#pandas.DataFrame.to_dense'), ('to_msgpack', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_msgpack.html#pandas.DataFrame.to_msgpack'), ('to_sparse', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sparse.html#pandas.DataFrame.to_sparse')]

**Comment by susmitpy** [comment]
@mvashishtha The methods are deprecated

**Comment by mvashishtha** [comment]
@susmitpy yes, I see that they are all deprecated in pandas and they don't work in Modin now either. Would you be willing to make a PR removing these methods from the list of supported API methods?

**Comment by susmitpy** [comment]
Sure @mvashishtha I will do that
