### ISSUE TITLE
Documentation build is broken

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3927]
The [build fails](https://readthedocs.org/projects/modin/builds/15737721/) because of the new version of ["sphinx-issues" package](https://pypi.org/project/sphinx-issues/#history), we have to pin it to the latest functional version.

Issue at the "sphinx-issue" side: sloria/sphinx-issues#125. 
TODO: remove the pin on our side after the next release of the sphinx-issue package.

**Comment by sloria** [comment]
FYI sphinx-issues==3.0.1 has been released with the fix

**Comment by dchigarev** [comment]
@sloria thanks for the update!
