### ISSUE TITLE
Automatically test tutorial notebooks in CI

### ISSUE THREAD

**Issue by dorisjlee** [modin-project/modin#3938]
Automatically run and test notebooks through [papermill](https://papermill.readthedocs.io/en/latest/) or something like [this](https://github.com/treebeardtech/nbmake-action) to ensure that the examples are running with the latest code.

**Comment by devin-petersohn** [comment]
The tutorials require some user-provided changes. What we might want to do is add a `tutorial_SOLUTIONS` or something and test those. As-is, tutorials don't have a solution anyway, which is another issue 😄 .

**Comment by YarShev** [comment]
@devin-petersohn, what if we create executed copies of the tutorials and test those?
