### ISSUE TITLE
pandas==1.4.0rc0 FilePathOrBuffer deprecation breaks modin import

### ISSUE THREAD

**Issue by jeffreykennethli** [modin-project/modin#3947]
### System information
- **OS Platform and Distribution**: Mac 12.0.1
- **Modin version** (`modin.__version__`): 0.12.0 - pandas==1.4.0rc0 [pre-release](https://github.com/pandas-dev/pandas/releases/tag/v1.4.0rc0)
- **Python version**: 3.8.8
- **Code we can use to reproduce**:

```
python -m pip install --upgrade --pre pandas==1.4.0rc0
ipython

# (in ipython)
import modin.pandas as pd

# throws error:
# cannot import name 'FilePathOrBuffer' from 'pandas._typing' (/Users/jeffreyli/opt/anaconda3/lib/python3.8/site-packages/pandas/_typing.py)
```

### Describe the problem
The Class FilePathOrBuffer no longer exists in pandas typing, after this PR https://github.com/pandas-dev/pandas/pull/43951.

**Comment by jeffreykennethli** [comment]
This is also caught by our CI in a workflow run that tests the pre-release candidate: https://github.com/modin-project/modin/actions/runs/1690328476

**Comment by anmyachev** [comment]
We have already updated pandas dependency to `1.4.1`.
