### ISSUE TITLE
Subclassing modin.pandas Dataframe

### ISSUE THREAD

**Issue by denish44** [modin-project/modin#3948]
Apologies if this follow under bug but I wasn't sure. I was trying to subclass modin to add on additional methods for our needs but I noticed that the subclassing works for the first result however when the dataframe is filtered or when a new dataframe is returned we always get a instance of modin dataframe rather than our own dataframe that we extended from modin.pandas dataframe. 

I did see traces of code where the return is `type(self)(...)` which would return our extended dataframe but make place the return is `Dataframe(...)` explicitly.

**Comment by devin-petersohn** [comment]
Hi @denish44, thanks for posting!

I definitely agree, ideally we will always use the `__constructor__` pattern we created, looking through the code there are some places that haven't been updated in a while that still use `DataFrame(...)`. For example:

https://github.com/modin-project/modin/blob/6550939753c76e896ef2bfd65bb9468d6ad161d7/modin/pandas/dataframe.py#L336

I agree, we should make these changes to ensure that the DataFrame can be subclassed. If you are able, and want to make the subset of changes necessary for your usecase I would be happy to accept a PR that solves part of the issue in the interest of unblocking you.

**Comment by denish44** [comment]
Not blocked by this but it is good first task to contribute. I will work on getting a PR ready for this, since the pattern is already setup don't think it will be too bad of change. It might be a few days.

**Comment by vnlitvinov** [comment]
@denish44 do you need any help from us to get a PR to fix this?

**Comment by YarShev** [comment]
@denish44, we merged #5485. Please let us know if this works for you.
