### ISSUE TITLE
Modin incompatibility with Seaborn boxplot

### ISSUE THREAD

**Issue by labanyamukhopadhyay** [modin-project/modin#3967]
### System information
- **Modin version** (`modin.__version__`): 0.12.0+62.g3c740dbf
- **Python version**: 3.7

Creating a boxplot using seaborn results in an error.

#### Source code
```
plt.figure(figsize=(10, 10))
sns.boxplot(y=df_1['Title'], x=df_1['Salary'],order=sorted_index_descent)
plt.ylabel('')
plt.title('Salaries for Data Science Positions')
plt.show() 
```
#### Error message
![Screen Shot 2022-01-13 at 2 12 43 PM](https://user-images.githubusercontent.com/17665008/149417290-71f4d31a-3cff-43b9-affc-351f2aa780eb.png)

![Screen Shot 2022-01-13 at 2 10 15 PM](https://user-images.githubusercontent.com/17665008/149417041-fb2c0b76-d2a9-4016-91b5-c0b1f9dbafe5.png)

**Comment by vnlitvinov** [comment]
@labanyamukhopadhyay could you please re-check if this still happens?

**Comment by labanyamukhopadhyay** [comment]
Seaborn and specifically `sns.boxplot` as in the example above are currently interoperable with Modin. Users will have to install seaborn from Github for its most recent updates: `pip install "seaborn @ git+https://github.com/mwaskom/seaborn"`
