### ISSUE TITLE
using DataFrame().loc when column location does not exists throws KeyError instead of creating a new column

### ISSUE THREAD

**Issue by eavidan** [modin-project/modin#399]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macos 10.14.2
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.2.5
- **Python version**: 3.6.4
- **Exact command to reproduce**: snippet below

### Describe the problem
Dataframe().loc fails with KeyError when using loc with column or row index which does not exists. The expected behaviour from pandas is to create that column

### Source code / logs

```
# works

import pandas as pd

df = pd.DataFrame({'x': ['1', '2', '3']})
df.loc[1, 'transformed_to_numeric'] = False
print(df)

# does not work

import modin.pandas as pd

df = pd.DataFrame({'x': ['1', '2', '3']})
df.loc[1, 'transformed_to_numeric'] = False
print(df)
```

**Comment by eavidan** [comment]
@devin-petersohn the issue seems to be with `_compute_lookup()` in `indexing.py`.
I was able to solve this locally with some conditional inserts, but it does not feel very elegant or efficient.

```py
    def _compute_lookup(self, row_loc, col_loc) -> Tuple[pandas.Index, pandas.Index]:
        if isinstance(row_loc, list) and len(row_loc) == 1:
            if (
                isinstance(self.qc.index.values[0], np.datetime64)
                and type(row_loc[0]) != np.datetime64
            ):
                row_loc = [pandas.to_datetime(row_loc[0])]

            if row_loc[0] not in self.qc.index:
                labels = self.qc.index.insert(len(self.qc.index), row_loc[0])
                self.qc = self.qc.reindex(labels=labels, axis=0)
                self.df._update_inplace(new_query_compiler=self.qc)

        if isinstance(col_loc, list) and len(col_loc) == 1:
            if col_loc[0] not in self.qc.columns:
                columns = self.qc.columns.insert(len(self.qc.columns), col_loc[0])
                self.qc = self.qc.reindex(labels=columns, axis=1)
                self.df._update_inplace(new_query_compiler=self.qc)

        row_lookup = self.qc.index.to_series().loc[row_loc].index
        col_lookup = self.qc.columns.to_series().loc[col_loc].index
        return row_lookup, col_lookup
```

**Comment by devin-petersohn** [comment]
Hi @eavidan, thanks for looking into this!

This seems like more of an issue in `__setitem__` in `indexing.py`. The `LocIndexer` should be the only class that has this because `ILocIndexer` does not support setting new columns. We do something similar to what needs to be done in `DataFrame.__setitem__`.

The conditions you added to `_compute_lookup` should be close to what is needed there.

**Comment by eavidan** [comment]
makes sense. I will take this if thats ok. 
will move the conditions to `__setitem__` in `indexing.py`. anything else to consider?

**Comment by devin-petersohn** [comment]
I can't think of anything else to consider, but please let me know if you run into something that is problematic.
