### ISSUE TITLE
REFACTOR: remove code duplication for `PandasOnRayDataframePartitionManager`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4000]
In the current implementation, the following methods of `PandasOnRayDataframePartitionManager` class (child class of `PandasDataframePartitionManager`) are overridden just to apply the `progress_bar_wrapper` decorator:
- map_partitions
- lazy_map_partitions
- map_axis_partitions
- _apply_func_to_list_of_partitions
- apply_func_to_select_indices
- apply_func_to_select_indices_along_full_axis
- apply_func_to_indices_both_axis
- binary_operation

Moving the decorator to the base class will remove the duplication of functions.

**Comment by devin-petersohn** [comment]
@anmyachev I don't think it's possible to move since there's quite a bit of Ray specific code needed for the progress bar.

**Comment by vnlitvinov** [comment]
What we can do is we can replace the pieces like
```python
    @classmethod
    @progress_bar_wrapper
    def lazy_map_partitions(cls, partitions, map_func):
        """
        Apply `map_func` to every partition in `partitions` *lazily*.

        Parameters
        ----------
        partitions : np.ndarray
            A NumPy 2D array of partitions to perform operation on.
        map_func : callable
            Function to apply.

        Returns
        -------
        np.ndarray
            A NumPy array of partitions.
        """
        return super(PandasOnRayDataframePartitionManager, cls).lazy_map_partitions(
            partitions, map_func
        )
```
with (untested, illustrating the idea)
```python
    lazy_map_partitions = progress_bar_wrapper(GenericRayDataframePartitionManager.lazy_map_partitions)
```

**Comment by anmyachev** [comment]
> 

This doesn't work because `classmethod` decorator should be applied last.

**Comment by mvashishtha** [comment]
@anmyachev @vnlitvinov can we use [inherit_doctsrings](https://github.com/modin-project/modin/blob/3f985ed6864cc1b5b587094d75ca5b2695e4139f/modin/utils.py#L311) to inherit the parent class docstrings?

**Comment by vnlitvinov** [comment]
> This doesn't work because `classmethod` decorator should be applied last (#4895).

Okay, so then do just
```python
    lazy_map_partitions = classmethod(progress_bar_wrapper(GenericRayDataframePartitionManager.lazy_map_partitions.__func__))
```

maybe even defining a small helper method like
```python
def _make_wrapped_method(name):
    return classmethod(progress_bar_wrapper(getattr(GenericRayDataframePartitionManager, name).__func__))

class RayDataframePartitionManager:
    lazy_map_partitions = _make_wrapped_method('lazy_map_partitions')
```

**Comment by anmyachev** [comment]
> @anmyachev @vnlitvinov can we use [inherit_doctsrings](https://github.com/modin-project/modin/blob/3f985ed6864cc1b5b587094d75ca5b2695e4139f/modin/utils.py#L311) to inherit the parent class docstrings?

I think we can, but this only solves part of the issue of code duplication.
