### ISSUE TITLE
scripts/ is getting installed in site-packages

### ISSUE THREAD

**Issue by denish44** [modin-project/modin#4005]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): 0.12.0
- **Python version**:  3.8
- **Code we can use to reproduce**:

I believe the scripts/ folder is getting installed in site-packages with modin. I used ```pip install modin[dask]```. We ran into an import issue since we have a scripts module (conflict between using ours vs the site-packages installed.) but when we install modin we found that your scripts module is getting installed in the site-packages. I am not sure if this is a mistake or intentional.

**Comment by devin-petersohn** [comment]
Thanks @denish44 this is resolved.
