### ISSUE TITLE
Propagate index in Modin frame raises error when setting column

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#4026]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

This line here
https://github.com/modin-project/modin/blob/406af7c8d6c973d680ab9e07d6edc13eb69481f0/modin/core/dataframe/pandas/dataframe/dataframe.py#L534
Needs to be moved to the end of the function and be unindented to be outside of the if statement right? Cause otherwise we will error out whenever we try and propagate columns.

**Comment by YarShev** [comment]
Closed in #4029.
