### ISSUE TITLE
``dataframe.first()`` and ``dataframe.last()`` don`t work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#4050]
When I run:
```
import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals
import modin.config as cfg
cfg.StorageFormat.put('omnisci')

i = pd.date_range("2010-04-09", periods=400, freq="2D")
modin_df = pd.DataFrame({"A": list(range(400)), "B": list(range(400))}, index=i)
pandas_df = pandas.DataFrame({"A": list(range(400)), "B": list(range(400))}, index=i)
df_equals(modin_df.first("3D"), pandas_df.first("3D"))
```
I have error:
```
AssertionError: (None, <2 * Days>)
```
Also I have this error for ``last``:
```
df_equals(modin_df.last("3D"), pandas_df.last("3D"))
```

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment]
> @modin-project/modin-omnisci could someone please check if this still happens?

The issue is still reproducible on the latest master:

pandas/_testing/asserters.py", line 1006, in assert_series_equal
    assert lidx.freq == ridx.freq, (lidx.freq, ridx.freq)
AssertionError: (None, <2 * Days>)

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
