### ISSUE TITLE
AttributeError: type object '_DTypeMeta' has no attribute '_abstract'

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#4053]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.12.1
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

If you run all the files in the test, there will be an error.

```shell
set MODIN_EXPERIMENTAL=1
set MODIN_ENGINE=Python
python -m pytest --simulate-cloud=normal modin/pandas/test/dataframe/test_indexing.py
```

If you run only a test where there is an error, there will be no error.

```shell
set MODIN_EXPERIMENTAL=1
set MODIN_ENGINE=Python
python -m pytest --simulate-cloud=normal modin/pandas/test/dataframe/test_indexing.py::test_loc_nested_assignment[float_nan_data]
```

The error occurs only when the entire test file is run.

### Describe the problem

The error appeared after PR https://github.com/modin-project/modin/pull/3742. It appears only if you run all the tests at once. If you then run one test that fell with an error, then there will be no error. Thus, it is quite difficult to reproduce the error.

### Source code / logs

```
======= Remote Traceback =======
 ... 
E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 338, in _dispatch_request
E       res = self._HANDLERS[handler](self, *args)
E     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 630, in _handle_call
E       return obj(*args, **dict(kwargs))
E     File "C:\prog\modin\modin\experimental\cloud\rpyc_proxy.py", line 34, in _batch_loads
E       return tuple(pickle.loads(item) for item in items)
E     File "C:\prog\modin\modin\experimental\cloud\rpyc_proxy.py", line 34, in <genexpr>
E       return tuple(pickle.loads(item) for item in items)
E   AttributeError: type object '_DTypeMeta' has no attribute '_abstract' 
```

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
