### ISSUE TITLE
``dataframe.count()``, ``dataframe.min()``, ``dataframe.mean()`` and ``dataframe.max()`` don`t work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#4091]
When I run:
```
import modin.pandas as pd
from modin.pandas.test.utils import test_data_large_categorical_dataframe
import modin.config as cfg
cfg.StorageFormat.put('omnisci')

modin_df = pd.DataFrame(test_data_large_categorical_dataframe)
modin_df.count()
```
I have error:
```
TypeError: expected bytes, int found
```
Also this error have functions ``min``, ``max``, ``mean``:
```
from modin.pandas.test.utils import test_data

modin_df = pd.DataFrame(test_data["float_nan_data"])
modin_df.T.min()
```

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment]
This issue is not reproducible, however, the following warning is printed:
UserWarning: <function DataFrame.transpose> is not currently supported by ExperimentalOmnisciOnNative, defaulting to pandas implementation.

**Comment by AndreyPavlenko** [comment]
Closing this issue as not reproducible.
