### ISSUE TITLE
Pandas error when rendering Modin DataFrame in Jupyter

### ISSUE THREAD

**Issue by paulovn** [modin-project/modin#4105]
Hi, I'm getting an exception

`OptionError: 'Pattern matched multiple keys'`

when trying to display a Modin DataFrame in Jupyter. My environment has
 * modin: 0.13.0
 * pandas: 1.4.0

I have tracked the source of the exception to these lines:

https://github.com/modin-project/modin/blob/cafd213b5f116dbf26a22feaaf05bfc05e435a6a/modin/pandas/dataframe.py#L228-L229

... if I change that to

```Python
        num_rows = pandas.get_option("display.max_rows") or 60
        num_cols = pandas.get_option("display.max_columns") or 20
```
... the problem goes away. I don't know if this is a specific problem with these versions of modin and Pandas

**Comment by devin-petersohn** [comment]
Hi @paulovn thanks for reporting!

I see this as well, since you have already done the triage and identified the source, do you want to put a PR in for the fix?

Thanks again!

**Comment by paulovn** [comment]
Sure, here it goes: https://github.com/modin-project/modin/pull/4109
