### ISSUE TITLE
ModuleNotFoundError: No module named 'modin.pandas'; 'modin' is not a package

### ISSUE THREAD

**Issue by cinnqi** [modin-project/modin#4110]
hello, when I am trying to install modin. My pandas version is 1.4.0.
after this command "pip install modin[all]", I get the ModuleNotFoundError. So I uninstalled modin, and tried this command"pip install git+https://github.com/modin-project/modin", it also won't work. 
What should I do to fix this?
Thank you

**Comment by cinnqi** [comment]
Question solved

**Comment by devin-petersohn** [comment]
@cinnqi Can you share how you solved this so others who find it can also benefit from your experience? Thanks!
