### ISSUE TITLE
read_excel do not support "encoding" keyword

### ISSUE THREAD

**Issue by Clem-D** [modin-project/modin#414]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  CentOS Linux release 7.5.1804 (Core)
- **Modin installed from (source or binary)**: pip install modin
- **Modin version**: 0.2.5
- **Python version**: 3.5.2
- **Exact command to reproduce**: `df = pd.read_excel( xlsxfile, encoding="latin1",sheetname='Data')`

### Describe the problem
When we use "encoding" with modin we get the following error :  `read_excel() got an unexpected keyword argument 'encoding'` but it works with panda.

This issue follows #405 

[read_excel doc from panda](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html)

**Comment by devin-petersohn** [comment]
Resolved by #415

**Comment by Clem-D** [comment]
Thanks a lot !
I install modin with pip, when the last changes will be available ?

**Comment by devin-petersohn** [comment]
You can try now if you install from the github master branch: [link to docs](https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch).

We are planning a release once we merge #413, #407 and a few others. We will push a new release candidate before then. Hopefully it will be only a couple of days.

**Comment by Clem-D** [comment]
Hi, I've just install modin v0.3.0 my feedbacks : 

1. I had to do` pip install dask` to make it works (even after `pip install modin`) otherwise I got 'ImportError: No module named 'dask'`

2. Now I got the following attribute error : 
`Can only use .str accessor with string values, which use np.object_ dtype in pandas` when I do something like `df['foo'] = df['foo'].str.replace('.', ',')`

**Comment by devin-petersohn** [comment]
Thanks @Clem-D for this feedback! We tested installing on a new virtualenv, but it seems that if upgrading Modin, Dask is a requirement. I will fix it so that Dask is only a requirement for `pip install modin[dask]`. 

Does the `df['foo'] = df['foo'].str.replace('.', ',')` work in pandas? I am able to run `.str` as long as it is valid in pandas. It might be good to create a new issue to track this so I can reproduce/fix this issue.
