### ISSUE TITLE
BUG: SeriesGroupBy has no attribute value_counts

### ISSUE THREAD

**Issue by ericct** [modin-project/modin#4154]
### System information
- **OS Platform and Distribution**: Linux fedora 5.15.12-200.fc35.x86_64 
- **Modin installed from**: binary
- **Modin version**: 0.13.0
- **Python version**: 3.8.12
- **Exact command to reproduce**: execute the code below

### Describe the problem

When executing the code below, it crashes with `AttributeError: 'SeriesGroupBy' object has no attribute 'value_counts'`. Of course, it works with pandas.

### Source code / logs

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randint(1000000000, 1000000010, size=(200000,2)),columns=['C1','C2'])
by_c1 = df.groupby("C1")
c2 = by_c1["C2"]
print(c2.value_counts())
```

**Comment by mvashishtha** [comment]
@ericct Thank  you for reporting this! I confirmed that the bug applies even at the latest Modin source version, 0.13.0+11.g62179ef6. Modin should at least default to pandas for this function, if not implement its own distributed version.
