### ISSUE TITLE
Modin `describe` output different from pandas for empty dataframes

### ISSUE THREAD

**Issue by c3-cjazra** [modin-project/modin#4191]
### System information
ray 1.9.2
modin 0.12.0
pandas 1.3.4

### Describe the problem

In modin, the describe result of an empty dataframe is the count, unique, top, and freq format, even if the dtypes are specified to numeric types. In pandas, if the dtypes are specified as numeric for an empty dataframe, the describe format count, mean, std, min, max.

```
modin_df = modin_pd.DataFrame(columns=['A', 'B'], dtype=(np.int64, np.float64))

modin_df.describe()
—
A	B
count	0	0
unique	0	0
top	NaN	NaN
freq	NaN	NaN
```

Pandas seems to properly looks at `dtypes` and provide the description relevant to numerical numbers
``` 
pandas_df = pandas_pd.DataFrame(columns=['A', 'B'], dtype=(np.int64, np.float64))

pandas_df.describe(percentiles=[0.25, 0.5, 0.75])
—
A	        B
count	0.0	0.0
mean	NaN	NaN
std	        NaN	NaN
min	        NaN	NaN
25%	NaN	NaN
50%	NaN	NaN
75%	        NaN	NaN
max	        NaN	NaN
```

**Comment by mvashishtha** [comment]
@c3-cjazra thanks for reporting this bug! I can reproduce it on Modin version 0.13.0+22.gaebdb522.

**Comment by mvashishtha** [comment]
Modin defaults to pandas for describing an empty dataframe, but it loses types when it converts empty Modin frames to pandas. Fixing #4060 should fix this issue, too.

**Comment by anmyachev** [comment]
Reproducer shows the same output for pandas and Modin on current master: 5b297a146e83d99a29fcfcaa3dc7dc20b60d02e4.

```bash
>>> print(df.describe())     
UserWarning: `DataFrame.describe` for empty DataFrame is not currently supported by PandasOnDask, defaulting to pandas implementation.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.
         A    B
count  0.0  0.0
mean   NaN  NaN
std    NaN  NaN
min    NaN  NaN
25%    NaN  NaN
50%    NaN  NaN
75%    NaN  NaN
max    NaN  NaN
>>> print(pdf.describe())
         A    B
count  0.0  0.0
mean   NaN  NaN
std    NaN  NaN
min    NaN  NaN
25%    NaN  NaN
50%    NaN  NaN
75%    NaN  NaN
max    NaN  NaN
```
