### ISSUE TITLE
Custom logging is not working after `import modin.pandas as pd`

### ISSUE THREAD

**Issue by Kotsakis** [modin-project/modin#4199]
I have a custom root logger and a special formatter. After importing modin.pandas, i cannot go back to that.

Reproducible example

```
import os
import logging
import logging.config


def initialise_logger(config):
    """
    Args:
        section (str): the log_configuration section for the service. Defaults to "log_configuration".

    """
    logging.config.fileConfig(fname=config, disable_existing_loggers=False)

    old_factory = logging.getLogRecordFactory()

    def my_record_factory(*args, **kwargs):
        """
        Standardized method to expose LogRecordFactory so new parameters
        that are semi static can be injected into CBD log records.

        Returns:
            [LogRecord]: Modified log record
        """
        record = old_factory(*args, **kwargs)

        # project and any other keys that may be used in index creation in elasticsearch
        # must be lowercase ( in scenario where kafka logging is used )
        record.project = "alex"
        record.microservice = "alex"
        record.hostname = "alex"
        record.local_ip = "alex"

        # all Mesos containers in production have this environment variable.
        # if it is not present, then we are not in production
        record.mesos_task_id = "alex"

        return record

    logging.setLogRecordFactory(my_record_factory)


def other():

    text = """
    [loggers]
    keys=root

    [handlers]
    keys=consoleHandler

    [formatters]
    keys=consoleFormatter

    [logger_root]
    level=INFO
    handlers=consoleHandler

    [handler_consoleHandler]
    class=StreamHandler
    level=INFO
    formatter=consoleFormatter
    args=(sys.stdout,)

    [handler_rayHandler]
    class=NullHandler

    [formatter_consoleFormatter]
    format=%(asctime)s.%(msecs)03d %(project)s %(microservice)s %(levelname)s %(hostname)s %(local_ip)s %(name)s %(filename)s %(lineno)d %(funcName)s %(module)s %(processName)s %(process)d %(threadName)s %(thread)d  %(message)s
    datefmt=%Y-%m-%d %H:%M:%S
    """

    config_path = os.path.join(os.getcwd(), "special_config.ini")
    with open(config_path, "w") as conffile:
        conffile.write(text)

    initialise_logger(config="special_config.ini")
    logger = logging.getLogger()

    logger.info(f"modin not imported")

    import modin.pandas as pd
    remote_df = pd.DataFrame([1, 2, 3, 4])
    logging.info(f"length: {len(remote_df)}")


if __name__ == '__main__':
    other()

```

This yields

```
`--- Logging error ---
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 434, in format
    return self._format(record)
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 430, in _format
    return self._fmt % record.__dict__
KeyError: 'project'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 666, in format
    s = self.formatMessage(record)
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 635, in formatMessage
    return self._style.format(record)
  File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 436, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'project'
Call stack:
  File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/vagrant/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/vagrant/dist-repos/cbd/stab/test_cbd3/test.py", line 305, in <module>
    other()
  File "/vagrant/dist-repos/cbd/stab/test_cbd3/test.py", line 302, in other
    logging.info(f"length: {len(remote_df)}")
Message: 'length: 4'
Arguments: ()

Process finished with exit code 0`
```

There is definitely something going on with `ray.autoscale._private.cli_logging.py` under the hood.

Any ideas how to fix that?

**Comment by YarShev** [comment]
cc @modin-project/modin-ray

**Comment by vnlitvinov** [comment]
@Kotsakis would it be possible to provide a self-contained reproducer, so we can debug the issue on our end, as this is much easier than to guesstimate basing on stacktraces only?

**Comment by arunjose696** [comment]
> I have a custom root logger and a special formatter. After importing modin.pandas, i cannot go back to that.
> 
> Reproducible example
> 
> ```
> import os
> import logging
> import logging.config
> 
> 
> def initialise_logger(config):
>     """
>     Args:
>         section (str): the log_configuration section for the service. Defaults to "log_configuration".
> 
>     """
>     logging.config.fileConfig(fname=config, disable_existing_loggers=False)
> 
>     old_factory = logging.getLogRecordFactory()
> 
>     def my_record_factory(*args, **kwargs):
>         """
>         Standardized method to expose LogRecordFactory so new parameters
>         that are semi static can be injected into CBD log records.
> 
>         Returns:
>             [LogRecord]: Modified log record
>         """
>         record = old_factory(*args, **kwargs)
> 
>         # project and any other keys that may be used in index creation in elasticsearch
>         # must be lowercase ( in scenario where kafka logging is used )
>         record.project = "alex"
>         record.microservice = "alex"
>         record.hostname = "alex"
>         record.local_ip = "alex"
> 
>         # all Mesos containers in production have this environment variable.
>         # if it is not present, then we are not in production
>         record.mesos_task_id = "alex"
> 
>         return record
> 
>     logging.setLogRecordFactory(my_record_factory)
> 
> 
> def other():
> 
>     text = """
>     [loggers]
>     keys=root
> 
>     [handlers]
>     keys=consoleHandler
> 
>     [formatters]
>     keys=consoleFormatter
> 
>     [logger_root]
>     level=INFO
>     handlers=consoleHandler
> 
>     [handler_consoleHandler]
>     class=StreamHandler
>     level=INFO
>     formatter=consoleFormatter
>     args=(sys.stdout,)
> 
>     [handler_rayHandler]
>     class=NullHandler
> 
>     [formatter_consoleFormatter]
>     format=%(asctime)s.%(msecs)03d %(project)s %(microservice)s %(levelname)s %(hostname)s %(local_ip)s %(name)s %(filename)s %(lineno)d %(funcName)s %(module)s %(processName)s %(process)d %(threadName)s %(thread)d  %(message)s
>     datefmt=%Y-%m-%d %H:%M:%S
>     """
> 
>     config_path = os.path.join(os.getcwd(), "special_config.ini")
>     with open(config_path, "w") as conffile:
>         conffile.write(text)
> 
>     initialise_logger(config="special_config.ini")
>     logger = logging.getLogger()
> 
>     logger.info(f"modin not imported")
> 
>     import modin.pandas as pd
>     remote_df = pd.DataFrame([1, 2, 3, 4])
>     logging.info(f"length: {len(remote_df)}")
> 
> 
> if __name__ == '__main__':
>     other()
> ```
> 
> This yields
> 
> ```
> `--- Logging error ---
> Traceback (most recent call last):
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 434, in format
>     return self._format(record)
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 430, in _format
>     return self._fmt % record.__dict__
> KeyError: 'project'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 1083, in emit
>     msg = self.format(record)
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 927, in format
>     return fmt.format(record)
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 666, in format
>     s = self.formatMessage(record)
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 635, in formatMessage
>     return self._style.format(record)
>   File "/home/vagrant/miniconda3/envs/cbd3-ray/lib/python3.9/logging/__init__.py", line 436, in format
>     raise ValueError('Formatting field not found in record: %s' % e)
> ValueError: Formatting field not found in record: 'project'
> Call stack:
>   File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
>     main()
>   File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 1476, in run
>     return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
>   File "/home/vagrant/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/vagrant/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/vagrant/dist-repos/cbd/stab/test_cbd3/test.py", line 305, in <module>
>     other()
>   File "/vagrant/dist-repos/cbd/stab/test_cbd3/test.py", line 302, in other
>     logging.info(f"length: {len(remote_df)}")
> Message: 'length: 4'
> Arguments: ()
> 
> Process finished with exit code 0`
> ```
> 
> There is definitely something going on with `ray.autoscale._private.cli_logging.py` under the hood.
> 
> Any ideas how to fix that?

On Running the code snipet in this issue, there is no error, I am able to use both `logging.info` also see the logs being displayed before and after modin import.

It also works without issues when using, just checked this additionally

```
from modin.config import LogMode
LogMode.enable()
```

**Comment by anmyachev** [comment]
The same issue in Ray: https://github.com/ray-project/ray/issues/22312

**Comment by YarShev** [comment]
@anmyachev, do you think we can close this issue and keep track of the one in Ray?

**Comment by anmyachev** [comment]
> @anmyachev, do you think we can close this issue and keep track of the one in Ray?

think so.
