### ISSUE TITLE
Groupby + agg sometimes ignores `numeric_only` arg

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#420]
### Describe the problem

First reported here: https://github.com/modin-project/modin/pull/413#issuecomment-455852817

If a partition only contains non-numeric data, pandas will ignore the `numeric_only` kwarg and do the operation anyway.

### Source code / logs

```python
df = pd.DataFrame({'A': [2, 2, 2, 3, 4],
                    'B': [5, 6, 7, 8, 9],
                    'C': ['a', 'b', 'c', 'd', 'e']})

df = df.groupby('A').sum(numeric_only=True)
print(df)
```

**Comment by mvashishtha** [comment]
This is fixed at least by version bd326f1c4175102489f08d271a53cf374bd9125e.
