### ISSUE TITLE
Same error but with text files 

### ISSUE THREAD

**Issue by shashankrustagiiiitdelhi** [modin-project/modin#4200]
### System information
Google Colab
Latest version of python

### Describe the problem

UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-49-1f10ec012427>](https://localhost:8080/#) in <module>()
     14   for file in files:
     15     with open(os.path.join(root,file)) as p:
---> 16       l.append([p.read() for file in files])

1 frames
[/usr/lib/python3.7/codecs.py](https://localhost:8080/#) in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 9: invalid continuation byte

**Comment by mvashishtha** [comment]
@shashankrustagiiiitdelhi I'm closing this bug because you haven't posted more information. Please comment here if you still need help.
