### ISSUE TITLE
test_join_sort.py in CI failed by timeout with new Dask release - 2022.2.0

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4202]
Error: https://github.com/modin-project/modin/runs/5195622251?check_suite_focus=true

Dask release - https://github.com/dask/dask/releases/tag/2022.02.0

Fastest option here - pin `dask<2022.2.0`, but it also requires an investigation into the cause.

**Comment by anmyachev** [comment]
cc @modin-project/modin-core

**Comment by dchigarev** [comment]
Besides fixing the perf issue, I think we can revise `test_join_sort` suites in order to reduce them. [Only this one test](https://github.com/modin-project/modin/blob/b7027597985a442734a57949d72e3fa0625b4d43/modin/pandas/test/dataframe/test_join_sort.py#L393-L517) generates up to 17.000+ cases (around ~35% of all tests for dataframes).

**Comment by anmyachev** [comment]
> So new Dask release has caused performance to degrade on these tests to the point where they always timeout?

Some kind of memory problem occurs, which leads to a timeout ([example](https://github.com/modin-project/modin/runs/5206389461?check_suite_focus=true)):
```bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise TimeoutError("No valid workers found")
E   asyncio.exceptions.TimeoutError: No valid workers found

C:\Miniconda\envs\modin\lib\site-packages\distributed\scheduler.py:5846: TimeoutError
---------------------------- Captured stderr call -----------------------------
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 448.04 MiB -- Worker memory limit: 476.84 MiB
```

> Is this something that we need to fix, or does it need to be reported to Dask?

I don't know, it's also possible that some `Dask` settings have changed. Can someone take a look? (I don't have the capacity to investigate the problem for now)

**Comment by YarShev** [comment]
Let's pin dask for now to make CI pass.

**Comment by devin-petersohn** [comment]
Agree, let's pin for now.

**Comment by mvashishtha** [comment]
`test_join_sort` on Ubuntu still takes about 4x long with dask as with ray. e.g. compare [this run](https://github.com/modin-project/modin/runs/5365519294?check_suite_focus=true) of test-ubuntu on dask with [this run](https://github.com/modin-project/modin/runs/6789322001?check_suite_focus=true) on ray. 47 minutes with dask, 12 minutes with ray. Anecdotally, `test-ubuntu` is quite often one of the last things to finish in our CI, and `test_join_sort` is one of the main reasons for that. test_join_sort on dask on windows is also way slower (~1.8x) than on ray on windows, e.g. dask [here](https://github.com/modin-project/modin/runs/6789325888?check_suite_focus=true) took 82 minutes vs ray [here](https://github.com/modin-project/modin/runs/6789324532?check_suite_focus=true) took 46 minutes.

Speeding up `test_join_sort` on dask is likely to substantially reduce the time for our CI to run.

**Comment by mvashishtha** [comment]
I am trying `MODIN_ENGINE=dask pytest -n 2  --durations=0 modin/pandas/test/dataframe/test_join_sort.py` on my Macbook to get an understanding of the test case time distribution on dask 2022.1.1.
