### ISSUE TITLE
`conda install modin-omnisci` installs modin 0.11.3

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#4204]
Should be latest, i.e. 0.13.2.

**Comment by YarShev** [comment]
Latest Modin is installed with conda/mamba only when setting `conda config --set channel_priority strict`.

**Comment by Garra1980** [comment]
tried on relatively fresh machine
conda config --show | grep channel
allow_non_channel_urls: False
channel_alias: https://conda.anaconda.org
**channel_priority: flexible**
channels:
custom_channels:
custom_multichannels:
default_channels:
migrated_channel_aliases: []
migrated_custom_channels: {}
override_channels_enabled: True
restore_free_channel: False
show_channel_urls: None
whitelist_channels: []

conda install -c conda-forge modin-omnisci


conda list | grep modin-omnisci
modin-omnisci             0.13.2           py39hf3d152e_0    conda-forge

**Comment by prutskov** [comment]
Possible, the root cause is similar to issue in #3615.

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by YarShev** [comment]
We can close this issue because it is apparently has gone. Feel free to reopen if the issue is still happening.
