### ISSUE TITLE
DataFrame.loc not ordering columns correctly

### ISSUE THREAD

**Issue by mcs526** [modin-project/modin#421]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**: source
- **Modin version**: current master 
- **Python version**: python 3.6
- **Exact command to reproduce**:

### Describe the problem

When passing in a list of columns to `loc`, the columns don't get ordered correctly, although the labels appear in the right order. In the example i was working with, the columns were reversed, yet the labels were in the correct order 

### Source code / logs

This is the line of code triggering the problem:
```python
data2 = data.loc[:,['degree_spondylolisthesis','pelvic_radius']]
```

**Comment by devin-petersohn** [comment]
Thanks @mcs526!

It looks isolated to `loc`. It is working correctly on `data[['degree_spondylolisthesis','pelvic_radius']]`
