### ISSUE TITLE
Modin `agg` with reduce functions output differently from Pandas for single column dataframe

### ISSUE THREAD

**Issue by c3-qiangyao** [modin-project/modin#4210]
### System information
ray 1.9.2
modin 0.12.0
pandas 1.3.4

### Describe the problem

In modin, if the dataframe is single column and the `agg` function has reduce functions like `max`, `min`, etc. The return is a `Dataframe` instead of a `Series` as in Pandas.

```
modin_df = modin_pd.DataFrame(
{'c0': [True,True,True]}
)
modin_df
—
c0
0	True
1	True
2	True
```
And modin will add index `__reduced__` to the Dataframe.
```
modin_df_1 = modin_df.agg(func=lambda x: max(x), axis=0)
modin_df_1
—
                  c0
_reduced_	True

modin_df_1._class_
—
modin.pandas.dataframe.DataFrame
```
However, if the reduce function is `sum` (maybe more), the output is a Series which is the same as Pandas. 
Also, this only occurs using `agg` function and at the same time the `func` parameter is lambda or a function (not a string like 'min', 'max', etc), i.e. for direct Api calls like `modin_df.min(axis=0)`, modin output is a Series.
```
modin_df.agg(func='max', axis=0).  <--- This is a Series
---
c0    1
dtype: int64.  

modin_df.agg(func=lambda x: max(x), axis=0) <--- Dataframe
---
                      c0
__reduced__        True


modin_df.agg(func=max, axis=0) <--- Dataframe
---
                      c0
__reduced__        True


modin_df.max(axis=0) <--- Series
---
c0    1
dtype: int64.  

```

Pandas behavior.
```
pandas_df_1 = pandas_df.agg(func=lambda x: min(x), axis=0)
pandas_df_1
—
c0    True
dtype: bool


pandas_df_1._class_
—
pandas.core.series.Series

```

I guess we have two expectations here, 1. Both direct api call and agg function call should return Series if the input dataframe is single column. 2. direct api call like `df.max(axis=0)` should have exact same behavior (output type and value) as `df.agg(func=max, axis=0)`

**Comment by mvashishtha** [comment]
@c3-qiangyao thanks for letting us know. While I can reproduce the bug in modin 0.12.0, it's been fixed by Modin 0.13.2. Please upgrade to version 0.13.2 or higher for the fix. If that's not possible, please let me know.
