### ISSUE TITLE
When I run `ap.user_id = ap.item_id`, everything does not change, Why?

### ISSUE THREAD

**Issue by JyiHUO** [modin-project/modin#422]
### System information
- **OS Platform and Distribution tlinux 2.2**:
- **Modin installed from pip **:
- **Modin version 0.2.4**:
- **Python version 3.6.1**:
- **Exact command to reproduce**:

### Describe the problem

The data do not change, when I run the code like this:
```python
ap.user_id = ap.item_id
```

After I run the code above, the value of `ap.user_id` is the same as before and do not change into `ap.item_id`, Why?

The structure of data:

![image](https://user-images.githubusercontent.com/16526817/51519401-d53e5500-1e5b-11e9-8fcc-edb12be80592.png)
 

### Source code / logs

Now, I provide the code which you can reproduce my result quickly:
```python
import numpy as np
import modin.pandas as pd

a = np.array([['bdgr3fom129hsoj6488g', '6UExPoNGS1GCWqPfb', 20190101105500, 0.0],
 ['bdgr3fom129hsoj6488g', '6VhJvfi041GCOisdI', 20190101105429, 0.0],
['bdgr3fom129hsoj6488g', '6ViNKCMMV1GCIQQAT', 20190101105409, 0.0],
 ['bdgr3fom129hsoj6488g', '6WIkLrUBL1GvSKkKv', 20190101105142, 0.0],
 ['bdgr3fom129hsoj6488g', '6WMEaqk7A1GvTYOjp', 20190101105006, 0.0]])

ap = pd.DataFrame(a)
print (ap)
ap.columns = ["user_id", "item_id", "reporttime", "label"]
ap.user_id = ap.item_id
print (ap)
```

**Comment by devin-petersohn** [comment]
Hi @JyiHUO, great question! The currently supported way to set a column in Modin is 
```
ap["user_id"] = ap.item_id
```

To support this behavior, pandas is doing a `__setattr__` override to allow setting of existing columns. This should be relatively simple to implement and can certainly make it in the next release.
