### ISSUE TITLE
Assigning categorical dtype Modin Series to column of Modin Dataframe changes dtype to int64

### ISSUE THREAD

**Issue by naren-ponder** [modin-project/modin#4222]
### System information
- **OS Platform and Distribution **: macOS Big Sur (version 11.6)
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.9.7
- **Code we can use to reproduce**:

```
import modin.pandas as pd
from modin.pandas import Categorical
import pandas.api.types as pt

s = pd.Series({'a': 1, 'b': 2, 'c': 3}, index=['a', 'b', 'c'])
s = Categorical(s)
print(pt.is_categorical_dtype(s))
```
> True

```
df = pd.DataFrame(columns = ['a', 'b', 'c'])
df['a'] = s
print(pt.is_categorical_dtype(df['a']))
```
> False

`print(df['a'].dtype)`
> dtype('int64')

### Describe the problem
On Modin version 0.10.0, when assigning a Series of categorical data type to a Dataframe, the data type is not maintained and rather changes to int64.

**Comment by mvashishtha** [comment]
Hi @naren-ponder , this isn't an issue as of Modin 0.13.0+22.gaebdb522. I'll close the issue because it doesn't apply to the current Modin version.
