### ISSUE TITLE
FAILED modin/pandas/test/test_concat.py::test_concat - ValueError: No clients found

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4227]
OS: `Windows 10`
Modin_version: aac01b2a4f18c8dc0afa942ee1e6bb4718e6b288

Reproducer: `pytest modin\pandas\test\test_concat.py::test_concat -s`

There are two solutions to the problem - add  `Engine.subscribe(_update_engine)` call inside `from_pandas` or use the dataframe constructor instead of `from_pandas` function.

Logs:
```bash
E           ValueError: No clients found
E           Start a client and point it to the scheduler address
E             from distributed import Client
E             client = Client('ip-addr-of-scheduler:8786')
```

**Comment by dchigarev** [comment]
Could you please add more info on how to reproduce the problem? The `pytest` command works fine on my Windows machine and the following code throws no error as well:
```python
import pandas
pandas_df = pandas.DataFrame([[1]])

from modin.pandas.utils import from_pandas
modin_df = from_pandas(pandas_df)
print(modin_df)

# Output:
# 2022-02-21 13:34:36,918 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265
#    0
# 0  1
```

<details><summary>python -m modin --version</summary>

INSTALLED VERSIONS
------------------
commit           : aac01b2a4f18c8dc0afa942ee1e6bb4718e6b288
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

Modin dependencies
------------------
modin            : 0.13.0+31.gaac01b2a
ray              : 1.9.0
dask             : 2022.02.0
distributed      : 2022.02.0
omniscidbe       : None

pandas dependencies
-------------------
pandas           : 1.4.0
numpy            : 1.19.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.2.2
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.17.0
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.01.0
scipy            : 1.8.0
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : None
xarray           : 0.21.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by anmyachev** [comment]
@dchigarev for some reason, problems only arise for Dask (reproduced on your code)
