### ISSUE TITLE
Add multiple columns to dataframe: list out of range error

### ISSUE THREAD

**Issue by iisri-vu** [modin-project/modin#4247]
### System information
- **OS Platform and Distribution: Windows 10, 
- **Modin version** (`modin.__version__`):  0.13.2
- **Python version**: Python 3.8
- **Code we can use to reproduce**:

cola = 1
colb = 2
colc = 5
columns= ['a', 'b', 'c']
df.loc[df['userid'].values == id, columns] =   cola, colb, colc

### Describe the problem
I get an error running the above code. 
KeyError(array(['a'], dtype='<U6'))

**Comment by mvashishtha** [comment]
No, there's no nightly build. You'll have to pull the latest source code from github after the fix.

**Comment by devin-petersohn** [comment]
@mvashishtha that's not completely accurate. You can pip install directly from the latest github by following the instructions here: https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch

**Comment by iisri-vu** [comment]
There's still a bug in the newer version.  We can't create multiple columns or add columns using this method.

**Comment by mvashishtha** [comment]
@iisri-vu yes, I'm sorry, but the bug #3764 is not fixed yet. I've only closed this issue so that we can track progress for both bugs in a single thread.

**Comment by iisri-vu** [comment]
Thanks for the fast response.  This library will be a great one when we have these features in place.
