### ISSUE TITLE
Refactoring efforts

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4248]

**Comment by jbrockmendel** [comment]
@anmyachev worth expanding on what this entails?

**Comment by anmyachev** [comment]
@jbrockmendel This is epic for all refactorings, so that it is convenient for everyone to see in which direction the modification of the old code is going and that there are efforts to improve the quality of the code at all. At least that's how I thought of it.  But perhaps this is visible to those who use Zenhub.
