### ISSUE TITLE
Test rolling with axis=1, win_type=, and center=True once pandas bug 46135 is fixed. 

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4261]
### Describe the problem

In my fix for #4185, I'm going to skip testing for this behavior due to https://github.com/pandas-dev/pandas/issues/46135. Once that bug is fixed, we should test this behavior.

**Comment by vnlitvinov** [comment]
@mvashishtha that bug in pandas is marked as fixed, we should proceed with testing.

**Comment by mvashishtha** [comment]
@vnlitvinov looks like we have to wait till at least version 1.5. The fix isn't included in pandas 1.4.4, which was cut after https://github.com/pandas-dev/pandas/issues/46135 was merged.
