### ISSUE TITLE
REFACTOR: `filepath_or_buffer_md` variable name is misleading as no buffer is used in it

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4282]
Initial found: https://github.com/modin-project/modin/pull/3441#discussion_r816719214

Current behavior: if the buffer is associated with a file, then an attempt is made to get the file name and work on it (`Modin` path), otherwise the code will execute in `pandas`.

**Comment by vnlitvinov** [comment]
@anmyachev do you have any suggestions on renaming?

**Comment by anmyachev** [comment]
@vnlitvinov I didn't find a good solution for this.

**Comment by anmyachev** [comment]
not actual
