### ISSUE TITLE
`groupby.mean`-like operations in Modin are significantly slower than in pandas on narrow data

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4288]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin version** (`modin.__version__`):  bb7805cb1ba4e78bc6bfc65616ea1bffa387e146
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

<details><summary>Benchmark</summary>

```python
import time

import numpy as np
import pandas as pd

import modin.pandas as mpd
import modin.config as cfg
import ray

cfg.BenchmarkMode.put(True)
ray.init()

def generate_data(path, nrows=5000, n_random_cols=100):
    data = {
        "Int": np.random.randint(0, 100, nrows),
        "Float": np.random.rand(nrows),
    }
    data_random = {f"col{i}":  np.random.rand(nrows) for i in range(n_random_cols)}
    data.update(data_random)
    df = mpd.DataFrame(data)
    #df.to_csv(path, index=False)
    return df

if __name__ == "__main__":
    path = "data.csv"

    mdf = generate_data(path, nrows=1_000_000, n_random_cols=9998)

    pdf = mdf._to_pandas()

    # df = df._to_pandas()
    print(f"Original shape: {pdf.shape}")

    t = time.time()
    pdf = pdf.groupby(["Int"], as_index=False).mean()
    print(f"pandas groupby.mean time: {time.time() - t} s")
    print(pdf.shape)

    t = time.time()
    mdf = mdf.groupby(["Int"], as_index=False).mean()
    print(f"modin groupby.mean time: {time.time() - t} s")
    print(mdf.shape)
```

</details>

### Describe the problem

`groupby.mean`-like operations in Modin are significantly slower than in pandas on narrow data

The results for Ray execution engine are follows:

1) The table with increasing number of rows, number of columns is fixed.

| Shape(rows, cols) | (100k, 32) |(1m, 32) | (10m, 32) | (100m, 32) |
| ----------- | ----------- | ----------- | ----------- |----------- |
| modin      | 1.3476 |0.6313| 2.5042|25.3606|
| pandas | 0.01814 |0.1025|0.7786|8.6838|

2) The table with increasing number of columns, number of rows is fixed.

| Shape(rows, cols) | (1m, 32) | (1m, 100) |(1m, 1k)| (1m, 10k)| 
| ----------- | ----------- | ----------- | ----------- | ----------- | 
| modin      | 0.67139 |0.5610|1.42168|23.5843|
| pandas | 0.1111 |0.22501|2.1197|55.1141|

**Comment by YarShev** [comment]
Related ones #1901, #3585.
