### ISSUE TITLE
OmniSci engine does not import booleans correctly

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#4299]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **Modin version** (`modin.__version__`): acd0ff91
- **Python version**: 3.8.12
- **Code we can use to reproduce**:
```python
import modin.pandas as pd
import pandas

df = pd.DataFrame({"mask": [True, False, True, True, False], "values": [1, 2, 3, 4, 5]})
print(f"modin:\n{df[df['mask']]}")

df = pandas.DataFrame(
    {"mask": [True, False, True, True, False], "values": [1, 2, 3, 4, 5]}
)
print(f"pandas:\n{df[df['mask']]}")
```

<details><summary>Output</summary>

```
modin:
   mask  values
0  True       1

pandas:
   mask  values
0  True       1
2  True       3
3  True       4
```

</details>

### Describe the problem
OmniSci appears to not correctly interprets booleans imported from the pyarrow table, there's a simpler reproducer with pure omniscidbe that confirms this:
<details><summary>reproducer</summary>

```python
import sys

sys.setdlopenflags(1 | 256)  # RTLD_LAZY+RTLD_GLOBAL
from omniscidbe import PyDbEngine
import pyarrow as pa

server = PyDbEngine()

tbl1 = pa.Table.from_pydict({"a": [True, False, True, True, False]})
print(f"before import:\n{tbl1}\n")

server.importArrowTable("table1", tbl1)
res = pa.Table.from_batches(
    [server.executeRA("SELECT * FROM table1").getArrowRecordBatch()]
)
print(f"after import:\n{res}\n")
```

Output:
```
before import:
pyarrow.Table
a: bool
----
a: [[true,false,true,true,false]]

after import:
pyarrow.Table
a: bool
----
a: [[true,false,false,false,false]]
```

</details>

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by anmyachev** [comment]
The reproducer works correctly on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
