### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yohannes-didana** [modin-project/modin#4302]
I get the following is errors when I run Modin with dask 
1. Pandas read_hdf feature request is not implemented 
2. df[df.id.duplicated())
  df[~(df.id.isin(df2.id))
gives Exception: Type Error("Object of type: coroutine" has no len()")

**Comment by mvashishtha** [comment]
@yohannes-didana thanks for posting here. 

> 1. Pandas read_hdf feature request is not implemented

We, the Modin contributors, appreciate the suggestion. We are already tracking this feature request in #1299.

> gives Exception: Type Error("Object of type: coroutine" has no len()")

I can't reproduce this error using the code you've provided, so it's difficult to tell what's going wrong here, and whether there is a bug in Modin. If you could provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), it would be very useful. Ideally you would send a snippet of Python code that uses Modin and produces the error you found.

**Comment by anmyachev** [comment]
Similar issue https://github.com/modin-project/modin/issues/3737
