### ISSUE TITLE
Mac(m1) "read_csv"-->object store size (9.313GiB) exceeds 

### ISSUE THREAD

**Issue by NOBB2333** [modin-project/modin#4361]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
>mac (m1) (8core + 16G memory)
>macos 12.3
- **Modin version** (`modin.__version__`):
 >modin-0.14.0
- **Python version**:
>python3.8.9(intel -version,only after 3.9 match for arm)
- **Code we can use to reproduce**:

### Source code / logs

file type:csv  
file size: 1.1GB  
fle shape:(327483, 290)  
part of this decode by "gb18030"
* use pandas to read_csv
```python
import pandas as pd

path1 = "/Users/nobb/Downloads/2022-04-02all.csv"
%time df = mpd.read_csv(path1,encoding="gb18030",low_memory=False)
```
result:
>CPU times: user 27.7 s, sys: 4.75 s, total: 32.5 s
Wall time: 40.4 s

* use modin.pandas to read_csv
```python
import modin.pandas as mpd

path1 = "/Users/nobb/Downloads/2022-04-02all.csv"
%time df = mpd.read_csv(path1,encoding="gb18030")
```
Error:
>ValueError: The configured object store size (9.313GiB) exceeds the optimal size on Mac (2.0GiB). This will harm performance! There is a known issue where Ray's performance degrades with object store size greater than 2.0GB on a Mac.To reduce the object store capacity, specify`object_store_memory` when calling ray.init() or ray start.To ignore this warning, set RAY_ENABLE_MAC_LARGE_OBJECT_STORE=1.

I can't find how to gnore this warning or reset ray.init() on the net 

arter this i test some different xlsx, even empty "csv" still can't read 
>i has already   
>pip install "modin[dask]"  
>pip install "modin[ray]"  
>pip install typing

**Comment by NOBB2333** [comment]
according to after blog i find the slove way, the error said 
>you need ignore this warning or reset ray.init() 

i find two days to slove this problem 
first:you need  **import ray**
you need set something when you **import ray** init()

```python
import ray
import warnings
warnings.filterwarnings('ignore')
# num_cpus is how much you want use 
ray.init(num_cpus=4, ignore_reinit_error=True)
import modin.pandas as pd

start = timer()
pd.read_csv("/Users/nobb/Downloads/2022-04-02审管系all.csv" ,encoding="gb18030")
end = timer()
print(end - start) 
```
result:
>10.758918999999992

it's so fast use 4 core the time is the same  4times fast


slove url:https://blog.csdn.net/qq_41865652/article/details/103992998
>from a chinese data analyst

**Comment by devin-petersohn** [comment]
Hi @NOBB2333 thanks for posting!

It looks like this was fixed by the following:

```python
import ray
ray.init()
```

@mvashishtha is this related to #4330 ?

**Comment by mvashishtha** [comment]
@devin-petersohn Yes, the bug is the same. The solution @NOBB2333 found was to initialize ray with the default object store size. The default object store size was presumably less than 2 GB, the level that triggers the `ValueError`.

**Comment by mvashishtha** [comment]
@NOBB2333 your solution will give your mac less object store memory than we suggest. That could potentially lead to worse performance in other Modin operations. I suggest you do one of the following instead:

1. Set environment variable `RAY_ENABLE_MAC_LARGE_OBJECT_STORE=1` when using Modin.
2. Use a version of Modin with fix #4335 included, e.g. by `pip install git+https://github.com/mvashishtha/modin.git@4330-start-modin-on-ray-1-11-0-on-mac`

Once #4335 is merged, Modin will automatically do solution (1).

**Comment by NOBB2333** [comment]
Thank you for  @mvashishtha @devin-petersohn   generous reply.
brefore I thought it would take a long time to solve this problem. 
I didn't expect your response to be so fast and efficient.
Through this, I realized that writing a pacage is really not an easy thing.

Thank you very much again，I believe Modin will be the main force in the near future.

**Comment by mvashishtha** [comment]
@NOBB2333 thanks for the kind comments. Now that #4335 is merged, I'll close this bug. Please reach out again if you have any other concerns.
