### ISSUE TITLE
Don't correctly work `dtype` for `column` in `exchange df_protocol` for OmniSci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#4366]
If we run:
```
import modin.pandas as pd
from modin.test.exchange.dataframe_protocol.omnisci.utils import split_df_into_chunks
import modin.config as cfg
cfg.StorageFormat.put('omnisci')

pd_df = pd.DataFrame({"a": pd.Categorical(list("testdataforexchangedataframeprotocol"))})
pd_chunks = split_df_into_chunks(pd_df, 2)
md_df = pd.concat(pd_chunks)
print(" ")
print("md_df.dtype = ", md_df["a"].dtype)
protocol_df = md_df.__dataframe__()
df_col = protocol_df.get_column_by_name(" ")
print("protocol_df.num_chunks() = ", df_col.num_chunks())
print("protocol_df.dtype = ", df_col.dtype)
```
We have result:
```
md_df.dtype =  category
protocol_df.num_chunks() =  2
protocol_df.dtype =  (<DTypeKind.INT: 0>, 64, 'l', '=')
```
This is because when converting df from an arrow table, the index column replaces the actual null column.

**Comment by AndreyPavlenko** [comment]
This issue seems to be fixed by #4834.

**Comment by YarShev** [comment]
@AndreyPavlenko, does the example above pass with those changes on your side?

**Comment by YarShev** [comment]
Would you add a test in `modin/test/interchange/dataframe_protocol/omnisci/test_protocol.py` so we can close this issue?

**Comment by AndreyPavlenko** [comment]
> Would you add a test in `modin/test/interchange/dataframe_protocol/omnisci/test_protocol.py` so we can close this issue?

Created PR with a single test - #4972. There are 2 CI tests failed, but the failures are not related to my changes, checks for some other PRs also failed wit the same errors.
