### ISSUE TITLE
 Relax some deps in general Modin env files

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#4379]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

Some deps constraints in general Modin env files seem to be obsolete. Let's try to get rid of those constraints

**Comment by YarShev** [comment]
Related to #3615 in terms of keeping dependencies consistency. We should correct the reqs in all the env files.

**Comment by anmyachev** [comment]
Done in https://github.com/modin-project/modin/pull/5216.
