### ISSUE TITLE
read_hdf throws TypeError when trying to read a file with 'fixed' format

### ISSUE THREAD

**Issue by eavidan** [modin-project/modin#438]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.2
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.3.0
- **Python version**: 3.6.7
- **Exact command to reproduce**: `read_hdf()`

### Describe the problem
When trying to read an HDF file which was saved with `format=fixed` (which is the pandas default), `read_hdf()` throws: 
`
TypeError: cannot pass a column specification when reading a Fixed format store. this store must be selected in its entirety
`
This is because the partitioning is trying to read specific columns which is not possible with `fixed` files.

My approach to fixing this would be:
- change the default format in `to_hdf()` to `table` with a proper message (as this is not pandas defaults) so it will support the parallelism of `read_hdf()`
- verify the file format in `read_hdf()`

### Source code / logs
```
import modin.pandas as pd

# works
df = pd.DataFrame({'x': [1, 2, 3]})
df.to_hdf("tmp.h5", key="s", format="table")  # fixed format is the default
df = pd.read_hdf("tmp.h5")

# does not work
df = pd.DataFrame({'x': [1, 2, 3]})
df.to_hdf("tmp.h5", key="s", format="fixed")  # fixed format is the default
df = pd.read_hdf("tmp.h5")
```

**Comment by devin-petersohn** [comment]
Thanks for the fix @eavidan! Closing via #440
