### ISSUE TITLE
Building latest documentaion is failing

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#4388]
After #4297 has been merged, building latest documentation has got failing. @alexander3774, could you look at this?

We can turn `fail_on_warning` off for now and exploring the issue in background if it requires a long investigation.

https://readthedocs.org/projects/modin/builds/16655802/#:~:text=Error,not%20changed%20recently.

**Comment by alexander3774** [comment]
@YarShev unfortunetely i haven't access to readthedocs logs, so i can't investigate this issue...
> We can turn fail_on_warning off for now and exploring the issue in background if it requires a long investigation.

Sure, let's turn off this option for now.
