### ISSUE TITLE
Remove `redis` as a mandatory dependency for Ray engine

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#4398]
Ray announced that they removed `redis` as a dependency since 1.12.0, so `redis` should be no longer needed to use basic Ray functionality.

However, it revelad in ray-project/ray#23982 that Ray still do require `redis` to be installed on Windows though it doesn't come in installation bundle, and that caused Modin initialization to fail due to `redis` missing package on Windows. As a quick fix we just included `redis` as a Modin's dependency in #4396, but it's desirable to remove this deps as soon as Ray release with ray-project/ray#23982 being fixed.

**Comment by Garra1980** [comment]
Should we give it a try?

**Comment by dchigarev** [comment]
The fix for mentioned Ray issue was introduced in 1.13.0, meaning that there are currently 2 Ray releases (1.12.0 and 1.12.1) that do not work with Modin unless there's a Redis manually installed.

Judging by Modin's `setup.py` we're supporting any Ray starting from 1.4.0
https://github.com/modin-project/modin/blob/6440684f3fd3eea477f83dcf77f8d66103b9df95/setup.py#L14-L15
In order to support the mentioned buggy Ray releases, there's a requirement for Redis listed in our `setup.py`
https://github.com/modin-project/modin/blob/6440684f3fd3eea477f83dcf77f8d66103b9df95/setup.py#L17
In order to resolve the #4398 ticket we have to either bump up the minimum supported Ray's version to 1.13.0 or ban these 2 Ray releases to work with Modin (`ray>1.4.0,!=1.12.0,!=1.12.1`).

**Comment by dchigarev** [comment]
The motivation for this is questionable to me.

Do we really want to remove the Redis requirement so much that we are ready to create a list of "bad" Ray releases that won't work for Modin?

**Comment by anmyachev** [comment]
Fixed in #5390
