### ISSUE TITLE
Improve memory use of read_csv

### ISSUE THREAD

**Issue by pschafhalter** [modin-project/modin#44]
`read_csv` falls back to the Pandas implementation for certain situations. This is expensive in terms of memory due to data duplication; first, we create a Pandas dataframe using `pandas.read_csv`, and then convert it to a Modin dataframe.

The following events fall back to `pandas.read_csv` and should be fixed to be more memory efficient:
- [ ] file does not exist on disk (e.g. located in S3).
- [ ] `filepath_or_buffer` is not an instance of `str`, `py.path.local` or `pathlib.Path`
- [ ] file is compressed (high priority)
- [ ] `as_recarray` is `True`
- [ ] `chunksize` is not `None`
- [ ] `skiprows` is list-like or callable
- [ ] `nrows` is not `None`

Most changes need to be done in `io.py`.

Thanks to @Bidek56 for reporting!

**Comment by pschafhalter** [comment]
I've assigned myself to this issue for now, but contributions are welcome!

**Comment by devin-petersohn** [comment]
Hi @chvsp! The best starter parameter from the list above is `nrows`. The first step would be to make sure you fully understand the behavior of the [pandas implementation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html). This will be a great performance improvement as `nrows` is a very common parameter to be used.

When you feel you are ready to start implementing it, [io.py](https://github.com/modin-project/modin/blob/master/modin/pandas/io.py#L194) is where this change will go. If you run into problems or questions along the way, feel free to email the [dev group](https://groups.google.com/forum/#!forum/modin-dev). Thanks again for looking into this!

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
