### ISSUE TITLE
Modin `DataFrameGroupBy.pct_change()` is missing all parameters

### ISSUE THREAD

**Issue by c3-andrewfitch** [modin-project/modin#4425]
### System information
ray 1.9.2
modin 0.12.0
pandas 1.3.4

### Describe the problem
In Modin, calling `DataFrameGroupBy.pct_change()` is missing all parameters.

To Reproduce in Modin:

```
import modin.pandas as pd
df = pd.DataFrame({'a':[1,2]})
df.groupby('a').pct_change(periods=1)
```

The Call to pct_change produces the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pct_change() got an unexpected keyword argument 'periods'
```

Expected result is:

```
Empty DataFrame
Columns: []
Index: [0, 1]
```

Upon using the inspect library, it’s clear that all parameters are missing from this API

```
>>> import modin.pandas as pd
>>> from inspect import signature
>>>>signature(pd.DataFrame({'a':[1,2]}).groupby('a').pct_change)
<Signature ()>
```

Signature for Pandas is:

```
>>> import pandas as pd
>>> from inspect import signature
>>> signature(pd.DataFrame({'a':[1,2]}).groupby('a').pct_change)
<Signature (periods=1, fill_method='pad', limit=None, freq=None, axis=0)>
```

**Comment by mvashishtha** [comment]
@c3-andrewfitch thank you for reporting this bug! I can reproduce it at Modin commit 5825856a4ee19ff0dd5d1beaf6090bf601d0b411. I'll start working on the fix.
