### ISSUE TITLE
drop_duplicates after pd.concat not working as expected

### ISSUE THREAD

**Issue by jrsacher** [modin-project/modin#4467]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 12.3.1
- **Modin version** (`modin.__version__`): 0.14.1
- **Python version**: Python 3.9.12
- **Code we can use to reproduce**:

```python
import pandas as pd
import modin.pandas as mpd
import numpy as np

# Pandas
np.random.seed(0)
df1 = pd.DataFrame(np.random.randint(0, 1000, size=1000), columns=["A"])
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(0, 1000, size=1000), columns=["A"])

df = pd.concat([df1, df2])
print(len(df))  # 2000
print(len(df.drop_duplicates()))  # 874

# Modin
np.random.seed(0)
df1 = mpd.DataFrame(np.random.randint(0, 1000, size=1000), columns=["A"])
np.random.seed(1)
df2 = mpd.DataFrame(np.random.randint(0, 1000, size=1000), columns=["A"])

df = mpd.concat([df1, df2])
print(len(df))  # 2000
print(len(df.drop_duplicates()))  # 322 ?!?

# Issue caused by index? Use ignore_index=True to fix
df = mpd.concat([df1, df2], ignore_index=True)
print(len(df))  # 2000
print(len(df.drop_duplicates()))  # 874
```

### Describe the problem

After combining DataFrames using `mpd.concat()`, dropping duplicate values removes WAY too many items. I believe this is related to the indexing of the combined DataFrames, as using `ignore_index=True` in the `concat()` call seems to fix the issue.

In regular pandas, the result is the same whether or not `ignore_index=True` is used.

The above example is a toy one. I noticed this when combining large CSV files. Happy to share those, but this takes much less time to run!

**Comment by jrsacher** [comment]
Tested with both Ray and Dask as the engine. Both give the same results.

**Comment by jrsacher** [comment]
Think I found the issue in `BasePandasDataset` class in `base.py`

```python
    def drop_duplicates(
        self, keep="first", inplace=False, **kwargs
    ):  # noqa: PR01, RT01, D200
        """
        Return `BasePandasDataset` with duplicate rows removed.
        """
        inplace = validate_bool_kwarg(inplace, "inplace")
        subset = kwargs.get("subset", None)
        if subset is not None:
            if is_list_like(subset):
                if not isinstance(subset, list):
                    subset = list(subset)
            else:
                subset = [subset]
            duplicates = self.duplicated(keep=keep, subset=subset)
        else:
            duplicates = self.duplicated(keep=keep)
        indices = duplicates.values.nonzero()[0]
        return self.drop(index=self.index[indices], inplace=inplace)
```

The `return` statement is using the index values, but the indices are duplicated after the `concat`.

My solution may be overly simplistic, but instead of this:
```python
        indices = duplicates.values.nonzero()[0]
        return self.drop(index=self.index[indices], inplace=inplace)
```
could you do something like what [Pandas does](https://github.com/pandas-dev/pandas/blob/a160caff845db846516ff5f973c5c0a09a605d8d/pandas/core/frame.py#L6363) (shown below)?
```python
        result = self[-duplicated]
        if ignore_index:
            result.index = default_index(len(result))

        if inplace:
            self._update_inplace(result)
            return None
        else:
            return result
```

(sorry if this isn't useful -- I'm much better at breaking things than fixing them!)

**Comment by mvashishtha** [comment]
@jrsacher thank you for reporting this bug! I was able to reproduce it at commit cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a. If I see a quick fix, I'll assign the issue to myself and make a PR.

**Comment by mvashishtha** [comment]
@jrsacher I'm sorry, but I missed your last message. I think you've diagnosed the bug correctly. I think making the Modin implementation more like the pandas implementation as you suggested should work. 

Would you be interested in contributing this fix yourself? Members of \@modin-project/modin-contributors, including me, can help you make the fix and get it merged. You could follow the guide [here](https://github.com/modin-project/modin/blob/cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a/contributing/contributing.md) to get set up for Modin development.

**Comment by jrsacher** [comment]
@mvashishtha Thanks for the push to tackle this myself. I gave it a shot. Looking forward to getting feedback!
