### ISSUE TITLE
BUG: Pickling a dataframe in benchmark mode raises AttributeError: 'NoneType' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4471]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Monterey 12.2.1
- **Modin version** (`modin.__version__`): cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a
- **Python version**: 3.9.12
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
from modin.config import BenchmarkMode
from pickle import dumps

BenchmarkMode.put(True)
dumps(pd.DataFrame([[1]]))
```

### Describe the problem
Pickling a Modin dataframe calls the query compiler method [finalize](https://github.com/modin-project/modin/blob/cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a/modin/core/storage_formats/pandas/query_compiler.py#L254), which ultimately calls the partition manager [finalize](https://github.com/modin-project/modin/blob/cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a/modin/core/dataframe/pandas/partitioning/partition_manager.py#L1277), which is wrapped by `@wait_computations_if_benchmark_mode`, which [assumes](https://github.com/modin-project/modin/blob/cf0eb393daa41abdd8cdf32b52ceee938cdcbe1a/modin/core/dataframe/pandas/partitioning/partition_manager.py#L66) that the function it's wrapping returns a 2d list of partitions or a tuple whose first element is a 2d list of partitions.

### Source code / logs
<details>
<summary>Show stack trace</summary>

```
AttributeError                            Traceback (most recent call last)
Input In [10], in <module>
      2 from modin.config import BenchmarkMode
      3 from pickle import dumps
----> 5 dumps(pd.DataFrame([[1]]))

File ~/software_sources/modin/modin/pandas/dataframe.py:3034, in DataFrame.__reduce__(self)
   3033 def __reduce__(self):
-> 3034     self._query_compiler.finalize()
   3035     if PersistentPickle.get():
   3036         return self._inflate_full, (self._to_pandas(),)

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:255, in PandasQueryCompiler.finalize(self)
    254 def finalize(self):
--> 255     self._modin_frame.finalize()

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:2839, in PandasDataframe.finalize(self)
   2832 def finalize(self):
   2833     """
   2834     Perform all deferred calls on partitions.
   2835
   2836     This makes `self` Modin Dataframe independent of a history of queries
   2837     that were used to build it.
   2838     """
-> 2839     self._partition_mgr_cls.finalize(self._partitions)

File ~/software_sources/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py:66, in wait_computations_if_benchmark_mode.<locals>.wait(*args, **kwargs)
     62     partitions = result
     63 # need to go through all the values of the map iterator
     64 # since `wait` does not return anything, we need to explicitly add
     65 # the return `True` value from the lambda
---> 66 all(map(lambda partition: partition.wait() or True, partitions.flatten()))
     67 return result

AttributeError: 'NoneType' object has no attribute 'flatten'
```
</details>

**Comment by anmyachev** [comment]
@mvashishtha it seems that this issue is duplication of https://github.com/modin-project/modin/pull/4404. Can you double check?

**Comment by mvashishtha** [comment]
Yes, that's right. I will close this issue.

**Comment by mvashishtha** [comment]
Duplicate of #4273.
