### ISSUE TITLE
df.eval with a local variable in Modin results in AttributeError

### ISSUE THREAD

**Issue by naren-ponder** [modin-project/modin#4477]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Version 11.6.4
- **Modin version** (`modin.__version__`): 0.14.1
- **Python version**: Python 3.8.11
- **Code we can use to reproduce**:

```
import modin.pandas as pd
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C": [7, 8, 9]})
b = 2
df.eval("@b")
```

### Describe the problem
The code above results in an output of "2" in pandas, but running it in modin results in `AttributeError: 'int' object has no attribute 'columns'`.

**Comment by mvashishtha** [comment]
More generally the bug is that any `eval` that should return a scalar will raise this error, because
