### ISSUE TITLE
PERF: get all partition widths/lengths in parallel instead of serially.

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4494]
The reproducing script is the same as in #4493, but the solution here is different: instead of getting all lengths/widths serially, we should do so in parallel. We will need to add a new method at the physical layer for that. 

This solution will not save us the cost of serializing the call queue drain result after computing length, but it will let us get all the lengths/widths at once instead of serially.

**Comment by noloerino** [comment]
I see this is already implemented for Dask by #4420. Is adding a similar implementation for PandasOnRay sufficient, or do we also need similar changes for PyarrowOnRay and OmnisciOnNative as well?

**Comment by mvashishtha** [comment]
@noloerino here are all the places I can find where we are getting uncached partition shapes serially. I found them by searching for `width()` in the Modin codebase.

- [PandasDataFrame._copartition for both dask and ray](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/dataframe/pandas/dataframe/dataframe.py#L2443-L2446): 
- [PandasDataFrame. _row_lengths for ray](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/dataframe/pandas/dataframe/dataframe.py#L225): note that dask is using its parallel implementation
- [PandasDataFrame._column_widths for ray](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/dataframe/pandas/dataframe/dataframe.py#L244) note that dask dataframe is using its parallel implementation
- [in partition manager for both dask and ray](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/dataframe/pandas/partitioning/partition_manager.py#L1205)
- [within dask virtual partitions](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py#L364-L400)
- [within ray virtual partitions](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py#L369-L405)

We do get lengths serially in [`rebalance_partitions`](https://github.com/modin-project/modin/blob/8f35ab57996d18f2c1f001d624682952853454cd/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py#L211), but that's okay because we [check](https://github.com/modin-project/modin/blob/8f35ab57996d18f2c1f001d624682952853454cd/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py#L182) first that the lengths are cached.

**Comment by mvashishtha** [comment]
It's hard to find a case where this optimization is useful. See my comment here: https://github.com/modin-project/modin/pull/4683#issuecomment-1191043276

Given that this optimization doesn't seem to give any major gains, it doesn't seem to be worth the extra code complexity in #4683. I'll close this issue for now.
