### ISSUE TITLE
Modin 0.14.1 from conda-forge installs pandas 1.4.1 while 1.4.2 is required

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#4496]
I am installing `modin-all` on windows (but it is true for linux too) from `conda-forge`. I am getting `modin-all-0.14.1` and `pandas-1.4.1`. But Modin release 0.14.1 requires `pandas-1.4.2` and gives a warning that incorrect version of pandas is installed. It looks like a bug in conda recipe https://github.com/conda-forge/modin-feedstock/pull/42.

Note: I use mamba as a conda package manager because conda itself is abysmally slow and literally takes days to resolve environment to install Modin.

**Comment by vnlitvinov** [comment]
Does the same happen with latest release, too?

**Comment by gshimansky** [comment]
I tried creating environment with modin 0.15.2 and it installs pandas 1.4.3 which seems to be correct version because Modin doesn't complain.
