### ISSUE TITLE
CI Fails on Build Docs

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#4498]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

Seems that a new major version of protobuf has been released, and our CI automatically downloads it. The ray project has old generated protos and some things are now disallowed/changed in the new release, so our `build_docs` fails. We need to pin protobuf to `<=3.20` until the ray team regens their protos.

**Comment by RehanSD** [comment]
Opened this on the ray repo: https://github.com/ray-project/ray/issues/25205

**Comment by mvashishtha** [comment]
@RehanSD is this CI failure in test-ray-client caused by the same bug: https://github.com/modin-project/modin/runs/6610720432?check_suite_focus=true

**Comment by mvashishtha** [comment]
@RehanSD @YarShev  it looks like proto 4.21.0 was yanked 15 hours ago: https://pypi.org/project/protobuf/#history

It looks like protobuf 4 is no longer available, at least at Python 3.9.12:

<img width="891" alt="Screen Shot 2022-05-26 at 11 09 47 AM" src="https://user-images.githubusercontent.com/10712109/170528602-88b45477-8a8e-4d84-826d-ca6410ca1406.png">

**Comment by RehanSD** [comment]
Given that protobuf 4.0 has been yanked (confirmed on python 3.8 as well) I think it makes sense to close this as well!
