### ISSUE TITLE
read_sql() parallelism parameter

### ISSUE THREAD

**Issue by rd5802** [modin-project/modin#455]
Add a parameter which will limit the maximum number of sessions for concurrent partitioned read.

RD

Thanks @rd5802 that sounds good to me. Would you mind to create a new issue so we can track that specific request? I think we can leave this conversation open for the sake of keeping the conversation on parallel `read_sql` alive.

_Originally posted by @devin-petersohn in https://github.com/modin-project/modin/issues/418#issuecomment-460400546_

**Comment by devin-petersohn** [comment]
Thanks @rd5802! It should be relatively straightforward, and a couple of people have recently come to me about contributing so I will let someone take it.

All we really need to do for this is to add a `max_sessions` parameter to `modin.experimental.pandas.io.read_sql`.

**Comment by rd5802** [comment]
That's really great @devin-petersohn . Looking forward to see whats next 👍 .

**Comment by itamarst** [comment]
Looks like this was fixed in #594 and can be closed?

**Comment by devin-petersohn** [comment]
Yes, thank you @itamarst
