### ISSUE TITLE
REF: Unify select_dtypes logic

### ISSUE THREAD

**Issue by NickCrews** [modin-project/modin#4576]
We currently have duplicated logic to select dtypes in in base.describe() vs dataframe.select_dtypes()

Looking at how pandas does this, their describe() uses select_dtypes() so that those two methods are guaranteed to have the same behavior and always be in sync. Do we want to / can we do the same thing? Or somehow merge that logic together so they both use the same helper functions?

_Originally posted by @NickCrews in https://github.com/modin-project/modin/issues/4571#issuecomment-1155596345_

**Comment by anmyachev** [comment]
`describe` reuses the logic of `select_dtypes` now.
