### ISSUE TITLE
Handle Empty/Small Data DataFrames as a separate case

### ISSUE THREAD

**Issue by naren-ponder** [modin-project/modin#4605]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

In our current approach, we default empty dataframes to pandas at the query compiler level which leads to some overhead as well as some bugs in empty dataframes (#4306, #4307). It would be ideal to default not only empty dataframes to pandas, but also dataframes with a small amount of data where distributing leads to more cost than it is worth.

**Comment by mvashishtha** [comment]
For reference, #4191 and #4060 are also bugs coming from improper treatment of empty dataframes.

**Comment by Billy2551** [comment]
@modin-project/modin-core @modin-project/modin-contributors @RehanSD @vnlitvinov @anmyachev Currently, indexes are processed asynchronously making it difficult to determine when a data frame will be empty or not without waiting on the index to complete. Wondering if anybody had any suggestions on how to approach this problem.

Some ideas we have include changes at the query compiler level, API level, or modin core level whenever columns or rows are potentially added/removed.

**Comment by vnlitvinov** [comment]
In most cases, axes are known, and I'm pretty sure most operations can be analyzed to see what effects such operations have on the axes, so in a typical case both axes would be known. We can simply make an assumption that we either know the axes (and as such can use their sizes to see which compiler to apply) or the dataframe is big.

There are only a few operations which are unpredictable on outcoming axes - filtering by some user-defined condition (like `df[df.a == b]`), running groupby operations, etc. All other operations could be analyzed in advance.
