### ISSUE TITLE
DOCS: Document partial support for to_pandas.

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4628]
Currently, the [supported APIs page](https://modin.readthedocs.io/en/stable/supported_apis/dataframe_supported.html) says that Modin always defaults to pandas for `to_parquet`. Per #4624, we should document that Modin on Ray has a parallel implementation of `to_parquet` for the cases not excluded in [this check](https://github.com/modin-project/modin/blob/4ec7f6347903f9133c65ebc5b6e0e15553b98577/modin/core/execution/ray/implementations/pandas_on_ray/io/io.py#L241).

The file to edit is [here](https://github.com/modin-project/modin/blob/7b83e3b26674ff764c412864f886fcb34206bc29/docs/supported_apis/dataframe_supported.rst).

**Comment by d33bs** [comment]
Hi @mvashishtha - I made some docs changes to help address this issue. Do the changes within my fork look okay to create a PR from? Thank you in advance for your input on this.

**Comment by mvashishtha** [comment]
@d33bs yes, that looks great to make a PR! I have some minor suggestions and someone from @modin-project/modin-core will have to approve the Pr, but let's discuss more on the PR.
