### ISSUE TITLE
After pd.set_option('display.max_rows', None), df.describe().T only displays 60 rows

### ISSUE THREAD

**Issue by rhstanton** [modin-project/modin#4640]
### System information
- OS: macOS 12.4
- Modin version: 0.15.2
- Python version: 3.9.12 (Anaconda)
- **Code we can use to reproduce**:
In Jupyter nbotebook:

```
import os
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pd
import numpy as np
import ray
ray.init()
pd.set_option('display.max_rows', None)
df = pd.DataFrame(np.zeros((2,100)))
df.describe().T
```

### Describe the problem

After running
```
pd.set_option('display.max_rows', None), df.describe().T only displays 60 rows
```
to display all rows of output, df.describe().T shows the first 30 rows and last 30 rows only, with no indication that you're not seeing all of the output.

**Comment by mvashishtha** [comment]
@rhstanton thank you for reporting this issue! I can reproduce it at Modin version 910bf2dd893f52072c2c25413bf0866825f8309d:

```python
import modin.pandas as pd
pd.set_option('display.max_rows', None)
print(pd.DataFrame(list(range(20))))
```

the above script gives me just 12 rows in my terminal in ipython, while pandas gives me all 20 rows.

To whomever works on the fix:
I tried passing `num_rows = len(self.index)` to [`modin.pandas.BasePandasDataset._build_repr_df`](https://github.com/modin-project/modin/blob/910bf2dd893f52072c2c25413bf0866825f8309d/modin/pandas/base.py#L135) in case `display.max_rows` is `None` (and likewise for columns), but that's not passing the modified unit test `test__options_display` with `max_rows = max_cols = None`. However, setting `max_rows` to `math.inf` with special treatment so we don't try to divide infinity worked. The latter solution doesn't seem as clear, though.

**Comment by pyrito** [comment]
This seems like low hanging fruit that we should fix in an effort to improve user experience.
