### ISSUE TITLE
drop_duplicates after sort_values producing incorrect results

### ISSUE THREAD

**Issue by mdbecker** [modin-project/modin#465]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.4 (17E202)
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.3.1
- **Python version**: Python 3.6.7 :: Anaconda, Inc.
- **Exact command to reproduce**:

```python
df = pd.DataFrame([
    {'value': 1, 'time': 2},
    {'value': 1, 'time': 1},
    {'value': 2, 'time': 1},
    {'value': 2, 'time': 2}
])
df.sort_values(['value', 'time']).drop_duplicates(['value'])
```

### Describe the problem
* When the above is executed in pandas it returns rows 1 and 2
* When run with modin it returns rows 0 and 2 (as if `sort_values` was never executed)

### Source code / logs
n/a

**Comment by devin-petersohn** [comment]
Thanks @mdbecker, this is related to the issue causing #464 and solved by the same PR #466. After that PR, the correct rows [1, 2] are returned. I will add this to the test cases.
