### ISSUE TITLE
Strings are converted to nans when interchanging dataframes

### ISSUE THREAD

**Issue by honno** [modin-project/modin#4654]
Interchanging a modin dataframe with string columns results in all string values being replaced with nan.

```python
>>> from modin import pandas as mpd
>>> df = mpd.DataFrame({"foo": mpd.Series(["bar"], dtype=mpd.StringDtype())})
>>> df["foo"].dtype
string[python]
>>> df
   foo
0  bar
>>> from modin.pandas.utils import from_dataframe
>>> out = from_dataframe(df)
>>> out
   foo
0  NaN
>>> out["foo"].dtype
dtype('O')
```

The above example was with pandas `1.4.3`, but this also happens with upstream pandas. And interchanging with pandas upstream gets a similar result

```python
>>> df = mpd.DataFrame({"foo": mpd.Series(["bar"], dtype=mpd.StringDtype())})
>>> from pandas.api.exchange import from_dataframe
>>> out2 = from_dataframe(df)
>>> out2
   foo
0  NaN
>>> out2["foo"].dtype
dtype('O')
```

**System information:**
- **OS Platform and Distribution**: Linux Ubuntu 20.04.4
- **Modin version**: 0.15.2
- **Python version**: 3.8.10

cc @vnlitvinov (I'm assuming you'd want to be cc'd for these kind of issues, let me know if not :sweat_smile:)

**Comment by honno** [comment]
Possibly a problem with validity buffer providing the wrong value for masking (or indeed the mask itself being wrong), like with https://github.com/vaexio/vaex/issues/2083

**Comment by anmyachev** [comment]
Fixed by https://github.com/modin-project/modin/pull/6523
