### ISSUE TITLE
Docs: Broken link on benchmarks/tutorials page

### ISSUE THREAD

**Issue by alejandro-ponder** [modin-project/modin#4661]
data science benchmarks link in docs is broken: "Using Modin with the NYC Taxi Dataset [[Source](https://github.com/modin-project/modin/blob/master/examples/jupyter/NYC_Taxi.ipynb)]"

**Comment by shahx95** [comment]
Hi @alejandro-ponder.  I'd like to take this up.

**Comment by mvashishtha** [comment]
The link to the taxi dataset seems to be correct [here](https://modin.readthedocs.io/en/latest/getting_started/examples.html#usage-examples) now, so I'm closing this issue. 

@shahx95 thank you so much for volunteering to contribute! Would you like to take another issue tagged as a good first issue? There are some of those [here](https://github.com/modin-project/modin/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue+%F0%9F%94%B0%22), including #4636.
