### ISSUE TITLE
Fix replacing __class__ for decorated classes and methods

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#4663]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`): 35782883efd7e22f8e29a7c9887a4453adabf783
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

`modin/experimental/cloud/meta_magic.py` has a `make_new()` method which should replace `__class__` closure variable for all methods within a class being wrapped. It currently does not take decorated methods into account, so it does not replace `__class__` there effectively breaking the seamless replacement.

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
