### ISSUE TITLE
BUG: internal and external dtype mismatch leads to incorrect types in iloc result

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4675]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Monterey 12.4
- **Modin version** (`modin.__version__`): 5af9832d7fad3d17f05d63908bc377e61542d953
- **Python version**:  3.10.4
- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df1 = pd.DataFrame(['a'])
df2 = pd.DataFrame([2])
df = pd.concat([df1, df2])
print(df.iloc[1:].dtypes)
```

### Describe the problem
In the script above, modin gives me dtype `int64`, and pandas gives dtype `object`. The modin frame has two partitions, the first of which internally has `object` dtype and the second of which has `int64` dtype. The modin frame also has the correct overall dtype of `object`. However, `iloc` internally gets `iloc` result from the second partition, which doesn't know about the overall dtypes.

The bug in general is similar to bugs we've had earlier with syncing internal and external row and column labels. I think in dtypes the bugs are not as obvious, so the synchronization isn't usually a problem. I wonder how many other functions have bugs like `iloc`'s here. 

For now, I think it's okay to just fix `iloc`.

**Comment by noloerino** [comment]
This particular reproducer with `pd.concat` seems to have been fixed by 8f3f38 -- I'm not sure if there's any other form of DataFrame construction that could lead to this bug.

**Comment by pyrito** [comment]
Agreed with @noloerino , it seems like we are getting the right dtype here now, so I am going to go ahead and close this issue.
