### ISSUE TITLE
PERF: Avoid deepcopy in Series arithmetic operations

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4705]
xref #4689 

In cases such as `df[0] - df[1]`, we have `df[0].index._id is df[1].index._id`, which means the `.equals` check in the alignment step is cheep.  Making a deep copy resets the two `_id` objects, making the alignment much more expensive.

**Comment by pyrito** [comment]
Thanks for opening the issue @jbrockmendel

**Comment by jbrockmendel** [comment]
closed by #4689?

**Comment by mvashishtha** [comment]
@jbrockmendel yes. On your future PRs please be sure fill out the PR template. The template includes a portion for the issue like `Resolves #`. If you put the issue number there, GitHub will close the issue automatically once the PR is merged.
