### ISSUE TITLE
PERF: slow `concat`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4727]
Measured on master (https://github.com/modin-project/modin/commit/cfafbb254c221dd4f739a9cf5af17c9e8cdf13c3), Ray, 8 cores.

Problem: too much time is spent doing `concat`, it can be much faster. Pandas vs Modin: 0.89 sec vs 4,5 sec.

Possible solution: compute `new_widths` via `_column_widths_cache` where possible.

Script:
```python
import modin.pandas as pd
import numpy as np
from time import time

random_state = np.random.RandomState(seed=42)
array = random_state.rand(10**6, 35)

df1 = pd.DataFrame(array)
df2 = pd.DataFrame(array)

df1 = df1 - 1
df2 = df2 - 2

start = time()
df = pd.concat([df1, df2], axis=1, copy=False)
print(f"concat time: {time()-start}") <-- 4,5 sec
```

**Comment by pyrito** [comment]
@anmyachev have you profiled to see where most of the time is spent when doing `concat`?

**Comment by anmyachev** [comment]
@pyrito 100% in https://github.com/modin-project/modin/blob/cfafbb254c221dd4f739a9cf5af17c9e8cdf13c3/modin/core/dataframe/pandas/dataframe/dataframe.py#L177 and most likely in [`_filter_empties`](https://github.com/modin-project/modin/blob/cfafbb254c221dd4f739a9cf5af17c9e8cdf13c3/modin/core/dataframe/pandas/dataframe/dataframe.py#L222).

Access to some fields will trigger the evaluation of pending operations, but there is a way to avoid this in some cases.

**Comment by pyrito** [comment]
@anmyachev I ran the same script you provided on an AWS Linux instance with 8 cores and did not see the same 4,5 sec performance that you were seeing. Do you have some more context on how you tested this?

**Comment by anmyachev** [comment]
I run this script on my local machine with 16GB (however only 6-8GB were available). It's possible that I got into a situation when Ray use object spilling.

What are yours times?

**Comment by pyrito** [comment]
@anmyachev This is what I'm seeing:
```
pandas took 1.19 seconds
modin took 1.44 seconds
modin w/benchmark mode took 0.0042 seconds
```

**Comment by pyrito** [comment]
Nevertheless, I think your PR addresses this @anmyachev

**Comment by anmyachev** [comment]
@pyrito thanks for checking that!

**Comment by pyrito** [comment]
@anmyachev yeah of course! I was a bit puzzled to see modin finish the `concat` quickly in BenchmarkMode, but then I recall that benchmark mode resolves computations immediately, so it didn't wait on the binary operation for `df1` and `df2`.
