### ISSUE TITLE
STY: rename QueryCompiler.view to something more consistent

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4729]
QueryCompiler.view seems to behave more like PandasDataframe.mask (which in turn is completely different from pandas.DataFrame.mask).

I propose that both QueryCompiler.view and PandasDataframe.mask (and whatever other relevant methods are out there) be renamed to something like `take_2d` or possibly `take_or_slice_2d`

**Comment by mvashishtha** [comment]
@jbrockmendel your proposal sounds great to me. Maybe for further clarity we could use `take_2d_labels` or `take_2d_positions` for take-2d-like methods that only take labels or positions, respectively.

**Comment by jbrockmendel** [comment]
Cool.  Are there any other methods that we should get while we're at it?

Are there any scenarios in which these don't make copies?  If so then "take" might not be appropriate. (but it'd be nice to have no-copy variants)

**Comment by mvashishtha** [comment]
@jbrockmendel 

> Are there any other methods that we should get while we're at it?

I can't think of anything else. Just `view` in the query compilers and `mask` at lower levels.

> Are there any scenarios in which these don't make copies? 

`loc` and `iloc` on a dataframe make copies of the `modin.pandas` dataframe, query compiler, and `PandasDataframe`, but they actually use the same partitions pointing to the same data, e.g. 

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 100, (2**10, 2**10)))
loc_2d_taken = df.loc[:,:]
iloc_2d_taken = df.iloc[:,:]

assert  loc_2d_taken._query_compiler._modin_frame._partitions[0,0] is df._query_compiler._modin_frame._partitions[0,0]
assert  iloc_2d_taken._query_compiler._modin_frame._partitions[0,0] is df._query_compiler._modin_frame._partitions[0,0]

assert  loc_2d_taken._query_compiler._modin_frame._partitions[0,0]._data is df._query_compiler._modin_frame._partitions[0,0]._data
assert  iloc_2d_taken._query_compiler._modin_frame._partitions[0,0]._data is df._query_compiler._modin_frame._partitions[0,0]._data
```

So I guess I would count the results as *not* copies.

**Comment by mvashishtha** [comment]
> So I guess I would count the results as not copies.

I think in the example above, the full slice short circuits the usual `PandasDataframe.mask` code. But more generally the `iloc` makes a new set of partitions with an `iloc` added to the call queue: https://github.com/modin-project/modin/blob/05bf659b67d2b7153d8aaa004dd95252377eed51/modin/core/dataframe/pandas/partitioning/partition.py#L188

Ray objects are immutable, and adding anything to the call queue means the new data is the result of a new Ray function call, so in that case the result data is a copy. I think `add_to_apply_calls` works the same way in Dask, and we make a copy.

**Comment by jbrockmendel** [comment]
> So I guess I would count the results as _not_ copies.

I think I worded the question poorly.  I meant "copy" as in "copying the underlying data, which can be expensive, and putting it in a new object", as opposed to "making a new object backed by the same data, which is cheap".  in pandas we would call this `.copy(deep=True)` vs `.copy(deep=False)`.

It sounds like modin is doing a third thing, making a copy of the data but not a new object?

**Comment by mvashishtha** [comment]
> It sounds like modin is doing a third thing, making a copy of the data but not a new object?

No, Modin will normally do "copying the underlying data, which can be expensive, and putting it in a new object". A typical `loc` or `iloc` will create a new pandas API object (series or dataframe), query compiler, modin frame, and partitions, which will ultimately get new references to new remote data, e.g.:


```python
import modin.pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]])
view = df.loc[[1], [0]]
assert view._query_compiler._modin_frame._partitions[0,0] is not  df._query_compiler._modin_frame._partitions[0,0]
# new partition still has old _data, but it has a loc[] on the call_queue
print(view._query_compiler._modin_frame._partitions[0,0].call_queue)
assert view._query_compiler._modin_frame._partitions[0,0]._data ==  df._query_compiler._modin_frame._partitions[0,0]._data
# convert view to pandas to flush ilocs from call queues so partitions have updated data
view._to_pandas()
# now the `view` partitions point to distinct `_data` references
assert view._query_compiler._modin_frame._partitions[0,0]._data != df._query_compiler._modin_frame._partitions[0,0]._data

```

but note that the lazy `add_to_apply_calls` I linked [here](https://github.com/modin-project/modin/issues/4729#issuecomment-1198911434) means that we defer creating the copy of the underlying data until it's needed for another operation. Above, the `_to_pandas` drains the call queue. I agree that we don't want to copy a large piece of data for operations like this, but on the other hand, we don't want to keep copying the entire original data from the object store when we have to do some operation on just a view of it. The current implementation of `view` means that the first time we have to do something with the subset of the data (say, with `view` above), we save just that subset in the object store (this is the new partition's new `_data`), and on subsequent accesses to `view`, we'll only have to access that small piece.

> in pandas we would call this .copy(deep=True) vs .copy(deep=False).

modin series and dataframe do support shallow copies for the entire object. These copies are backed by the same data: https://github.com/modin-project/modin/blob/05bf659b67d2b7153d8aaa004dd95252377eed51/modin/pandas/base.py#L1035-L1040

**Comment by jbrockmendel** [comment]
> A typical loc or iloc will create a new pandas API object (series or dataframe), query compiler, modin frame, and partitions, which will ultimately get new references to new remote data, e.g.:

Doesn't this conflict with

> but they actually use the same partitions pointing to the same data, e.g.

?

**Comment by mvashishtha** [comment]
> Doesn't this conflict with

It does. I think my second statement is correct. I should correct my first statement about "actually use the same partitions pointing to the same data" to say that it only seems to apply to copies (either deep or not) and full slices like `loc[:]`.
