### ISSUE TITLE
BUG: passing a function returning a series to Series.apply raises KeyError: 'DataFrame'

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4734]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Monterey
- **Modin version** (`modin.__version__`): 05bf659b67d2b7153d8aaa004dd95252377eed51
- **Python version**: 3.10.4
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
import pandas

pd.Series(1).apply(lambda x: pandas.Series([x, x]))
```

### Describe the problem
In pandas the above script gives a dataframe:

```
   0  1
0  1  1
```

In modin I get an error from `result = globals()[return_type](query_compiler=result)`. The string `"DataFrame"` isn't in `globals()`.

### Source code / logs
<details>

<summary>Stack trace</summary>

```
UserWarning: Distributing <class 'int'> object. This may take some time.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <cell line: 4>()
      1 import modin.pandas as pd
      2 import pandas
----> 4 pd.Series(1).apply(lambda x: pandas.Series([x, x]))

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/_compat/pandas_api/latest/series.py:28, in LatestCompatibleSeries.apply(self, func, convert_dtype, args, **kwargs)
     27 def apply(self, func, convert_dtype=True, args=(), **kwargs):
---> 28     return self._apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/pandas/series.py:663, in Series._apply(self, func, convert_dtype, args, **kwargs)
    661         return result
    662 else:
--> 663     result = globals()[return_type](query_compiler=result)
    664     if result.name == self.index[0]:
    665         result.name = None

KeyError: 'DataFrame'
```

</details>

**Comment by pyrito** [comment]
This is an interesting bug. The reason why we are not seeing `DataFrame` in globals is because it's not being imported properly. If we do import and check the type properly by doing something like this:
```python
     ...
    else:
            from .dataframe import DataFrame
            
            if return_type == "DataFrame":
                result = DataFrame(query_compiler=result)
                
            elif return_type == "Series":
                result = Series(query_compiler=result)
                if result.name == self.index[0]:
                    result.name = None
            else:
                raise TypeError("return type is somehow not DataFrame or Series.")
            
            return result
```
I get an output like this:
```Out[3]: 
                  __reduced__
0  0    1
1    1
dtype: int64
```
Which doesn't seem fully correct. IIRC, `__reduced__` means the Series column does not have a name.

**Comment by mvashishtha** [comment]
@pyrito yes, your fix does get the type we want! However, I see that the result is a 1x1 frame whose only value is `pandas.Series([1, 1])`. We get that result because when the `apply` function returns a `DataFrame`, we return the result of `Series.map`:

https://github.com/modin-project/modin/blob/3f985ed6864cc1b5b587094d75ca5b2695e4139f/modin/pandas/series.py#L651-L663

but mapping every element of the series `pands.Series(1)` gives the 1x1 dataframe.

I don't know yet how to solve this problem.

**Comment by pyrito** [comment]
After investigating this a bit more I think what we are doing is not _fundamentally_ incorrect, besides the fact that we have `__reduced__` was the name for one of the DataFrame columns. If we don't set it as that, we end up getting this as an output:
```
                            0
0  0    1
1    1
dtype: int64
```
which is also incorrect as you have stated @mvashishtha . However, after reading the code, it looks like we are doing exactly this:
```python
y = lambda x: pandas.Series([x, x])
print(pandas.DataFrame(pandas.Series(1)).applymap(lambda s: y(s)))
```
This gives us the same output as the one mentioned above. i tried some other different apply combinations with pandas and I was getting some weird results, so I'm not sure what the best approach is here.

**Comment by pyrito** [comment]
I started a PR for this, but haven't gotten around to cleaning it up and getting it merged it. I'll try to prioritize this.
