### ISSUE TITLE
Support parallel CSV reads for different file schemas (e.g. `gs://`)

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#4742]
**Is your feature request related to a problem? Please describe.**
Currently `read_csv` only supports parallel reads for `s3` and `file` and any other filesystem backend defaults to pandas. We should try to support the following schemes as well: ftp and gs.

**Comment by pyrito** [comment]
@prutskov oops yes! I just edited the issue. Thanks for pointing it out.

**Comment by prutskov** [comment]
Take a look at this discussion (https://github.com/modin-project/modin/pull/4710#discussion_r937833450) when somebody starts to implement this.

**Comment by pyrito** [comment]
Should be supported as of #4898
