### ISSUE TITLE
Fix Modin conformance to data interchange API spec

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#4746]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Modin version** (`modin.__version__`): cfafbb254c221dd4f739a9cf5af17c9e8cdf13c3
- **Python version**: any
- **Code we can use to reproduce**:

### Describe the problem
Since https://github.com/data-apis/dataframe-api/pull/74 and https://github.com/data-apis/dataframe-api/pull/69 were merged, the interchange spec has changed a little bit. We need to align our implementation with it.

### Source code / logs

Note on testing: some bits in https://github.com/data-apis/dataframe-interchange-tests could be looked into.

**Comment by honno** [comment]
> ###
> 
> Note on testing: some bits in https://github.com/data-apis/dataframe-interchange-tests could be looked into.

FYI updates to the test suite are in https://github.com/data-apis/dataframe-interchange-tests/pull/11. Ignoring the roundtrip tests (as obviously everything's out of sync now), everything from #4763 looks good ([save known issues](https://github.com/modin-project/modin/issues/created_by/honno)).

```bash
pytest --disable-warnings tests/ -k "modin and not from_dataframe"
```
