### ISSUE TITLE
module 'modin.pandas' has no attribute 'HDFStore'

### ISSUE THREAD

**Issue by Wilson-G** [modin-project/modin#476]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAC OS 10.14.6
Modin installed from (source or binary): pip
Modin version: 0.2.2
Python version: 3.6
Exact command to reproduce: pd.HDFStore(query, project_id, private_key, dialect)
Describe the problem
I'm getting this error when I'm trying to read hdf data , as worked in Pandas library.

Source code / logs
AttributeError: module 'modin.pandas' has no attribute 'HDFStore'

**Comment by devin-petersohn** [comment]
Hi @Wilson-G, thanks for posting this! 

We will have a preliminary way to do this in Modin 0.4, which is planned for pre-release later this week.

**Comment by Wilson-G** [comment]
Cool! Thanks for all of your works

**Comment by devin-petersohn** [comment]
Hi @Wilson-G, sorry some things took slightly longer than expected.

This is available as a pre-release. Try install with `pip install --pre modin` to see if it works for you. It is currently defaulting to pandas for HDFStore, but we do have fast readers (and hopefully writers soon) for HDF5 files with `pd.read_hdf`, so integrating the code paths together shouldn't be too much of an issue. I am going to label that integration as [Help Wanted]() for now until one of our Committers can get to it. Thanks again for posting, and let me know if it is working for you!

**Comment by Wilson-G** [comment]
Hi @devin-petersohn, I tried to use pip install --pre modin to install the pre version but it seems nothing changed cause a lot fo "Requirement already satisfied:" printed on my screen.

And also I tried to install the version 0.4.0 by the .whl file in the release, yes it works, but also no HDFStore module found in the 0.4.0 version.

I don't know why it doesn't work for me to install the pre version

**Comment by devin-petersohn** [comment]
You can try `pip install modin==0.4.0rc1` or `pip install -U --pre modin`. Both of those should work. 

You can also try to install from the [master branch](https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch). We are running a test that runs code directly from pandas documentation: https://github.com/modin-project/modin/blob/master/modin/pandas/test/test_io.py#L878-L891, so it should be working.

**Comment by devin-petersohn** [comment]
Hi @Wilson-G, we released 0.4, so `pip install -U modin` should fix this problem.

Feel free to reopen the issue if you still have this problem.
