### ISSUE TITLE
PERF: `_propagate_index_objs` can be implemented to compute caches

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4794]
Place:
https://github.com/modin-project/modin/blob/aeff7ac70162b53f8c6178f048498c2ee9bd631b/modin/core/dataframe/pandas/dataframe/dataframe.py#L515

Most likely, we will have to change the interface of `add_to_apply_calls` function so that it passes caches to the partition constructor.

**Comment by YarShev** [comment]
Same applicable to apply. Working on this in https://github.com/YarShev/modin/commit/adb38ca15eb70d396fed7bd45bde86e71a27fb63.
