### ISSUE TITLE
DOCS: Improve developer experience in Issues template

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#4814]
**Is your feature request related to a problem? Please describe.**
Currently our Github issues template for bugs misses code blocks for the reproducible example and error logs. We should make the developer experience a little nicer by adding a code block and drop-down log area within the template.

**Comment by mvashishtha** [comment]
@pyrito I think that's a great idea! We could take inspiration from the [pandas bug template](https://github.com/pandas-dev/pandas/blob/08fd9c0c0cc939a5c41bb4d198349d42efd986de/.github/ISSUE_TEMPLATE/bug_report.yaml). It doesn't have collapsible sections, though, and I really like those.

**Comment by pyrito** [comment]
@mvashishtha I was thinking of taking some inspiration from pandas, but not too much since I still want to keep this relatively lean. We're not getting flooded by Github Issues at the moment, so I don't think it needs to be as robust. Thoughts?

**Comment by mvashishtha** [comment]
@pyrito the pandas bug report template is pretty simple to code and I don't see any downside to copying a lot of it. I would like to have some way to put stack traces in collapsible sections automatically, though.

**Comment by pyrito** [comment]
@mvashishtha I tried creating a bug report on pandas right now and it's actually a lot nicer since the text boxes are rendered directly, so I agree. I think we can copy most of it.

**Comment by pyrito** [comment]
@mvashishtha in that same light, I think we should have different templates for documentation issues, performance issues and have different templates for each perhaps? That can be a longer term goal.
