### ISSUE TITLE
Numpy 1.16 support for future read_hdf

### ISSUE THREAD

**Issue by adithyabsk** [modin-project/modin#482]
Due to this issue (https://github.com/PyTables/PyTables/issues/717) it seems that, at least on my host machine, the latest version of numpy is needed to store and play with large datasets using hdf5. Naturally, I would love to use modin (ray) for these purposes and but realized that modin runs with numpy<=1.15.

I downloaded the source of Ray from github to test to see if numpy 1.15+ was supported and it seems that tests were failing for numpy 1.16.1. I was curious if modin planned to support higher versions of numpy in the near term as would be required to interplay with py tables.

**Comment by devin-petersohn** [comment]
Hi @adithyabsk, thanks for posting this!

We do plan to update this dependency in the near-term, but there are some minor changes needed internally to Modin. Ideally this will happen early-mid March. We have other robustness issues higher on the backlog, so for now I will add this to the [Help Wanted](https://github.com/modin-project/modin/labels/Help%20Wanted%20%3Aglobe_with_meridians%3A) queue until we are ready to start it in case anyone is interested in picking this up.

**Comment by williamma12** [comment]
Hi @adithyabsk, sorry for the delay!

I'm looking into updating numpy to 1.16 and hopefully should have it merged into master by the end of the week. Once it gets merged, you can install from master using `pip install git+https://github.com/modin-project/modin`.
