### ISSUE TITLE
Column lookups on GroupBy with arbitrary Series in by

### ISSUE THREAD

**Issue by alejandro-ponder** [modin-project/modin#4824]
**Is your feature request related to a problem? Please describe.**
Trying to groupby a column and an arbitraty calculated value as follows, but feature not implemented.

df.groupby(by=['categorical',df.date.dt.month_name() ])['another_column'].mean()

'''
NotImplementedError: Column lookups on GroupBy with arbitrary Series in by is not yet supported.
'''

**Comment by mvashishtha** [comment]
@alejandro-ponder thank you for reporting this! I see it's a duplicate of #3285.

**Comment by mvashishtha** [comment]
Duplicate of #3285
