### ISSUE TITLE
df.describe() with "include='all'"

### ISSUE THREAD

**Issue by concretevitamin** [modin-project/modin#484]
`df.describe(include='all')` is a valid pandas argument but it fails with modin.

(Awesome project @devin-petersohn!  Pushing a button & installing Modin makes loading a large dataframe >3x faster!  However, I had to resort back to pd due to this describe() issue.)

**Comment by devin-petersohn** [comment]
Thanks @concretevitamin for posting this. I tested this on latest master and it is still failing. At some point we lost the support for `include="all"`, but we should add it back.

I will get this in before the 0.4.0 final release is cut. Thanks again for finding and posting this!

**Comment by devin-petersohn** [comment]
Resolved via #486
