### ISSUE TITLE
Set minimal supported `fsspec` version

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#4855]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Modin version** (`modin.__version__`): 8f3f389949e8c29b72269939318f49671676291b
- **Python version**: any
- **Code we can use to reproduce**: N/A

### Describe the problem
As we do not set any constraints on `fsspec`, it is possible that some users would install incompatible versions and have weird issues, like https://stackoverflow.com/questions/73428646/typeerror-localfileopener-object-is-not-iterable. To overcome this, we should set up at least minimal version in our `setup.py` and other environment files.

**Comment by anmyachev** [comment]
Done in https://github.com/modin-project/modin/pull/6342
