### ISSUE TITLE
Unable to create DataFrame form a PyArrow table containing a Dictionary Array

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#4859]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 22.04.1
- **Modin version** (`modin.__version__`): 0.15.0+89.g8f3f3899
- **Python version**: 3.8.13
- **Code we can use to reproduce**:

import pyarrow as pa
import modin.config as cfg
from modin.pandas.utils import from_arrow
from modin.pandas.test.utils import df_equals

cfg.StorageFormat.put('omnisci')
cfg.IsExperimental.put(True)

indices = pa.array([0, 1, 0, 1, 2, 0, None, 2])
dictionary = pa.array(['first', 'second', 'third'])
dict_array = pa.DictionaryArray.from_arrays(indices, dictionary)
at = pa.table({"col": dict_array})
pdf = at.to_pandas()
print(pdf)
mdf = from_arrow(at)
print(mdf)
df_equals(mdf, pdf)

### Describe the problem
The method from_arrow() fails with the bellow error if the input table contains a dictionary. 

### Source code / logs
Traceback (most recent call last):
...
  File "pyarrow/types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int64, ordered=0>

**Comment by YarShev** [comment]
Reopening the issue because of https://github.com/modin-project/modin/pull/4864#discussion_r1030784639.
