### ISSUE TITLE
PERF: compute `lengths` cache in `concat` even if partitions are rebalanced

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4867]
This will allow operations that follow the concatenation and require lengths to not have to wait for previous operations to complete. More profit here from asynchronous execution, however, this will also reduce the number of remote calls.

**Comment by YarShev** [comment]
@anmyachev, can you revisit this?

**Comment by anmyachev** [comment]
Already done in https://github.com/modin-project/modin/blob/097ea527c8e3f099e1f252b067a1d5eb055ad0b5/modin/core/dataframe/pandas/partitioning/partition_manager.py#L1532
