### ISSUE TITLE
TST: temp files left behind after pytest modin/pandas/test/

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4879]
I see 200kx99.csv and modin/pandas/test/io_tests_data/ left behind.

could reuse pandas' tm.ensure_clean for this

**Comment by pyrito** [comment]
@jbrockmendel thanks for opening this issue. The culprit of 200kx99.csv seems to be `test___setitem__with_mismatched_partitions` in `test_indexing.py`. It also looks like we make no effort to clean up `IO_OPS_DATA_DIR`.
