### ISSUE TITLE
usecols argument is not working properly in read_csv function

### ISSUE THREAD

**Issue by panurjoma** [modin-project/modin#4884]
Always return the first column independently of the column name specified in the usecols argument. 

my modin version is 0.15.2

**Comment by pyrito** [comment]
Hi @panurjoma , thank you for opening this issue! Could you give us some more context with regards to the bug you are facing? Is it possible for you to post a reproducer of the issue?

**Comment by panurjoma** [comment]
Hi @pyrito thank you for your response. I leave you here an example of the file to execute to test modin.pandas versus pandas. pandas is giving the correct answer but modin.pandas give the first column instead the column indicated. 

[](https://github.com/panurjoma/Example_repository/blob/main/test_usecols_modin.py)

and here a link to the .txt data to read with the function read_csv:

[](https://github.com/panurjoma/Example_repository/blob/main/test_nav_313_NAVRecorder_2022-03-10-13-44-24Makefile_ANAVInternalData_A.txt_NAVPlayer.txt)

Thank you in advance and I will wait for your updates! It is a little bit urgent in case that I could help you with something. 

Best regards!

**Comment by RehanSD** [comment]
Hi @panurjoma! I've tried replicating the bug locally, but can't seem to - would you mind sharing a stack trace for me where you encounter this bug?

This is the result of me trying the replication script you attached locally!
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/17012605/186727077-067196cb-695b-42f1-9319-f8daf9a886c2.png">

**Comment by panurjoma** [comment]
Hi @RehanSD, this is the code I execute and also the result. 

![image](https://user-images.githubusercontent.com/61909255/186765381-4b64e963-b81f-466d-816f-ad5b35e84874.png)

![image](https://user-images.githubusercontent.com/61909255/186765498-4f0de7a4-6207-4f7d-a60c-57e53d4b65df.png)

which version of pandas, modin do you have? Also apart from that which version of ray?

thank you in advance. 

Best regards.

**Comment by RehanSD** [comment]
Hi @panurjoma! Thank you - just realized I was testing with the latest version of Modin! It seems that this issue is fixed there, so would you mind pip installing modin from GitHub (like so: `pip install -U pip install git+https://github.com/modin-project/modin`)? We'll be releasing a new version of Modin soon, so the fix should be public soon!

**Comment by panurjoma** [comment]
Hi @RehanSD , thank you for the clarification. I will install the version from github and try again. The next modin version is the 0.15.3? thank you and we keep in contact!

**Comment by panurjoma** [comment]
Hi again @RehanSD. I have observed that the function 'concat' is not working properly when you pass modin frames to the function, is this the desired behaviour? I have to pass pandas frame in order to make it work?

**Comment by panurjoma** [comment]
hi again @RehanSD, forget about the last comment, I was importing pandas instead of modin.pandas xd. Thank you again!

**Comment by pyrito** [comment]
@panurjoma I will go ahead and close this issue if you are not having this specific issue! If you have another one, please feel free to open a new issue!

**Comment by panurjoma** [comment]
@pyrito perfect, for me there is no problem, you could close the issue.
