### ISSUE TITLE
BUG: `base_lengths` should be computed from `base_frame` instead of `self` in `copartition`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4914]
In some cases, `self` object may be empty, which may lead to incorrect work, for example, for `insert` function.

Place: https://github.com/modin-project/modin/blob/eee5f435f68786778184c4886ff25d386fce0c4f/modin/core/dataframe/pandas/dataframe/dataframe.py#L2486

**Comment by pyrito** [comment]
This is a good catch. Do you have a specific test/reproducer for such a case?

**Comment by anmyachev** [comment]
> This is a good catch. Do you have a specific test/reproducer for such a case?

It is quite difficult to write a test because this situation will only occur when `take_2d_labels_or_positional` function returns a core dataframe that has no cached lengths, and this will happen after I change the function in that way so it stops triggering the length calculation in the cases when we work with columns.

![image](https://user-images.githubusercontent.com/45976948/187972217-d64f6e43-26e6-40ec-b732-f0dce2f64ca0.png)
