### ISSUE TITLE
Modin only uses less than half memory

### ISSUE THREAD

**Issue by cnll0075** [modin-project/modin#492]

**Comment by devin-petersohn** [comment]
Hi @cnll0075, I see that you have closed this, but just in case you still haven't found the answer:

We have an environment variable we track called `MODIN_MEMORY`. This setting is experimental, but it should allow you to set however much memory you'd like for Modin.

Also, if you would like to exceed memory, we have an experimental out-of-core implementation ([docs](https://modin.readthedocs.io/en/latest/out_of_core.html))

**Comment by cnll0075** [comment]
Hi thanks a lot for your note. I actually have another question that I
don't know if I should raise an issue for. Looks like using some Numpy
manipulations with Modin is much slower than using pandas, for example, for
this command, "data[i] = np.where(data[i]=='',np.nan,data[i])" takes at
least 5-6 times longer than native pandas. I wonder what is the reason, and
if I should other functions for this type transformations.

**Comment by devin-petersohn** [comment]
That is a great question. I think it would be good to ask that question as an issue or on our new Discourse board (discuss.modin.org). That way it is easy to find for other people who have the same question.
