### ISSUE TITLE
BUG: `dtypes` wrong computation in `dataframe.filter`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4927]
Place: https://github.com/modin-project/modin/blob/19ac8ff208eb02a7f86037e338ce306f1e96d7a9/modin/core/dataframe/pandas/dataframe/dataframe.py#L1882

**Comment by YarShev** [comment]
It would be great to have a reproducer where Modin fails but pandas doesn't.

**Comment by anmyachev** [comment]
> It would be great to have a reproducer where Modin fails but pandas doesn't.

The bug was that the axis was never equal to 0 and the `dtypes` were always equal to `None`, which forced the types to always be recalculated.
