### ISSUE TITLE
BUG: `try_cast_to_pandas` doesn't preserve `dtypes` for empty frame

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#4934]
Reproducer:
```python
def test_try_cast_to_pandas_preserve_dtypes():
    modin_df = pd.DataFrame({"col": [1]}, dtype=np.int64)
    pandas_df = pandas.DataFrame({"col": [1]}, dtype=np.int64)
    modin_df.query("col > 2", inplace=True), pandas_df.query("col > 2", inplace=True)
    casted_to_pandas_df = modin.utils.try_cast_to_pandas(modin_df)
    df_equals(casted_to_pandas_df, pandas_df)
    df_equals(casted_to_pandas_df.dtypes, pandas_df.dtypes)
```
Error:
```python
E   AssertionError: Series are different
E   
E   Series values are different (100.0 %)
E   [index]: [col]
E   [left]:  [object]
E   [right]: [int64]
```

**Comment by mvashishtha** [comment]
@anmyachev @Billy2551 is working on #4605. In case you don't need this fixed urgently, you could skip the fix and wait for a comprehensive fix, which should hopefully come within 3 months, for #4605.

**Comment by anmyachev** [comment]
> @anmyachev @Billy2551 is working on #4605. In case you don't need this fixed urgently, you could skip the fix and wait for a comprehensive fix, which should hopefully come within 3 months, for #4605.

Good! My other PR highlights this problem in CI, then I'll just mark it as xfail.

**Comment by anmyachev** [comment]
From what I've seen so far, `from_pandas` function doesn't save dtypes of the empty dataframe either (because the empty dataframe doesn't get into `put` function).

**Comment by anmyachev** [comment]
Problem not reproducible on [master](https://github.com/modin-project/modin/commit/29d9da056a4e4766314c4ae9ea62b33e0d52e662).
