### ISSUE TITLE
Support pandas 1.4.4

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4939]
And soon 1.5.0

**Comment by Garra1980** [comment]
1.4.4 already supported in 0.15.3 I believe

**Comment by pyrito** [comment]
Yes, pandas 1.4.4 is supported in 0.15.3, so I'll go ahead and close this issue.

**Comment by jbrockmendel** [comment]
when i pip upgrade pandas i see

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
modin 0.15.0+58.g3782b9fb requires pandas==1.4.3, but you have pandas 1.4.4 which is incompatible.
```

**Comment by pyrito** [comment]
@jbrockmendel this is when you are using the 0.15.3 cut?

**Comment by pyrito** [comment]
This PR bumped everything up: https://github.com/modin-project/modin/pull/4926
