### ISSUE TITLE
PERF: `concatenate` on wide DataFrames has poor performance

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#4940]
Our current implementation of `concatenate` (used in `to_pandas()` to combine row partitions) tries to iterate over all columns to find which ones are categorical types. This approach results in very poor performance for wide DataFrames:

```python
In [1]: import modin.pandas as pd

In [2]: import numpy as np

In [3]: df = pd.DataFrame(np.random.randint(0,100, size=(1,100000)))
UserWarning: Ray execution environment not yet initialized. Initializing...
To remove this warning, run the following python code before doing dataframe operations:

    import ray
    ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.

In [4]: %time df._to_pandas()
CPU times: user 1min 47s, sys: 984 ms, total: 1min 48s
Wall time: 1min 48s
Out[4]: 
   0      1      2      3      4      5      6      7      8      9      10     11     12     ...  99987  99988  99989  99990  99991  99992  99993  99994  99995  99996  99997  99998  99999
0     38     89     98     43     25     34     63     32     32     71     34     82     15  ...     90     40      0     41     12      6     24      1     45     11     74     17     28

[1 rows x 100000 columns]
```
A cleaner solution proposed by @mvashishtha would use `select_dtypes` to get columns that are the category dtype and then iterate over those.

**Comment by pyrito** [comment]
@mvashishtha I'd assume that if we weren't this test would fail right: https://github.com/modin-project/modin/blob/b09dd424e95830e6a19a631741eb8381b9020ee5/modin/pandas/test/test_general.py#L743

**Comment by mvashishtha** [comment]
> I 'd assume that if we weren't this test would fail right:

I think there's only one row partition in that test, so we don't have to union multiple types.
