### ISSUE TITLE
The OmniSci tests fail with "libjvm.so: cannot open shared object file" error

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#4962]
### System information
- **OS Platform and Distribution**: Ubuntu 22.04.1
- **Modin version** (`modin.__version__`): 0.15.0+123.g9fe020ba
- **Python version**: 3.8.13
- **Code we can use to reproduce**:
pytest modin/test/storage_formats/omnisci/test_internals.py

### Describe the problem
The  OmniSci tests fail with "libjvm.so: cannot open shared object file" error. The root cause of the issue is openjdk  17.0.3   h85293d2_2  from conda-forge package, that has a different libraries location. The expected library path is lib/server/libjvm.so, but the actual path is lib/jvm/lib/server/libjvm.so.

**Comment by Garra1980** [comment]
Fix is here - https://github.com/conda-forge/hdk-feedstock/pull/5

**Comment by AndreyPavlenko** [comment]
> Fix is here - [conda-forge/hdk-feedstock#7](https://github.com/conda-forge/hdk-feedstock/pull/7)

The issue has been resolved.
