### ISSUE TITLE
BUG: calling pd.to_timedelta on modin series gives TimedeltaIndex instead of Series

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4966]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Monterey
- **Modin version** (`modin.__version__`): b09dd424e95830e6a19a631741eb8381b9020ee5
- **Python version**: 3.10.4
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
import pandas

duration = pd.Series([1])
print(pd.to_timedelta(duration), '\n\n')

duration_pandas = pandas.Series([1])
print(pandas.to_timedelta(duration_pandas))
```

### Describe the problem
pandas documents the correct return types here: https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html

If input is a series, result should be another series.

**Comment by pyrito** [comment]
@mvashishtha this is an interesting bug. It seems like we just default to the pandas implementation which obviously doesn't know how to handle Modin series. It looks like we need to implement our own version of `to_timedelta` and if the input it a Series we change the dtype of the df? Do we need to do any explicit casting on each element or is it enough to just change the dtype?

**Comment by mvashishtha** [comment]
#5028 fixed this bug. Thanks @Billy2551
