### ISSUE TITLE
BUG: TEST: fuzzydata does not provide artifacts on failure

### ISSUE THREAD

**Issue by suhailrehman** [modin-project/modin#5032]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Issue Description

First discovered in issue #4983. 
The referenced job should have downloadable artifacts that allow for it to be re-run in Fuzzydata to pinpoint the errors:
https://github.com/modin-project/modin/actions/runs/3062497807/jobs/4943541816 

### Expected Behavior

If there's a fuzzydata run that errored out after at least a few operations are completed, they should be downloadable from the actions tab. An example of a successful run with downloadable artifacts is below:

https://github.com/modin-project/modin/actions/runs/3120556547

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>
Fix requires an update to Action YAML
</details>

**Comment by mvashishtha** [comment]
@suhailrehman how do I get the artifacts for this failure: https://github.com/modin-project/modin/actions/runs/3349949579/jobs/5550403137

**Comment by suhailrehman** [comment]
It's shown on the job summary page: https://github.com/modin-project/modin/actions/runs/3349949579 

Direct Link: https://github.com/modin-project/modin/suites/9023889911/artifacts/416282301

**Comment by mvashishtha** [comment]
@suhailrehman is there some guide to interpreting the artifacts? I see some JSONs and CSVs, but I can't figure out what python code caused the error.
