### ISSUE TITLE
REFACTOR: Add mypy checks for modin.core.dataframe.base

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5079]

**Comment by shalearkane** [comment]
Could you please assign me this issue?

**Comment by mvashishtha** [comment]
@shalearkane sure. I'm happy to help you merge a PR for this issue. You can follow the instructions [here](https://github.com/modin-project/modin/issues/5073#issue-1395324747), except replace `modin/core/dataframe/algebra` with `modin/core/dataframe/base`.
