### ISSUE TITLE
API layer should not be using `modin._compat` or care about compatibility at all

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#5086]
`modin._compat` is encapsulating the compatibility logic, and API layer should not be using it at all.

For now some functions still use that to simplify the migration, but ideally we should get rid of that usage.

**Comment by anmyachev** [comment]
@vnlitvinov can we close the issue?

**Comment by mvashishtha** [comment]
Yep, modin doesn't have backwards compatibility any longer.
