### ISSUE TITLE
BUG: modin.pandas.series.Series object raises TypeError with matplotlib.pyplot.scatter

### ISSUE THREAD

**Issue by aarati-K** [modin-project/modin#5114]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import matplotlib.pyplot as plt
import ray
ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

# CSV file from modin/examples/data folder
data = pd.read_csv("data/boston_housing.csv")
plt.scatter(data['RM'], data['PRICE'])
plt.show()
```

### Issue Description

This is a snippet of the code from modin/examples/modin-scikit-learn-example.ipynb. A TypeError is raised when using variables of type modin.pandas.series.Series as arguments to matplotlib.pyplot.scatter().

### Expected Behavior

Scatter plot generated successfully.

### Error Logs

<details>

```python-traceback

TypeError                                 Traceback (most recent call last)
Cell In [1], line 8
      6 # CSV file from modin/examples/data folder
      7 data = pd.read_csv("data/boston_housing.csv")
----> 8 plt.scatter(data['RM'], data['PRICE'])
      9 plt.show()

File ~/workspace/py38/lib/python3.8/site-packages/matplotlib/pyplot.py:2811, in scatter(x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, plotnonfinite, data, **kwargs)
   2805 @docstring.copy(Axes.scatter)
   2806 def scatter(
   2807         x, y, s=None, c=None, marker=None, cmap=None, norm=None,
   2808         vmin=None, vmax=None, alpha=None, linewidths=None,
   2809         verts=cbook.deprecation._deprecated_parameter,
   2810         edgecolors=None, *, plotnonfinite=False, data=None, **kwargs):
-> 2811     __ret = gca().scatter(
   2812         x, y, s=s, c=c, marker=marker, cmap=cmap, norm=norm,
   2813         vmin=vmin, vmax=vmax, alpha=alpha, linewidths=linewidths,
   2814         verts=verts, edgecolors=edgecolors,
   2815         plotnonfinite=plotnonfinite, **({"data": data} if data is not
   2816         None else {}), **kwargs)
   2817     sci(__ret)
   2818     return __ret

File ~/workspace/py38/lib/python3.8/site-packages/matplotlib/__init__.py:1565, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1562 @functools.wraps(func)
   1563 def inner(ax, *args, data=None, **kwargs):
   1564     if data is None:
-> 1565         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1567     bound = new_sig.bind(ax, *args, **kwargs)
   1568     auto_label = (bound.arguments.get(label_namer)
   1569                   or bound.kwargs.get(label_namer))

File ~/workspace/py38/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py:358, in _delete_parameter.<locals>.wrapper(*args, **kwargs)
    352 if name in arguments and arguments[name] != _deprecated_parameter:
    353     warn_deprecated(
    354         since, message=f"The {name!r} parameter of {func.__name__}() "
    355         f"is deprecated since Matplotlib {since} and will be removed "
    356         f"%(removal)s.  If any parameter follows {name!r}, they "
    357         f"should be pass as keyword, not positionally.")
--> 358 return func(*args, **kwargs)

File ~/workspace/py38/lib/python3.8/site-packages/matplotlib/axes/_axes.py:4388, in Axes.scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, plotnonfinite, **kwargs)
   4384 y = self.convert_yunits(y)
   4386 # np.ma.ravel yields an ndarray, not a masked array,
   4387 # unless its argument is a masked array.
-> 4388 x = np.ma.ravel(x)
   4389 y = np.ma.ravel(y)
   4390 if x.size != y.size:

File ~/workspace/py38/lib/python3.8/site-packages/numpy/ma/core.py:6828, in _frommethod.__call__(self, a, *args, **params)
   6824 if method is None:
   6825     # use the corresponding np function
   6826     method = getattr(np, method_name)
-> 6828 return method(marr, *args, **params)

File ~/workspace/py38/lib/python3.8/site-packages/numpy/ma/core.py:4633, in MaskedArray.ravel(self, order)
   4631 r._update_from(self)
   4632 if self._mask is not nomask:
-> 4633     r._mask = ndarray.ravel(self._mask, order=order).reshape(r.shape)
   4634 else:
   4635     r._mask = nomask

TypeError: descriptor 'ravel' for 'numpy.ndarray' objects doesn't apply to a 'method' object

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 621bc10e16c21ca4270a4c2a25aa05f814f2686b
python           : 3.8.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-169-generic
Version          : #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.16.0
ray              : 2.0.0
dask             : 2022.9.2
distributed      : 2022.9.2
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.4.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.8.2
gcsfs            : None
matplotlib       : 3.2.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           :  #None
</details>

**Comment by pyrito** [comment]
@aarati-K thank you for opening the issue. I was able to reproduce this on the latest master.

@modin-project/modin-contributors has modin Series ever worked with pyplot before? I feel like we should be converting it. I wouldn't expect it to work by plugging it in directly.

**Comment by mvashishtha** [comment]
Root cause in the report by @aarati-K is a very weird error within `np.ma.ravel`:

i don't know yet which Modin function(s) to fix in order to fix the bug.

```python
import modin.pandas as pd
import numpy as np

print(np.ma.ravel(pd.Series(1)))
```

<details>

<summary>Stack trace</summary>

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 np.ma.ravel(pd.Series(1))

File ~/opt/anaconda3/envs/modin-dev/lib/python3.10/site-packages/numpy/ma/core.py:6828, in _frommethod.__call__(self, a, *args, **params)
   6824 if method is None:
   6825     # use the corresponding np function
   6826     method = getattr(np, method_name)
-> 6828 return method(marr, *args, **params)

File ~/opt/anaconda3/envs/modin-dev/lib/python3.10/site-packages/numpy/ma/core.py:4633, in MaskedArray.ravel(self, order)
   4631 r._update_from(self)
   4632 if self._mask is not nomask:
-> 4633     r._mask = ndarray.ravel(self._mask, order=order).reshape(r.shape)
   4634 else:
   4635     r._mask = nomask

TypeError: descriptor 'ravel' for 'numpy.ndarray' objects doesn't apply to a 'method' object
```
</details>

**Comment by mvashishtha** [comment]
> has modin Series ever worked with pyplot before?

@pyrito generally we don't know whether libraries that accept pandas objects will work with Modin. Seaborn is known to have bugs, #3967. One likely culprit is that the library might try to mix (e.g. do a binary operation or a merge) between a Modin.pandas frame object from the user and a pandas frame object from the library. This case looks different, though.
