### ISSUE TITLE
TEST: epic: Make codecov more useful and less annoying

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5122]
This is an epic covering a few smaller goals for codecov.

# Current state:

## Pull requests

1. Many jobs in Modin's CI that successfully finish tests will upload all coverage data (an xml from pytest) to the codecov app. The jobs upload data using `codecov/codecov-action@v2`, e.g. [here](https://github.com/modin-project/modin/blob/88f7b27d32b099c508e93251cafe503f2908d426/.github/workflows/ci.yml#L328)
2. (does not necessarily happen before 3, but in practice always does) we get an initial email and PR comment when codecov gets coverage data for the first test (see step 3 for what these results mean). codecov will keep updating this comment as more CI jobs finish. Example comment [here](https://github.com/modin-project/modin/pull/5121#issuecomment-1276241373).
3. Aggregating all the "hits" / "misses" (i.e. lines covered / not covered by tests) from all tests that ran from all workflows for the PR, codecov compares coverage on the CI jobs to coverage of the last green commit on master
    - For a PR with no changes and assuming all tests pass for both PR and master, codecov will typically give about 4% extra coverage. This is mainly because the set of CI runs for master vs a PR are different. the pull request jobs actually do have different coverage than the push-to-master jobs. e.g. here we get +100% coverage in compat because we test compat on pull request but not on merge: https://app.codecov.io/gh/modin-project/modin/pull/5048

## Commits on master
On merging commits to master, codecov calculates coverage for the project and calculates how much of the diff from the commit was covered by tests. e.g. for [this commit](https://github.com/modin-project/modin/commit/4bcce6ef12c0c80d6df15ef4a4b2b3a85713c106) we have both results [here](https://app.codecov.io/gh/modin-project/modin/commit/4bcce6ef12c0c80d6df15ef4a4b2b3a85713c106). These give confusing results, e.g. I don't understand the losses [here](https://app.codecov.io/gh/modin-project/modin/commit/d0054290ec8305d01b040e740e3f4524815ea77e). Also they don't always compare to the last green commit, so e.g. [here](https://app.codecov.io/gh/modin-project/modin/commit/0215a133ac32969ca0a4126f6aef82be099ae8ef) we seem to get a bunch of gains but that's just because the omnisci tests failed on the previous commit.

Also consider [this case](https://app.codecov.io/gh/modin-project/modin/commit/d50269468c30c422cfaa388578cbe4fda4a09fd6) where codecov is saying "CI passed" in the codecov UI but if we look at [commit](https://github.com/modin-project/modin/commit/d50269468c30c422cfaa388578cbe4fda4a09fd6), we see [ci failure](https://github.com/modin-project/modin/actions/runs/3137906060/jobs/5096628509).

# Changes that this epic covers, from most to least urgent:

1) Stop leaving the codecov comment on PRs. Currently no regular Modin contributor looks at it because it's not useful (see the subsequent tasks), and it will almost always report failure. The comment is probably really confusing to external contributors, too. If we want to look at codecov results, we can check the codecov job in CI. If eventually codecov is more useful, we can bring this comment back, but we should make sure per #2544 that we delay the notifications until all the jobs finish.
2) make push-to-master and the pull-request test coverage the same so codecov stops spuriously telling us we're adding coverage on empty PRs
3) (optional) if codecov is now useful on PRs, we can re-enable the comments we disabled for (1)
4) improve the commit-to-commit codecov accuracy by addressing the problems with it that I mentioned in "Current state".

**Comment by anmyachev** [comment]
@mvashishtha coverage calculation looks pretty stable now. Do we need the issue anymore?

**Comment by mvashishtha** [comment]
@anmyachev if it looks stable, let's close.
