### ISSUE TITLE
ArrowIOError: Memory mapping file failed: No such device

### ISSUE THREAD

**Issue by JamesCropcho** [modin-project/modin#513]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.6 LTS
- **Modin installed from (source or binary)**: attempted both; same result
- **Modin version**: 0.4.0
- **Python version**: Python 3.7.2
- **Exact command to reproduce**: `df = pd.read_parquet('./fastparquet-directory')`

### Describe the problem
The entirety of my fresh Jupyter Notebook:
```
import modin.pandas as pd
```

> Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-03-28_02-30-28_15957/logs.
> Waiting for redis server at 127.0.0.1:40086 to respond...
> Waiting for redis server at 127.0.0.1:35891 to respond...
> Starting Redis shard with 10.0 GB max memory.
> WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 402257592320 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
> Starting the Plasma object store with 482.0 GB memory using /tmp.
```
%%time

df = pd.read_parquet('./fastparquet-directory')
df
```

### Source code / logs
```
ArrowIOError                              Traceback (most recent call last)
<timed exec> in <module>

~/modin/modin/pandas/io.py in read_parquet(path, engine, columns, **kwargs)
     26     return DataFrame(
     27         query_compiler=BaseFactory.read_parquet(
---> 28             path=path, columns=columns, engine=engine, **kwargs
     29         )
     30     )

~/modin/modin/data_management/factories.py in read_parquet(cls, **kwargs)
     49     @classmethod
     50     def read_parquet(cls, **kwargs):
---> 51         return cls._determine_engine()._read_parquet(**kwargs)
     52 
     53     @classmethod

~/modin/modin/data_management/factories.py in _read_parquet(cls, **kwargs)
     53     @classmethod
     54     def _read_parquet(cls, **kwargs):
---> 55         return cls.io_cls.read_parquet(**kwargs)
     56 
     57     @classmethod

~/modin/modin/engines/ray/generic/io.py in read_parquet(cls, path, engine, columns, **kwargs)
    108 
    109         if not columns:
--> 110             pf = ParquetFile(path)
    111             columns = [
    112                 name

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/parquet.py in __init__(self, source, metadata, common_metadata, memory_map)
    126                  memory_map=True):
    127         self.reader = ParquetReader()
--> 128         self.reader.open(source, use_memory_map=memory_map, metadata=metadata)
    129         self.common_metadata = common_metadata
    130         self._nested_paths_by_prefix = self._build_nested_paths()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetReader.open()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/io.pxi in pyarrow.lib.get_reader()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/io.pxi in pyarrow.lib._get_native_file()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/io.pxi in pyarrow.lib.memory_map()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/io.pxi in pyarrow.lib.MemoryMappedFile._open()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowIOError: Memory mapping file failed: No such device
```

**Comment by devin-petersohn** [comment]
Thanks @JamesCropcho, would you let me know if the following is working for you:

```python
import ray
from pyarrow.parquet import ParquetFile

f = ParquetFile("./fastparquet-directory") # will likely fail
# Then try this one
f = ParquetFile("./fastparquet-directory", memory_map=False)
```
From the trace, it looks like Arrow is unable to mmap the file. If the first attempt in the code above throws an error, it is probably worth opening an issue in Arrow, if not we have more to figure out. In the meantime, if the second line is working for you, the source code edit is relatively simple to make Modin useful in the meantime:

In **modin/modin/engines/ray/generic/io.py**: **Line 110**
```python
# pf = ParquetFile(path)
pf = ParquetFile(path, memory_map=False)
```
Of course this is only temporary, and it will likely affect the performance somewhat until the source of the problem can be fixed. In the general case we want to keep the files mmapped for performance, so this change won't happen in Modin.

cc @pcmoritz

**Comment by JamesCropcho** [comment]
Hello all. Sorry about the delay on this; I've been swamped. I do hope to post the results of your proposed experiment.
