### ISSUE TITLE
BUG: Converting a Modin Dataframe to a Pandas Dataframe drops the column names

### ISSUE THREAD

**Issue by ponder-blog** [modin-project/modin#5130]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
# Example adapted from: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html

import modin.pandas as pd
import pandas as old_pd

data = {'row_1': [3, 2, 1, 0], 'row_2': ['a', 'b', 'c', 'd']}
data_df = pd.DataFrame.from_dict(data, orient='index',
                       columns=['A', 'B', 'C', 'D'])

old_pd.DataFrame(data_df)
```

### Issue Description

Once the Modin dataframe is convert to a pandas dataframe, it loses its column names.

### Expected Behavior

The column names should persist.

### Error Logs

No error logs -- No error is thrown

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 98a9694694584f50d03f6e27b516eb10d18d36ef
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.16.1
ray              : 1.12.1
dask             : 2022.01.1
distributed      : 2022.01.1
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.0
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 21.2.4
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : 
sqlalchemy       : 1.4.32
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by pyrito** [comment]
@ponder-blog thank you for opening this issue! I was able to reproduce this behavior on the latest master. We get the correct DataFrame in `data_df` but it seems that in your example you are trying to create a pandas DataFrame using a Modin DataFrame which shouldn't work. If you want to convert to a pandas DataFrame, you can use `_to_pandas()`.
