### ISSUE TITLE
BUG: df_categories_equal typo?

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#5138]
```python
elif isinstance(getattr(df1, "dtype"), pandas.CategoricalDtype) and isinstance(
            getattr(df1, "dtype"), pandas.CategoricalDtype
        ):
```

I'm guessing the second `getattr(df1, "dtype")` should be checking df2.dtype?

**Comment by vnlitvinov** [comment]
I now wonder why we aren't just using `df1.dtype` and `df2.dtype` in that...

**Comment by mvashishtha** [comment]
@jbrockmendel thanks for reporting this issue, but could you please add a permalink to the code next time: https://github.com/modin-project/modin/blob/08ec2e1397cf48fd26cb2a69fb378bb2f38c5d16/modin/pandas/test/utils.py#L487-L496
