### ISSUE TITLE
now I use pandas==0.24.2,so how i used the modin on windows,thanks

### ISSUE THREAD

**Issue by nankaimy** [modin-project/modin#5139]
now I use pandas==0.24.2,so how i used the modin on windows,thanks

**Comment by vnlitvinov** [comment]
Is there a specific reason for using pandas release which is 3 years old now?.. That said, latest Modin that supports _that_ ancient pandas version is somewhere around 0.5.3 or 0.5.4, but that's missing *a lot* of features we put in during these 3 years.

**Comment by nankaimy** [comment]
some projects are coded using pandas==0.24.2,so if upgrade the pandas to latest version,there would be somewhere not compatible，so keep use pandas==0.24.2。

thanks
