### ISSUE TITLE
CI: pytest 7.2.0 dropping `py` from dependencies is causing test failures

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#5154]
See: https://github.com/ionelmc/pytest-benchmark/issues/226 for more context

This is causing failures on master: https://github.com/modin-project/modin/actions/runs/3322482406/jobs/5491562285

**Comment by pyrito** [comment]
May actually be resolved now: https://github.com/ionelmc/pytest-benchmark/issues/226#issuecomment-1291158690

**Comment by mvashishtha** [comment]
pytest-benchmark 4.0.0 should fix this error, but it's not on conda forge yet, so our CI still fails: https://github.com/modin-project/modin/actions/runs/3322482407/jobs/5496407595

**Comment by pyrito** [comment]
Issue has been resolved since pytest-benchmark 4.0.0 has been updated on conda forge and pypi.
