### ISSUE TITLE
BUG: Index column name recovery

### ISSUE THREAD

**Issue by kukushking** [modin-project/modin#5158]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
df = pd.DataFrame({"c0": [0, 1], "c1": [2, 3]}, index=pd.RangeIndex(start=5, stop=7, step=1))
df.index.name = "foo"
df
Out[2]: 
     c0  c1
foo        
5     0   2
6     1   3

path = "s3://.../df.parquet"
df.to_parquet(path, index=True)
dfr = pd.read_parquet(path)
dfr
Out[3]: 
   c0  c1
5   0   2
6   1   3
dfr.index.name
```

### Issue Description

Hi folks, looks like index column name does not survive round trips when writing & reading parquet (see example) with modin. Works fine in pure pandas (see expected behavior).

Confirmed it's still an issue in main `__version__='0.16.0+24.g11ba481'`.

### Expected Behavior

Equivalent code in pandas 1.5.1:

```
import pandas as pd
df = pd.DataFrame({"c0": [0, 1], "c1": [2, 3]}, index=pd.RangeIndex(start=5, stop=7, step=1))
df.index.name = "foo"
df
Out[4]: 
     c0  c1
**foo**        
5     0   2
6     1   3

path = "s3://.../df.parquet"
df.to_parquet(path, index=True)
dfr = pd.read_parquet(path)

dfr
Out[10]: 
     c0  c1
foo        
5     0   2
6     1   3

dfr.index.name
Out[11]: 'foo'
```

### Installed Versions

commit           : 3f01114dd9c8b09376ea77bae2f11d9abef99490
python           : 3.9.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_GB.UTF-8
Modin dependencies
------------------
modin            : 0.16.2
ray              : 2.0.1
dask             : None
distributed      : None
hdk              : None
pandas dependencies
-------------------
pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 21.3.1
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.10.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

**Comment by pyrito** [comment]
It seems like the root of the issue here is that `df.index.name` isn't getting propagated to the partitions. This is actually handled by `to_csv` and `to_sql` by calling `_propagate_index_objs`, which is missing for `to_parquet`. However, this only resolves the issue for this case. We will need to look into handling this for more general cases as reported in this issue: https://github.com/modin-project/modin/issues/1618

**Comment by pyrito** [comment]
@kukushking this issue has been resolved and is in master now. Thanks!
