### ISSUE TITLE
TEST: test_groupby.py:test_not_str_by seems to unintentionally be testing an empty dataframe

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5165]
The data's column names don't match the dataframe's column names, so the dataframe is empty: https://github.com/modin-project/modin/blob/3cc33a2be050a2472fd084ccc3b9bbb33986f770/modin/pandas/test/test_groupby.py#L1928-L1929

I don't think this test was meant to test empty dataframes. I happened to find out that the dataframe was empty when I tested execution with a query compiler that had `lazy_execution` as `True`, so the groupby was not defaulting to pandas any more.

Note that when I use data to make a real frame, e.g. with `data = np.arange(5 * 5).reshape(5, 5)`, `BaseOnPython` execution has several failures:

```
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[True-by4] - TypeError: You have to supply one of 'by' and 'level'
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[True-by6] - KeyError: '[nan] not in index'
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-0] - TypeError: object of type 'int' has no len()
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-1.5] - TypeError: object of type 'float' has no len()
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-by3] - TypeError: object of type 'Timestamp' has no len()
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-by4] - TypeError: You have to supply one of 'by' and 'level'
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-by5] - ValueError: cannot insert 0, already exists
FAILED modin/pandas/test/test_groupby.py::test_not_str_by[False-by6] - KeyError: '[nan] not in index'
```

Some things that I think are going wrong: 
- setting `by` to `by.name` [here](https://github.com/modin-project/modin/blob/f492ba9888fc05ff7c224db8a22faac8c0106a4b/modin/core/dataframe/algebra/default2pandas/groupby.py#L202-L208), so we set `by` to `None`, which is illegal, so we get `You have to supply one of 'by' and 'level'`
- pandas sometimes converts the `None` in the index to `nan` and sometimes not.

cc @dchigarev who is on the git blame for this test case.

**Comment by dchigarev** [comment]
Yep, it seems that the test actually tests nothing because of my mistake. I'll assign myself to the issue in order to review failing tests and create according trackers (and probably try to make quick fixes myself)
