### ISSUE TITLE
[PERF] compute `dtypes` when performing binary operations

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#5182]
It should be possible and beneficial to compute `dtypes` when doing binary operations without remote calls so other subsequent operations, which require `dypes` to be known, do not perform the remote calls to compute it.

Here are some examples when we can compute/pass known dtypes to the core dataframe.

1. `left_df + right_df`, leftleft_df.dtypes and right_df.dtypes are known and equal to each other
2. `left_df + 1`, left_df.dtypes is known, dtype of 1 is int.

**Comment by anmyachev** [comment]
https://github.com/modin-project/modin/issues/4868

**Comment by arunjose696** [comment]
As resultant dtypes for each function are each function are dependent on the operation. Looks like this has to be done specific to each function. 

eg For add function df1+d2 for each column the resultant dtype would be determined by going through below steps. With 



Case 1)Check whether dtype of column in df1 can be casted to dtype  column of df2.  eg If A  can be casted to B. B becomes resultant dtype  

eg 

```
df1 = pd.DataFrame(np.ones((10, 10)),dtype=np.int8)
df2 = pd.DataFrame(np.ones((10, 10)),dtype=np.int16)
df3=df1+df2
print(df3.dtypes)  # prints int16
```

Case 2)In case if dtypes cant be casted. A dtype which is just higher than both of the dtypes is assigned

eg:

```
df1 = pd.DataFrame(np.ones((10, 10)),dtype=np.float16)
df2 = pd.DataFrame(np.ones((10, 10)),dtype=np.int16)
df3=df1+df2
print(df3.dtypes)  # prints float32 which is not in any of the input dtypes
```

Note: With pandas supporting 20 dtypes there can be 190 ways to combine them. With 163 of them falling in first case and 27 in second case. The first case is easily implementable. Looking into ways to implement case 2 without giving like 27 rules to handle each set of dtypes.

**Comment by YarShev** [comment]
We could use the following method from pandas. It seems to me it is used in pandas to determine resultant dtypes.

```python
from pandas.core.dtypes.cast import find_common_type

find_common_type([np.float16, np.int16])
dtype('float32')
```
