### ISSUE TITLE
Is modin's concat functionality limited to HDK only?

### ISSUE THREAD

**Issue by sabrsulab** [modin-project/modin#5191]
I am using the Dask client and have to jump between pandas and modin because of the functionality limitations for the data cleansing principles that I had to implement. There is a point in my code where I convert 50 dataframes to modin (I double-checked the types to ensure the type was correct right before I run the concat).
For my purposes I need to ignore_index and concatenate along the rows, but know that the documentation note states that HDK ignores ignore_index and axis. 

**The question:** If I'm using the Dask client, is it still ignoring those keyword arguments?

I cannot provide my code for the matter of this question, as it's for an expansive research project, but some insight into the functionality of the modin concat function would really help.

**Comment by mvashishtha** [comment]
@sabrsulab thank you for your post and welcome to the Modin GitHub. To be precise, Dask and HDK are two Modin [**engines**](https://modin.readthedocs.io/en/stable/index.html#installation-and-choosing-your-compute-engine). As the supported APIs [entry](https://modin.readthedocs.io/en/stable/supported_apis/utilities_supported.html) for `concat` suggests, every feature is supported on engines other than HDK. You can use the following script to quickly verify that `ignore_index` works:

```python
import modin.pandas as pd
from modin.config import Engine

Engine.put('dask')
df1 = pd.DataFrame([1])
df2 = pd.DataFrame([2])
# result has index pd.Index([0, 1]) because of ignore_index
print(pd.concat([df1, df2], ignore_index=True))
```

I'm going to close this issue for now. Please comment again if you have further concerns.
