### ISSUE TITLE
`drop` does not always drop columns or rows on the same partition

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#52]
### Describe the problem

`drop` does not drop columns or rows from the same partition if they contain the same name. This required a large refactor of the overall implementation.

### Source code / logs

```python
import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 2

nu_df = pandas.DataFrame(pandas.compat.lzip(range(3), range(-3, 1),
                                                 list('abc')), columns=['a', 'a', 'b'])
ray_nu_df = pd.DataFrame(nu_df)
x = ray_nu_df.drop('a', axis=1)
y =  nu_df[['b']]
print(x)
```

Printing `x` gives an error because it did not drop all of the columns it should have. However, 

```python
x._col_partitions
print(x)
```

Works correctly.

**Comment by simon-mo** [comment]
Closed by #53
