### ISSUE TITLE
BUG: binary operations fail when `other` is a dictionary

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5204]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(np.ones([2, 4]), columns=["a", "b", "c", "d"])
dictionary = {"a": 1, "b": 2, "c": 3, "d": 4}
print(df * dictionary)
```

### Issue Description

The related snippet fails with `TypeError: Cannot do operation with improper dtypes` from here:
https://github.com/modin-project/modin/blob/c30ab4c132295b1e168fbb06a050c76554759e11/modin/pandas/base.py#L296

It seems that the [`._validate_other`](https://github.com/modin-project/modin/blob/c30ab4c132295b1e168fbb06a050c76554759e11/modin/pandas/base.py#L212) function doesn't work as expected when `other` is a dictionary.

### Expected Behavior

As the pandas support binary operations between dataframe and dictionary modin should as well.

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jbrockmendel** [comment]
Does this work in pandas?

**Comment by Garra1980** [comment]
> Does this work in pandas?

yep, it prints
     a    b    c    d
0  1.0  2.0  3.0  4.0
1  1.0  2.0  3.0  4.0
