### ISSUE TITLE
BUG: inner merge works wrong

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#5212]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import pandas
from pandas.testing import assert_frame_equal


test1 = pd.DataFrame([1,2], columns=["a"])  
test2 = test1.append(test1)
test1["b"] = [3,4]
 
res_md = pd.merge(test2, test1, on=["a"])._to_pandas()
res_pd = pandas.merge(test2._to_pandas(), test1._to_pandas(), on=["a"])
assert_frame_equal(res_md, res_pd) # AssertionError
```

### Issue Description

Modin doesn't preserve row order between partitions. 

### Expected Behavior

Same row order as in pandas

### Error Logs

<details>

```python-traceback

AssertionError: DataFrame.iloc[:, 0] (column name="a") are different

DataFrame.iloc[:, 0] (column name="a") values are different (50.0 %)
[index]: [0, 1, 2, 3]
[left]:  [1, 2, 1, 2]
[right]: [1, 1, 2, 2]

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by YarShev** [comment]
Related to https://github.com/modin-project/modin/issues/2246
