### ISSUE TITLE
Add trigger_execution to dataframe and series

### ISSUE THREAD

**Issue by Egor-Krivov** [modin-project/modin#5221]
Sometimes I need to "force" execution (trigger execution of all delayed computations).

It is useful for benchmarking. Currently benchmarks have to do something like [this](https://github.com/intel-ai/omniscripts/blob/master/utils/trigger_execution.py) to trigger computations. As you can see it is dependent on backend. It feels like this should be part of modin API to avoid clients to go so deep inside of the library.

**Comment by mvashishtha** [comment]
@Egor-Krivov yes, this is a feature we mentioned [here](https://github.com/modin-project/modin/pull/5020#pullrequestreview-1116775616) while writing the [benchmarking guide](https://modin.readthedocs.io/en/latest/usage_guide/benchmarking.html). That guide now says

> Sometimes, if you don’t have a natural end-point to your workflow, you can just call `repr` on the workflow’s final Modin objects.

but also points out that `repr` can be misleading, too.

**Comment by Egor-Krivov** [comment]
Thank you for the link. From the link I get that __repr__ is not completely reliable, since it will only block first and last rows. So the feature is still relevant for benchmarking.

> The problem is that the repr blocks only on getting the first few and the last few rows, but the slow execution is for row 5001, which Modin is computing asynchronously in the background even after repr finishes.
