### ISSUE TITLE
TEST: CI: CI broken because of 403 HTTPError for taxi CSV on modin-test s3

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5252]
I can't reproduce this failure locally. It appears in CI for at least two unrelated PRs: https://github.com/modin-project/modin/actions/runs/3527986556/jobs/5918024859

cc @noloerino

**Comment by RehanSD** [comment]
Hmm - I tried using `curl` as well as going to the link thats failing directly, and I'm getting an error that all access is forbidden. Seems that this bucket is one owned by us, so let me check around to see whats going on with it!

**Comment by mvashishtha** [comment]
Some questions:

- Who owns the modin-test bucket?
- Why does the test fail in CI but not locally? Do we use a local `taxi.csv` locally?
- Why can I do `aws s3 ls modn-test` but not `aws s3 ls modin-datasets`? The former gives me `An error occurred (AllAccessDisabled) when calling the ListObjectsV2 operation: All access to this object has been disabled`. Is that the root cause?

cc @modin-project/modin-contributors @modin-project/modin-core @gshimansky

**Comment by RehanSD** [comment]
@mvashishtha I'm able to repro the failure locally - I think maybe you have a cached copy of the dataset? I'm checking with @devin-petersohn to see who has ownership of the S3 buckets, since I think he may be the owner!

**Comment by mvashishtha** [comment]
@RehanSD yep, I can reproduce the error when I remove the taxi.csv at my modin root.

**Comment by RehanSD** [comment]
Seems like the bucket's access policy has changed, will reach out to see if they can be changed back or if we need to self host a bucket.
