### ISSUE TITLE
TEST: Restore the data that used to be in s3 bucket `modin-test` and use it in tests

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5259]
The AWS account that used to own modin-test/ is no longer active and we can't retrieve the data.

I was told that the data that used to be here was a subset of some NYC taxi dataset. Evidence like [this](https://github.com/modin-project/modin/blob/317bd75d0677c0ae1a400f7313953ee6638185ac/examples/quickstart.ipynb?short_path=98a86b2#L85), [this](https://github.com/modin-project/modin/blob/317bd75d0677c0ae1a400f7313953ee6638185ac/examples/tutorial/jupyter/execution/pandas_on_dask/test/test_notebooks.py#L105), and [this](https://github.com/modin-project/modin/blob/317bd75d0677c0ae1a400f7313953ee6638185ac/examples/tutorial/jupyter/execution/pandas_on_dask/test/test_notebooks.py#L119) suggest that we need to get the first N rows of the original dataset at `s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv` such that the resulting file is about 200 MB.

**Comment by RehanSD** [comment]
I've created a file about 200MB by getting the first 1933507 rows of the `yellow_tripdata_2015-01.parquet` file from https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page. The file can be found on the modin-development slack (too big to upload as a gist or on here). @gshimansky would you mind adding the file to the modin AWS S3 bucket?

**Comment by gshimansky** [comment]
There is a separate public bucket called `s3://yellow-taxi-dataset/` that contains a whole yellow taxi dataset (this is a 2.5 years of data that contain geopositions before collection of geo data was disabled). For historical reasons this dataset resides separately from `s3://modin-datasets`. Please take a look at it whether you can use files from `s3://yellow-taxi-dataset/` directly.

**Comment by RehanSD** [comment]
Hi @gshimansky! I took a look at that bucket, and while it does contain the yellow_tripdata_2015-01.csv, we don't actually want the whole file. I believe for testing purposes, we want a much reduced file thats only 200MB, while the file in that bucket is 1.8GiB, which is why that won't work for this purpose! The file I uploaded on slack is only the first 1.9M rows of the file in the bucket you sent, and is only 200 MB!

**Comment by gshimansky** [comment]
Ok I placed your file in this location `s3://modin-datasets/testing/yellow_tripdata_2015-01.csv`

**Comment by RehanSD** [comment]
Hi @gshimansky - would it be possible to get an http URL I could use to download the file?

**Comment by RehanSD** [comment]
Hi @gshimansky would it be possible to get the region that this bucket is located in? I need an http URL to download the file!

**Comment by gshimansky** [comment]
To use http URL it was necessary to "make public using ACLs", after doing this it is possible to download the file using link https://modin-datasets.s3.amazonaws.com/testing/yellow_tripdata_2015-01.csv
The bucket is located in us-west-2, but this information is not useful to download the file.

**Comment by YarShev** [comment]
Closed in https://github.com/modin-project/modin/pull/5401.
