### ISSUE TITLE
BUG: df.align raises  AttributeError: 'tuple' object has no attribute '_query_compiler'

### ISSUE THREAD

**Issue by arunjose696** [modin-project/modin#5272]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
cd modin\asv_bench\benchmarks


from utils import execute
from modin.pandas import  DataFrame

df1 = DataFrame([[1,2,3,4], [6,7,8,9]], columns=['D', 'B', 'E', 'A'], index=[1,2])
df2 = DataFrame([[10,20,30,40], [60,70,80,90], [600,700,800,900]], columns=['A', 'B', 'C', 'D'], index=[2,3,4])

execute(df1.align(df2, join='outer', axis=1)) #failure occurs here
```

### Issue Description

The execute function in modin.asv_bench.benchmarks.utils.py fails with the below exception when trying to run the execute function for align method, 

### Expected Behavior

The below function call should work without errors

```python
execute(df1.align(df2, join='outer', axis=1))
```

### Error Logs

<details>

```python-traceback


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\arunjose\OneDrive - Intel Corporation\Documents\modin\myForks\modin\asv_bench\benchmarks\utils\common.py", line 498, in execute
    partitions = df._query_compiler._modin_frame._partitions.flatten()
AttributeError: 'tuple' object has no attribute '_query_compiler'


```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 099730713e702de1db57ede5171a1c6cf9b88735
python           : 3.10.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

Modin dependencies
------------------
modin            : 0.15.2
ray              : None
dask             : 2021.10.0
distributed      : 2021.10.0
omniscidbe       : None

pandas dependencies
-------------------
pandas           : 1.4.3
numpy            : 1.23.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : 2022.10.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by RehanSD** [comment]
Hi @arunjose696! I've confirmed that I can reproduce this locally! Will you be handling this issue, or should we assign someone to take care of it?

**Comment by arunjose696** [comment]
@dchigarev Thanks, this makes sense I will go with the first option for now.
