### ISSUE TITLE
REFACTOR: Document that modin.pandas.base._validate_other can return a query compiler

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5282]
docstrings says we always return `BasePandasDataset`, but see [here](https://github.com/modin-project/modin/blob/b103735f05bc5cda2b19bf84f404e95b0bb894d5/modin/pandas/base.py#L249). This is a follow-up from [here](https://github.com/modin-project/modin/pull/5237#discussion_r1030469675).

**Comment by arunjose696** [comment]
Docstring was changed in #7253, it now mentions BaseQueryCompiler or Any
