### ISSUE TITLE
REFACTOR: Fix code scanning alert - Potentially uninitialized local variable in modin/pandas/groupby.py

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5295]
Tracking issue for:
- [ ] https://github.com/modin-project/modin/security/code-scanning/377

#5229 triggered this alert, but it applied even before python 3.6 support was added. Risky `order` use is [here](https://github.com/modin-project/modin/blob/da7bd1a14752895a38342b2faa3220a8db4cb7ff/modin/pandas/groupby.py#L584). `order` is supposed to be defined [here](https://github.com/modin-project/modin/blob/da7bd1a14752895a38342b2faa3220a8db4cb7ff/modin/pandas/groupby.py#L513).

**Comment by anmyachev** [comment]
Already fixed.
