### ISSUE TITLE
ImportError: libparquet.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KateShan** [modin-project/modin#530]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux version 2.6.32-504.23.4.el6.x86_64  (gcc version 4.4.7 20120313 (Red Hat 4.4.7-9) (GCC) )
- **Modin installed from (source or binary)**:
pip install modin
- **Modin version**: 
- **Python version**: Python 2.7.13 :: Continuum Analytics, Inc.

- **Exact command to reproduce**:

**Comment by devin-petersohn** [comment]
Hi @KateShan thanks for posting! Would you be able to tell me which command caused the issue?

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
