### ISSUE TITLE
ConnectionError: Operation timed out. when importing modin

### ISSUE THREAD

**Issue by FanNotFan** [modin-project/modin#531]
### System information
- **macOS Mojave 10.14.1 **:
- **Modin installed from source**:
- **Modin version 0.4.0:
- **Python version 3.7.2:
- **Exact command to reproduce**:

### Describe the problem
when i excute 'import modin.pandas as pd'
ConnectionError: Error 60 connecting to 10.184.194.75:46756. Operation timed out.

### Source code / logs---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/connection.py in connect(self)
    491         try:
--> 492             sock = self._connect()
    493         except socket.timeout:

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/connection.py in _connect(self)
    549         if err is not None:
--> 550             raise err
    551         raise socket.error("socket.getaddrinfo returned an empty list")

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/connection.py in _connect(self)
    537                 # connect
--> 538                 sock.connect(socket_address)
    539 

TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-1-d42df328a6c7> in <module>
----> 1 import modin.pandas

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/modin/pandas/__init__.py in <module>
    180 
    181 if execution_engine == "Ray":
--> 182     initialize_ray()
    183     num_cpus = ray.global_state.cluster_resources()["CPU"]
    184 elif execution_engine == "Dask":  # pragma: no cover

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/modin/pandas/__init__.py in initialize_ray()
    172             ignore_reinit_error=True,
    173             plasma_directory=plasma_directory,
--> 174             object_store_memory=object_store_memory,
    175         )
    176         # Register custom serializer for method objects to avoid warning message.

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/worker.py in init(redis_address, num_cpus, num_gpus, resources, object_store_memory, redis_max_memory, node_ip_address, object_id_seed, num_workers, local_mode, driver_mode, redirect_worker_output, redirect_output, ignore_reinit_error, num_redis_shards, redis_max_clients, redis_password, plasma_directory, huge_pages, include_webui, driver_id, configure_logging, logging_level, logging_format, plasma_store_socket_name, raylet_socket_name, temp_dir, _internal_config, use_raylet)
   1452         global _global_node
   1453         _global_node = ray.node.Node(
-> 1454             head=True, shutdown_at_exit=False, ray_params=ray_params)
   1455         address_info["redis_address"] = _global_node.redis_address
   1456         address_info[

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/node.py in __init__(self, ray_params, head, shutdown_at_exit)
     84         self._webui_url = None
     85 
---> 86         self.start_ray_processes()
     87 
     88         if shutdown_at_exit:

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/node.py in start_ray_processes(self)
    276         # If this is the head node, start the relevant head node processes.
    277         if self._redis_address is None:
--> 278             self.start_redis()
    279             self.start_monitor()
    280             self.start_raylet_monitor()

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/node.py in start_redis(self)
    128              redirect_worker_output=self._ray_params.redirect_worker_output,
    129              password=self._ray_params.redis_password,
--> 130              redis_max_memory=self._ray_params.redis_max_memory)
    131         assert PROCESS_TYPE_REDIS_SERVER not in self.all_processes
    132         self.all_processes[PROCESS_TYPE_REDIS_SERVER] = []

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/services.py in start_redis(node_ip_address, port, redis_shard_ports, num_redis_shards, redis_max_clients, redirect_output, redirect_worker_output, password, use_credis, redis_max_memory)
    393             # Below we use None to indicate no limit on the memory of the
    394             # primary Redis shard.
--> 395             redis_max_memory=None)
    396         processes.append(p)
    397     else:

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/services.py in _start_redis_instance(node_ip_address, port, redis_max_clients, num_retries, stdout_file, stderr_file, password, executable, modules, redis_max_memory)
    633         address(node_ip_address, port),
    634         node_ip_address, [stdout_file, stderr_file],
--> 635         password=password)
    636     return port, p
    637 

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/ray/services.py in record_log_files_in_redis(redis_address, node_ip_address, log_files, password)
    180             # address.
    181             log_file_list_key = "LOG_FILENAMES:{}".format(node_ip_address)
--> 182             redis_client.rpush(log_file_list_key, log_file.name)
    183 
    184 

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/client.py in rpush(self, name, *values)
   1664     def rpush(self, name, *values):
   1665         "Push ``values`` onto the tail of the list ``name``"
-> 1666         return self.execute_command('RPUSH', name, *values)
   1667 
   1668     def rpushx(self, name, value):

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/client.py in execute_command(self, *args, **options)
    770         pool = self.connection_pool
    771         command_name = args[0]
--> 772         connection = pool.get_connection(command_name, **options)
    773         try:
    774             connection.send_command(*args)

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/connection.py in get_connection(self, command_name, *keys, **options)
    992         try:
    993             # ensure this connection is connected to Redis
--> 994             connection.connect()
    995             # connections that the pool provides should be ready to send
    996             # a command. if not, the connection was either returned to the

~/anaconda3/envs/python3-7_interpreter_test_2019/lib/python3.7/site-packages/redis/connection.py in connect(self)
    495         except socket.error:
    496             e = sys.exc_info()[1]
--> 497             raise ConnectionError(self._error_message(e))
    498 
    499         self._sock = sock

ConnectionError: Error 60 connecting to 10.184.194.75:46756. Operation timed out.

**Comment by devin-petersohn** [comment]
Thanks for posting @FanNotFan! This looks like an issue with the redis Ray is using.

What is your redis version?

```python
import redis
print(redis.__version__)
```

It might be worth trying to update your redis version. `pip install -U redis`

cc @robertnishihara - have you seen this before?

**Comment by robertnishihara** [comment]
@FanNotFan, can you also check the logs under `/tmp/ray/session_*/logs/` and see if there is anything interesting, e.g., in the `redis*` logs?

**Comment by LuisBlanche** [comment]
Hello I seem to have the same issue 
`Successfully installed modin-0.7.2 pandas-1.0.1 ray-0.8.0`

Here is the content of `redis.out` in the logs, it tells it received a SIGTERM ..

`93257:C 23 Mar 2020 14:34:08.918 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
93257:C 23 Mar 2020 14:34:08.918 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=93257, just started
93257:C 23 Mar 2020 14:34:08.918 # Configuration loaded
93257:M 23 Mar 2020 14:34:08.923 # Server initialized
93257:signal-handler (1584970531) Received SIGTERM scheduling shutdown...
93257:M 23 Mar 2020 14:35:31.900 # User requested shutdown...
93257:M 23 Mar 2020 14:35:31.900 # Redis is now ready to exit, bye bye...`

**Comment by devin-petersohn** [comment]
Thanks for the update @LuisBlanche, since this looks like a VPN issue I'm going to go ahead and close the issue. I updated the title to make it easier for others looking for the solution since there may be many people using a VPN these days.
