### ISSUE TITLE
Fix code scanning alert - Explicit returns mixed with implicit (fall through) returns

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#5337]
Tracking issue for:
- [ ] https://github.com/modin-project/modin/security/code-scanning/397

For example (from the link above):
![image](https://user-images.githubusercontent.com/45976948/205467223-20d5987e-f0fd-49c3-a249-f966858ae427.png)

**Comment by pyrito** [comment]
@anmyachev I don't think that alert is visible to all contributors. Could you post a screenshot for some more context?

**Comment by anmyachev** [comment]
> @anmyachev I don't think that alert is visible to all contributors. Could you post a screenshot for some more context?

posted

**Comment by anmyachev** [comment]
no one is interested
