### ISSUE TITLE
pd.read_csv throws error when used with parse_dates and index_col together

### ISSUE THREAD

**Issue by eralmansouri** [modin-project/modin#537]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Modin installed from (source or binary)**: pip3 install modin
- **Modin version**: 0.4.0
- **Python version**: 3.6.5

### Describe the problem
As the title says, ValueError is thrown when using pd.read_csv with parse_dates and index_col together. 

### Source code / logs

This is the line that throws an error:

`pd.read_csv(cb_filepath, names=['timestamp', 'symbol', 'high', 'low', 'open', 'close', 'spread', 'volume'], header=0, index_col=0, parse_dates=['timestamp'], encoding='utf-8')`

The csv file is formed like this:

> timestamp,symbol,high,low,open,close,spread,volume
> 2010-04-01 00:00:00,USD/JPY,93.52600,93.36100,93.51800,93.38200,0.00500,3049
> 2010-04-01 00:30:00,USD/JPY,93.47500,93.35200,93.38500,93.39100,0.00600,2251
> 2010-04-01 01:00:00,USD/JPY,93.42100,93.32600,93.39100,93.38400,0.00600,1577

Error:

> File "/home/censored/tensorflow/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
>     self._engine = CParserWrapper(self.f, **self.options)
>   File "/home/censored/tensorflow/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1904, in __init__
>     self._set_noconvert_columns()
>   File "/home/censored/tensorflow/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1973, in _set_noconvert_columns
>     _set(val)
>   File "/home/censored/tensorflow/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1963, in _set
>     x = names.index(x)
> ValueError: 'timestamp' is not in list

[error.log](https://github.com/modin-project/modin/files/3048366/error.log)

**Comment by devin-petersohn** [comment]
Thanks for posting @eralmansouri! 

This looks like an issue with the way we are using `BytesIO` as a way to parallel read the file. This should be a pretty straightforward fix, we've had to use something similar for the Apache Arrow reader in #502. Great find, thanks!
