### ISSUE TITLE
[ASV] port stack, unstack, replace and  groups benchmarks from pandas github

### ISSUE THREAD

**Issue by arunjose696** [modin-project/modin#5378]
Have to add ASV benchmarks related which does the following actions
1) perform stack and unstack on dataframe.
2) Replace function on a dataframe.
3) Get groups returned by groupby.

**Comment by mvashishtha** [comment]
@arunjose696 thank you for filing this issue. Could you please add priorities to all new Modin issues? You can ask someone from modin-core if you need help assigning a priority. I think these benchmarking issues can be P2.
