### ISSUE TITLE
BUG: groupby more than one pd.Grouper would get error

### ISSUE THREAD

**Issue by eromoe** [modin-project/modin#5409]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2, 2, 3], "b": [3, 4, 5, 6], "c": [2, 2, 3, 4]})
grp_obj = df.groupby([pd.Grouper("a"), pd.Grouper("b")]) # KeyError
```

### Issue Description

Inconsistent behavious.

### Expected Behavior

Same

### Error Logs

<details>

```python-traceback

Traceback (most recent call last):
  File "t2.py", line 5, in <module>
    grp_obj = df.groupby([pd.Grouper("a"), pd.Grouper("b")])
  File "/localdisk/dchigare/repos/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/localdisk/dchigare/repos/modin/modin/pandas/dataframe.py", line 537, in groupby
    raise KeyError(next(x for x in names if x not in self))
KeyError: Grouper(key='a', axis=0, sort=False, dropna=True)

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 7f801adce1b204469bdf95fae82b110d6cf59299
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

Modin dependencies
------------------
modin            : 0.17.1
ray              : 2.0.0
dask             : 2022.01.1
distributed      : 2022.01.1
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.2
numpy            : 1.23.1
pytz             : 2021.1
dateutil         : 2.8.1
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : 0.4.1
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 2022.11.0
fsspec           : 2021.07.0
gcsfs            : None
matplotlib       : 3.5.3
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.07.0
scipy            : 1.9.3
snappy           : 
sqlalchemy       : 1.4.7
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
tzdata           : None
</details>

**Comment by dchigarev** [comment]
Thank you for your report!

I've been able to reproduce the problem. It seems that modin currently doesn't support Groupers in groupby at all. I think this shouldn't be a hard thing to support so I believe we'll fix it in a near future.

**Comment by anmyachev** [comment]
This producer works on the [master](https://github.com/modin-project/modin/commit/47b7cae3b6a60fbef33fa9e8319087bd539fb66f) branch (however defaults to pandas).

To optimize this case, I think we need to create a separate issue.
