### ISSUE TITLE
How to prevent groupby.agg(list) produce columns `__reduced__` ?

### ISSUE THREAD

**Issue by eromoe** [modin-project/modin#5410]
I have to remove those `__reduced__`  in case

```
df = df[[c for c in df.columns if c !='__reduced__']]
```

**Comment by dchigarev** [comment]
Hi @eromoe, thanks for your report.

Could you please elaborate on your use case of `groupby.agg(list)`? I've tried a couple of common scenarios for an aggregation specified by a list and didn't get any `__reduced__` columns in the result:

```python
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2, 2], "b": [3, 4, 5]})
print(df.groupby("a").agg(["sum", "mean"]))

series = pd.Series([1, 2, 3])
print(series.groupby([1, 2, 2]).agg(["sum", "mean"]))
```
Output:
```
    b
  sum mean
a
1   3  3.0
2   9  4.5

   sum  mean
1    1   1.0
2    5   2.5

```

**Comment by anmyachev** [comment]
@eromoe feel free to reopen if needed
