### ISSUE TITLE
Add a NumPy API Layer to Modin

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#5423]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?
It would be nice to be able to use the NumPy API to manipulate Modin objects, i.e. have a `modin.numpy` package.

**Comment by jbrockmendel** [comment]
I'm confused by #5422.  Is the idea a) to be able to call `numpy.whatever(modin_object)` or b) to make `modin_object.to_numpy()` give back a distributed numpy-like object?

**Comment by RehanSD** [comment]
The idea is b) - we want to create a distributed numpy object - just like our distributed pandas object. So modin.numpy.array() is a distributed object that has the same behaviors + API's as numpy.array()!

**Comment by jbrockmendel** [comment]
Doing that (well) seems like a really big increase in scope for modin.
