### ISSUE TITLE
Implement groupby aggregation when functions specified by a list

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5428]
The goal is to support cases like:
```python
df.groupby("a").agg(["sum", "mean"])
```
Currently, we're defaulting to pandas in this case:
https://github.com/modin-project/modin/blob/ba7ab8eb80dd6412f275ffff806db37ff7ebdb01/modin/pandas/groupby.py#L560-L565

**Comment by YarShev** [comment]
@dchigarev, @vnlitvinov, is this issue covered by #5996?

**Comment by vnlitvinov** [comment]
Fixed by #5996 (I wonder why Github didn't close this issue, I certainly said so in that PR description...).
