### ISSUE TITLE
BUG: Plotly choropleth incompatible with Modin

### ISSUE THREAD

**Issue by labanyamukhopadhyay** [modin-project/modin#5447]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import plotly.express as px
from urllib.request import urlopen
import json

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                   dtype={"fips": str})

fig = px.choropleth(df, geojson=counties, locations='fips', color='unemp',
                           color_continuous_scale="Viridis",
                           range_color=(0, 12),
                           scope="usa",
                           labels={'unemp':'unemployment rate'}
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()
```

### Issue Description

Plotly choropleth parameters such as `locations` or `color` does not accept either column name or index.  

### Expected Behavior

<img width="999" alt="Screen Shot 2022-12-15 at 1 19 29 PM" src="https://user-images.githubusercontent.com/17665008/207969323-f4fd7dce-0a22-45a5-93a5-a6f188bde846.png">

### Error Logs

<details>

```python-traceback

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[32], line 3
      1 import plotly.express as px
----> 3 fig = px.choropleth(df, geojson=counties, locations='fips', color='unemp',
      4                            color_continuous_scale="Viridis",
      5                            range_color=(0, 12),
      6                            scope="usa",
      7                            labels={'unemp':'unemployment rate'}
      8                           )
      9 fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
     10 fig.show()

File ~/Desktop/ponder-integ/lib/python3.9/site-packages/plotly/express/_chart_types.py:1091, in choropleth(data_frame, lat, lon, locations, locationmode, geojson, featureidkey, color, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, hover_name, hover_data, custom_data, animation_frame, animation_group, category_orders, labels, color_discrete_sequence, color_discrete_map, color_continuous_scale, range_color, color_continuous_midpoint, projection, scope, center, fitbounds, basemap_visible, title, template, width, height)
   1051 def choropleth(
   1052     data_frame=None,
   1053     lat=None,
   (...)
   1085     height=None,
   1086 ) -> go.Figure:
   1087     """
   1088     In a choropleth map, each row of `data_frame` is represented by a
   1089     colored region mark on a map.
   1090     """
-> 1091     return make_figure(
   1092         args=locals(),
   1093         constructor=go.Choropleth,
   1094         trace_patch=dict(locationmode=locationmode),
   1095     )

File ~/Desktop/ponder-integ/lib/python3.9/site-packages/plotly/express/_core.py:1990, in make_figure(args, constructor, trace_patch, layout_patch)
   1987 layout_patch = layout_patch or {}
   1988 apply_default_cascade(args)
-> 1990 args = build_dataframe(args, constructor)
   1991 if constructor in [go.Treemap, go.Sunburst, go.Icicle] and args["path"] is not None:
   1992     args = process_dataframe_hierarchy(args)

File ~/Desktop/ponder-integ/lib/python3.9/site-packages/plotly/express/_core.py:1405, in build_dataframe(args, constructor)
   1402     args["color"] = None
   1403 # now that things have been prepped, we do the systematic rewriting of `args`
-> 1405 df_output, wide_id_vars = process_args_into_dataframe(
   1406     args, wide_mode, var_name, value_name
   1407 )
   1409 # now that `df_output` exists and `args` contains only references, we complete
   1410 # the special-case and wide-mode handling by further rewriting args and/or mutating
   1411 # df_output
   1413 count_name = _escape_col_name(df_output, "count", [var_name, value_name])

File ~/Desktop/ponder-integ/lib/python3.9/site-packages/plotly/express/_core.py:1207, in process_args_into_dataframe(args, wide_mode, var_name, value_name)
   1205         if argument == "index":
   1206             err_msg += "\n To use the index, pass it in directly as `df.index`."
-> 1207         raise ValueError(err_msg)
   1208 elif length and len(df_input[argument]) != length:
   1209     raise ValueError(
   1210         "All arguments should have the same length. "
   1211         "The length of column argument `df[%s]` is %d, whereas the "
   (...)
   1218         )
   1219     )

ValueError: Value of 'locations' is not the name of a column in 'data_frame'. Expected one of [0, 1] but received: fips

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4114183f84d3d152126510655db5698fd4ea1071
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.18.0+3.g4114183f
ray              : 2.0.1
dask             : 2022.11.1
distributed      : 2022.11.1
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.2
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.11.0
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by gpaolopedrazza** [comment]
I am also stuck because of that. I found that the issue starts in plotly there 
https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L1306
because I do not pass an instance of pd.DataFrame but of modin.pd.DataFrame.
The fresh pd.DataFrame instance has pandas.RangeIndex as type of the columns argument, while the old modin.pd.DataFrame instance which got replaced there had panda.Index instead. According with pandas documentation [1], index will default to RangeIndex if no indexing information part of input data and no index provided. So that could be exactly what modin is missing, but that is just of guess of mine.
[1] https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

**Comment by mvashishtha** [comment]
This is still not working on Modin because there's some bug in the interchange implementation in Modin:

```python
import modin.pandas as pd
import plotly.express as px
from urllib.request import urlopen
import json

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                   dtype={"fips": str})

fig = px.choropleth(df, geojson=counties, locations='fips', color='unemp',
                           color_continuous_scale="Viridis",
                           range_color=(0, 12),
                           scope="usa",
                           labels={'unemp':'unemployment rate'}
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()
```

all the values are blank because modin doesn't convert correctly to interchange:

```python
import pandas

print(pandas.api.interchange.from_dataframe(df.__dataframe__()))
```

Column `fips` becomes `NaN` when it should have numbers.

**Comment by mvashishtha** [comment]
> all the values are blank because modin doesn't convert correctly to interchange:

I filed #6518 for that

**Comment by anmyachev** [comment]
Looks like the reproducer works with Modin after https://github.com/modin-project/modin/pull/6523.

@mvashishtha please double check.

**Comment by labanyamukhopadhyay** [comment]
Yes this works now with the fix thank you @anmyachev !

**Comment by anmyachev** [comment]
@labanyamukhopadhyay thanks for checking!
