### ISSUE TITLE
[BUG] AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by cosmicBboy** [modin-project/modin#5466]
**Context:** I'm the maintainer of [pandera](https://github.com/unionai-oss/pandera) and we're disabling modin-ray CI tests due to the following error:

```
FAILED tests/modin/test_schemas_on_modin.py::test_init_modin_dataframe_errors[ray-invalid_data2] - ray.exceptions.RayTaskError: ray::deploy_ray_func() (pid=25258, ip=10.1.0.56)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: module 'pandas' has no attribute 'core'
traceback: Traceback (most recent call last):
  File "/usr/share/miniconda/envs/pandera-dev/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py", line 698, in subimport
    __import__(name)
  File "/usr/share/miniconda/envs/pandera-dev/lib/python3.7/site-packages/pandas/__init__.py", line 179, in <module>
    import pandas.testing
  File "/usr/share/miniconda/envs/pandera-dev/lib/python3.7/site-packages/pandas/testing.py", line 6, in <module>
    from pandas._testing import (
  File "/usr/share/miniconda/envs/pandera-dev/lib/python3.7/site-packages/pandas/_testing/__init__.py", line 948, in <module>
    cython_table = pd.core.common._cython_table.items()
AttributeError: module 'pandas' has no attribute 'core'
```

(See CI run for an example: https://github.com/unionai-oss/pandera/actions/runs/3720647228/jobs/6310259805#logs)

**Versions:**
```
modin                     0.12.1                   pypi_0    pypi
pandas                    1.3.5            py37he8f5f7f_0    conda-forge
ray                       2.2.0                    pypi_0    pypi
```

This error only comes up irregularly on python3.7 + ubuntu and 3.10 + windows, but I'm not able to reliably reproduce it locally.

As a workaround I'm disabling the modin-ray pandera testing for these python version-OS combinations.

**Comment by Garra1980** [comment]
Such an old versions of Python and Modin. Is it on purpose?

**Comment by YarShev** [comment]
It seems to me that the issue is related to #4564. We fixed (worked around) the problem in #4603 and the releases starting 0.16.0 should work fine. @cosmicBboy, is it possible for you to upgrade the Modin version? Also, as I see you initialize Ray in pandera by yourself. You should add an additional parameter for ray.init() to make Modin on Ray work.

```python
ray.init(
    <your_arguments>,
    runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}}
)
```

**Comment by mvashishtha** [comment]
@cosmicBboy do we need to do anything else to address this issue? Were you able to use a newer version of Modin?

**Comment by cosmicBboy** [comment]
hi @mvashishtha I was able to address the issue by disabling CI tests for older versions of pandas/modin https://github.com/unionai-oss/pandera/pull/1052/files
