### ISSUE TITLE
BUG: `read_parquet` arguments `filters` didn't take effect

### ISSUE THREAD

**Issue by sylcjl** [modin-project/modin#5509]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as mpd
import pandas as pd

df = pd.DataFrame([{"col_a": 1, "col_b": "a"}, 
                   {"col_a": 2, "col_b": "b"}, 
                   {"col_a": 3, "col_b": "c"}])
df.to_parquet("test.parquet")

pdf = pd.read_parquet("test.parquet", filters=[[("col_a", "==", 1)]], columns=["col_b"], engine="pyarrow")
print(pdf.shape)  # (1, 1) <- expected result

mdf = mpd.read_parquet("test.parquet", filters=[[("col_a", "==", 1)]], columns=["col_b"], engine="pyarrow")
print(mdf.shape)  # (3, 1)
```

### Issue Description

Hi Modin team, I am facing the problem when using `modin.pandas.read_parquet` with argument: filters. Example above shows `read_parquet` with `pandas` filter that return result was what i expected but `modin.pandas.read_parquet` do not. How can i fix this issue? Is there any suggestion for this? Thanks a lot!

### Expected Behavior

`modin.pandas.read_parquet` returns exactly same what pandas do.

### Error Logs

<details>

```python-traceback

No error log in this case

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : ba7ab8eb80dd6412f275ffff806db37ff7ebdb01
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.el7.x86_64
Version          : #1 SMP Tue Aug 18 14:50:17 EDT 2020
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.18.0
ray              : 2.0.1
dask             : 2022.12.1
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.2
numpy            : 1.23.3
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : 2022.11.0
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.5.0
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by vnlitvinov** [comment]
Hi @sylcjl, 

I can see this reproducer showing the error on both Dask and Ray, but not in "debug" `PandasOnPython` mode. Needs further investigation.

@pyrito could you please take a look? IIRC it was you who last touched parquet-related code...

**Comment by pyrito** [comment]
@vnlitvinov yup, I just took a look. It looks like we just straight up don't support the filters kwargs since we read based on row group chunks. We could add support to handle this naively now and then think of a smart way to filter out rows in parallel. I can't think of a straightforward way off the top of my head.
