### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by do-me** [modin-project/modin#5518]
Is support for Python 3.11 planned?

**Comment by pyrito** [comment]
It should be supported in the near future. cc: @modin-project/modin-core

**Comment by nekicier** [comment]
Hi,
It seems Modin is not available for python > 3.11.0, please could you confirm ?
Here is the output when I try to install it (os=linux, conda=23.7.0, python=3.11.4)

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
  - modin-dask -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
```

Thanks

**Comment by anmyachev** [comment]
Hi @nekicier, python 3.11 is still not supported for conda.

I suppose in the nearest releases we will try to add conda packages for python 3.11. For now you could try to install modin via pip: `pip install modin[dask]`.

**Comment by anmyachev** [comment]
Modin 0.25.0 is the first release that has conda packages for python 3.11
