### ISSUE TITLE
Tensorflow can't use if i install modin

### ISSUE THREAD

**Issue by 514123661** [modin-project/modin#558]
I have installed the modin by using 'pip install modin'. I notice that it uninstall numpy 1.16.  And then, I attempted 'import tensorflow', but I can't import this, it reported me this was error. 

Reported: 
ImportError: No module named _multiarray_umath
Traceback (most recent call last):
  File "_pydevd_bundle/pydevd_cython_darwin_27_64.pyx", line 689, in _pydevd_bundle.pydevd_cython_darwin_27_64.PyDBFrame.trace_dispatch
ImportError: numpy.core.multiarray failed to import
ImportError: No module named _multiarray_umath
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-04-16 20:05:24.499817: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by 514123661** [comment]
it seems that 'tensorflow' can need 1.16 numpy

**Comment by devin-petersohn** [comment]
Hi @514123661, thanks for posting! 

This is fixed in the master branch ([link](https://github.com/modin-project/modin/blob/master/setup.py#L18)) and will be included in the next release. If you'd like to try it now, please follow the instructions in the documentation for installation from the master: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch. Note that we are still in the testing phase of the release process, so please let us know if you run into any new issues!

**Comment by 514123661** [comment]
I got a new error about install master branch. I used 'pip install git+https://github.com/modin-project/modin' in my terminal, but i get a error report:  

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/pip-req-build-BUwUyB/setup.py", line 7, in <module>
        with open("README.md", "r", encoding="utf8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function

My computer is macbook pro, the system is macOS Sierra 10.12.6. And my python is 2.7

**Comment by devin-petersohn** [comment]
Sorry, installing from the master branch is only supported on Python 3. I should add this to the documentation. The library is built for Python 3 and we run some scripts to be compatible with Python2. You can fork/clone the repo and build that way by running the scripts yourself if you'd like. I'm happy to walk you through that process.

We are planning to release on/around April 24 if you would rather wait.

**Comment by 514123661** [comment]
It does not matter. I would like to wait this excellent project.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
