### ISSUE TITLE
read_fwf does not set column names properly

### ISSUE THREAD

**Issue by slomeks** [modin-project/modin#560]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **Modin installed from (source or binary)**:
pip
- **Modin version**:
0.4.0
- **Python version**:
3.6.7
- **Exact command to reproduce**:
`p_data = pd.read_fwf(data_file, colspecs=column_specs, names=column_names, na_values=nan_values, index_col=['stationID', 'year'])`

### Describe the problem
While using pandas read_fwf, column names are properly set as defined in column_names and index properly set. While changing to use modin version, column names are ignored and taken from first row of data.
Used data from [here](https://www1.ncdc.noaa.gov/pub/data/ghcn/v4/ghcnm.tavg.latest.qcu.tar.gz) (unpacked)

### Source code / logs
```
import pandas as pd
# import modin.pandas as pd

data_file = './data/ghcnm.v4.0.0.20190413/ghcnm.tavg.v4.0.0.20190413.qcu.dat'

column_specs = [(0,11), (11,15), (19,24), (27,32), (35,40),  (43,48), (51,56),
                (59,64), (67,72), (75,80), (83,88), (91,96), (99,104), (107,112)]

column_names = ['stationID', 'year', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

nan_values=['-9999']

p_data = pd.read_fwf(data_file, colspecs=column_specs, names=column_names, 
                   na_values=nan_values, index_col=['stationID', 'year'])

p_data.head() #gives different output for pandas and modin
```

**Comment by devin-petersohn** [comment]
Hi @slomeks, thanks for posting!

I was able to reproduce your error. Even though our `fwf` reader is not parallelized and defaults to pandas, we are still dropping the metadata and some of the `kwargs`. It's a quick fix, I can PR the fix tonight.
