### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" when using pd.concat 

### ISSUE THREAD

**Issue by Rockgecko** [modin-project/modin#562]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.4.0
- **Python version**: 3.7
- **Exact command to reproduce**: pd.concat([test_data, row])

### Describe the problem
Using pd.concat to assemble a dataframe from individual rows causes modin to throw the following error. 

### Source code / logs
```
import modin.pandas as pd

test_data = pd.DataFrame()
row = pd.Series({0:"a", 1:"b"})
pd.concat([test_data, row])
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-20-1558f0fda4ff> in <module>
>       3 test_data = pd.DataFrame()
>       4 row = pd.Series({0:"a", 1:"b"})
> ----> 5 pd.concat([test_data, row])
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/pandas/concat.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, sort, copy)
>     116         verify_integrity=False,
>     117         copy=True,
> --> 118         sort=False,
>     119     )
>     120     result_df = DataFrame(query_compiler=new_query_compiler)
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py in concat(self, axis, other, **kwargs)
>     310             Concatenated objects.
>     311         """
> --> 312         return self._append_list_of_managers(other, axis, **kwargs)
>     313 
>     314     def _append_list_of_managers(self, others, axis, **kwargs):
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py in _append_list_of_managers(self, others, axis, **kwargs)
>     323         ignore_index = kwargs.get("ignore_index", False)
>     324         new_self, to_append, joined_axis = self.copartition(
> --> 325             axis ^ 1, others, join, sort, force_repartition=True
>     326         )
>     327         new_data = new_self.concat(axis, to_append)
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py in copartition(self, axis, other, how_to_join, sort, force_repartition)
>     447 
>     448             reindexed_self, reindexed_other = reindexed_self.copartition_datasets(
> --> 449                 axis, other[i].data, reindex_left, reindex_right
>     450             )
>     451             reindexed_other_list.append(reindexed_other)
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/engines/base/block_partitions.py in copartition_datasets(self, axis, other, left_func, right_func)
>     273                 axis,
>     274                 right_func,
> --> 275                 new_self.block_lengths if axis == 0 else new_self.block_widths,
>     276             )
>     277         return new_self, new_other
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/engines/base/block_partitions.py in manual_shuffle(self, axis, shuffle_func, lengths)
>    1035             partitions = self.column_partitions
>    1036         func = self.preprocess_func(shuffle_func)
> -> 1037         result = np.array([part.shuffle(func, lengths) for part in partitions])
>    1038         return self.__constructor__(result) if axis else self.__constructor__(result.T)
>    1039 
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/engines/base/block_partitions.py in <listcomp>(.0)
>    1035             partitions = self.column_partitions
>    1036         func = self.preprocess_func(shuffle_func)
> -> 1037         result = np.array([part.shuffle(func, lengths) for part in partitions])
>    1038         return self.__constructor__(result) if axis else self.__constructor__(result.T)
>    1039 
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/engines/base/axis_partition.py in shuffle(self, func, lengths, **kwargs)
>     159         args = [self.axis, func, num_splits, kwargs, False]
>     160         args.extend(self.list_of_blocks)
> --> 161         return self._wrap_partitions(self.deploy_axis_func(*args))
>     162 
>     163     @classmethod
> 
> /tmp/res-933/lib/python3.7/site-packages/modin/engines/base/axis_partition.py in _wrap_partitions(self, partitions)
>      80             return [self.partition_type(partitions)]
>      81         else:
> ---> 82             return [self.partition_type(obj) for obj in partitions]
>      83 
>      84 
> 
> TypeError: 'NoneType' object is not iterable

**Comment by devin-petersohn** [comment]
Hi @Rockgecko, thanks for posting! This is a bug and should get fixed before the next release.

This bug was introduced in #522 when we added support for `Series`. The `TypeError` given here shouldn't be possible because the `partitions` object in `axis_partition.py` should never be `None`.

Great find, thanks!
