### ISSUE TITLE
Synchronize `apply_full_axis` and `broadcast_apply_full_axis` parameters

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#5620]
The following parameters make sense for both functions:
* apply_indices
* enumerate_partitions

After these changes, only one difference should remain: `other` parameter.

**Comment by shalearkane** [comment]
Could you assign this issue to me?

**Comment by YarShev** [comment]
@shalearkane, assigned this issue to you. Will be happy to see your contribution.
