### ISSUE TITLE
Can't get modin working with out-of-memory data

### ISSUE THREAD

**Issue by apapikyan** [modin-project/modin#5638]
OS: Ubuntu 22.04.1 LTS
Total RAM: 16 GB
Python: 3.10.6
Modin version: 0.18.0
Ray version: 2.2.0

Trying to get the example from [Modin website](https://modin.readthedocs.io/en/stable/getting_started/why_modin/out_of_core.html#operating-on-out-of-memory-data-with-modin) working but the kernel is always restarting and my laptop is frozen for several seconds (seems to be memory issue).

Here is my code:
```
import modin.pandas as pd
import numpy as np
import os
import ray

os.environ['MODIN_MEMORY']='6000000000'

df = pd.concat([pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))) for _ in range(5)]) # 5x2GB frames -- Working!
df.info()
```
Any idea what I am doing wrong ? 
Please let me know if you need additional information

**Comment by YarShev** [comment]
Hi, @apapikyan. I tried running your script on my laptop with 24 GB RAM and it works well. When specifying `MODIN_MEMORY` you are saying how much memory (in bytes) give to an execution engine. If we consider Ray, then using `os.environ['MODIN_MEMORY']='6000000000'` (6 GB) tells Ray the amount of memory to start the Plasma object store with. Since the capacity of the Plasma is 6 GB and each frame is 2 GB (larger a bit) in your case, then creation of 3rd, 4th, 5th frames should make Ray spill data to disk. That is exactly what I am seeing.

```python
import modin.pandas as pd
import numpy as np
import os

os.environ['MODIN_MEMORY']='6000000000'
df = pd.concat([pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))) for _ in range(5)])
# (raylet) Spilled 6112 MiB, 194 objects, write throughput 607 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
# (raylet) Spilled 6336 MiB, 201 objects, write throughput 588 MiB/s.
# (raylet) Spilled 8192 MiB, 259 objects, write throughput 591 MiB/s.
df.info()
# <class 'modin.pandas.dataframe.DataFrame'>
# Int64Index: 5242880 entries, 0 to 1048575
# Columns: 256 entries, 0 to 255
# dtypes: int64(256)
# memory usage: 10.0 GB
```

I wonder what messages (outputs) do you see? And which exact line makes your laptop froze?

**Comment by apapikyan** [comment]
Hello @YarShev. Thanks for your reply. 
It fails on creation of the data frame or maybe on concatenation.
I am adding the screenshot bellow.   

Btw, if I don't specify the modin memory size it starts complaining on /dev/shm size.
```UserWarning: The size of /dev/shm is too small (7825764352 bytes). The required size at least half of RAM (8197564416 bytes)```
So, that's the reason I have to set ['MODIN_MEMORY']='6000000000'


![Screenshot from 2023-02-13 17-09-28](https://user-images.githubusercontent.com/4134169/218467355-45ef2263-db68-49ce-a882-ff203a0ff453.png)

**Comment by YarShev** [comment]
Hi @apapikyan, sorry for delayed response, was a little busy. I was able to run the script in jupyter notebook both with python 3.8 and python 3.10. The script worked well. Although I got some new warnings with python 3.10 from Ray.

```python
(raylet) miniconda3/envs/modin-py310/lib/python3.10/site-packages/ray/dashboard/agent.py:51: DeprecationWarning: There is no current event loop
(raylet)   aiogrpc.init_grpc_aio()

(raylet) [2023-03-06 16:30:45,287 E 4589 4589] (raylet) node_manager.cc:3040: 3 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: 5f58db8d62a630e368357f16f6d6f9920862c4e4353dca4ec0a09202, IP: 172.26.54.29) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.26.54.29`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
```

Would you be able to run the script with python 3.8 to see if the issue persists?

**Comment by YarShev** [comment]
It is worth mentioning that I even increased the number of dfs to 10 and the script worked.

**Comment by YarShev** [comment]
@apapikyan, meanwhile, could you also run the following code snippet, which doesn't involve Modin usage, to see if you see a problem with it?

```python
import pandas as pd
import numpy as np
import ray

ray.init(object_store_memory=6000000000)

refs = [ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8)))) for _ in range(5)]

@ray.remote
def memory_usage_partial(df):
    series = df.memory_usage()
    return pd.DataFrame(series).T

@ray.remote
def memory_usage_full(*dfs):
    df = pd.concat([df for df in dfs], axis=0)
    return df.memory_usage(index=False)

refs2 = [memory_usage_partial.remote(ref) for ref in refs]
ref3 = memory_usage_full.remote(*refs2)
print(ray.get(ref3))
```

**Comment by apapikyan** [comment]
Hey @YarShev , suddenly it started to work. Maybe some of the packages are updated.
I can see a lot of warnings and errors but at least can see the dataframe created and it's info.
Please see attached screenshots.
I am still on python 3.10 

![Screenshot from 2023-03-06 22-03-48](https://user-images.githubusercontent.com/4134169/223193799-9dc9b280-94c6-4b4b-bff8-f38e4209765d.png)
![Screenshot from 2023-03-06 22-04-06](https://user-images.githubusercontent.com/4134169/223193821-f5e22a6c-c4b8-47c1-9e13-e3603580f5cb.png)

**Comment by YarShev** [comment]
@apapikyan, some warnings are the same that I see but I haven't come across the `ImportError`(s). Can you try to run the script with python 3.8 or 3.9?

**Comment by apapikyan** [comment]
Not working on python 3.8. Seems to be out of memory again.
![Screenshot from 2023-03-07 17-24-31](https://user-images.githubusercontent.com/4134169/223435042-0853d40c-9d27-499f-b9c4-68f14aace183.png)

**Comment by apapikyan** [comment]
@YarShev the code you have provided just crashed and closed my pycharm :)

**Comment by YarShev** [comment]
I believe Ray is not able to handle the example from docs on your machine because it doesn't have enough resources. I don't think we can do something on our side to resolve the issue. We just need to make up an example without Modin and submit it to Ray in hope they can do something. Is it possible for you to use other machine?
