### ISSUE TITLE
BUG: HDK: Escape character is handled by read_csv() differently from Pandas

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#5649]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals
from pandas._testing import ensure_clean

with ensure_clean(".csv") as fname:
    with open(fname, "w") as f:
        f.write('A\n"testX""Xtest"\n')
    kwargs = {
        "filepath_or_buffer": fname,
        "escapechar": "X",
    }
    pdf = pandas.read_csv(**kwargs)
    mdf = pd.read_csv(**kwargs)
    df_equals(pdf, mdf)
```

### Issue Description

The escape character is handled differently:
```python-traceback
DataFrame.iloc[:, 0] (column name="A") values are different (100.0 %)
[index]: [0]
[left]:  [test"Xtest"]
[right]: [test"test"]
```

### Expected Behavior

I'm not sure which behavior is correct since pandas documentation is unclear:

```
escapecharstr (length 1), optional
One-character string used to escape other characters.
```

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
