### ISSUE TITLE
[QUESTION] Modin only supports unidist on MPI for now ?

### ISSUE THREAD

**Issue by raphaelauv** [modin-project/modin#5671]
Hello,

is there a roadmap or some blocking points on supporting other unidist backends ( I'm mostly thinking about multiprocessing ) ?

Thanks

```python
import os

os.environ["MODIN_ENGINE"] = "unidist"
os.environ["UNIDIST_BACKEND"] = "multiprocessing"

import modin.pandas as pd

test_df = pd.DataFrame({
    'col1': [['ad_1', 'ad_2'], ['ad_3']],
})

if __name__ == '__main__':
    pass

```

**Comment by YarShev** [comment]
Hi @raphaelauv, thanks for posting this. Yes, currently, Modin only supports MPI backend of unidist but our plan is to support every backend of unidist in Modin to have the unified API for every single engine (MPI, Ray, Dask, Python Multiprocessing, sequential python) in future. My thinking was that we would be gradually supporting each unidist backend in Modin in the following sequence: MPI, Ray, Dask, Python Multiprocessing and sequential python. The thing that Python Multiprocessing is among the latest in the list is that it is not stable enough (not fully functional for Modin, in other words) and not that performant as MPI, Ray and Dask for now. Do you think we should prioritize Python Multiprocessing to get it supported in Modin right after MPI?

**Comment by YarShev** [comment]
It is also worth noticing that currently our efforts are mainly focused on MPI backend to get it as performant as possible.

**Comment by YarShev** [comment]
The question is answered. Feel free to reopen if needed.
