### ISSUE TITLE
BUG: RuntimeError: ERR_DIV_BY_ZERO is thrown on MOD operation

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#5812]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas
import modin.pandas as pd

df1 = pandas.Series([1])
df2 = pandas.Series([0])
print(df1 / df2)  # -> inf
print(df1 % df2)  # -> NaN
print(df1 / 0)  # -> inf
print(df1 % 0)  # -> NaN
print(df2 / 0)  # -> NaN
print(df2 % 0)  # -> NaN

df1 = pd.Series([1])
df2 = pd.Series([0])
print(df1 / df2)  # -> inf
print(df1 % df2)  # -> NaN
print(df1 / 0)  # -> NaN
print(df1 % 0)  # -> RuntimeError: ERR_DIV_BY_ZERO
print(df2 / 0)  # -> NaN
print(df2 % 0)  # -> RuntimeError: ERR_DIV_BY_ZERO
```

### Issue Description

See the related HDK issue for more details

### Expected Behavior

0    inf
dtype: float64
0   NaN
dtype: float64
0    inf
dtype: float64
0   NaN
dtype: float64
0   NaN
dtype: float64
0   NaN
dtype: float64

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
