### ISSUE TITLE
Remove category-hacks from the HDK tests.

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#5818]
As discussed here https://github.com/modin-project/modin/pull/5738#pullrequestreview-1348432612, the hacks should not be required anymore, after applying the fix #5738.

**Comment by anmyachev** [comment]
@AndreyPavlenko Is it still relevant?

**Comment by AndreyPavlenko** [comment]
> @AndreyPavlenko Is it still relevant?

Yes, it's relevant.

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
