### ISSUE TITLE
REFACTOR: Remove inplace kwarg from query compiler clip() arguments

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5844]
As the docs say, 

> This parameter serves the compatibility purpose.

https://github.com/modin-project/modin/blob/67efa96e14e7cd2339c68f90e81703f1fa755b3e/modin/core/storage_formats/base/query_compiler.py#LL797C13-L797C61

This param shouldn't go to the query compiler at all. API layer handles the `inplace` parameter: https://github.com/modin-project/modin/blob/67efa96e14e7cd2339c68f90e81703f1fa755b3e/modin/pandas/base.py#L1089

**Comment by anmyachev** [comment]
> This parameter serves the compatibility purpose.

I no longer see this comment in the pandas docs. Looks like we should support `inplace=True`. @mvashishtha?
https://pandas.pydata.org/pandas-docs/version/1.5.3/reference/api/pandas.DataFrame.clip.html?highlight=clip#pandas.DataFrame.clip

**Comment by mvashishtha** [comment]
> This parameter serves the compatibility purpose.

@anmyachev I think I meant that this was in the documentation of the query compiler method. What I meant was that we should handle this at the API layer and the query compiler methods should not accept an `inplace` parameter.

**Comment by anmyachev** [comment]
@mvashishtha ok, done in https://github.com/modin-project/modin/pull/5954
