### ISSUE TITLE
BUG: HDK's lazy computation tree may grow so big that it hits python's recursion limit

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5889]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import pandas
import tempfile
import sys

n_concats = 500

df = pd.DataFrame()

with tempfile.NamedTemporaryFile() as file:
    pandas.DataFrame({"a": [1, 2, 3, 4]}).to_csv(file.name, index=False)

    for _ in range(n_concats):
        chunk = pd.read_csv(file.name)
        df = pd.concat([df, chunk])

    op = df._query_compiler._modin_frame._op

    depth, stack = 0, [op]
    while stack:
        node = stack.pop()
        depth += 1
        if hasattr(node, "input"):
            for i in node.input:
                stack.append(i._op)
    
    print(f"computation tree depth: {depth}") # 1997
    print(f"max depth allowed: {sys.getrecursionlimit()}") # 1000
    
    try:
        print(df)
    except RecursionError as e:
        print(f"A recursion error has occurred when tried to operate on the frame: {e}") # it actually occurs
```

### Issue Description

HDK backend uses recursive functions to walk through its lazy computation tree, we should reimplement it to a non-recursive approach in order to not hit the limit.

### Expected Behavior

Not to fail

### Error Logs

<details>

```python-traceback

computation tree depth: 1997
max depth allowed: 1000
A recursion error has occured when tried to operate on the frame: maximum recursion depth exceeded in comparison

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by dchigarev** [comment]
It would also fail with one big concatenation as HDK doesn't support multiple arguments on rows join and so this is converted to a sequence of binary union operations:
```python
chunks = []
for _ in range(n_concats):
    chunks.append(pd.read_csv(file.name))
df = pd.concat(chunks)
print(df) # RecursionError as well
```

**Comment by dchigarev** [comment]
From a high-level view these are the places we should consider rewriting:
1. `.run_sub_queries()` https://github.com/modin-project/modin/blob/46d2cb5851efff580c8e469ced7d80592b1411d9/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py#L1934
2. `._can_execute_arrow()` https://github.com/modin-project/modin/blob/46d2cb5851efff580c8e469ced7d80592b1411d9/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py#L1951
3. the way we execute arrow (the `._execute_arrow()` method is called reqursevely on each node that can actually be executed through arrow): https://github.com/modin-project/modin/blob/46d2cb5851efff580c8e469ced7d80592b1411d9/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py#L1977
4. `.walk_dfs()`: https://github.com/modin-project/modin/blob/46d2cb5851efff580c8e469ced7d80592b1411d9/modin/experimental/core/execution/native/implementations/hdk_on_native/df_algebra.py#L175
5. calcite builder logic: https://github.com/modin-project/modin/blob/46d2cb5851efff580c8e469ced7d80592b1411d9/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_builder.py#L805-L808

**Comment by ienkovich** [comment]
Using the recursion for tree walks is a common approach. We can try to rewrite all our walkers to use loops and additional structures instead, but is it really better? Can we simply increase the limit using `sys.setrecursionlimit`?

**Comment by ienkovich** [comment]
As an option: catch `RecursionError` in `_execute` method, use a loop algorithm to compute the actual tree depth and set the new limit accordingly as `depth * cst`, and retry one more time.

**Comment by raistefintel** [comment]
I reported this internally, just so you know, when we tried increasing the recursion limit to suffice, a segmentation fault (core dumped) error was thrown, not sure this would work

**Comment by Garra1980** [comment]
sys.setrecursionlimit(10000) before all loops works for me :)

**Comment by Garra1980** [comment]
> sys.setrecursionlimit(10000) before all loops works for me :)

but for n_concats=2000 I see a segfault indeed. thanks @dchigarev for great reproducer btw
