### ISSUE TITLE
Reshuffling groupby doesn't handle grouping on a categorical column correctly

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5925]
The reshuffling groupby implementation introduced in #5928 doesn't handle categoricals correctly:

```python
import pandas

from modin.test.storage_formats.pandas.test_internals import construct_modin_df_by_scheme

df = pandas.DataFrame({"a": [1, 1, 1, 1, 2, 2, 2, 2], "b": [3, 4, 5, 6, 7, 8, 9, 10]}).astype({"a": "category"})

md_df = construct_modin_df_by_scheme(df, partitioning_scheme={"row_lengths": [4, 4], "column_widths": [2]})
assert md_df._query_compiler._modin_frame._partitions.shape == (2, 1)

import modin.config as cfg
cfg.ExperimentalGroupbyImpl.put(True)

print("modin:")
print(md_df.groupby("a").sum())
#     b
# a
# 1  18
# 2   0
# 1   0
# 2  34

print("pandas:")
print(df.groupby("a").sum())
#     b
# a
# 1  18
# 2  34
```

There are currently safeguards ([1](https://github.com/dchigarev/modin/blob/95b56becc9b6c799a438b1c39afc8288fa879aad/modin/core/storage_formats/pandas/query_compiler.py#L3109-L3111), [2](https://github.com/dchigarev/modin/blob/95b56becc9b6c799a438b1c39afc8288fa879aad/modin/core/dataframe/pandas/dataframe/dataframe.py#L3345-L3348)) that hides the problem and falls back to a non-reshuffling implementation. These safeguards have to be removed in order to reproduce the problem.

**Comment by YarShev** [comment]
@dchigarev, should we close this issue?

**Comment by dchigarev** [comment]
Not yet, it's still relevant. Planing to submit a PR fixing this soon

> @dchigarev, should we close this issue?
