### ISSUE TITLE
AttributeError when trying to index on an empty Series object

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#595]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.14
- **Modin installed from (source or binary)**: source
- **Python version**: 3.6

### Describe the problem
An `AttributeError: type object 'Series' has no attribute '__constructor__'` gets thrown when trying to index on an empty series

### Source code / logs
```
import modin.pandas as pd
pd.Series([])[:42]
```

**Comment by devin-petersohn** [comment]
Fixed by #596
