### ISSUE TITLE
Verify dtypes equality in tests

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5956]
We currently don't do so

--
Note: this issue is a part of an epic https://github.com/modin-project/modin/issues/3804

**Comment by mvashishtha** [comment]
Is this a duplicate of #3804?

**Comment by dchigarev** [comment]
Right, thanks for the catch!

Thus closing this one as duplicated

**Comment by dchigarev** [comment]
Although, let's reopen it and just put it as a child task of the #3804 epic
