### ISSUE TITLE
BUG: `Series.cat.codes` gives incorrect dtypes on HDK

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5973]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas
import modin.pandas as pd

import modin.config as cfg; cfg.StorageFormat.put("Hdk")

pd_ser = pandas.Series(["a", "ba", "a"], dtype="category")
md_ser = pd.Series(["a", "ba", "a"], dtype="category")

md_res = md_ser.cat.codes
pd_res = pd_ser.cat.codes

print(f"modin dtypes:\n{md_res.dtypes}\n") # category
print(f"pandas dtypes:\n{pd_res.dtypes}\n") # int8

print(f"modin internal dtypes:\n{md_res._to_pandas().dtypes}") # int32 (doesn't match modin's cache)
```

### Issue Description

As `cat.codes` produces integer values the dtype has to be not categorical but numerical.

The mismatch happens because HDK backend simply copies old dtypes, however it should infer a new one:
https://github.com/modin-project/modin/blob/7a95be20971b01026adab88104887a9591a98cb0/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py#L1595

### Expected Behavior

To match pandas.

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

--
Note: this issue is part of an epic https://github.com/modin-project/modin/issues/3804

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
