### ISSUE TITLE
BUG: `BaseOnPython` execution produces different from pandas dtypes on an empty slice

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5974]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
from modin.conftest import set_base_execution
from modin.pandas.test.utils import create_test_dfs

set_base_execution() # Set `BaseOnPython` execution 

md_df1, pd_df1 = create_test_dfs({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8], "c": [9, 10, 11, 12]})
md_res, pd_res = md_df1[2:2], pd_df1[2:2] # slice an empty dataframe

print(md_res.dtypes) # object
print(pd_res.dtypes) # int64
```

### Issue Description

Different dtypes

### Expected Behavior

To match pandas

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

--
Note: this issue is part of an epic https://github.com/modin-project/modin/issues/3804

**Comment by anmyachev** [comment]
Results on the current [master](https://github.com/modin-project/modin/commit/29d9da056a4e4766314c4ae9ea62b33e0d52e662):
```bash
>>> print(md_res.dtypes) # object
a    int64
b    int64
c    int64
dtype: object
>>> print(pd_res.dtypes) # int64
a    int64
b    int64
c    int64
dtype: object
```
