### ISSUE TITLE
CI: `test_io.py` failing on main because of missing AWS keys

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#5977]
See: https://github.com/modin-project/modin/actions/runs/4668447583/jobs/8265551805

Merge to main is failing right now because it is missing AWS keys for the motoserver.

**Comment by mvashishtha** [comment]
@pyrito this didn't work; could you please take a look: https://github.com/modin-project/modin/actions/runs/4670463354/jobs/8270225802

**Comment by anmyachev** [comment]
Perhaps this is the reason: https://github.com/modin-project/modin/issues/5944. Let's return the old way of waiting for the result, until we deal with this bug.
