### ISSUE TITLE
TEST: Allow concurrent test runs for pushes to master

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#5980]

**Comment by mvashishtha** [comment]
motivation: cancelled runs like https://github.com/modin-project/modin/actions/runs/4670296389/jobs/8269846726

but on the other hand, we use some common workflows for PR and push-to-master e.g. here https://github.com/modin-project/modin/blob/e1d639fed377a6eab01db8bfe0b768b2435bc753/.github/workflows/codeql.yml#L4-L7 and we don't want concurrent workflows on PRs. So I'm not sure what to do. cc @anmyachev

**Comment by anmyachev** [comment]
@mvashishtha https://github.com/modin-project/modin/pull/5917 should help. This allows multiple runs of CI in parallel on the master branch, but leaves the current behavior for pull requests.
