### ISSUE TITLE
TEST: eval_general should assume by default that pandas does not throw an error

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#6016]
right now `eval_general` with default parameters will not raise an assertion if both pandas and modin raise an error, even if that error is due to a mistake in writing the test code. This is dangerous behavior and it has silently swallowed mistakes in test code before. We should have to explicitly state that we are looking for an error.

Right now it's possible to work around this by setting [`raising_exceptions=(Exception,)`](https://github.com/modin-project/modin/blob/0a9fe393281280c2f1ff29ecec15461e80a98572/modin/pandas/test/utils.py#L881), but that should be the default.

@modin-project/modin-contributors @modin-project/modin-core @anmyachev I would like your thoughts on this.

**Comment by anmyachev** [comment]
@mvashishtha I agree, we should change the default behaviour.

**Comment by dchigarev** [comment]
+1 on this change

**Comment by vnlitvinov** [comment]
I would add that we may want to check that error messages are "close" (I don't have a good enough definition of "close" here, though).

The case my proposal is aimed at is handling a case when e.g. pandas throws an `AttributeError` but we've made a typo in test code (and so are also getting `AttributeError` but not the one we're expecting).
