### ISSUE TITLE
REFACTOR: Fix and refactor `resample` methods

### ISSUE THREAD

**Issue by noloerino** [modin-project/modin#6069]
We need to port fixes for resample.{sum,prod,size} and route a few additional methods differently. Unfortunately, the commits do not include test cases, so we will need to either comb through our internal JIRA or triage the failure cases manually.

- https://github.com/ponder-org/modin-public/commit/bd77b4140b029e38f7160546c663ca861f1dceee
- https://github.com/ponder-org/modin-public/commit/b6dc5c80e1a90b66876b15276ee9ea7433655872
- https://github.com/ponder-org/modin-public/commit/32a8db9e2238bb24c08c1416e50e2d7bba2aa842 <- need to figure out why this is marked no upstream
- https://github.com/ponder-org/modin-public/commit/b3fde395db21ee8d6092c8c3ade8ac9304fb814c
- https://github.com/ponder-org/modin-public/commit/ba7aa6d118ac85f0659daa8e768b270900a4dc82

**Comment by mvashishtha** [comment]
I can't keep working on this right now but I started a branch with all the commits, but there are some test failures at least in test_resample: https://github.com/mvashishtha/modin/tree/6069/fix-up-resample
