### ISSUE TITLE
REFACTOR: Push `first`/`last` to query compiler level

### ISSUE THREAD

**Issue by noloerino** [modin-project/modin#6071]
- https://github.com/ponder-org/modin-public/commit/bd9dd5fe519fa2f86d8017d37916430fed759719

**Comment by noloerino** [comment]
On further examination, it seems like the modin implementation of these methods needs to call `BasePandasDataset.loc`, and refactoring the logic for that into the query compiler would be difficult/undesirable. @mvashishtha do you have any suggestions for handling this?

**Comment by mvashishtha** [comment]
@noloerino in cases like this, we put that logic into the base query compiler. see e.g. [`merge_asof`](https://github.com/modin-project/modin/blob/1f321c7858da4786ee1fe71addeb6462cff7a998/modin/core/storage_formats/base/query_compiler.py#L896)
