### ISSUE TITLE
Pandas 2.0 | arrow data types.

### ISSUE THREAD

**Issue by OnyxianSoul** [modin-project/modin#6096]
Hello! I read a bit about modin and it seems very interesting, specially since its basically a dropin replacement for pandas.

However, I'm currently using pandas 2.0, with the new arrow dtypes, and when i install modin pandas 2.0 is uninstalled.
1- Is there a way to install a newer version of modin that uses pandas 2.0+ ?
2- Or is support for pandas 2.0 planned soon?
3- Is there some other way to use the current version of modin with arrow dtypes?
4- Is there a way to at least prevent modin from uninstalling pandas 2.0?

Thanks for developing an amazing library!

**Comment by Garra1980** [comment]
pandas 2.0 support currently is in progress, please expect it in the next Modin release

**Comment by mvashishtha** [comment]
#5936 is the issue to watch for pandas 2.0 support
