### ISSUE TITLE
loc gives incorrect values when given a Boolean indexer

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#610]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.6.0.dev.0
- **Python version**: 3.6
- **Exact command to reproduce**: `df.loc[df.col1 < 5]`

### Describe the problem

`loc` does not support Boolean indexers. This was originally reported over email and reproduced by me locally.

### Source code / logs

```python
import modin.pandas as pd
df = pd.DataFrame({"col1":[1,2,3,4,5,6], "col2":[1,2,3,4,5,6]})
df.loc[df.col1 < 5]
```

**Comment by ipacheco-uy** [comment]
Hi Devin, i check and loc does not support boolean and callable, the idea is to fallback or support it?

**Comment by devin-petersohn** [comment]
Thanks @ipacheco-uy, we won't fallback to support this because it would be really expensive.

I outlined a bit of what is needed in a post on the discourse: https://discuss.modin.org/t/indexing-update-rewrite/57

Indexing needs to be updated because some of the general implementation is too slow. Indexing should be fast and correct. We also have diverged codepaths for `loc` and `__getitem__`, which doesn't make a lot of sense because they do similar things. They should at least be the same in the backend.
