### ISSUE TITLE
pip install modin.  ERROR: Could not find a version that satisfies the requirement ray==0.6.6 (from modin) (from versions: none) ERROR: No matching distribution found for ray==0.6.6 (from modin)

### ISSUE THREAD

**Issue by halesantosh** [modin-project/modin#611]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by devin-petersohn** [comment]
Hi @halesantosh, it looks like you might be using Windows. Read here for how to install from Windows: https://modin.readthedocs.io/en/latest/installation.html#windows

If you are not using Windows, please let me know your OS/Python version and which Modin version you are trying to install. Thanks!

**Comment by devin-petersohn** [comment]
Note, we do have an active effort on Windows support, see #657.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.

**Comment by jerrybaba2** [comment]
> Hi @halesantosh, it looks like you might be using Windows. Read here for how to install from Windows: https://modin.readthedocs.io/en/latest/installation.html#windows
> 
> If you are not using Windows, please let me know your OS/Python version and which Modin version you are trying to install. Thanks!

I need to install ray[rllib]==0.7.6 on python 3.8 ubuntu 20.04 but having issues. could someone please help?

**Comment by devin-petersohn** [comment]
@jerrybaba2 Ray is on release 1.2 and we dropped support for ray < 1.0 because of some API changes.
