### ISSUE TITLE
The columns will be mixed where using "usecols" in pd.read_csv()

### ISSUE THREAD

**Issue by excitingx** [modin-project/modin#612]
```
import modin.pandas as pd
col = ['name', 'idcard', 'phone', 'loan_dt']
cur_data_old_1 = pd.read_csv(os.path.join(path, 'train'), sep='\t', usecols=col)
```

**Comment by devin-petersohn** [comment]
Hi @excitingx thanks for posting!

Would you be able provide an "expected output" and a "actual output"? The column order should match the pandas behavior. Thanks!

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
