### ISSUE TITLE
 Error in pip command: 'utf-8' codec can't decode byte 0xe9 in position 32: invalid continuation byte

### ISSUE THREAD

**Issue by Mat6935** [modin-project/modin#6124]
Hello everyone. I tried to install the opsvis package from openseespy. But I face a problem when I use the pip command.
![Capture160](https://github.com/modin-project/modin/assets/132265276/59554978-aba2-4ed7-a4a4-a720485edcfe)
 Can you help me please ?

**Comment by pyrito** [comment]
Hi @Mat6935 - I'm not sure if this bug is related to anything Modin related (please correct me if I'm wrong here), so I'm going to go ahead and close this issue.
