### ISSUE TITLE
FEAT: ray.data.from_modin should work with non-partitioned modin storage format

### ISSUE THREAD

**Issue by rentruewang** [modin-project/modin#6141]
Right now it doesn't work because `unwrap_partitions` here:

https://github.com/ray-project/ray/blob/5a5155c7f49f720a2a548812057724a16d5d564f/python/ray/data/read_api.py#L1523-L1541

doesn't work when modin is not backed by partitions. Maybe this could be changed?

**Comment by anmyachev** [comment]
@rentruewang could you provide more details about the problem you were trying to solve?
