### ISSUE TITLE
BUG: Interchange `Column.size` should be a property, not a method

### ISSUE THREAD

**Issue by honno** [modin-project/modin#6143]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
>>> df = mpd.DataFrame({"foo": [42]})
>>> df.__dataframe__()
>>> col = df.__dataframe__().get_column(0)
>>> col.size
<bound method PandasProtocolColumn.size>  # should just return an int object
```

### Issue Description

The [relevant interchange protocol spec](https://github.com/data-apis/dataframe-api/blob/16aabbf1413346190d34b401cef0ec7afa4bd7a0/protocol/dataframe_protocol.py#L216-L227) has `Column.size` as a property, not a method. `modin`'s interchange column object however has it as a method

https://github.com/modin-project/modin/blob/f76f98f8b6d480bc2200dc65a8fa958b4973cf65/modin/core/dataframe/pandas/interchange/dataframe_protocol/column.py#L113-L114

This prevents interchanging with other libraries a lot of the time, as `Column.size` is assumed an `int` so you get a bunch of type errors and the like.

### Expected Behavior

```python
>>> col.size
1
```

### Installed Versions

<details>

```
mpd.show_versions()
UserWarning: Setuptools is replacing distutils.

INSTALLED VERSIONS
------------------
commit           : 632d724adb013d6f4d18aa2a4f2faa9325d324e8
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-41-generic
Version          : #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

Modin dependencies
------------------
modin            : 0.20.0+47.g632d724a
ray              : 2.4.0
dask             : 2023.5.0
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 1.4.3
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.4.0
pip              : 23.0.1
Cython           : None
pytest           : 7.3.1
hypothesis       : 6.75.3
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.5.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : 0.57.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : 2023.4.2
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
```

</details>

**Comment by YarShev** [comment]
@honno, as you mentioned a link to the relevant interchange protocol spec, size is a method rather than a property. Or am I missing on something? https://github.com/data-apis/dataframe-api/blob/16aabbf1413346190d34b401cef0ec7afa4bd7a0/protocol/dataframe_protocol.py#L216-L227

**Comment by honno** [comment]
> @honno, as you mentioned a link to the relevant interchange protocol spec, size is a method rather than a property. Or am I missing on something? https://github.com/data-apis/dataframe-api/blob/16aabbf1413346190d34b401cef0ec7afa4bd7a0/protocol/dataframe_protocol.py#L216-L227

Oh yeah... sorry about that! I mangled other issues in my head :facepalm:
