### ISSUE TITLE
Error jupyter import modin module

### ISSUE THREAD

**Issue by Canon88** [modin-project/modin#619]
![image](https://user-images.githubusercontent.com/19372121/57705423-744ebd00-7696-11e9-92aa-67ccaabb62ad.png)

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.4 (18E226)
- **Modin installed from (source or binary)**: pip install modin
- **Modin version**: 0.5.0
- **Python version**: Python 3.7
- **Exact command to reproduce**: import modin.pandas as pd

### Describe the problem
When I imported the Modin module using jupyter, I saw the following error.

But with ipython everything is fine with imports, anyone tell me why? thinks!

**Comment by devin-petersohn** [comment]
Hi @Canon88, thanks for posting!

This is strange, I have seen it before here: #540. I thought it would be fixed by removing the `typing` dependency, did you have Modin 0.4 installed on that machine?

One option to try is to `pip uninstall typing`. Please let me know if that helps!

**Comment by Canon88** [comment]
I did not install Modin 0.4 before then, but I ` pip uninstall typing ` problem solved. thinks!
![image](https://user-images.githubusercontent.com/19372121/57712603-710dfe00-76a3-11e9-8650-8e429db2a94c.png)
