### ISSUE TITLE
Allow set_index to take an object to be handled by the backend (a backend index, etc)

### ISSUE THREAD

**Issue by jkew** [modin-project/modin#6225]
As discussed in #1780, the set_index API assumes that we either have a set of column names/objects and that the set of columns passed in matches the set of known columns. We then call set_index_from_columns to let the backend handle the operation. A problem occurs when we need to call set_index with a backend type which the modin layer does not know about:

```
df.set_index(MyBackendIndex)
```

`MyBackendIndex` is not a normal Pandas type, nor a type which modin knows about, nor an actual column in the dataframe. In this case we want the backend to be responsible for as much of the handling here as possible. We *also* want to retain the nice error handling already present in set_index to get for missing columns.

One solution I have is to get to see if keys is non-"primitive" and when it is considered missing from the columns we raising an error and throw it over the wall to the query_compiler. Another method might be to agree on an attribute or method set on each backend which can tell the dataframe set_index method to circumvent the column checks.

*dataframe.set_index* approach:
```
-        if missing:
+        # If the missing column is a "primitive", return the errors.
+        # Otherwise we let the query compiler figure out what to do with
+        # the keys
+        if missing and not hasattr(missing[0], "__dict__"):
+            # The keys are a primitive type
             raise KeyError(f"None of {missing} are in the columns")
```
 
https://github.com/modin-project/modin/issues/1780

**Comment by mvashishtha** [comment]
> Another method might be to agree on an attribute or method set on each backend which can tell the dataframe set_index method to circumvent the column checks.

If we find another case where we need to differentiate a pandas index from a "modin index", we can create an abstract base class `modin.pandas.AbstractIndex`, and each backend can subclass that class. Then, we can check `isinstance(missing[0], modin.pandas.AbstractIndex)`. There is already a [`ModinIndex`](https://github.com/modin-project/modin/blob/f0f9ffee78e40591c18a851df7dad12541c71bce/modin/core/dataframe/pandas/metadata/index.py#L20) in this repository, but modin uses it internally and doesn't expose it to users. If we ever expose `ModinIndex` to users, `ModinIndex` could subclass the new abstract class as well.
