### ISSUE TITLE
Support vectors

### ISSUE THREAD

**Issue by rentruewang** [modin-project/modin#6236]
Is it possible to use modin dataframes like a vector database such as [milvus](https://github.com/milvus-io/milvus)? That would be very helpful!

**Comment by anmyachev** [comment]
@rentruewang thanks for the question!

If you mean is it possible to use this database as one of Modin's backends, then I think it is possible and it would be interesting. However, I'm not familiar with this database and it's hard for me to guess how long Modin's integration with it will take.

@modin-project/modin-core maybe you know more about Milvus.

**Comment by mvashishtha** [comment]
@anmyachev , @rentruewang is exploring a solution to this, so I've assigned this issue to him for now.
