### ISSUE TITLE
Fix some groupby test cases that were commented out after switching to pandas>=2.0.

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6246]
https://github.com/modin-project/modin/blob/1d8a179dc0d775b8601f0586da4b64f9c4f86c0b/modin/pandas/test/test_groupby.py#L1344-L1356

**Comment by YarShev** [comment]
@anmyachev, the issue in pandas was fixed in 2.0.1. Do we still see the problem on our side?

**Comment by anmyachev** [comment]
> @anmyachev, the issue in pandas was fixed in 2.0.1. Do we still see the problem on our side?

yes, I see
