### ISSUE TITLE
ArrowInvalid: Maximum size exceeded (2GB)

### ISSUE THREAD

**Issue by Jie-Yuan** [modin-project/modin#628]
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-8-a36dd1ddace7> in <module>
----> 1 mdf.head().title.map(func)

/usr/local/lib/python3.5/dist-packages/modin/pandas/series.py in map(self, arg, na_action)
    686         return self.__constructor__(
    687             query_compiler=self._query_compiler._map_partitions(
--> 688                 lambda df: pandas.DataFrame(df.iloc[:, 0].map(arg, na_action=na_action))
    689             )
    690         )

/usr/local/lib/python3.5/dist-packages/modin/backends/pandas/query_compiler.py in _map_partitions(self, func, new_dtypes)
   1049     def _map_partitions(self, func, new_dtypes=None):
   1050         return self.__constructor__(
-> 1051             self.data.map_across_blocks(func), self.index, self.columns, new_dtypes
   1052         )
   1053 

/usr/local/lib/python3.5/dist-packages/modin/engines/base/frame/partition_manager.py in map_across_blocks(self, map_func)
    207             A new BaseFrameManager object, the type of object that called this.
    208         """
--> 209         preprocessed_map_func = self.preprocess_func(map_func)
    210         new_partitions = np.array(
    211             [

/usr/local/lib/python3.5/dist-packages/modin/engines/base/frame/partition_manager.py in preprocess_func(self, map_func)
     98             being used).
     99         """
--> 100         return self._partition_class.preprocess_func(map_func)
    101 
    102     # END Abstract Methods

/usr/local/lib/python3.5/dist-packages/modin/engines/ray/pandas_on_ray/frame/partition.py in preprocess_func(cls, func)
    106             A ray.ObjectID.
    107         """
--> 108         return ray.put(func)
    109 
    110     @classmethod

/usr/local/lib/python3.5/dist-packages/ray/worker.py in put(value)
   2214             worker.task_context.put_index,
   2215         )
-> 2216         worker.put_object(object_id, value)
   2217         worker.task_context.put_index += 1
   2218         return object_id

/usr/local/lib/python3.5/dist-packages/ray/worker.py in put_object(self, object_id, value)
    373         # Serialize and put the object in the object store.
    374         try:
--> 375             self.store_and_register(object_id, value)
    376         except pyarrow.PlasmaObjectExists:
    377             # The object already exists in the object store, so there is no

/usr/local/lib/python3.5/dist-packages/ray/worker.py in store_and_register(self, object_id, value, depth)
    307                         memcopy_threads=self.memcopy_threads,
    308                         serialization_context=self.get_serialization_context(
--> 309                             self.task_driver_id))
    310                 break
    311             except pyarrow.SerializationCallbackError as e:

/usr/local/lib/python3.5/dist-packages/ray/utils.py in _wrapper(*args, **kwargs)
    473                 def _wrapper(*args, **kwargs):
    474                     with self.lock:
--> 475                         return orig_attr(*args, **kwargs)
    476 
    477                 self._wrapper_cache[attr] = _wrapper

/usr/local/lib/python3.5/dist-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient.put()

/usr/local/lib/python3.5/dist-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.serialize()

/usr/local/lib/python3.5/dist-packages/ray/pyarrow_files/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: Maximum size exceeded (2GB)

**Comment by devin-petersohn** [comment]
Thanks @Jie-Yuan for reporting this!

What is the data size you're working with? For a `map` I am surprised by this error message.

cc @pcmoritz

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
