### ISSUE TITLE
Add support for pyhdk v0.6.1 flags

### ISSUE THREAD

**Issue by alexbaden** [modin-project/modin#6296]
In pyhdk v0.6.1 we are introducing two new features:

* Ability to place logs in a specific directory (e.g. the temp directory, if log files are not required). This was a request from one of our benchmarking teams. 
* Ability to lazily materialize dictionary encoded string columns. This feature speeds up the import process, particularly if only a few text columns are processed later in a query. However, it makes benchmarking more difficult, and can slow down workflows with large numbers of queries on text columns, so we're making it configurable. 

We have also introduced a version API in HDK v0.5 which we will use to remove these flags from the command string for HDK versions older than 0.6.1. 

I plan to submit a PR with these new config variables + version processing shortly.

**Comment by Garra1980** [comment]
Let's also substitute 0.6.1 to 0.7 everywhere
