### ISSUE TITLE
Should `__array__` method always return array of vanilla numpy? (instead of experimental Modin wrapper)

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6299]
In some cases inside Modin, the series and dataframe objects are converted to a numpy array as follows: `numpy.array(value)`. However, the functions further do not expect that there can be an distributed object after this call.

@RehanSD what do you think about?

**Comment by RehanSD** [comment]
NumPy expects __array__ to return a NumPy object - if we modify it I think NumPy will complain, so to me, it makes sense to have __array__ default to NumPy. If a user wants to convert to a Modin NumPy array, I think it’s far more likely they’ll use .to_numpy or Modin.numpy.array(object) - so we don’t need to worry about users getting tripped up by this!

**Comment by anmyachev** [comment]
> NumPy expects **array** to return a NumPy object - if we modify it I think NumPy will complain, so to me, it makes sense to have **array** default to NumPy. If a user wants to convert to a Modin NumPy array, I think it’s far more likely they’ll use .to_numpy or Modin.numpy.array(object) - so we don’t need to worry about users getting tripped up by this!

@RehanSD I prepared a pull request with the appropriate changes :) #6300
