### ISSUE TITLE
add modin-spreadsheet in conda-forge

### ISSUE THREAD

**Issue by rootsmusic** [modin-project/modin#6331]
I installed [modin-all](https://anaconda.org/conda-forge/modin-all) 0.18.0 from conda-forge, but it doesn't include [modin-spreadsheet](https://github.com/modin-project/modin-spreadsheet).

**Comment by YarShev** [comment]
Hi @rootsmusic, thanks for opening this issue. Currently, `modin-spreadsheet` is not included in `modin-all` on conda-forge. To have `modin-spreadsheet` installed you can use `pip install modin[all]`, for instance. There were the reasons discussed in https://github.com/conda-forge/modin-feedstock/pull/14 to not include `modin-spreadsheet` in `modin-all`. @devin-petersohn, do we have plans to include `modin-spreadsheet` in `modin-all` on conda-forge?

**Comment by rootsmusic** [comment]
Thanks, @YarShev.  modin-spreadsheet isn't working, which makes this issue moot.
