### ISSUE TITLE
BUG: ray thinks pytz is not installed

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#6335]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
(raylet) Error processing line 1 of /home/ec2-user/.local/lib/python3.9/site                                                         -packages/modin-autoimport-pandas.pth:
(raylet)
(raylet)   Traceback (most recent call last):
(raylet)     File "/usr/lib64/python3.9/site.py", line 169, in addpackage
(raylet)       exec(line)
(raylet)     File "<string>", line 1, in <module>
(raylet)     File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/                                                         __init__.py", line 16, in <module>
(raylet)       raise ImportError(
(raylet)   ImportError: Unable to import required dependencies:
(raylet)   pytz: No module named 'pytz'
(raylet)
(raylet) Remainder of file ignored
```

### Issue Description

pytz is definitely installed.

### Expected Behavior

NA

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by anmyachev** [comment]
@jbrockmendel could you provide self-contained reproducer?

**Comment by vnlitvinov** [comment]
I would guess there's something weird going on in terms of how Ray starts the cluster...
Could you also provide the `import pytz; print(pytz.__file__)` from the environment where `pytz` is "definitely installed"?

**Comment by anmyachev** [comment]
At the moment there is not enough information for any action on our part.
