### ISSUE TITLE
New Feature Request: Add support for drop_duplicates()

### ISSUE THREAD

**Issue by ddutt** [modin-project/modin#634]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **Modin installed from (source or binary)**: binary, pip install modin
- **Modin version**: 0.5.0
- **Python version**: 3.7.3
- **Exact command to reproduce**: Use drop_duplicates()

### Describe the problem

drop_duplicates() is not supported today resulting in the following message when used:
```
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
UserWarning: `DataFrame.duplicated` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: Distributing <class 'pandas.core.series.Series'> object. This may take some time.
UserWarning: `Series.__array__` defaulting to pandas implementation.
```

**Comment by ddutt** [comment]
Hmm.  If I add inplace=False as one of the options to drop_duplicates() I no longer see the error.

**Comment by devin-petersohn** [comment]
Thanks @ddutt for the request! `drop_duplicates` is currently implemented to use `drop` after computing `duplicated` in dataframe.py. For `inplace=False`, that shouldn't change the behavior of the operation generally. 

We would need to implement `duplicated` as a parallel operation and `drop_duplicates` would get the benefit from that as well.

For now I will flag as Help Wanted.

**Comment by devin-petersohn** [comment]
We do try to prune the messages so it's not constantly giving them if the same thing is done over and over, that may be what you're experiencing with the same operation.

**Comment by ddutt** [comment]
Ahh, thanks for that explanation. BTW, is you can provide any pointers to what is required to support duplicated as a parallel operation, I can try to help. I'm a software engineer.

**Comment by devin-petersohn** [comment]
Thanks @ddutt, we love new contributors! Never be afraid to ask to contribute to Modin 😄 

In this case, the best first-pass would probably be to make use of the functionality in the backend. It will allow parallelism across columns. 

We will need a new functionality in the [`PandasQueryCompiler`](https://github.com/modin-project/modin/blob/master/modin/backends/pandas/query_compiler.py) to support `duplicated`. It can call the `_map_across_full_axis` helper function and follow a similar pattern to `PandasQueryCompiler.diff`. 

Let me know if that helps or if you have any questions!

**Comment by eavidan** [comment]
Hi @devin-petersohn. 
Would the implementation simply be to use the `_apply_full_axis()` and apply `duplicated`?
This should apply to both `Dataframe` and `Series`. am I missing something?
also, what kind of tests should I add for this? can you reference an example?
Thanks

**Comment by devin-petersohn** [comment]
I wrote something in another comment for how to handle this in this comment: https://github.com/modin-project/modin/issues/820#issuecomment-541259286

The relevant code is:

```python
df.drop(df.index[pd.DataFrame(df.apply(lambda s: hash(s.to_numpy().data.tobytes()), axis=1)).apply(lambda s: s.duplicated())[0]], inplace=True)
```

Test wise we will need to test the following:

- `keep` parameterized for `["first", "last", False]`
- `subset` parameterized for some subset of column labels (and left `None`) for each of the following:
  - data where every row is a duplicate
  - data where no rows are duplicate
  - data where some of the rows are duplicate
  - data where a subset of the columns are duplicate
- `inplace` argument
- a few different `dtypes` in the columns

I don't think any of our test datasets are controlled in this way, many of those datasets are randomized with a seed. It might require adding a custom test dataset that is prepared specifically for the `drop_duplicates` test.

**Comment by eavidan** [comment]
Thanks @devin-petersohn.
The above example works but I still find it hard to write an implementation which conforms with our current code flow.
would the following make sense?

in `dataframe.py`:
```py
    def duplicated(self, subset=None, keep="first"):
        df = self[subset] if subset is not None else self
        return super(
            DataFrame,
            DataFrame(df.apply(lambda s: hash(s.to_numpy().data.tobytes()), axis=1)),
        ).duplicated(keep=keep)
```

in `series.py`:
```py
    def duplicated(self, keep="first"):
        from .dataframe import DataFrame

        return super(DataFrame, DataFrame(self)).duplicated(keep=keep)
```

and in `base.py`:
```py
    def duplicated(self, keep="first"):
        duplicates = self.apply(lambda s: s.duplicated(keep=keep)).squeeze()
        duplicates.name = None
        return duplicates
```

This does not feel "clean" enough, but I could not find a better way to implement the same logic on both `Series` and `Dataframe`.
Also, is there a clearer way to get rid of the assigned name other than `duplicates.name = None` ?

**Comment by devin-petersohn** [comment]
We may want to put some of this logic into the PandasQueryCompiler so that it can be used by other implementations.

What about this:

in `dataframe.py`:
```py
    def duplicated(self, subset=None, keep="first"):
        df = self[subset] if subset is not None else self
        # if the number of columns we are checking for duplicates is larger than 1, we must
        # hash them to generate a single value that can be compared across rows.
        if len(df.columns > 1):
            hashed = df.apply(lambda s: hash(s.to_numpy().data.tobytes()), axis=1)).to_frame()
        else:
            hashed = self
        return hashed.apply(lambda s: s.duplicated(keep=keep)).squeeze(axis=1)
```

in `series.py`:
```py
    def duplicated(self, keep="first"):
        return self.to_frame().duplicated(keep=keep)
```
The `base.py` code in your answer assumed a dataframe input, so that code probably belongs in `dataframe.py`.

**Comment by devin-petersohn** [comment]
Feature added via #892
