### ISSUE TITLE
Pandas's dataframe to modin's dataframe

### ISSUE THREAD

**Issue by DBRookie** [modin-project/modin#6348]
`import numpy as np

import modin.pandas as pd
import pandas
import re as re
import modin.config as modin_cfg
modin_cfg.Engine.put("dask")  # Modin will use Dask

train = pandas.read_csv('train.csv', header = 0, dtype={'Age': np.float64})
test  = pandas.read_csv('test.csv' , header = 0, dtype={'Age': np.float64})
train = pd.DataFrame(train)`

I use pandas to read csv, then I want to convert pandas dataframe to modin dataframe, but _train = pd.DataFrame(train)_ will report an error TypeError: unhashable type: 'list'  . Can someone tell me what this is about?

**Comment by anmyachev** [comment]
Hi @DBRookie! Thanks for the question. 

It is difficult to understand the reason for this error. Could you provide the full stacktrace of the error?

**Comment by DBRookie** [comment]
thanks for your repaly @anmyachev !
This is the full stacktrace of the error:

`Traceback (most recent call last):
  File "/root/volume/script_data/ML_modin.py", line 14, in <module>
    train = pd.DataFrame(train)
  File "/usr/local/lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modin/pandas/dataframe.py", line 178, in __init__
    distributed_frame = from_non_pandas(data, index, columns, dtype)
  File "/usr/local/lib/python3.9/site-packages/modin/pandas/utils.py", line 71, in from_non_pandas
    new_qc = FactoryDispatcher.from_non_pandas(df, index, columns, dtype)
  File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 173, in from_non_pandas
    return cls.get_factory()._from_non_pandas(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 115, in get_factory
    Engine.subscribe(_update_engine)
  File "/usr/local/lib/python3.9/site-packages/modin/config/pubsub.py", line 217, in subscribe
    callback(cls)
  File "/usr/local/lib/python3.9/site-packages/modin/pandas/__init__.py", line 147, in _update_engine
    from modin.core.execution.dask.common import initialize_dask
  File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dask/common/__init__.py", line 16, in <module>
    from .engine_wrapper import DaskWrapper
  File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dask/common/engine_wrapper.py", line 18, in <module>
    from distributed.client import default_client
  File "/usr/local/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/usr/local/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/usr/local/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/usr/local/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/local/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/usr/local/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'`

And this is my env:
Pandas：1.5.3
modin：0.22.2

**Comment by DBRookie** [comment]
Hi @anmyachev ～

**Comment by anmyachev** [comment]
> thanks for your repaly @anmyachev ! This is the full stacktrace of the error:
> 
> ```
> Traceback (most recent call last):
>   File "/root/volume/script_data/ML_modin.py", line 14, in <module>
>     train = pd.DataFrame(train)
>   File "/usr/local/lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
>     return obj(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/modin/pandas/dataframe.py", line 178, in __init__
>     distributed_frame = from_non_pandas(data, index, columns, dtype)
>   File "/usr/local/lib/python3.9/site-packages/modin/pandas/utils.py", line 71, in from_non_pandas
>     new_qc = FactoryDispatcher.from_non_pandas(df, index, columns, dtype)
>   File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 173, in from_non_pandas
>     return cls.get_factory()._from_non_pandas(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 115, in get_factory
>     Engine.subscribe(_update_engine)
>   File "/usr/local/lib/python3.9/site-packages/modin/config/pubsub.py", line 217, in subscribe
>     callback(cls)
>   File "/usr/local/lib/python3.9/site-packages/modin/pandas/__init__.py", line 147, in _update_engine
>     from modin.core.execution.dask.common import initialize_dask
>   File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dask/common/__init__.py", line 16, in <module>
>     from .engine_wrapper import DaskWrapper
>   File "/usr/local/lib/python3.9/site-packages/modin/core/execution/dask/common/engine_wrapper.py", line 18, in <module>
>     from distributed.client import default_client
>   File "/usr/local/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
>     from distributed.actor import Actor, ActorFuture, BaseActorFuture
>   File "/usr/local/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
>     from distributed.client import Future
>   File "/usr/local/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
>     WorkerDataParameter: TypeAlias = Union[
>   File "/usr/local/lib/python3.9/typing.py", line 243, in inner
>     return func(*args, **kwds)
>   File "/usr/local/lib/python3.9/typing.py", line 316, in __getitem__
>     return self._getitem(self, parameters)
>   File "/usr/local/lib/python3.9/typing.py", line 421, in Union
>     parameters = _remove_dups_flatten(parameters)
>   File "/usr/local/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
>     all_params = set(params)
> TypeError: unhashable type: 'list'
> ```
> 
> And this is my env: Pandas：1.5.3 modin：0.22.2

Thanks for the information! Judging by the stack, the problem is related to the Dask. Could you also provide information about versions of `dask` and `distributed` in your environment.

**Comment by anmyachev** [comment]
> Hi @anmyachev ～ Actually, I'm trying to convert numpy's ndarray to modin's dataframe, but I can't find the api for that, so for now I'm trying to convert ndarray to pandas dataframe first, and then convert pandas dataframe to modin's

`modin.pandas.DataFrame(ndarray)` should work. Did you try it?

**Comment by DBRookie** [comment]
> 
Yes, I tried this approach，but it has the same error `unhashable type: 'list'`.

**Comment by DBRookie** [comment]
> > Hi @anmyachev ～ Actually, I'm trying to convert numpy's ndarray to modin's dataframe, but I can't find the api for that, so for now I'm trying to convert ndarray to pandas dataframe first, and then convert pandas dataframe to modin's
> 
> `modin.pandas.DataFrame(ndarray)` should work. Did you try it?

Yes, I tried this approach，but it has the same error `unhashable type: 'list'`.
 Versions of dask and distributed are both 2023.6.1

**Comment by anmyachev** [comment]
@DBRookie It looks like you've encountered a rare bug in python itself. What version of python are you using? For reference: https://bugs.python.org/issue42965

**Comment by anmyachev** [comment]
> > @DBRookie It looks like you've encountered a rare bug in python itself. What version of python are you using? For reference: https://bugs.python.org/issue42965
> 
> Hi @anmyachev ! My python version is 3.9.0. It's rather strange that my code seems to only involve the conversion of dataframes from pandas to modin, or it could be a problem with some of the underlying code.

Hi @DBRookie, the problem is in standard library - `typing`, you need to update python at least to version 3.9.2 (according to https://bugs.python.org/issue42965). After updating python, your reproducer should work without any changes.

A good tip in that cases would be to use the latest version of python as possible to avoid this kind of error. For example, python=3.9.15.

**Comment by DBRookie** [comment]
Hi @anmyachev ! As you said, it was indeed a problem with the python version, I solved it after switching to 3.10.2, thank you very much!

**Comment by anmyachev** [comment]
@DBRookie glad to hear that!
