### ISSUE TITLE
New Feature Request: Predicate Pushdown support for Parquet

### ISSUE THREAD

**Issue by ddutt** [modin-project/modin#636]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.04
- **Modin installed from (source or binary)**: binary, pip install modin
- **Modin version**: 0.5.0
- **Python version**: 3.7.3
- **Exact command to reproduce**: Use filters in read_parquet

### Describe the problem

Probably one of the most important features of parquet is the support for predicate pushdown which helps cut down on the I/O quite significantly. pyarrow supports it, but not in the read_pandas() code. If you replace the existing call to read_pandas() in ray/pandas_on_ray/io.py with the following segment, predicate pushdown automatically works:
```
    df = pq.ParquetDataset(path, **kwargs) \
           .read(columns=columns) \
           .to_pandas()
    # df = pq.read_pandas(path, columns=columns, **kwargs).to_pandas()
    # Append the length of the index here to build it externally
```
I've included the original read_pandas() code commented out to provide an anchor.

**Comment by devin-petersohn** [comment]
Thanks @ddutt! I agree this is an extremely important addition.

Feel free to add this in a PR since you've already written the code to do it in your issue report. Thanks!

cc @williamma12

**Comment by ddutt** [comment]
OK, I can do a PR with the relevant patch.

**Comment by ddutt** [comment]
Issued a PR.

**Comment by devin-petersohn** [comment]
Resovled by #638
