### ISSUE TITLE
BUG: Ray to_parquet defaults to Pandas while documentation says supported

### ISSUE THREAD

**Issue by ajalberd** [modin-project/modin#6401]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
df = pd.DataFrame(range(5))
df.to_parquet('d.parquet', compression='brotli')
```

### Issue Description

Documentation states:

`Ray/Dask/Unidist: Parallel implementation only if path parameter is a string; does not end with “.gz”, “.bz2”, “.zip”, or “.xz”; and compression parameter is not None or “snappy”. In these cases, the path parameter specifies a directory where one file is written per row partition of the Modin dataframe.`

But when I specify compression='brotli' or some other compression, it will state "defaulting to pandas implementation"

### Expected Behavior

Parquet writes but after Pandas conversion.

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

<details>

pandas 2.0.3
modin 0.23.0

</details>

**Comment by ajalberd** [comment]
Solution: DON'T specify compression, it will write just fine without defaulting to pandas. Documentation should be clarified on this as Pandas documentation has snappy as default compression, but Modin says not to specify snappy, I figured I would specify another but this is not the case..

**Comment by mvashishtha** [comment]
@ajalberd thank you for reporting this issue! Indeed, the documentation is incorrect, here. However, I think supporting all compression schemes should be simple. I'll see if I can fix this.
