### ISSUE TITLE
Filters in read_parquet

### ISSUE THREAD

**Issue by zmbc** [modin-project/modin#6417]
Currently, `pd.read_parquet(..., filters=<filters>)` defaults to Pandas. If I understand correctly, this means that there is no way to read a small part of a large Parquet file in Modin without loading the whole file into memory, and _then_ performing filters.

I was surprised to see this default to Pandas, because the docs for `read_parquet` [say the Modin implementation is complete](https://modin.readthedocs.io/en/stable/supported_apis/io_supported.html) and the docstring even says "Any additional kwargs are passed to the engine" which seems like it would be enough to make this feature work.

In case this is somehow a bug, here's my full reproducible example:

I downloaded userdata1.parquet from [this GitHub repo](https://github.com/Teradata/kylo/tree/master/samples/sample-data/parquet) to use as sample data.

Then I ran:

```
import modin.pandas as pd
pd.read_parquet('./userdata1.parquet', filters=[('id', '==', 1)])
```

**Comment by vnlitvinov** [comment]
This is a recent check added in the code in https://github.com/modin-project/modin/pull/5911, which was fixing an issue somewhat resembling what you say here (https://github.com/modin-project/modin/issues/5509). I think we should amend the documentation for now, and try to implement distributed `read_parquet` sometime in the future.

cc @anmyachev

**Comment by anmyachev** [comment]
@vnlitvinov https://github.com/modin-project/modin/pull/6420
