### ISSUE TITLE
BUG: Using `from_partitions` on a Ray dataset returns an incorrect index

### ISSUE THREAD

**Issue by jaidisido** [modin-project/modin#6418]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import ray

path = "s3://bucket/file.parquet"

df = pd.DataFrame({"c0": [0, 1, 2], "c1": ["foo", "bar", "baz"]})
df.to_parquet(path=path)

ds = ray.data.read_parquet(path)
print(f"Number of blocks: {len(ds._block_num_rows())}")
df = ds.to_modin()
print(df)

df2 = pd.read_parquet(path)
print(df2)
```

### Issue Description

Please see the details in https://github.com/ray-project/ray/issues/37771 I have opened the issue in Ray originally but they are arguing that the issue lies with the `from_partitions` Modin function instead

### Expected Behavior

That the correct index is returned

### Error Logs

<details>

```python-traceback

Replace this line with the error backtrace (if applicable).

```

</details>

### Installed Versions

Ray 2.6
Modin 0.22.x and 0.23.x

**Comment by vnlitvinov** [comment]
To me it feels like a misunderstanding somewhere... in Modin code, I see that we're expecting partitions to contain the correct bits of indices, while Ray _might_ be expecting us to just re-build the index from scratch.

I wonder if @YarShev could add something here, as he was one of the main implementers of this API if I'm not mistaken...

**Comment by vnlitvinov** [comment]
@jaidisido 
As a workaround for now, I could suggest calling `df.reset_index(drop=True)` to reset the index on the dataframe returned by Ray's `.to_modin()`

**Comment by YarShev** [comment]
@vnlitvinov, you are right. The things work as expected on our end. I propose to close this issue and continue in https://github.com/ray-project/ray/issues/37771. Feel free to reopen.
