### ISSUE TITLE
Reason: 'lines' argument not supported how to resolve tis issue 

### ISSUE THREAD

**Issue by manjulac16** [modin-project/modin#6463]
a am trying to execute the code in modin ,but it is throwing an error as Reason: 'lines' argument not supported how to resolve tis issue

**Comment by anmyachev** [comment]
Hi @manjulac16! You have provided very little information for us to be able to help you.

I can assume that this is related to `read_json` function, which does not have a parallel implementation in Modin (when `lines==False`), and simply executes the code in pandas. However, in this case there should not be an error, but only a warning.

So the question is, do you need us to implement this case in Modin, or is there a bug you encountered (in the case, please provide a reproducer)?

**Comment by anmyachev** [comment]
@manjulac16 feel free to reopen if needed
