### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by solocazzimiei** [modin-project/modin#6475]
Since I'm new user of Modin/Dansk/Ray's fascinating tools. Need your help because I receive  error as in the object: 

> RuntimeError: dictionary changed size during iteration 

Here is the code:
```
import numpy as np
import pandas as pd
import polars as pl
import os
import ray
# ray.init(num_cpus=25, object_store_memory=75*1000*1024*1024)
ray.init()
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pdd

import dask.dataframe as dd
import dask.array as da
# import ray
# ray.init()
# import modin.pandas as pdd
# import modin as pdd
# pdd.config.Engine.put("Dask")
import matplotlib.pyplot as plt

ffm= pdd.read_csv(dir_base+'T_cvs\\'+tit_comp[0]+'.csv')
```
or whatever
`ff = [pdd.read_csv(dir_base+'Titoli_cvs\\'+k+'.csv') for k in tit_comp]
`
I finally need to fast concat several csv files loaded into a dataframe like this, using the "date" column as "outer" index join:   
`ffg = pdd.concat([ff for _ in range(len(ff))])`              
I work with win10 , winpython 3.10.8, ray 2.6.1,modin  0.23.0, 

Thanks for your help

**Comment by anmyachev** [comment]
Hi @solocazzimiei! Looks like a problem with installing packages.

First of all, I have seen the problem in the past https://github.com/modin-project/modin/issues/536. Maybe this comment can help you https://github.com/modin-project/modin/issues/536#issuecomment-480385889 if not, then I need a python traceback to figure it out. Could you show it?

**Comment by anmyachev** [comment]
@solocazzimiei feel free to reopen if needed
