### ISSUE TITLE
Equivalent of dask.dataframe.from_map?

### ISSUE THREAD

**Issue by zmbc** [modin-project/modin#6492]
dask.dataframe has an experimental function called [`from_map`](https://docs.dask.org/en/latest/generated/dask.dataframe.from_map.html). This allows the user to define a custom function for loading/creating partitions of a dataframe. Conceptually, I think this is similar to [Registering Custom Functions](https://github.com/modin-project/modin/blob/cf335c30758244309db9fc9e3f75c8f19618146f/examples/tutorial/jupyter/execution/pandas_on_ray/local/exercise_3.ipynb), except that it allows a function to **create** a DataFrame, rather than operate on an **existing** DataFrame.

This seems like it would be very useful to have in Modin; I don't see any straightforward way to achieve this currently. Am I missing something? I know that it would need to have some additional complexity that Dask doesn't have to worry about, in order to be general across storage formats and allow 2D partitioning, but these don't seem like insurmountable issues.

Any reactions to the utility and/or feasibility of this feature?

**Comment by anmyachev** [comment]
@zmbc I think it's quite similar to what `from_partitions` function does.

https://github.com/modin-project/modin/blob/29d9da056a4e4766314c4ae9ea62b33e0d52e662/modin/distributed/dataframe/pandas/partitions.py#L129-L136

Example:
```python
import pandas as pd
from modin.distributed.dataframe.pandas import from_partitions

import ray
ray.init(num_cpus=4)

partitions = list(map(lambda number: ray.put(pd.DataFrame([number])), [0, 1, 2]))

modin_df = from_partitions(partitions, axis=0)
```

**Comment by zmbc** [comment]
Thanks! That's helpful, but it does require me to interact directly with the underlying engine (Ray in your example). That's kind of a pain when I want to write code that will work with any Modin engine.

**Comment by anmyachev** [comment]
> Thanks! That's helpful, but it does require me to interact directly with the underlying engine (Ray in your example). That's kind of a pain when I want to write code that will work with any Modin engine.

Indeed too many low level details for end user. Looks like this functionality can be useful and we can try to implement it. Thanks for the idea @zmbc!

cc @modin-project/modin-core in case you have any more thoughts about that.
