### ISSUE TITLE
pivot_table is not supported :-(

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#65]
Opening this to track https://github.com/ray-project/ray/issues/2206

cc @chanansh

**Comment by devin-petersohn** [comment]
Hi @ryanpeach thanks for posting!

Currently we are defaulting to pandas for `pivot_table`. Are you having performance issues with pandas for this operation?

**Comment by chanansh** [comment]
Pivot is a heavy operation, especially with big data and can be
distributed. See spark.

**Comment by devin-petersohn** [comment]
I understand @chanansh, it comes down to how to prioritize new features with the engineering resources available.

If you're interested in getting involved, feel free to submit a PR for this or any issue. If you know the internals of Spark, you will already have a good idea on how to implement a pivot.

**Comment by ryanpeach** [comment]
My error had something to do with being unable to do a reindex during a pivot operation. I dont really have time to debug so I just switched back to pandas for now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by devin-petersohn** [comment]
Duplicate of #1200
