### ISSUE TITLE
BUG: no module named 'botocore' when using modin.pandas.read_csv with fsspec url

### ISSUE THREAD

**Issue by datth4** [modin-project/modin#6519]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd

pd.read_csv("myprotocol://file_path")
```

### Issue Description

There is no 'botocore' library when reading CSV file using fsspec url.

### Expected Behavior

Should add 'botocore' library to requirement file

### Error Logs

from botocore.exceptions import (
    255     NoCredentialsError,
    256     EndpointConnectionError,
    257     ConnectTimeoutError,
    258 )
    260 if storage_options is not None:
    261     new_storage_options = dict(storage_options)

ModuleNotFoundError: No module named 'botocore'
<img width="548" alt="Screenshot 2023-08-29 at 11 37 42" src="https://github.com/modin-project/modin/assets/50819157/f9f6c8b8-51cf-4c18-9cdb-fec51fc44702">

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 26ce87547e327ad129ca1d75dc9102bf9d5cb77c
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.6.0
Version          : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.20.0+46.g26ce8754.dirty
ray              : 2.5.1
dask             : None
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.3
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.1.2
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 1.0.9
fastparquet      : 2023.7.0
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2023.3

**Comment by dchigarev** [comment]
@anmyachev, shouldn't botocore be automatically installed even after #6496?

**Comment by anmyachev** [comment]
> @anmyachev, shouldn't botocore be automatically installed even after #6496?

Depends on how to install. In development environment `botocore` is installed.

If you install via pip, then this package is not installed by default.

@datth4 thanks for the issue!

Modin and pandas both treat this dependency as optional. Now pandas is throwing the following exception (if `fsspec` is installed):
```python
pd.read_csv("s3://noaa-ghcn-pds/csv/1788.csv")  # ImportError: Install s3fs to access S3
```

Modin after https://github.com/modin-project/modin/pull/6521 is merged will throw the same exception.
