### ISSUE TITLE
BUG: reading 1 GB on intel devcloud jupyter notebook 94 GB RAM crashes server

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#6539]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

follow the steps here: https://stackoverflow.com/questions/77025510/intel-server-unavailable-after-executing-the-code?noredirect=1#comment135796503_77025510

**How to Reproduce this?**

1. https://devcloud.intel.com/oneapi/
2. click on Getting Started tab.
3. Go down and Click on launch JupyterLab. (It is like Google Colab or Kaggle Notebooks)
4. Create ipynb and use wget to download this data: `!wget https://s3-ap-southeast-1.amazonaws.com/he-public-data/datasetab75fb3.zip`
5. read_csv() from zip file

**System Information**
OS - Linux 90-Ubuntu 5.4.0-80-generic
CPU - Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
RAM - 188 GB

### Issue Description

pandas reads the CSV without crashing. trying to read the CSV with modin seems to crash the notebook.

### Expected Behavior

modin should be able to read the CSV.

### Error Logs

N/A

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b5545c686751f4eed6913f1785f9c68f41f4e51d
python           : 3.9.16.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-80-generic
Version          : #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.23.1
ray              : 2.6.3
dask             : None
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 2.0.3
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.35
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.14.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.9.0
gcsfs            : None
matplotlib       : 3.7.2
numba            : 0.57.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 13.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : 0.19.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by mvashishtha** [comment]
@anmyachev @YarShev @dchigarev has anyone seen this kind of failure before in an intel devcloud jupyter notebook? I Can read the CSV with modin on ray on my mac: 

- MacBook Pro (16-inch, 2019)
- Processor: 2.3 GHz 8-core intel core i9
- Memory: 16 GB 2667 MHz DDR4

**Comment by mvashishtha** [comment]
There are some updates here: https://community.intel.com/t5/Intel-oneAPI-Data-Analytics/Intel-Server-Unavailable-after-executing-this-code/m-p/1521559/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExNOUNNQ0VZUkQ5MlpPfDE1MjE1NTl8U1VCU0NSSVBUSU9OU3xoSw#M970

**Comment by anmyachev** [comment]
> @anmyachev @YarShev @dchigarev has anyone seen this kind of failure before in an intel devcloud jupyter notebook? 

No

> There are some updates here: https://community.intel.com/t5/Intel-oneAPI-Data-Analytics/Intel-Server-Unavailable-after-executing-this-code/m-p/1521559/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExNOUNNQ0VZUkQ5MlpPfDE1MjE1NTl8U1VCU0NSSVBUSU9OU3xoSw#M970

At the moment there is nothing that we can do from the open source side. For now we can rely on technical support on community.intel.com, I think.

cc @Garra1980

**Comment by Garra1980** [comment]
there is a way to read it, check https://community.intel.com/t5/Intel-oneAPI-Data-Analytics/Intel-Server-Unavailable-after-executing-this-code/m-p/1531256/highlight/true#M987

**Comment by anmyachev** [comment]
@Garra1980 I guess there's nothing more we can do here. Should we close it?

**Comment by anmyachev** [comment]
Stackoverflow has an answer to the problem.
