### ISSUE TITLE
BUG: read_parquet with filters doesn't handle indices correctly

### ISSUE THREAD

**Issue by zmbc** [modin-project/modin#6540]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas
import pyarrow.dataset as ds

my_data = pandas.DataFrame({'a': range(10), 'b': range(10, 20)})

import pyarrow as pa

ds.write_dataset(pa.Table.from_pandas(my_data), './test_parquet_multiple_files/', format='parquet', max_rows_per_group=2, max_rows_per_file=3)

import modin.pandas as mpd

df = mpd.read_parquet(
    './test_parquet_multiple_files/',
    filters=[('a', '>=', 1)],
)
print(df)
```

### Issue Description

This is a bug in my own contribution in #6442.

The current implementation assumes that if the dataframe has a RangeIndex, each partition will have a RangeIndex. However, this is not the case if a single partition contains chunks from multiple files -- the index will restart, and therefore become a regular integer index.

### Expected Behavior

```python-console
>>> pandas.read_parquet('./test_parquet_multiple_files/', filters=[('a', '>=', 1)])
   a   b
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
5  6  16
6  7  17
7  8  18
8  9  19
```

A normal RangeIndex is created.

### Error Logs

<details>

```python-traceback

Traceback (most recent call last):
  File "~/src/modin/test_parquet.py", line 20, in <module>
    df = mpd.read_parquet(
  File "~/src/modin/modin/utils.py", line 475, in wrapped
    return func(*params.args, **params.kwargs)
  File "~/src/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "~/src/modin/modin/pandas/io.py", line 297, in read_parquet
    query_compiler=FactoryDispatcher.read_parquet(
  File "~/src/modin/modin/core/execution/dispatching/factories/dispatcher.py", line 195, in read_parquet
    return cls.get_factory()._read_parquet(**kwargs)
  File "~/src/modin/modin/core/execution/dispatching/factories/factories.py", line 213, in _read_parquet
    return cls.io_cls.read_parquet(**kwargs)
  File "~/src/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "~/src/modin/modin/core/io/file_dispatcher.py", line 159, in read
    query_compiler = cls._read(*args, **kwargs)
  File "~/src/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "~/src/modin/modin/core/io/column_stores/parquet_dispatcher.py", line 725, in _read
    return cls.build_query_compiler(
  File "~/src/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "~/src/modin/modin/core/io/column_stores/parquet_dispatcher.py", line 601, in build_query_compiler
    index, sync_index = cls.build_index(
  File "~/src/modin/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "~/src/modin/modin/core/io/column_stores/parquet_dispatcher.py", line 563, in build_index
    start = index_objs[0].start
AttributeError: 'Index' object has no attribute 'start'. Did you mean: 'sort'?

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.4.0-135-generic
Version             : #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.0
numpy               : 1.25.1
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.0
hypothesis          : None
sphinx              : 7.1.0
blosc               : None
feather             : 0.4.1
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : None
psycopg2            : 2.9.6
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : 2022.12.0
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : 3.7.2
numba               : None
numexpr             : 2.8.4
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : 0.15.0
pyarrow             : 12.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : 2023.6.0
scipy               : 1.11.1
sqlalchemy          : 1.4.45
tables              : 3.8.0
tabulate            : None
xarray              : None
xlrd                : 2.0.1
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.3.1
pyqt5               : None

</details>

**Comment by zmbc** [comment]
By the way, with regard to the expected behavior, from a bit of investigation I have determined that the two parquet engines, pyarrow and fastparquet, behave a little differently with respect to the `step` attribute of the RangeIndex.

```python
import pandas
import pyarrow.dataset as ds

my_data = pandas.DataFrame({'a': range(10), 'b': range(10, 20)})
# Non-default step
my_data.index = my_data.index * 2

import pyarrow as pa
ds.write_dataset(pa.Table.from_pandas(my_data), './test_parquet_multiple_files_step/', format='parquet', max_rows_per_group=2, max_rows_per_file=3)

print('With pyarrow:')
print(pandas.read_parquet('./test_parquet_multiple_files_step/', filters=[('a', '>=', 4)]))

print('With fastparquet:')
print(pandas.read_parquet('./test_parquet_multiple_files_step/', filters=[('a', '>=', 4)], engine="fastparquet"))
```

outputs:

```
With pyarrow:
   a   b
0  4  14
1  5  15
2  6  16
3  7  17
4  8  18
5  9  19
With fastparquet:
    a   b
0   3  13
2   4  14
4   5  15
6   6  16
8   7  17
10  8  18
12  9  19
```

That is, they both start the RangeIndex at 0 regardless of filters, but fastparquet preserves the step, while any filters in pyarrow reset the step to 1. Is this a quirk that Modin would want to replicate in its `read_parquet` method?

Without filters, of course, they both preserve `step`. Also note that the different numbers of rows in the outputs is a known difference: fastparquet does not implement filtering within a row group.

**Comment by vnlitvinov** [comment]
@zmbc thanks for reporting! Would you be able to work on a fix for that, too?


> Is this a quirk that Modin would want to replicate in its `read_parquet` method?

Modin strives to be 100%-compatible with pandas, so we should try to replicate whatever quirks pandas has, unless it's too burdensome...

**Comment by zmbc** [comment]
@vnlitvinov Yes, I will work on a fix. It turns out that fastparquet and pyarrow have one additional quirk with regard to indices, but it shouldn't be too much of a burden to get the exact same behavior.
