### ISSUE TITLE
BUG: read_csv with `iterator=True` throws AttributeError

### ISSUE THREAD

**Issue by SiRumCz** [modin-project/modin#6553]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
df_iter = pd.read_csv('path/to/file.csv', iterator=True)
```

### Issue Description

`AttributeError: 'TextFileReader' object has no attribute 'columns'`

### Expected Behavior

returns TextFileReader.

### Error Logs

<details>

```python-traceback
...
venv/lib/python3.10/site-packages/modin/core/io/text/text_file_dispatcher.py", line 1062, in _read    
    column_names = pd_df_metadata.columns
AttributeError: 'TextFileReader' object has no attribute 'columns'

```

</details>

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : b5545c686751f4eed6913f1785f9c68f41f4e51d
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.23.1
ray              : 2.6.3
dask             : None
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 2.0.3
numpy            : 1.25.2
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 59.6.0
pip              : 23.2.1
Cython           : None
pytest           : 7.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.9.0
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 13.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>

</details>

**Comment by anmyachev** [comment]
Thanks @SiRumCz! I can reproduce the problem.
