### ISSUE TITLE
alteranative for iloc,loc,at,iat in loop? 

### ISSUE THREAD

**Issue by SiRumCz** [modin-project/modin#6555]
I need to access the data in both current row and next row, and my original code worked relatively fast, but when I switched to modin, this seem to be significantly slower comparing to pandas, especially when I am looping through dataframe. Here's an example to show how slow it is comparing to pandas:

```py
import time
import numpy as np
import modin.pandas as pd

df = pd.DataFrame(np.zeros(shape=(1000, 3)), columns=['a', 'b', 'c'])

_df = df._to_pandas()
st = time.time()
for i in _df.index[:-1]:
    _curr = _df.iloc[i]
    _next = _df.iloc[i+1]
    # do something...
print('--- %s sec' % str(time.time()-st)) # --- 0.023520231246948242 sec

st = time.time()
for i in df.index[:-1]:
    _curr = df.iloc[i]
    _next = df.iloc[i+1]
    # do something...
print('--- %s sec' % str(time.time()-st)) # --- 2.2935643196105957 sec
```

And this gets worse pretty fast. I am wondering how can I optimize my code to works with modin.

**Comment by noloerino** [comment]
Thanks for the question @SiRumCz. `iloc` comes with a fair bit of internal overhead in modin, so here's a couple suggestions I can think of to help:

1. Perform 1 fewer iloc call per iteration by reusing a temporary variable, like so:
```python3
_curr = df.iloc[0]
_next = df.iloc[1]
for i in df.index[2:-1]:
    _curr, _next = _next, df.iloc[i]
    # do something...
```

2. Use a [rolling window function](https://pandas.pydata.org/docs/reference/api/pandas.core.window.rolling.Rolling.apply.html):
```
df.rolling(2).apply(lambda s: ...) # do something in this function
```

**Comment by SiRumCz** [comment]
@noloerino thanks for the reply, the first solution will definitely help reduce the time but I think it will still struggle with the data size I have. I will have to read a bit more about the rolling window, appreciate it!

**Comment by noloerino** [comment]
Happy to help. In general, modin performance has some trouble with explicit for-loop iteration, and it's better to use tricks like window functions + `df.apply` if you're able to rewrite your code to support it.

I'm closing this issue for now, feel free to reopen if you have further questions.
