### ISSUE TITLE
BUG: TypeError: BasePandasDataset.reset_index() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by SiRumCz** [modin-project/modin#6580]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [ ] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas as pd


def find_group_name(df):
    return df.name


df = pd.DataFrame({'id': ['a','a','b','b','b'], 'val': [1,2,3,4,5]})
print(df.groupby('id').apply(find_group_name).reset_index(name='group'))


import modin.pandas as pd
import ray


ray.init(num_cpus=4, include_dashboard=False, runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})


df = pd.DataFrame({'id': ['a','a','b','b','b'], 'val': [1,2,3,4,5]})
print(df.groupby('id').apply(find_group_name).reset_index(name='group'))
```

### Issue Description

getting error message:
`TypeError: BasePandasDataset.reset_index() got an unexpected keyword argument 'name'`

### Expected Behavior

`name` should be recognized since it is a param in `Series.reset_index()`[https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.Series.reset_index.html]

### Error Logs

<details>

```python-traceback

  id group
0  a     a
1  b     b
2023-09-18 11:34:30,267 INFO worker.py:1621 -- Started a local Ray instance.
UserWarning: Distributing <class 'dict'> object. This may take some time.
Traceback (most recent call last):
  File "/mnt/d/xxx/test.py", line 20, in <module>
    print(df.groupby('id').apply(find_group_name).reset_index(name='group'))
  File "/mnt/d/xxx/venv/lib/python3.10/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
TypeError: BasePandasDataset.reset_index() got an unexpected keyword argument 'name'

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b5545c686751f4eed6913f1785f9c68f41f4e51d
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.23.1
ray              : 2.6.3
dask             : None
distributed      : None
hdk              : None

pandas dependencies
-------------------
pandas           : 2.0.3
numpy            : 1.25.2
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 59.6.0
pip              : 23.2.1
Cython           : None
pytest           : 7.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.9.0
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 13.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by vnlitvinov** [comment]
I can reproduce this, and some small digging shows that the cause for the issue is that `df.groupby('id').apply(find_group_name)` returns a `Series` in pandas but `DataFrame` in Modin. Still need to figure out why, though... cc @dchigarev

**Comment by dchigarev** [comment]
the root cause might be similar to #5763

**Comment by SiRumCz** [comment]
@vnlitvinov @dchigarev thank both of you for the input, indeed in my case pandas returns Series instead of DataFrame.

**Comment by SiRumCz** [comment]
This issue seems to be resolved.
