### ISSUE TITLE
Weird behaviors when performing an apply function on a DataFrame

### ISSUE THREAD

**Issue by SiRumCz** [modin-project/modin#6596]
Hi Dev team, 

The code I am trying to do is: `df.apply(lambda x,sep: sep.join[item.as_string() for item in x['items']], sep='--', axis=1)`, while it works fine when I use Ray with ONLY the head node (i.e., single server), I will be getting error below if I have additional raylets:
```
RayTaskError(TypeError): ray::apply_list_of_funcs()
    partitiion = func(partition, *args, **kwargs)
TypeError: `NoneType` object is not callable
```

And the weird thing is, I added three lines of `logger.debug()` just to check if my data are not containing any empty data, all of the sudden, the code can be finished without any error. 

However, it generates a couple of warning messages (presumably from Ray) which I think is relevant to the issue:
```
WARNING: 136 PYTHON worker processes have been started on node: xxx with address: xxx. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds)
WARNING: 148 PYTHON worker processes have been started on node: xxx with address: xxx. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds)
WARNING: 178 PYTHON worker processes have been started on node: xxx with address: xxx. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds)
```

I am still checking that discussions, but I would also like to seek some advices from you guys. Have a nice weekend.

**Comment by SiRumCz** [comment]
@zmbc the task that caused error was rather simple, I just want to convert the values in one of my columns from tuple of objects to string format.

I also checked your issue in #6594, I couldn't reproduce the error from your code, however, it was somewhat similar to my original code where I need to pass in variables from variables defined outside of the `apply()`, but I still got the error even I have defined the function with those variables as the parameters.

From my observation, the problem seems to be caused from the transfer of my apply function to raylet, it could be because my objects are rather complex and may have referenced data that raylet couldn't find.

To this point, I have to use the vanilla pandas to continue my task because I couldn't trust that these three lines of logging are the fix to my problem.

**Comment by zmbc** [comment]
> I couldn't make a simple reproducible code that can get to me this error, which is why I can't tell if it's problem on my end or Modin's and Ray's.

Yes, you'll need to make a reproducible example to helpfully report a bug here, or for someone to be able to help you. If you're not willing to do that, you're probably on your own.

> I have to use the vanilla pandas

If your data is small enough that using vanilla pandas is feasible, that works!

**Comment by anmyachev** [comment]
It seems very likely that modin objects are closured in lambda, which once again initializes ray in worker processes, which leads to strange errors. Fixing https://github.com/modin-project/modin/issues/6594 may help here also.

**Comment by SiRumCz** [comment]
@anmyachev I believe it is a problem on my end, after I refactored my original code, I can run without any issue. Closing this issue.
