### ISSUE TITLE
BUG: .diff() does not work on modin.pandas.groupby.DataFrameGroupBy object

### ISSUE THREAD

**Issue by dromare** [modin-project/modin#6628]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
# Create Pandas DataFrame
import numpy as np
import pandas as pd

np.random.seed(1066)
dates = pd.date_range(start='2023-01-01', periods=10, freq='W')
df1 = pd.DataFrame({'date': dates,
                   'group': 'A',
                   'value': np.random.randint(0, 100, size=len(dates))
                  })
df2 = pd.DataFrame({'date': dates,
                    'group': 'B',
                    'value': np.random.randint(0, 100, size=len(dates))
                  })
pd_df = pd.concat([df1,df2], ignore_index=True)

droplist = [1,2,3,6,7,13,15,17,18]
pd_df = pd_df.drop(droplist).reset_index(drop=True)

# Test .diff() function
print(pd_df['date'].diff())
print(pd_df[['group', 'date']].sort_values(by=['group', 'date']).groupby('group').diff())

# Repeat above with Modin DataFrame

import modin.pandas as modin_pd
import ray
ray.init()

modin_df = modin_pd.DataFrame(pd_df)

print(modin_df['date'].diff())
print(modin_df[['group', 'date']].sort_values(by=['group', 'date']).groupby('group').diff())
```

### Issue Description

.diff() works as expected on both pandas.core.series.Series and modin.pandas.series.Series objects, giving following result (issue with Modin series was reported in #6402 and resolved in #6403):

0         NaT
1     28 days
2      7 days
3     21 days
4      7 days
5    -63 days
6      7 days
7      7 days
8     14 days
9     14 days
10    21 days
Name: date, dtype: timedelta64[ns]

However, .diff() works as expected on pandas.core.groupby.generic.DataFrameGroupBy object but not on modin.pandas.groupby.DataFrameGroupBy object.

### Expected Behavior

# Expected output with modin_df DataFrame (actual output from pd_df DataFrame):
print(modin_df[['group', 'date']].sort_values(by=['group', 'date']).groupby('group').diff())

      date
0      NaT
1  28 days
2   7 days
3  21 days
4   7 days
5      NaT
6   7 days
7   7 days
8  14 days
9  14 days
10 21 days

### Error Logs

<details>

```python-traceback

File /usr/local/lib/python3.10/site-packages/modin/pandas/groupby.py:1427, in DataFrameGroupBy.diff(self, periods, axis)
   1421     for col, dtype in self._df.dtypes.items():
   1422         # can't calculate diff on non-numeric columns, so check for non-numeric
   1423         # columns that are not included in the `by`
   1424         if not is_numeric_dtype(dtype) and not (
   1425             isinstance(self._by, BaseQueryCompiler) and col in self._by.columns
   1426         ):
-> 1427             raise TypeError(f"unsupported operand type for -: got {dtype}")
   1429 return self._check_index_name(
   1430     self._wrap_aggregation(
   1431         type(self._query_compiler).groupby_diff,
   (...)
   1436     )
   1437 )

TypeError: unsupported operand type for -: got datetime64[ns]

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 4c01f6464a1fb7a201a4e748c7420e5cb41d16ce
python              : 3.10.11.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 4.19.128-microsoft-standard
Version             : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine             : x86_64
processor           : 
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

Modin dependencies
------------------
modin               : 0.24.1
ray                 : 2.7.0
dask                : None
distributed         : None
hdk                 : None

pandas dependencies
-------------------
pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 65.5.1
pip                 : 23.0.1
Cython              : None
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by Garra1980** [comment]
thanks for the detailed reproducer! Indeed, I reproduce that TypeError, will take a look
