### ISSUE TITLE
Cannot read local csv file with remote ray clusters

### ISSUE THREAD

**Issue by SiRumCz** [modin-project/modin#6634]
I have below env vars
```sh
export MODIN_EXPERIMENTAL_GROUPBY=True
export MODIN_RAY_CLUSTER=True
export RAY_ADDRESS="ray://xx.xxx.xxx.xxx:10001"
```

and when I run below code, it will give me `FileNotFoundError`:
```py
fpath = "sample.csv" # relative path, same parent dir as the script

import pandas
import modin.pandas as mpd

df = pandas.read_csv(fpath) # no error
mdf = pd.read_csv(fpath) # FileNotFoundError: [Errno 2] No such file or directory: <full path of the file> the parent dir is the path of the ray node.
```

but if I unset both `MODIN_RAY_CLUSTER` and `RAY_ADDRESS`, a local ray instance will be created and file will be loaded without an error. Could anyone confirm if this is a bug, or I am using it wrong, how can I load it without first load into local vanilla pandas dataframe.

I also tried things like:
1. upload the file to server and parse the path to be the absolute path of that file in the server, still getting FileNotFoundError
2. unset the RAY env vars and init ray inside of the script with the address, still same error

I am using modin@0.23.1 because I need to use it on python 3.8, and my machine that calls the script is a WSL2 on Win 11, and my ray clusters are on ubuntu LTS 22.04.

**Comment by Garra1980** [comment]
Yes, this is expected, some details can be found eg here - https://github.com/modin-project/modin/issues/3179

**Comment by SiRumCz** [comment]
@Garra1980 thank you, after making file available to all workers (including) my local machine, read_csv will work. But to be honest, I was expecting Modin can read my local file and distribute into DataFrame automatically, wonder if that can be made as a future feature.
