### ISSUE TITLE
Should we use `@lazy_metadata_decorator` for `ModinDataFrame.finalize`?

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6664]
https://github.com/modin-project/modin/blob/112afb6fb455beec67c9ded6f42ffbf378bbbf79/modin/core/dataframe/pandas/dataframe/dataframe.py#L4100

**Comment by dchigarev** [comment]
my opinion is yes, `.finalize()` should propagate deferred indices as it's also some kind of form of lazy computations
