### ISSUE TITLE
PERF: Use lazy_map_partitions() for dtypes conversion

### ISSUE THREAD

**Issue by AndreyPavlenko** [modin-project/modin#6694]
The code below is ~6 times faster if `lazy_map_partitions()` is used by `astype()`.

```python
import timeit
import modin.pandas as pd
import ray

ray.init()

df = pd.DataFrame({i: range(1000) for i in range(100)})
def test():
    for c in df.columns:
        df[c] = df[c].astype(float)
    df.shape
time = timeit.timeit(test, number=1)
print(f"Time: {time}")
```

**Comment by anmyachev** [comment]
@AndreyPavlenko what if instead `df.shape` use `modin.utils.execute`?

**Comment by AndreyPavlenko** [comment]
> @AndreyPavlenko what if instead `df.shape` use `modin.utils.execute`?

In this case, the difference is not significant, however the number of remote calls is 2x less if lazy_map_partitions() is used.

**Comment by AndreyPavlenko** [comment]
Btw, on a 12 cpu machine, there are 1200 partitions and, thus, it results in 1200 remote calls.
