### ISSUE TITLE
Can't install Modin with Python 3.7

### ISSUE THREAD

**Issue by frreiss** [modin-project/modin#67]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **Modin installed from (source or binary)**: Both
- **Modin version**: 0.1.1 and HEAD
- **Python version**: 3.7.0
- **Exact command to reproduce**: pip install modin

### Describe the problem
Modin currently depends on Pandas 0.22, which depends on a version of Numpy that won't compile against Python 3.7. I had to downgrade my system Python from 3.7 to 3.6 to install Modin (i.e. `brew switch python 3.6.5`). If you could upgrade to the latest version of Pandas and add a Python 3.7 build, it would save others from having to figure out this workaround.

**Comment by devin-petersohn** [comment]
Thanks for posting this @frreiss. We are currently in the process of upgrading the Pandas version.

We depend on Ray, and it also does not have a distribution for Python 3.7. cc @robertnishihara

**Comment by robertnishihara** [comment]
Ray now supports 3.7 (these won't be on PyPI until the next release, but the nightly wheels support 3.7).

**Comment by SouparnaD** [comment]
Modin can't install Ray still, python 3.7.3.  This the issue:

Collecting ray==0.6.6 (from modin)
  Could not find a version that satisfies the requirement ray==0.6.6 (from modin) (from versions: )
No matching distribution found for ray==0.6.6 (from modin)

**Comment by devin-petersohn** [comment]
Hi @SouparnaD, please see #611, this is likely not a Python 3.7 issue, rather a Windows issue. Let's continue the conversation there since Modin does support python 3.7.
