### ISSUE TITLE
Modin objects are not able to be pickled

### ISSUE THREAD

**Issue by wsf1990** [modin-project/modin#672]
```
File ".../site-packages/cache_memoize/__init__.py", line 116, in inner
    result = cache.get(cache_key, MARKER)
  File ".../site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File ".../site-packages/django_redis/cache.py", line 81, in get
    client=client)
  File ".../site-packages/django_redis/client/default.py", line 210, in get
    return self.decode(value)
  File ".../site-packages/django_redis/client/default.py", line 318, in decode
    value = self._serializer.loads(value)
  File ".../site-packages/django_redis/serializers/pickle.py", line 35, in loads
    return pickle.loads(value)
  File ".../site-packages/modin/pandas/base.py", line 3337, in __getattribute__
    if self.empty and is_callable:
  File ".../site-packages/modin/pandas/base.py", line 3343, in __getattribute__
    return object.__getattribute__(self, item)
  File ".../site-packages/modin/pandas/dataframe.py", line 211, in empty
    return len(self.columns) == 0 or len(self.index) == 0

  File ".../site-packages/modin/pandas/dataframe.py", line 131, in _get_columns
    return self._query_compiler.columns
  File ".../site-packages/modin/pandas/dataframe.py", line 1898, in __getattr__
    if key in self.columns:
  File ".../site-packages/modin/pandas/base.py", line 3343, in __getattribute__
    return object.__getattribute__(self, item)

#  ... So many times!

  File ".../site-packages/modin/pandas/dataframe.py", line 131, in _get_columns
    return self._query_compiler.columns
  File ".../site-packages/modin/pandas/base.py", line 3343, in __getattribute__
    return object.__getattribute__(self, item)
RecursionError: maximum recursion depth exceeded while calling a Python object
```
 I use django-cache to cache the result of modin df, When django want to fetch the cache,It hit this issue.

**Comment by devin-petersohn** [comment]
This is a serialization issue. Right now Modin objects cannot be pickled, which is where the error is coming from. The main thing needed here is the ability to pickle Modin objects.

Our backlog is quite packed at the moment, so I will put as Help Wanted. Please let me know if you are interested in contributing.

**Comment by wsf1990** [comment]
I'll be very glad.Please let me know what can I do.

**Comment by devin-petersohn** [comment]
Thanks @wsf1990, this is a large undertaking because I don't believe that Ray ObjectIDs are able to be pickled. 

@simon-mo Do you run into this in Ray Serve?

**Comment by simon-mo** [comment]
@devin-petersohn ray.ObjectID can be pickled:
```python
In [9]: pickle.dumps(ray.ObjectID(b'1'*20))
Out[9]: b'\x80\x03cray._raylet\nObjectID\nq\x00C\x1411111111111111111111q\x01\x85q\x02Rq\x03.'
```

This seems like some getting `self.columns` issues in `modin/pandas` because the error messages loop through:
```py3
File ".../site-packages/modin/pandas/base.py", line 3343, in __getattribute__
  return object.__getattribute__(self, item)
File ".../site-packages/modin/pandas/dataframe.py", line 211, in empty
  return len(self.columns) == 0 or len(self.index) == 0
File ".../site-packages/modin/pandas/dataframe.py", line 131, in _get_columns
  return self._query_compiler.columns
File ".../site-packages/modin/pandas/dataframe.py", line 1898, in __getattr__
  if key in self.columns:

[Again!]
File ".../site-packages/modin/pandas/base.py", line 3343, in __getattribute__
  return object.__getattribute__(self, item)
```

**Comment by jontis** [comment]
Not sure if this helps... dill also fails. Both pickle and dill fails on the unserialization, not on serialization.

dill.detect.errors(modin.pandas.DataFrame(data=['aaa']))
UserWarning: Distributing <class 'list'> object. This may take some time.
UserWarning: `DataFrame.__getstate__` defaulting to pandas implementation.
T4: <class 'modin.pandas.dataframe.DataFrame'>
# T4
D2: <dict object at 0x7f5f3f56f6e0>
T4: <class 'pandas.core.internals.managers.BlockManager'>
# T4
F2: <function _new_Index at 0x7f5fa37ea830>
# F2
T4: <class 'pandas.core.indexes.range.RangeIndex'>
# T4
D2: <dict object at 0x7f5f3f5737d0>
# D2
D2: <dict object at 0x7f5f37124280>
# D2
B3: <built-in function _reconstruct>
F2: <function _get_attr at 0x7f5f2f6cc200>
# F2
M2: <module 'numpy.core._multiarray_umath' from '/home/jonathan/miniconda3/envs/dhi/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so'>
F2: <function _import_module at 0x7f5f2f6cc320>
# F2
# M2
# B3
T4: <class 'numpy.ndarray'>
# T4
T4: <class 'numpy.dtype'>
# T4
D2: <dict object at 0x7f5f363e8c80>
# D2
D2: <dict object at 0x7f5f3f548eb0>
D2: <dict object at 0x7f5f2d2eabe0>
D2: <dict object at 0x7f5f3f548140>
Sl: slice(0, 1, 1)
T1: <class 'slice'>
F2: <function _load_type at 0x7f5f37eb1680>
# F2
# T1
# Sl
# D2
# D2
# D2
# D2
Out[89]: RecursionError('maximum recursion depth exceeded')


dill.detect.errors(modin.pandas.DataFrame())
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
UserWarning: `DataFrame.__reduce_ex__` for empty DataFrame defaulting to pandas implementation.
Out[90]: _pickle.PicklingError('args[0] from __newobj__ args has the wrong class')

**Comment by devin-petersohn** [comment]
Thanks @jontis, this does help. We're trying to just default to pandas, which the serializers still don't like.

Try this as a workaround. I tested it and it works:

```python
import modin.pandas as pd
import pickle

df = pd.DataFrame([1,2,3,4])
s = pickle.dumps(df._query_compiler)
df2 = pd.DataFrame(query_compiler=pickle.loads(s))
```

Let me know if this helps.

**Comment by jontis** [comment]
That does work.

**Comment by jontis** [comment]
Workaround for the caching:
from memoization import cached

@cached
def test_cache(in_df):
    ....

**Comment by wsf1990** [comment]
@jontis Thanks！You guys do a great job! I'll test it when I have time.

**Comment by anmyachev** [comment]
@vnlitvinov set estimate please

**Comment by devin-petersohn** [comment]
This was dropped, @vnlitvinov do you want to pick it back up? I think it is still high priority.

**Comment by vnlitvinov** [comment]
Yes, I still want to, but I don't know about if I could fit it in :)
That said, let's try and poke at it again.
