### ISSUE TITLE
ModuleNotFoundError: No module named 'modin.pandas.testing'

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6783]
This module is public and is used quite often.
It shouldn't be difficult to maintain, as it has a few functions:
```python
__all__ = [
    "assert_extension_array_equal",
    "assert_frame_equal",
    "assert_series_equal",
    "assert_index_equal",
]
```

**Comment by anmyachev** [comment]
Interest in this module: https://github.com/modin-project/modin/issues/4236

**Comment by YarShev** [comment]
@anmyachev, should we close the issues you linked above in the comment?

**Comment by anmyachev** [comment]
> @anmyachev, should we close the issues you linked above in the comment?

Both of them are closed now.
