### ISSUE TITLE
Consider to remove experimental `PyarrowOnRay` execution

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6812]
Some details:
* Pandas supports `pyarrow` as a backend for its objects, starting with version 2.0 (optional). Modin can reuse it for different engines (Dask, Ray, Unidist).
* Moreover, it is [planned](https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#pyarrow-will-become-a-required-dependency-with-pandas-3-0) to make `pyarrow` dependency required starting with version 3.0.
* Current testing of this execution is extremely sparse. At CI we ran only `TestCsv` tests (we're [skipping](https://github.com/modin-project/modin/blob/1a1e090032a187409515ce5697156a0716c4a599/modin/pandas/test/test_io.py#L257) even those tests right now).

@devin-petersohn your feedback here is especially valuable, as I recall it was implemented before many of us started developing Modin.

@modin-project/modin-core your feedback is also welcome

**Comment by dchigarev** [comment]
+1 on removing it
