### ISSUE TITLE
Allow pass-through to underlying pandas implementation

### ISSUE THREAD

**Issue by idantene** [modin-project/modin#6843]
We occasionally have the need to access underlying pandas DataFrame internals, i.e. attributes/functions prefixed with `_`, such as follows:

```python3
import pandas
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
dfp = pandas.DataFrame({"a": [1, 2], "b": [3, 4]})

df._info_axis_name

AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 df._info_axis_name

File .../site-packages/modin/pandas/dataframe.py:2489, in DataFrame.__getattr__(self, key)
   2487 if key not in _ATTRS_NO_LOOKUP and key in self.columns:
   2488     return self[key]
-> 2489 raise err

File .../site-packages/modin/pandas/dataframe.py:2485, in DataFrame.__getattr__(self, key)
   2467 """
   2468 Return item identified by `key`.
   2469 
   (...)
   2482 try to get `key` from ``DataFrame`` fields.
   2483 """
   2484 try:
-> 2485     return object.__getattribute__(self, key)
   2486 except AttributeError as err:
   2487     if key not in _ATTRS_NO_LOOKUP and key in self.columns:

AttributeError: 'DataFrame' object has no attribute '_info_axis_name'

dfp._info_axis_name
> 'columns'
```

It would be great if Modin could fallback to also internal attribute accessing (perhaps toggleable with some configuration?):

```python3
    @disable_logging
    def __getattr__(self, key):
        # docstring truncated
        try:
            return object.__getattribute__(self, key)
        except AttributeError as err:
            if key not in _ATTRS_NO_LOOKUP and key in self.columns:
                return self[key]
            try:  # If not a column name and not inherently supported by Modin, get raw pandas dataframe and get that attribute
                return getattr(self._to_pandas(), key)  # Or object.__getattribute(self._to_pandas(), key)?
            except:
                raise err
```

**Comment by YarShev** [comment]
Hi @idantene, thank you for opening this feature request. While your suggestion may work for simple cases, I think we should have proper testing for all cases to make sure that accesing pandas internals works with Modin. Also, if you need to access a pandas internal attribute, which just returns some metadata about a dataframe, conversion of a Modin dataframe to pandas one may harm performance. Could you repsond to a couple of questions I have?

1) Pandas has very extensive API, which I assume can provide you with necessary stuff to allow to do what you want. Are you able to use only public pandas API or you have the strong necessity to access pandas internals?
2) Can you provide a list of all pandas internals you want to access with Modin?

**Comment by idantene** [comment]
Thanks for the quick reply @YarShev!

Those are good questions. We have some use cases that must use pandas' internals, or otherwise we'd have to introduce some hard-coded values which will be subject to change.  
I don't have a full list of pandas' internals - I could look in our code base for those - and I think that following your line of thought (`proper testing for all cases to make sure that accesing pandas internals works with Modin`), a subset of these may not be enough.
I'd imagine a good starting point would be pandas own code ([dataframe](https://github.com/pandas-dev/pandas/blob/main/pandas/core/frame.py), [series](https://github.com/pandas-dev/pandas/blob/main/pandas/core/series.py)), and simply capturing any function/property that starts with a single underscore. What do you think?

As for the performance hit - I can see that. I think it would be acceptable, especially if this option would be a toggleable one which is off by default.

**Comment by YarShev** [comment]
> I'd imagine a good starting point would be pandas own code ([dataframe](https://github.com/pandas-dev/pandas/blob/main/pandas/core/frame.py), [series](https://github.com/pandas-dev/pandas/blob/main/pandas/core/series.py)), and simply capturing any function/property that starts with a single underscore. What do you think?

One of the problems with `capturing any function/property that starts with a single underscore` might be the attributes with the same names both in Modin and pandas but with different parameters and thus with different implementations (e.g., `_update_inplace`). Another problem is related to pandas specifics/internals like the attributes `_as_manager` or `_constructor_from_mgr`. Modin has its own manager of partitions. I think it is not clear for users to call such APIs and what parameters have to be passed in to those methods. Modin is a drop-in replacement for public pandas API, but not for pandas internals. I think we should either come up with a list of pandas internals attributes you want to use in your code base and try to implement those on Modin side or replace the use of pandas internals to public pandas API on your side.

**Comment by idantene** [comment]
Excellent points @YarShev (and happy new years!).

- `same names both in Modin and pandas` - I'd imagine in such cases, Modin takes priority, just as it does with other drop-in replacements.
- `Another problem is related to pandas specifics/internals like the attributes _as_manager or _constructor_from_mgr` - that does sound worrisome, to some extent, though I'd imagine if someone is aiming for the pandas' internals version of this, they _probably_ know what they want (i.e. they want pandas' partition manager). Would it not suffice to highlight that calling such underlying attributes materialize the data frame (i.e. call `self.to_pandas()`), so that these calls _would_ make sense? And of course, it's all the user's responsibility, since as you said, Modin is not a drop-in replacement for pandas internals.

I can definitely navigate this specific instance away (i.e. the one given as an example, `_info_axis_name`), but I'm certain I'll run into more such instances in the future.

With that, I think the question is more that, given that Modin also specifies `D stands for default to pandas` for public APIs, can we not offer the user a toggle-on setting to default/fallback to pandas with internal calls? It is essentially equal to [Defaulting to pandas](https://modin.readthedocs.io/en/latest/supported_apis/defaulting_to_pandas.html), but for internal API (with a default `off` setting).

```python3
import os
os.environ['MODIN_FALLBACK_INTERNALS'] = 'True'
import modin.pandas as pd

# Or
import modin.config
modin.config.InternalFallback.put(True)
import modin.pandas as pd
```

**Comment by YarShev** [comment]
@idantene, Happy New Year! Sorry for the delayed response.

> `same names both in Modin and pandas` - I'd imagine in such cases, Modin takes priority, just as it does with other drop-in replacements.

I think you are missing the important point in the phrase `same names both in Modin and pandas`, namely, Modin and pandas may have different definitions (same function names but different parameters) and implementations. If the user moves from pandas to Modin and Modin takes the priority, it may require passing different arguments and thus different result may get returned. This doesn't sound like drop-in replacement to me.

> `Another problem is related to pandas specifics/internals like the attributes _as_manager or _constructor_from_mgr` - that does sound worrisome, to some extent, though I'd imagine if someone is aiming for the pandas' internals version of this, they probably know what they want (i.e. they want pandas' partition manager). Would it not suffice to highlight that calling such underlying attributes materialize the data frame (i.e. call `self.to_pandas()`), so that these calls would make sense? And of course, it's all the user's responsibility, since as you said, Modin is not a drop-in replacement for pandas internals.

We shouldn't distinguish API into "very" pandas specific and "not very" pandas specific. From my perspective this can only bring complexity and difficulties in the design.

> With that, I think the question is more that, given that Modin also specifies D stands for default to pandas for public APIs, can we not offer the user a toggle-on setting to default/fallback to pandas with internal calls? It is essentially equal to [Defaulting to pandas](https://modin.readthedocs.io/en/latest/supported_apis/defaulting_to_pandas.html), but for internal API (with a default off setting).

Again, If we were to provide this toggle, we would get the issue I mentioned above in the first point. So, I don't really see a good way to support pandas internal APIs, which may also be unstable, btw. We can help you to rewrite your code to replace pandas internals usage, if it is possible at all and you don't mind sharing the code with us.

**Comment by YarShev** [comment]
Closing this issue as no plans on pushing it forward.
