### ISSUE TITLE
Rename `read_pickle_distributed/to_pickle_distributed` to ` read_pickle_glob/to_pickle_glob`

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6856]
For consistency with other functions like `read_csv_glob` and `read_parquet_glob`.

**Comment by npochhi** [comment]
Hi 👋, I'd like to work on this simple issue if it's alright with you.

**Comment by YarShev** [comment]
Hi @npochhi, it would be great if you could help us with this. Please note that this is not a simple renaming. We should also preserve backward compatibility for a few future Modin releases. You can open a PR where we discuss more.
