### ISSUE TITLE
Add Support for `pydantic` 2

### ISSUE THREAD

**Issue by achieveordie** [modin-project/modin#6916]
**Is your feature request related to a problem? Please describe.**
An explicit [restriction](https://github.com/modin-project/modin/issues/6336) was added to the requirements. However, `ray` seems to [support](https://github.com/ray-project/ray/blob/master/python/requirements.txt#L60) 2.5+ version of `pydantic`. Are there any more reasons to restrict it to 1.x?

Check out [this](https://github.com/ray-project/ray/commit/31c6631b8c5e098927c980aef195039c7f64fba0) commit which adds that functionality. It'll be really helpful if we could use `modin` with latest versions of `pydantic`.

**Comment by anmyachev** [comment]
Hi @achieveordie! I will try to unpin it.

**Comment by anmyachev** [comment]
@achieveordie Modin 0.27.0 (planning release date: 14 February) will not require `pydantic<2`.

**Comment by achieveordie** [comment]
Thanks! @anmyachev
