### ISSUE TITLE
read_sql says wrong syntax when pandas read_sql can work with the same syntax

### ISSUE THREAD

**Issue by qxlsz** [modin-project/modin#694]
read_sql says wrong syntax when pandas read_sql can work with the same syntax

**Comment by devin-petersohn** [comment]
Hi @qxlsz, thanks for the report.

Would you be able to include the syntax that you used that failed? We need more information to fix this issue. Thanks!

**Comment by TheCedarPrince** [comment]
Hey there! I can add to this discussion; I am having the same error using a postgres DB

Here is my code: 

```
import modin.pandas as pd
import psycopg2 
from sqlalchemy import create_engine

# Creates a sqlalchemy engine using for connecting to a local database.
engine = create_engine('postgresql+psycopg2://' +  # States DB config to use
                       'USERNAME:' +  # <Username>: for DB
                       'PASSWORD' +  # Password for DB
                       '@HOSTNAME/' +  # @<Hostname>
                       'step_count')  # Table in DB

# Points to DB to write information.
conn = engine.raw_connection()
cur = conn.cursor()

test = pd.read_sql("select * from step_count", conn)

print(test.head())
```

Which should yield something like this: 

```
   device                  startDate                    endDate  value
0  iPhone  2017-08-15 16:08:43 -0600  2017-08-15 16:18:41 -0600     52
1  iPhone  2017-08-15 16:18:41 -0600  2017-08-15 16:26:50 -0600     14
2  iPhone  2017-08-15 16:26:50 -0600  2017-08-15 16:31:29 -0600     62
3  iPhone  2017-08-15 17:02:47 -0600  2017-08-15 17:09:51 -0600      8
4  iPhone  2017-08-15 17:10:26 -0600  2017-08-15 17:17:48 -0600     58
```

But instead gives me a traceback like this: 

```
WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
2019-06-22 11:50:00,398 INFO node.py:497 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-22_11-50-00_398163_30350/logs.
2019-06-22 11:50:00,505 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:36687 to respond...
2019-06-22 11:50:00,622 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:32668 to respond...
2019-06-22 11:50:00,625 INFO services.py:806 -- Starting Redis shard with 1.65 GB max memory.
2019-06-22 11:50:00,643 INFO node.py:511 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-22_11-50-00_398163_30350/logs.
2019-06-22 11:50:00,651 WARNING services.py:1318 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 3708985344 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
2019-06-22 11:50:00,652 INFO services.py:1441 -- Starting the Plasma object store with 4.0 GB memory using /tmp.
2019-06-22 11:50:00,670 WARNING services.py:909 -- Failed to start the reporter. The reporter requires 'pip install psutil'.
Traceback (most recent call last):
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/io/sql.py", line 1431, in execute
    cur.execute(*args)
psycopg2.ProgrammingError: subquery in FROM must have an alias
LINE 1: SELECT COUNT(*) FROM (select * from step_count)
                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stepcount_query.py", line 16, in <module>
    test = pd.read_sql("select * from step_count", conn)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/modin/pandas/io.py", line 324, in read_sql
    return DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/modin/data_management/factories.py", line 155, in read_sql
    return cls._determine_engine()._read_sql(**kwargs)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/modin/data_management/factories.py", line 159, in _read_sql
    return cls.io_cls.read_sql(**kwargs)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/modin/engines/ray/generic/io.py", line 802, in read_sql
    row_cnt = pandas.read_sql(row_cnt_query, con).squeeze()
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/io/sql.py", line 380, in read_sql
    chunksize=chunksize)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/io/sql.py", line 1468, in read_query
    cursor = self.execute(*args)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/io/sql.py", line 1445, in execute
    raise_with_traceback(ex)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/compat/__init__.py", line 420, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/src/Programs/miniconda3/envs/oh2/lib/python3.5/site-packages/pandas/io/sql.py", line 1431, in execute
    cur.execute(*args)
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT COUNT(*) FROM (select * from step_count)': subquery in FROM must have an alias
LINE 1: SELECT COUNT(*) FROM (select * from step_count)
                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

Right now I am having to revert back to vanilla pandas - any thoughts about what is happening? 

Let me know if you need more info.

P.S. Here are the results of my pip freeze: 

```
asn1crypto==0.24.0
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
bcrypt==3.1.6
bleach==3.1.0
bokeh==1.2.0
certifi==2018.8.24
cffi==1.12.3
cli-helpers==1.2.1
Click==7.0
colorama==0.4.1
configobj==5.0.6
cryptography==2.6.1
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
filelock==3.0.12
flatbuffers==1.11
funcsigs==1.0.2
humanize==0.5.1
ifaddr==0.1.6
importlib-metadata==0.18
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
isort==4.3.17
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
modin==0.5.3
more-itertools==7.0.0
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
numpy==1.16.2
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
paramiko==2.4.2
parso==0.4.0
pathlib2==2.3.3
pexpect==4.7.0
pgspecial==1.11.5
pickleshare==0.7.5
Pillow==6.0.0
pluggy==0.12.0
prometheus-client==0.7.0
prompt-toolkit==2.0.9
psycopg2==2.7.5
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pydocstyle==3.0.0
pyflakes==2.1.1
Pygments==2.4.2
pylama==7.7.1
pylama-pylint==3.1.1
pylint==2.3.1
PyNaCl==1.3.0
pyparsing==2.4.0
pyrsistent==0.15.2
pytest==4.6.3
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1.1
pyzmq==18.0.1
ray==0.7.0
redis==3.2.1
scikit-learn==0.20.3
scipy==1.2.1
Send2Trash==1.5.0
setproctitle==1.1.10
six==1.12.0
sklearn==0.0
snowballstemmer==1.2.1
SQLAlchemy==1.3.5
sqlparse==0.3.0
tabulate==0.8.3
terminado==0.8.2
terminaltables==3.1.0
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
typed-ast==1.3.1
typing==3.7.4
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.1
zeroconf==0.22.0
zipp==0.5.1

```

**Comment by devin-petersohn** [comment]
Thanks @TheCedarPrince, this helps a lot. 

>Right now I am having to revert back to vanilla pandas - any thoughts about what is happening?

This is a bug, but an easy one to fix. When we read from a sqlalchemy table, we make a connection from each worker to read a part of the table. In this case, we built the subqueries inadvertently without being compatible with postgres. That is why this is a bug.

It's a one line fix, and very simple. Thanks for the clarification, I will make sure it is in the next release.

**Comment by TheCedarPrince** [comment]
@devin-petersohn - awesome! Looking forward to the new release.

When it is done, just let me know and I can give it a shot - looking forward to moving back to modin. : )

**Comment by devin-petersohn** [comment]
@TheCedarPrince I added a fix yesterday would you see if it works in your setup? Install like this:

```
pip install git+https://github.com/devin-petersohn/modin@issues/694
```

We are in mid-development on this release, so some other things may not work as expected. Please let us know if you encounter any of these 😄.

**Comment by qxlsz** [comment]
It still doesnt work :/

**Comment by qxlsz** [comment]
I have the same exact error as @TheCedarPrince  
`  File "/Users/GrumpyLord/env_1774/lib/python3.6/site-packages/pandas/io/sql.py", line 1431, in execute
    cur.execute(*args)
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT COUNT(*) FROM (SELECT DISTINCT req, a1, a2, a3 from tmpdb as foo)': subquery in FROM must have an alias
LINE 1: SELECT COUNT(*) FROM (SELECT DISTINCT req, a1, a2...
                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.`

**Comment by devin-petersohn** [comment]
@qxlsz It hasn't been in a release yet. You can install from the master branch to try it out: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by qxlsz** [comment]
@devin-petersohn 
I did install from master branch 
```

In [1]: import pandas as pd

In [2]: import psycopg2
   ...:
   ...:
   ...: CONN = psycopg2.connect(dbname="tmpdb", user="xx",
   ...:                             password="xx", host="xx")

In [3]: df = pd.read_sql("SELECT time FROM tmpdb", CONN)

In [4]: import modin.pandas as pd

In [5]: df = pd.read_sql("SELECT time FROM tmpdb", CONN)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/stream_exit/lib/python3.6/site-packages/ray/worker.py in put_object(self, object_id, value)
    382         try:
--> 383             self.store_and_register(object_id, value)
    384         except pyarrow.PlasmaObjectExists:

~/stream_exit/lib/python3.6/site-packages/ray/worker.py in store_and_register(self, object_id, value, depth)
    316                         serialization_context=self.get_serialization_context(
--> 317                             self.task_driver_id))
    318                 break

~/stream_exit/lib/python3.6/site-packages/ray/utils.py in _wrapper(*args, **kwargs)
    478                     with self.lock:
--> 479                         return orig_attr(*args, **kwargs)
    480

~/stream_exit/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient.put()

~/stream_exit/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.serialize()

~/stream_exit/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.SerializationContext._serialize_callback()

~/stream_exit/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py in dumps(obj, protocol)
    951         cp = CloudPickler(file, protocol=protocol)
--> 952         cp.dump(obj)
    953         return file.getvalue()

~/stream_exit/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py in dump(self, obj)
    266         try:
--> 267             return Pickler.dump(self, obj)
    268         except RuntimeError as e:

/usr/local/var/pyenv/versions/3.6.4/lib/python3.6/pickle.py in dump(self, obj)
    408             self.framer.start_framing()
--> 409         self.save(obj)
    410         self.write(STOP)

/usr/local/var/pyenv/versions/3.6.4/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    495             if reduce is not None:
--> 496                 rv = reduce(self.proto)
    497             else:

TypeError: can't pickle psycopg2.extensions.connection objects
```
I get this error

**Comment by devin-petersohn** [comment]
@qxlsz Thanks, that is helpful! We fixed the case for sqlalchemy connections, but the psycopg2 connections were not updated. I will add the fix for it. I'm opening a new issue for this because it is a separate issue from the original and I'd like to track is separately. Thanks again!

**Comment by Harshitg** [comment]
I am getting the following error in case of msssql.

```
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near ')'. (102) (SQLExecDirectW)")
[SQL: SELECT COUNT(*) FROM (select * from cashflow_data as foo)]
```

Minimal  code is as follows:

```
import modin.experimental.pandas as pd
query = f'''select * from cashflow_data'''
file_data = pd.read_sql(sql = query, con=engine2,max_sessions = 10)
y = datetime.datetime.now() - x
```

Any way to fix it

**Comment by devin-petersohn** [comment]
@Harshitg thanks for posting, would you mind to create a new issue to track this?

I will also need to know what `engine2` (minus passwords, etc.) is and a couple of lines of synthetic data that represent your workflow. Thanks!

**Comment by mst3v3nsn** [comment]
@devin-petersohn 
I'm also receiving an issue similar to this.

A brief snippet is as follows:
`
import ray

driver = 'SQL SERVER'

os.environ['MODIN_ENGINE'] = "ray"
ray.init(num_gpus=1)
import modin.pandas as pd

conn_string = f'mssql+pyodbc://{user}:{password}@{server}/{db}?driver={driver}'

query_base = f'SELECT * FROM {table} WHERE ({col_name} >= \'{_start}\' AND {col_name} < \'{_end}\')'

sql_query = pd.read_sql(sql=query_base, con=conn_string)
`

The error I received is as follows:
`
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'LIMIT'. (102) (SQLExecDirectW)")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\envs\ark-discord-tool\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'LIMIT'. (102) (SQLExecDirectW)")

(Background on this error at: http://sqlalche.me/e/13/f405)
`

Any help would be greatly appreciated.

**Comment by LeonKolyang** [comment]
I think the error lies within the sql_dipatcher.py module. Modin builds a connection string for retrieving the table columns names with  "SELECT * FROM ({}) as foo LIMIT 0" and chunks the requests with "SELECT * FROM ({}) as foo LIMIT {} OFFSET {}". The LIMIT statement does not exist in SQL Server, I think we would need a translation for this,
AFAIK  a proper SQL Server statement would look something like this:
SELECT * 
FROM {table}
ORDER BY {order_col} ASC 
OFFSET {offset} ROWS
FETCH NEXT {fetch} ROWS ONLY;

Hope I am not wrong with this one.
