### ISSUE TITLE
No module named 'modin.pandas'; 'modin' is not a package

### ISSUE THREAD

**Issue by wswsmao** [modin-project/modin#6964]
I get similar error like this
https://github.com/modin-project/modin/issues/2360

and there are more strange behavior
```
(venv) # pip install git+https://github.com/modin-project/modin
(venv) # export PYTHONPATH=`pwd`
(venv) # python -c "import modin.pandas as pd"
(venv) # python -c "import modin.pandas as pd"
```

until here, everything is ok.

however,
```
(venv) # python tst_modin.py
Traceback (most recent call last):
  File "/home/abushwang/pytorch/modin/modin/modin.py", line 1, in <module>
    import modin.pandas as pd
  File "/home/abushwang/pytorch/modin/modin/modin.py", line 1, in <module>
    import modin.pandas as pd
ModuleNotFoundError: No module named 'modin.pandas'; 'modin' is not a package

(venv) # python -c "import modin.pandas as pd"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/abushwang/pytorch/modin/modin/modin.py", line 1, in <module>
    import modin.pandas as pd
ModuleNotFoundError: No module named 'modin.pandas'; 'modin' is not a package

cat tst_modin.py
import modin.pandas as pd
import pandas

#############################################
### For the purpose of timing comparisons ###
#############################################
import time
import ray
# Look at the Ray documentation with respect to the Ray configuration suited to you most.
ray.init()
#############################################

# This may take a few minutes to download
dataset_url = "/home/abushwang/pytorch/yellow_tripdata_2015-01.csv"

start = time.time()

pandas_df = pandas.read_csv(dataset_url, parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"], quoting=3)

end = time.time()
pandas_duration = end - start
print("Time to read with pandas: {} seconds".format(round(pandas_duration, 3)))

start = time.time()

modin_df = pd.read_csv(dataset_url, parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"], quoting=3)

end = time.time()
modin_duration = end - start
print("Time to read with Modin: {} seconds".format(round(modin_duration, 3)))

print("Modin is {}x faster than pandas at `read_csv`!".format(round(pandas_duration / modin_duration, 2)))
```

as the report, this cmd also fail
```
(venv) # python -c "import modin.pandas as pd"
```

I get tst_modin.py from this doc
https://modin.readthedocs.io/en/latest/getting_started/quickstart.html

**Comment by arunjose696** [comment]
The issue is because you have named your file "/home/abushwang/pytorch/modin/modin/modin.py" modin.py, python thinks you are trying to import modin.pandas from this python file and it complains this is not a package. The problem should go away if you rename your file to something else other than modin.py

**Comment by wswsmao** [comment]
> The issue is because you have named your file "`/home/abushwang/pytorch/modin/modin/modin.py`" `modin.py`, python thinks you are trying to import `modin.pandas` from this python file and it complains this is not a package(As this is just a python file). The problem should go away if you rename your file to something else other than modin.py
> 
> Also this command `python -c "import modin.pandas as pd"` errors because there is still modin.py in the python path as the current directory has higher precedence compared to installed modules

@arunjose696 it works, thank you
```
Time to read with pandas: 4.154 seconds
Time to read with Modin: 3.247 seconds
Modin is 1.28x faster than pandas at `read_csv`
```

**Comment by YarShev** [comment]
@wswsmao, let's track your question in #6982.

**Comment by wswsmao** [comment]
> @wswsmao, let's track your question in #6982.

ok, thanks

**Comment by YarShev** [comment]
@wswsmao, keeping you updated, the notebooks on master should work now.
