### ISSUE TITLE
Remove read_pickle_distributed/to_pickle_distributed

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6967]
They were [deprecated](https://github.com/modin-project/modin/pull/6957) for 0.28.0.

**Comment by YarShev** [comment]
We also have a bunch of other methods like from_*/to_* we deprecated. Can we remove them in one go?

**Comment by anmyachev** [comment]
> We also have a bunch of other methods like from_*/to_* we deprecated. Can we remove them in one go?

We can. Do you have a list of such functions?

**Comment by YarShev** [comment]
E.g., from_pandas, from_arrow, from_dataframe and from_non_pandas from location modin.pandas.utils. You may find some more examples by searching for `will be removed in a future version` in codebase.
