### ISSUE TITLE
Make it possible to choose which layers to log or not log in modin logger

### ISSUE THREAD

**Issue by arunjose696** [modin-project/modin#7092]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

By default the Modin logger logs information about all layers that inherit ClassLogger this logs a lot of content, It would be good if  it would be  possible to choose which layers to log with modin logger.

By default modin logger could log all information to the file and if required user through environment variables can suggest which layers  Log if logs of only specific layers are required, For example this could be helpful if the user needs to log only higer level layers and leave out lower layers from being logged.

**Comment by YarShev** [comment]
@anmyachev, @dchigarev, thoughts?

**Comment by anmyachev** [comment]
> For example this could be helpful if the user needs to log only higer level layers and leave out lower layers from being logged.

`enable_api_only` could be used for that, right?
https://github.com/modin-project/modin/blob/c75343687799e3b69fc04a99b8a9d11eab1fd984/modin/config/envvars.py#L476

**Comment by arunjose696** [comment]
With `enable_api_only` currently all the classes that inherit classLogger would be logged, The only [difference](https://github.com/arunjose696/modin/blob/logging_layer/modin/logging/config.py#L184) between enable_api_only and enable is in enable additionally memory.log also would be written. 

As you said I think we could use this enable_api_only Variable to choose which layers to log.

**Comment by anmyachev** [comment]
> With enable_api_only currently all the classes that inherit classLogger would be logged, The only [difference](https://github.com/arunjose696/modin/blob/logging_layer/modin/logging/config.py#L184) between enable_api_only and enable is in enable additionally memory.log also would be written.

Also this:
https://github.com/modin-project/modin/blob/c75343687799e3b69fc04a99b8a9d11eab1fd984/modin/logging/config.py#L172

Maybe it would be enough to simply move the lower-level functionality logging to the debug level (instead of `info`)?

> As you suggesting to use LogMode to choose which layers to log?

As an option. BTW how many different levels are there now?

**Comment by arunjose696** [comment]
Currently layer names have not been named, so every layer is just given the default name PANDAS-API, We could add the following layers.

Dataset
QueryCompiler
Dataframe
PandasDataframePartitionManager
Axis Partition
Block partition


Maybe a common layer for classes such as Dispatcher,parser, acessor etc

**Comment by YarShev** [comment]
It seems to me enable_api_only and enable options look confusing. Maybe we should just leave enable option, using which memory.log would also be generated?

> Maybe it would be enough to simply move the lower-level functionality logging to the debug level (instead of info)?

It would make sense since I think only developers would look at the lower-level functionality. Making it possible to choose which layers to log would only complicate the things for users. Thoughts?

**Comment by arunjose696** [comment]
> It seems to me enable_api_only and enable options look confusing. Maybe we should just leave enable option, using which memory.log would also be generated?

I think this makes better sense as the memory.log would not be a large file as logging is just done every 5 seconds by default.

> > Maybe it would be enough to simply move the lower-level functionality logging to the debug level (instead of info)?

Which layers should be considered lower level?

> Making it possible to choose which layers to log would only complicate the things for users. Thoughts?

Then can I close this issue if it would not be beneficial?

**Comment by YarShev** [comment]
> > It seems to me enable_api_only and enable options look confusing. Maybe we should just leave enable option, using which memory.log would also be generated?
> 
> I think this makes better sense as the memory.log would not be a large file as logging is just done every 5 seconds by default.

Let's resolve that in a separate issue. Please create one.

>> Maybe it would be enough to simply move the lower-level functionality logging to the debug level (instead of info)?
> 
> Which layers should be considered lower level?

I think everything besides the API layer.

>> Making it possible to choose which layers to log would only complicate the things for users. Thoughts?
> 
> Then can I close this issue if it would not be beneficial?

Yes, let's close it.
