### ISSUE TITLE
Modin and Python 3.12

### ISSUE THREAD

**Issue by YuriyTigiev** [modin-project/modin#7098]
Hello, 

Is Modin compaitable with pytho 3.12?

**Comment by YarShev** [comment]
Hi @YuriyTigiev, thank you for this question! Modin should be available for python 3.12 with Dask and MPI engines. `modin[dask]` or `modin[mpi]` for installing from PyPI, `modin-dask` or `modin-mpi` for installing from conda-forge.

**Comment by YarShev** [comment]
@YuriyTigiev, just rechecked Modin builds in conda-forge. We don't have builds for python 3.12 yet there. You can only install `modin[dask]` or `modin[mpi]` with python 3.12 from PyPI. For Modin builds with python 3.12 in conda-forge we would have to update the feedstock.

**Comment by rootsmusic** [comment]
@YarShev  [pandas will be supporting](https://github.com/pandas-dev/pandas/issues/58734) Python 3.13.

**Comment by YarShev** [comment]
@rootsmusic, thanks for letting us know this! When pandas starts supporting python 3.13, we should also try to support it. However, as long as a Modin engine (Ray, Dask or MPI) doesn't have support for python 3.13, we will not be able to support that python version. You can see such an issue with Ray engine and python 3.12.

**Comment by anmyachev** [comment]
**FYI:** it looks like Ray will soon be released with Python 3.12 support: https://github.com/ray-project/ray/issues/40211#issuecomment-2148428366

**Comment by anmyachev** [comment]
> @YuriyTigiev, just rechecked Modin builds in conda-forge. We don't have builds for python 3.12 yet there. You can only install `modin[dask]` or `modin[mpi]` with python 3.12 from PyPI. For Modin builds with python 3.12 in conda-forge we would have to update the feedstock.

Feedstock is updated. Installation for py3.12 from conda-forge should works (at least for dask and mpi).
