### ISSUE TITLE
get version of modin module

### ISSUE THREAD

**Issue by jangorecki** [modin-project/modin#71]
standard way `pd.__version__` does not work

**Comment by devin-petersohn** [comment]
Good point. Currently the Modin version is checked by 
```
import modin
modin.__version__
```
I do see value in adding `pd.__version__`. What would you want to see in `pd.__version__`? We could have it be the `pandas` version that is being used by Modin. Alternatively it could just be the same as `modin.__version__`.

**Comment by jangorecki** [comment]
Sorry, I should include more details.
Below does not work.
```py
import modin.pandas as pd
pd.__version__
```
This works perfectly fine:
```py
import modin as modin
modin.__version__
```
In any case I expect to get `modin` version.
I would like to use modin as drop-in replacement for pandas, does `import modin` works for that? or I need to `import modin.pandas as pd`. If `import modin as pd` is already pandas drop-in replacement then we can close this issue. I can just basically stop using `modin.pandas`.

**Comment by devin-petersohn** [comment]
`import modin as pd` would not be a drop-in replacement. In the future we will have `modin.pandas`, `modin.sql`, and other APIs that are drop-in replacements. 

```python
import modin.pandas as pd
pd.__version__
```

This seems like a good thing to add.
