### ISSUE TITLE
Ray 2.10.0 broke tests

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#7115]
A new release of Ray is out, which broke our tests. To unblock CI let's exclude the version for now.

**Comment by YarShev** [comment]
An example of the failure - https://github.com/modin-project/modin/actions/runs/8417991762/job/23054300277?pr=7114. The tests are failing locally too with `pytest -n 2`. @rkooo567, do you know what might be broken in Ray 2.10.0?

**Comment by rkooo567** [comment]
@YarShev I am not aware of anything. can you actually post to Ray Github repo? Thank you!

**Comment by YarShev** [comment]
https://github.com/ray-project/ray/issues/44264
