### ISSUE TITLE
access git revision from inside the project

### ISSUE THREAD

**Issue by jangorecki** [modin-project/modin#72]
`modin.__git_revision__` could return full git SHA of latest commit.
It is useful for developers to track which particular revision they are running at the moment.
Something like https://github.com/dask/dask/pull/1760

**Comment by devin-petersohn** [comment]
This would be great to add. If you are able and willing to contribute this, that would be great. Otherwise, I am happy to add this in the next couple of days.

**Comment by simon-mo** [comment]
@devin-petersohn Did this get removed from the codebase some reason?
