### ISSUE TITLE
raise TypeError("Cannot do operation non-numeric dtypes")

### ISSUE THREAD

**Issue by techbrismo** [modin-project/modin#720]
### System information
- **OS Platform and Distribution:**  Linux Ubuntu 18.04
- **Modin installed from (source or binary)**: : pip3 install modin
- **Modin version**: 0.5.3
- **Python version**: 3.6.8
- **Exact command to reproduce**:
1- df_runFlag = pd.read_csv(Config.FX_GetJsonConfig()['RunFlagTablePath'], usecols=['Platform', 'RunFlag', 'RAI', 'IAI', 'OAI'], encoding = 'utf8')

2-  st_Platforms = df_runFlag.loc[df_runFlag['RunFlag'] == 1, 'Platform']

### Describe the problem
I have those two lines of code in separated files. Both including modin.pandas.
misc file have the line of code number 1.
main file have the line of code number 2.
On main file I am calling the a method on the misc file that will read the csv. The main file has modin.pandas all the time, and if on misc file (to read the csv) has pandas..everything will work but if I change to modin.pandas I get an error.

### Source code / logs
File "main.py", line 97, in <module>
    Fx_Initialization()
  File "main.py", line 47, in Fx_Initialization
    st_Platforms = df_runFlag.loc[df_runFlag['RunFlag'] == 1, 'Platform']
  File "/.local/lib/python3.6/site-packages/modin/pandas/indexing.py", line 241, in __getitem__
    if key[0] == slice(None):
  File "/.local/lib/python3.6/site-packages/modin/pandas/base.py", line 3158, in __eq__
    return self.eq(other)
  File "/.local/lib/python3.6/site-packages/modin/pandas/series.py", line 527, in eq
    return super(Series, new_self).eq(new_other, level=level, axis=axis)
  File "/.local/lib/python3.6/site-packages/modin/pandas/base.py", line 1037, in eq
    return self._binary_op("eq", other, axis=axis, level=level)
  File ".local/lib/python3.6/site-packages/modin/pandas/base.py", line 191, in _binary_op
    other = self._validate_other(other, axis, numeric_or_object_only=True)
  File "/.local/lib/python3.6/site-packages/modin/pandas/base.py", line 155, in _validate_other
    raise TypeError("Cannot do operation non-numeric dtypes")

What is causing this? 
Thank you in advance

**Comment by devin-petersohn** [comment]
Hi @techbrismo, thanks for posting!

It looks like our error checking is not matching pandas in this case. I will look into this a bit deeper.

Using multiple python files shouldn't cause any errors, so I don't think that is causing the problem. Thanks again for the report!
