### ISSUE TITLE
Parrallelize __array_wrap__

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#727]
### Describe the problem

~~We need to figure out what the `__array_wrap__` method is used for.~~ 

Now that we have an implementation for `__array__`, we should add support for `__array_wrap__`. It can be found [here](https://github.com/modin-project/modin/blob/master/modin/pandas/base.py#L3164)

**Comment by mvashishtha** [comment]
I can't quite understand from the documentation what this function does. I haven't heard of anyone asking for it, so I'll assume it's low priority.

**Comment by anmyachev** [comment]
Deprecated function.
