### ISSUE TITLE
Prepare Modin code to NumPy 2.0

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#7292]
Migration guide: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

`ruff check modin --select NPY201 --preview`

**Comment by rootsmusic** [comment]
@anmyachev Add modin's "Min compatible version" in [tracker table](https://github.com/numpy/numpy/issues/26191#issue-2219105340)?

**Comment by anmyachev** [comment]
> @anmyachev Add modin's "Min compatible version" in [tracker table](https://github.com/numpy/numpy/issues/26191#issue-2219105340)?

@rootsmusic good idea! Will you do this? :)

**Comment by anmyachev** [comment]
@rootsmusic Thanks for the suggestion! I added Modin to HackMD.
