### ISSUE TITLE
modin read big csv failed

### ISSUE THREAD

**Issue by Crazy-LittleBoy** [modin-project/modin#733]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

when i used modin.pandas read a big csv file (about 20GB), the following error happened.
notice that, when i read a smaller csv file (about 1.5GB),it works very well.
can someone fix it? thx.

### Source code / logs

data = pd.read_csv('/data/xxx.csv',
                   low_memory=False,
                   sep='|')

(pid=19522) Traceback (most recent call last):
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 920, in _process_task
(pid=19522)     self._store_outputs_in_object_store(return_object_ids, outputs)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19522)     self.put_object(object_ids[i], outputs[i])
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19522)     self.store_and_register(object_id, value)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19522)     self.task_driver_id))
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19522)     return orig_attr(*args, **kwargs)
(pid=19522)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19522)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19522)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19522) pyarrow.lib.ArrowIOError: Encountered unexpected EOF
(pid=19522) 
(pid=19522) During handling of the above exception, another exception occurred:
(pid=19522) 
(pid=19522) Traceback (most recent call last):
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=19522)     ray.worker.global_worker.main_loop()
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1042, in main_loop
(pid=19522)     self._wait_for_and_process_task(task)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 993, in _wait_for_and_process_task
(pid=19522)     self._process_task(task, execution_info)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 924, in _process_task
(pid=19522)     ray.utils.format_error_message(traceback.format_exc()))
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 933, in _handle_process_task_failure
(pid=19522)     self._store_outputs_in_object_store(return_object_ids, failure_objects)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19522)     self.put_object(object_ids[i], outputs[i])
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19522)     self.store_and_register(object_id, value)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19522)     self.task_driver_id))
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19522)     return orig_attr(*args, **kwargs)
(pid=19522)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19522)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19522)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19522) pyarrow.lib.ArrowIOError: Broken pipe
(pid=19522) 
(pid=19522) During handling of the above exception, another exception occurred:
(pid=19522) 
(pid=19522) Traceback (most recent call last):
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=19522)     driver_id=None)
(pid=19522)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=19522)     time.time())
(pid=19522)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=19522)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19522) Exception: [RayletClient] Connection closed unexpectedly.
(pid=19525) Fatal Python error: Bus error
(pid=19525) 
(pid=19536) Fatal Python error: Bus error
(pid=19536) 
(pid=19527) Traceback (most recent call last):
(pid=19527)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=19527)     ray.worker.global_worker.main_loop()
(pid=19527)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1041, in main_loop
(pid=19527)     task = self._get_next_task_from_raylet()
(pid=19527)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1024, in _get_next_task_from_raylet
(pid=19527)     task = self.raylet_client.get_task()
(pid=19527)   File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
(pid=19527)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19527) Exception: [RayletClient] Raylet connection closed.
(pid=19527) 
(pid=19527) During handling of the above exception, another exception occurred:
(pid=19527) 
(pid=19527) Traceback (most recent call last):
(pid=19527)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=19527)     driver_id=None)
(pid=19527)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=19527)     time.time())
(pid=19527)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=19527)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19527) Exception: [RayletClient] Connection closed unexpectedly.
(pid=19544) Fatal Python error: Bus error
(pid=19544) 
(pid=19524) Fatal Python error: Bus error
(pid=19524) 
(pid=19539) Fatal Python error: Bus error
(pid=19539) 
(pid=19533) Fatal Python error: Bus error
(pid=19533) 
(pid=19534) Traceback (most recent call last):
(pid=19534)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=19534)     ray.worker.global_worker.main_loop()
(pid=19534)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1041, in main_loop
(pid=19534)     task = self._get_next_task_from_raylet()
(pid=19534)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1024, in _get_next_task_from_raylet
(pid=19534)     task = self.raylet_client.get_task()
(pid=19534)   File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
(pid=19534)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19534) Exception: [RayletClient] Raylet connection closed.
(pid=19534) 
(pid=19534) During handling of the above exception, another exception occurred:
(pid=19534) 
(pid=19534) Traceback (most recent call last):
(pid=19534)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=19534)     driver_id=None)
(pid=19534)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=19534)     time.time())
(pid=19534)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=19534)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19534) Exception: [RayletClient] Connection closed unexpectedly.
(pid=19532) Fatal Python error: Bus error
(pid=19532) 
(pid=19526) Fatal Python error: Bus error
(pid=19526) 
(pid=19528) Fatal Python error: Bus error
(pid=19528) 
(pid=19529) Fatal Python error: Bus error
(pid=19529) 
(pid=19537) Fatal Python error: Bus error
(pid=19537) 
(pid=19513) Fatal Python error: Bus error
(pid=19513) 
(pid=19542) Fatal Python error: Bus error
(pid=19542) 
(pid=19540) Fatal Python error: Bus error
(pid=19540) 
(pid=19521) Fatal Python error: Bus error
(pid=19521) 
(pid=19516) Traceback (most recent call last):
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 920, in _process_task
(pid=19516)     self._store_outputs_in_object_store(return_object_ids, outputs)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19516)     self.put_object(object_ids[i], outputs[i])
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19516)     self.store_and_register(object_id, value)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19516)     self.task_driver_id))
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19516)     return orig_attr(*args, **kwargs)
(pid=19516)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19516)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19516)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19516) pyarrow.lib.ArrowIOError: Broken pipe
(pid=19516) 
(pid=19516) During handling of the above exception, another exception occurred:
(pid=19516) 
(pid=19516) Traceback (most recent call last):
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=19516)     ray.worker.global_worker.main_loop()
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1042, in main_loop
(pid=19516)     self._wait_for_and_process_task(task)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 993, in _wait_for_and_process_task
(pid=19516)     self._process_task(task, execution_info)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 924, in _process_task
(pid=19516)     ray.utils.format_error_message(traceback.format_exc()))
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 933, in _handle_process_task_failure
(pid=19516)     self._store_outputs_in_object_store(return_object_ids, failure_objects)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19516)     self.put_object(object_ids[i], outputs[i])
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19516)     self.store_and_register(object_id, value)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19516)     self.task_driver_id))
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19516)     return orig_attr(*args, **kwargs)
(pid=19516)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19516)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19516)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19516) pyarrow.lib.ArrowIOError: Broken pipe
(pid=19516) 
(pid=19516) During handling of the above exception, another exception occurred:
(pid=19516) 
(pid=19516) Traceback (most recent call last):
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=19516)     driver_id=None)
(pid=19516)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=19516)     time.time())
(pid=19516)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=19516)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19516) Exception: [RayletClient] Connection closed unexpectedly.
(pid=19535) Traceback (most recent call last):
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 920, in _process_task
(pid=19535)     self._store_outputs_in_object_store(return_object_ids, outputs)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19535)     self.put_object(object_ids[i], outputs[i])
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19535)     self.store_and_register(object_id, value)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19535)     self.task_driver_id))
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19535)     return orig_attr(*args, **kwargs)
(pid=19535)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19535)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19535)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19535) pyarrow.lib.ArrowIOError: Broken pipe
(pid=19535) 
(pid=19535) During handling of the above exception, another exception occurred:
(pid=19535) 
(pid=19535) Traceback (most recent call last):
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=19535)     ray.worker.global_worker.main_loop()
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1042, in main_loop
(pid=19535)     self._wait_for_and_process_task(task)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 993, in _wait_for_and_process_task
(pid=19535)     self._process_task(task, execution_info)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 924, in _process_task
(pid=19535)     ray.utils.format_error_message(traceback.format_exc()))
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 933, in _handle_process_task_failure
(pid=19535)     self._store_outputs_in_object_store(return_object_ids, failure_objects)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 831, in _store_outputs_in_object_store
(pid=19535)     self.put_object(object_ids[i], outputs[i])
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 383, in put_object
(pid=19535)     self.store_and_register(object_id, value)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 317, in store_and_register
(pid=19535)     self.task_driver_id))
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 475, in _wrapper
(pid=19535)     return orig_attr(*args, **kwargs)
(pid=19535)   File "pyarrow/_plasma.pyx", line 497, in pyarrow._plasma.PlasmaClient.put
(pid=19535)   File "pyarrow/_plasma.pyx", line 327, in pyarrow._plasma.PlasmaClient.create
(pid=19535)   File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
(pid=19535) pyarrow.lib.ArrowIOError: Broken pipe
(pid=19535) 
(pid=19535) During handling of the above exception, another exception occurred:
(pid=19535) 
(pid=19535) Traceback (most recent call last):
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=19535)     driver_id=None)
(pid=19535)   File "/home/user_xxx/anaconda3/lib/python3.7/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=19535)     time.time())
(pid=19535)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=19535)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=19535) Exception: [RayletClient] Connection closed unexpectedly.
---------------------------------------------------------------------------
ArrowIOError                              Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/lib/python3.7/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     97         if not kwargs.get("sep", sep):
     98             kwargs["sep"] = "\t"
---> 99         return _read(**kwargs)
    100 
    101     return parser_func

~/anaconda3/lib/python3.7/site-packages/modin/pandas/io.py in _read(**kwargs)
    110         kwargs: Keyword arguments in pandas.read_csv
    111     """
--> 112     pd_obj = BaseFactory.read_csv(**kwargs)
    113     # This happens when `read_csv` returns a TextFileReader object for iterating through
    114     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/anaconda3/lib/python3.7/site-packages/modin/data_management/factories.py in read_csv(cls, **kwargs)
     57     @classmethod
     58     def read_csv(cls, **kwargs):
---> 59         return cls._determine_engine()._read_csv(**kwargs)
     60 
     61     @classmethod

~/anaconda3/lib/python3.7/site-packages/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     61     @classmethod
     62     def _read_csv(cls, **kwargs):
---> 63         return cls.io_cls.read_csv(**kwargs)
     64 
     65     @classmethod

~/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    544         if cls.read_csv_remote_task is None:
    545             return super(RayIO, cls).read_csv(**kwargs)
--> 546         return cls._read(**kwargs)
    547 
    548     @classmethod

~/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py in _read(cls, filepath_or_buffer, **kwargs)
    614         else:
    615             return cls._read_csv_from_file_pandas_on_ray(
--> 616                 filepath_or_buffer, filtered_kwargs
    617             )
    618 

~/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_pandas_on_ray(cls, filepath, kwargs)
    391 
    392         if index_col is None:
--> 393             new_index = pandas.RangeIndex(sum(ray.get(index_ids)))
    394         else:
    395             new_index_ids = get_index.remote([empty_pd_df.index.name], *index_ids)

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_ids)
   2191 
   2192         global last_task_error_raise_time
-> 2193         values = worker.get_object(object_ids)
   2194         for i, value in enumerate(values):
   2195             if isinstance(value, RayError):

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get_object(self, object_ids)
    543                     max([
    544                         ray._config.get_timeout_milliseconds(),
--> 545                         int(0.01 * len(unready_ids)),
    546                     ]),
    547                 )

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in retrieve_and_deserialize(self, object_ids, timeout, error_timeout)
    421                         object_ids[i:i + batch_size],
    422                         timeout,
--> 423                         with_meta=True,
    424                     )
    425                     for j in range(len(metadata_data_pairs)):

~/anaconda3/lib/python3.7/site-packages/ray/utils.py in _wrapper(*args, **kwargs)
    473                 def _wrapper(*args, **kwargs):
    474                     with self.lock:
--> 475                         return orig_attr(*args, **kwargs)
    476 
    477                 self._wrapper_cache[attr] = _wrapper

~/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient.get_buffers()

~/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient._get_object_buffers()

~/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowIOError: Encountered unexpected EOF

**Comment by devin-petersohn** [comment]
>when i used modin.pandas read a big csv file (about 20GB)

How much memory does your environment have? How many cores?

This error has been brought up in Ray: https://github.com/ray-project/ray/issues/1838 and it looks related. cc @pcmoritz

**Comment by Crazy-LittleBoy** [comment]
> > when i used modin.pandas read a big csv file (about 20GB)
> 
> How much memory does your environment have? How many cores?
> 
> This error has been brought up in Ray: [ray-project/ray#1838](https://github.com/ray-project/ray/issues/1838) and it looks related. cc @pcmoritz

My environment have 252G memory and 32 cores.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
