### ISSUE TITLE
BUG: Broken links in Modin Usage Examples page

### ISSUE THREAD

**Issue by MortalHappiness** [modin-project/modin#7335]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-main-branch).)

### Reproducible Example

N/A

### Issue Description

[This page](https://modin.readthedocs.io/en/stable/usage_guide/examples/index.html) has many borken links. For example, 

https://github.com/modin-project/modin/blob/759d548814a6ac224e83e7531cf98e20b13d85cb/docs/usage_guide/examples/index.rst?plain=1#L19

### Expected Behavior

No borken links.

### Installed Versions

Latest version of doc

**Comment by YarShev** [comment]
Hi @MortalHappiness, thanks for posting this issue. @Retribution98, can you take a look at the broken links? IIRC, you were the last person who updated the pages for Modin on Ray in a cluster.

**Comment by MortalHappiness** [comment]
@YarShev I opened a PR here.

https://github.com/modin-project/modin/pull/7336

**Comment by YarShev** [comment]
Oh, I see, thanks!
