### ISSUE TITLE
UserWarning: `DataFrame.<lambda>`

### ISSUE THREAD

**Issue by fschlimb** [modin-project/modin#734]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.5.3
- **Python version**: 3.6.8
- **Exact command to reproduce**: -

### Describe the problem
My code does not contain any lambda expression, modin still issues the following warning:

```UserWarning: `DataFrame.<lambda>` defaulting to pandas implementation.```

I'd like to understand where this come from to understand potential performance implications.
Any idea?

### Source code / logs
pandas functions used:
```
* read_csv
* df.merge
* df = df[expr]
* df.groupby
* group.count().unstack()
* group.sum()
* df.values
* series.isin
```

**Comment by devin-petersohn** [comment]
This is probably just an issue with the error message, I will take a look into it.

We default to pandas implementation for operations not yet supported and for all operations on empty dataframes. For larger dataframes there is a non-trivial cost to converting a partitioned dataframe object to a pandas DataFrame, and we are constantly working on improving the coverage for the API: https://modin.readthedocs.io/en/latest/UsingPandasonRay/dataframe_supported.html.

**Comment by fschlimb** [comment]
Thanks!
Could this be caused by using `df.groupy(["c1", "c2"])`?

I get an extra warning for using `pd.merge(df1, df2, left_on=..., right_on=..., ...)`.

**Comment by devin-petersohn** [comment]
You are correct, it is the `groupby`. I am adding a better message. Thanks!
