### ISSUE TITLE
S3FS update to 0.3.0 causes unclosed socket warning in pytest

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#743]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem
Updating s3fs to 0.3 causes an unclosed socket warning to be issued during testing for the `test_from_csv_s3` method. This warning is only observed in pytest, and #742 temporarily fixes it by checking if the warnings issued are unclosed socket warnings, in which case the test proceeds, or warnings indicating that the pandas backend is being used, rather than the modin.pandas backend.

The warning looks like this:

```python
unclosed <ssl.SSLSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('128.32.46.77', 65363), raddr=('54.231.40.219', 443)>
```

**Comment by RehanSD** [comment]
Similar issue in boto3 repo: https://github.com/boto/boto3/issues/454 - a fix for that will probably help us out since it seems that s3fs is built on top of boto3

**Comment by devin-petersohn** [comment]
Looks like we're already using the best practices here. Closing as nothing to do here.
