### ISSUE TITLE
KeyError when trying to drop a column

### ISSUE THREAD

**Issue by joeydonovan4** [modin-project/modin#744]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Modin installed from (source or binary)**: Binary
- **Modin version**: 0.5.4
- **Python version**: 3.7.3
- **Exact command to reproduce**: `dataframe.drop(columns=['tran_nbr'], axis=1, inplace=True)`

### Describe the problem
I am trying to drop a column from a dataframe that I save to a file using `read_csv`:
`pd.read_csv(TMP + 'tmp.dat', compression=compression, header=(1 if sep == CSV else None), sep=sep, usecols=cols, dtype=dtype, encoding=encoding)`

Later on in the process, I want to drop a column from the dataframe but I get an error saying that the specified column name is not found. I have printed out the columns of the dataframe and the column that I am trying to drop and both are returning expected values.

This same code was working fine before I began using `modin.pandas` rather than just `pandas` itself.

### Source code / logs
```
Traceback (most recent call last):
File "main.py", line 89, in <module>
    main(exec_mode, s3_filepath, create_csv)
  File "main.py", line 25, in main
    if raw_to_std(file_path, create_csv):
  File "/python/src/raw_to_std/raw_to_std.py", line 53, in raw_to_std
    dataframe.drop(columns=['tran_nbr'], axis=1, inplace=True)
  File "/lib/python3.7/site-packages/modin/pandas/base.py", line 955, in drop
    index=axes["index"], columns=axes["columns"]
  File "/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 2460, in drop
    new_dtypes = self.dtypes.drop(columns)
  File "/lib/python3.7/site-packages/pandas/core/series.py", line 3829, in drop
    inplace=inplace, errors=errors)
  File "/lib/python3.7/site-packages/pandas/core/generic.py", line 3780, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/lib/python3.7/site-packages/pandas/core/generic.py", line 3812, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4965, in drop
    '{} not found in axis'.format(labels[mask]))
KeyError: "['tran_nbr'] not found in axis"
```

**Comment by devin-petersohn** [comment]
Does it work if you remove the `axis` argument from the `drop`?

```python
dataframe.drop(columns=['tran_nbr'], inplace=True)
```

This is likely a case where our error checking is more strict than pandas. pandas is ignoring the `axis=1` argument because when `axis=1` it attempts to drop from the rows, and it is looking for the label you provided (`tran_nbr`) in the rows instead of the columns. We should also ignore this argument if `columns` or `index` is specified.

**Comment by joeydonovan4** [comment]
@devin-petersohn thanks for the quick response.
Doesn't seem to be working when I remove the `axis` argument either. Still gives the same error.

**Comment by devin-petersohn** [comment]
Ok, looking through the trace it appears that there is a bug with the `dtypes` that is causing the issue. I was able to reproduce the error locally, and even resetting the cache for the `dtypes` does not fix the issue. I will dig into this and get it fixed. Thanks for reporting!

**Comment by devin-petersohn** [comment]
I rewrote the way we handle `dtypes` in #721, and this is no longer reproducible for me. Please let me know if you are still having problems and feel free to re-open the issue.
