### ISSUE TITLE
NotImplementedError: Groupby with lists of columns not yet supported.

### ISSUE THREAD

**Issue by mathlf2015** [modin-project/modin#75]
### System information
- OS Platform and Distribution (e.g., Linux centos):
- Modin installed from pip:
- Modin version 0.1.1:
- Python version 3.6.6:
- t1 = t1.groupby(["subid","label"])["cnt"].count().reset_index():

0.1.1

### Describe the problem

Groupby with lists of columns not yet supported.

### Source code / logs
Waiting for redis server at 127.0.0.1:59835 to respond...
Waiting for redis server at 127.0.0.1:16671 to respond...
Starting local scheduler with the following resources: {'CPU': 56, 'GPU': 4}.
Traceback (most recent call last):
  File "gen_fea_online.py", line 318, in <module>
    df = get_data_log_hive(pre_time=(2018,8,7))
  File "gen_fea_online.py", line 290, in get_data_log_hive
    df_vod40 = gen_fea_active_log(df_vod40)
  File "gen_fea_online.py", line 238, in gen_fea_active_log
    t1 = t1.groupby(["subid","label"])["cnt"].count().reset_index()
  File "/root/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 823, in groupby
    "Groupby with lists of columns not yet supported.")
NotImplementedError: Groupby with lists of columns not yet supported.

**Comment by devin-petersohn** [comment]
Hi @mathlf2015, thanks for the request.

We are currently rewriting the majority of the backend for scalability, performance, and maintainability. With this update, `groupby` will have better performance, and we should be able to extend it to this. #70 contains the rewrite.
