### ISSUE TITLE
KeyError in groupby when specifying a label from MultiIndexLevel

### ISSUE THREAD

**Issue by agardelein** [modin-project/modin#758]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 9 unstable
- **Modin installed from (source or binary)**: pip3 install -U git+https://github.com/modin-project/modin
- **Modin version**: 0.5.4
- **Python version**: 3.7.3
- **Exact command to reproduce**:

Following fix of modin-project#756, this new issue occurs.

File test.dat:
```
p0,p1,data0,data1,data2
A,0,10,11,12
B,1,20,21,22
C,2,30,31,32
D,3,40,41,42
E,4,50,51,52
```

### Describe the problem

The issue occurs when performing a `groupby()` followed by a `get_group()`

Note that the `print` inserted at line 1836 use `self.columns` since `self.keys()` at line 395 is supposed to return `self.columns`
### Source code / logs

```
import modin.pandas
import pandas as pd

# Working example with Pandas
csv1=pd.read_csv('test.dat',header=0,index_col=[0,1])
g1=csv1.groupby(by=lambda x:x[1]<3)
g1.get_group(True)

# Testing with modin.pandas
csv2=modin.pandas.read_csv('test.dat',header=0,index_col=[0,1])
g2=csv2.groupby(by=lambda x:x[1]<3)
df_g=csv2.groupby('p0').get_group('A')
```

Log:
```
p0 Index(['data0', 'data1', 'data2'], dtype='object')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-704c3a79c97b> in <module>()
----> 1 df_g=csv2.groupby('p0').get_group('A')

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed, **kwargs)
    353         elif isinstance(by, string_types):
    354             idx_name = by
--> 355             by = self.__getitem__(by)._query_compiler
    356         elif is_list_like(by):
    357             if isinstance(by, Series):

~/.local/lib/python3.7/site-packages/modin/pandas/base.py in __getitem__(self, key)
   3220             return self._getitem_slice(indexer)
   3221         else:
-> 3222             return self._getitem(key)
   3223 
   3224     def _getitem_slice(self, key):

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in _getitem(self, key)
   1835         else:
   1836             print(key, self.columns)
-> 1837             return self._getitem_column(key)
   1838 
   1839     def _getitem_column(self, key):

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in _getitem_column(self, key)
   1839     def _getitem_column(self, key):
   1840         if key not in self.keys():
-> 1841             raise KeyError("{}".format(key))
   1842         s = self._reduce_dimension(self._query_compiler.getitem_column_array([key]))
   1843         s._parent = self

KeyError: 'p0'
```

**Comment by devin-petersohn** [comment]
Thanks @agardelein, for opening this! Comments below copied from #756: 

When you use a label for the `groupby`, pandas will also allow you to specify a label from the index if is it a MultiLevelIndex. This is not documented, which is why it was missed.

The way we need to handle this is to check before the `KeyError` is thrown that the label is not in `df.index.names` (as long as it is a `MultiLevelIndex`), then handle the level accordingly.

Currently we are defaulting to pandas for the `level` parameter, so that can be done here as well to achieve functional parity, until we can have more efficient support for metadata and MultiLevelIndex in #721.

**Comment by agardelein** [comment]
While diving in the internals of `groupby()` mechanisms I found also that using `level` parameter in `groupby()` from `modin` seems not to operate. Is there something I'm doing wrong ?

```
In [1]: import modin.pandas
   ...: import pandas as pd
   ...: 
   ...: # Working example with Pandas
   ...: csv1=pd.read_csv('test.dat',header=0,index_col=[0,1])
   ...: g1=csv1.groupby(by=lambda x:x[1]<3)
   ...: g1.get_group(True)
   ...: 
   ...: # Testing with modin.pandas
   ...: csv2=modin.pandas.read_csv('test.dat',header=0,index_col=[0,1])
   ...: g2=csv2.groupby(by=lambda x:x[1]<3)
   ...: 

In [2]: csv1.groupby(level=0).groups.keys()
Out[2]: dict_keys(['A', 'B', 'C', 'D', 'E'])

In [3]: csv2.groupby(level=0).groups.keys()
Out[3]: dict_keys([])
```

**Comment by devin-petersohn** [comment]
>While diving in the internals of groupby() mechanisms I found also that using level parameter in groupby() from modin seems not to operate. Is there something I'm doing wrong ?

I also found this as I was doing the rewrite in #721. It should be fixed in master now, let me know!

**Comment by devin-petersohn** [comment]
I am going to close this, please re-open if you still run into the issue!

**Comment by agardelein** [comment]
After `pip3 install --force-reinstall git+https://github.com/modin-project/modin --no-cache` ipython3 issued  `ModuleNotFoundError: No module named 'distributed'` that was corrected with a pip3 install dask distributed.
After this `modin.pandas` loaded correctly, and I still run the same issues (both). Did I missed something in the update process ?

```
In [1]: import modin.pandas
   ...: import pandas as pd
   ...: 
   ...: # Working example with Pandas
   ...: csv1=pd.read_csv('test.dat',header=0,index_col=[0,1])
   ...: g1=csv1.groupby(by=lambda x:x[1]<3)
   ...: g1.get_group(True)
   ...: 
   ...: # Testing with modin.pandas
   ...: csv2=modin.pandas.read_csv('test.dat',header=0,index_col=[0,1])
   ...: g2=csv2.groupby(by=lambda x:x[1]<3)
   ...: df_g=csv2.groupby('p0').get_group('A')
   ...: 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-c0da508744ab> in <module>()
     10 csv2=modin.pandas.read_csv('test.dat',header=0,index_col=[0,1])
     11 g2=csv2.groupby(by=lambda x:x[1]<3)
---> 12 df_g=csv2.groupby('p0').get_group('A')

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed, **kwargs)
    349         elif isinstance(by, str):
    350             idx_name = by
--> 351             by = self.__getitem__(by)._query_compiler
    352         elif is_list_like(by):
    353             if isinstance(by, Series):

~/.local/lib/python3.7/site-packages/modin/pandas/base.py in __getitem__(self, key)
   3200             return self._getitem_slice(indexer)
   3201         else:
-> 3202             return self._getitem(key)
   3203 
   3204     def _getitem_slice(self, key):

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in _getitem(self, key)
   1812             # return self._getitem_multilevel(key)
   1813         else:
-> 1814             return self._getitem_column(key)
   1815 
   1816     def _getitem_column(self, key):

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in _getitem_column(self, key)
   1816     def _getitem_column(self, key):
   1817         if key not in self.keys():
-> 1818             raise KeyError("{}".format(key))
   1819         s = self._reduce_dimension(self._query_compiler.getitem_column_array([key]))
   1820         s._parent = self

KeyError: 'p0'

In [2]: csv2.groupby(level=0).groups.keys()
Out[2]: dict_keys([])


```

**Comment by devin-petersohn** [comment]
Sorry for the `ModuleNotFoundError: No module named 'distributed', that will be fixed shortly. We added Dask support, so we need to make sure we selectively install it. You haven't made any mistakes here

The `level` issue was fixed, but not the name of the label. That will be relatively straightforward to fix. I am out of the country at the moment, so I will do my best to get this fixed since I have identified the main source of the issue.

**Comment by agardelein** [comment]
I confirm the issue is solved with these changes.

For the installation had to do `pip3 uninstall modin` then `pip3 install modin` instead of `--force-reinstall` due to many `NewConnectionError (...) Name or service not known (...)` probably due to server issue.

Pushing modin tests a bit further I tried this:
```
g1bis=csv1.groupby(['p0', 'p1'])
g2bis=csv2.groupby(['p0', 'p1'])
```

Leading to:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-143388c9626e> in <module>()
----> 1 g2bis=csv2.groupby(['p0', 'p1'])

~/.local/lib/python3.7/site-packages/modin/pandas/dataframe.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed, **kwargs)
    370                 pass
    371             elif mismatch:
--> 372                 raise KeyError(next(x for x in by if x not in self))
    373 
    374         if by is None and level is not None and axis == 0:

KeyError: 'p0'
```
Is this an expected behavior ?

**Comment by devin-petersohn** [comment]
Thanks @agardelein, this is very helpful! Our error checking within `groupby` related to MultiIndex has historically been more strict than pandas and we want to change this. Would you open a new issue for the list of labels from the Index so we can track it separately? Thanks!
