### ISSUE TITLE
Location of `from_pandas` code

### ISSUE THREAD

**Issue by dulinda** [modin-project/modin#762]
### System information
- **Modin version**: 0.5.4

### Describe the problem

The `from_pandas` code seems to have the same function as some of the `read_csv` code so should it be moved to io.py for consistency?

**Comment by devin-petersohn** [comment]
Thanks @dulinda, I agree. `from_pandas` should share code with the other data ingest methods.

**Comment by mvashishtha** [comment]
By version bd326f1c4175102489f08d271a53cf374bd9125e or earlier, `from_pandas` is in the IO code: https://github.com/modin-project/modin/blob/41e32e9edcd1e6755d6f959e573f807a75c7ae7e/modin/core/io/io.py#L60
