### ISSUE TITLE
UserWarning: `Series.__getstate__` defaulting to pandas implementation. 

### ISSUE THREAD

**Issue by FlamesCN** [modin-project/modin#764]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 18.04.1 LTS
- **Modin installed from (source or binary)**:binary
- **Modin version**:0.5.4
- **Python version**:3.6.8
- **Exact command to reproduce**:
The ‘merged’ is a DataFrame that 'modin.pandas.concat(list)' function generates. The column of ‘ticker’ is a series that the type of element  is an integer.
```
merged['ticker'] = merged['ticker'].astype(str)
```

### Describe the problem

Then raise a warning:
```
UserWarning: `Series.__getstate__` defaulting to pandas implementation.
```
The program is stuck and don't go on.

**Comment by devin-petersohn** [comment]
Thanks @FlamesCN for reporting this.

I narrowed down the issue to how we assign columns. Apparently, we have a bug in assigning a column after it has been modified, so it will be relatively easy to fix. Thanks for the report!
