### ISSUE TITLE
[Packaging] What about conda?

### ISSUE THREAD

**Issue by Hoeze** [modin-project/modin#797]
It would be cool to have a modin package in conda-forge

**Comment by williamma12** [comment]
That is one of our goals with the next release! Conda forge requires that
all of our dependencies be on conda forge and before we used to rely on
ray, which was not on conda forge. However, with the upcoming release,
modin is going to not depend on any engine (e.g., Ray, Dask). As a result,
with the next release (which should be soon), we will be able to be on
conda forge!

**Comment by Hoeze** [comment]
Thanks, cool that you're on it already!

**Comment by devin-petersohn** [comment]
Linking PR in conda-forge for reference: https://github.com/conda-forge/staged-recipes/pull/8471

**Comment by BraINstinct0** [comment]
> Linking PR in conda-forge for reference: [conda-forge/staged-recipes#8471](https://github.com/conda-forge/staged-recipes/pull/8471)
Seems like build on only Windows was successful, maybe wanna check?

**Comment by devin-petersohn** [comment]
Thanks @BraINstinct0, I will make some time to get it for the next release.

Because of the issue with Ray not being on conda, we have to work around it in our own build process and update accordingly.

**Comment by ianozsvald** [comment]
I'd love to see conda supported, running a mixed conda environment (for teaching) with "tacked on" pip installs is definitely a bit more complicated for students. Thanks for the package!

**Comment by devin-petersohn** [comment]
Conda was just added. This was a non-trivial effort because Ray is not supported on conda. Thanks all for your patience.
