### ISSUE TITLE
sliceing with datetimeindex is not working as expected

### ISSUE THREAD

**Issue by dwSun** [modin-project/modin#798]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin installed from (source or binary)**:pypi
- **Modin version**:0.6.0
- **Python version**:3.6.8
- **Exact command to reproduce**:

### Describe the problem
with modin:
```py
import modin.pandas as pd
df = pd.DataFrame(data={'data': range(10)}, index=pd.date_range('2017/1/4',periods=10))
print(df['2017-01-06':'2017-01-09'])
```
 I got this:
```sh
            data
2017-01-04     0
2017-01-05     1
2017-01-06     2
2017-01-07     3
2017-01-08     4
2017-01-09     5
```

but  with pandas:
```py
import pandas as pd
df = pd.DataFrame(data={'data': range(10)}, index=pd.date_range('2017/1/4',periods=10))
print(df['2017-01-06':'2017-01-09'])
```
 I got this:
```sh
            data
2017-01-06     2
2017-01-07     3
2017-01-08     4
2017-01-09     5

```

**Comment by devin-petersohn** [comment]
Hi @dwSun, thanks for posting! 

I can reproduce the bug, and it looks like an issue with how we handle slices that don't contain numeric indices.

```python
df[2:6] # works
```

I will dig into this before the next release, thanks again for posting!
