### ISSUE TITLE
Efficient View Structure for reindexing

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#80]
After the backend re-write, we no longer have a global view of `global_index` -> (`blk_index`, `internal_index`) exists anywhere. This makes re-index doing a full copy (it will be a bottleneck for distributed case). This also creates problem for DataManagerView. Take the following example:
```py
In [6]: df
Out[6]:
   col1  col2  col3
0     1     6    10
1     2     7    11
2     3     8    12
3     4     9    13

In [7]: df.iloc[:, [1,2,0]]
Out[7]:
   col2  col3  col1
0     6    10     1
1     7    11     2
2     8    12     3
3     9    13     4
```

Say the dataframe is partitioned as (2,2) blocks. Block widths: `[2,1]`. So many rows of `col1` and `col2` shares RemotePartitions. The correct DataManagerView does not support operation like this. It is applying an `iloc` call to _internal_ dataframes. This does not work in this case. 

We need a way to shuffle without gathering data. Here's an idea. Whenever we need to do a shuffle, we brake the metadata down to each row/column and duplicate certain RemotePartition object, then attach an apply_func to select certain columns. Here's an example:

- Blocks look like this:
![image](https://user-images.githubusercontent.com/21118851/45612409-b7796300-ba17-11e8-835e-ed109e1fe8f2.png)

When we are going to reorder `['col1', 'col2', 'col3', 'col4']` into `['col3', 'col2', 'col4', 'col1']`, blocks will be organized as follows to re-present the dataframe:

![image](https://user-images.githubusercontent.com/21118851/45612423-bfd19e00-ba17-11e8-9bb2-bbc8ff92ed18.png)

I'm not planning on implementing this in the re-write. But it would be great to include it in the repartition/efficient shuffle PR.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
