### ISSUE TITLE
Can't install modin[dask] on Windows

### ISSUE THREAD

**Issue by elcidhani** [modin-project/modin#803]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin installed from (source or binary)**:  binary
- **Modin version**: 0.6
- **Python version**: 7.7.3
- **Exact command to reproduce**:  pip install "modin[dask]"

When I run pip install with modin[dask], I get the below error:
ERROR: Could not find a version that satisfies the requirement ray==0.7.3 (from modin[dask]) (from versions: none)
ERROR: No matching distribution found for ray==0.7.3 (from modin[dask])

I thought the new version already supports Windows?

Thanks

**Comment by devin-petersohn** [comment]
Hi @elcidhani, it is supported, but the `install_requires` had included `ray`, which is not supported on windows.

We fixed this for the next release which should be done today.

**Comment by devin-petersohn** [comment]
0.6.1 was just released, please reopen if the issue persists.
