### ISSUE TITLE
Internal Feature Request: Hook for Converting Incoming Types

### ISSUE THREAD

**Issue by lightsighter** [modin-project/modin#807]
This is a request to add a hook inside of the Modin implementation so that custom implementations of the query compiler interface can inspect incoming types and determine if they can be automatically converted to a query compiler without having to first convert them to a base Pandas type. In most cases the answer will probably be no and the default path will likely be used, but some custom query compilers may know how to convert types from other Python libraries into query compilers with significantly less work, hence the need for a hook. Here is the relevant bit of code:
https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L56-L83
and some psuedo code to suggest what the functionality should do:
```
if isinstance(data, (DataFrame, Series)):
    ... already a modin type
elif query_compiler is None:
   if query_compiler_cls.can_convert(data):
        self.query_compiler = query_compiler_cls.convert(data)
   else:
        ... explicit conversion
else:
    self.query_compiler = query_compiler
```

**Comment by devin-petersohn** [comment]
Thanks @lightsighter, this will be useful!
