### ISSUE TITLE
Fix Pyarrow CSV reader for experimental API

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#824]
### Describe the problem

Because of changes in the pyarrow API, the CSV reader is no longer up to date: https://github.com/modin-project/modin/blob/7466cccd7e0261ab47317353edbe966edc7b8834/modin/experimental/engines/pyarrow_on_ray/io.py#L43-L57

This code needs to be updated to the latest pyarrow that is available and shipped with Ray.

Once that is fixed, we should re-enable the testing of the experimental pyarrow backend.

**Comment by YarShev** [comment]
We removed PyarrowOnRay execution in https://github.com/modin-project/modin/pull/6848 so closing this issue.
