### ISSUE TITLE
Link to Pandas Documentation in our own Docs for usage

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#84]
For reference it is useful to have links to the Pandas documentation page from our own documentation.

This should be possible with a script and hopefully would not require significant manual data entry. 

We can discuss here whether to create a new page for the links, or to just link from the existing methods pages.

**Comment by devin-petersohn** [comment]
Hi @nandan-pc thanks for asking! Yes, this is still open. I think creating a new page under `Using Modin` makes the most sense, with the list of methods/APIs hyperlinked to the pandas Documentation page for each. Perhaps in the future we can also put the parameters for each in an adjacent column for quick reference.

Let me know you have any questions!

**Comment by Kopurlso** [comment]
Hi @devin-petersohn 
Was taking a look at this, did you have an idea of how specifically you wanted to links to be integrated? Two options off the top of my head include hyperlinking all mentions of pandas as well as pandas methods/objects or creating a subsection at the bottom that populates automatically based off of mentions made in the body.

**Comment by Kopurlso** [comment]
#397 

Hey @devin-petersohn,
So after giving it more thought, not sure if it's worth the trouble of creating a separate script since it seems cumbersome to hyperlink every mention, I just decided to hyperlink the first mentions of any new pandas modules in the using_modin.rst to start. If that's okay, I can just edit the rest of the .rst files in the doc folder to align with this approach.

**Comment by devin-petersohn** [comment]
Thanks @Kopurlso, that makes sense. We do have a large file called [pandas_supported.rst](https://github.com/modin-project/modin/blob/master/docs/pandas_supported.rst) that contains a list of all of the methods we support. The script concept was mostly intended to help with that file. If you find it easier to do it without a script, that is also fine.

The first mention of each component is the right approach. There is a precedent for that in most documentation.

**Comment by Kopurlso** [comment]
Ooh, I see what you're talking about. Was the hope to hyperlink all the individual methods in pandas_supported.rst back to pandas?

**Comment by devin-petersohn** [comment]
Eventually, yes that was the hope. We sometimes get questions on usage, and it would be nice to just have a link from the documentation.

**Comment by loopyme** [comment]
Hi, I wrote a [script](https://github.com/loopyme/docTools/blob/master/get_pandas_api.py) to hyperlink all the individual methods in dataframe_supported.rst and I have already send a PR #749 . If this way is appropriate, I may able to hyperlink all the individual methods in other files.

However, some apis do not appear in the Pandas Doc. Here is what my script says:
```
WARNING: pandas.DataFrame.consolidate is not found
WARNING: pandas.DataFrame.convert_objects is not found
WARNING: pandas.DataFrame.value is not found
WARNING: pandas.DataFrame.from_csv is not found
WARNING: pandas.DataFrame.reindex_axis is not found
WARNING: pandas.DataFrame.select is not found
WARNING: pandas.DataFrame.sortlevel is not found
WARNING: pandas.DataFrame.to_panel is not found
```
Some of them may be removed or deprecated from Pandas

**Comment by devin-petersohn** [comment]
Thanks @loopyme, I took a look and it looks great!

Those APIs could have been removed from the documentation but not yet from the API, that doc was generated based on the API.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
