### ISSUE TITLE
get_dummies doesn't update columns variable

### ISSUE THREAD

**Issue by Rdlenke** [modin-project/modin#842]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin installed from (source or binary)**: pypi
- **Modin version**: 0.6.2
- **Python version**: 3.6.8

### Describe the problem
```get_dummies``` doesn't update the dataframe columns variable. EDIT: Actually, it appears that it doesn't update anything in the dataframe, since the ```.shape``` of the returned dataframe stays the same.

With pandas:
```py
import pandas as pd

df = pd.DataFrame({'categories': ['one', 'two', 'three', 'four']})
df = pd.get_dummies(df)
df
```

Gives me:
```py
   categories_four  categories_one  categories_three  categories_two
0                0               1                 0               0
1                0               0                 0               1
2                0               0                 1               0
3                1               0                 0               0
```

and ```df.columns``` outputs:
```
Index(['categories_four', 'categories_one', 'categories_three',
       'categories_two'],
      dtype='object')
```

With modin:

```py
import modin.pandas as pd

df = pd.DataFrame({'categories': ['one', 'two', 'three', 'four']})
df = pd.get_dummies(df)
df
```

Gives

```py
   categories_four  categories_one  categories_three  categories_two
0                0               1                 0               0
1                0               0                 0               1
2                0               0                 1               0
3                1               0                 0               0
```

But ```df.columns``` gives

```py
Index(['categories'], dtype='object')
```

**Comment by devin-petersohn** [comment]
Hi @Rdlenke, thanks for posting!

This is a bug with the metadata calculation after the computation has finished. We keep the metadata separate for performance reasons, so this will be a quick fix. The computation is still correct, but if you do `df.columns` that value will not be correct. As you point out `shape` is also an issue, but `shape` is using the columns to determine the size. 

Thanks again for posting! I will get this fixed today.

**Comment by Rdlenke** [comment]
@devin-petersohn Well, that explains it. I thought that there was something wrong with _fold, but couldn't point what was it.

Thanks for answering!

**Comment by devin-petersohn** [comment]
Yes, it was a misuse of `_fold` trying to use an optimization that isn't possible for the `get_dummies` case. Thanks again for the report!
