### ISSUE TITLE
RuntimeError for multiprocessing

### ISSUE THREAD

**Issue by junxu-ai** [modin-project/modin#843]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 + CUDA
- **Modin installed from (source or binary)**: pip install modin[dask]
- **Modin version**: 0.6.2
- **Python version**:3.6
- **Exact command to reproduce**: 

import modin.pandas as pd
df=pd.read_csv(r"c:\temp\huge_size_csv.csv")

### Describe the problem

RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
                if __name__ == '__main__':
                    freeze_support()
                    ...
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
### Source code / logs

import modin.pandas as pd
df=pd.read_csv(r"c:\temp\huge_size_csv.csv")

Note that there is no issue if i run the code in the python console one by one.  However, in this case, the time cost of modin is longer than the normal pandas.

**Comment by devin-petersohn** [comment]
Hi @junxuwdc, thanks for posting!

For the dask backend, I/O support is not completely finished yet. #754 is a first step toward that and the I/O support for dask will be ready for the next release.

For the `freeze_support` issue, I will take a look at that as well. Thanks for reporting!

Thanks again for posting!

**Comment by janwendt** [comment]
same problem here.

**Comment by devin-petersohn** [comment]
Thanks @junxuwdc and @janwendt, this is related to https://github.com/dask/distributed/issues/2520.

I can put the fix in today, thanks!

**Comment by devin-petersohn** [comment]
For a quick fix, you can just add the following to your script:

```python
if __name__ == "__main__":
    import modin.pandas as pd
    df=pd.read_csv(r"c:\temp\huge_size_csv.csv")
    ...
```

I am not sure of the right way to handle this in Modin at the moment after digging into it a bit.

Since this isn't related to the `read_csv` Not Implemented issue I'm going to remove the tags related to that.

**Comment by ee-** [comment]
+1 for the issue.

Windows 10. py3.7 :(

**Comment by devin-petersohn** [comment]
@ee- This is not fixable. It is a property of Dask Client when running on Windows, and cannot be bypassed. Unfortunately the only fix is the one listed above.

**Comment by chetansurwade** [comment]
> @ee- This is not fixable. It is a property of Dask Client when running on Windows, and cannot be bypassed. Unfortunately the only fix is the one listed above.

Well this project is significantly very new and in early stage, yet I would appreciate if this could be fixed? Even with the work around you provided, i can not import the library in other modules where pandas is being used as they are not in __main__ namespace.

**Comment by gshimansky** [comment]
I am not sure that this problem is Windows specific. I've seen Dask output tons of exceptions on Linux when I forgot to add `if __name__ == "__main__":` to my program. So it is definitely Dask specific, but I think it is cross-patform.

**Comment by chetansurwade** [comment]
> I am not sure that this problem is Windows specific. I've seen Dask output tons of exceptions on Linux when I forgot to add `if __name__ == "__main__":` to my program. So it is definitely Dask specific, but I think it is cross-patform.

Okay, Any progress with Ray backend on Windows? Ray is also a Berkeley project, so the cross platform integration of the two should be the priority, at least that's what i think.

**Comment by chetansurwade** [comment]
Lets say i import this in main file, Is there a way I could use this import in other files as well like other modules, if yes then how?

**Comment by chetansurwade** [comment]
Really liked the project but, can not use it. Any help here appreciated.

**Comment by devin-petersohn** [comment]
@chetansurwade It may help to initialize a Dask client before you import modin:

```python
from distributed import Client
client = Client()
import modin.pandas as pd
```

You should only initialize the client once in the project. Modin can connect to it after it is created.

**Comment by chetansurwade** [comment]
Tried with it. Didn't work. I have multiple modules using pandas and as suggested in the documentation i replaced the import statement, I've also tried the approach you mentioned, initializing dask client in main file - didn't work, in __init__ file didn't work after __name__ == __main__ in main file- didn't work.

**Comment by chetansurwade** [comment]
So basically either I'll have to wait for ray on windows or dig into the issue myself :-(

**Comment by chetansurwade** [comment]
I'll wait for a stable release in that case and use just pandas till then. Thanks for the information anyway.

**Comment by sivasai-quartic** [comment]
same issue, I'm using ubuntu 18.04. It's working fine with ray. but when I added env to dask. It keeps throwing this error even for the small code.

tried sample code:
`
from distributed import Client
client = Client(n_workers=6)
import modin.pandas as pd

if __name__ == '__main__':
    
    path= "path/to/file"
    modin_df = pd.read_parquet(path)
    modin_df.to_parquet("path2/test.parquet")
    print(f'Modin DF len = {len(modin_df)}')`

`Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /usr/lib/python3.6/asyncio/tasks.py:530> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 291, in start
    response = await self.instantiate()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 374, in instantiate
    result = await self.process.start()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 567, in start
    await self.process.start()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()`

**Comment by itsmesrds** [comment]
@devin-petersohn same issue, I'm using ubuntu 18.04. It's working fine with ray. but when I added env to dask. It keeps throwing this error even for the small code.

tried sample code:
`
from distributed import Client
client = Client(n_workers=6)
import modin.pandas as pd

if __name__ == __main__:
    
    path= "path/to/file"
    modin_df = pd.read_parquet(path)
    modin_df.to_parquet("path2/test.parquet")
    print(f'Modin DF len = {len(modin_df)}')`

`Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /usr/lib/python3.6/asyncio/tasks.py:530> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 291, in start
    response = await self.instantiate()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 374, in instantiate
    result = await self.process.start()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 567, in start
    await self.process.start()
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == __main__:
                freeze_support()`

**Comment by chetansurwade** [comment]
> @devin-petersohn same issue, I'm using ubuntu 18.04. It's working fine with ray. but when I added env to dask. It keeps throwing this error even for the small code.
> 
> tried sample code:
> `
> from distributed import Client
> client = Client(n_workers=6)
> import modin.pandas as pd
> 
> if **name** == "**main**":
> 
> ```
> path= "path/to/file"
> modin_df = pd.read_parquet(path)
> modin_df.to_parquet("path2/test.parquet")
> print(f'Modin DF len = {len(modin_df)}')`
> ```
> 
> Error trace:
> 
> `Task exception was never retrieved
> future: <Task finished coro=<_wrap_awaitable() done, defined at /usr/lib/python3.6/asyncio/tasks.py:530> exception=RuntimeError('\n An attempt has been made to start a new process before the\n current process has finished its bootstrapping phase.\n\n This probably means that you are not using fork to start your\n child processes and you have forgotten to use the proper idiom\n in the main module:\n\n if **name** == '**main**':\n freeze_support()\n ...\n\n The "freeze_support()" line can be omitted if the program\n is not going to be frozen to produce an executable.',)>
> Traceback (most recent call last):
> File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
> return (yield from awaitable.**await**())
> File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 291, in start
> response = await self.instantiate()
> File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 374, in instantiate
> result = await self.process.start()
> File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/nanny.py", line 567, in start
> await self.process.start()
> File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
> res = func(*args, **kwargs)
> File "/home/srds/virtual_env/airflow_venv/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
> process.start()
> File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
> self._popen = self._Popen(self)
> File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
> return Popen(process_obj)
> File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in **init**
> super().**init**(process_obj)
> File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in **init**
> self._launch(process_obj)
> File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
> prep_data = spawn.get_preparation_data(process_obj._name)
> File "/usr/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
> _check_not_importing_main()
> File "/usr/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
> is not going to be frozen to produce an executable.''')
> RuntimeError:
> An attempt has been made to start a new process before the
> current process has finished its bootstrapping phase.
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ ==" __main__":
>             freeze_support()`
> ```

That's a dask related issue. Running dask in modular package environment or scripts is a mess.

**Comment by nightvision04** [comment]
Really looking forward to ray being added so I can use Modin in a modular context.

A bit surprised there isn't more activity on this issue.

**Comment by bverhoeff** [comment]
Same issue here with dask and modular structure. This excludes windows users. I'm sticking with handcrafted multiprocessing for now...

**Comment by devin-petersohn** [comment]
Thanks everyone for the comments. As I mentioned above, this cannot be fixed in Modin because it is a property of Dask that cannot be worked around. If you add an issue in Dask for this problem, please link here. It is not just tied to Windows environments, it is anyone using Dask. 

I have just tested preliminary Windows support for Ray on their nightly wheels, it is working quite well. We are waiting for the next Ray release to make a bigger public comment about this and update the build process to favor Ray on Windows as well.

**Comment by mariobm** [comment]
What worked for me is this:
OS: Windows 10
Python: 3.9 
CSV file size: 724mb
```py
if __name__ == '__main__':
    import multiprocessing.popen_spawn_win32
    import modin.pandas as pd
    df = pd.read_csv("ratings.csv", sep="\t")
    print(df.head())
```

**Comment by Vaderv** [comment]
hope it gets resolved

**Comment by mvashishtha** [comment]
> As I mentioned above, this cannot be fixed in Modin 

@devin-petersohn I'm going to close this issue, then.
