### ISSUE TITLE
Plotting with seaborn 

### ISSUE THREAD

**Issue by Skvortsovg** [modin-project/modin#847]
Hello!
Please, add the ability to visualize with the seaborn module.
Now, I receive following message:

`TypeError: 'data' must be pandas DataFrame object, not: <class 'modin.pandas.dataframe.DataFrame'>`

**Comment by devin-petersohn** [comment]
Hi @Skvortsovg, thanks for posting!

This is something we are aware of, but I'm not sure it can be done (safely) in Modin because that check is happening in the seaborn package. We could override the `__class__` attribute of the `modin.pandas.DataFrame` object, but that presents a number of challenges when libraries are using internal APIs (things like `_data`, which we don't have an alias for because our data is distributed). 

There's a possibility to add this, but it may still not work. I will make some time to investigate this to see if there's a possibility here.

**Comment by devin-petersohn** [comment]
It should be possible to add support for this. Marking as "Help Wanted" until I can get to it.

**Comment by mvashishtha** [comment]
See also #3967.

**Comment by sugizo** [comment]
the code works well on pandas 
```
eco = 'eco'
count = 'count'
top = 10

if result == 'all':
    groupby = df[(df[eco].notnull() ) & (df[eco] != '') ].groupby([eco] ).size().reset_index(name = count)
else:
    groupby = df[(df[eco].notnull() ) & (df[eco] != '') ].query(query).groupby([eco] ).size().reset_index(name = count)

sort_groupby = groupby.sort_values([count, eco], ascending = [False, True] ).head(top)
```

but not in modin that have an error occured
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-22-99773b7725e4>](https://localhost:8080/#) in <cell line: 2>()
      1 # error
----> 2 sns.barplot(data = sort_groupby, x = eco, y = count)

7 frames
[/usr/local/lib/python3.10/dist-packages/modin/pandas/base.py](https://localhost:8080/#) in __nonzero__(self)
   3759             Always since truth value for self is ambiguous.
   3760         """
-> 3761         raise ValueError(
   3762             f"The truth value of a {self.__class__.__name__} is ambiguous. "
   3763             + "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

best regards

**Comment by anmyachev** [comment]
@labanyamukhopadhyay do you think we can close this issue? Or is there something left to be done here?

**Comment by labanyamukhopadhyay** [comment]
@anmyachev Yes I believe this issue can be closed- seaborn and specifically `sns.barplot` as in the example above are currently interoperable with Modin. Users will have to install seaborn from Github for its most recent updates:`pip install "seaborn @ git+https://github.com/mwaskom/seaborn"`

**Comment by mvashishtha** [comment]
Thank you @labanyamukhopadhyay

**Comment by anmyachev** [comment]
Thanks @labanyamukhopadhyay!
