### ISSUE TITLE
 pandas.DatetimeTZDtype support

### ISSUE THREAD

**Issue by freshsun** [modin-project/modin#862]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Centos 6.4
- **Modin installed from (source or binary)**:
binary
- **Modin version**:
0.6.2
- **Python version**:
3.7.4
- **Exact command to reproduce**:
pd.Series([1573104809000000000],dtype=pd.DatetimeTZDtype(tz='dateutil/America/Detroit'))

### Describe the problem
ValueError: Unable to convert timezone `tzfile('/usr/share/zoneinfo/Asia/Shanghai')` to string. When using original pandas it's OK.

### Source code / logs

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-b9e9de10e4f9> in <module>
     23         if k is 'timestamp':
     24             print(dic[k])
---> 25             series[k] = pd.Series(dic[k],dtype=pd.DatetimeTZDtype(tz='dateutil/Asia/Shanghai'),name=k)
     26         else:
     27             series[k] = pd.Series(dic[k], dtype='object', name=k)

~/miniconda3/lib/python3.7/site-packages/modin/pandas/series.py in __init__(self, data, index, dtype, name, copy, fastpath, query_compiler)
     48                         name=name,
     49                         copy=copy,
---> 50                         fastpath=fastpath,
     51                     )
     52                 )

~/miniconda3/lib/python3.7/site-packages/modin/pandas/utils.py in from_pandas(df)
     21     from .dataframe import DataFrame
     22 
---> 23     return DataFrame(query_compiler=BaseFactory.from_pandas(df))
     24 
     25 

~/miniconda3/lib/python3.7/site-packages/modin/data_management/factories.py in from_pandas(cls, df)
     26     @classmethod
     27     def from_pandas(cls, df):
---> 28         return cls._determine_engine()._from_pandas(df)
     29 
     30     @classmethod

~/miniconda3/lib/python3.7/site-packages/modin/data_management/factories.py in _from_pandas(cls, df)
     30     @classmethod
     31     def _from_pandas(cls, df):
---> 32         return cls.io_cls.from_pandas(df)
     33 
     34     @classmethod

~/miniconda3/lib/python3.7/site-packages/modin/engines/base/io.py in from_pandas(cls, df)
     12     @classmethod
     13     def from_pandas(cls, df):
---> 14         return cls.query_compiler_cls.from_pandas(df, cls.frame_cls)
     15 
     16     @classmethod

~/miniconda3/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py in from_pandas(cls, df, data_cls)
     59     @classmethod
     60     def from_pandas(cls, df, data_cls):
---> 61         return cls(data_cls.from_pandas(df))
     62 
     63     index = property(_get_axis(0), _set_axis(0))

~/miniconda3/lib/python3.7/site-packages/modin/engines/base/frame/data.py in from_pandas(cls, df)
   1168         new_columns = df.columns
   1169         new_dtypes = df.dtypes
-> 1170         new_frame, new_lengths, new_widths = cls._frame_mgr_cls.from_pandas(df, True)
   1171         return cls(
   1172             new_frame,

~/miniconda3/lib/python3.7/site-packages/modin/engines/base/frame/partition_manager.py in from_pandas(cls, df, return_dims)
    304                 for j in range(0, len(df.columns), col_chunksize)
    305             ]
--> 306             for i in range(0, len(df), row_chunksize)
    307         ]
    308         if not return_dims:

~/miniconda3/lib/python3.7/site-packages/modin/engines/base/frame/partition_manager.py in <listcomp>(.0)
    304                 for j in range(0, len(df.columns), col_chunksize)
    305             ]
--> 306             for i in range(0, len(df), row_chunksize)
    307         ]
    308         if not return_dims:

~/miniconda3/lib/python3.7/site-packages/modin/engines/base/frame/partition_manager.py in <listcomp>(.0)
    302             [
    303                 put_func(df.iloc[i : i + row_chunksize, j : j + col_chunksize].copy())
--> 304                 for j in range(0, len(df.columns), col_chunksize)
    305             ]
    306             for i in range(0, len(df), row_chunksize)

~/miniconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py in put(cls, obj)
    117             A `RayRemotePartition` object.
    118         """
--> 119         return PandasOnRayFramePartition(ray.put(obj), len(obj.index), len(obj.columns))
    120 
    121     @classmethod

~/miniconda3/lib/python3.7/site-packages/ray/worker.py in put(value)
   2275                 worker.task_context.put_index,
   2276             )
-> 2277             worker.put_object(object_id, value)
   2278         worker.task_context.put_index += 1
   2279         return object_id

~/miniconda3/lib/python3.7/site-packages/ray/worker.py in put_object(self, object_id, value)
    396                 range(ray_constants.DEFAULT_PUT_OBJECT_RETRIES)):
    397             try:
--> 398                 self._try_store_and_register(object_id, value)
    399                 break
    400             except pyarrow.plasma.PlasmaStoreFull as plasma_exc:

~/miniconda3/lib/python3.7/site-packages/ray/worker.py in _try_store_and_register(self, object_id, value)
    416         """
    417         try:
--> 418             self.store_and_register(object_id, value)
    419         except pyarrow.plasma.PlasmaObjectExists:
    420             # The object already exists in the object store, so there is no

~/miniconda3/lib/python3.7/site-packages/ray/worker.py in store_and_register(self, object_id, value, depth)
    325                         memcopy_threads=self.memcopy_threads,
    326                         serialization_context=self.get_serialization_context(
--> 327                             self.current_job_id))
    328                 break
    329             except pyarrow.SerializationCallbackError as e:

~/miniconda3/lib/python3.7/site-packages/ray/utils.py in _wrapper(*args, **kwargs)
    517                 def _wrapper(*args, **kwargs):
    518                     with self.lock:
--> 519                         return orig_attr(*args, **kwargs)
    520 
    521                 self._wrapper_cache[attr] = _wrapper

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/_plasma.pyx in pyarrow._plasma.PlasmaClient.put()

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.serialize()

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.pxi in pyarrow.lib.SerializationContext._serialize_callback()

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py in _serialize_pandas_dataframe(obj)
    168             )
    169 
--> 170         return pdcompat.dataframe_to_serialized_dict(obj)
    171 
    172     def _deserialize_pandas_dataframe(data):

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/pandas_compat.py in dataframe_to_serialized_dict(frame)
    556 
    557         if isinstance(block, _int.DatetimeTZBlock):
--> 558             block_data['timezone'] = pa.lib.tzinfo_to_string(values.tz)
    559             if hasattr(values, 'values'):
    560                 values = values.values

~/miniconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/types.pxi in pyarrow.lib.tzinfo_to_string()

ValueError: Unable to convert timezone `tzfile('/usr/share/zoneinfo/Asia/Shanghai')` to string

**Comment by devin-petersohn** [comment]
Hi @freshsun, thanks for the report! This is a serialization issue with Ray, and I raised the issue in Ray: https://github.com/ray-project/ray/issues/6110

**Comment by devin-petersohn** [comment]
This was resolved in Ray, please reopen the issue if you still see the same problem after updating Modin/Ray.
