### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by withinboredom** [modin-project/modin#863]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Specs**: 64GB ram, 12 4ghz cores, SSD
- **Modin installed from (source or binary)**: Binary
- **Modin version**: 0.7.3
- **Python version**: 3
- **Exact command to reproduce**:

The following takes multiple tens of minutes to run with a 7gb file. Without Modin, it usually only takes a few moments.

```
import modin.pandas as pd

tbl_connections = pd.read_csv('vertices.csv')
tbl_connections['date_created'] = pd.to_datetime(tbl_connections.date_created)
tbl_connections.set_index('date_created', inplace=True, drop=False)
tbl_connections.head()
```

An example file can be created with the following schema:
```
| id (int) | to_id (int) | date_created (timestamp) | committed (short) |
```

### Describe the problem

I expected Modin to complete the job as fast or faster than regular pandas, I could really use it for other parts of the program. If there's a workaround, I'd appreciate it.

**Comment by devin-petersohn** [comment]
Hi @withinboredom, thanks for posting!

Are you saying that pandas is reading the 7GB file in a few moments? That has not been my experience, and testing things locally, I don't reproduce that behavior.

The code you wrote can actually be parameters to `read_csv`:

```python
import modin.pandas as pd
tbl_connections = pd.read_csv("vertices.csv", parse_dates="date_created", index_col="date_created")
tbl_connections.head()
```

It will run faster (probably in both modin and pandas) if you write it this way.

Some things like `pd.to_datetime` are not implemented and pass through pandas to make them work correctly. See the documentation here for more information: https://modin.readthedocs.io/en/latest/pandas_supported.html#defaulting-to-pandas

**Comment by withinboredom** [comment]
Thanks @devin-petersohn, that implementation is much faster!

> Are you saying that pandas is reading the 7GB file in a few moments?

It's likely the file is cached by the filesystem in RAM at this point, so it's quite quick :), especially with these changes + Modin!

For future reference, I had to rewrite it like:

```
tbl_connections = pd.read_csv("vertices.csv", parse_dates=["date_created"], index_col="date_created")
```
