### ISSUE TITLE
astype category doesn't change the actual dtype to categorical

### ISSUE THREAD

**Issue by bareini** [modin-project/modin#864]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin installed from (source or binary)**: binary (pip)
- **Modin version**:  0.6.2
- **Python version**: 3.6.9
- **Exact command to reproduce**:
```import modin.pandas as pd
a = pd.Series(['A', 'A', 'B', 'B', 'A'])
a.dtype
Out[4]: dtype('O')
a = a.astype('category')
a.dtype
Out[6]: 'category'
```
Whereas in the original pandas:
```
a = pd_org.Series(['A', 'A', 'B', 'B', 'A'])
a = a.astype('category')
a.dtype
Out[10]: CategoricalDtype(categories=['A', 'B'], ordered=False)
```
### Describe the problem
'astype' function is only changing the name of the type without changing it to `CategoricalDtype` (as expected in Pandas). 
Using the following workaround, the expected behavior is achieved:
```
a = pd.Series(['A', 'A', 'B', 'B', 'A']) 
a = pd.Series(a.values, dtype='category') 
a.dtype 
Out[13]: CategoricalDtype(categories=['A', 'B'], ordered=False)
```

### Source code / logs
The above causing the following issues (when relying on `CategoricalDtype`):
```
a = pd.Series(['A', 'A', 'B', 'B', 'A'])
a = a.astype('category')
a_df = a.to_frame()
a_df.select_dtypes('category')
Traceback (most recent call last):
  File "/home/bar/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-15c3ee7df6bb>", line 1, in <module>
    a_df.select_dtypes('category')
  File "/home/bar/.local/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 1412, in select_dtypes
    is_dtype_instance_mapper, self.dtypes.iteritems()
  File "/home/bar/.local/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 1409, in is_dtype_instance_mapper
    return column, functools.partial(issubclass, dtype.type)
AttributeError: 'str' object has no attribute 'type'
```

**Comment by devin-petersohn** [comment]
Hi @bareini, thanks for the report! It looks like our optimization is oversimplifying the `dtype` in the case of `Categorical`.

This should be relatively easy to fix, but in the meantime you can reset the dtypes with:

```python
a._query_compiler._modin_frame._dtypes = None
a.dtype                                                                                                                                                                       
Out[9]: CategoricalDtype(categories=['A', 'B'], ordered=False)
```

This will force Modin to recompute the dtypes as if we could not infer them. Thanks again for the report!

**Comment by susmitpy** [comment]
@devin-petersohn 
The same issue occurs when,
`modin.pandas.Categorical()` is used. The resulting dtype is not category, it is what it was earlier, float, object, int

**Comment by devin-petersohn** [comment]
Hi @susmitpy thanks for the comment! Can you open a new issue for that case? This one is a little old and it will help to track it (to get it fixed 😄).

**Comment by susmitpy** [comment]
@devin-petersohn 
Sure !

**Comment by susmitpy** [comment]
@devin-petersohn 
Have a look at #3895
