### ISSUE TITLE
Running modin.pandas.read_csv() throwing error

### ISSUE THREAD

**Issue by yahoyoungho** [modin-project/modin#873]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux
- **Modin installed from (source or binary)**:
-pip3 install "modin[complete]"
- **Modin version**:
-0.6.2
- **Python version**:
-3.5.3
- **Exact command to reproduce**:
```python
import ray
ray.init(num_cpus=25, object_store_memory=75*1000*1024*1024)
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pd
```

### Describe the problem

Currently, I am trying to load a sparse matrix with around  6million rows and 2000 columns (around 25GB) using jupyter notebook. 

I have tried several differnt num_cpus and object_store_memory parameter values and they almost always throw this error. (If this read_csv() function works, then usually some other functions involving modin.pandas throw this error or that some worker already exist)

Also, I always wait few seconds after each cell is ran that has modin.pandas in it

### Source code / logs

RayTaskError                              Traceback (most recent call last)
<ipython-input-2-8c34af9f1819> in <module>
----> 1 mat = pd.read_csv("refOriMatzero.vcf",sep="\s+")

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     95         if not kwargs.get("sep", sep):
     96             kwargs["sep"] = "\t"
---> 97         return _read(**kwargs)
     98 
     99     return parser_func

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/pandas/io.py in _read(**kwargs)
    108         kwargs: Keyword arguments in pandas.read_csv
    109     """
--> 110     pd_obj = BaseFactory.read_csv(**kwargs)
    111     # This happens when `read_csv` returns a TextFileReader object for iterating through
    112     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/data_management/factories.py in read_csv(cls, **kwargs)
     50     @classmethod
     51     def read_csv(cls, **kwargs):
---> 52         return cls._determine_engine()._read_csv(**kwargs)
     53 
     54     @classmethod

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     54     @classmethod
     55     def _read_csv(cls, **kwargs):
---> 56         return cls.io_cls.read_csv(**kwargs)
     57 
     58     @classmethod

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/engines/ray/generic/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    680         if cls.read_csv_remote_task is None:
    681             return super(RayIO, cls).read_csv(**kwargs)
--> 682         return cls._read(**kwargs)
    683 
    684     @classmethod

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/engines/ray/generic/io.py in _read(cls, filepath_or_buffer, **kwargs)
    766             return cls._read_csv_from_pandas(filepath_or_buffer, filtered_kwargs)
    767         else:
--> 768             return cls._read_csv_from_file_ray(filepath_or_buffer, filtered_kwargs)
    769 
    770     @classmethod

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_ray(cls, filepath, kwargs)
    503         # over the whole column for each column. The index is set below.
    504         dtypes = (
--> 505             pandas.concat(ray.get(dtypes_ids), axis=1)
    506             .apply(lambda row: find_common_type(row.values), axis=1)
    507             .squeeze(axis=0)

~/Store/Cardiomics/python_dir/python_project/lib/python3.5/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayTaskError: ray_worker:modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray() (pid=2950, host=complex2)
ray.exceptions.UnreconstructableError: Object 0369a14bc595e08cfbd508dfaa162cb7feffffff is lost (either evicted or explicitly deleted) and cannot be reconstructed.

**Comment by devin-petersohn** [comment]
Hi @yahoyoungho, thanks for posting! A few questions to start:

- Does the same thing happen when you do not specify `ray.init` parameters beforehand?
- We recently released, can you update Modin (`pip isntall -U modin`) and see if this still happens?
- After you update, would you also be able to check if the issue is present with the Dask engine?
- Does this also happen with [out of core](https://modin.readthedocs.io/en/latest/out_of_core.html) enabled?

I am involved in a project that is working to make reading VCF and other genomic formats easier in Modin ([link](https://github.com/bigdatagenomics/mango/pull/536)), and we have tested with some genomic files of this size and larger so it isn't the file or support in the library. Ray has some strict rules when it comes to memory, I have been working with them on getting some of these things resolved.

**Comment by yahoyoungho** [comment]
Hello @devin-petersohn, so I have tried running the same thing without using ray.init() and along with update Modin package. 
So far all the code seems to be running fine. However, I have not tried checking it with dask engine yet. Also, when I was running into this problem, out_of_core=True did not really work fine, if i remember correctly.

I have some questions then. Is it currently not possible to work with set number of cores using ray.init()? or is there another way to do this?

**Comment by devin-petersohn** [comment]
>I have some questions then. Is it currently not possible to work with set number of cores using ray.init()? or is there another way to do this?

Yes, you can set the number of cores with `ray.init`, but you also need to specify memory requirements. You were requesting 75TB of memory, Ray probably did not fully accept this number. We set Ray's allotted memory to 60% of total memory.

If you try `pd.DEFAULT_NPARTITIONS = 25`, Modin will reduce the number of partitions to 25 which will also reduce the number of cores used at any given time. This may sometimes use more than 25 if you are trying to do multiple computations at once, but it might serve your purposes better. This isn't the intended use of this variable, but it might work well for you. Let me know if this helps!

**Comment by mvashishtha** [comment]
I'm closing this issue as stale. Please comment if it's still relevant.
