### ISSUE TITLE
df.assign() not working with index mismatches

### ISSUE THREAD

**Issue by ecoughlan** [modin-project/modin#876]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2
- **Modin installed from (source or binary)**: pip
- **Modin version**: 0.6.3
- **Python version**: 3.7.3
- **Exact command to reproduce**: See below

### Describe the problem
Assign does not work when "length of values does not match length of index", but it should for compatibility with pandas, see example below. This can happen for example with constructs like `df.query("foo > 0").assign(bar = df.a * df.b)`

### Source code / logs
Not working:
```python
import modin.pandas as pd
pd.DataFrame(data={"a": range(10)}).query("a != 5").assign(foo = pd.Series(range(10)))
```
working:
```python
import pandas
pandas.DataFrame(data={"a": range(10)}).query("a != 5").assign(foo = pandas.Series(range(10)))
```

**Comment by devin-petersohn** [comment]
Thanks for reporting @ecoughlan! I can reproduce it.

This behavior defaults to pandas, so it is interesting that it does not match pandas. Link to code for reference: https://github.com/modin-project/modin/blob/9966f6821155285b784b0670cb4e1b91a243b63d/modin/pandas/dataframe.py#L484-L485

I will dig into the source of this issue. Thanks for posting!
