### ISSUE TITLE
Trouble installing modin on WSL: No matching distribution found for pandas==0.25.3

### ISSUE THREAD

**Issue by NeoXx123** [modin-project/modin#880]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 with WSL (Windows Subsystem for Linux)
- **Modin installed from (source or binary)**:
- **Modin version**: Newest
- **Python version**: Anaconda Python 3.7 (Newest)
- **Exact command to reproduce**: pip install modin[ray]

I installed WSL (Windows Subsystem for Linux) and I am trying to install Modin on it. I am using Anaconda 3.7 within WSL and when I type 'pip install modin[ray]' I receive the following error message:   

_Could not find a version that satisfies the requirement pandas==0.25.3 (from modin) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
No matching distribution found for pandas==0.25.3 (from modin)_

Same error message occurs if I type 'pip install modin' or 'pip install modin'. I tried first installing pandas and ray and then modin, then tried first installing modin. Same result always.
Keep in mind I am running everything within WSL so its not Windows.

Any advice how to fix this?

**Comment by devin-petersohn** [comment]
Hi @NeoXx123, thanks for posting!

Does the same thing happen when you type `python3 -m pip install modin[ray]`?

The pip in your path looks like it is the python2 version, looking at the pandas distributions available. pandas dropped python2 in 0.25, which would explain why it's not in that list.

Let me know if this helps! I use WSL on a daily basis for development and testing so the issue shouldn't be related to that.

**Comment by devin-petersohn** [comment]
Hi @NeoXx123, I am going to close this in favor of tracking with #888, which is actionable from our side. Please feel free to open a new issue if you still have problems installing.
