### ISSUE TITLE
Missing 'title' method in StringMethods object

### ISSUE THREAD

**Issue by jh-wu** [modin-project/modin#887]
### System information
- **OS Platform and Distribution: Linux Ubuntu 16.04
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.6.3
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem
Got AttributeError: 'StringMethods' object has no attribute 'title' when I was trying to execute a line of code contains series.str.title().

I have checked the code in modin/pandas/series.py, method 'title' isn't there. Can you add it in or introduce a workaround? Thanks a lot!

### Source code / logs
modin/pandas/series.py

**Comment by devin-petersohn** [comment]
Hi @jh-wu, thanks for posting!

I will get this fixed before the next release, it shouldn't take long to implement. As a temporary workaround, you can do `series.apply(str.title)`.
