### ISSUE TITLE
Attribute name in the dataframe

### ISSUE THREAD

**Issue by DaielChom** [modin-project/modin#891]
Hi, I am testing modin and I have a problem, but I don't know if this problem is caused by the version of pandas of modin, The attribute "name" in the iloc change between pandas and modin.pandas.

![2](https://user-images.githubusercontent.com/22222488/70291037-f116c500-17a7-11ea-8f5e-ffccc6f80f11.png)

**Comment by devin-petersohn** [comment]
Thanks @DaielChom for reporting!

It looks like the name swapped with the index value between the two during the `iloc` call. I will dig into this and get it fixed for the next release. Thanks again for reporting!
