### ISSUE TITLE
a bug was found in the modin's read_csv() and query() method

### ISSUE THREAD

**Issue by crystalxiaoou** [modin-project/modin#894]
### System information
- **OS Platform and Distribution **:  macOS Mojave 10.14.5
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.6.3
- **Python version**: 3.7
- **Exact command to reproduce**: 

### Describe the problem
when I used modin.pandas read_csv() method in my python project,  there has a  bug!!!!
The problem is the first time I call read_csv() method in modin.pandas to load a csv file of 10W rows, It cost about 550ms , the second time I call read_csv() to load the same csv file , it cost about 100ms.
and I found that when I use the original pandas read_csv(), it only cost 250ms.  
so I think there has a bug of the modin.pandas read_csv() method.  

by the way,  I found the modin.pandas query() method have the same bug. 

### Source code / logs

import modin.pandas as pd
import time
now = time.time()
df = pd.read_csv("test.csv", header=None)
print("the frist time, pandas read_csv cost:", time.time() - now)

print("len:", len(df))

now = time.time()
df = pd.read_csv("test.csv", header=None)
print("the frist time, pandas read_csv cost:", time.time() - now)

print("len:", len(df))

### The Result for the bug
the frist time, pandas read_csv cost: 0.6014809608459473
len: 107665
the frist time, pandas read_csv cost: 0.11737322807312012
len: 107665

**Comment by devin-petersohn** [comment]
Hi @crystalxiaoou, thanks for posting.

This is not really a bug. Ray takes some time to start up and so the first operation typically has some small overheads associated, so what you're seeing in the first run is that cost. The second cost does not include this i.e. Ray is already "warmed" up so there is a lower cost.

`query` is similar in this respect. These are artifacts of the way that the Ray engine works.

**Comment by devin-petersohn** [comment]
We have made significant improvements to improving the performance at this scale. Closing this for now, please feel free to reopen if the issue persists!
