### ISSUE TITLE
How is `groupby().apply()` parallelized?

### ISSUE THREAD

**Issue by Hvass-Labs** [modin-project/modin#895]
(I see you want "general questions" written to a mailing-list, but I don't know how that works, so I hope it's OK to write my question here. I apologize for any inconvenience.)

It's a very interesting project you have made! I am currently testing to see if I can use it as the backend in a new financial data API I am working on, because I have some quite slow functions that group data by stock-tickers and perform calculations for each ticker individually.

I am particularly interested in parallelizing computations of the form `df.groupby('Ticker').apply(func)`, but currently Modin seems to take the same time as normal Pandas for this kind of computation.

Here's an example of how I would parallelize it using Python `multiprocessing.Pool`:

    # Apply this function for each stock individually.
    def func(df_grp):
        # Do something ...
        return df_grp_result

    
    # Split original DataFrame into sub-groups.
    groups_iter = df.groupby('Ticker')
    tickers, df_groups = zip(*groups_iter)

    # Parallel processing for each DataFrame sub-group.
    pool = multiprocessing.Pool()
    result = pool.map(func, df_groups)
    pool.close()
    pool.join()

    # Combine results back into a single DataFrame.
    df_result = pd.concat(result, axis=0)

But I can't actually implement it like this, because `multiprocessing.Pool` has several limitations that don't work so well with how the rest of my code-base has been structured (e.g. `func` cannot be a local function, or a lambda-function, etc.) I have also tried the pathos / multiprocess library, but it's actually slower than a single process for this kind of computation.

So I am wondering if you are planning on supporting the above kind of parallelization for `groupby().apply()`?

Thanks!

**Comment by devin-petersohn** [comment]
We don't find that parallelization for each group individually gains a significant amount because the cost of the `groupby` component is too high. There's often a lot of shuffling involved and it doesn't cost much more to do the computation while computing the `groups` (some caveats here of course, but in general). Originally I had tried to implement the parallelism in the way you describe but could not both make it efficient and keep the pandas semantics.

`groupby().apply` is parallelized over columns, and the apply is performed on a per-column basis. This can present some challenges depending on what the `apply` function is assuming. Also, if your dataset has only a few columns, the parallelism will be reduced (which may be what you saw). I have plans to tune the performance a bit with smaller column datasets, but I also have PhD student obligations because I would like to graduate eventually 😄. 

Let me know if this helps! Also, if you would like to you can also ask questions on the Discourse page: https://discuss.modin.org. You can also continue to ask questions here.

**Comment by Hvass-Labs** [comment]
Thanks very much for the quick and detailed response, I greatly appreciate that!

I don't quite understand how you can parallelize over columns? I often need to use data from different columns inside the `groupby().apply()` calculations.

In case you are interested in understanding my use-cases, here is a minimal working example that will automatically download the data and load it as Pandas DataFrames (you can also get fundamental financial data in the same way, which is where the magic really starts to happen with this new API).

You can install the simfin package using: `pip install simfin` but because it is early-early beta that changes a lot, it may be better to install directly from the github master:

    pip install git+https://github.com/simfin/simfin.git

Example code:

    import simfin as sf
    from simfin.names import *

    # SimFin data-directory.
    sf.set_data_dir('~/simfin_data/')

    # Get the free data.
    sf.set_api_key(api_key='free')

    # Download and load share-prices into Pandas DataFrame.
    df_prices = sf.load_shareprices(variant='daily', market='us')

    # Function to apply on a per-ticker basis.
    # These are typically much more complicated.
    def func(df_grp):
        return df_grp.rolling(20).mean()

    # Calculate using groupby().apply() takes about 20 seconds on my PC.
    df_result1 = df_prices.groupby(TICKER).apply(func)

    # Calculate using groupby().rolling() takes about 8 seconds on my PC.
    df_result2 = df_prices.groupby(TICKER).rolling(20).mean()

One reason for having `func()` work on a per-ticker basis, is that I have made a little helper-function called `sf.apply()` which can automatically detect whether the DataFrame contains one or more stocks, and then perform the calculation using `groupby().apply()` or just `func()` directly. For example:

    # Calculate for all stocks on a per-ticker basis.
    # For some reason (?) this only takes about 7 seconds on my PC.
    df_result3 = sf.apply(df=df_prices, func=func)

    # Calculate for a single stock. This takes 6 msec on my PC.
    df_result4 = sf.apply(df=df_prices.loc['MSFT'], func=func)

The helper-function `sf.apply()` is implemented here:

https://github.com/SimFin/simfin/blob/master/simfin/utils.py#L67-L130

Here are some examples of functions that use `sf.apply()` to perform `groupby().apply()` with functions similar to `func()` above, but much larger:

https://github.com/SimFin/simfin/blob/master/simfin/signals.py

For example:

    # Calculate price-signals for all stocks. This takes about 30 seconds on my PC.
    df_signals = sf.price_signals(df_prices=df_prices) 

My preliminary experiments suggest that this time-usage can be improved almost linearly with `multiprocessing.Pool.map()` but the problem is that local functions are not supported, so I would have to significantly restructure all my code into something that is not so elegant, and it would also make it difficult for users to make their own `func()` functions.

So I wonder if perhaps it would be possible for you to either provide a special Modin parameter in `groupby()`, or a special Modin function `groupby_apply()`, for doing this kind of parallelization that I need? In `sf.apply()` I could check if Modin is being used, and then switch to this special function.

Or if you have any other suggestions it would be appreciated.

I understand completely if you don't have time for this. It is already remarkable what you have made here (by yourself?). I wish you all the best with this project and your PhD!

PS: I found Pandas' `groupby()` function to be extremely weird and I have spent many days trying to understand it. It seems that some of its the semantics are inconsistent. It is certainly poorly documented. I still don't understand what `group_keys` and `as_index` are supposed to do. Sometimes they don't do anything and the doc-strings are only a few obscure lines.

**Comment by jonschwenk** [comment]
I am also finding that I have to disable modin when using groupby() + apply(). In my case, I need to use different functions to group different columns, so I place these lambda functions in a custom function that is passed to apply(). This only works if I can access all columns of the dataframe--parallelizing over columns seems to only make sense if the same function is used for all columns. Perhaps a flag could catch these cases and revert to regular pandas? I also couldn't figure out how to revert to regular pandas just for this function and ended up disabling modin entirely for this workflow, which is a shame!

**Comment by vnlitvinov** [comment]
> I also couldn't figure out how to revert to regular pandas just for this function and ended up disabling modin entirely for this workflow, which is a shame!

@jonschwenk you could convert from Modin DataFrame to Pandas and back using patterns like this:

```python
import modin.pandas as pd
from modin.pandas.utils import to_pandas
# do stuff
df = func_that_produces_modin_dataframe()
# do more stuff
...
# convert to pandas
pandas_df = to_pandas(df)
pandas_df.groupby('foo').apply(my_func)
# convert back to modin
df = pd.DataFrame(pandas_df)
# go on as usual using awesome Modin powers
```

**Comment by mvashishtha** [comment]
I'm closing this question because it's old, but you can follow in #3435 the bug where groupby-apply fails when the apply function access elements from another column.
