### ISSUE TITLE
read_csv bug

### ISSUE THREAD

**Issue by JenniferShelton** [modin-project/modin#897]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.4.1708
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.6.3
- **Python version**: 3.7.4
- **Exact command to reproduce**: 

```
import modin.pandas as pd

data = pd.read_csv(baf, skiprows=10, names = ['CHR', 'POS', 'REF_COUNT', 'ALT_COUNT', 'BAF'], dtype = {'CHR' : str}, sep='\t')

data.head()
    CHR    POS  REF_COUNT  ALT_COUNT                  BAF
0   CHR    POS  REF_COUNT  ALT_COUNT                  BAF
1  chrFAKE  FAKE1         FAKE          FAKE               0
2  chrFAKE  FAKE2         FAKE         FAKE   0
3  chrFAKE  FAKE3         FAKE         FAKE  0
```

### Describe the problem
I'm exploring modin now and I have a question. When I load a CSV file using skiprows modin does not skip the rows. Is this expected and if so should it come with a warning? This was described as a bug (that only occurs when names is used) on the google group.

**Comment by devin-petersohn** [comment]
Thanks for the report @JenniferShelton!

This is indeed a bug, and only happens when `names` and `skiprows` are set together. I will make sure this gets in the next release.

Here is a temporary workaround so you are not blocked on the next release:

```python
import modin.pandas as pd

names = ['CHR', 'POS', 'REF_COUNT', 'ALT_COUNT', 'BAF']
data = pd.read_table(baf, skiprows=10, header=None)
data.columns = names
data.head()
```
Let me know if this helps in the sort term. Thanks again for the report!
