### ISSUE TITLE
'NoneType' object has no attribute 'ncores'

### ISSUE THREAD

**Issue by lastrei** [modin-project/modin#905]
AttributeError                            Traceback (most recent call last)
<ipython-input-6-569b81e05d48> in <module>()
      1 import os
      2 os.environ["MODIN_ENGINE"] = "dask"  # Modin will use Dask
----> 3 import modin.pandas as pd

D:\Miniconda3\lib\site-packages\modin\pandas\__init__.py in <module>()
    225 
    226             client = Client()
--> 227         num_cpus = sum(client.ncores().values())
    228 elif execution_engine != "Python":
    229     raise ImportError("Unrecognized execution engine: {}.".format(execution_engine))

D:\Miniconda3\lib\site-packages\distributed\client.py in nthreads(self, workers, **kwargs)
   3093         if workers is not None and not isinstance(workers, (tuple, list, set)):
   3094             workers = [workers]
-> 3095         return self.sync(self.scheduler.ncores, workers=workers, **kwargs)
   3096 
   3097     ncores = nthreads

**Comment by devin-petersohn** [comment]
Hi @lastrei, thanks for posting!

What is the version of Dask/distributed/Modin/Python you are using?

From the traceback, the source of the error is in the distributed package, and I haven't been able to reproduce this.

**Comment by chenwest95** [comment]
I have the same probelm and my warning tells:UserWarning: The Dask Engine for Modin is experimental.
Traceback (most recent call last):

  File "<ipython-input-8-7e7b44bd7fd7>", line 1, in <module>
    import modin.pandas as pd

  File "D:\soft\python\lib\site-packages\modin\pandas\__init__.py", line 227, in <module>
    num_cpus = sum(client.ncores().values())

  File "D:\soft\python\lib\site-packages\distributed\client.py", line 3036, in nthreads
    return self.sync(self.scheduler.ncores, workers=workers, **kwargs)

AttributeError: 'NoneType' object has no attribute 'ncores'

**Comment by devin-petersohn** [comment]
@chenwest95 Would you be able to tell me the versions of the packages:

```python
import dask
print(dask.__version__)
import distributed
print(distributed.__version__)
```

I have been unable to reproduce this issue.

**Comment by lastrei** [comment]
sorry i'm late 
it's Modin version problem 
i uninstall Modin and re install in an old version it's working fine

**Comment by devin-petersohn** [comment]
@mecaloza What version of Modin are you using? The code from this part of Modin has changed a lot so it should not be running into this anymore.

The error is getting thrown from within Dask, so it is not something that Modin can control. We changed the way we access parts of Dask so we do not rely on Dask to compute the number of cores anymore.

**Comment by devin-petersohn** [comment]
This hsould be resolved, please reopen if the issue persists.

**Comment by lucasczpnk** [comment]
Having the same issue on python3.9:
```
dask version: 2021.01.0
modin version: 0.8.3
```

**Comment by devin-petersohn** [comment]
@lucasczpnk Does the issue persist if you install from the github master? 

https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by lucasczpnk** [comment]
@devin-petersohn Thank you!
It worked just fine.

**Comment by ma00** [comment]
the conda version has the same problem

**Comment by mvashishtha** [comment]
@ma00 could you please post your `dask` and `distributed` versions:

```python
import dask
print(dask.__version__)
import distributed
print(distributed.__version__)
```

Could you please also describe your operating system and your python version?

Does [this answer](https://stackoverflow.com/a/72320523/17554722) from StackOverflow help you?

**Comment by STTamhane** [comment]
I have this issue in a conda base environment. Python 3.7, modin is 0.12.1, distributed is 2021.10.0 and dask is 2021.10.0. Error message while reading modin.pandas read_csv was - 'NoneType' object has no attribute 'ncores'. Please help.

**Comment by mvashishtha** [comment]
@STTamhane I can't reproduce your error in an environment that should be similar. I have

- Operating System: macOS Monterey
- hardware: Macbook Pro (16-inch, 2019)
- python: 3.7.13
- modin: 0.12.1
- distributed: 2021.10.0
- dask: 2021.10.0

Could you please provide:
- a complete reproducer of the failure, including the CSV you are trying to read. if you can't send the entire CSV, please send some other CSV that reproduces the error.
- a complete stack trace
- tell how you installed modin (e.g. conda forge)

Also, are you able to upgrade to the latest versions of modin, dask, and distributed?

**Comment by STTamhane** [comment]
@mvashishtha My os is windows 10. The csv is very large. I will send another one instead and include the trace. Please note, that the same code works perfectly with pure Pandas.

modin[all] was pip installed.

I am in a corporate environment and cannot upgrade to the latest versions.
