### ISSUE TITLE
Single source of package version

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#906]
### Describe the problem

Version information is in 3 places. This issue would follow one of these guidelines to enforce that there is only one source for this: https://packaging.python.org/guides/single-sourcing-package-version/. That would simplify the release process and reduce potential bugs and mismatches.

### Source code / logs

Version is in these places: 
- https://github.com/modin-project/modin/blob/master/setup.py#L15
- https://github.com/modin-project/modin/blame/master/README.md#L10
- https://github.com/modin-project/modin/blob/master/modin/__init__.py#L62

**Comment by aeroaks** [comment]
Hi @devin-petersohn ,

Can I pick this up? Do we have any decision on what approach we want to take?

**Comment by devin-petersohn** [comment]
Sure @aeroaks, thanks for volunteering.

Dask uses Versioneer, I think it's a sensible approach. https://github.com/warner/python-versioneer

As an example, this is the PR that added it to Dask (it is from 2016 so some things are likely different). https://github.com/dask/dask/pull/1569, but it would be good to have versions based on the git hash as well.
