### ISSUE TITLE
when running  pd.read_sql(sql=qury,con=connstring, chunksize= chunk_size)) throws the error  TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by sumepr** [modin-project/modin#909]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 18.04.1
- **Modin installed from (source or binary)**:binary
- **Modin version**:0.6.3
- **Python version**:3.6.8
- **Exact command to reproduce**:pd.read_sql(sql=qury,con=connstring, chunksize= chunk_size))

### Describe the problem
when running 
pd.read_sql(sql=qury,con=connstring, chunksize= chunk_size)) throws the error 
TypeError: object of type 'generator' has no len()

### Source code / logs
source code
>>> limit=200000
>>> chunk_size=40000
>>> for from_row in range(1390001, rows, limit):
...     qury = f'''
...             SELECT
...                     *
...             FROM
...                     paper
...             ORDER BY
...                     id
...             LIMIT {limit} OFFSET {from_row}
...             '''
...     for i, chunk in enumerate(pd.read_sql(sql=qury,con=connstring, chunksize= chunk_size)):
...             chunk.to_csv('Data/paper/test/paper_fromRow_'+str(from_row)+ '_chunk_' + str(i+1)+'-'+str(chunk_size)  +'.csv', index=False)

--------------------------
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "lib/python3.6/site-packages/modin/pandas/io.py", line 321, in read_sql
    return DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
  File "lib/python3.6/site-packages/modin/data_management/factories.py", line 148, in read_sql
    return cls._determine_engine()._read_sql(**kwargs)
  File "lib/python3.6/site-packages/modin/data_management/factories.py", line 152, in _read_sql
    return cls.io_cls.read_sql(**kwargs)
  File "lib/python3.6/site-packages/modin/engines/ray/generic/io.py", line 509, in read_sql
    index_lens = ray.get(index_ids)
  File "lib/python3.6/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=26249, host=life)
  File "lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py", line 99, in _read_sql_with_limit_offset
    index = len(pandas_df)
TypeError: object of type 'generator' has no len()

**Comment by eavidan** [comment]
Hi @sumepr , thanks for reporting this !
This looks like a bug. We are missing support for `read_sql()` when `chucksize` is given and a generator is returned and not a `Dataframe`.
In the mean while, if what you need is to save chunks of the queries to different csv file, I suggest a work around using a while loop and adding dynamic `LIMIT` and `OFFSET` to you query at each iteration. Similar to the following:
```python
chunksize = 10
offset = 0
while True:
    df = pd.read_sql(sql="SELECT * FROM boston_housing LIMIT {} OFFSET {}".format(chunksize, offset), con=conn)
    if len(df) == 0:
        break
    df.to_csv("tmp-{}-{}.csv".format(offset, offset+chunksize-1))
    offset += chunksize
```

Let me know if this helps and thanks again for reporting !

**Comment by eavidan** [comment]
@devin-petersohn I was thinking about wrapping the `read_sql()` implementation with a generator for when `chucksize` is passed. We can use the OFFSET and LIMIT here as well. The question is where to place this code. If in `modin.pandas.io` then it would look something like this
```
_, _, _, kwargs = inspect.getargvalues(inspect.currentframe())
    if chunksize is not None:
        kwargs["chunksize"] = None

        def query_iterator():
            offset = 0
            while True:
                kwargs["sql"] = "SELECT * FROM ({}) LIMIT {} OFFSET {}".format(sql, chunksize, offset)
                offset += chunksize
                df = DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
                if df.empty:
                    break
                else:
                    yield df

        return query_iterator()

    return DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
```
Does this makes sense?
If so, where would you suggest to place this code?

**Comment by devin-petersohn** [comment]
@eavidan There is one other option for putting the logic in `modin.pandas.io`. I'll lay out here so we can evaluate probably.

```python
_, _, _, kwargs = inspect.getargvalues(inspect.currentframe())
kwargs["chunksize"] = None
df = DataFrame(query_compiler=BaseFactory.read_sql(**kwargs))
if chunksize is not None:
    num_chunks = len(df) // chunksize if len(df) % chunksize == 0 else len(df) // chunksize + 1
    return (df.iloc[i * chunksize: (i + 1) * chunksize] for i in num_chunks)
else:
    return df
```

This would establish the connection to the database once and read once. The downside of this approach is that the number of partitions won't be the same. Often people use `chunksize` when they are manually parallelizing their code, so I am not sure that we need to be worried about the number of partitions.

We could handle the chunksize argument for all readers this way. Currently on all readers we default to pandas for the `chunksize` argument. Do you have thoughts on this approach?

**Comment by eavidan** [comment]
@devin-petersohn this sounds like a good solution, assuming that the chucks are indeed small enough and will not benefit from partitioning as well. My only thought is that, hypothetically, reading in chucks should not have an effect on scalability. I do agree that usually reading chunks is done by people who want to parallelizing their code, and in this case defaulting to pandas makes sense as well.
I was thinking that if I have a huge data set that I would like to read in chunks, since my cluster (or super computer) RAM is simply not enough. I would like those huge chunks to get the benefits of Modin partitioning.
This could be a stretch, so we could start with simply defaulting to pandas, to resolve this bug, and add a more robust support later if needed.
what do you think?

**Comment by devin-petersohn** [comment]
I think that makes sense. The partitioning shouldn't be too big of an issue and the scalability of `.iloc` should be pretty good right now (although there is probably more that can be done here).

I like your suggestion to resolve the bug first, then decide after. We will probably want a separate issue to track that.

**Comment by devin-petersohn** [comment]
Closing via #920. #923 was opened to track supporting this feature without defaulting to pandas.
