### ISSUE TITLE
segfault on read_parquet

### ISSUE THREAD

**Issue by shgoren** [modin-project/modin#912]
## System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16.04.2
- **Modin installed from (source or binary)**:
with pip install modin[ray]
- **Modin version**:
0.6.3
- **Python version**:
3.6.5
- **Exact command to reproduce**:
read_parquet()

### Describe the problem
I tried reading a parquet file with modin.pandas inside a Jupyter Notebook and failed due to segmentation fault

### Source code / logs
pd.DataFrame(np.random.randint(1,10,(3,3)), columns=["a","b","c"]).to_parquet("example.pqt")
pd.read_parquet("example.pqt")

error stack:
(pid=4065) Fatal Python error: Segmentation fault
(pid=4065) 
---------------------------------------------------------------------------
RayWorkerError                            Traceback (most recent call last)
<ipython-input-94-f02937e4c096> in <module>
      1 pd.DataFrame(np.random.randint(1,10,(3,3)), columns=["a","b","c"]).to_parquet("example.pqt")
----> 2 pd.read_parquet("example.pqt")

~/shahaf_env/lib/python3.6/site-packages/modin/pandas/io.py in read_parquet(path, engine, columns, **kwargs)
     25     return DataFrame(
     26         query_compiler=BaseFactory.read_parquet(
---> 27             path=path, columns=columns, engine=engine, **kwargs
     28         )
     29     )

~/shahaf_env/lib/python3.6/site-packages/modin/data_management/factories.py in read_parquet(cls, **kwargs)
     42     @classmethod
     43     def read_parquet(cls, **kwargs):
---> 44         return cls._determine_engine()._read_parquet(**kwargs)
     45 
     46     @classmethod

~/shahaf_env/lib/python3.6/site-packages/modin/data_management/factories.py in _read_parquet(cls, **kwargs)
     46     @classmethod
     47     def _read_parquet(cls, **kwargs):
---> 48         return cls.io_cls.read_parquet(**kwargs)
     49 
     50     @classmethod

~/shahaf_env/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in read_parquet(cls, path, engine, columns, **kwargs)
    212         # column.
    213         dtypes_ids = list(blk_partitions[-1])
--> 214         dtypes = pandas.concat(ray.get(dtypes_ids), axis=0)
    215         if directory:
    216             if len(partitioned_columns) > 0:

~/shahaf_env/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayWorkerError: The worker died unexpectedly while executing this task.

**Comment by devin-petersohn** [comment]
Hi @shgoren thanks for posting!

Does this happen every time you run it? Sometimes Ray crashes and the fix is just to restart the kernel and try again.

**Comment by aregm** [comment]
Please, recheck and close.

**Comment by dchigarev** [comment]
Reproducer above started to work with Ray version >= 0.8.1

Current Modin master uses 0.8.7 Ray Version, so that bug is fixed
