### ISSUE TITLE
Modin defaulting to pandas implementation on Windows. 

### ISSUE THREAD

**Issue by DerekLW6** [modin-project/modin#917]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Microsoft Windows 10 Pro, Dell XPS 15 9570

- **Modin installed from (source or binary)**:
Modin Installed via Anaconda 

- **Modin version**:
0.6.2

- **Python version**:
Python 3.7.5

- **Exact command to reproduce**:
import numpy as np
import modin.pandas as pd
df = pd.read_csv(“file”) #Note – file is saved in the same directory as the jupyter notebook. 

### Describe the problem
Reading in a 392MB csv file modin (running on Dask) is defaulting to the pandas implementation.

**Comment by devin-petersohn** [comment]
Dask `read_csv` was recently implemented as a part of Modin 0.6.3. `pip install -U modin` should fix it. Let me know if this works for you!

**Comment by DerekLW6** [comment]
🤦‍♂️ Thanks Battle



Sent by my Phone
Respectfully,

Derek Wales
Duke MIDS Student Class of 2021
Cell: 334.750.7507<tel:334.750.7507>
"Be strong to be useful"



-------- Original message --------

**Comment by devin-petersohn** [comment]
@DerekLW6 I deleted part of your comment that contained personal information since these comments are public.

**Comment by DerekLW6** [comment]
It worked! Thanks man.

Respectfully,

Derek Wales
Duke MIDS Student Class of 2021
Cell: 334.750.7507
"Be strong to be useful"

**Comment by devin-petersohn** [comment]
Closing as resolved.
