### ISSUE TITLE
convert dataframe

### ISSUE THREAD

**Issue by qitianliang** [modin-project/modin#921]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**:
- **Modin version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by qitianliang** [comment]
how to convert a standard pandas dataframe to modin pandas dataframe

**Comment by devin-petersohn** [comment]
You can pass it to the constructor:

```python
# some pandas DataFrame (pandas_df)
import modin.pandas as pd
modin_df = pd.DataFrame(pandas_df)
```

Do you mind to share how you'd like to use it?
