### ISSUE TITLE
Improve performance of narrow dataframes

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#946]
### Describe the problem

Currently, we limit the parallelism for narrow dataframes. This was initially done in an effort to improve the performance of small dataframes, but arbitrary decisions were made that leave performance on the table for more narrow dataframes.

By narrow, I mean `1 < len(df.columns) <= 32`. 32 is the limit we chose for the minimum number of rows/columns to avoid having a large amount of tiny dataframes in the partitions. For column partitioning, I think it is okay to have a single column within a partition, but performance profiling will be necessary to verify this hypothesis.

Marking as good first issue, if you put in a PR, please make sure you include performance numbers for a variety of dataframe widths.

### Source code / logs

Link to source code where default is set: 
https://github.com/modin-project/modin/blob/308fd5236b778e6092b03196c92086ef6e746fbc/modin/data_management/utils.py#L20

The default probably just needs to be turned off for `col_chunksize`.

**Comment by devin-petersohn** [comment]
After running performance tests myself, narrow dataframes I can report some numbers:

Consistent behavior with 4 columns, {5 million, 1 million} rows
```
Reductions/Groupby:
	- 2-3x faster to keep column partitions larger
Map:
	- 6x faster to keep column partitions larger
Column partition operations (e.g. median):
	- 2x slower to keep column partitions larger
```

More testing is needed, there may be some way to handle partitioning more intelligently because it seems that it is not always in our best interest to partition for more parallelism.

**Comment by discdiver** [comment]
@devin-petersohn 
Thank you for your work on Modin! I'm testing out Modin and didn't realizing narrow DF might be the issue why things aren't going smoothly.

Reading in 100,000,000 rows x 3 columns floats NumPy array into a DataFrame with Ray as backend was impossible with Modin on my 16GB RAM MacBook, and took far less than a second in pandas. After writing the file to CSV with pandas, reading it in with Modin took 106 seconds vs. 61 seconds with pandas. I also tested in the cloud with Deepnote and Modin with Ray and Dask backends didn't work. 

Am I missing something? If it's just the case that Modin isn't good for really narrow DataFrames, I think that should be stated upfront. So folks can quickly find the right too for the job.

**Comment by discdiver** [comment]
Following up on the above comment, Modin with Dask was able to read in the 100,000,000 rows x 3 columns of floats csv in 53 seconds. So there was a little boost there. 👍

**Comment by devin-petersohn** [comment]
@discdiver I cannot reproduce the numbers you are seeing. I think it is worth opening a new issue because what you are seeing would not be affected by the changes proposed here. This is a performance tuning issue for dataframes that have already been ingested.

Based on what you said, here is what I am seeing on a 2013 4-core iMac:

```
In [1]: import modin.pandas as pd                                                                                                                                                           

In [2]: import numpy as np                                                                                                                                                                  

In [3]: arr = np.random.uniform(low=0.0, high=100.0, size=(100_000_000, 3))                                                                                                                 

In [4]: arr                                                                                                                                                                                 
Out[4]: 
array([[83.50074335, 36.53988716, 33.88572563],
       [98.22207008, 91.91693515, 36.44056617],
       [55.93528592, 21.85161031, 25.69569814],
       ...,
       [38.92105634, 71.55563561, 96.26778243],
       [84.99028293, 82.07808505, 82.68538043],
       [ 8.45163629, 43.76632399, 78.50019794]])

In [5]: %time df = pd.DataFrame(arr)                                                                                                                                                        
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
CPU times: user 1min 14s, sys: 14.9 s, total: 1min 29s
Wall time: 1min 24s

In [6]: df.to_csv("test_100mx3.csv")                                                                                                                                                        
UserWarning: `DataFrame.to_csv` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.

In [7]: %time df = pd.read_csv("test_100mx3.csv")                                                                                                                                           
CPU times: user 3.72 s, sys: 8.2 s, total: 11.9 s
Wall time: 27.3 s
```

Fresh environment

```
In [1]: import modin.pandas as pd                                                                                                                                                           

In [2]: %time df = pd.read_csv("test_100mx3.csv")                                                                                                                                           
CPU times: user 3.03 s, sys: 4.84 s, total: 7.87 s
Wall time: 18.1 s

In [3]: import pandas                                                                                                                                                                       

In [4]: %time df = pandas.read_csv("test_100mx3.csv")                                                                                                                                       
CPU times: user 37 s, sys: 5.07 s, total: 42.1 s
Wall time: 41.4 s
```
