### ISSUE TITLE
Add Python 3.8 to CI

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#972]
### Describe the problem

We should test Python 3.8 in the CI and master builds. Recently, several issues have popped up related to Python 3.8 specifically, so it's good to test. I'm hesitant to add prior to the next release because I just did a big overhaul of the CI and GitHub Actions seems to be throttling the builds.

**Comment by devin-petersohn** [comment]
Inherited from #853

**Comment by devin-petersohn** [comment]
Python 3.8 is not supported by Ray

**Comment by anmyachev** [comment]
We are testing Python 3.8 in CI now.
