### ISSUE TITLE
Update pandas API to 1.0

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#981]
### Describe the problem

pandas has a release candidate for v1.0.0. We need to run some tests to make sure that we can update and create a branch that is ready once the final release is cut.

### Source code / logs

https://github.com/pandas-dev/pandas/releases/tag/v1.0.0rc0

**Comment by gabriel19913** [comment]
Hi @devin-petersohn just to know the modin latest version are not yet working with pandas 1.0.1 right?

**Comment by devin-petersohn** [comment]
Not yet, I started the changes yesterday. There are a lot of them, but I'll make sure it's out by the next release.

Most of the changes are not directly seen by the user, but some are. Is there a functionality that you need from pandas 1.0 that 0.25 doesn't include?

A lot of the changes are testing related, so I'd like to make sure we're still testing properly.

**Comment by gabriel19913** [comment]
Thaks for your reply.
I don't need anything specific from pandas 1.0.
I was just trying to install modin today and it gave me a error message because of that.
So I came here to ask what is the status of this.

Thank you for your work.
I am lookin forward fo the new release.

**Comment by devin-petersohn** [comment]
Unfortunately I forgot to label this and it slipped because other high-priority bugs took its place. It will be pushed to the next release.

**Comment by devin-petersohn** [comment]
Resolved by #1081
